### ISSUE TITLE
FEAT: Additional keyboard shortcuts

### ISSUE THREAD

**Issue by PHLAK** [beekeeper-studio/beekeeper-studio#1000]
**Is your feature request related to a problem? Please describe.**

I rely on keyboard shortcuts to speed up my workflows and there are many missing shortcuts I'd like to see added.

**Describe the solution you'd like**

I would like the following additional keyboard shortcuts added.

##### Connection

  - <kbd>Ctrl</kbd> + <kbd>Q</kbd> - Disconnect from current connection
  
##### Table Tab

  - <kbd>Ctrl</kbd> + <kbd>N</kbd> - Add row to table
  - <kbd>Ctrl</kbd> + <kbd>R</kbd> - Refresh table
  - <kbd>Ctrl</kbd> + <kbd>S</kbd> - Save pending changes

**Additional context**

Ideally these would be exposed to the user to customize but that can come later. As a first-pass just adding the suggested shortcuts would suffice for my needs.

Also, I'm sure there are additional actions that could use keyboard shortcuts but these are the ones particularly useful to me.

**Comment by PHLAK** [comment]
Just realized some of the same shortcuts were requested in #803

**Comment by rathboma** [comment]
Yes these are sensible! I'll be working on this stuff soon :+1:

**Comment by PHLAK** [comment]
Just noticed another thing today. I believe the "Run" vs "Run Current" shortcuts should be reversed in the (free form) query editor. That is, today the keyboard shortcuts are

  - <kbd>Crl</kbd> + <kbd>Enter</kbd> - Run (all)
  - <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>Enter</kbd> - Run current

and I believe they should be switched to

  - <kbd>Crl</kbd> + <kbd>Enter</kbd> - Run current
  - <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>Enter</kbd> - Run (all)

The reasoning behind this is that in other applications <kbd>Crl</kbd> + <kbd>Enter</kbd> is the default shortcut for "do something" (e.g. post a form in a web browser, etc.) and I believe in most situations where there are more than one query in the editor the default desired behavior would be to run the _currently highlighted_ query only, not _all_ queries. In fact, running all queries by default could be a dangerous action.

**Comment by rathboma** [comment]
So I'm not sure about the ctrl-enter stuff, but I'm adding the table keyboard shortcuts (ctrl+r, etc)
