### ISSUE TITLE
FEAT: detailed view for a row

### ISSUE THREAD

**Issue by benediktms** [beekeeper-studio/beekeeper-studio#1002]
**Is your feature request related to a problem? Please describe.**
For tables that have a large number of columns, it can sometimes be clunky to view specific data, especially when you need to view data from multiple columns at the same time

**Describe the solution you'd like**
It would be nice to be able to select a column and view it in some sort of details mode, where the columns could actually be displayed as rows, in a vertical manner so it's easy to see all the content at once.

**Describe alternatives you've considered**
The alternative would be to write a query only for the fields you want, but then you'd have to re-write the query every time your needs change so it's not really a good solution.

**Additional context**
DBeaver has a feature that let's you select a single record and get a detailed view for it:
![image](https://user-images.githubusercontent.com/48836135/151564856-6eefed80-317a-4299-973c-9c668fa75fc6.png)
![image](https://user-images.githubusercontent.com/48836135/151565021-f296869b-0818-4d0a-86c2-ec14389fb5d8.png)

It would be great if Beekeeper Studio had a similar feature :slightly_smiling_face: 

**Database type, if appropriate**
All DBs

**Comment by stalingino** [comment]
This detailed view can be added to right side panel & can change data as we select different rows.

**Comment by rathboma** [comment]
Yep, that's exactly the plan!

Something like this:
![TableTable Details](https://user-images.githubusercontent.com/279769/151823141-14cc27ac-3aec-4519-aaba-527b42e72fa1.png)

**Comment by stunaz** [comment]
That's a killer feature... especially for huge table.
its maybe not related, but it would be great to have a _value_ in the side panel,  i.e. to be able to see the whole value of a column in the side panel. A good use-case its when the field is a json type field, it helps a lot to see the json value in the side panel.  (dbeaver and jetbrains) has it.

**Comment by sunnz** [comment]
+1 this is the only feature I miss from table plus, bee keeper would be THE GOLDEN database manager

![image](https://user-images.githubusercontent.com/1378551/190359142-b3ecf762-bf8a-4bcf-9958-3d5b8e02acd2.png)

**Comment by faysal515** [comment]
+1 @sunnz I'd love something like this. or at least a tree view. with shortcuts to switch to different views

**Comment by pastudan** [comment]
Is there any progress on this so far? I'd love to try and contribute this feature, especially if there's already a WIP branch.

Like others said, this is the _only_ feature I miss from other gui db tools :)
