### ISSUE TITLE
BUG: PostgreSQL jsonb column names do not appear

### ISSUE THREAD

**Issue by trichask** [beekeeper-studio/beekeeper-studio#1004]
**Describe the bug**
When using the postgresql connection, jsonb column names do not appear when browsing the table

![image](https://user-images.githubusercontent.com/1044231/151791750-b9cd7046-4025-45d6-9d58-17f4973114a0.png)

**Comment by trichask** [comment]
- I am using postgreSQL version 13 (from the docker image `postgres:13`)
- Heres a sample sql:

```
CREATE TABLE orders (
    id serial NOT NULL PRIMARY KEY,
    info json NOT NULL
);
```

```
INSERT INTO orders (info)
VALUES('{ "customer": "John Doe", "items": {"product": "Beer","qty": 6}}');
```

**Comment by onurkose** [comment]
I can also report this problem happening on Mysql 5 for json columns.

**Comment by rathboma** [comment]
Hmm, I cannot replicate this with postgres 13. This is what I see (on master):

![image](https://user-images.githubusercontent.com/279769/153951681-726fdc00-9e8c-4b31-818e-fc59798eadc9.png)

**Comment by rathboma** [comment]
@trichask Are there any errors in the developer console? See Help -> show developer tools

**Comment by rathboma** [comment]
@onurkose can you also check developer tools and see if there is any output there?

**Comment by oxycoder** [comment]
@rathboma Try switch to light theme, it only happen with light theme. Dark theme work fine.

**Comment by rathboma** [comment]
fixed this. the title is actually there, but the style was applied to `sortable` columns only, and jsonb columns are not sortable!
