### ISSUE TITLE
BUG: Query editor stops working

### ISSUE THREAD

**Issue by m4r-bvrv** [beekeeper-studio/beekeeper-studio#1005]
**Describe the bug**
Query editor stops working after closing unsaved query.

**To Reproduce**
1. Have saved query open in a tab.
2. Open a new query editor in another tab.
3. Write anything in the newly opened tab.
4. Close the tab without saving the changes.
5. Go back to the first tab with the saved query open.
6. Editor won't work.

**Expected behavior**
You can freely edit any query after closing unsaved ones.

**Version Information (please complete the following information):**
 - OS: Windows 10
 - App Version: 3.1.0
 - Database type and version: Postgresql 11.12

**Comment by rathboma** [comment]
This is fixed!
