### ISSUE TITLE
I can't seem to be able to query and save the table using the typical "create table" statement

### ISSUE THREAD

**Issue by learningbymodeling** [beekeeper-studio/beekeeper-studio#1007]
**Details:**
Hello I am querying a table while trying to save the output as a new table and I keep getting a syntax at or near SELECT.
My query is simply:
```
CREATE TABLE XX.table_x
SELECT *
FROM XX.table_all;
```

**Version Information [might be relevant to your issue]**
Operating System: Windows 2016
App Version [help -> about]: 3.1.0
Database type and version: Posgresql 12.3

Thank you!

**Comment by learningbymodeling** [comment]
i just realized I forgot the "as" *facepalm*

**Comment by rathboma** [comment]
Glad you worked it out!
