### ISSUE TITLE
FEAT: Multiple Filters

### ISSUE THREAD

**Issue by PHLAK** [beekeeper-studio/beekeeper-studio#1009]
**Is your feature request related to a problem? Please describe.**

When filtering a table I often wish to filter by multiple columns.

**Describe the solution you'd like**

The ability to add multiple filters. Ideally this would be a button to let me add another filter that would be applied in addition to the first.

**Additional context**

This is inspired by TablePlus, you can see mutliple filters in their documentation [here](https://docs.tableplus.com/gui-tools/filter).

**Comment by rathboma** [comment]
So there is a button that switches the filter to 'sql mode', that allows you to enter as many filters as you like.

For now this is the 'multi filter' solution. Going to close the issue, not because I don't care about this, but with my limited time there are just so many other things to prioritize.

**Comment by rathboma** [comment]
Ok, I'm going to re-open this. I think we should do it.

Some notes for implementation:
- When switching from multiple filters -> SQL it should try to convert the filters to SQL
- When switching back, it should keep the filters if the SQL wasn't modified (so if you wanna just see what the button does), but discard the filters if the SQL is edited
- It should 'look nice' on the table view and feel natural, no weird scroll areas

**Comment by azmy60** [comment]
I came across some good examples from google images lol. This is one of them. @rathboma Do you think something like this would work?

![googled it](https://blog.coupler.io/wp-content/uploads/2023/06/image-15-1024x536.png)

It has AND / OR conditions. It's a popup that sits right after the filter button. For us, we could probably use a dialog that shows in the center of the screen like Column Filter.

**Comment by rathboma** [comment]
@azmy60 Make sure you `git pull` before working on this, as I changed that part of the tabletable last week to accomodate row selection.

I think for now just keep things simple and functional. I don't want to totally redesign that part of the view right now.

In the future we can do a full redesign -- I have an idea of how it should look when we get there.
