### ISSUE TITLE
Website has wrong canonical tag

### ISSUE THREAD

**Issue by schliflo** [beekeeper-studio/beekeeper-studio#101]
Didn't know where to report this, but your website has an incorrect canonical tag: 
```html
<link rel="canonical" href="https://beekeeper-studio.com" />
```
This breaks native link sharing in mobile browsers (canonical link is shared instead of the one in the URL bar), as the domain there is not resolved any longer.
I suggest fixing the tag and adding a redirect from `beekeeper-studio.com` to `beekeeperstudio.io`

**Comment by ghstng** [comment]
rgr, thanks
