### ISSUE TITLE
BUG: Sometimes text entry boxes stop taking input

### ISSUE THREAD

**Issue by BrianPittVP** [beekeeper-studio/beekeeper-studio#1010]
**Describe the bug**
I am on Windows 11, so that could be part of the problem, but I've noticed that sometimes, for no apparent reason, I am no longer able to click into a text box and type.  This includes filtering the list of DB tables or filtering within a table.  The cursor turns into the bar, but clicking does nothing.  I am, however, able to click the **x** to clear the search text.

So far, the only solution I know of is it restart the app.

**Version Information**
```
Processor	11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz   2.30 GHz
Installed RAM	16.0 GB (15.7 GB usable)
System type	64-bit operating system, x64-based processor
OS 		Windows 11 Pro
Version		21H2
OS build	22000.434
Experience	Windows Feature Experience Pack 1000.22000.434.0
---
App Version:	3.1.0
Database:	MySQL v14.14 Distrib 5.7.33
```

**Comment by rathboma** [comment]
This is fixed in the latest version!
