### ISSUE TITLE
FEAT: Filter and reorder columns

### ISSUE THREAD

**Issue by bediu** [beekeeper-studio/beekeeper-studio#1018]
**Is your feature request related to a problem? Please describe.**
I have two problems: 
* Some columns tend to have big (jsond) data which slow beekeeperstudio down. These big data columns are absolutely unnecessary in the visual table almost all the time.  
* A lot of columns are purely functional/meta, I have basically never interacted with 90% of my columns through beekeeper studio

**Describe the solution you'd like**
The ability to ignore columns. But not just ignore them visually. It would be nice if beekeeper studio ignored it when communicating with the database as well -- this would make the app so much smoother when working with big data. 

The ability to re-arrange columns. I have asked about this feature before. This is very necessary. It is very poor UX to always scroll horizontally past 20 columns you rarely touch, just to access a target column! 

**Describe alternatives you've considered**
I haven't considered alternatives. The other tools try too hard, the beauty of beekeeper studio is simplicity compared to the rest of the monoliths out there and that is why I believe these feature requests will only add to the feeling of why people choose beekeeper studio over, say, dbweaver.

**Additional context**
Beekeeper studio has always been open in my taskbar for over half a year now. Please consider adding these power user features. 

**Database type, if appropriate**
Postgresql

**Comment by azmy60** [comment]
@rathboma I'll try to make PR for the filter. It will look similar to this.
![Screenshot_2022-07-18_15-13-52](https://user-images.githubusercontent.com/38707148/179471763-6b80cc07-e20f-4abd-aa48-b89c9edc04bc.png)

**Comment by bediu** [comment]
@azmy60 I'll buy you a beer if this PR makes it in next version
