### ISSUE TITLE
FEAT: Warn users that sorting or filtering will discard pending changes

### ISSUE THREAD

**Issue by anon2573** [beekeeper-studio/beekeeper-studio#1019]
**Describe the bug**
When adding data to a database and then click any column all pending changes are lost

**To Reproduce**
1. Create new Table
2. Select Table
3. Click 'Add row' a couple of times
4. Add data to rows
5. Click on any column

**Expected behavior**
Either only existing data gets sorted by column and changes stay on top (maybe in themselves sorted by column).
Or pending changes are mixed with existing data sorted by column
Or a warning appears that this will discard your pending changes with an option to cancel

**Comment by ptitan** [comment]
Same here on Ubuntu 18.04, snap package...

**Comment by rathboma** [comment]
Agreed, this is a current limitation of the editing system.

I think the easiest is that it warns you that sorting or filtering will discard your pending changes (or maybe disable those features with a tooltip.)
