### ISSUE TITLE
Open new tab query is incorrect

### ISSUE THREAD

**Issue by thellimist** [beekeeper-studio/beekeeper-studio#102]
For postgres `Open new tab` fails. I have a table called `user` and I'm guessing the SQL fails to bring the results. It just shows a red "Error" in the UI.

The reason might be generated SQL is `SELECT * FROM tableName`, however, it should be `SELECT * FROM "tableName"` with the quotes.

Other tables work fine. I'm guessing it's because `user` is a reversed key and a table named the same would create an issue.

I might be incorrect. Let me know if you need more info

![image](https://user-images.githubusercontent.com/6690196/81492595-9db32080-92cb-11ea-813e-594c60f8a4cb.png)

**Comment by rathboma** [comment]
yep! I have a fix for this in Master, and it will be in a new release this week! See #82
