### ISSUE TITLE
FEAT: Keyboard Tab Support & Better Support to Edit Stored Procs

### ISSUE THREAD

**Issue by jerrybrown5** [beekeeper-studio/beekeeper-studio#1021]
I love BeeKeeper! What an amazing find! As a database programmer I could see this as being one of my primary tools!

--But IMO it does need a little TLC (little tender loving care) to make it the best fast and simple (but deceptively powerful) db tool ever--

Tree View Pane:

* The entity objects should be grouped by type (not just sorted) in the left tree view (eg Tables; Views, Funcs, Procs)

* The SQL: Create right click option is great but so would a SQL: Alter

* Double clicking on a Stored Procedure (or even a function) could open sql to run it. Instead of asking for parameters you could just include the type in a small comment after the exec sql.

* I like the full screen view but that only hides the left top level menu options which can be compressed anyway. I believe the full screen view should hide the left side tree as well. 

* The top level menu could be hidden by adding a hamburger icon above the far left side database icon (ala VS Code). Space is precious when coding.

* The left side tree menu is limited to how narrow it can be. IMO I don't think programmer tools should try be smarter than the programmers using it.

Top Right (SQL Edit) Pane:

* The top right sql edit view is also limited to how much it can be compressed. If you are concerned about users making it too narrow that the program is unusable IMO you can just make sure the layout gets reset  when you re-open it.

Regarding Tabs in Sql Edit Pane:

* Tabs should be definable in setup as to how many spaces they refer to 

* They do not get saved. 

* Tabs (should be definable in setup as to how many spaces they refer to) do not get saved. 

* If I correctly indent a proc and then save it and then go back in, everything is left aligned again.

(* Sql Server Management Studio also complains about the line endings being inconsistent If I open a procedure there after saving it here.)

Saved Queries:

It would great if saved queries could have folders

History:

It would be great if I could clear all history of have an option to not save it at all. This is a potential security nightmare having this sql be logged and be so accessible.

--

Ok, these are my $0.02. That being said I think you are on to something. This is becoming an amazing product!

Warmest,
Jerry

**Comment by rathboma** [comment]
Hey Jerry,

Thanks for all the amazing feedback! You can hide the sidebar by clicking the icon that is currently open! This is like how VSCode does it.

Lots to process here. I've categorized your points and created issues where appropriate

## Ripe for #197, tagging here:
- Tab sizes
- Tabs v Spaces
- Tabs v spaces auto-detect
- Whether to save query history
- Whether to show tables/views/etc in folders or just sorted (currently sorted)


## Possible Bugs (issues created and linked)
- Line endings for SQL Server
- Whitespace not getting saved (presumably in stored procedures)
- Top menu not hidden in full screen

## New features (issues created)
- tabs v spaces
- double click proc to run it

**Comment by rathboma** [comment]
@jerrybrown5 I'm going to close this issue because I've splintered into the other issues. But to be clear I'm closing the issue because it was AWESOME, and I've already broken it down, not because I don't agree with you :-). I just don't want to forget about what I did in a few weeks

**Comment by jerrybrown5** [comment]
Sure. I want to again repeat that you are creating an amazing piece of software. :)

Thank you!
