### ISSUE TITLE
QUESTION: Do you support Azure SQL DB connection?

### ISSUE THREAD

**Issue by s7angeorgiev** [beekeeper-studio/beekeeper-studio#1027]
**Details:**
Is it possible to connect to Azure SQL Database and also, to use Active Directory MFA authentication?

**Version Information [might be relevant to your issue]**
Operating System: Windows 10
App Version [help -> about]: 3.1.0
Database type and version [eg Posgresql 9.3]: Azure SQL Database

**Screenshot / GIF [if appropriate]**:
A screenshot of the app if that helps

**Comment by rathboma** [comment]
Hey! Right now MFA is not supported, so I don't think it really supports Azure SQL Database with MFA.

Certainly a good candidate for the future.

**Comment by rathboma** [comment]
Going to close this Q as I created an issue to explicitly track it.
