### ISSUE TITLE
Multiple connections open at the same time

### ISSUE THREAD

**Issue by mlebrun** [beekeeper-studio/beekeeper-studio#103]
It would be great if you could connection to multiple databases at the same time! If it's already possible, feel free to close with steps on how! The client looks great, though! Excited to see this software mature more!

**Comment by rathboma** [comment]
Hey! No, currently this is not possible (it was a trade off for being able to launch).

I'm on the fence about whether to enable this in a single interface, or to just allow users to open a new window

**Comment by mlebrun** [comment]
Even a new window would be fine! I also saw https://github.com/beekeeper-studio/beekeeper-studio/issues/63 ([Enhancement] Pick color for each connection to quickly distinguish them) and each window could somehow incorporate this label color. 

I think being able to open multiple connections and keep which is which accurate (to be able to compare stage/production values directly next to each other) are pretty much the only things stopping me from completely dropping Sequelpro, which WAS nice. But this UI is much cleaner, more support for other DBs, open source, etc. Just a couple of niceties missing!

**Comment by rathboma** [comment]
awesome feedback thanks! We'll definitely support this :-). Not sure when I'll get to implementing it though.

**Comment by nickabbooo** [comment]
Was about to create the same suggestion but realized on I could simply create a new window. Maybe after #225 switching between multiple connections will be a breeze. Really love how clean the UI. I'm using Ubuntu so the UI is WAY BETTER compared to other clients. Excited to see more! :D

**Comment by ghstng** [comment]
v1.6

**Comment by phillpafford** [comment]
Did this get implemented? If not how do I reopen this as this is a deal breaker for me to use this as my main application.

**Comment by rathboma** [comment]
Hey! Mulitiple windows for multiple connections work as expected. We'll probably figure out a way to do multi-connections in the same window at some point, but for now this works fine.

**Comment by tyler-bobik** [comment]
+1

**Comment by Tubaleviao** [comment]
I think that we already have the issue #576 talking about multiple connections in the same window, so maybe this one doesn't need to be reopened
