### ISSUE TITLE
BUG: Changing saved connections sorting doesn't actually change the order

### ISSUE THREAD

**Issue by luisfix** [beekeeper-studio/beekeeper-studio#1032]
**Describe the bug**
When viewing Saved Connections and changing the sorting order, the order never changes.

**To Reproduce**
1. Open the app
2. Top left, Saved Connections, click the Sorting Icon and pick any option
3. Order doesn't change

**Expected behavior**
The order should change when changing sorting order

**Screenshots / Gifs**
![image](https://user-images.githubusercontent.com/90848314/153844015-2a705e53-7528-45d3-8e13-656513f22cb7.png)

![image](https://user-images.githubusercontent.com/90848314/153844250-b93036bd-4ae2-4af8-85fd-490e7057ec12.png)

**Version Information (please complete the following information):**
 - OS: Mac, Monterey 12.2.1
 - App Version: 3.1.0
 - Database type and version: not needed (I think)

**Comment by rathboma** [comment]
This is fixed in the latest version!
