### ISSUE TITLE
QUESTION: Does not return records from table

### ISSUE THREAD

**Issue by bbedyukh** [beekeeper-studio/beekeeper-studio#1033]
**Details:**

- Create a MariaDB connection.
- I searched for the necessary database.
- I looked up the table, double clicked and it doesn't return the records.

Instead, if I perform a query, it works for me.

`SELECT * FROM messenger;`

Would they know what was going on?

**Version Information [might be relevant to your issue]**
Operating System: Ubuntu 20.04.3 LTS
App Version [help -> about]: 3.1.0
Database type and version: Server version: 10.3.27-MariaDB-0+deb10u1 Debian 10

**Screenshot / GIF [if appropriate]**:
![1](https://user-images.githubusercontent.com/44715973/153902195-697b0746-8a43-49d2-b18f-0f3479e782ec.png)
![2](https://user-images.githubusercontent.com/44715973/153902207-7b74d6b1-34b5-4602-a3d3-dea463e49e5f.png)

**Comment by rathboma** [comment]
@bbedyukh Very intesresting.

Happy to investigate. Couple of things to help:

1. Open the dev tools (help -> show developer tools), and see if there's an error you can take a screenshot of
2. If possible, could you provide me with the `CREATE TABLE` for the table and an example `INSERT` to help me replicate it?

**Comment by bbedyukh** [comment]
Hi how are you doing?

Sorry for the delay.

I tried again and magically it worked. I do not understand why.

Finally, problem solved.

Thanks,
Greetings.
