### ISSUE TITLE
BUG: Unable to boot with Fedora libva error

### ISSUE THREAD

**Issue by matdave** [beekeeper-studio/beekeeper-studio#1034]
**Describe the bug**
The application is unable to boot in Fedora 35 with Nvidia GPU

**Logging**
./Beekeeper-Studio-3.1.0.AppImage 
11:04:48.024                     › initializing background
running migrations
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[9842:0214/110449.975335:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)

**Temporary Solution**
I am able to get it to run if i add the argument ` --in-process-gpu` 

**Version Information (please complete the following information):**
 - OS: Fedora release 35 (Thirty Five) x8
 - App Version 3.1.0
 - Nvidia Driver 510.47.03

**Comment by rathboma** [comment]
I think this is related to Wayland, judging by the internet breadcrumbs I see. Something about Chromium not supporting something but the driver not knowing what to do.

**Comment by rathboma** [comment]
eg - https://bugzilla.redhat.com/show_bug.cgi?id=1491186

There should be a way to run Beekeeper Studio natively in Wayland (not XWayland) soon as that is merged into upstream chromium now I think

**Comment by rathboma** [comment]
Don't think there's really much I can do until then.

**Comment by rathboma** [comment]
Oh yeah Nvidia is notorious for terrible wayland support. I don't think they even supported wayland in their drivers until 2022.

I'd suggest running your desktop with X for a while if you're using Nvidia drivers.

Going to close this issue as I don't think I can really debug this.

**Comment by rathboma** [comment]
@matdave there will be a linux build created as part of #1094 - can you test that and let me know if it fixes the issue?

**Comment by Apakottur** [comment]
Just adding that I've just encountered the error on a fresh install of Ubuntu 22.04 with NVIDIA driver 510 on app version 3.2.1.

**Comment by Vam-Jam** [comment]
You can get it to run on wayland by adding in some arguments. 

```
--no-sandbox --ignore-gpu-blocklist --disable-features=UseOzonePlatform --enable-features=VaapiVideoDecoder --use-gl=desktop --enable-gpu-rasterization --enable-zero-copy
```
