### ISSUE TITLE
BUG: SQL: Create - wrong order (postgres db)

### ISSUE THREAD

**Issue by jonas-hoebenreich** [beekeeper-studio/beekeeper-studio#1048]
**Describe the bug**
I like the feature that Beekeeper Studio can export the structure of a table as a create statement. However, with my postgres database the order of the columns is exactly the wrong way around, with mysql it works.

**To Reproduce**
1. open postgres db
2. Right click on a table "SQL: Create"
3. Compare order of columns

**Expected behavior**
Order of columns is the same in both cases

**Screenshots / Gifs**
![image](https://user-images.githubusercontent.com/64426524/154808938-ba8c36d4-ce90-4a4a-9c89-ec2d48860ab3.png)

**Version Information (please complete the following information):**
 - OS: Linux, Ubuntu 20.04
 - App Version 3.1.0
 - Database type and version PostgreSQL 14.1 on aarch64-unknown-linux-gnu, compiled by gcc (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0, 64-bit

**Additional context**
Thanks for this great piece of software. I used Datagrip before (€200 / year!) but prefer Beekeeper :)

**Comment by rathboma** [comment]
Ah yes, very interesting. Thanks for the heads up.

**Comment by rathboma** [comment]
this is fixed.
