### ISSUE TITLE
BUG: Schema support for MSSQL

### ISSUE THREAD

**Issue by benaunt** [beekeeper-studio/beekeeper-studio#1049]
**Describe the bug**
Have connected to a MSSQL database with multiple Schemas, when attempting to edit a table structure via Beekeeper studio that is not within the dbo schema the editor appears to only attempt to find the table in dbo.

**To Reproduce**
Eg:
Two schema:

- dbo
- ContractorApplication

Create table staff within schema ContractorApplication, this works
Right click the staff table and select data, this works
Right click the staff table and select view structure, fails with the below error:

"The object dbo.Staff does not exist in the database 'db name' or is invalid for this operation.

It appears when selecting view structure the command it sends only passes the dbo schema name.

**Expected behavior**
When selecting to view structure of a table within any schema, it loads that schemas table

**Version Information (please complete the following information):**
 - OS: Windows 10
 - App Version : 3.2.0
 - Database type and version: Microsoft SQL Server 14.0.2

**Comment by rathboma** [comment]
Interesting, is the schema not shown in the sidebar?

Can you share some screenshots of the UI or error messages?

**Comment by benaunt** [comment]
As requested:

![beekeeper error](https://user-images.githubusercontent.com/83434591/155033839-5d729dd9-b38f-4956-95fe-bb850d284015.png)
