### ISSUE TITLE
FEAT: Connection info in Application title

### ISSUE THREAD

**Issue by adhayward** [beekeeper-studio/beekeeper-studio#1052]
I often have multiple connections to different DB servers open. I'm very happy to keep multiple windows open for each connection but as every window is titled "Beekeeper-Studio" it can be difficult to identify the window I'm looking for without squinting to see the connection colour at the bottom of the preview. 

<img width="311" alt="image" src="https://user-images.githubusercontent.com/18305551/154924659-780c9350-3b22-41db-b359-d2719c778f8d.png">

If it could set the title to something like  "CONNECTION NAME - Beekeeper-Studio" it'd be far easier to identify the window I'm looking for.

**Comment by rathboma** [comment]
Hah, yes agreed I've been thinking about this for a while.
