### ISSUE TITLE
FEAT: Support Azure SQL DB with MFA

### ISSUE THREAD

**Issue by rathboma** [beekeeper-studio/beekeeper-studio#1059]
From #1027

Explicitly support Azure SQL and MFA.

**Comment by jtourlamain** [comment]
Would love to have that feature and willing to pay for it in the ultimate

**Comment by rathboma** [comment]
@jtourlamain @subspacefield we just added support for SSO and EntraID to version 4.6+ (ultimate edition) -- Can you check it works for you?
