### ISSUE TITLE
Scroll bars too small and disappear on mac

### ISSUE THREAD

**Issue by saberworks** [beekeeper-studio/beekeeper-studio#106]
In the results pane, I would like to be able to have scroll bars always shown.  This would indicate that the result pane data has overflowed and that one should scroll to see the rest.  As it is, I have no idea unless I move my mouse there and the scroll bars magically appear.

In addition, the scroll bars on my mac (Mojave) are really really skinny.  I think the vertical scroll bar only has one pixel wide of click/draggable area.  If you go one pixel farther to the right it wants to resize the window and one pixel to the left and I can't grab the scroll bar.

The horizontal scroll bar actually disappears if I move my mouse to it.  It appears when the mouse enters the results pane (from the top/query area) but then disappears when I move down to try to click the scroll bar.  If I come at it from below the results pane I have a one-pixel opportunity to grab it.

I would recommend making the scroll bars significantly bigger and always visible.

**Comment by rathboma** [comment]
@ghstng thoughts about this?

**Comment by ghstng** [comment]
Certainly makes a good point -- I am of the mind, if enough people have an issue with this, I will make changes. As it currently stands, however, I will always push back on things I think make the app less visually appealing. Or perhaps it could be a setting.

**Comment by rathboma** [comment]
Fair. I do think in the result-pane the horizontal scrolling is a little hard -- as it's not bound to a mouse-wheel or a trackpad.

**Comment by saberworks** [comment]
Thank you for the responses.  Please consider the fact that the mouse scroll wheel and trackpad can supplement the scroll bars but they can't replace them.  The use cases I have for scroll bars (in general, not just this app) is when there is a lot of scrolling to do, it's really easy to glance at the scroll bar and see "how much content" there is (size of the bar in relation to the scrollable area), being able to jump page by page (clicking in the scroll bar area but not on the bar itself), and being able to quickly click & drag to a specific spot in the results.  These things are very difficult (on long result sets) with wheels and trackpads.

**Comment by rathboma** [comment]
Hey @saberworks, I understand your use case for sure. If we do make a change, it probably won't make it into this release. In the meantime, maybe some other folks will weigh in with opinions.

**Comment by ghstng** [comment]
Made scrollbar always visible with a slight increase in size. Ultimately, I think  a non-native scrollbar solution can find a better balance between being usable and not cluttering the app. Will put it on the list.
