### ISSUE TITLE
BUG: Color sorting should be ROYGBIV (or reverse), not alphabetical

### ISSUE THREAD

**Issue by PHLAK** [beekeeper-studio/beekeeper-studio#1065]
**Describe the bug**

When sorting connections by color they are sorted alphabetically by the _name_ of the color. For example.

  - Green
  - Orange
  - Purple
  - Red
  - Yellow

**To Reproduce**

Sort connections by color

**Expected behavior**

Connections should be sorted by ROYGBIV or VIBGYOR (reversed ROYGBIV). Ideally, whether or not this is reversed would be an option available to the user. 

**Screenshots / Gifs**
<table>
  <tr>
    <td><strong>Current</strong></td>
    <td><strong>Proposed</strong></td>
  </tr>

  <tr>
    <td>
      <img alt="Screenshot of colors sorted currently" src="https://user-images.githubusercontent.com/53531/155175587-3b828fb9-76d9-41be-b14b-bc56a9135cbc.png" width="66">
    </td>
    <td>
      <img alt="Screenshot of colors sorted by reverse ROYGBIV" src="https://user-images.githubusercontent.com/53531/155177074-6697335e-6470-4097-8362-1facb21218c8.png" width="66">
    </td>
  </tr>
<table>

**Version Information (please complete the following information):**

App Version: 3.2.0

**Additional context**

When assigning colors to a connection I will put the less critical/local connections towards the violet end of the color spectrum and the more critical/production connections towards the red end of the color spectrum. For example, from the screenshots above: My local development connection is purple. Our shared testing environment is green. Staging is yellow. Production is red.

Sorting by ROYGBIV or reverse allows this ordering to be more logical based on the colors assigned.

**Comment by rathboma** [comment]
Yes I think you're right here.

**Comment by PHLAK** [comment]
Thank you!
