### ISSUE TITLE
BUG: When trying to close an unsaved tab that it's not in the last position, closes the last tab instead

### ISSUE THREAD

**Issue by gonan-gl** [beekeeper-studio/beekeeper-studio#1071]
**Describe the bug**
Trying to close an unsaved tab that it's not in the last position, closes the last tab in the list instead of the one clicked on

**To Reproduce**
1. Open a few tabs and one of them is a custom SQL query
2. Move the tab with the custom SQL query to any position except the last one (the rightmost one)
3. Click on it with the mouse wheel to close it
4. The last tab is closed instead of the unsaved one

**Expected behavior**
it is expected that the clicked tab will close instead of the last one.

**Version Information (please complete the following information):**
 - OS: Mac Monterey (12.2.1)
 - App Version 3.2.0
 - Database type and version MySQL

**Comment by ctholho** [comment]
It's the same for me. I'm also on Monterey. Noticed this since the update to version 3.2.0 if i'm not mistaken but din't have the time to report yet.

**Comment by rathboma** [comment]
Good find. Thank you. I'm fixing now.
