### ISSUE TITLE
BUG: SSH Tunnel stops working

### ISSUE THREAD

**Issue by pakapor** [beekeeper-studio/beekeeper-studio#1073]
I've always been using DB connections over ssh tunneling all the time. Last week, it stopped working. I'm not sure if the error came right after some update or not but I do update regularly. 

I use Beekeeper on Windows 10 and ssh to MacOS BigSur. The DBs are postgres and mysql on Linuxes but I think the problem is on the tunneling step. 

**To Reproduce**
1. Goto edit any working connection.
2. enable SSH Tunnel and put the Hostname, Port, Use KeyFile or Password for authentication. (Try if the ssh works on terminal/Powershell first)
3. Click Test the connection

**Expected behavior**
It should connect.

**Screenshots / Gifs**
![image](https://user-images.githubusercontent.com/5183050/155656840-1c2b8045-873d-4fa7-819f-959bc056bbcb.png)

**Version Information (please complete the following information):**
 - OS: Windows 10 Pro 20H2 64-bit build 19042.1526
 - App Version 3.2.0
 - Postgres, mysql (many versions) : all work without SSH Tunnel

**Comment by rathboma** [comment]
Thanks for pointing this out. I'll take a look to see if I can replicate.

Yes this seems like an SSH timeout. 

Questions:
- Can you manually ssh fine to the same host with the same credentials?
- Any errors in the dev tools? Help -> Show developer tools

**Comment by pakapor** [comment]
Sorry for the late reply. The issue has gone before version 3.2.1 thank you.
