### ISSUE TITLE
Launched application does not have icon

### ISSUE THREAD

**Issue by ignissak** [beekeeper-studio/beekeeper-studio#108]
**System:** elementaryOS Hera 5.1 (Ubuntu 18.04 LTS)
**App version:** 1.2.0
**Description:** When I launch Beekeeper Studio that I installed from Snap Store it will have an icon, but another application is launched and this one does not have the icon. The one with the icon after a few seconds vanishes from the dock.
![image](https://user-images.githubusercontent.com/25119437/81649622-e46e5b00-9430-11ea-9f12-2c65ebcffabb.png)

**Comment by rathboma** [comment]
That is interesting. I've been annoyed by this in the past by other apps, and I thought I'd gotten it right, grrr.

**Comment by simonrob** [comment]
I have the opposite problem with the macOS version (1.3.0): there is no icon for the app in the applications folder, but there is one in the Dock when Beekeeper Studio is opened.

**Comment by rathboma** [comment]
lol, oh my.

Was the icon present with version 1.2? Trying to figure out if I broke something with Electron-builder.

**Comment by simonrob** [comment]
I didn't use Beekeeper Studio until the current release, but have just downloaded a few previous releases including 1.2 and there is no icon for the app in the disk images for any of them.

It could be just me experiencing this I suppose, but all my other applications have proper icons so I think that's probably unlikely. Let me know if you need any more information to help locate the cause.

**Comment by k3rni** [comment]
confirming with 1.3 on Manjaro 
![image](https://user-images.githubusercontent.com/200996/81956140-3f5baa00-960b-11ea-8956-338e6dc55f05.png)

**Comment by rathboma** [comment]
jeez. Is this new since 1.3? Or did 1.2 have this problem too?

**Comment by rathboma** [comment]
This is because of a mismatch in the `StartupWMClass` in the .desktop file. I'm not sure why it is mismatched, but I'm investigating.

**Comment by rathboma** [comment]
@ignissak @k3rni  can you download the linux assets from https://github.com/beekeeper-studio/beekeeper-studio/actions/runs/105067091 (once the build is done) and see if it fixes the missing icon?

**Comment by ignissak** [comment]
> @ignissak @k3rni can you download the linux assets from https://github.com/beekeeper-studio/beekeeper-studio/actions/runs/105067091 (once the build is done) and see if it fixes the missing icon?

It is fixed.
