### ISSUE TITLE
BUG: Cannot copy id value

### ISSUE THREAD

**Issue by sepehrr** [beekeeper-studio/beekeeper-studio#1081]
**Describe the bug**
I want to right-click & copy the value of ID but it doesn't work.
the same problem happens when I try to copy a column that is foreign key.
copying other columns' values works correctly.

**To Reproduce**
open a table & try to copy the primary-key column value(or a foreign-key column)

**Expected behavior**
the id/number should be copied to the clipboard

**Screenshots / Gifs**
If applicable, add screenshots or GIFS to help explain your problem.

**Version Information (please complete the following information):**
 - OS: Mac
 - App Version: 3.2.3
 - Database type and version: Posgresql

**Additional context**
Anything else you think might be helpful

**Comment by rathboma** [comment]
I have a new version coming with explilcit right click -> copy for all tables, so that should solve this!
