### ISSUE TITLE
FEAT: context menu on column values

### ISSUE THREAD

**Issue by dandv** [beekeeper-studio/beekeeper-studio#1087]
**Is your feature request related to a problem? Please describe.**
I've just installed BKS to rescue `text` content from an old SQLite database (it was opened read-only, and I didn't look into why, but that was OK). I found the column I wanted easily thanks to the structure in the left pane, but it wasn't very clear how to see more of the `text` than the first line.

![image](https://user-images.githubusercontent.com/33569/156261532-51b9c1c5-8ee6-4255-9c64-2750996d566f.png)

**Describe the solution you'd like**
A context menu with a "Copy" option would be easily discoverable and presumably easy to implement.

**Describe alternatives you've considered**
Ctrl+C worked, but there was no visual feedback that something was copied to the clipboard.
There was also an Export option.

**Additional context**
The ability to scroll through multi-line `text` values would be nice.

**Comment by rathboma** [comment]
This is fixed for the upcoming release! (the copying anyway)

Also coming soon, but not in the next relese: open a record in a sidebar so you can view multiline values, json formatting, etc.
