### ISSUE TITLE
FEAT: Reorder columns in table

### ISSUE THREAD

**Issue by oojacoboo** [beekeeper-studio/beekeeper-studio#1088]
**Is your feature request related to a problem? Please describe.**
Pretty straight-forward.  There isn't a way to reorder the columns presently.

**Comment by rathboma** [comment]
Agreed! I'm going to have a 'table configuration' setting soon with reordering / hiding of columns

**Comment by mcanepa** [comment]
I also need this!

**Comment by oojacoboo** [comment]
It's unlikely to happen, without just being faux reordering.  Postgres doesn't actually support column reordering and takes the ridiculous stance that it's not necessary and that you should be executing a SELECT statement that specifies the column ordering.  That, somehow, the default ordering of `SELECT *` isn't important.

For us, the ordering causes an ActiveRecord ORM implementation to fail if not correct.  Maybe that ORM shouldn't rely on ordering, but that's really beside the point.  Unfortunately, there is also no clean way of reordering columns on tables in Postgres.  You have to clone tables, drop indexes, FK constraints and more, then reassociate, add back indexes, etc.  It's a nightmare.

**Comment by rathboma** [comment]
We're going to do this, but it will simply be client-side reordering, not server side.

**Comment by rathboma** [comment]
Implementation notes

In TableTable we want to re-organize table columns, in the same way that we want to show/hide columns.

There are several ways this should work:

### In the show/hide modal

0. Rename this menu item to `Column visibility (#)` where # is the number of columns hidden. Tooltip should be `# columns currently hidden`
1. Update the show/hide columns modal to allow drag/drop of columns to reorder them
2. Provide a `reset order` button that restores default ordering, this should be on the bottom-left of the modal

### Interacting with the table
The TableTable sheet module should have the same resize behavior as Google Sheets:
1. If someone clicks a column header and drags, this selects multiple columns
2. If someone clicks a column header, releases, then clicks again and drags, this moves the column.
See below for a demo (apologies there is no cursor):

[Screencast from 02-09-2024 03:10:03 PM.webm](https://github.com/beekeeper-studio/beekeeper-studio/assets/279769/b03075e9-8a29-4fbd-804d-31a236c83e49)

**Comment by azmy60** [comment]
I think the second solution is the best approach for this. Luckily, it's easy to do that with tabulator, but it still needs some fixing from there https://github.com/olifolkerd/tabulator/pull/4431.

To keep it simple, it's not completely like google sheets yet. It's only able to move a single column instead of multiple columns for now.
