### ISSUE TITLE
FEAT: Support for DB2 and Oracle Drivers

### ISSUE THREAD

**Issue by sebbarry** [beekeeper-studio/beekeeper-studio#1095]
Hi guys. 

Really appreciate this amazing product and the time that has gone into this! Thank you.

I just wanted to reach out to see if you would look to support drivers for other enterprise databases like DB2 and Oracle in the future? Sure would make working in corporate more fun and I would definitely push my department to use this product if that became the case. 

Thanks!

**Comment by DMouse10462** [comment]
Issues #20 (Oracle) and #1006 (DB2) track these currently. I certainly agree; the more the merrier!

**Comment by rathboma** [comment]
Yep! Going to close this issue as tracking these independently.

Thanks so much for adding an issue!
