### ISSUE TITLE
FEAT: Optimize confirm  dialog

### ISSUE THREAD

**Issue by b0123456789** [beekeeper-studio/beekeeper-studio#1101]
I think it no need to make the dialog  to fullscreen, the small one which in the centre is enough.

Open a query tab and write some thing. then i click the close button to  close the tab.
when the dialog show. i alway choose to close the dialog then re-open this.
the reason why I open  the dialog twice  is that i want to review  the tab content.
i worry about  that  if i had close a wrong tab.
i worry about  that  if closing tab has written some thing not saved or not ran.
i lose everythink when i make a wrong dicision to close the dialog.
if the dialog is small, i can see the tab conent to avoid mistake.

Here is the confirm window.
![2022-03-12_10-44](https://user-images.githubusercontent.com/21169660/158000984-76a25aed-b76f-4236-8e04-8b07c07121ee.png)

**Comment by rathboma** [comment]
Thanks! Yes this could be optimized. Honestly this confirm dialog was just added quickly because the native dialog on Windows broke the app when dismissed (I don't know why).

**Comment by rathboma** [comment]
Closing this as I added some more text to identify what you are closing
