### ISSUE TITLE
FEAT: Allow expressions in table edit mode

### ISSUE THREAD

**Issue by inmanturbo** [beekeeper-studio/beekeeper-studio#1102]
Allow expressions in table edit mode.
such as `now()` and `uuid()`

**Comment by rathboma** [comment]
What database type are you using?

In MySQL you can use CURRENT_TIMESTAMP because it's treated differently

**Comment by rathboma** [comment]
Going to close this because escaping user input is something I'm not going to remove I'm afraid.
