### ISSUE TITLE
BUG: postgres over ssh tunnel appears to be using the wrong port for the db

### ISSUE THREAD

**Issue by doughsay** [beekeeper-studio/beekeeper-studio#1106]
**Describe the bug**

I'm connecting to a postgres database over an ssh tunnel.  The ssh connection appears to be fine, but it times out connecting to postgres. Postgres is exposed on a non-standard port.

**To Reproduce**
1. Create an SSH tunnel connection to a postgres database
2. Click on connect
3. It times out

**Expected behavior**
It connects as expected.

**Screenshots / Gifs**

This screenshot shows my configuration and the error from the debug console:

![Screenshot from 2022-03-18 19-24-44](https://user-images.githubusercontent.com/221693/159103183-f6e25aa9-6264-42bd-8420-be2228921cf4.png)

Here's the debug log that is produced with `DEBUG=*` enabled:

```
19:24:24.177 (postgresql)        › create driver client for postgres with config {"host":"127.0.0.1","port":10000,"database":"postgres","max":5,"connectionTimeoutMillis":15000,"idleTimeoutMillis":20000,"user":"postgres"}
19:24:24.177 (postgresql)        › connected
19:24:39.213 (ConnectionInterface) › Error: Connection terminated due to connection timeout
    at u.<anonymous> (app://./js/chunk-vendors.736bd382.js:2503:3639)
    at Object.onceWrapper (events.js:421:28)
    at u.emit (events.js:315:20)
    at Socket.<anonymous> (app://./js/chunk-vendors.736bd382.js:2439:59797)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:673:12)
```

This error message appears to show it trying to use port 10000 instead of the configured port of 54321.

And here's proof that I can ssh and connect to postgres from the terminal:

```
chris@local ~ λ ssh 192.168.0.24
chris@remote:~$ psql -U postgres -h localhost -p 54321 postgres
psql (11.11, server 14.1)
WARNING: psql major version 11, server major version 14.
         Some psql features might not work.
Type "help" for help.

postgres=#
```

**Version Information (please complete the following information):**
 - OS: Pop!_OS 21.10 x86_64
 - App Version: 3.2.1 (installed from the Debian/Ubuntu repo)
 - Database type and version: Postgres 14.1

**Additional context**

I use beekeeper studio from an Arch linux machine with SSH tunneling just fine.  Not sure why it's not working in this case...

**Comment by rathboma** [comment]
Hey!

So it does use the right port, but it does so using an SSH tunnel, so it forward localhost:1000 to database:1234. That means when you connect it will look like it's connecting through a different port (it is, but on your local machine).

Closing this, but please open another ticket if SSH tunneling isn't working for some other reason.
