### ISSUE TITLE
Sporadic behavior of CONCAT function in MySQL

### ISSUE THREAD

**Issue by suhail-ps** [beekeeper-studio/beekeeper-studio#1110]
**Description of the bug**
When trying to use CONCAT function in MySQL server it gives sporadic results.

**Steps to Reproduce**
1. Connect to MySQL server
2. Run the following Query
`SELECT CONCAT("A","?","B") AS AA,
CONCAT("A","?","B") AS BB
FROM DUAL;`
3. In column 'AA' the Question mark (?) character is not showing up as part of result.
![image](https://user-images.githubusercontent.com/102216381/159659931-3aab0e1c-f7c2-4d45-83a5-7fba6a7e86b7.png)

**Expected Behavior**
In column AA the output should contain Question mark (?) character, where as currently it is not showing.

**Version Information**
 - OS: Windows 10 Pro, Version 21H2, OS build 19044.1586
 - App Version: 3.2.1
 - Database type and version: MySQL - 5.7.32-log

**Comment by rathboma** [comment]
Hey! This is actually a weird quirk of the MySQL driver -- it thinks the first `?` is a parameter and because I pass an empty object for parameters `{}`, it tries to apply them and ends up with a blank space.

Simple fix, fixing now.
