### ISSUE TITLE
JSON Column is getting displayed as [Object Object]

### ISSUE THREAD

**Issue by abhimanyu003** [beekeeper-studio/beekeeper-studio#112]
Hello, this is really great work. :heart: 

In PostgreSQL JSON column is getting displayed as `[object Object]`
In other software like `datagrip` they display full parsed JSON.

Here is a screenshot, is possible to add something like this.
![image](https://user-images.githubusercontent.com/265913/81776169-fbce4680-950b-11ea-9d57-54df408e7a86.png)

**How it's displayed in datagrip.**

![image](https://user-images.githubusercontent.com/265913/81776382-4f409480-950c-11ea-8350-f955c05d5fac.png)

Thanks

**Comment by rathboma** [comment]
see release 1.3! This should be fixed

**Comment by GammaGames** [comment]
Will beekeper support syntax highlighting in json fields as well? They're currently not very easy to parse visually
