### ISSUE TITLE
FEAT: Sync query history feature

### ISSUE THREAD

**Issue by gopibabus** [beekeeper-studio/beekeeper-studio#1120]
Right now when I am switching machines, I am loosing query history to execute frequently used commands. This solution will allow us to organize queries in multiple projects.

Adding Github sync feature will help me to work on multiple machines. 

May be we can add support to sync history with GoogleDrive/OneDrive or Dropbox.

**Reference**: draw.io app using Github sync feature to save diagrams to Github/Gitlab/GoogleDrive etc.

**Comment by rathboma** [comment]
Hey! This is actually built-in to the ultimate edition. Hope that works for you! See here: https://www.beekeeperstudio.io/workspaces
