### ISSUE TITLE
BUG: ECONNRESET error when executing query or connecting to server.

### ISSUE THREAD

**Issue by theOofDoctor** [beekeeper-studio/beekeeper-studio#1121]
**Describe the bug**
My team and I normally use SSMS with windows authentication (which I understand is not currently supported), so I created a login on the server to allow beekeeper to sign in.

Connection to the server typically succeeds without issue, but running any queries results in a "Connection lost - read ECONNRESET" error in the results window. Weirdly enough, if the app is left alone for a bit and then the query is re-executed, it will succeed, but rerunning it immediately results in the same error. Once the error has happened, if you disconnect, attempting to reconnect will result in the same issue. I also get the error (only in the dev console) when double clicking on an entity in the left pane.

I did notice on another Github that uses the same db library that disabling encryption fixed it for them, but unfortunately (from what I can tell) SQL Server doesn't allow unencrypted connections.

**To Reproduce**
1. Connect to a SQL Server
2. Execute a query
3. Error pops up in the results window

**Expected behavior**
I should be able to execute queries and see 

**Screenshots / Gifs**
![image](https://user-images.githubusercontent.com/58712803/160736449-05783300-c20d-4db9-acda-dba2fd7c2e12.png)
![image](https://user-images.githubusercontent.com/58712803/160736467-fc877efa-9bf5-4f92-8d9b-9c1146d9716e.png)

**Version Information (please complete the following information):**
 - OS: Windows 11
 - App Version: 3.3.6
 - Database type and version: SQL Server 15.0.2000.5

**Comment by rathboma** [comment]
@theOofDoctor Some questions for you:

- Are you accessing a remote server, or on your local machine?
- Are you using an SSH tunnel?
- Is this a change with the newest version of Beekeeper Studio?
  - If so - had you enabled SSL for the connection in the previous version?

**Comment by theOofDoctor** [comment]
@rathboma 
- I'm currently just using it to connect to my local machine, haven't tried connecting to our hosted dbs
- I believe so? I know our prod and test dbs are through azure.
- No
- I'm not totally sure. I tried using beekeeper for work a couple months ago and couldn't get it to function properly, so I gave up. I could downgrade when I have time and see if the issue is still present if you'd like?

**Comment by theOofDoctor** [comment]
@rathboma just a note. I was hoping that maybe the latest release (With the new option for sql server) might fix my issue, but it hasn't. It does remove the need for ssl to be enabled, but I still get the same behaviour as before.

**Comment by theOofDoctor** [comment]
@rathboma I am able to connect to our remote servers for our environments perfectly fine, everything works as expected. It's just the local db that's giving me trouble for some reason.

**Comment by rathboma** [comment]
Hey! I think this is because you're probably using `SQL Server LocalDB` which despite it's name, is actually a **totally different** product that doesn't accept TCP connections.

**Comment by rathboma** [comment]
Can you check if that is what you are using?

**Comment by theOofDoctor** [comment]
@rathboma I don't think I'm using `SQL Server LocalDB`? At least when I connect to the LocalDB instance that's on my PC I don't see any of my databases:
![image](https://user-images.githubusercontent.com/58712803/164788889-18453e7a-b5a2-4ceb-b242-a1333b03c7b8.png)
That's also a completely different version of SQL Server than I'm using.

**Comment by rathboma** [comment]
Have you tried checking the 'trust server certificate's checkbox when connecting?

**Comment by theOofDoctor** [comment]
@rathboma yeah I have, I can't connect to the server otherwise. The issue is just contacting the server more than once within a 5 minute or so period. For instance, if I test the connection beekeeper says the connection is good, but then I get the econnreset error if I attempt to connect right after that. Same thing if I run a query and then another one after that. But if I have multiple queries in the same window and run, they all run perfectly fine.

**Comment by rathboma** [comment]
Ok I'll see if I can replicate it.

Can you record a screen capture of it happening? They really really help a lot with debugging.

**Comment by theOofDoctor** [comment]
@rathboma I'm gone for the weekend, but I should be able to do it when I get back on Sunday

**Comment by theOofDoctor** [comment]
@rathboma Here are 2 examples of the bug

Connecting and then immediately running a query throws an error
https://user-images.githubusercontent.com/58712803/165143892-b9227b26-d210-4897-968b-297887b62ea3.mp4

Running two queries consecutively throws an error
https://user-images.githubusercontent.com/58712803/165145460-6a9699a7-1dd5-4d2c-9358-8673571e8373.mp4

**Comment by theOofDoctor** [comment]
@rathboma I have finally figured out the issue! Took a bit of fooling around, but it is nothing to do with Beekeeper as far as I can see. I had to go into SQL Server Configuration manager, enable TCP/IP for the server, and then changed my connection port in Beekeeper from 1434 to 1433. So sorry to cause you so much trouble.
