### ISSUE TITLE
UI Suggestion: Close tabs via middle mouse click

### ISSUE THREAD

**Issue by Dragory** [beekeeper-studio/beekeeper-studio#113]
This is the behaviour in e.g. all browsers and many editors such as VS Code (at least on Windows). I can look into submitting a PR for it as well.

**Comment by rathboma** [comment]
yeeees. Good idea.

**Comment by rathboma** [comment]
should be as easy as adding a `@click.middle` to `CoreTabHeader.vue` if someone wants an easy contribution
