### ISSUE TITLE
Paid for Ultimate - now what?

### ISSUE THREAD

**Issue by oojacoboo** [beekeeper-studio/beekeeper-studio#1133]
How do I register this license key?  I don't see anywhere in the app to do so.  It's about time for a preferences modal.

**Comment by rathboma** [comment]
Hey! You can download the ultimate version here:

https://www.beekeeperstudio.io/get

It'll just replace your existing installation. Then go to menubar -> ultimate -> license key

Sorry it is two separate downloads, it's to cleanly separate the OSS and proprietary code.
