### ISSUE TITLE
QUESTION: How to view results

### ISSUE THREAD

**Issue by flying-sheep** [beekeeper-studio/beekeeper-studio#1134]
**Details:**
When executing the following PostgreSQL, I saw something like “Transaction was rolled back, not showing output until transaction ends”.

I specifically ran that code to be able to see simulate the update in order to debug it. How can I make Beekeeper studio show the results to me?

```sql
BEGIN;

UPDATE a
SET col = 'x'
FROM b
WHERE a.b_id = b.id
RETURNING *;

ROLLBACK;
```

The same applies if I use a `SELECT` statement instead of `RETURNING`

**Version Information [might be relevant to your issue]**
Operating System: Arch Linux
App Version [help -> about]: 3.2.1
Database type and version [eg Posgresql 9.3]: 13

**Comment by rathboma** [comment]
Hey! There's a little result selector in the bottom left of the results view:

![image](https://user-images.githubusercontent.com/279769/164781386-2b4c318e-5b08-44f7-999d-16f65855a7a7.png)
