### ISSUE TITLE
BUG: SqliteError when trying to save new connection

### ISSUE THREAD

**Issue by GabrielGaspar447** [beekeeper-studio/beekeeper-studio#1137]
**Describe the bug**
When trying to save a new MySQL connection I get a Sqlite Error (see image). I could only try with MySQL, can't say if this is happening with the others.

I can use the database if I click "Connect", just can't save the connection.

Downgraded to 3.3.6 and it works as intended.

**To Reproduce**
1. Select MySQL in "Connection Type"
2. Enter credentials
3. Enter connection name
4. Click "Save"

**Expected behavior**
Save a new connection to the list.

**Screenshots / Gifs**
![Screen Shot 2022-04-01 at 17 07 41](https://user-images.githubusercontent.com/83838669/161335495-f3f81dc1-a7c1-465f-807d-81425d0db86b.png)

**Version Information (please complete the following information):**
 - OS: MacOS Monterey 12.3 (MacBook Air M1)
 - App Version: 3.3.7 (arm64)
 - Database type and version: MySQL 5.7.37 (Docker)

**Comment by rathboma** [comment]
yes!  I just realized I made this mistake, there's a build already on the way. Sorry about that!
