### ISSUE TITLE
FEAT: support bind variables and explain plans

### ISSUE THREAD

**Issue by techwanker** [beekeeper-studio/beekeeper-studio#1138]
**Is your feature request related to a problem? Please describe.**
New Feature request

**Describe the solution you'd like**
I use prepared statements.

I would like to be able to write a query such as

select count(*) from etl_customer where etl_file_id = :etl_file_id

and :etl_file_id is a bind_name
then allow me to specify bind_name, bind_value pairs that applies to all of the statements.

I would also like the ability to show explain plans

I just started with this product 10 minutes ago but it seems to be very minimal, not a complaint, do one thing, simply and well
it's just that I doubt this is a buried feature I missed/

**Database type, if appropriate**
any database

**Comment by rathboma** [comment]
Hey,

Yes unfortunately these features are not yet in Beekeeper Studio, they will be soon!

Closing this issue as both of these are tracked elsewhere.

Question: Would you expect bind_value pairs to be stored in the database, or in Beekeeper Studio itself.
