### ISSUE TITLE
BUG: Add Table UI Bug

### ISSUE THREAD

**Issue by northmaster** [beekeeper-studio/beekeeper-studio#1139]
**Describe the bug**
Basically the UI is bugged now, it doesn't show the stuff properly while adding columns. It goes up, to fix this you need to resize the client and everything works fine, otherwise the new columns just keep going up.

**To Reproduce**
1. Connect to any database
2. Select any scheme
3. Click to create new table button
4. Click to add new column
5. See the error

**Expected behavior**
Show the columns while adding new ones

**Screenshots / Gifs**
https://i.imgur.com/tZNMCTv.mp4

**Version Information (please complete the following information):**
 - OS: Windows 10 21H1 Build 19043.1586
 - App Version: Beekeeper Studio 3.3.8
 - Database type and version: MySQL 8

**Additional context**
Maybe the height of the New Table UI isn't updating when clicking to add new column.

**Comment by AnoplexAdmin** [comment]
Same issue in Mac OS Monterey 12.3

**Comment by rathboma** [comment]
Thanks! This was a problem with the tabulator upgrade. I've fixed this, it'll be in the next release!
