### ISSUE TITLE
MySQL 8 connection error, can't pass login auth

### ISSUE THREAD

**Issue by gnovaro** [beekeeper-studio/beekeeper-studio#114]
![mysql8_auth_error](https://user-images.githubusercontent.com/270990/81801191-5370b000-9514-11ea-9ed6-1e81b0e21f7c.png)

New version use sha-256

**Comment by rathboma** [comment]
try version 1.3! I just released it and it should fix the error

**Comment by gnovaro** [comment]
Now works! you can close this issue
