### ISSUE TITLE
QUESTION: Saved queries locked behind updates connection break 

### ISSUE THREAD

**Issue by michaelbpyle** [beekeeper-studio/beekeeper-studio#1141]
**Details:**
Since the update from 3.3.5 to 3.3.6, Beekeeper can no longer establish a connection to out SQL database. Because of this, Neither the update to 3.3.7 nor 3.3.8 have fixed the issue. I have two issues:

1) I would like to have a Beekeeper version that reinstates that connection
2) More importantly, I need access to all of my saved queries. I can't figure out how to access them without first re-establishing the connection, which shouldn't be necessary for me to view *my own work*.

**Version Information [might be relevant to your issue]**
Operating System: Windows 11.
App Version: 3.3.8
Database type and version: SQL Database

**Screenshot / GIF [if appropriate]**:
A screenshot of the app if that helps

**Comment by rathboma** [comment]
Hey! There's a new setting introduced by the SQL Server driver that requires you to explicitly trust connections, you'll need to check the `Trust Server Certificate` box.

Can you try that and see if it works?

You can get all of your saved queries by using Beekeeper Studio to query Beekeeper Studio's database actually! `Help -> add beekeeper's database`, then check the `favorite_queries` table.
