### ISSUE TITLE
BUG: Create New Table Bug

### ISSUE THREAD

**Issue by AnoplexAdmin** [beekeeper-studio/beekeeper-studio#1142]
When clicking the create new table "+" icon, and then the "+" icon to add a column, the resulting column list scrunches up in a tiny window and you can't see any of the columns.

1. Go to the Entities list in the sidebar
2. Click on '+' for create new table
3. Click on '+' for add new column
4. See unusable scrunched list

**Expected behavior**
A usable list appears where I can add fields to the new table.

**Screenshots / Gifs**
![Screen Shot 2022-04-04 at 10 26 48 AM](https://user-images.githubusercontent.com/82687975/161599279-8d827f78-9584-4412-95f9-24437eff71c0.png)

**Version Information (please complete the following information):**
 - OS: Mac OS Monterey 12.3
 - App Version 3.3.8
 - MySql

**Comment by northmaster** [comment]
Same on Windows

**Comment by UtechtDustin** [comment]
Duplicate of #1139

**Comment by AnoplexAdmin** [comment]
> 

Different OS - so not really a duplicate

**Comment by UtechtDustin** [comment]
For me the screenshot and the video looks like the same issue.
I guess one Issue is enough, if a other OS is also affected it can be mentioned there :-)

**Comment by AnoplexAdmin** [comment]
Good point — I commented there.
