### ISSUE TITLE
BUG: Failed to connect : self signed certificate

### ISSUE THREAD

**Issue by js-kulkarni** [beekeeper-studio/beekeeper-studio#1144]
**Describe the bug**

**To Reproduce**

**Expected behavior**
Failed to connect to MS SQL Server 

**Screenshots / Gifs**
If applicable, add screenshots or GIFS to help explain your problem.

**Version Information (please complete the following information):**
 - OS: Mac Apple Sillicon Arm64
 - App Version :3.3.8
 - Database type and version MS SQL 2014

**Additional context**
Error establishing a connection. This wa working good till yesterday update. Error post latest update.

**Comment by rathboma** [comment]
Hey! You have to check the 'Trust Server Certificate' checkbox -- this is a SQL Server driver safeguard that was introduced recently.

**Comment by js-kulkarni** [comment]
Yes it worked. Thanks
