### ISSUE TITLE
QUESTION: Why do the tables I create with Beekeeper Studio all have read only schemas?

### ISSUE THREAD

**Issue by Sonander** [beekeeper-studio/beekeeper-studio#1148]
**Details:**
I am new to Beekeeper studio so this is probably a stupid question. 

For tables already existing in the database, when I right click a table and do 'View Structure' the tab that appears is editable. I can add new columns and edit the type of existing ones. 

However if I create a new table, and on this new table do View Structure, the tab that opens shows a warning triangle and Read Only in the status bar at the bottom of the window. No edit operations are possible on the table structure.  

**Version Information [might be relevant to your issue]**
Operating System: MacOS 12.3.1
App Version [help -> about]: 3.3.8
Database type and version [eg Posgresql 9.3]: Posgresql 13.5

**Screenshot / GIF [if appropriate]**:
A screenshot of the app if that helps

<img width="892" alt="Screenshot 2022-04-06 at 16 08 03" src="https://user-images.githubusercontent.com/31996566/162006929-7eba0cce-9c14-4201-acdf-246f76f74d2a.png">

This may be relevant background. I cannot create the table directly as I would like because the screen to edit the columns on table creation just has a gray bar where the column list should be. For example this second screen shot shows a new table just created with 3 columns added. 

<img width="894" alt="Screenshot 2022-04-06 at 16 10 40" src="https://user-images.githubusercontent.com/31996566/162007716-424c1e04-cd5b-4568-9ffe-d0974b86c789.png">

So I created the table with a random token column and then had hoped to edit it afterwards, unfortunately tables created this way are read only in their schema.

**Comment by WellingtonFonseca** [comment]
regarding your first question, so far as I understand the beekeeper needs a PK to be able to edit the data. 
So far I haven't found out if there's a way to add this column to a table that already exists, because the beekeeper doesn't allow it (read only).
I'm currently using `ALTER TABLE table_name ADD COLUMN id INT PRIMARY KEY AUTO_INCREMENT FIRST`
until this issue is resolved [issue #984](https://github.com/beekeeper-studio/beekeeper-studio/issues/984)

**Comment by Sonander** [comment]
Thank you! Designating my existing ID field a primary key made my table editable in Beekeeper.
