### ISSUE TITLE
Need to share my Saved Connections with colleagues 

### ISSUE THREAD

**Issue by prateekagarwal95** [beekeeper-studio/beekeeper-studio#1149]
**Details:**
Need to share my Saved Connections with colleagues. Can you please guide me how to do that ?

**Comment by rathboma** [comment]
Hi! Next week I'll be relaunching team workspaces as a free feature for the ultimate edition which will allow you to easily share connections and queries, stay tuned!

**Comment by rathboma** [comment]
@prateekagarwal95 Thsi is supported in the ultimate edition through workspaces: https://www.beekeeperstudio.io/workspaces
