### ISSUE TITLE
scroll offsets not remembered in tabs

### ISSUE THREAD

**Issue by k3rni** [beekeeper-studio/beekeeper-studio#115]
Scenario: 
1. connect, navigate to a table in the left pane, open it in a new tab. 
2. scroll down and/or right a bit. take note which row is shown on top.
3. focus another tab, e.g. the default Query tab
4. return to that table's tab

Expected:
the tab shows data just as I left it: same page in paginator, same row shown on top, same horizontal and vertical scroll offset

Actual:
page number preserved, but scroll offsets reset to zero (top-left) each time.

```
$ snap list beekeeper-studio
Name              Version  Rev  Tracking     Publisher         Notes
beekeeper-studio  1.3.0    19   latest/edge  matthew-rathbone  -
```

**Comment by rathboma** [comment]
Yeah I think this is the table library we're using resetting it's scroll when hidden. Good find. I'll poke around.

**Comment by ghstng** [comment]
v1.7
