### ISSUE TITLE
FEAT: Save and Copy to clipboard as markdown

### ISSUE THREAD

**Issue by WellingtonFonseca** [beekeeper-studio/beekeeper-studio#1150]
**Is your feature request related to a problem? Please describe.**
with the implementation of copy to clipboard it would be very useful to have the option to copy with this pattern below (which I don't remember the name at this time)

![beekeper-studio](https://user-images.githubusercontent.com/25608175/162256201-035a708b-de21-42b9-8c49-876972796915.png)

**Comment by rathboma** [comment]
Ah, a markdown table? Yeah that'd be cool.
