### ISSUE TITLE
Unable to connect to SQL Server after Upgrade to 3.3.8

### ISSUE THREAD

**Issue by DarinFlippo** [beekeeper-studio/beekeeper-studio#1154]
Running on an M1 Pro based MacBook pro, after updating BKS to 3.3.8, I can no longer connect to SQL databases.

**Comment by thomasstas** [comment]
Same issue here: "Error establishing a connection". 
(M1 MacBook Pro, BKS 3.3.8)

**Comment by rathboma** [comment]
Hey! Check the `Trust Server Certificate` box in the SQL Server connection settings. This was a new setting introduced by the SQL server driver that requires an explicit check
