### ISSUE TITLE
Freeze on loading tables

### ISSUE THREAD

**Issue by throrin19** [beekeeper-studio/beekeeper-studio#1164]
**Describe the bug**
When I want to change database in my server, Beekeeper freeze in tables loading and does not respond. 

**To Reproduce**
1. Connect to the server
2. Switch Base
3. Freeze

**Expected behavior**
No freeze

**Version Information (please complete the following information):**
 - OS: Mac
 - App Version 3.3.8
 - Database type and version Postgres 12 with TimescaleDB 2.4

**Additional context**
I am connected to a timescaleDB server : beekeeper try to load all tables, including chunk tables (arround 16k tables)

If beekeeper load, by default, only the public schema tables and only tables (no views or functions) It will be fine I guess.

**Comment by rathboma** [comment]
Hey! I think that number of tables is killing it for sure. It's because I also load all the columns for all the tables at the same time.

I'm tracking a fix on another ticket, but I'm def not ignoring this, it's a big bug I need to fix.

**Comment by throrin19** [comment]
@rathboma any news about this ? Freeze are already presents :(
