### ISSUE TITLE
BUG: Highlighting cell data is broken on macOS?

### ISSUE THREAD

**Issue by MTPeyton** [beekeeper-studio/beekeeper-studio#1166]
**Describe the bug**
I just upgraded to version 3.3.8 and it appears that both highlighting and copying cell data is no longer working on macOS. I'm running macOS Monterey 12.1 on an Apple SIlicon Mac.

**To Reproduce**
1. Open Beekeeper Studio
2. Connect to a database
3. Perform a query that returns rows
4. Attempt to double click on a cell's value

**Expected behavior**
The cell should be highlighted, and thus allow for copying the highlighted value.

**Screenshots / Gifs**
N/A

**Version Information (please complete the following information):**
 - OS: MacOS Monterey 12.1
 - App Version 3.3.8
 - Database type and version: MySQL 5.7

**Additional context**
Totally unrelated to this bug, but in previous Beekeeper Studio versions, I noticed that when I did copy/paste a value from a cell, the value would have a newline character appended to it. Not sure if that was expected behavior or not.

**Comment by rathboma** [comment]
Hey!

Ok, so to solve the weird character problems I removed cell highlighting and added a right click menu with specific copy options.

Can you right click a cell and see if the copy command there works ok?

**Comment by MTPeyton** [comment]
That works! Thank you! Really appreciate the help, and really appreciate all the work you guys put into Beekeeper!

**Comment by MTPeyton** [comment]
Hi, sorry to have to reopen this. Right-clicking is now extremely unreliable. I noticed this behavior in both 3.3.8 and 3.4.1. Same system specs as above. Most of the time right clicking on a row produces no effect. Occasionally it'll work as intended, and the context menu appears with the copy options. I've yet to be able to reliably reproduce this. Restarting the DB connection, restarting the app, and restarting my computer don't appear to help.

If I can figure out a reliable way to reproduce this, I'll add another comment here. Unfortunately for now this makes Beekeeper essentially unusable for me. :(

**Comment by rathboma** [comment]
Hey!

So sorry you're seeing an issue with this. I'll investigate and fix on Monday as soon as I can!

If before then you can record any sort of screen capture of you demoing the bug it would be very helpful!

**Comment by MTPeyton** [comment]
Unfortunately, due to the sensitive data in the database I'm accessing, I cannot record a screen capture. However, I did some more testing and determined that the right-click menu correctly appears when I right click rows that have exactly one primary key  column in their table. The right click menu does not appear when I attempt to right click rows that do not have any primary key specified for their columns in their table.

Additionally, I opened the devtools and did not see any output in the console.

If there's any application logs that would be helpful to send: please let me know.

**Comment by rathboma** [comment]
Hey! Right click menu will be totally fixed in next release, sorry about that! Copying non-text was broken, as was copying from a read-only table.

**Comment by rathboma** [comment]
@MTPeyton Fyi I am re-enabling a 'better' cell click highlight, and fixing right click menus, so you get both! Cell copying will also not include formatting oddities.

**Comment by MTPeyton** [comment]
This is awesome, thank you so much!
