### ISSUE TITLE
FEAT: Is it possible to add multiple languages to Beekeeper Studio

### ISSUE THREAD

**Issue by bluehysteric** [beekeeper-studio/beekeeper-studio#1176]
Is it possible to add multiple languages to Beekeeper Studio?

**Comment by rathboma** [comment]
Hey! It is, but right now it's just me working 2 days a week, so I really just don't have time to do this at the moment :-/. It would also require quite a substantial set of modifications to the code to support it.

Going to close this ticket for now, but if I ever end up working on the project full-time I'll come back to it.
