### ISSUE TITLE
BUG:  On save connection port number reset to default

### ISSUE THREAD

**Issue by io-oss** [beekeeper-studio/beekeeper-studio#1178]
https://user-images.githubusercontent.com/25923473/164168482-f044dad8-201c-4f38-bd28-529231bdfc09.mov

<img width="286" alt="图像" src="https://user-images.githubusercontent.com/25923473/164168625-0e454563-f212-4437-930c-5d41351dc992.png">

**Comment by tayhimself** [comment]
Hello - I am seeing the same issue, same version. macOS 12.3.1 Monterey.

**Comment by rathboma** [comment]
Hey! Yes I'll be fixing this soon. Sorry for the snaffu!

**Comment by ad-on-is** [comment]
Where can we find the config-file for the servers, so we can change back the port manually?

**Comment by physanus** [comment]
@ad-on-is On Windows, you can find the config in `%appdata%\beekeeper-studio\app.db`. You can open that file directly with Beekeeper and modify the port of the connection in the table `saved_connection`. After a restart, the port is loaded correctly.

**Comment by ad-on-is** [comment]
> @ad-on-is On Windows, you can find the config in `%appdata%\beekeeper-studio\app.db`. You can open that file directly with Beekeeper and modify the port of the connection in the table `saved_connection`. After a restart, the port is loaded correctly.

I'm on Linux, and tried exactly that, but `~/.config/beekeeper-studio/app.db` only contained one connection in saved_connection. 
Is another configuration file used?

I downloaded an older AppImage to revert back the changes.

**Comment by barrrettt** [comment]
same on ubuntu 22.04.1 LTS

**Comment by rathboma** [comment]
Pretty sure this is fixed?
