### ISSUE TITLE
 enhancement: Foreign Key relation with a link like PhpMyAdmin

### ISSUE THREAD

**Issue by gnovaro** [beekeeper-studio/beekeeper-studio#118]
Is a nice to have. When a click in a relational link open the another table data view.

**Comment by rathboma** [comment]
Yes for sure! I particularly like the way Postico does it

**Comment by linaspasv** [comment]
It would be a huge QoL improvements if you could preview a value from a related table on hover... like it's on PhpMyAdmin :-)
