### ISSUE TITLE
BUG: Mac M1 relations show incorrect

### ISSUE THREAD

**Issue by Eggoser** [beekeeper-studio/beekeeper-studio#1180]
Hi, developers. I found issue. I can't create relation because window is too little.

<img width="875" alt="Снимок экрана 2022-04-21 в 14 29 50" src="https://user-images.githubusercontent.com/51169434/164448844-81b5847e-aa4b-4f7d-af6b-ae604901eafc.png">

**Comment by rathboma** [comment]
Hey! Yes I've noticed this problem too. If you resize the window it'll correct itself. I'll fix this in a patch release next week.

Thanks!
