### ISSUE TITLE
FEAT: Move each database object type to separated folders

### ISSUE THREAD

**Issue by mojtabakaviani** [beekeeper-studio/beekeeper-studio#1190]
For example now for Postgresql database tables, views, procedures and functions are in public folder. please separated each  database object type to separated folders. this feature help to better access for databases with many objects.

- public
  - functions
  - procedures
  - tables
  - views

**Comment by rathboma** [comment]
Hey! I've deliberately not done this right now. I think the flatter UI is more friendly to the average database user, but I do agree that a tree view is better if you're more of an expert.

I plan on adding a setting section in a future update. Tagging this there - #197 .

Gonig to close this issue, but now I've tracked it from the settings ticket I'm still on top of it.

Thanks for contributing to the community!
