### ISSUE TITLE
BUG: Primary key column cann't edit and copy  value

### ISSUE THREAD

**Issue by b0123456789** [beekeeper-studio/beekeeper-studio#1194]
![2](https://user-images.githubusercontent.com/21169660/164953759-27f0d2ab-0338-4159-a023-b5a2ccdd9c62.png)

Id column cann't edit and cann't copy value from menu ```Copy Cell```

**Comment by rathboma** [comment]
Hey! Yes you can't edit -- this is a current limitation of Beekeeper Studio, but copy should work after the next update. Thanks for reporting!

I'm going to close the issue as it should be resolved soon.

![image](https://user-images.githubusercontent.com/279769/174660944-d6b05710-e98f-4b7c-ac18-80531fa624cc.png)
