### ISSUE TITLE
BUG: Cockroach Connection using wrong fields

### ISSUE THREAD

**Issue by bladefist** [beekeeper-studio/beekeeper-studio#1195]
**Describe the bug**
Trying to connect to an insecure development cluster.  A picture is worth a thousand words:

![image](https://user-images.githubusercontent.com/1520456/165311253-a487a459-5d0f-4da2-9bef-cec8813e01ff.png)

**Comment by UtechtDustin** [comment]
Can't reproduce this issue, for me the correct input was used.

Could you maybe try to save the connection again and/or recreate it ?
Maybe its an issue of an old fix bug and your connection still has wrong data in the beekeeper database
