### ISSUE TITLE
BUG: high port number does not get saved

### ISSUE THREAD

**Issue by pixelpeter** [beekeeper-studio/beekeeper-studio#1200]
Entering a high port number like `33236` for a Postgres connection it will always be reset to `5432`.
Only way to make the connection work (although not saved) is to type {enter} after entering the port number

Beekeeper Studio 3.4.1
MacOS Monterey 12.3.1

**Comment by UtechtDustin** [comment]
Duplicate of #1203

**Comment by rathboma** [comment]
fixed in master, release coming today
