### ISSUE TITLE
BUG: Saving a new connection causes port setting to revert

### ISSUE THREAD

**Issue by donuts-are-good** [beekeeper-studio/beekeeper-studio#1203]
**Describe the bug**
When typing in the connection details for a new remote database, my database has a non standard port, and entering that port causes the port to revert to 5432 after pressing save. 

**To Reproduce**
1. MacOS (current), on M1 air
2. Open new install of beekeeper
3. Add a connection
4. Set a non standard port
5. Click the orange button to assign the color orange to this connection (for some reason yellow did not produce this behavior, but yellow is my least favorite color.)
6. Press SAVE

**Expected behavior**
I was expecting the same port I had set to stay in the number picker. 

**Screenshots / Gifs**

![Screen Recording 2022-04-30 at 11 42 48 PM](https://user-images.githubusercontent.com/96031819/166132594-cda94db6-db72-463d-ac7d-b89fbc5d2302.gif)

**Version Information (please complete the following information):**
 - OS: MacOS Latest
 - App Version: I accepted the new version update just a few hours ago when I got the notification 
 - Database type and version [eg Posgresql 9.3] Postgres 13
(you have a typo here)

**Additional context**
I hate MacOS, what a trash operating system. How do people even live like this?

**Comment by treehousetim** [comment]
I have this problem as well.

**Comment by sbs-mpadilla** [comment]
Same issue. Gotta manually update the port every time I try to login

**Comment by yogesnsamy** [comment]
Same issue since I installed a new Beekeeper update today.

**Comment by holyoaks** [comment]
Same problem, on Intel Mac.And @donuts-are-good , I LOVE my Mac. Don't know how people work on Windows 😁
