### ISSUE TITLE
BUG: Console errors when viewing tables, unable to open foreign key links

### ISSUE THREAD

**Issue by djpowers** [beekeeper-studio/beekeeper-studio#1204]
**Describe the bug**
Clicking the icon when hovering over a foreign key record column does not open a tab with that record data.

**To Reproduce**
1. Connect to a database
2. Double click a table name that has a foreign key column from the "Entities" list (note that this results in `Invalid column definition option: dataType` errors being thrown once per column count, originating from `tabulator esm.js:18584`)
3. Scroll over to a foreign key column and click the linked resource icon shown on hover.
4. No UI change, console error originating from `TableTable.vue:756`:
```
Uncaught TypeError: Cannot read property 'toTable' of undefined
    at s.fkClick (TableTable.vue:756)
    at Be.dispatchEvent (tabulator_esm.js:12510)
    at Be.handle (tabulator_esm.js:12444)
    at tabulator_esm.js:22637
    at Array.forEach (<anonymous>)
    at Dt._dispatch (chunk-vendors.1d55ef3c.js:2536)
    at xt.dispatch (tabulator_esm.js:79)
    at xt.triggerEvents (tabulator_esm.js:22174)
    at xt.track (chunk-vendors.1d55ef3c.js:2536)
```

**Expected behavior**
The associated foreign key record should be opened in a new tab.

**Screenshots / Gifs**
<img width="877" alt="image" src="https://user-images.githubusercontent.com/4978418/166162215-6904f268-c937-427b-af43-fced53c51e43.png">

**Version Information (please complete the following information):**
 - OS: macOS 12.3.1
 - App Version 3.4.2
 - Database type and version: Posgresql 13.6

**Comment by Guilledll** [comment]
Same here for Mysql database, my tables are `Users` and `Roles` where every user has a `role_id` column which gives me the same error.
User Role relation looks good:
![image](https://user-images.githubusercontent.com/54317276/166393898-572e090e-9126-4e3d-9285-cf55eab4f4f5.png)

**Comment by djpowers** [comment]
Thanks @rathboma! Confirming this fixed the issue for me.
