### ISSUE TITLE
How can I see all my databases.

### ISSUE THREAD

**Issue by franklin106** [beekeeper-studio/beekeeper-studio#1209]
currently I have 43 databases (more may come) but I can only see 33 of them, even in full screen the scroll bar does not go all the way to the bottom OR maybe it does but the data does not show...  the attached shows what I can see .. there are a number of databases after the last one shown.

![fullscreen](https://user-images.githubusercontent.com/59705717/166713846-1403341e-52d3-4d27-ab24-3bbbc60b9b46.jpg)

I'm sure its just some view change but I haven't been able to fine it...

Thank you for your help

**Comment by rathboma** [comment]
Hey! Can I check what version of the app you have? (help -> about beekeeper studio)

This was fixed in 3.4.2 as far as I can tell

**Comment by franklin106** [comment]
Hi Matthew,

 

I have version 3.3.8

 

Thanks for your help in this.. I like the app but if I can't access all the
dbs it isn't really helpful.

 

franklin106; Author 

 

  _____

**Comment by rathboma** [comment]
@franklin106 ok, this is easy to fix then! If you restart Beekeeper Studio it should prompt you to update, otherwise, just install the new version from https://beekeeperstudio.io
