### ISSUE TITLE
FEAT: Collapse public schema on connecting [Postgres]

### ISSUE THREAD

**Issue by nelwinjacob** [beekeeper-studio/beekeeper-studio#1213]
Currently, the public schema is expanded as soon as the connection is made. It is more convenient if all schemas are shown collapsed in the beginning. An option to customize this behaviour will also be helpful.

**Comment by rathboma** [comment]
Tagging with #197 so it can be added to an eventual settings screen

**Comment by rathboma** [comment]
I'm going to close this as I'll track it on the settings issue!
