### ISSUE TITLE
QUESTION: Support of certain database software.

### ISSUE THREAD

**Issue by GalaxyBlade** [beekeeper-studio/beekeeper-studio#1219]
Does Beekeeper Studio support MongoDB and Redis? (planning on using MySQL, MongoDB, Redis, and maybe a few other database software(s) for something in the future) (I don't know if software is the right term)

**Comment by rathboma** [comment]
Hey!

It does not support either of those databases yet. Currently it only support relational SQL databases. Adding no-sql database support is a lot more complex, as each of those requires a different UI, so it won't happen for a while, unless one of the companies sponsors me to build the integration.
