### ISSUE TITLE
Cannot remove saved connection

### ISSUE THREAD

**Issue by jonorossi** [beekeeper-studio/beekeeper-studio#122]
I've got 2 saved connections, when I click "Remove" on the first one it does nothing. Restarting the app doesn't change anything. Both saved connections have the same name.

OS: macOS with your CI build from #116

**Comment by jonorossi** [comment]
"Rename" also doesn't do anything.

**Comment by rathboma** [comment]
Ah, yes, you cannot remove right now (def an oversight). You can rename, if you click on it, then rename it at the bottom and click save again

**Comment by jonorossi** [comment]
> You can rename, if you click on it, then rename it at the bottom and click save again

Oh, thanks. If I click on the ellipsis to get the Remove/Rename menu it selects the item and brings up the connection details on the right, so rename doesn't appear to do anything since it is already showing. Maybe for a saved connection the UI show should the name at the top or something, anyway something to think about because the UI is not intuitive.
