### ISSUE TITLE
BUG: Clicking foreign key link doesn't open corresponding table

### ISSUE THREAD

**Issue by devinvb** [beekeeper-studio/beekeeper-studio#1220]
**Describe the bug**

Clicking the link behind a foreign key value should open the corresponding table and show the row, but it doesn't work. Error is shown in the developer tools console:
`TableTable.vue:756 Uncaught TypeError: Cannot read property 'toTable' of undefined
    at s.fkClick (TableTable.vue:756)
    at Be.dispatchEvent (tabulator_esm.js:12510)
    at Be.handle (tabulator_esm.js:12444)
    at tabulator_esm.js:22637
    at Array.forEach (<anonymous>)
    at Dt._dispatch (chunk-vendors.1d55ef3c.js:2536)
    at xt.dispatch (tabulator_esm.js:79)
    at xt.triggerEvents (tabulator_esm.js:22174)
    at xt.track (chunk-vendors.1d55ef3c.js:2536)`

**To Reproduce**

1. Go to any table that has a foreign key column. 
2. Click on the icon 'View record in table'
3. Table does not open
4. Error is shown in developer tools console.

**Expected behavior**
Clicking the icon behind the foreign key value should open that table in a new tab and show the corresponding record.

**Screenshots / Gifs**
![beekeeper bug](https://user-images.githubusercontent.com/10828601/167589401-30f97bb2-8b02-4dc1-ab33-17368f076690.PNG)

**Version Information (please complete the following information):**
 - OS: Windows
 - App Version: 3.4.2. (installed version)
 - Database type and version: 10.3.34-MariaDB-0ubuntu0.20.04.1 (running locally in WSL2)

**Comment by rathboma** [comment]
fixed in master, release coming today
