### ISSUE TITLE
BUG: File dropdown graphic glitch

### ISSUE THREAD

**Issue by nitodico** [beekeeper-studio/beekeeper-studio#1222]
**Describe the bug**
Graphic glitch opening the "File" dropdown

**To Reproduce**
1. Dropdown "File" tab
2. That's it. It's just the File tab

**Expected behavior**
Being readable

**Screenshots / Gifs**
![imagen](https://user-images.githubusercontent.com/49000973/167853780-2f99c146-a1ca-480c-8936-1786e6e52aaf.png)

**Version Information (please complete the following information):**
 - OS: Ubuntu Mate 20.04.4 LTS, Ryzen 5 3500U, Vega 11
 - App Version: 3.4.2
 - Database type and version Sqlite, MySQL... any kind

**Additional context**
I usually work with all kind of graphic software (inkscape, gimp, blender) even some gaming without issues, doesn't looks like a graphic processor  problem. I've tried downloading again with no success.

**Comment by rathboma** [comment]
Oh Ryzen graphics. I've seen these a lot.

Are you using the `snap` version of the app? Are you using Wayland vs X?

My guess is you're using the snap version -- if so, download the .AppImage from the website and try that. Snaps have a bunch of stuff broken about them.

**Comment by nitodico** [comment]
Yes, it's the snap version. Downloaded the appimage and works charming... maybe it could be a good idea to add such information in the readme for ryzen users?
