### ISSUE TITLE
BUG: button background-color

### ISSUE THREAD

**Issue by shaoxiangwu** [beekeeper-studio/beekeeper-studio#1229]
**Describe the bug**
background-color and text color are the same

**To Reproduce**
![image](https://user-images.githubusercontent.com/67614581/168716476-61a9fa13-7d4e-409e-8c90-51a359fae25e.png)

**Version Information (please complete the following information):**
 - OS: [Mac]
 - App Version:3.4.2
 - Database type and version [eg Posgresql 9.3]

**Comment by rathboma** [comment]
Good catch! I thought I'd fixed this everywhere.
