### ISSUE TITLE
BUG: MySQL connection port changes to default 3306 overwriting any custom port on save.

### ISSUE THREAD

**Issue by codeoholic** [beekeeper-studio/beekeeper-studio#1232]
**Describe the bug**
On connection save, MySQL connection port changes to default 3306 overwriting any custom port.

**To Reproduce**
1. Go to 'change the port to anything on an already saved connection.'
2. Click on 'save connection'
3. Port number will change to default 3306.

**Expected behavior**
Connection port should be respected which is not the case here.

**Version Information (please complete the following information):**
 - OS: macOS
 - App Version 3.4.2
 - MySQL

**Comment by rathboma** [comment]
fixed in master, release coming soon
