### ISSUE TITLE
FEAT: Set primary key cell to NULL while cloning a row

### ISSUE THREAD

**Issue by nheimann1** [beekeeper-studio/beekeeper-studio#1236]
Currently while cloning a row, one of the things that needs to be done for primary keys (especially when they are auto incremented) is to delete the current value and keep it as NULL before applying your changes. 

It would be great if when cloning a row the primary key cell would be set to NULL auomatically on the new cloned row, at least when the primary key has auto increment setting.

Now that multiple rows selection is around the corner, it feels it would have even more need.

Thank you

**Comment by rathboma** [comment]
Yes I'll add this as soon as #1126 is merged!

**Comment by wmontgomery** [comment]
@rathboma How would we expect a primary key WITHOUT a default value to work? Still set as NULL and go from there to be filled out however the user sees fit?

**Comment by rathboma** [comment]
@wmontgomery yes it should just null it out because it has to be unique
