### ISSUE TITLE
QUESTION: Need help connecting via SSH tunnel

### ISSUE THREAD

**Issue by Johnhersh** [beekeeper-studio/beekeeper-studio#1240]
Hi, I used Beekeeper with my Postgres database for a while and it's been great. Recently however I had some security issues and so I moved the DB to be behind an SSH tunnel and closed the remote connection. I can connect to it just fine via PGAdmin with their SSH tunnel, or via SSH just from the shell (I'm on a Mac).

With beekeeper though I cannot get it to connect via SSH tunnel. I keep getting this error: "Error: All configured authentication methods failed". The only thing that stands out is that in the console I see:
tunnel config:
{fromPort: 10000, toPort: 5432, toHost: "localhost"}
fromPort: 10000
toHost: "localhost"
toPort: 5432
proto: Object

Which seems odd to me since I don't have port 10,000 open anywhere. This is on an AWS ec2 instance. Do I need to open that port on there instead of 22? I tried that but it didn't make a difference.

I also see the message about enabling AllowTcpForwarding, but I uncommented that line from the sshd config on my ec2 instance and it still made no difference.

Any ideas for anything else I can try?

**Comment by alex-telpis** [comment]
I'm getting the same error. 

<img width="619" alt="Screenshot 2022-07-09 at 21 08 21" src="https://user-images.githubusercontent.com/3338171/178120555-aa580310-207d-4f8c-9616-4cdd88603520.png">

**Comment by rathboma** [comment]
Hey all,

I'm not sure why you are seeing this error. Is AllowTCPForwarding set on your SSH server? This is the one thing that stands out to me

If you can check the dev console to see if there are any more errors, that would be very helpful.

The port `10000` is a local port opened up for the tunnel. It creates a bridge to your SSH server using a local port that forwards packets to your database over SSH.

**Comment by mathias22osterhagen22** [comment]
Hello, 
I have exact same problem. `AllowTcpForwarding` is set to `yes`
![image](https://user-images.githubusercontent.com/60438474/201736274-721df54f-452f-4cfc-987d-0741f4afc54e.png)

My PEM key is working with tabby I can forward the port but not with beekeeper.

![image](https://user-images.githubusercontent.com/60438474/201736450-b07b2c6d-4d11-4ec4-8984-207ae53e22ff.png)

![image](https://user-images.githubusercontent.com/60438474/201736670-c7f822f6-92e3-4716-962f-51fc6bc2aeb9.png)

I'm trying to reach a container running on the remote host: 
![image](https://user-images.githubusercontent.com/60438474/201736915-9dddb089-9ab7-4be7-8f0a-051065bf28e6.png)

**Comment by michaelgambold** [comment]
I just started having this issue today with our ssh bastion. It was working yesterday the only change we have made is that we have replaced the server from Ubuntu 18.04 to 22.04. No changes have been made to the ssh keys or any other part of the infrustructure.

I can ssh directly into the bastion with the same ssh key that beekeeper is using (through the "agent" SSH Authentication).

The key is a sha2 256.

**Comment by michaelgambold** [comment]
@rathboma I have performed the same checks as @mathias22osterhagen22 and have the same result. What more can we do on our ends to assist in the speedy resolution of this as it's impacting my workflow?

**Comment by jonathborg** [comment]
Same here, trying to access Postgres behind a bastion host.

**Comment by jonathborg** [comment]
@rathboma can you help us here? My team is giving up beekeeper (for now) since we can't access Postgres over SSH in Ubuntu 22.04.

**Comment by rathboma** [comment]
Hey! I need a way to reproduce the error. @davidkaufman can you think what other information they could gather for us to debug this?

**Comment by jonathborg** [comment]
My scenario:
- 2 machines (AWS EC2), both with Ubuntu 22.04 and in the same network (AWS VPC).
- The first machine is in a private subnet (but this doesn't matter) and has Postgres installed.
- The second machine is in a public subnet.
- I set up the connection (database host) with the private IP of the first machine and over SSH with the public IP of the second machine.

I found the same problem with other client databases, with the same message, like Antares SQL.

`All configured authentication methods failed.`

In [this issue](https://github.com/antares-sql/antares/issues/509), he says "is an issue related to SSH tunnel with private key authentication".

Feel free to let me know if you guys need more information. But I believe it's now possible to reproduce the error.

**Comment by michaelgambold** [comment]
Our scenario is similar to @jonathborg with the only difference our DB is running on AWS Aurora (Postgres). I.e. we connect straight to the Aurora instance from the Ubuntu 22.04 bastion.

**Comment by jonathborg** [comment]
@michaelgambold can you try [this](https://github.com/mscdex/ssh2/issues/989#issuecomment-1117074996)?

**Comment by rathboma** [comment]
Oh my gosh. Good find. While it doesnt look resolvable right now in the node library, it looks like I can add a more verbose error message and create a docs page to describe this workaround.

**Comment by davidkaufman** [comment]
A lot of folks have reported similar issues in this ticket!  

And it looks like @jonathborg and @michaelgambold have confirmed that its likely due to the sshd change in Ubuntu server > v22.04  

Can @Johnhersh @alex-telpis @mathias22osterhagen22 chime in if you guys are having this problem while trying to connect to an sshd daemon running on one of these recent Ubuntu releases too?

- https://github.com/mscdex/ssh2/issues/989

**Comment by jonathborg** [comment]
In my case, I can confirm that adding `PubkeyAcceptedKeyTypes=+ssh-rsa` in the `/etc/ssh/sshd_config`and restarting ssh (`sudo systemctl restart sshd.service`) solve the problem.

**Comment by davidkaufman** [comment]
Thanks for that workaound @jonathborg!

**Comment by michaelgambold** [comment]
FYI to people following this issue. The ssh2 library has an open [PR](https://github.com/mscdex/ssh2/pull/1200) that may address this. However it was opened July 2022 and has not been merged yet.

**Comment by davidkaufman** [comment]
ssh2 module has been upgraded in PR #1653 so this should be fixed in the next release!
