### ISSUE TITLE
FEAT: Please provide feature to have multiple window of different connection

### ISSUE THREAD

**Issue by amrishkakadiya** [beekeeper-studio/beekeeper-studio#1241]
**Is your feature request related to a problem? Please describe.**
Currently, I have multiple environment connection saved, When I want to switch between them I have to disconnect from exisitng.

**Describe the solution you'd like**
There should be feature like I can use multiple connection in separate window  so It will be easy to switch between connections.

**Additional context**
Feature is like, working in multiple project using vs code multiple window.

**Database type, if appropriate**
No, This is for every database.

**Comment by rathboma** [comment]
This works! You can go to File -> New Window and connect to whatever other connection you like.

**Comment by s22-tech** [comment]
But how do you switch back and forth bewteen them?  There's no Windows menu, at least not on the Mac version 3.9.9 I'm using.
