### ISSUE TITLE
FEAT: shift + tab on selection to remove indentation in editor

### ISSUE THREAD

**Issue by kilbiller** [beekeeper-studio/beekeeper-studio#1242]
**Is your feature request related to a problem? Please describe.**
Currently you can use TAB to indent text, SHIFT + TAB to remove one level of indentation, use TAB with selected text to indent multiple rows but you can't use SHIFT + TAB on selected text to remove one level of indentation for multiple rows

**Describe the solution you'd like**
SHIFT + TAB with text selected should be able to remove one level of indentation for multiple rows

**Comment by wmontgomery** [comment]
Hey @kilbiller , I'll be looking into this issue, have some leads but it looks like a downfall of Code Mirror for now (they really want "tab" to not be messed with too much). I'll add a link to this when I find it again. In the meantime, you can highlight the rows and use `ctrl/cmd + [` to remove a level of indentation. Conversely, `ctrl/cmd + ]` will indent it for single or multiple lines.

**Comment by wmontgomery** [comment]
@rathboma , PR submitted https://github.com/beekeeper-studio/beekeeper-studio/pull/1366
