### ISSUE TITLE
BUG: SQL Syntax characters included as parameter name

### ISSUE THREAD

**Issue by mghizzo** [beekeeper-studio/beekeeper-studio#1244]
**Describe the bug**
Dollar sign parameters includes all SQL syntax characters (comma, parenthesis, etc..) as parameter name instead of using that for SQL syntax

**To Reproduce**
1. Create a new Query
2. Use dollar sign for parameters and have a comma to separate something in the query (e.g. you use IN operator and you specify multiple parameters separated with a comma)

**Expected behavior**
I'd expect comma not to be included as parameter name

**Screenshots / Gifs**
Affected query area in my case:
![Schermata 2022-05-26 alle 20 20 03](https://user-images.githubusercontent.com/29211226/170551389-225e4106-ec3f-4f9d-8dab-55a1f7b934b8.png)

Result (Check $3):
![Schermata 2022-05-26 alle 20 20 15](https://user-images.githubusercontent.com/29211226/170551548-de81ef31-1e04-40e5-a15d-400bb2b04371.png)

**Version Information (please complete the following information):**
 - OS: Mac
 - App Version: 3.4.3
 - Database type and version: Posgresql v14

**Comment by rathboma** [comment]
Good catch thanks!

**Comment by azmy60** [comment]
I think it's safe to close this as it's resolved by this PR https://github.com/coresql/sql-query-identifier/pull/56. I checked it using the latest bks too.
