### ISSUE TITLE
FEAT: View record in {table} doesn't account for multiple foreign keys.

### ISSUE THREAD

**Issue by theOofDoctor** [beekeeper-studio/beekeeper-studio#1246]
**Is your feature request related to a problem? Please describe.**
If you have multiple foreign key relations on the same column, the view record tooltip action seems to just pick the last relation as the table to navigate to, even if that key doesn't go to that specific column

**Describe the solution you'd like**
I would like that tooltip to navigate to the proper table, depending on which relation is actually 'active' in that case.

**Describe alternatives you've considered**
You could possibly just show all of the tables that are linked in that tooltip

**Additional context**
In this particular case, we have 3 relations on the 'TargetId' column, with only one of them being linked to the 'User' table:
![image](https://user-images.githubusercontent.com/58712803/170579319-206646fb-9470-451f-87da-64fe667026ba.png)

Whenever one hovers over that column in the data view it only allows you to navigate to the 'User' table:
![signal-2022-05-26-145301](https://user-images.githubusercontent.com/58712803/170578993-c53090da-f2d7-4e8d-8e78-01fc3077fab9.jpeg)

When you get to that table, there is no data to be found:
![image](https://user-images.githubusercontent.com/58712803/170579150-29316422-ebe2-49f9-a61f-a35ea53543af.png)

This does work as expected if the link is to the 'User' table though (I didn't put this as a bug because I'm assuming this just wasn't thought of so it is as designed?)

**Comment by rathboma** [comment]
@theOofDoctor I know this is merged, but would you be able to give me some SQL to create tables like this so I can demo it?

What database supports multiple relations on the same column?

**Comment by rathboma** [comment]
Oh, looks like SQL Server. Either way - some SQL to help me demo it would be amazing!

**Comment by theOofDoctor** [comment]
@rathboma yeah for sure! I'm at work rn but I should be able to get to this tonight

**Comment by theOofDoctor** [comment]
@rathboma Here ya go!

```sql
CREATE TABLE Table1 (Id INT NOT NULL PRIMARY KEY, MultipleFKs INT NOT NULL);
CREATE TABLE Table2 (FK1 INT NOT NULL PRIMARY KEY);
CREATE TABLE Table3 (FK2 INT NOT NULL PRIMARY KEY);
CREATE TABLE Table4 (FK3 INT NOT NULL PRIMARY KEY);

ALTER TABLE Table1 WITH NOCHECK ADD CONSTRAINT FK_TABLE2 FOREIGN KEY (MultipleFKs)
REFERENCES Table2 (FK1);

ALTER TABLE Table1 NOCHECK CONSTRAINT FK_TABLE2

ALTER TABLE Table1 WITH NOCHECK ADD CONSTRAINT FK_TABLE3 FOREIGN KEY (MultipleFKs)
REFERENCES Table3 (FK2);

ALTER TABLE Table1 NOCHECK CONSTRAINT FK_TABLE3

ALTER TABLE Table1 WITH NOCHECK ADD CONSTRAINT FK_TABLE4 FOREIGN KEY (MultipleFKs)
REFERENCES Table4 (FK3);

ALTER TABLE Table1 NOCHECK CONSTRAINT FK_TABLE4

INSERT INTO Table2 VALUES (1);
INSERT INTO Table3 VALUES (2);
INSERT INTO Table4 VALUES (3);

INSERT INTO Table1 VALUES
(1, 1),
(2, 2),
(3, 3);
```
