### ISSUE TITLE
BUG: Export table as SQL with jsonb fields - arrays become objects

### ISSUE THREAD

**Issue by kazzkiq** [beekeeper-studio/beekeeper-studio#1249]
**Describe the bug**
Whenever you export a table with JSONB columns that contains arrays (`[]`), the generated SQL has the arrays replaced with objects (`{'0': {}, '1': {}, ...}`).

Example:
```sql
-- A JSONB column with array
'["a", "b", "c"]'

-- Becomes this after export:
'{"0": "a", "1": "b", "2": "c"}'
```

**To Reproduce**
1. Create a table with a JSONB column.
2. Add a entry with an array in said column. e.g.: `['hello', 'world', 'wow']`
3. Right-click a table > "Export";
4. Select "Format" > "SQL" and export.
5. Open the file and check the columns that had JSONB arrays, they're now objects. e.g.: `{'0': 'hello', '1': 'world', '2': 'wow'}`

**Expected behavior**
Exported  JSONB columns with array should remain arrays, not be turned into objects. This leads to all sorts of bugs since the data is corrupted.

**Version Information (please complete the following information):**
 - OS: macOS
 - App Version: 3.4.3
 - Database type and version:
 ```
PostgreSQL 14.1 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-12), 64-bit
 ```

**Comment by wmontgomery** [comment]
Definitely able to replicate. I'll see what I can do.

**Comment by wmontgomery** [comment]
PR submitted https://github.com/beekeeper-studio/beekeeper-studio/pull/1339
