### ISSUE TITLE
Views not returned in 'tables & views' list

### ISSUE THREAD

**Issue by CptMonac** [beekeeper-studio/beekeeper-studio#125]
In the newest Beekeeper update that includes multiple-schema support, views belonging to the non-public schema do not show up in the list. 

Example screenshot with relevant query included below. In the screenshot, the query returns views 'codaexport', and 'daylioexport' that are not visible in the table list
![image](https://user-images.githubusercontent.com/1922661/82082799-78dcf580-969d-11ea-8d7f-80ed999524a6.png)

**Comment by rathboma** [comment]
Oh, you're right! This should be an easy fix. I'll do it this weekend
