### ISSUE TITLE
Why cant i remove a cell in my player_jobs

### ISSUE THREAD

**Issue by CottonMouthMax** [beekeeper-studio/beekeeper-studio#1252]
trying to delete a job from the player_jobs but doesnt give me the option to delete the cell. Need help as its breaking my multijob

**Comment by CottonMouthMax** [comment]
![Screenshot (187)](https://user-images.githubusercontent.com/104052807/171060695-674d07fd-3469-48c9-a37b-faea3699fa8e.png)

**Comment by rathboma** [comment]
Hey! Looks like there is no primary key on that table. Beekeeper currently only supports editing tables that have a primary key :-(. Hopefully this can be resolved in the future.
