### ISSUE TITLE
FEAT: Add "Close to the Right" tab option

### ISSUE THREAD

**Issue by Zerotask** [beekeeper-studio/beekeeper-studio#1257]
**Is your feature request related to a problem? Please describe.**
I'm used to use that option in other programs like a Browser or VS Code

**Describe the solution you'd like**
If you right-click on a tab, you currently have the options:
- Close
- Close Others
- Close All

I'd like to have an additional "Close to the Right"

**Comment by rathboma** [comment]
Yes, agreed! this is a pretty easy issue for a first-time contributor too.
