### ISSUE TITLE
FEAT: Unable to create/update procedures

### ISSUE THREAD

**Issue by luizfelipevbll** [beekeeper-studio/beekeeper-studio#1259]
**Is your feature request related to a problem? Please describe.**
I cant update a stored procedure using DELIMITER keyword from MySQL

**Describe the solution you'd like**
Allow DELIMITER keyword usage

**Describe alternatives you've considered**

```sql
DELIMITER $$
CREATE PROCEDURE sp_procedure....
```
**Additional context**

**Database type, if appropriate**
MySQL/MariaDB

**Comment by rathboma** [comment]
Hey! You don't need to use `DELIMITER` at all in Beekeeper Studio, this is a feature of the MySQL cli tool, not MySQL as a whole:

https://docs.beekeeperstudio.io/troubleshooting/#mysql
