### ISSUE TITLE
BUG: Default 'order by' can cause problems with sharded databases

### ISSUE THREAD

**Issue by MrFabio** [beekeeper-studio/beekeeper-studio#1261]
**Is your feature request related to a problem? Please describe.**
When connecting to a Vitess cluster (mysql vtgate) with a sharded keyspace, the `ORDER BY` clause is not supported. Resulting in Error when Viewing the data using the UI:

`Execute: unsupported query: "select * from MyTable order by Id asc limit :redacted1, :redacted2"`

**Describe the solution you'd like**
One way to fix this is to allow the ability to disable that automatic `ORDER BY`, like on the connection settings or at database level.

**Describe alternatives you've considered**
A special "View Data without sorting" context option.

**Additional context**
It only happens when selecting a table that is in a sharded database and we select the option "View Data". When querying via SQL it all works fine if we don't use the sorts as that is a limitation in Vitess.

**Database type, if appropriate**
MySQL with Vitess in a sharded keyspace

**Comment by rathboma** [comment]
Hey, very interesting. I had not thought about this causing a problem for some databases.

It would probably make sense to disable ordering in the default view anyway.

**Comment by rathboma** [comment]
What this should do:
- When opening a table, just do `select * from table limit 100` without an order by (when allowed). Some databases require a sort order if you're only taking a certain amount of records I think.

**Comment by MrFabio** [comment]
I'm happy to report that this issue is fixed. Not sure in what specific version.
I currently use `v3.9.17` and can view data from tables in a sharded database.
