### ISSUE TITLE
FEAT: Add options parameter to connection string (Cockroach Cloud)

### ISSUE THREAD

**Issue by korpa** [beekeeper-studio/beekeeper-studio#1263]
To be able to connect to CockroachCloud an `options` parameter is needed:

`postgresql://xxx:@xxxx.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full&options=--cluster%3Dxxx-xxxx-1234`

Could you please add it.

**Comment by rathboma** [comment]
Yes it's added! It'll be in the next release.
