### ISSUE TITLE
BUG: Bits are not converted back to proper form for insert scripts.

### ISSUE THREAD

**Issue by theOofDoctor** [beekeeper-studio/beekeeper-studio#1264]
**Describe the bug**
Currently in results view/data view, all bits are converted to true/false values (which I do find helpful). One frustrating thing is when you export something as a script (copy row (insert) for instance) those values are not converted back to bits, so I have to manually go through and fix those values before running the script. A small thing, but can be annoying.

**To Reproduce**
1. Open data view of some table that has bit columns
2. Right click on a row
3. Click "Copy Row (insert)"
4. Paste this in a new query window

**Expected behavior**
Bits should be converted back to 1/0 form instead of true/false for insert.

**Screenshots / Gifs**
![image](https://user-images.githubusercontent.com/58712803/173691355-7f1e22f3-ece6-4238-8eed-fb47dd2c998e.png)
![image](https://user-images.githubusercontent.com/58712803/173691456-cd3bd350-f167-4c93-b980-e518438c444a.png)
The second screenshot is of the resulting script, which fails as 'true' is not a valid value for a bit column in SQL server

**Version Information (please complete the following information):**
 - OS: Windows 11
 - App Version 3.5.8
 - Database type and version SQL Server 15.0.2080.9

**Comment by theosherman** [comment]
To expand the issue, exporting a table with boolean values will not serialize properly

JSON...
{ "myBoolValue":"b''" }

SQL...
insert into [dbo].[MyTable] ([myBoolValue]) values ('b''''');

**Comment by theOofDoctor** [comment]
This is also an issue with Dates

**Comment by wmontgomery** [comment]
@theOofDoctor yup, just replicated the initial issue. I'll see what I can do about it. As far as the Dates issue, what exactly are you seeing with that so I can replicate it as well.

@theosherman Replicated that one too. Working on a fix.

**Comment by theOofDoctor** [comment]
@wmontgomery I can't seem to replicate it myself anymore either lol. At some point my dates were being formatted, but now they're all back in raw form so honestly I don't know what to tell you. Should have taken screenshots when it happened, but I was in the middle of work. Sorry about that! I will let you know if I come across it again.

**Comment by wmontgomery** [comment]
@theOofDoctor hahaha, no problem! Hopefully it was just a fluke going on.

**Comment by theOofDoctor** [comment]
@wmontgomery that or I'm going insane. Either way, probably no fault of yours

**Comment by wmontgomery** [comment]
@rathboma PR is ready for review. One outstanding issue is the export feature doesn't 100% mimic the copy row (insert) feature because there is a disconnect between how the SQL is generated between the 2 of those. The export portion getting the right inserts would take quite a bit of work and should probably be its own issue to focus on instead of holding this one up further. Either way, both issues or the inserts from "copy row" and the serialization have been taken care of.
