### ISSUE TITLE
QUESTION:  getaddrinfo enotfound

### ISSUE THREAD

**Issue by leavea** [beekeeper-studio/beekeeper-studio#1266]
**Details:**
When I choose to use the domain name to connect to MySQL, the software will report getaddrinfo enotfound xxxx com.
xxxx. com is my domain name

**Version Information [might be relevant to your issue]**
Operating System:Mac
App Version [help -> about]:Beekeeper-Studio-3.4.3
Database type and version [eg Posgresql 9.3]:mysql

**Screenshot / GIF [if appropriate]**:
A screenshot of the app if that helps

**Comment by rathboma** [comment]
Hey! I don't think this is anything to do with Beekeeper Studio, but rather there's no route to the hostname you provided.

I'm going to close this issue, but if you still have the problem, please re-open and add as much detail as you can to help me debug. Also please check if the same configuration works in other tools.
