### ISSUE TITLE
QUESTION: Pagination issue in Beekeeper studio

### ISSUE THREAD

**Issue by waleeds12** [beekeeper-studio/beekeeper-studio#1268]
I'm getting pagination issue like when I run select query, the studio fetches 5000 records table from the DB and taking 2 to 6 mints to execute. Any help on this?

![image](https://user-images.githubusercontent.com/107856842/174595703-ced4198c-3971-4276-a3c5-3ef36b23f564.png)

**Comment by rathboma** [comment]
Hey! There’s a hard limit of 50k for the results view right now I’m afraid, soon we’ll be working on a way to see everything!

**Comment by rathboma** [comment]
Closing this issue as it’s beeping tracked elsewhere
