### ISSUE TITLE
FEAT: Add "Drop database" and "Drop table" on the context menu (right click) (and truncate, rename?)

### ISSUE THREAD

**Issue by mathias22osterhagen22** [beekeeper-studio/beekeeper-studio#1270]
**Is your feature request related to a problem? Please describe.**
I'm using an ORM during development that is migrating the database.
I need to DROP the table(s) or the database(s) some time to mage the migration pass.
A "Rename" and "Truncate" option would be great as well.

**Describe the solution you'd like**
You right click on the table/database name, a context menu appears with few options like "Drop" / "Rename" / "Refresh" /  "Truncate"

**Describe alternatives you've considered**
I'm using SQL query for now.

**Additional context**
![image](https://user-images.githubusercontent.com/60438474/174639530-8295c948-0df7-4c4d-b158-411c4a69060c.png)

**Database type, if appropriate**
All (I'm using it only for Postgresql till now).

**Comment by wmontgomery** [comment]
Currently working on this issue.

**Comment by wmontgomery** [comment]
PRs have been submitted for truncate and drop table.
