### ISSUE TITLE
Add "abort query" button and hot keys combination

### ISSUE THREAD

**Issue by shootnix** [beekeeper-studio/beekeeper-studio#128]
Hi,
I'm not sure this feature exists already so I decided to create a feature request.
Sometimes you may write query like "update users set balance=1000000 where is_active" and then just forget to specify, for example, id or something like this. So this query adds  1000000 money to all users and sometimes (haha) this is not what you want to gonna happen. 
In this kind of situation I always using "Ctrl + C" keys combination. And it could be awesome to have this combination in Beekeeper Studio.
Thanks!

**Comment by rathboma** [comment]
Same as #185. Yes, lets do this.
