### ISSUE TITLE
QUESTION: $1 is treated as a column

### ISSUE THREAD

**Issue by StephanoAH** [beekeeper-studio/beekeeper-studio#1282]
**Details:**
I want to know how query parameters work because I follow the instructions in the documentation, but $1 is treated as a column and throws an error.

**Version Information [might be relevant to your issue]**
Operating System: Windows 11 Pro 21H2
App Version: Beekeeper Community Edition 3.4.3
Database type and version: MySQL  8.0.29

**Screenshot / GIF [if appropriate]**:
![image](https://user-images.githubusercontent.com/65463808/175775300-5215b803-ca29-406a-98c8-d9d25a2032ea.png)

**Comment by rathboma** [comment]
Try it with `?` instead of `$1`? I think it's a MySQL specific params thing

**Comment by StephanoAH** [comment]
I try with "?" but give a syntax error too

![image](https://user-images.githubusercontent.com/65463808/178290151-f276778b-219c-4685-9470-da67b5c54326.png)

**Comment by rathboma** [comment]
Hey! You can just use `?` with no number for MySQL

**Comment by rathboma** [comment]
Closing this as a syntax error for MySQL. These are great questions to ask in the [Slack Group](https://launchpass.com/beekeeperstud-lvg5276) if you ever get stuck again!
