### ISSUE TITLE
BUG: Export errors do not show in the UI

### ISSUE THREAD

**Issue by jgraber** [beekeeper-studio/beekeeper-studio#1283]
**Is your feature request related to a problem? Please describe.**
If something goes wrong, you need to look at the developer tools to see the error message. While this works, it is not the most user-friendly approach.

**Describe the solution you'd like**
It would be nice to get a pop-up dialog that tells me that there was an error and with enough details that I can create a bug here at GitHub.

- Type of error in the dialog title
- A message for end users on what went wrong
- Expand section with the technical details of the error

**Describe alternatives you've considered**
Looking at the developer tools and scrolling up until I find the right error. What is not so easy as I retry an action if it does not work the first time.

**Additional context**

**Database type, if appropriate**
All types of databases.

**Comment by rathboma** [comment]
Can I ask what errors you are seeing that are not appearing in the UI? I try to surface errors that are useful to the user.

The devtools gets a bunch of error output that can be ignored, but I agree there should be something to report errors at least.

**Comment by jgraber** [comment]
Hi,
I had a problem as described in issue #1275 where the export failed. I got no feedback in the UI and had to open the developer console to see that someting went wrong.

**Comment by rathboma** [comment]
@jgraber sorry about that. Let me mark this as a bug as all errors should create some sort of dialog.

**Comment by davidkaufman** [comment]
This was fixed in
- Issue #472

All export errors (whether query or table exports) are now displayed to the user
