### ISSUE TITLE
BUG Running a selection prompts for parameters even if parameters are not part of query

### ISSUE THREAD

**Issue by lorefnon** [beekeeper-studio/beekeeper-studio#1285]
**Describe the bug**
If we have some parameters in the query buffer, and we select and execute part of the buffer, the editor will prompt for parameters even if the selection does not use any parameters.

**To Reproduce**
1. Open Query Editor
2. Populate text as: 
```
select * from "user" where id in ($1, $2);

SELECT version();
```
3. Select `SELECT version();` only and click 'Run Selection'
4. We get an unnecessary popup asking for parameters 
![image](https://user-images.githubusercontent.com/1449492/175834833-6bd60222-e8a0-4de5-a4e1-9e5a8770e5df.png)

**Expected behavior**
It should ask for parameters only if they are used in the selection being executed

Version Information (please complete the following information):

OS: Ubuntu
App Version 3.4.3
Database type and version Postgres 14.1

**Comment by rathboma** [comment]
Really good find. Thank you. So sorry about this!

**Comment by lorefnon** [comment]
NP, thanks for your work on this repo. Good to see this has been accepted and is on the roadmap.

**Comment by AJRDRGZ** [comment]
Hi, I'm new here, @rathboma Can you assign me this issue?

**Comment by azmy60** [comment]
@rathboma I took a quick check. This was fixed in master, but still an issue in sql server. I made the [PR](https://github.com/coresql/sql-query-identifier/pull/72) for the sql server in `sql-query-identifier` repo a few months ago but it hasn't been published yet.
