### ISSUE TITLE
BUG: Cannot update the port of a saved connection

### ISSUE THREAD

**Issue by teynar** [beekeeper-studio/beekeeper-studio#1288]
**Describe the bug**
When I try to update the port number for an existing connection, it does not update the port and instead it falls back to the previous value

**To Reproduce**
1. Create a new Postgres connection
2. Set any name
4. Save the connection
5. **Select the connection from the list of connections (important)**
6. Change the port number from 5432 to 15432
7. Save the connection

**Expected behavior**
The port should change to 15432, but instead it goes back to 5432

**Screens
![bug](https://user-images.githubusercontent.com/97400690/177144288-5bd43a83-7916-41fb-8ca2-58e5f5a36bf8.gif)**

**Version Information (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - App Version: 3.4.1
 - Database type and version: Postgres

**Comment by wmontgomery** [comment]
Tested on v3.6.2 on macos and wasn't able to replicate. Is this still an issue on the latest version @teynar?

**Comment by teynar** [comment]
I just upgraded from v3.4.1 to v3.6.2 and I cannot reproduce it anymore, so I guess that it is fixed, thank you! @wmontgomery
