### ISSUE TITLE
BUG: Stuck on loading when table is empty

### ISSUE THREAD

**Issue by nook24** [beekeeper-studio/beekeeper-studio#1289]
**Describe the bug**
When I open a empty table, Beekeeper shows `Loading` forever and mostly stuck. It also starts to eat up a lot of CPU usage.

**To Reproduce**
1. Create a empty table in MySQL
2. Double click on the table in Beekeeper

**Expected behavior**
Basically, do not freeze on empty tables :)

**Screenshots / Gifs**
![beekeeper_loading](https://user-images.githubusercontent.com/9019992/177293998-9eeadd58-7d18-46d6-98e2-18e44ed01454.PNG)

**Version Information (please complete the following information):**
 - OS: Windows 10
 - App 3.5.1
 - Database type and version: MySQL 8.0.29-0ubuntu0.22.04.2

**Additional context**
The connection is running via an SSH tunnel

**Comment by PHLAK** [comment]
I've noticed the same happens when filtering a table and it contains zero results.

**Comment by marshallswain** [comment]
And the same thing occurs when you delete the last record in a table.

**Comment by marshallswain** [comment]
I've downgraded to 3.4.3, since the issue doesn't occur in that version.  Only version 3.5 exhibits the issue.

**Comment by liscuate** [comment]
From what I can see there seems to be a memory leak as well. Once the loading appears the memory spikes to almost 4GB.

**Comment by azmy60** [comment]
Somehow the `table` side effect always run when the table is empty.

https://github.com/beekeeper-studio/beekeeper-studio/blob/0e3ed525f0340c10ac7c9266ff01b2b41f7b0502/apps/studio/src/components/tableview/TableTable.vue#L599-L612

`dataFetch()` also gets called a lot.
https://github.com/beekeeper-studio/beekeeper-studio/blob/0e3ed525f0340c10ac7c9266ff01b2b41f7b0502/apps/studio/src/components/tableview/TableTable.vue#L1115-L1196

**Comment by rathboma** [comment]
I've got a fix for this. Of course this is a one line fix. I'm putting out a patch today
