### ISSUE TITLE
Keyboard shortcut: comment line

### ISSUE THREAD

**Issue by codeoholic** [beekeeper-studio/beekeeper-studio#129]
It would be nice if we could use cmd + / to comment queries.

**Comment by mariusa** [comment]
Since `/` isn't a valid comment in SQL, another shortcut might make more sense. VS Code uses Ctrl + Shift + A, for example.

**Comment by keith-hall** [comment]
<kbd>Ctrl + /</kbd> is a standard shortcut in Sublime Text for all languages, and I just tested in VS Code and it works there too...

**Comment by alexeightsix** [comment]
is it possible to re-map this so when i type "gcc" it does the same thing as ctrl + / ?
