### ISSUE TITLE
BUG:All configured authentication methods failed

### ISSUE THREAD

**Issue by nandakumark1** [beekeeper-studio/beekeeper-studio#1292]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots / Gifs**
If applicable, add screenshots or GIFS to help explain your problem.

**Version Information (please complete the following information):**
 - OS: [e.g. Windows/Mac/Ubuntu]
 - App Version [e.g. help -> About Beekeeper Studio]
 - Database type and version [eg Posgresql 9.3]

**Additional context**
Anything else you think might be helpful

**Comment by rathboma** [comment]
Hey, closing this issue as there are no details or any way to replicate. If you have screenshots or any other details, please open a new issue and share them!
