### ISSUE TITLE
BUG: resize column triggers table sort

### ISSUE THREAD

**Issue by jedibird** [beekeeper-studio/beekeeper-studio#1297]
**Describe the bug**
After running a query, when resizing a column in the data results, a sort operation is triggered when the mouse is released.  This means I can't resize a column and maintain the default sort (as specified by the query or engine if no ORDER BY was specified).

**To Reproduce**
1. run a query that returns multiple columns of data
2. using the mouse, click on the little bar between two column headers and drag it left to shrink the size of the column
3. let go of the mouse button
4. notice that the table data is resorted, usually the column to the right of the one that was just resized

**Expected behavior**
The column should be resized but should not trigger a sort.

**Screenshots / Gifs**
Attached video showing the problem.  Watch the column to the left of the one I'm resizing.
https://user-images.githubusercontent.com/95879390/178325709-f07ad2e8-0c3a-42f9-b23a-8c11f737dfac.mov

**Version Information:**
 - OS: Mac
 - App Version: 3.5.1
 - Database type and version: MySQL

**Comment by rathboma** [comment]
Hey! Yes 100% this is a problem I know about.

I'm planning on some work to add a button to the column header for sorting rather than clicking the header, which should fix this.

**Comment by mickaelandrieu** [comment]
I can confirm the issue ✅

**Comment by azmy60** [comment]
Can I work on this?

**Comment by rathboma** [comment]
Sure, but I think it would have to be solved in the tabulator code, not the Beekeeper code

**Comment by azmy60** [comment]
Yeah, I couldn't find the clean way to solve this with the tabulator.

**Comment by olifolkerd** [comment]
@rathboma This functionality is now available via the new `headerSortClickElement` in the 5.4 release.

Cheers

Oli :)

**Comment by rathboma** [comment]
This is fixed in the latest version of Beekeeper (in master). Also @olifolkerd++ - truly a legend
