### ISSUE TITLE
Sql Server: "Invalid object name" when loading a table not under [dbo] schema

### ISSUE THREAD

**Issue by vincent** [beekeeper-studio/beekeeper-studio#130]
Hi, 
First: nice project, thank you.

I'm using the Sql Server connector. 
When I open from the sidebar a table that is not under the dbo schema, it shows "Errors" in the result area, and "Invalid object name" in the the console.

It seems to work fine when I open a table under the dbo schema, so I guess we're just missing the schema somewhere.

<img width="834" alt="Capture d’écran 2020-05-18 à 10 20 18" src="https://user-images.githubusercontent.com/5623/82190384-3d3a6980-98f1-11ea-817a-d3bb5dbca8c8.png">

**Comment by rathboma** [comment]
Bah, you're right, sorry about that, I'm not passing through the schema. Should be an easy fix.
