### ISSUE TITLE
BUG: Results stuck on 'loading' when there are zero results for the query

### ISSUE THREAD

**Issue by gurdeepsembi** [beekeeper-studio/beekeeper-studio#1302]
**Describe the bug**
Open an empty table, or run a SELECT query which does not return any rows, the results screen remains stuck on 'loading'

**To Reproduce**
1. Connect to DB
2. Open a table with no rows in it, or run a SELECT query which will return no matching rows
3. Results section stays stuck on 'loading'

**Expected behavior**
Results screen to show zero rows returned

**Screenshots / Gifs**
![image](https://user-images.githubusercontent.com/9131620/178942307-e1a81757-d5fd-43ff-a32a-281b4d5bfa79.png)

**Version Information (please complete the following information):**
 - OS: Win 11
 - App Version 3.5.1
 - Database type and version MariaDB

**Additional context**
This only started happening when we updated to the latest release earlier this week

**Comment by mloureiro** [comment]
It also happens in:
- OS: OSX 12.4
- App version: 3.5.1
- MySQL v8.0.23

**Comment by SpaceNerden** [comment]
It also happens in:

OS: Arch Linux
App version: 3.5.1
MySQL

Logs (Maybe less than a minute's worth?):
[1658131805873.log](https://github.com/beekeeper-studio/beekeeper-studio/files/9130421/1658131805873.log)

**Comment by azmy60** [comment]
See #1289
