### ISSUE TITLE
FEAT: Better Windowing for Multiple Connections

### ISSUE THREAD

**Issue by kpconnell** [beekeeper-studio/beekeeper-studio#1306]
**Is your feature request related to a problem? Please describe.**
As a multi-platform multi-customer developer, I need to easily know which connection I am using and switch between connections  because otherwise it is difficult to find a previous connection when working on multiple simultaneously.

- **Describe the solution you'd like**
1) put the connection name in the title
2) Add a window menu showing the title of opened windows

**Describe alternatives you've considered**
I really don't want to go back to DbEaver.  Trust me.   And don't overcomplicate it with a tree view of connections.  Most of the time people have one window per connection, this is a good design convention.

**Comment by rathboma** [comment]
Love it. Let’s do it
