### ISSUE TITLE
How to connect to databases in phphmyadmin inside Beekeeper studio ?

### ISSUE THREAD

**Issue by HzK-0210181** [beekeeper-studio/beekeeper-studio#1309]
so i have localhost running using xampp i wanna access those databases , i don't see it in the docs even tho i set the port on the mysql port 3306 

**Version Information [might be relevant to your issue]**
OS: Manjaro Linux x86_64 :
App Version 3.4.1:
Database type and version [MySQL]:

**Screenshot / GIF [if appropriate]**:
A screenshot of the app if that helps

**Comment by rathboma** [comment]
Hey! You'll need to know what host the database is running on. If it's running on your machine you'll need `localhost` as the host. Then you should just be able to specify your username and password.

Going to close this issue, but if you have problems like this again you can also [join our Slack chat room](https://launchpass.com/beekeeperstud-lvg5276) and ask there -- you should get a quicker response!
