### ISSUE TITLE
BUG: High CPU for process

### ISSUE THREAD

**Issue by peterolivo** [beekeeper-studio/beekeeper-studio#1311]
**Describe the bug**
Weird process hogging my machine.

**To Reproduce**
Not sure, it just happened when I was trying to load a CSV to a postgresql db

**Expected behavior**
Not kill my cpu.

**Screenshots / Gifs**
<img width="485" alt="Screen Shot 2022-07-21 at 4 46 13 PM" src="https://user-images.githubusercontent.com/7140818/180333405-aa2d51ba-bb64-45f1-ab53-5778aaf53fc1.png">

**Version Information (please complete the following information):**
- Hardware: M1 Macbook Air 
- OS: Mac 12.4  
 - App Version: 3.6.2
 - Database type and version: Posgresql 14.4

**Additional context**
Unfortunately I was unable to find relevant logs.

**Comment by rathboma** [comment]
Hey! Sorry you're seeing this. Can you describe in more detail what you were doing with the app and maybe provide a screenshot?

Otherwise it's super hard for me to debug -- and I want to fix this if it's a problem!

**Comment by peterolivo** [comment]
Yeah i figured it would be. The pid shot it all I have.
It was after I closed the app and the logs had been flushed which was weird.
I will see if I can reproduce and open it back up if I get any thing more useful.
