### ISSUE TITLE
FEAT: Query Magics Format Enum

### ISSUE THREAD

**Issue by not-night-but** [beekeeper-studio/beekeeper-studio#1313]
**Is your feature request related to a problem? Please describe.**
My company has a lot of enums in our db (UserType, ContractType, etc.). We use SQL Server, which means there is no super clean way to use enum values (they are just stored as integers, sometimes we have a table for the enum, but those aren't always updated and are honestly quite useless 😂 )

**Describe the solution you'd like**
It could be nice to be able to define enums in user settings or something, and then be able to format those columns with query magics.
Eg.
In user settings define an enum called UserType with values: [
  {1, "Default"},
  {2, "Guest"},
  {3, "Admin"}
]

then you can format a column with 
```sql
SELECT
    UserType as UserType__format__enum__UserType
FROM [dbo].[User]
```

and then the string values are displayed in place of the integer values.

**NOTE**
This is just something that I know I would use ALL the time, but it could just be specific to me. I would totally be willing to help develop this, though I understand that the solution would probably have to be close source.
Thanks for reading!

**Database type, if appropriate**
SQL Server (and any others that don't support enums natively.)

**Comment by rathboma** [comment]
I can probably fairly easily make a plugin system for people to write their own magics.

Let me see what I can cobble together tonight for you :-)

**Comment by rathboma** [comment]
Ok, I think your idea of user types could work well.

Questions:

- It sounds like you sometimes store data like that in the database, but not always, is that right?
- If you store it in the database, why not just join on it?

**Comment by theOofDoctor** [comment]
Yeah we do sometimes store it in the database, but that is kinda just vestigial code at this point. I think we used to do something with it, but now we just do everything through the Entity Framework. Half of the enums we use aren't in the db and the ones that are are way out of date, which is why this would just be more useful, cause those tables are purely for developer reference, it makes no difference to the functionality or presentation of the data.

**Comment by rathboma** [comment]
What about a directory in Beekeeper's config directory called something like `enums` where you could put JSON files with this information in it? Beekeeper could read these at start and load them into the enum formatter.

Format would be something like this:

in `<config>/enums/user_type.json`
```json
{
  name: "user_type",
  values: [
    { id: 1, title: "Default"}
  ]
```
That'd work right?

**Comment by theOofDoctor** [comment]
Yeah for sure!

**Comment by rathboma** [comment]
Hey! Sorry this hasn't moved yet. It's been a crazy few months and I've barely had chance to do any coding. I think this is a fun feature though and I'm going to do it soon :-)
