### ISSUE TITLE
BUG:  failed to download/update to new version (MacOS Catalina)

### ISSUE THREAD

**Issue by davidkaufman** [beekeeper-studio/beekeeper-studio#1314]
**Describe the bug**

Beekeeper failed to download/update to new version (MacOS)

**To Reproduce**

1. Launch Beekeeper Studio 3.5.1 (after an update such as 3.6.2 is available) 
2. Dialog appears, asking if you want to download new version:
![update-manager](https://user-images.githubusercontent.com/2336122/180912865-f47fe26d-abb3-4d43-abe8-3677c911e821.png)
3. Press Download
4. Message appears, telling you to "Hold tight":
![Hold-tight](https://user-images.githubusercontent.com/2336122/180913066-1c48cc21-321c-413d-a7e0-8cb438cfe695.png)

5. Wait.
6. Wonder.
7. Look in Downloads folder...
8. Scratch head...
9. Give up waiting, exit and restart
10. Open developer tools / console 
11. clear all the noise
12. Press download again

Console says:
~~~js



› sysctl shell command to check for macOS Rosetta environment failed: 
Error: Command failed: sysctl sysctl.proc_translated sysctl: unknown oid 'sysctl.proc_translated'
~~~

**Expected behavior**

- first of all, the dialog could be a little more helpful
- What is the new version that's available, i can haz a link to the release notes before deciding? :smile:
- After pressing the Download button, some info "Downloading version X.Y.Z from https://url.tl/path/x.y.x.dmg... " would be nice
- some progress would be great too! "[18 of 115MB] downloaded, guestimated time remaining: 7 minutes..."
- and then, of course, effectively trapping and reporting any errors like the one above
 
**Screenshots / Gifs**
If applicable, add screenshots or GIFS to help explain your problem.

**Version Information (please complete the following information):**
 - OS: MacOS Catalina 10.15.7
 - App Version: 3.5.1 
 - Database type and version: n/a

**Comment by davidkaufman** [comment]
An update, and a correction:

### Update

On the 2nd or third try, the new version did download and install.  I left BeeKeeper open for a long time while doing something else, and when it came back, it was prompting me to restart to install the update and, after restarting, the update was installed!

I was able to recreate this bug however, by simply re-installing the older version.

Correction:

The console says:
`12:48:01.979 (update-manager)` (_then_): `› sysctl shell command to check for macOS Rosetta environment failed: 
Error: Command failed: sysctl sysctl.proc_translated sysctl: unknown oid 'sysctl.proc_translated'`

Investigating code now.  @rathboma feel free to assign this to me :-)

**Comment by davidkaufman** [comment]
Not sure if this is related, but I get these 2 console errors (and a popup error when dev tools are closed):
~~~json
App.vue:78 Error: getaddrinfo ENOTFOUND true
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67)
mounted @ App.vue:78
vue.runtime.esm.js:1897 Error: getaddrinfo ENOTFOUND true
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67)
st @ vue.runtime.esm.js:1897
~~~
after _downgrading_ by overwriting the new 3.6.2 app with the old 3.5.1 app and deleting my `~/Library/Application Support/beekeeper-studio` directory, immediately after re-launching the "downgraded" app

along with both upgrade dialogs stacked:
![image](https://user-images.githubusercontent.com/2336122/181069865-1d7a661c-625a-499e-a1fa-21be463277e2.png)

(which seems a bit much)

**Comment by davidkaufman** [comment]
Getting these same `EONOTFOUND` error popups ^^^ on Ultimate 3.6.6

**Comment by rathboma** [comment]
Uck, looks like thats a bug with Rosetta detection. Are you on MacOS? What version?

**Comment by davidkaufman** [comment]
Yep: MacOS Catalina 10.15.7

**Comment by davidkaufman** [comment]
Running a 2012 MacbookPro 🤓  still works like a champ, but it can't upgrade past Catalina :sad_nerd_face

**Comment by davidkaufman** [comment]
This looks like it might be helpful: 

How to Detect Apple Silicon and Rosetta from within a Shell Script 
https://indiespark.top/software/detecting-apple-silicon-shell-script/

**Comment by rathboma** [comment]
Honestly I took the code right from the electron builder codebase and modified it to allow an override, so I expected it to work a bit better. Shouldn't be a super hard fix. I'll take a look later this week.

**Comment by rathboma** [comment]
I might ping you to test it as I don't have a catalina machine handy :-)

**Comment by rathboma** [comment]
Note for future Matthew: Best thing is to check for MacOS < BigSur, and to just return the intel version if true

**Comment by rathboma** [comment]
sysctl kern.osrelease < 20.0.0

**Comment by rathboma** [comment]
So after thinking about this - I'm not going to fix it. Catalina is nearing EOL, and will likely stop getting security updates this year.

I'm happy to accept a PR to fix this, but I just don't have time to work on it. Closing for that reason, but please submit a PR if you care enough!
