### ISSUE TITLE
BUG: Columns width reset after doing certain things

### ISSUE THREAD

**Issue by azmy60** [beekeeper-studio/beekeeper-studio#1318]
**Describe the bug**
Columns width reset unexpectedly after doing certain things like:
- Maximizing/unmaximizing
- Refreshing table
- Clicking filter button
- Applying filter
- Sorting rows by clicking the column header

**To Reproduce**
1. Resize a column
2. Do one of the things on the list above ☝️

**Expected behavior**
Column sizes should not reset regardless of window state / data loading.

**Screenshots / Gifs**

https://user-images.githubusercontent.com/38707148/181548493-98c64148-53dd-4e89-ab98-790f957cad0c.mp4

**Version Information (please complete the following information):**
 - OS: Debian GNU/Linux 11
 - App Version 3.62
 - Database type and version MySQL 8.0.29

**Additional context**
I think to fix this, we can add a reserved option for user to click, specifically to reset the table view (including columns width, filter, order, etc..) maybe in settings menu (the gear icon in status bar).

**Comment by rathboma** [comment]
I have this fixed in master! However I'm waiting on https://github.com/olifolkerd/tabulator/issues/3970 to merge in order to put together the new release.
