### ISSUE TITLE
FEAT: Search bar in structure

### ISSUE THREAD

**Issue by RobinHerzog** [beekeeper-studio/beekeeper-studio#1319]
**Is your feature request related to a problem? Please describe.** Yes, I have table with 100 column and no way to search

**Describe the solution you'd like** A search bar that is flexible and search in fulltxt

**Describe alternatives you've considered** Using another soft

**Additional context**
Add any other context or screenshots about the feature request here. (we love screenshots with red circles if the request is for something visual)

**Database type, if appropriate**
Does this feature only relate to a specific type of database? (eg Postgresql)

**Comment by rathboma** [comment]
Hey! Yes this is coming soon, duplicate of #1291 .

I'm going to close this issue, but I'm tracking this feature request and we're going to do it!
