### ISSUE TITLE
FEAT: hide system tables

### ISSUE THREAD

**Issue by anilsg** [beekeeper-studio/beekeeper-studio#1320]
There may be users who like to see system tables but I can't remember a time when I've used them. There are collections of system tables in some databases that clutter the view and just add a bit more of unnecessary data on screen that means your eyes have additional filtering to do.

Preferably there could be some way of hiding the system tables from view. I personally wouldn't mind this in settings as I use system tables so infrequently. Others may want that per database, maybe as part of the connection info, or just a live UI toggle somewhere, perhaps even in the filters list "System" could be distinguished from "Tables".

**Comment by azmy60** [comment]
I'll take a look

**Comment by azmy60** [comment]
Possible solution is to make a list of common system table names and then hide the tables based on that. Any better idea to detect system tables?

**Comment by anilsg** [comment]
Isn't there a hierarchy that's known for each database system?

Postgres always uses two schemas  `information_schema` and `pg_catalog`. There seems to be a default schema of `public` that new user tables are created in if another schema is not specified, and otherwise the user can create any number of schemas.

So for Postgres you would just hide `information_schema` and `pg_catalog`, but this approach may not work for MS SQL Server (shrug) but I'm not sure how MS SQL Server manages its tables.

Perhaps you could make individual schemas "hideable" and that could then work for all databases that support schemas.

**Comment by azmy60** [comment]
Thanks for the feedback! I just made a postgres db in railway.app. And it seems like there are much more than just `information_schema` and `pg_catalog`, which kind of makes sense for an app service to have extra schemas.

I imagine if other services (like supabase) also have their own schemas too 🤔.

**Comment by davidkaufman** [comment]
FYI: for MySQL and MariaDB, the system tabes are named:

`mysql`
`information_schema`
`performance_schema`

**Comment by anilsg** [comment]
Maybe to short circuit all this complexity and potential pain just allow the user to hide schemas per connection.

**Comment by azmy60** [comment]
Also, maybe to hide tables, functions, or any items in the list.
