### ISSUE TITLE
QUESTION: How to get Beekeeper to honor PATH for newer SQLite version?

### ISSUE THREAD

**Issue by ts1g** [beekeeper-studio/beekeeper-studio#1328]
**Details:**
MacOS currently uses SQLite3 v 3.37, while v 3.39.x now (finally!) offers FULL JOIN. Since /usr/bin where macOS SQLite v 3.37 resides is protected, it is necessary to install newer versions of SQLite3 in /usr/local/bin and then set the PATH in BASH or ZSH profile to a) point to the newer version of SQLite and b ) set priority of newer version at /usr/local/bin as higher than the /usr/bin version installed at the base macOS.

Updating PATH to push newer SQLite version to top of priority list works for Terminal and other programs (confirmed by using _which -a sqlite3_ in Terminal and _sqlite_version()_ in other apps) but Beekeeper returns the older 3.37  version of SQLite when sqlite_version() used. Is there to force Beekeeper to honor PATH priority?

**Version Information [might be relevant to your issue]**
Operating System: macOS
App Version [help -> about]: 3.6.2
Database type and version [eg Posgresql 9.3]: SQLite 3.39.2

**Screenshot / GIF [if appropriate]**:
A screenshot of the app if that helps

**Comment by rathboma** [comment]
Hey! I actually have to publish a new binary with the new SQLite linked. I'll do that soon!

**Comment by rathboma** [comment]
Happy to accept a pr with the new version of better-sqlite3 if someone has time to do it

**Comment by ts1g** [comment]
@rathboma Thanks for the clarification; I pulled down Ultimate trial to see if it worked, but looks like it's also the same limitation. Nice UX!
