### ISSUE TITLE
BUG: Yarn install showing gyp errors

### ISSUE THREAD

**Issue by atticusliu** [beekeeper-studio/beekeeper-studio#1329]
**Describe the bug**
After a coworker built our own version of BKS, I'm trying to get the repo up and running on locally on my macOS M1 machine. After cloning the repo, I'm seeing issues with just running `yarn install.`

**To Reproduce**
1. On an M1 MacBook without BKS or any of its packages, simply run `yarn install.`

**Expected behavior**
For the `yarn install` to succeed without error.

**Screenshots / Gifs**
Please see attached.
<img width="772" alt="Screen Shot 2022-08-02 at 19 57 19" src="https://user-images.githubusercontent.com/3667216/182496374-5e9f0617-053f-4d60-bb7a-ca5a85ab0e65.png">
<img width="777" alt="Screen Shot 2022-08-02 at 19 57 29" src="https://user-images.githubusercontent.com/3667216/182496395-210b50df-c5fb-4d8f-9a7b-c8d82aaf2d44.png">

**Version Information (please complete the following information):**
 - OS: macOS
 - App Version: studio/n
 - Database type and version: Postgresql 12

**Additional context**
N/A

**Comment by atticusliu** [comment]
Thanks for your time and energy, I greatly appreciate it.

**Comment by rathboma** [comment]
That module is optional. I think there's a flag to skip optional compiles.

Also try node 14

**Comment by atticusliu** [comment]
I'm sorry but I'm completely unfamiliar with this process. How can I find the flag to skip these optional compiles?
