### ISSUE TITLE
BUG:  always loading

### ISSUE THREAD

**Issue by b0123456789** [beekeeper-studio/beekeeper-studio#1331]
![aaa](https://user-images.githubusercontent.com/21169660/182980834-82c5042b-b3a6-4820-bebe-b4ed6df1e9ee.png)

**Comment by rathboma** [comment]
What version are you using?

**Comment by b0123456789** [comment]
![222](https://user-images.githubusercontent.com/21169660/182988676-b8d3fb96-a734-4e6b-8cfa-ca799dff9e10.png)

**Comment by b0123456789** [comment]
It be correct after installed new version.
