### ISSUE TITLE
BUG: View struct input problem

### ISSUE THREAD

**Issue by b0123456789** [beekeeper-studio/beekeeper-studio#1332]
![444](https://user-images.githubusercontent.com/21169660/182994862-c619de23-54a6-423a-a4ad-f6c2df24798f.png)

beekeeper-studio   v3.6.2

Cannot input after clear data. 

step:
> choose a datatype from menu 
> clear choosed value
> click input

**Comment by not-night-but** [comment]
Closing as this doesn't seem to be an issue anymore
