### ISSUE TITLE
QUESTION: Slow data loading

### ISSUE THREAD

**Issue by FatuityCookie** [beekeeper-studio/beekeeper-studio#1336]
**Details:**
When there is a lot of data in the table, it takes a long time to load。After a few minutes, the page cannot be displayed normally！

**Version Information [might be relevant to your issue]**
Operating System: window 11
App Version [help -> about]: 3.5.1
Database type and version : mysql 8.0.28

**Screenshot / GIF [if appropriate]**:
![image](https://user-images.githubusercontent.com/46119806/183796059-d3dfdb9f-f4e4-4fc1-ac2e-428daf785048.png)
![image](https://user-images.githubusercontent.com/46119806/183796340-a2822dc9-f986-4d94-93b3-28a6b472a298.png)

**Comment by rathboma** [comment]
Please upgrade to the latest version! I fixed this :-)

**Comment by FatuityCookie** [comment]
upgrade  to latest version 3.6.2 ,When there are 7548700 rows of data in the table, the “view data” cannot be loaded. Can 200 or 500 rows be displayed by default?

**Comment by FatuityCookie** [comment]
![image](https://user-images.githubusercontent.com/46119806/183823388-10b27fb7-7489-4370-bb55-3348c9bfb500.png)

**Comment by rathboma** [comment]
Hmm, that doesn't seem right. Questions:

1. What database and database version are you using?
2. Are there any errors in the dev console (help -> show dev console)
3. Can you share the schema of the table this happens to, and a sample of the data? (so we can reproduce it)

**Comment by FatuityCookie** [comment]
Thank you for your reply. I think I know what the problem is Apache Doris( adopts MySQL protocol ),but` **SHOW KEYS FROM `ga_check` WHERE Key_name = 'PRIMARY'**` cannot operate normally.

Finally, thank you again
