### ISSUE TITLE
BUG: Say something here

### ISSUE THREAD

**Issue by devklick** [beekeeper-studio/beekeeper-studio#1343]
**Describe the bug**
I'm trying to drop my database. It's name contains uppercase characters. When I execute the `DROP DATABASE` command, it seems like Beekeeper Studio is converting the command (or at least the database name) to lowercase, and then hits an error because no database with the _lowercase_ name exists. 

**To Reproduce**
1. Create a database containing uppercase characters (you may have to do this outside of Beekeeper Studio)
2. Try to drop the database using the `DROP DATABASE` command from a SQL script in Beekeeper Studio

**Expected behavior**
The database exists. The exact name of the database has been specified in the script. The database should successfully be dropped. 

**Screenshots / Gifs**
![image](https://user-images.githubusercontent.com/58235000/184555666-3f75db93-bb9a-4581-b620-4c00752f845a.png)

**Version Information (please complete the following information):**
 - OS: Zorin OS, v16.1
 - App Version 3.6.2
 - Database type and version Postgres 14.3

**Additional context**
Anything else you think might be helpful

**Comment by kaharlichenko** [comment]
It's not Beekeeper. According to SQL standard names are case insensitive, so it's up to the implementation to normalize them to all lowercase or all uppercase.

As a rule of thumb avoid mixed case for SQL names. But if you must do so, quote them:

```sql
DROP DATABASE "ExampleEcom";
```
