### ISSUE TITLE
FEAT: Support IAM Authentication for Amazon Redshift

### ISSUE THREAD

**Issue by bcelenza** [beekeeper-studio/beekeeper-studio#1345]
**Is your feature request related to a problem? Please describe.**

AWS allows an end user to use temporary credentials federated by an IAM user or role. You can read more about it [here](https://docs.aws.amazon.com/redshift/latest/mgmt/generating-user-credentials.html).

**Describe the solution you'd like**

I'd like for the ability to _optionally_ use IAM to authenticate to an Amazon Redshift cluster.

**Describe alternatives you've considered**

The current alternative or workaround is to manually [call the `GetClusterCredentials` API using the AWS CLI](https://docs.aws.amazon.com/cli/latest/reference/redshift/get-cluster-credentials.html).

**Additional context**
Add any other context or screenshots about the feature request here. (we love screenshots with red circles if the request is for something visual)

**Database type, if appropriate**

Amazon Redshift only (for now!).

**Comment by rathboma** [comment]
I''m
