### ISSUE TITLE
QUESTION: beekeeper doesn't decrypt

### ISSUE THREAD

**Issue by franklin106** [beekeeper-studio/beekeeper-studio#1349]
**Details:**
I have a program that has a query that presents decrypted data from encrypted database fields.  When I run the program everything is fine the query presents the data as expected,  

If I try to run the same query in the beekeeper it doesn't decrypt..  yes the decrypt command is there yes the decryption key is correct.

Is this a known issue?

**Version Information [might be relevant to your issue]**
Operating System: Windows
App Version [help -> about]: 3.6.2
Database type and version [eg Posgresql 9.3]: Mysql 8

**Screenshot / GIF [if appropriate]**:
A screenshot of the app if that helps

**Comment by not-night-but** [comment]
@franklin106 Hey! Is this still an issue you're experiencing? I'm just going through old issues and trying to clear out things that have been fixed/are irrelevant now.

If this is still an issue, could you provide me with some SQL that reproduces the issue? 

Thanks,
Day

**Comment by rathboma** [comment]
Closing as no information to reproduce
