### ISSUE TITLE
QUESTION: How can I see postgresql messages?

### ISSUE THREAD

**Issue by marcosazevedo2112** [beekeeper-studio/beekeeper-studio#1351]
*Details*
Where do I see postgresql messages?
Like `RAISE NOTICE` output, the interface is not very welcome to find it

*Version*
db: Postgresql 14.3
Beekeeper version: 3.6.2

**Comment by not-night-but** [comment]
The application could definitely benefit from richer error messages. i'm going to close this issue in favour of #1520

**Comment by rathboma** [comment]
This is psql specific syntax we should support

**Comment by Anquuni** [comment]
This feature is still needed and relevant for us. When is this planned to be implemented and released?
