### ISSUE TITLE
BUG:Not all schema are displayed

### ISSUE THREAD

**Issue by RobinHerzog** [beekeeper-studio/beekeeper-studio#1352]
**Describe the bug**
On a Redshift database, I see many schema. Many new one were introduced by our data team but I can not see them. However, my colleague with another software can see them and I can query them from SQL builder.

**To Reproduce**
Open your DB and refresh schema list

**Expected behavior**
See all schemas

**Version Information (please complete the following information):**
- Mac
- 3.62
- Redshift

**Comment by ameckl** [comment]
I can confirm that I experience the same bug.

* MBP M1
* v3.6.2
* MSSQL

**Comment by khadnot-dc** [comment]
Same here. I'm unable to see the new schema in Beekeeper Studio, but I'm able to see it using DBeaver.

**Comment by not-night-but** [comment]
@RobinHerzog @ameckl @khadnot-dc Could one/all of you provide some basic SQL that can reproduce this issue?

@ameckl (I suspect the schema not having tables probably has something to do with the issue)

@khadnot-dc  What DB are you using?

Apologies for how long it took for yall to get a response, we're a small team and most of us have other jobs. 

Hope to hear from you soon! Thanks,
Day

**Comment by alex-96-eng** [comment]
+1

**Comment by not-night-but** [comment]
@alex-96-eng would you be able to send me a minimal sample of SQL to reproduce this?

**Comment by khadnot-dc** [comment]
@not-night-but 

CREATE TABLE employee_info (
    employee_id INTEGER primary key,
    first_name character varying, 
    last_name character varying
);

INSERT INTO employee_info (employee_id, first_name, last_name)
VALUES 
    (123, 'John', 'Doe'),
    (321, 'Jane', 'Bean'),
    (734, 'Mike', 'Johnson');

**Comment by not-night-but** [comment]
On what schema?

**Comment by alex-96-eng** [comment]
I appear to have fixed it by adding a table to the schema that was not visible. Once I had applied a random table to the schema and then hit refresh, the client now shows it.

**Comment by rathboma** [comment]
Hey! Just a note that we're also fixing an issue with external tables/schemas not showing -- #561
