### ISSUE TITLE
FEAT: table browser: 'like' filter should convert json/jsonb columns to text automatically when querying

### ISSUE THREAD

**Issue by mariusa** [beekeeper-studio/beekeeper-studio#1354]
**Is your feature request related to a problem? Please describe.**
A table with json/jsonb columns can be queried with
`select * from "tbl" where col::text like '%whatever%'`

In table browser, selecting a jsonb column, filter `like` and typing `%whatever%` results in `Error No data`

**Describe the solution you'd like**
table browser: 'like' filter should convert json/jsonb columns to text automatically when querying
so that for user  typing `%whatever%` gives same result as the query above.

**Database type, if appropriate**
Postgresql

**Comment by rathboma** [comment]
Hey! So the basic filter is really just for basic querying, click the little `<>` button to enter whatever filter you like!
