### ISSUE TITLE
FEAT: Support connecting as root user without password

### ISSUE THREAD

**Issue by martin-braun** [beekeeper-studio/beekeeper-studio#1357]
**Is your feature request related to a problem? Please describe.**
On my MacBook I have installed MariaDB via [Homebrew](https://formulae.brew.sh/formula/mariadb#default). I don't wish to deal with passwords locally, but it is possible to connect to the database via root like so:

```sh
$% sudo mysql -u root    
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 126
Server version: 10.8.3-MariaDB Homebrew

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> USE my-db
Database changed
MariaDB [my-db]> exit
Bye
```

Trying to login via root isn't possible: 

<img width="595" alt="Access denied for user 'root'@'localhost' after trying to login with default values and root as username." src="https://user-images.githubusercontent.com/24259245/186953639-4246ef61-83b6-4004-b4a5-314474537167.png">

Putting in my root password won't change the outcome. If I don't enter any username, the connection works, but I cannot find my database `my-db` that I created with the root account previously. 

**Describe the solution you'd like**
It would be nice if I could decide to give the database driver root permissions to connect. Maybe a "Login as root" checkbox?

**Describe alternatives you've considered**
I will have to give my user a password now, but I don't really like this solution

**Additional context**
Nothing more to say

**Database type, if appropriate**
MariaDB

**Comment by rathboma** [comment]
Probably you can do that with a socket connection, my guess is that's how your command line version is working. Try changing 'host and port' to socket

**Comment by martin-braun** [comment]
@rathboma I figured my socket with `mysql> show variables like 'socket';`. It still returns "Access denied for user 'root'@'localhost'" in all three variants (no username, only root, root with password).

**Comment by rathboma** [comment]
probably because you were using `sudo mysql -u root`, you usually don't want to use sudo to run the mysql cli, but likely connecting using sudo changes some things.

Probably easiest to just create a new user:

```sql
CREATE USER 'sammy'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'sammy'@'localhost' WITH GRANT OPTION;
```

from: https://www.digitalocean.com/community/tutorials/how-to-create-a-new-user-and-grant-permissions-in-mysql

**Comment by 7104423** [comment]
I had the same problem with Beekeeper (and with DBeaver also). It helped me to change the password to the empy password. That should be default configuration, but it seems, the empty password is stored like invalid value in the database...

Login to the database via terminal (I use Linux, but it should be same for MacOS):

```bash
sudo mysql -u root
```

- Enter password for `sudo`, not for database account...

Check user system table:

```sql
SELECT host, user, password FROM mysql.user;
```

If the password for your root account is `invalid` (or whatever else than empty cell), then set the empty password again:

```sql
ALTER USER 'root'@'localhost' IDENTIFIED BY '';
exit;
```

Now try to login via Beekeeper with root account and password leave empty.

The solution above worked for both of the Beekeeper and DBeaver.

**Comment by rathboma** [comment]
Going to close this, as not really a BKS issue to fix
