### ISSUE TITLE
 QUESTION: How to log in via ddns link

### ISSUE THREAD

**Issue by dicklim** [beekeeper-studio/beekeeper-studio#1358]
Hi! I am using Beekeeper to connect my MySql in a ubuntu server.
however I found that I can not change 'username'@'localhost' into 'username'@'%' or 'username'@'ip'.

Here is my detail:
![图片](https://user-images.githubusercontent.com/55022062/187021440-c3bf465b-ac35-4c1b-a97d-ae5a8776b45f.png)

Version
db: MySql 8.0.30-0ubuntu0.20.04.
Beekeeper version: 3.6.2

**Comment by rathboma** [comment]
Hey! Closing this as I think this was just accessing a local database.
