### ISSUE TITLE
BUG: Application freezing when opening two windows

### ISSUE THREAD

**Issue by sm3136** [beekeeper-studio/beekeeper-studio#1359]
**Bug Description**
When opening two windows of Beekeeper on Ubuntu 22.04 with the initial window being zoomed in it causes the application / entire system to freeze up.

**To Reproduce**
1. Open an initial Beekeeper window
2. Press Ctrl + 9 in order to zoom it in one click
3. Open another window of Beekeeper
4. At this point the computer begins to freeze

**Expected behavior**
I would expect to be able run two windows of Beekeeper. This way I can have multiple databases open. (Currently working on a data migration program)

**Version Information:**
 - OS: Ubuntu 22.04 
 - GNOME Version: 42.2
 - Windowing System: X11
 - App Version: 3.6.2
 - Database Type and Version: N/A (Freezes before selecting a database)

**Additional context**
I am not 100% sure that this is something you fellas can fix. I have a strange feeling that it might be caused by the window manager since it affects the entire system after attempting to open the two Beekeeper windows, but in good practice I am bringing it up here just in case it is on your end. If there is anything else you need let me know.

**Comment by rathboma** [comment]
Hey! Future Matthew here -- we haven't been able to replicate this, so closing for now
