### ISSUE TITLE
Can't use  Group as table name

### ISSUE THREAD

**Issue by isgj** [beekeeper-studio/beekeeper-studio#136]
I have a table with the name `Group`. When I click the icon to open the table in a new tab I get
![image](https://user-images.githubusercontent.com/20517048/82447293-605b4980-9aa8-11ea-9aca-2c7d0e1593de.png)

if I run the query
```sql
select * from Group
```
the error is
![image](https://user-images.githubusercontent.com/20517048/82447689-e7a8bd00-9aa8-11ea-9d35-6012647a3d96.png)

If I use the backticks around the table name
```sql
select * from `Group`
```
it works(no autocompletion for the column names though).

DB in use MySql
BeeKeeper version: 1.3.1

**Comment by rathboma** [comment]
Ah, yes when opening tables it should escape the table names in the select query. Sorry about that.

**Comment by rathboma** [comment]
This should be fixed in Release 1.4

**Comment by isgj** [comment]
@rathboma it looks like this one is reproducible again (version 1.8.7)

![image](https://user-images.githubusercontent.com/20517048/97425681-b7e0c980-1912-11eb-9a20-70b93a5a6a8d.png)

**Comment by rathboma** [comment]
Yuck. Sorry about that. I'm in the process of adding some unit tests to the databases to prevent these sorts of regressions.

**Comment by rathboma** [comment]
@isgj what database were you accessing? MySQL or Maria DB? What version?

**Comment by isgj** [comment]
MySQL 5.7 minor version should be the last. We're in the process of upgrading to version 8

**Comment by rathboma** [comment]
closing thanks to the fix. I'll be sure to add unit tests on my branch

**Comment by isgj** [comment]
Thanks for the fast response
