### ISSUE TITLE
FEAT: load_extension for sqlite

### ISSUE THREAD

**Issue by vespadj** [beekeeper-studio/beekeeper-studio#1360]
**Details:**
Can extensions be used and how?
```sql
SELECT load_extension('./re.so'); 
SELECT REGEXP_REPLACE('this year is 2021', '[0-9]+', '2050');
```
[https://github.com/nalgeon/sqlean](https://github.com/nalgeon/sqlean)

It returns the error: There was a problem: not authorized.

**Version Information [might be relevant to your issue]**
Operating System: Linux
App Version [help -> about]: 3.6.2

**Comment by rathboma** [comment]
This is coming to the ultimate edition soon!

**Comment by rathboma** [comment]
Some notes for future implementer:

- This should be an option on the connection screen, not allowed in SQL
- https://github.com/WiseLibs/better-sqlite3/blob/master/docs/api.md#loadextensionpath-entrypoint---this

**Comment by davidkaufman** [comment]
Note to self:
https://sqlite.org/loadext.html#loading_an_extension
> Note that different operating systems use different filename suffixes for their shared libraries. Windows uses ".dll", Mac uses ".dylib", and most unixes other than mac use ".so". If you want to make your code portable, you can omit the suffix from the shared library filename and the appropriate suffix will be added automatically by the [sqlite3_load_extension()](https://sqlite.org/c3ref/load_extension.html) interface.

**Comment by davidkaufman** [comment]
Steps to compile extensions (macos):
~~~
git clone git@github.com:sqlite/sqlite.git
cd sqlite

# beekeeper uses better-sqlite3 v5.4.3 released 9/24/19, which uses sqlite 3.29, so
git co version-3.29.0 

# ssqlite docs say to build from somewhere outside the project dir, so
cd ..
mkdir -p sqlite-extensions/v3.29.0
cd sqlite-extensions/v3.29.0
../../sqlite/configure
make  # takes about 7 minutes on my old mac

# make sure we compiled the right (old) version
./sqlite3 --version
3.29.0 2019-07-10 17:32:03 fc82b73

# Compile rot13.c and csv.c file against sqlite 3.29.0
gcc -I. -g -fPIC -dynamiclib ../../sqlite/ext/misc/rot13.c -o rot13.dylib
gcc -I. -g -fPIC -dynamiclib ../../sqlite/ext/misc/csv.c -o csv.dylib
~~~

Test rot13:
~~~sql
./sqlite3
SQLite version 3.29.0 2019-07-10 17:32:03
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.

sqlite> .load rot13
sqlite> SELECT rot13('abc');
nop
~~~
We can rotate alpha strings 13 characters to the right in SQL!

And load CSV files as virtual tables too:
~~~bash
# create a sample.csv file
echo -e 'col_text,col_int\napples,3\noranges,5' > sample.csv
~~~

~~~sql
./sqlite3
SQLite version 3.29.0 2019-07-10 17:32:03
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.

sqlite> .load csv
sqlite> CREATE VIRTUAL TABLE temp.t1 USING csv(filename="sample.csv");
sqlite> SELECT * FROM t1;
col_text|col_int
apples|3
oranges|5
~~~

**Comment by davidkaufman** [comment]
Here are the loadable compiled extension files for macos:
[sqlite3-v3.29.0-extensions.tar.gz](https://github.com/beekeeper-studio/beekeeper-studio/files/11260003/sqlite3-v3.29.0-extensions.tar.gz)

**Comment by davidkaufman** [comment]
But, as always, it's not that easy
![image](https://user-images.githubusercontent.com/2336122/233682578-1aec1060-143c-4b4c-873a-ee9dd6e8b429.png)

Digging in to that 
~~~js
SqliteError: no such function: rot13
    at Database.prepare (/Users/dkaufman/dev/bks/ultimate/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
    at eval (webpack-internal:///./src/lib/db/clients/sqlite.js:1942:34)
    at new Promise (<anonymous>)
    at runQuery (webpack-internal:///./src/lib/db/clients/sqlite.js:1939:12)
    at _callee3$ (webpack-internal:///./src/lib/db/clients/sqlite.js:1977:22)
    at tryCatch (webpack-internal:///../../node_modules/@babel/runtime/helpers/esm/regeneratorRuntime.js:137:17)
    at Generator.eval [as _invoke] (webpack-internal:///../../node_modules/@babel/runtime/helpers/esm/regeneratorRuntime.js:117:24)
    at Generator.eval [as next] (webpack-internal:///../../node_modules/@babel/runtime/helpers/esm/regeneratorRuntime.js:168:21)
    at asyncGeneratorStep (webpack-internal:///../../node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:9:24)
    at _next (webpack-internal:///../../node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:31:9)
~~~

We queries through better-sqlite3's prepare(), which doesn't know about new function that the extension provides.  The only workaround seems to be running them with it's exec() function which:
a. "performs worse and is less safe than using [prepared statements](https://github.com/WiseLibs/better-sqlite3/blob/master/docs/api.md#preparestring---statement), and
b. doesn't take bound parameter arguments, just executes the literal sql.  So... we'd have to roll our own code to quote parameters and modify the sql?  

digging deeper to see if a more recent version of better-sqlite3 addresses this problem...

**Comment by davidkaufman** [comment]
Got it working!

Nevermind all that ^^^ 


(Note to self: it helps if you load the `rot13`, rather than the `csv`, extension before testing the `rot13()` function 😁)

**Comment by davidkaufman** [comment]
Should support loading multiple extensions at the same time too..

**Comment by davidkaufman** [comment]
This is done!

**Comment by davidkaufman** [comment]
@vespadj wrote:
> 
> https://github.com/nalgeon/sqlean

This is a great resource for precompiled extensions -- thanks!

**Comment by vespadj** [comment]
Thanks!
in which version will we see the update and how will the functions be loaded?

**Comment by davidkaufman** [comment]
Should be in the next release, and has been added to the SQLite connection settings as a file picker to load, and an unload button to unload, the custom extension file.
