### ISSUE TITLE
FEAT: Export multiple tables (multiple formats - CSV, JSON, SQL, etc) - this is different from 'backup' which is more opinionated.

### ISSUE THREAD

**Issue by virtualLast** [beekeeper-studio/beekeeper-studio#1368]
**Details:**
I cannot see how to export an entire database - Im using the linux version.

**Comment by afiaudofia** [comment]
Same here. I couldn’t find an export database option.

**Comment by Zerotask** [comment]
Duplicate of #778

**Comment by vardumper** [comment]
same here.

**Comment by rathboma** [comment]
Hey! This isn't supported yet. Coming soon though.

@afiaudofia question -- what format would you want the whole-db export to be in?
@vardumper what format would you want it in?
@virtualLast same question for you -- what format would you want the whole DB export to be in?

I'm assuming SQL that can be run back-in to a new database as an import.

**Comment by rathboma** [comment]
I've taken over this issue to refer to 'export' specifically. I think it's worth making a distinction between backup/restore and export/import.

Export / import - CSV,JSON, etc
Backup / restore - opinionated SQL

**Comment by virtualLast** [comment]
Yeah sql would be the easiest

**Comment by afiaudofia** [comment]
Yes, SQL format.

**Comment by KeshariPiyush24** [comment]
Yes it would be great to have this feature.

**Comment by Santosl2** [comment]
Does anyone have any updates?

**Comment by LeoMoshko** [comment]
+1

**Comment by david-kariuki** [comment]
Is this a TODo or an ongoing development? Is there any update on the same?
