### ISSUE TITLE
AppImage download link is wrong

### ISSUE THREAD

**Issue by marufmax** [beekeeper-studio/beekeeper-studio#137]
This is an issue with website not with the actual project. 
If I navigate to this [https://www.beekeeperstudio.io/download/?platform=appimage](https://www.beekeeperstudio.io/download/?platform=appimage) from homepage, I am prompting downloading an `exe` file. 

Which is wrong, I should download `appimage` file. 

I made it download by visiting GitHub's release section

thanks

**Comment by MarcusMann** [comment]
it happens here too.

**Comment by rathboma** [comment]
lol, typo. Sorry about that. Will fix presently
