### ISSUE TITLE
FEAT: drop column even if is foreign key

### ISSUE THREAD

**Issue by mcanepa** [beekeeper-studio/beekeeper-studio#1374]
If I try to drop a column from `table A` that is related to another `table B`, then I get this message

> Cannot drop index 'fk_tablea_tableb1_idx': needed in a foreign key constraint

What I would expect is to being able to drop it anyway and for beekeeper to take care of the index dropping for me and perform this backstage:

```
ALTER TABLE `table_a` DROP FOREIGN KEY `fk_tablea_tableb1`;

DROP INDEX `fk_tablea_tableb1_idx` on `table_a`; //I think this one is optional

ALTER TABLE `table_a` DROP COLUMN `id_from_table_b`;
```

**Comment by rathboma** [comment]
Hey! Neat idea, but I think this is probably outside of the scope of the visual structure editor for now. Going to close this issue for now, but may come back to this stuff later on
