### ISSUE TITLE
FEAT: Toggle menu 

### ISSUE THREAD

**Issue by lyhongpon** [beekeeper-studio/beekeeper-studio#1379]
**Is your feature request related to a problem? Please describe.**
Not really a problem. But I like to keep every app I use clean and menu is what I rarely use so I'd like a feature to hide/show it. 

**Describe the solution you'd like**
If you have a menu item inside View -> Hide/Show menu, it's really easy to use.

**Describe alternatives you've considered**
Maybe a preference panel?

**Comment by rathboma** [comment]
Hey! Tracking these issues separately, settings and customization coming soon :-)
