### ISSUE TITLE
syntax error at or near SELECT

### ISSUE THREAD

**Issue by Juang999** [beekeeper-studio/beekeeper-studio#1382]
I just used beekepeer, I want to see the structure of tables, I got an error when want to see the structure of table
![Screenshot_2022-09-20_13-28-58](https://user-images.githubusercontent.com/70432761/191184103-13d76037-9cb8-4be9-a19f-d9cd88558703.png)

**Comment by not-night-but** [comment]
@Juang999 I know this was ages ago, but is this still an issue for you?
