### ISSUE TITLE
QUESTION: Is multiselect + copy now limited to the paid versions?

### ISSUE THREAD

**Issue by johnknoop** [beekeeper-studio/beekeeper-studio#1383]
I've previously been able to select multiple rows and copy to clipboard, but that now seems to be unavailable. I'm running the community edition. Has these features been limited to paid versions, or is there a bug?

**Comment by rathboma** [comment]
Hey! That feature was kind of broken, lol.

It's coming back, I'm just waiting for an upsteam change to tabulator first.

**Comment by rathboma** [comment]
Pr: #1326 <--- this one

**Comment by johnknoop** [comment]
Thanks
