### ISSUE TITLE
FEAT: add new database

### ISSUE THREAD

**Issue by mcanepa** [beekeeper-studio/beekeeper-studio#1388]
A button to create a new database is needed here, maybe next to the refresh icon?

That should open a popup to enter a name

![Captura-de-pantalla-de-2022-09-27-11-41-51](https://user-images.githubusercontent.com/25961439/192560379-efac5e26-9e78-40e5-b257-f9933ee50db7.png)

**Comment by jesperordrup** [comment]
+1

**Comment by WeeHorse** [comment]
+1

**Comment by pizsd** [comment]
+1

**Comment by rathboma** [comment]
This is done!
