### ISSUE TITLE
SQL Server 2005 - no tables found

### ISSUE THREAD

**Issue by lorenzoganni** [beekeeper-studio/beekeeper-studio#139]
I'm trying to open a SQL Server 2005 database.
Connection and database listing is fine, but after a few seconds "finding tables" no tables are shown (_There are no tables in *TABLENAME*_).
Other db management apps correctly list all the 100+ tables.

Not sure if Beekeper is meant to be compatible with a 2005 db.

**Comment by rathboma** [comment]
Hmm,

The driver I'm using DOES support all the way back to SQL Server 2000, but can't say I have an instance of SQL Server 2005 to test against.

The query I'm using to get table names is 

```
    SELECT
      table_schema,
      table_name
    FROM information_schema.tables
    WHERE table_type NOT LIKE '%VIEW%'
```
And to get columns:

```
    SELECT column_name, data_type
    FROM information_schema.columns
    WHERE table_name = '${table}'
    ORDER BY ordinal_position
```

Can you check if these work on 2005? If not we can figure out the right syntax

**Comment by lorenzoganni** [comment]
Tried both queries, they fail. 
Turns out the database has a case-sensitive collation.

The following queries are fine with SQL Server 2005:
```
    SELECT
      table_schema,
      table_name
    FROM **INFORMATION_SCHEMA.TABLES**
    WHERE table_type NOT LIKE '%VIEW%'
```
and
```
    SELECT column_name, data_type
    FROM **INFORMATION_SCHEMA.COLUMNS**
    WHERE table_name = '${table}'
    ORDER BY ordinal_position
```

**Comment by rathboma** [comment]
Interesting, I'm not that familiar with the variation in sql servers but do you think that would cause problems in newer versions if I capitalized those table names?

**Comment by lorenzoganni** [comment]
Unfortunately, I'm not familiar with that too... from a little search it doesn't seem to matter wheter it's uppercase or lowercase in newer versions, but can't tell for sure. 
I do not have newer SQL Server instances to test them against.

**Comment by rathboma** [comment]
Ok thanks! I'll do some tests and figure it out.
