### ISSUE TITLE
FEAT: The ability to delete multiple rows at one time

### ISSUE THREAD

**Issue by Zerotask** [beekeeper-studio/beekeeper-studio#1394]
**Is your feature request related to a problem? Please describe.**
During development I sometimes want to delete one, multiple or all rows of a table.

**Describe the solution you'd like**
1. Option to delete all:
Right click on the table name -> delete all rows
Option to press ctrl + a and then press del
Possibly a button somewhere (at the bottom?) to enter a delete mode (where I can check specific rows to delete them)

2. Option to delete a single row
A the moment you have to right click on the row -> Delete Row. It would be great to simply select a row and the press del

3. Option to delete multiple rows
Select with the mouse multiple rows, then a) press del or right click -> Delete Selected Rows
Probably a delete mode (see above) where you can check specific rows (or all) and then delete them; kinda lika a bulk mode

**Describe alternatives you've considered**
- Right click and delete one by one
- Run a SQL statement
- Use a different program

**Database type, if appropriate**
In my case MySQL/MariaDB, but would be a use case for other DBMS' too.

**Comment by rathboma** [comment]
Some of this is here:

right click in sidebar -> truncate deletes all data.

Some is coming soon - i have an open branch with improvements for row selection behavior, which will allow multi-delete

**Comment by andradei** [comment]
Hello. Any news on this feature?
