### ISSUE TITLE
FEAT: Option to not run an update on db but just send the queries to the clipboard

### ISSUE THREAD

**Issue by Gabb1995** [beekeeper-studio/beekeeper-studio#1397]
**Is your feature request related to a problem? Please describe.**
Yes my problem is that I only have read access to production databases, and whenever I do an update of a row I get denied from the db obviously and then I have to write the sql query manually and copy paste it to my devops team.

**Describe the solution you'd like**
I should have an option that instead of running the update, it just sends the queries to my clipboard. So if I change 3 rows on beekeeper but dont have the right to run the update, I can just generate the sql and send it to my team.

**Describe alternatives you've considered**
Manually writing the query

**Additional context**

**Database type, if appropriate**

**Comment by not-night-but** [comment]
@Gabb1995 This was fixed with #1541
