### ISSUE TITLE
BUG: USE database syntax should change the active database in the GUI

### ISSUE THREAD

**Issue by davedgd** [beekeeper-studio/beekeeper-studio#1398]
**Describe the bug**
Right now, USE syntax does not seem to work as expected as far as the GUI is concerned. One issue is that the USE keyword does not receive syntax highlighting, although it does work fine (testing on MariaDB in this case). More importantly though, selecting a database via USE does not result in the GUI showing that database as active via the dropdown in the top left (see first screenshot below). Moreover, due to this, it is entirely possible to CREATE and then USE a new database without any relevant tables showing up in the Entities list (see the second screenshot), which can be confusing to end users (in my case, students).

**To Reproduce**
1. Connect to a database
2. Write syntax to USE a specific database
3. Notice lack of changes in the active database within the GUI

**Expected behavior**
The USE keyword should receive syntax highlighting and also make the database in question active within the GUI itself (perhaps including a refresh of the database list if needed if CREATE is involved).

**Screenshots / Gifs**
<img width="1312" alt="Screen1" src="https://user-images.githubusercontent.com/4490587/195449559-a6e8846c-f9eb-4726-b079-b573504693b0.png">
<img width="1312" alt="Screen2" src="https://user-images.githubusercontent.com/4490587/195449600-d9a9de04-ed56-499d-931d-abaa176c3cba.png">

**Version Information (please complete the following information):**
 - OS: macOS (and Windows)
 - App Version 3.6.2
 - Database type and version MariaDB 10.8.5

**Additional context**
N/A

**Comment by rathboma** [comment]
I agree it should syntax highlight, but not sure it should change the whole gui state. I agree it should apply to the scope of the queries being run though.

**Comment by rathboma** [comment]
I’m going to create another ticket for the highlighting #1449 .
going to close this as I don’t think switching the ui when running a use is something we’ll do tbh.
