### ISSUE TITLE
Beekeeper 1.4 Can’t be opened in MacOS

### ISSUE THREAD

**Issue by manngo** [beekeeper-studio/beekeeper-studio#140]
I have tried the usual right-click open method, and my security settings allow non-appstore applications.

Currently running MacOS Catalina 10.15.4. Previous version of Beekeeper worked well.

**Comment by manngo** [comment]
Maybe it’s just the ZIP version on the GitHub page. The DMG version on the main site is opening properly.

**Comment by rathboma** [comment]
Yeah only the dmg is signed, sorry for the confusion!

**Comment by manngo** [comment]
Ah, that explains it. Thanks
