### ISSUE TITLE
BUG: sqlite3 bool field problem

### ISSUE THREAD

**Issue by mshzsh** [beekeeper-studio/beekeeper-studio#1408]
**Describe the bug**
When I want to change the value of a boolean field in the sqlite3 database, I encounter the following error:
`SQLite3 can only bind numbers, strings, bigints, buffers, and null`
beekeeper only allows entering `true` and `false` values.

**Screenshots / Gifs**

![ssbeekeeper](https://user-images.githubusercontent.com/41986782/197481980-31fd6b4b-c13a-4a11-9f68-f05bd5f1a2e9.png)

**Version Information:**
 - OS: Arch Linux x86_64 6.0.2
 - App Version 3.6.2
 - Database type and version sqlite3

**Comment by davidkaufman** [comment]
I'm having trouble recreating this problem.  When I create sqlite3 tables with bool columns, I'm able to update them to any value (any integer, any string, etc) without that error message, on both Beekeeper v3.6.2 and v3.7.3 🤔 

@mshzsh can you show me the full schema of the table in your screenshot above? (right click the table name in left pane and choose "SQL: Create" from the dropdown menu or, in sqlite3 cli run "`.schema users`" (in case it's a view, constraint or function that your table is referencing that causes the error...)

Also, please post your sqlite3 version: `SELECT sqlite_version()` (mine returns `3.37.2`)

@rathboma can you reproduce this? Maybe it's a Linux thing (I'm back on a Mac, my Linux Desktop box is ill)

Thanks!

-dave

**Comment by mshzsh** [comment]
Now I tested with another device (my laptop) and this problem still exists.

    OS: Arch Linux x86_64 6.0.12-arch1-1
    beekeeper: 3.6.2
    sqlite3: 3.37.2

`
![20230101_23h15m58s_grim](https://user-images.githubusercontent.com/41986782/210183139-14d54cc8-7794-45eb-bd7a-05ed1f9300d5.png)
![20230101_23h24m06s_grim](https://user-images.githubusercontent.com/41986782/210183142-8ce258c9-945d-4afb-aeb9-4e6731db3cac.png)
`

**Comment by davidkaufman** [comment]
Thanks for the extra info @mshzsh!  I'm gonna resurrect my Ubuntu box and see if i can make this happen there...
