### ISSUE TITLE
Not getting any results from SELECT query when switching databases in the query itself

### ISSUE THREAD

**Issue by manngo** [beekeeper-studio/beekeeper-studio#141]
The following query on my database:

```sql
USE australia;
SELECT * FROM images;
```

gets me no results. I don’t think it is running the second query.

The table appears in the list of Tables & Views, and the connection appears to be successful.

Beekeeper 1.4.0. Currently running MacOS Catalina 10.15.4.

**Comment by rathboma** [comment]
There should be a 'results 1/2' drop-down in the bottom right? Also- try just switching databases with the drop down in the top left?

**Comment by rathboma** [comment]
*bottom left.

Might be that you need to switch dbs in the ui. I'll do some tests.

**Comment by manngo** [comment]
I missed that drop down with the result sets. Thanks.
This leads on to a separate feature request which I will post.
