### ISSUE TITLE
FEAT: Show comments on the table structure

### ISSUE THREAD

**Issue by Karlies** [beekeeper-studio/beekeeper-studio#1410]
Hey, I'm using beekeeper to connect my postgresql, I comment a lot for my co-workers ,but I can't see it when I click [View Structure] . Now there are only [Name, Type, Nullable, Default Value and Primary]
If you can add a column of  [Comment], it would be very useful for development.

**Comment by vioulo** [comment]
> 

hi， how did you do it？
Also, how to display comments for tables？

**Comment by GKyomen** [comment]
Hi, I would really like to see comments too. Is there a way or a prevision to when this feature will be done?
