### ISSUE TITLE
FEAT: Allow copying results to clipboard as rich text

### ISSUE THREAD

**Issue by bkane-msft** [beekeeper-studio/beekeeper-studio#1414]
**Is your feature request related to a problem? Please describe.**
I'd like to copy the results of my table into a word document. 

**Describe the solution you'd like**
I'd like the download button to have a "Copy to Clipboard (Rich Text Table)" option.
![image](https://user-images.githubusercontent.com/92759008/199109683-6de90790-f44e-4fa2-aae7-3036c0e87c3d.png)

**Describe alternatives you've considered**

I can use the [this script](https://github.com/bbkane/dotfiles/blob/master/bin_common/bin_common/copy_as_rtf.py) to convert a csv into rich text on MacOS, but it's very cumbersome

**Comment by rathboma** [comment]
The upcoming 3.7 adds the markdown format!
