### ISSUE TITLE
App wants me to see Query Magics

### ISSUE THREAD

**Issue by secretgspot** [beekeeper-studio/beekeeper-studio#1427]
Constantly keeps popping up with Format Results with Query Magics

![image](https://user-images.githubusercontent.com/203323/201800485-2228e263-16ea-41ee-b4c6-c3d777c73ed1.png)

click on it to see why it's annoying me only to be met with 

![image](https://user-images.githubusercontent.com/203323/201800532-38a49e88-7170-4476-a9ac-7a889c8dcf0c.png)

**Comment by rathboma** [comment]
Hey! Hmm it should go away permanently if you dismiss it, does it not?

Also I think I just fixed the link in the latest release, sorry about that!

**Comment by rathboma** [comment]
Hey, going to close this. Please re-open if you find the notice doesn't permanently go away when clicking the `x`
