### ISSUE TITLE
BUG: Cannot refresh opened table

### ISSUE THREAD

**Issue by Runae** [beekeeper-studio/beekeeper-studio#1428]
It started after the latest update. The table doesn't refresh it's content upon pressing the update button.
In console there is this

<img width="543" alt="Screen Shot 2022-11-15 at 15 36 55" src="https://user-images.githubusercontent.com/18416889/201847307-42fd2615-0aa3-4e9c-84d0-a755f3610e60.png">

**Version Information:**
 - MacOS 12.5.1 (Chip: Apple M1 Pro)
 - App Version 3.7.4
 - Posgresql 14.5

**Comment by mkvlrn** [comment]
Can confirm, but as a really easy workaround for the time being, just reordering the table by clicking one of the headers the table will refresh.

**Comment by rathboma** [comment]
fixed
