### ISSUE TITLE
Show Triggers, Stored Procedures, and Functions

### ISSUE THREAD

**Issue by reeceahar** [beekeeper-studio/beekeeper-studio#143]
I notice that HeidiSQL has a very neat way of allowing you to quickly add Triggers, Stored Procedures and Functions, it would be great to see this feature. It's listed amongst the tables when you select a Schema but when you open it there is a specific design to make it easier to add them.

**Comment by rathboma** [comment]
Yeah we're planning on having a section underneath (tables and views) with this information

**Comment by gnovaro** [comment]
Add Events too

**Comment by rathboma** [comment]
I think this is actually a good first issue -- we have hooks in the various database client libraries to get functions and procedures, they just need 'plumbing in' so to speak

**Comment by rathboma** [comment]
see also #329

**Comment by phillpafford** [comment]
Any update on the progress of this feature?

**Comment by rathboma** [comment]
I have an active development branch, but work has slowed down a little due to covid and homeschooling unfortunately. 

It should be in the next major point release (1.9)!

**Comment by empz** [comment]
I'm on 1.12 and I do see stored procedures in the list but it's pretty useless. I can't see their definitions. 

What's the use of this if not being able to right-click "CREATE/ALTER command in New Query" or something like that?
