### ISSUE TITLE
BUG: cannot get SQL for a materialized view on Postgres

### ISSUE THREAD

**Issue by m3Lith** [beekeeper-studio/beekeeper-studio#1432]
**Describe the bug**
If you have a materialized view on a Postgres DB, you cannot get SQL's `CREATE` script.

**To Reproduce**
1. Have/Create a materialized view.
    1.1. E.g., `CREATE MATERIALIZED VIEW mat_view_test AS SELECT * FROM some_table LIMIT 10;`.
3. Find and right click on it in the "Entities" list on the left panel.
4. Click on "SQL: Create".
5. See error: `Can't find script for mat_view_test (materialized-view)`.

**Expected behavior**
A new query tab opens with the view's SQL script.

**Version Information**
 - OS: macOS Ventura
 - App version: 3.7.9
 - Database type and version: Postgres 13.7

**Comment by rathboma** [comment]
Thanks! Good catch.

**Comment by lanzoninicola** [comment]
I believe this issue is connected to #1461, and a viable solution to the problem may have been found as describe here #1502
