### ISSUE TITLE
BUG: Highlighting query causes syntax error

### ISSUE THREAD

**Issue by cyounkins** [beekeeper-studio/beekeeper-studio#1436]
**Describe the bug**
Highlighting part of a query causes a syntax error. Clearing the highlight without changing the query corrects the issue.

**Screenshots / Gifs**
<img width="491" alt="Screen Shot 2022-11-18 at 11 02 39 PM" src="https://user-images.githubusercontent.com/346185/202833366-06cf86d6-f632-454a-a147-eb262a6a2ca2.png">

**Version Information (please complete the following information):**
 - OS: macOS 12.6
 - App Version: 3.7.9
 - Database type and version: Postgres 11.16

**Comment by rathboma** [comment]
Hey! When you highlight text, the `run` button turns into `run selected`, so it tries to run the selected text. Click the arrow next to the run button to run something different.

**Comment by cyounkins** [comment]
It does make sense when you see that the button text changes, but I never click the button and I've never noticed that the button text changes. I always use the keyboard shortcut to run, and my focus is always on the query.
