### ISSUE TITLE
Question about new features

### ISSUE THREAD

**Issue by ricardomac** [beekeeper-studio/beekeeper-studio#1440]
### Discussed in https://github.com/beekeeper-studio/beekeeper-studio/discussions/1439

<div type='discussions-op-text'>

<sup>Originally posted by **ricardomac** November 21, 2022</sup>
I'd like to start contributing and have a question: when developing a new feature, do I need to deploy it to all supported databases?

I already solved some resources, but I didn't do the PR because I couldn't solve it for some banks</div>

**Comment by rathboma** [comment]
Hi! No you don't need to. I can help you add a flag to other databases to indicate the feature is not supported. Please open a PR and we can help :-)

**Comment by rathboma** [comment]
Going to close this
