### ISSUE TITLE
BUG: Quick search does not show saved queries

### ISSUE THREAD

**Issue by nceight** [beekeeper-studio/beekeeper-studio#1441]
**Describe the bug**
I have table named `fin_zones` and saved query file named `insert_fin_zones`. When quick searching "zones", it show both as result. But when searching "insert", it show no result.

**To Reproduce**
1. When searching "zones"
![image](https://user-images.githubusercontent.com/33314691/204219979-c06b2810-95c1-43b1-8ce5-d801ac34801c.png)

2. When searching "insert"
![image](https://user-images.githubusercontent.com/33314691/204220191-34a37764-3d71-4d9a-b549-1122a7517095.png)

**Expected behavior**
Quick searching "insert" should show `insert_fin_zones`.

**Version Information (please complete the following information):**
 - OS: Linux 6.0.10-arch2-1
 - App Version: 3.7.10
 - Database type and version: MySQL 8.0.25

**Comment by rathboma** [comment]
Hmm, that’s weird. Good catch!

**Comment by tomaskudlicka** [comment]
I'm looking at this bug, but it's probably already been fixed. So I would close this ticket.
<img width="628" alt="Screenshot 2023-03-18 at 7 34 03" src="https://user-images.githubusercontent.com/103044576/226089599-67f7c044-b206-4bb1-bd23-a162d5fdfc86.png">
<img width="673" alt="Screenshot 2023-03-18 at 7 34 14" src="https://user-images.githubusercontent.com/103044576/226089609-dfa9b519-2c62-45d9-9b68-396b917cceba.png">

**Comment by nceight** [comment]
I just checked with the most recent version, and it has been fixed. Thanks.
