### ISSUE TITLE
SQL Auto Complete isn't working

### ISSUE THREAD

**Issue by menjilx** [beekeeper-studio/beekeeper-studio#145]
Hi,
Anyone encountered the same issue as what I've encountered? I tried to run some basic SQL but the editor won't show or recommend any "auto-complete" SQL syntax.

Am I missing something here?

Thanks!

**Comment by rathboma** [comment]
@menjilx What database are you using?

Try pressing ctrl+space (or cmd+space) to force the auto-complete suggestions to appear.

It should automatically pop up when typing `from `, and `table.`, or `alias.`

**Comment by menjilx** [comment]
> @menjilx What database are you using?
> 
> Try pressing ctrl+space (or cmd+space) to force the auto-complete suggestions to appear.
> 
> It should automatically pop up when typing `from `, and `table.`, or `alias.`

Typing "Select" or "Update" won't auto-complete but after typing the complete keyword like "Select" the autocomplete works fine already.

**Comment by sundowndev** [comment]
It works great for me with PostgreSQL 9.6, so far I only tested tables and fields with aliases

**Comment by rathboma** [comment]
I'm gonna close this issue, but do have a private ticket for myself -- I want to totally overhaul the SQL editor with a full SQL parser that's a lot more smart.
