### ISSUE TITLE
BUG: Interval column sorting is incorrect

### ISSUE THREAD

**Issue by atrejut** [beekeeper-studio/beekeeper-studio#1466]
**Describe the bug**
Having a (postgres) database column of type 'interval' the front-end sorting in beekeeper studio is not correct --  see screenshot (the fourth entry of 27mins is in the wrong place).

![image](https://user-images.githubusercontent.com/6804206/210206920-5806c1e7-a30b-469b-aab9-8b9c13ac900f.png)

with the changes proposed in #1465 the behaviour is still incorrect:

![image](https://user-images.githubusercontent.com/6804206/210207047-df7a1cfd-35cd-4dbb-af78-0b5841e1651f.png)

(see #1442 for some background to this report).

**To Reproduce**
- create a postgres table with a column of type `Interval`
- insert some values into the table (see screenshots above for values)
- display table in beekeeper studio, and try to sort by the value of the interval column

**Expected behavior**
Sorting is in increasing/decreasing length of the interval.

**Version Information (please complete the following information):**
- OS: Ubuntu
- App Version 3.7.2
- PostgreSQL 14.5 (Ubuntu 14.5-0ubuntu0.22.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0, 64-bit

**Comment by rathboma** [comment]
You are totally right.
