### ISSUE TITLE
QUESTION: Can I export a saved Query on Beekeeper?

### ISSUE THREAD

**Issue by wjj28** [beekeeper-studio/beekeeper-studio#1467]
**Details:**
I saved a query that I will need to use more than once, but I would like to upload it and share with other people.
Is there a way to 'save as' queries to a file or 'export' the query to outside of beekeeper?

**Version Information [might be relevant to your issue]**
Operating System:
3.7.10 Ubuntu 20.04 LTS
Database type and version MySQL

A screenshot of the app if that helps
![beekeeper](https://user-images.githubusercontent.com/39323686/210545247-aac7a013-5b32-4ec1-817e-cb5c5cdce96d.png)

**Comment by joshua1** [comment]
This is a needed feature
