### ISSUE TITLE
BUG: Color sorting is not working

### ISSUE THREAD

**Issue by sunnz** [beekeeper-studio/beekeeper-studio#1469]
it has grouped all the red connections but all the rest are not sorted, see attached screenshot below

**To Reproduce**
Steps to reproduce the behaviour:
1. save a handful of connections of different colours, I got 21, but you are likely to reproduce this before reaching 21 connections
2. see the order in a new beekeeper studio window

**Expected behaviour**

connections sorted by ROYGBIV or VIBGYOR (reversed ROYGBIV).

**Screenshots / Gifs**

![image](https://user-images.githubusercontent.com/1378551/210696486-280429d6-fb60-4428-a15a-3b12557f1535.png)

_database urls are redacted_

**Version Information (please complete the following information):**
 - OS: mac/linux
 - App Version: 3.7.10
 - Database type and version: postgres ^13

**Comment by davidkaufman** [comment]
I noticed this too.  Was hoping to just be able to “pin” my most frequently used connections to the top of the list, but was surprised that I couldn’t, so I tried using the colors and sorting by those, and noticed it only works for one color

**Comment by rathboma** [comment]
lol. So sorry here. Yes we should have pinned connections too
