### ISSUE TITLE
FEAT: selectable fields in the table structure view

### ISSUE THREAD

**Issue by antoine-gallix** [beekeeper-studio/beekeeper-studio#1472]
When coding, I often need to go find the exact name of a column in a table. Using Beekeeper, I open the "table structure" view. Ideally I want to be able to highlight a column name and copy it to clipboard. But I can't even highlight text fields in this view.

Would it be possible to make it happen?

**Comment by rathboma** [comment]
Yes that is totally possible. What about click-to-copy rather than making it selectable?

**Comment by antoine-gallix** [comment]
Both are good to me. As long as the click-to-copy feature is somehow implied visually to the user.

**Comment by rathboma** [comment]
Implementation notes:
Add a `title` to each column that indicates click to copy, highlight the column name on hover, then on click run the copy function which should automatically create the 'copied' notification.
