### ISSUE TITLE
BUG: new update broke the 'create table' function

### ISSUE THREAD

**Issue by dvnschmchr** [beekeeper-studio/beekeeper-studio#1477]
**Describe the bug**
new update broke the 'create table' function

**To Reproduce**
1. Go to a DB
2. Click on the + icon to create a new table
3. See error --> page is blank

**Expected behavior**
should have a table creation gui

**Screenshots / Gifs**
<img width="1512" alt="Screen_Shot_2023-01-13_at_16_35_10" src="https://user-images.githubusercontent.com/45643901/212441584-0b03b54a-dcec-4c17-8b63-7cada3307fed.png">

**Version Information (please complete the following information):**
 - OS: [e.g. Windows/Mac/Ubuntu]
 - App Version [e.g. help -> About Beekeeper Studio]
 - Database type and version [eg Posgresql 9.3]

**Additional context**
Anything else you think might be helpful

**Comment by rathboma** [comment]
Thanks! We'll check it out this weekend

**Comment by wmontgomery** [comment]
Just a note for myself: I checked Postgres 9 and 13 and things looked good. MySQL on the other hand is another story. I'm going to check the other connections to see what's up and get a fix started.
