### ISSUE TITLE
BUG / FEAT: node 18 support

### ISSUE THREAD

**Issue by yfdyh000** [beekeeper-studio/beekeeper-studio#1485]
**Describe the bug**
`# First: Install NodeJS 12 or 14, NPM, and Yarn` in README.
18.13.0 LTS Recommended For Most Users in https://nodejs.org/.

```
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
warning url-loader@1.1.2: Invalid bin field for "url-loader".
error @achrinza/node-ipc@9.2.2: The engine "node" is incompatible with this module. Expected version "8 || 10 || 12 || 14 || 16 || 17". Got "18.12.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**To Reproduce**
1. yarn install

**Expected behavior**
build and the app works.

**Version Information (please complete the following information):**
 - OS: Windows 10
 - App Version N/A
 - Database type and version N/A

**Additional context**
https://github.com/vuejs/vue-cli/releases
See https://cli.vuejs.org/migrations/migrate-from-v4.html for a complete list of breaking changes from v4.
https://github.com/vuejs/vue-cli/issues/7178#issuecomment-1161948724

**Comment by myspace20** [comment]
I've been facing a similar issue for a week now. Have you found a solution ?

**Comment by rathboma** [comment]
Hi! I'm using a specific version of Electron that bundles Node 14, so for local development you'll need that version.

You can use NVM to install those versions if you like!
