### ISSUE TITLE
BUG: Beekeeper's tooltip shouldn't render html

### ISSUE THREAD

**Issue by bediu** [beekeeper-studio/beekeeper-studio#1490]
**Describe the bug**
If you store html in a field, and then hover that field, the tooltip renders the html

![image](https://user-images.githubusercontent.com/43962398/216438125-16bc62b0-5ea6-4057-90a5-6f627593f1fe.png)

**To Reproduce**
Store html and hover over a key

**Comment by rathboma** [comment]
What version are you using? This has been fixed, I think it's in the latest release?

**Comment by bediu** [comment]
@rathboma  I am using 3.7.10 from snap
