### ISSUE TITLE
FEAT: VSCode Extension/Plugin

### ISSUE THREAD

**Issue by luizfelipevbll** [beekeeper-studio/beekeeper-studio#1497]
Currently Beekeeper is my preferred Client for databases, most because its simple and lightweight.

My suggestion is a VSCode Extension to access databases, similiar to [Database Client](https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-database-client2&ssr=false#overview)

**Comment by rathboma** [comment]
Hey! I do not have any plans to integrate this into VSCode in the foreseeable future I'm afraid.

I'm going to close the issue, but I'll def think about it as we grow.

:heart: thank you so much for taking the time to suggest it.
