### ISSUE TITLE
FEAT: `CTRL + F` in query editor

### ISSUE THREAD

**Issue by krystxf** [beekeeper-studio/beekeeper-studio#1501]
**Is your feature request related to a problem? Please describe.**
It's not really a problem, but I found out that I actually use find and replace features a lot when writing code and it's also a feature that is in basically every text editor

**Describe the solution you'd like**
In Query editor
- find in the text  `CTRL + F` or the context menu option
- find and replace `CTRL + H` or the context menu option
- I personally love this VScode feature that highlights all occurrences of selected text (not needed but nice to have in my opinion)
![image](https://user-images.githubusercontent.com/48121710/219513277-ae64e529-dc9f-4778-bf02-68c34094e973.png)

**Describe alternatives you've considered**
Only alternative is to write queries elsewhere

**Additional context**
not needed

**Database type, if appropriate**
all

**Comment by davidkaufman** [comment]
Just sayin...
- find **_next_** `CTRL + G` is one i rely upon heavily, too! 🤣

**Comment by not-night-but** [comment]
@krystxf I believe this is implemented now. CTRL + F for find, and CTRL + R for find/replace

**Comment by wmontgomery** [comment]
Yup, this has been implemented as @not-night-but mentioned
![1501_find](https://github.com/user-attachments/assets/1e0abae1-09ec-4fca-830f-19b40bca3c51)
