### ISSUE TITLE
Feature Request: Add row conter to interface

### ISSUE THREAD

**Issue by BordaLorde** [beekeeper-studio/beekeeper-studio#151]
I think it would be nice to know how many rows a table has without running a separate query.
My suggestion is to put it at the bottom of the window next to the pagination buttons.

**Comment by rathboma** [comment]
agreed! We actually don't control that footer (tabulator controls it). So this does require implementing our own footer and having tabulator 'insert' the pagination buttons using their [control element](http://tabulator.info/docs/4.0/page#element) api

**Comment by rathboma** [comment]
This should be easy now. We have `totalRecords` available, so can just stick this somewhere in the footer, probably on the right next to the 'last update timestamp'
