### ISSUE TITLE
QUESTION: Windows ARM64 Support?

### ISSUE THREAD

**Issue by stormenergy91** [beekeeper-studio/beekeeper-studio#1519]
Since there are versione for ARm64 for both macos and linux, there is also a version for Windows ARM64? The x64 version works on my Sruface Pro X but it is slow. It will be great if there is a native version. Thanks

**Comment by rathboma** [comment]
Hi! I don't have any plans or ability to do this unless someone at msft wants to ship me one of the ARM dev boxes unfortunately.

I'm going to close this comment as can't do this in the foreseeable future

**Comment by linaspasv** [comment]
@rathboma maybe community could help test (I would be more then happy to help)? Windows on ARM has risen in popularity with new snapdragon devices and native Windows ARM64 would be a very welcome.
