### ISSUE TITLE
BUG: opening the SQL:Create view of a stored procedure or function has a syntax error

### ISSUE THREAD

**Issue by michi-zuri** [beekeeper-studio/beekeeper-studio#1522]
**Describe the bug**
The code block is escaped by a named dollar quote (`$function$` code block `$function$`). Regardless of the name given to the code block in the function definition, the dollar quotes are automatically renamed to `$function$`, however a space is introduced between the word function and the second dollar sign in the opening tag: `$function $`, making it a non-valid opening quote. This syntax error leads to the whole code block not being escaped at all and having to remove the space before being able to run the generated sql query.

**To Reproduce**
1. Run this query:

```sql
drop function if exists public.just_fail();

create function public.just_fail() returns void 
as $foo$
  begin
    raise exception 'I refuse!'
    using detail = 'Pretty simple',
    hint = $hint$ There's nothing you can do. $hint$ ;
  end 
$foo$ language plpgsql;
```

2. Right-click on the newly created function in the left side-bar and choose `SQL: Create`
3. See the wrongly inserted space in the opening dollar quotes `$function $` (instead of $foo$) and `$hint $` instead of `$hint$`
5. Also note the incorrect syntax highlighting by the misinterpretation of the single quote within the dollar-quoted string. One important reason (probably the most important reason) for dollar-quoting to exist at all is to allow for the usage of single quotes within the quoted text.
6. Last and least important the semi-colon at the end of the function definition is missing (after the last `$function$`. 

![grafik](https://user-images.githubusercontent.com/26734536/220459211-e65a9c94-0d37-4fcd-bec3-b97dbe693eae.png)

**Expected behavior**
I would expect the dollar-quotes to not be renamed and to have no spaces introduced in their name.

**Version Information (please complete the following information):**
 - OS: Windows Portable
 - App Version 3.8.9
 - Database type and version Posgresql 14.7

**Additional context**
https://www.postgresqltutorial.com/postgresql-plpgsql/dollar-quoted-string-constants/

**Comment by rathboma** [comment]
Thanks for bringing this up! We'll get it fixed.

**Comment by michi-zuri** [comment]
thanks for taking care of this. While you're at it, I noticed another glitch: Let's say I have two functions with the same name, but accepting different parameters: I will always get the same DDL for both functions (which cannot distinguished easily from the sidebar, both having the same name) with the SQL: Create functionality. 
![grafik](https://user-images.githubusercontent.com/26734536/224969466-4ed9c87b-ab35-4b74-b6fa-9f0f74df6674.png)


Here's an example of two results when calling 

```
SELECT pg_get_functiondef(p.oid)
            FROM pg_proc p
            LEFT JOIN pg_catalog.pg_namespace n ON n.oid = p.pronamespace
            WHERE proname = 'inserttwo'
            AND n.nspname = 'public'
```
            
| pg_get_functiondef |
| :------------------------------------------------------------------------------------- |
| `CREATE OR REPLACE FUNCTION public.inserttwo() RETURNS integer LANGUAGE sql AS $function$ insert into test2(val) values(currval('test2_id_seq'::regclass)*2) returning id; $function$`  |
| `CREATE OR REPLACE FUNCTION public.inserttwo(_a integer)  RETURNS integer LANGUAGE sql AS $function$ insert into test2(val) values(currval('test2_id_seq'::regclass)*2+_a) returning val;$function$` |

I think, currently only result row 1 will ever be shown in beekeeper.
