### ISSUE TITLE
Add 'Copy to SQL' to the table editing interface

### ISSUE THREAD

**Issue by rathboma** [beekeeper-studio/beekeeper-studio#1534]
We allow a user to copy the SQL of an action rather than applying it automatically, we should do the same thing for table data changes.

See as reference: alterTable and alterTableSql

**Comment by not-night-but** [comment]
@rathboma Do we just want to do this for table data changes, or should this also be implemented for schema changes?

**Comment by rathboma** [comment]
I think we already do it for screens changes, if not, yes!

**Comment by not-night-but** [comment]
@rathboma I just checked, we definitely do. My bad
