### ISSUE TITLE
add package to official Debian/Ubuntu sources

### ISSUE THREAD

**Issue by alexanderadam** [beekeeper-studio/beekeeper-studio#154]
Are there any efforts to add beekeeper-studio to official Debian/Ubuntu packages?
Did you [submit your packages for inclusion](https://packaging.ubuntu.com/html/packaging-new-software.html#submitting-for-inclusion)?

Is there any issue or thread that I could subscribe to get some updates about that?

**Comment by rathboma** [comment]
I have not yet opened a request to do that. I'm not sure how useful this is given that we already provide both a Snap and a deb repo?

Is there a benefit to be in the official repos?

**Comment by alexanderadam** [comment]
> Is there a benefit to be in the official repos?

1. "Easier" installation for those users who are not so familiar with external sources
2. General visibility because users can simply search install with their standard package manager
3. Also trust: some users have more trust in reviewed packages from their distributions than external repositories
4. Compatibility (not an issue for Snap of course): users don't have to fear that a dependency from an external repository could cause issues

Those are some points that directly came into my mind.

**Comment by farnas123** [comment]
Snap & AppImage didn't work for me on Debian 10. I suspect a bug here.

**Comment by rathboma** [comment]
Closing this issue as it's super duper hard to get in the default repos
