### ISSUE TITLE
EXPLAIN ANALYZE not returning any results

### ISSUE THREAD

**Issue by kamranjon** [beekeeper-studio/beekeeper-studio#155]
Appending `EXPLAIN ANALYZE` before queries is a common way to investigate performance issues with your SQL queries in Postgres. For example:
```sql
EXPLAIN ANALYZE SELECT * FROM table LIMIT 10;
```

When performing the operation it with beekeeper studios it shows now results:
![image](https://user-images.githubusercontent.com/3966239/83041971-ef5ee900-9ff5-11ea-8029-f47adc7efe63.png)

Here is an example output from another SQL client (SqlElectron) - which might give an idea of the type of result that would be expected here:
![image](https://user-images.githubusercontent.com/3966239/83042122-21704b00-9ff6-11ea-963c-90edf6f9d9e3.png)

It's likely the result view only supports columns selected within a query but I have not looked at the code

**Comment by rathboma** [comment]
Thanks! Agreed this makes sense.

**Comment by kamranjon** [comment]
@rathboma did the fix for this get in the latest? just tried it out and seeing same behavior - wasn't sure if the commit referenced in the closure was meant to fix

**Comment by rathboma** [comment]
No, it's merged into master though if you want to pick up a Dev build.

It'll be in the next release, likely next week

**Comment by kamranjon** [comment]
@rathboma I downloaded and tried out this release - https://github.com/beekeeper-studio/beekeeper-studio/releases/tag/v1.4.1 - is that the dev release?

**Comment by rathboma** [comment]
No, you can grab the assets from https://github.com/beekeeper-studio/beekeeper-studio/actions/runs/117334223

They won't be signed, but they will work
