### ISSUE TITLE
BUG: `e.replace is not a function`

### ISSUE THREAD

**Issue by Skgland** [beekeeper-studio/beekeeper-studio#1555]
**Describe the bug**

**To Reproduce**
1. Connect to sqlite databse 
2. Open a table in sqlite database
3. Attempt to delete any row
4. Deletion failed with notification `e.replace is not a function`

**Expected behavior**
Row is deleted or at least an error on the side of the database occurs.

**Version Information (please complete the following information):**
 - OS: Windows 10
 - App Version: 3.8.9
 - Database type and version: Sqlite

**Additional context**
Developer Console

```
14:50:17.918 (sqlite)              › query exception:  TypeError: e.replace is not a function
    at escapeString (js/chunk-vendors.94153028.js:69)
    at f (js/chunk-vendors.94153028.js:54)
    at i.t [as _escapeBinding] (js/chunk-vendors.94153028.js:54)
    at js/chunk-vendors.94153028.js:2530
    at String.replace (<anonymous>)
    at a (js/chunk-vendors.94153028.js:2530)
    at js/chunk-vendors.94153028.js:2591
    at Array.map (<anonymous>)
    at e.exports.e.toQuery (js/chunk-vendors.94153028.js:2591)
    at js/app.ee30a798.js:1
```    

Manually running a querry like `DELETE FROM <table> WHERE <PrimaryKeyColumn> == <PrimaryKeyValue>` works.

**Comment by not-night-but** [comment]
Are you on the latest release or are you building from source? Cause I believe I recently fixed this issue and it's in master.
