### ISSUE TITLE
BUG: Filtering doesn't work and sometimes crashes the app

### ISSUE THREAD

**Issue by juanmvrkemok** [beekeeper-studio/beekeeper-studio#1560]
**Describe the bug**
I have a Postgres DB and when I try to search for a table name, it works fine (only the tables and views matching the name show up listed) but, when I do the same thing typing a function or stored procedure name, it does not list the resulting entities at all, but it shows the number of matching entities.
Also sometimes when filtering the app freezes completely and I have to close and reopen it.

**To Reproduce**
Just filter for a function name in a database.

**Expected behavior**
It should list the matching functions as it does with tables and views.

**Screenshots / Gifs**
![image](https://user-images.githubusercontent.com/126504908/229162685-57482f91-39b8-4240-93c2-8e370beb5ba9.png)

**Version Information (please complete the following information):**
 - OS: Windows 10
 - App Version: 3.8.9
 - Database type and version Postgresql 14

**Comment by rathboma** [comment]
@juanmvrkemok any errors in the dev console? help -> show developer tools (look for red)

**Comment by juanmvrkemok** [comment]
@rathboma nope, nothing shows up in the console
