### ISSUE TITLE
BUG: Relation does not exists

### ISSUE THREAD

**Issue by cainamagoncalves** [beekeeper-studio/beekeeper-studio#1568]
System: Windows 10
Database; PostgreSQL 11.18
App version: 3.9.5

After get the last beekeeper update (3.9.5), all my connected databases don't show any of columns.

When I go to the, Help > Show Developer Tools > Console, and click on any of my tables inside the public folder, I get the following error, "error: relation "public.mytablename" does not exist".

The following image has an example.

![image](https://user-images.githubusercontent.com/60739925/231207654-c5e2ec19-0ebd-4996-a2e4-881ba9992b79.png)

I have tryed to create a new connection but the error persists. All my errors occurs on postgres databases.

**Comment by davidkaufman** [comment]
@cainamagoncalves said
> System: Windows 10
> Database; PostgreSQL 11.18
> App version: 3.9.5

**Comment by osmarpb97** [comment]
@not-night-but 
System: macOS ventura v13.3
Database: PostgreSQL 12.11 on aarch64-unknown-linux-gnu, compiled by gcc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-6), 64-bit
App version: 3.9.5

**Comment by rathboma** [comment]
@cainamagoncalves or @osmarpb97 can you record a screenshare of where you're seeing the problem?

In particular - are there screens that do work?

Here are some screen recording tools: https://docs.beekeeperstudio.io/docs/troubleshooting#tools-for-taking-screen-recordings-when-reporting-issues

**Comment by osmarpb97** [comment]
I

> @cainamagoncalves or @osmarpb97 can you record a screenshare of where you're seeing the problem?
> 
> In particular - are there screens that do work?
> 
> Here are some screen recording tools: https://docs.beekeeperstudio.io/docs/troubleshooting#tools-for-taking-screen-recordings-when-reporting-issues

I already downgraded my version to 3.8 and it seems to be working, so I can confirm that this issue was introduced on the new version, the issue I think is we are trying to access "public.{table_name}" instead of just "{table_name}".

I can help you to record the issue in about 30 min i need to do something quickly.

The issue is basically that we can't access the data on the UI but we can still query data manually through a query

**Comment by oliversd** [comment]
Same problem here:

System: Ubuntu 22.10
Database: PostgreSQL 12.11
App version: 3.9.5

**Comment by not-night-but** [comment]
@cainamagoncalves thanks so much! I will look into this right away

**Comment by not-night-but** [comment]
@cainamagoncalves @osmarpb97 
I believe I've fixed this. Would you be able to download the fix from [here](https://github.com/beekeeper-studio/beekeeper-studio/actions/runs/4670196434) just to make sure it has actually fixed your issue before we deploy it?

**Comment by rathboma** [comment]
(scroll down to 'artifacts' and go to your platform of choice)

It will give a warning during install because these master binaries are not signed, but that can be ignored.

**Comment by osmarpb97** [comment]
@not-night-but No is not fixed at least on MacOS :( 
<img width="1222" alt="image" src="https://user-images.githubusercontent.com/36203999/231245472-f8d5af1d-bfc2-4b50-84de-b61b5250689d.png">
<img width="604" alt="image" src="https://user-images.githubusercontent.com/36203999/231245617-f8939573-e4f2-48c1-8f06-eef44ae83d42.png">

**Comment by not-night-but** [comment]
@osmarpb97 Does the structure view for that table work now though? (right-click table, click 'View Structure')

**Comment by osmarpb97** [comment]
> @osmarpb97 Does the structure view for that table work now though? (right-click table, click 'View Structure')
No, it does not work
<img width="1068" alt="image" src="https://user-images.githubusercontent.com/36203999/231246266-3f8a38c6-fc05-4f59-a3de-2dc5be532c21.png">

**Comment by cainamagoncalves** [comment]
> @cainamagoncalves @osmarpb97 I believe I've fixed this. Would you be able to download the fix from [here](https://github.com/beekeeper-studio/beekeeper-studio/actions/runs/4670196434) just to make sure it has actually fixed your issue before we deploy it?

I will try on windows, one moment.

**Comment by cainamagoncalves** [comment]
@osmarpb97 

I tried on windows, but not work too.

It's the same problem.

![image](https://user-images.githubusercontent.com/60739925/231248579-2834576b-3925-46ea-8e87-ae195d28105e.png)

**Comment by rathboma** [comment]
@oliversd @cainamagoncalves can I have you try one more build?

https://github.com/beekeeper-studio/beekeeper-studio/actions/runs/4670717609

I think we found the cause of the problem

**Comment by cainamagoncalves** [comment]
> @oliversd @cainamagoncalves can I have you try one more build?
> 
> https://github.com/beekeeper-studio/beekeeper-studio/actions/runs/4670717609
> 
> I think we found the cause of the problem

Yeah! You did it!

Nice guys, you're amazing! 😁

**Comment by not-night-but** [comment]
@cainamagoncalves Coolio, thanks for catching that issue! Release should be out soon

**Comment by osmarpb97** [comment]
@not-night-but i tested it on macOS is fixed now! ty!

**Comment by oliversd** [comment]
Everything ok on Linux as well thank you
