### ISSUE TITLE
Can't expand views after collapsing

### ISSUE THREAD

**Issue by sundowndev** [beekeeper-studio/beekeeper-studio#157]
After clicking on "expand all" then "collapse all", the views won't expand anymore, even when refreshing, I have to disconnect and reconnect to make it work again.

![image](https://user-images.githubusercontent.com/16480203/83121293-679adc80-a0d2-11ea-906f-6c6146b24d7a.png)

Env: Linux Ubuntu 18.04 LTS
DB: Postgresql through SSH tunnel

**Comment by rathboma** [comment]
Oh my gosh you're right, yes. Clearly I didn't test that with schemas.

Thanks for identifying!
