### ISSUE TITLE
QUESTION: Source code for magics

### ISSUE THREAD

**Issue by mohamed-aziz** [beekeeper-studio/beekeeper-studio#1574]
**Details:**
I read about the magic query feature, I couldn't find it in the code, is it proprietary  ?
I want to extend it with new types.
Cheers,
Aziz

**Comment by not-night-but** [comment]
Hey!

Query Magics are only in the ultimate edition of the app, so yes it is proprietary.
Are there any specific types you feel like we're missing?

**Comment by mohamed-aziz** [comment]
@not-night-but hey there,
I have links to audio files in my db, I want to listen to them directly on beekeeper

Cheers,
Aziz
