### ISSUE TITLE
BUG: Color sorting ROYGBIV not working

### ISSUE THREAD

**Issue by andreas-ajaib** [beekeeper-studio/beekeeper-studio#1575]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots / Gifs**
If applicable, add screenshots or GIFS to help explain your problem.

**Version Information (please complete the following information):**
 - OS: [e.g. Windows/Mac/Ubuntu]
 - App Version [e.g. help -> About Beekeeper Studio]
 - Database type and version [eg Posgresql 9.3]

**Additional context**
Anything else you think might be helpful

**Comment by not-night-but** [comment]
@andreas-ajaib could you properly fill out the form in the body of your issue? The title is not enough to go off of

**Comment by not-night-but** [comment]
@andreas-ajaib reopening cause I found the issue. My previous fix was overwritten at some point before the merge. Not sure when the fix will be pushed out, but you can track this issue to see when it does!

In the future when reporting issues, it's quite useful for us to see system information (OS, bks version, database version, etc) as well as screenshots, what you're expecting to happen, etc. The more thorough your report, the faster we can fix it.

Thanks for finding this!
Day.
