### ISSUE TITLE
BUG: Only parent table shows in UI when using INHERITS

### ISSUE THREAD

**Issue by ekreutz** [beekeeper-studio/beekeeper-studio#1583]
**Describe the bug**
When a child table `INHERITS` from another parent table, only the parent table shows up in Beekeeper's UI. The child table is totally hidden, and unfamiliar users connecting to the DB might never be aware that it exists.

___

**To Reproduce**

Step 1: In a fresh database, run for instance the following SQL:

```sql
/* Create schema just for kicks */
CREATE SCHEMA my_schema;

/* Create parent table */
CREATE TABLE my_schema.parent (
  id INTEGER PRIMARY KEY
);

/* Create child table, this does *NOT* show in Beekeeper UI. */
CREATE TABLE my_schema.child (
  name VARCHAR(100)
) INHERITS (my_schema.parent);

/* This is not needed to show the bug, but perhaps makes it more clear...*/
INSERT INTO my_schema.child(id, name) VALUES (1, 'Alice');
```

Step 2: check the Beekeeper UI - the child does not show.

___

**Expected behavior**

At least by default, child tables should show up in the UI instead of being invisible. Preferrably they should also somehow indicate which table is their parent.

___

**Screenshots / Gifs**

**Image 1 below:** Screenshot after running the above example sql; the child table is not shown, while the parent is.

![image](https://user-images.githubusercontent.com/9801173/234236241-f2d509ff-7cd9-4e85-beeb-cec3d59067ae.png)

**Image 2 below:** The inserted element (Alice) correctly shows up for the parent, when clicked. However, the child table can't be selected in the menu to the left since it is not shown at all.

![image](https://user-images.githubusercontent.com/9801173/234237542-d58e2fc1-f72b-4bba-b7a3-0c1de1749acb.png)

___

**Version Information (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - App Version: Beekeeper 3.9.9
 - Database type and version: Postgres 15.2

**Comment by not-night-but** [comment]
@ekreutz Hmmm this was definitely caused by the implementation of #788. Do the children show up in the structure view? (right click on table, structure, partitions)

**Comment by ekreutz** [comment]
No, it's not visible in the structure view as far as I can tell. There is no "partitions" tab in there for me, but none of the 4 existing tabs show it either. It looks like this for the table "parent" (right click + structure). Perhaps the "Relations" tab is the closest, but that one is empty when I select it.

![image](https://user-images.githubusercontent.com/9801173/234631439-f88e8cbc-89ac-4800-adad-856e7d79054e.png)

**Comment by not-night-but** [comment]
Okay so beekeeper isn't seeing them as partitions, but is also not seeing them as regular tables. I will probably have to screw around with the table selection query a bit more. I'll keep you updated on this issue!

**Comment by not-night-but** [comment]
@ekreutz Fixed! :)

![image](https://user-images.githubusercontent.com/58712803/234693626-d5f8db00-5d2a-485c-9a9a-45e62f9097cd.png)
 
Gonna do a bit more testing just to make sure I haven't messed anything else up, and then we will push this out as soon as we can.

Thanks for reporting this issue!!
Day

**Comment by ekreutz** [comment]
Brilliant, looking forward to a release with the fix!
