### ISSUE TITLE
BUG: Invalid SQL for "Copy insert" action of dropdown in table for Postgres

### ISSUE THREAD

**Issue by svyatoslavratov** [beekeeper-studio/beekeeper-studio#1596]
**Describe the bug**
Invalid SQL for "Copy Insert" action of dropdown in table data with array column for Postgres.

**To Reproduce**
1. Create table with array column and insert row.
2. Open table.
3. Click RMB on table row then click "Copy Row (insert)"
4. Paste and run copied query.

**Expected behavior**
The insertion was successful.

**Version Information (please complete the following information):**
 - OS: macOS Ventura 13.3.1
 - App Version: 3.9.9
 - Database: Postgres 10.4

**Additional context**
Expected SQL, ex.:
```sql
insert into "public"."test" ("some_array") values ('{1,9,2,10,11}');
```
Actual SQL with error, ex.:
```sql
insert into "public"."test" ("some_array") values ('[1,9,2,10,11]');
```

**Comment by rathboma** [comment]
Thanks you! Sorry for this.
