### ISSUE TITLE
Refresh button

### ISSUE THREAD

**Issue by gnovaro** [beekeeper-studio/beekeeper-studio#160]
For example i create a new db. but if want to use this db y need to disconnect and connect again to see this new database in the select.

**Comment by rathboma** [comment]
Very true. You can refresh tables, but not databases. Should be easy to fix

**Comment by aligoren** [comment]
I added something like that. Can I open PR?

![image](https://user-images.githubusercontent.com/4205423/83349479-d3cd4880-a33d-11ea-8ce8-86c57007d442.png)

Thanks you <3
