### ISSUE TITLE
BUG: Pinned connections in teams do not show on first launch of the application

### ISSUE THREAD

**Issue by PHLAK** [beekeeper-studio/beekeeper-studio#1604]
**Describe the bug**

Pinned connections in teams do not show on first launch of the application. However, after connecting and disconnecting from a database the pinned connections show. See video posted below.

**To Reproduce**

1. Pin one ore more connections in a team workspace
2. Close Beekeeper Studio
3. Open Beekeeper Studio
4. Open the team workspace (no pinned connections)
5. Connect to a database
6. Disconnect from the database (shows pinned connections)

**Expected behavior**

My pinned connections should appear at the top of the list

**Screenshots / Gifs**

https://www.youtube.com/watch?v=1beBWtNloOo

**Version Information (please complete the following information):**
 - OS: Arch Linux
 - App Version: 3.9.10
 - Database type and version: All

**Comment by not-night-but** [comment]
Hello!

Thanks for reporting this. I suspect I probably just forgot to check for pinned connections when switching workspaces 🤦. I'll look into it in a bit.

Thanks,
Day

PS. I approve of your choice of OS (I use arch btw)

**Comment by not-night-but** [comment]
@PHLAK Hey! Just an update on this. I've filed a PR on the Ultimate Edition repo, should hopefully get merged soon. This issue will be auto closed when it is merged, so you'll at least get that status update.

This allowed me to find another bug with refreshing, so thanks again for reporting this!

Apologies for how long it took, I've had a crazy couple weeks.
