### ISSUE TITLE
BUG: Long Title is not properly  align 

### ISSUE THREAD

**Issue by zeelsheladiya** [beekeeper-studio/beekeeper-studio#1605]
**Describe the bug**
I have a long title and file path. when I open the studio the title is not properly aligned.

**Screenshots / Gifs**
<img width="357" alt="image" src="https://github.com/beekeeper-studio/beekeeper-studio/assets/46935793/b65e5929-510a-487d-bb05-375a530f2580">

**Version Information (please complete the following information):**
 - OS: Mac
 - App Version 3.9.14
 - Database type and version MYSQL

**Comment by rathboma** [comment]
Yuck, sorry.
