### ISSUE TITLE
BUG: “SQL: Create” no longer works on postgres 15

### ISSUE THREAD

**Issue by davidkaufman** [beekeeper-studio/beekeeper-studio#1612]
Ronnie Garcia reported (in the Beekeeper Studio Slack #help channel):

### I recently updated to [Beekeeper Studio] version 3.9.10 and the “SQL: Create” feature no longer works for me. Does it still work for everyone else?

**Version Information (please complete the following information):**
 - OS: Mac (running Apple Silicon)
 - App Version: 3.9.10
 - Database type and version: Posgresql 15
 

> @rathboma asked:
> > Oh, hmm. What database and version of the DB are you on?
> 
> Ronnie replied:
> > Postgres 15.3-1.pgdg110+1
> > 
> > It worked great before, but now when I click “SQL: Create”, nothing happens. No errors or anything, just a dead click.
> 
> @davidkaufman (gigawatt, on Slack) said
> > Hi Ronnie Garcia
> > I’m not able to recreate the problem in the latest Beekeeper Studio release 3.9.14 on postgres 13.9.  When this happens, do you see any error displayed in the DevTools panel (Help menu/ Show Developer Tools)?
> 
> Ronnie Garcia
> > When I click on SQL: Create nothing happens. I tried reinstalling the app too. I’m on Apple Silicon.
> 
> @rathboma asked:
> > Is this for a table? or view, or materialized view?
>  
> Ronnie Garcia
> > For a table.
> 
> @rathboma
> > @davidkaufman: try postgres 15?
> 
> @rathboma
> Ronnie Garcia, can you click help -> show developer tools and see if there are any errors in the console (they’d be red)
> 
> Ronnie Garcia
> > Ah, yup. Didn’t realize that was a thing…
> ![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/2336122/20cf0e32-73ba-4a1b-943a-9e5e4531bb19)
> 
> Ronnie Garcia
> > If I try another table with just an ID and JSONB column…

Excerpt of error:
~~~
vue.runtime.esm.js:3019 Error: Parse error: Unexpected "::characte" at line 6 column 57
    at e.value (TokenizerEngine.js:88:14)
    at e.value (TokenizerEngine.js:68:24)
    at e.value (Tokenizer.js:66:59)
    at e.tokenize (createParser.js:38:95)
    at e.value (LexerAdapter.js:38:26)
    at o.feed (nearley.js:281:15)
    at Object.parse (createParser.js:48:33)
    at n.value (Formatter.js:93:70)
    at n.value (Formatter.js:85:22)
    at F (sqlFormatter.js:127:36)
Hn @ vue.runtime.esm.js:3019
Fn @ vue.runtime.esm.js:3011
Bn @ vue.runtime.esm.js:2978
(anonymous) @ vue.runtime.esm.js:2989
processTicksAndRejections @ node:internal/process/task_queues:96
Promise.catch (async)
Un @ vue.runtime.esm.js:2989
Rr.e.$emit @ vue.runtime.esm.js:3685
handler @ TableListContextMenus.ts:82
optionClicked @ ContextMenu.vue?e1df:68
click @ ContextMenu.vue:1
Un @ vue.runtime.esm.js:2987
n @ vue.runtime.esm.js:1785
Ls.o._wrapper @ vue.runtime.esm.js:7428
vue.runtime.esm.js:3019 Error: Parse error at token: "ThrottleConfigs" at line 1 column 21
Unexpected STRING token: {"type":"STRING","raw":"\"ThrottleConfigs\"","text":"\"ThrottleConfigs\"","start":20}. Instead, I was expecting to see one of the following:

A LINE_COMMENT token [...]
A BLOCK_COMMENT token [...]
A ARRAY_IDENTIFIER token [...]
A ARRAY_KEYWORD token [...]
A ASTERISK token [...]
A IDENTIFIER token [...]
A QUOTED_IDENTIFIER token [...]
A VARIABLE token [...]
    at o.feed (nearley.js:343:27)
    at Object.parse (createParser.js:48:33)
    at n.value (Formatter.js:93:70)
    at n.value (Formatter.js:85:22)
    at F (sqlFormatter.js:127:36)
    at s.loadTableCreate (CoreTabs.vue?38ea:343:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
~~~
full log file: [`console_error.log`](https://github.com/beekeeper-studio/beekeeper-studio/files/11710550/console_error.log)

rathboma
> Thank you! This helps

**Comment by davidkaufman** [comment]
I'm working to try and reproduce this with postgres 15 (on my Intel-based Mac )

**Comment by not-night-but** [comment]
Related to #1609

I suspect this has nothing to do with postgres. We updated the SQL formatter library. Not sure why it seems like the errors are only happening on some machines. It could just be because SQL formatter doesn't support the syntax needed for those specific tables?

**Comment by davidkaufman** [comment]
Thanks @not-night-but

I'm able to recreate #1609 locally, can you post the commit or pr link here so i can test?

**Comment by not-night-but** [comment]
@davidkaufman #1599 is when the formatter was updated
