### ISSUE TITLE
FEAT: Paste TSV data into new row

### ISSUE THREAD

**Issue by mattgardner96** [beekeeper-studio/beekeeper-studio#1615]
**Description:**
When pasting data from Excel or Google Sheets to add to a PostgreSQL DB table view visually, data can only be pasted in one cell at a time; if I try to paste in multiple cells within a row, the data appears in a single cell with tabs separating the data that should be entered across multiple cells. Similarly, pasting data that should appear in multiple rows within one column all appears in a single cell.

**Alternatives:**
I haven't discovered any alternatives/workarounds for this issue.

**Additional context**
Add any other context or screenshots about the feature request here. (we love screenshots with red circles if the request is for something visual)
For example, copying the below data:
![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/39067505/6e94b23e-5a53-4596-8e72-c0b5fcd19d21)

Leads to the following entry on selecting paste (Ctrl+V):
![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/39067505/fcad082f-13a4-41d7-8fa5-115786b40750)

Instead of the expected behavior:
![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/39067505/87ca253f-203f-41f5-be8e-084f0bba75aa)

Not sure if this is database type specific or not. Thank you!

**Comment by not-night-but** [comment]
Yeah for sure! We have a lot of features planned for this component to make it more useable (see #1507).

**Comment by rathboma** [comment]
This is a really obvious and great idea!
