### ISSUE TITLE
cannot move the cursor

### ISSUE THREAD

**Issue by homerLL** [beekeeper-studio/beekeeper-studio#1620]
Version 3.9.17 cannot use the keyboard direction keys to move the cursor in the query edit box, but version 3.9.14 can move normally

**Comment by not-night-but** [comment]
@homerLL hey! This is a known issue that was fixed with #1619. There is a temporary fix detailed in #1618 , or you can install the git version. So sorry about that!

Thanks,
Day

**Comment by homerLL** [comment]
ok, i see.thanks for answer
