### ISSUE TITLE
Arrow, backspace, and delete keys no longer work properly

### ISSUE THREAD

**Issue by holyoaks** [beekeeper-studio/beekeeper-studio#1621]
**Describe the bug**
The arrow keys no longer move the cursor between lines or to the right nor left. Also, the backspace and delete keys no longer work if the adjacent character is a space or CR/LF character

**To Reproduce**
Write any query, such as `select now()`, then enter a carriage return. Try to use the arrow keys or delete/backspace keys to move the cursor. Then highlight any portion of the query and use the backspace key to delete the selected characters. I have verified it's not my keyboard just by typing out this bug report.

**Expected behavior**
Basic keyboard functionality should work

**Screenshots / Gifs**
https://github.com/beekeeper-studio/beekeeper-studio/assets/5797525/e3680a51-8a0a-42c1-8b76-b428d695f669

**Version Information (please complete the following information):**
 - OS: Mac 13.4
 - App Version 3.9.17
 - Database type and version Postgresql 13.3

**Comment by not-night-but** [comment]
@holyoaks this is a known issue that was fixed with #1619. You can find a temporary fix in #1618. Thanks for reporting this though!

**Comment by holyoaks** [comment]
Thanks @not-night-but

**Comment by andradei** [comment]
@holyoaks did you get it fixed with the workaround or something else?
I'm on the latest version and this bug is still there no matter what workaround I use.

**Comment by holyoaks** [comment]
I have it working with the workaround, though I have to apply it multiple times and change the text setting to Default. I don’t understand why this one is taking so long to resolve.

**Comment by andradei** [comment]
I think this should be re-opened and looked into, I'd like to be able to write queries again 😅

**Comment by not-night-but** [comment]
@andradei @holyoaks are either of you running off of the git version? The fix hasn't been pushed out in a release yet

**Comment by not-night-but** [comment]
@andradei you have to follow the steps in that workaround *exactly*, and then I'd avoid using the query dropdown (bottom left of status bar when you run multiple queries in one query editor at once), as that is what causes the bug

**Comment by not-night-but** [comment]
> @not-night-but The workaround didn't work on Windows 11, Beekeeper 3.9.17.
 
@andradei in that case, could you send me what is in your user setting table for the keymap setting? The whole row

**Comment by not-night-but** [comment]
> I have it working with the workaround, though I have to apply it multiple times and change the text setting to Default. I don’t understand why this one is taking so long to resolve. 

@holyoaks you having to do it multiple times is because of the query dropdown, not vim mode. You should be able to use vim after the workaround

**Comment by andradei** [comment]
@holyoaks @not-night-but I finally decided to delete the `app.db` sqlite file (where beekeeper keeps its settings), then I reinstalled beekeeper. Now it works every time.

**Comment by magesh-memorres** [comment]
This issue still persists in the latest release, I have to reinstall it now and then. the only workaround is https://github.com/beekeeper-studio/beekeeper-studio/issues/1621#issuecomment-1631439113

**Comment by not-night-but** [comment]
@magesh-memorres hi! The fix actually hasn't been pushed out in a release yet. It will definitely be in the next release, which should hopefully be our very soon

**Comment by magesh-memorres** [comment]
Thanks for the update. You people are doing great 😃👍

**Comment by not-night-but** [comment]
@andradei @holyoaks @magesh-memorres New release is out with this fix! Please let me know if you continue to have issues after updating
