### ISSUE TITLE
BUG: Flagged by anti virus and Virustotal

### ISSUE THREAD

**Issue by DaEpicR** [beekeeper-studio/beekeeper-studio#1625]
**Describe the maybe a bug**
After downloading the stable version for windows the security flagged the app as a virus (trojan)
**To Reproduce**
1. Go to the exe
2. Click on it
3. boom flagged

virus total also get 3/63 
https://www.virustotal.com/gui/file-analysis/NWJhNDdkNDc1ZjliYzdmN2JhYTIxYjJmNTNjNjcyNGU6MTY4ODIyOTQ3MA==

is it a false detection by both virustotal and windows security ?

**Comment by DaEpicR** [comment]
im an asshole its the wrong issue page for the wring app sorry

**Comment by not-night-but** [comment]
@DaEpicR lol no worries!
