### ISSUE TITLE
BUG: Unsaved socket connections show up wrong in recents

### ISSUE THREAD

**Issue by not-night-but** [beekeeper-studio/beekeeper-studio#1627]
**Describe the bug**
When you connect to a database through a unix socket without first saving the connection, the information is then not shown correctly in the recent connections list: 

**To Reproduce**
1. New connection
2. enter socket details
3. connect
4. disconnect
5. the new recent connection will show a host and port configuration.

**Expected behavior**
The new recent connection should be the configured socket connection.

**Screenshots / Gifs**
![socketConnectionBug](https://github.com/beekeeper-studio/beekeeper-studio/assets/58712803/8513d358-cd71-4dc3-9625-89f6baa62f6e)

**Version Information (please complete the following information):**
 - OS: Linux (Arch btw)
 - App Version: 3.9.17

**Comment by tkudlicka** [comment]
Hey @not-night-but,

It looks like you discovered the bug where connecting via a Unix socket doesn't get stored in recent connections, leading to default connection details being displayed. Do you think we should explore automatically storing these connections to ensure accuracy?

Tomas

**Comment by not-night-but** [comment]
@tkudlicka hey! I think we should definitely ensure the recent connection is accurate and you can connect to it again. Haven't looked at how we store the recent connections in a while, so I'm not sure if this would require schema changes. I think this issue just leads to confusion with the user, ie "I don't remember connecting to this?" Or "Where'd my connection go?"
