### ISSUE TITLE
unable to save a favorite query without providing a database name

### ISSUE THREAD

**Issue by jo-wu** [beekeeper-studio/beekeeper-studio#163]
OS: Linux Mint 18.3 (Ubuntu 16.04)
installed by snap

**Comment by rathboma** [comment]
I'll take a look, any error message or anything like that?

**Comment by rathboma** [comment]
@jo-wu please try running like this:

```bash
DEBUG=beekeeper:* beekeeper-studio
```

and let me know what errors you see.

**Comment by jo-wu** [comment]
thx..below is the log:

QueryFailedError: SQLITE_CONSTRAINT: NOT NULL constraint failed: favorite_query.database
    at new QueryFailedError (/snap/beekeeper-studio/22/resources/app.asar/node_modules/typeorm/error/QueryFailedError.js:11:28)
    at Statement.handler (/snap/beekeeper-studio/22/resources/app.asar/node_modules/typeorm/driver/sqlite/SqliteQueryRunner.js:48:38)
at @ vue.runtime.esm.js:1888
ot @ vue.runtime.esm.js:1879
rt @ vue.runtime.esm.js:1839
(anonymous) @ vue.runtime.esm.js:1856
Promise.catch (async)
it @ vue.runtime.esm.js:1856
n @ vue.runtime.esm.js:2179
o._wrapper @ vue.runtime.esm.js:6917

**Comment by rathboma** [comment]
Yep, looks like you're not specifying a `defaultDatabase` for the connection, and that is required by my schema.

**Comment by rathboma** [comment]
not sure what type of db you're connecting to, but try specifying the field name

**Comment by jo-wu** [comment]
...right, after I set the connection name and the select a database, it works right. thx

**Comment by rathboma** [comment]
This is fixed in master.
