### ISSUE TITLE
BUG: Vim and Default settings are unusable (can't move cursor reliably)

### ISSUE THREAD

**Issue by andradei** [beekeeper-studio/beekeeper-studio#1634]
**Describe the bug**
When writing/editing a query
- Can't use arrow keys to move cursor
  - Can't move cursor in Default or Vim modes with those
- Vim mode doesn't work at all
- Sometimes I can move the cursor but the UI doesn't update the cursor position (it shows at the end of the line)

I tried the workaround [suggested here](https://github.com/beekeeper-studio/beekeeper-studio/issues/1618#issuecomment-1598096829)

And also read #1621

Beekeeper Studio `3.9.17`

**To Reproduce**

### In Default mode
1. Open any query or create a new one
2. Type a line
3. Type another line
4. Backspace to erase the bottom line and keep doing it to do the previous line (won't go)
5. Type the arrow keys to move the cursor (won't work)

### In Vim mode
1. You can type and create a new line

**Expected behavior**
- Arrow keys would move cursor
- Backspace on an empty line would delete it and move to the line above

**Screenshots / Gifs**
![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/2653546/5b283d98-1357-4a08-803a-e176d4d2941e)
---
![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/2653546/34271a3e-703a-4747-b9ce-8cdc1781ae69)

**Version Information (please complete the following information):**
 - OS: Windows 11 fully updated
 - App Version: 3.9.17
 - Database type and version: (remote DB) mariadb  Ver 15.1 Distrib 10.5.19-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper

**Comment by andradei** [comment]
@not-night-but I decided to create new issue top add all the details I can.
This is the keymap row on from `user_setting` table:

```json
{"id":"9","section":null,"key":"keymap","userValue":"vim","defaultValue":"","linuxDefault":null,"macDefault":null,"windowsDefault":null,"valueType":"5","createdAt":"2023-07-10 19:17:50.358","updatedAt":"2023-07-11 19:08:04","version":"12"}
```

**Comment by andradei** [comment]
Thanks to all who work on this, btw.

For full transparency:
- I discovered there were 2 versions installed: 3.9.14 via `winget` and 3.9.17 via `scoop`
- Deleted the `winget` version
- Reinstalled the `scoop` one

Problem persists.

**Comment by not-night-but** [comment]
> ```json
> {"id":"9","section":null,"key":"keymap","userValue":"vim","defaultValue":"","linuxDefault":null,"macDefault":null,"windowsDefault":null,"valueType":"5","createdAt":"2023-07-10 19:17:50.358","updatedAt":"2023-07-11 19:08:04","version":"12"}
> ```

okay so the `valueType: 5 ` is the issue here. That is what the workaround is attempting to fix by forcibly setting it to 0, and then immediately exiting the application, as if the setting is not updated in the app it will be overwritten by the next setting save.

**Comment by andradei** [comment]
Deleting the `app.db` sqlite file and reinstalling Beekeeper fixed the issue.

**Comment by not-night-but** [comment]
@andradei alrighty. Just hold tight, we're trying to get the release out as soon as we can. Just note that again, this issue will come back if you use the query dropdown before the next release. Ominous I know, but unfortunately that's the only way to ensure this doesn't happen again :joy:
