### ISSUE TITLE
BUG: SQL editor won't let me move the cursor with arrow keys + delete not deleting letters.

### ISSUE THREAD

**Issue by SuzukiRyuichiro** [beekeeper-studio/beekeeper-studio#1636]
**Describe the bug**
In the SQL editor, arrow keys stopped working. Also, I cannot delete new lines and spaces anymore.

**To Reproduce**
1. Opne a database (postgreslq)
2. Cmd + T to create a new SQL query
3. Type some SQL.
4. Click on left or right arrow. Cursor won't move
5. Try deleting a few letters. When it's at the end of a word, it won't delete

**Expected behavior**
It should act as a normal text editor where arrow keys move cursors and delete should delete a letter

**Screenshots / Gifs**
![output](https://github.com/beekeeper-studio/beekeeper-studio/assets/46629248/ce47af9b-e2d1-4060-835c-a34443a7109d)

**Version Information (please complete the following information):**
 - OS: M1 Macbook Air  MacOS 13.4 (22F66)
 - App Version: Version 3.9.17 (3.9.17)
 - Database type and version: postgres (PostgreSQL) 14.8 (Homebrew)

**Comment by riyadparvez** [comment]
Same issue on the MacOS. Beekeeper has become unusable for me.

**Comment by not-night-but** [comment]
@SuzukiRyuichiro @riyadparvez @danieljaguiar Hi!! This is a known issue that was fixed with #1619. You can find a temporary fix in #1618. 

Here's the workaround: https://github.com/beekeeper-studio/beekeeper-studio/issues/1618#issuecomment-1598096829

**Comment by SuzukiRyuichiro** [comment]
Thanks for letting us know 🙂 I love the app so glad it's fixed 🙂

**Comment by not-night-but** [comment]
@SuzukiRyuichiro no problem! Glad you like the app 😃

**Comment by riyadparvez** [comment]
@not-night-but I have tried your workaround. Now the whole editor has disappeared for me. It's just black area

**Comment by not-night-but** [comment]
@SuzukiRyuichiro any errors in the console?

**Comment by not-night-but** [comment]
@SuzukiRyuichiro @riyadparvez @danieljaguiar I'm pushing out a release right now that should hopefully fix this error for good. So sorry for any inconvenience or frustration this probably caused.

**Comment by not-night-but** [comment]
@SuzukiRyuichiro @riyadparvez @danieljaguiar new release is out, please let me know if you still have issues after updating.

**Comment by SuzukiRyuichiro** [comment]
@not-night-but Yeah, can confirm it's working as intended. thanks for the fix ❤️

**Comment by riyadparvez** [comment]
Arrow keys still don't work for me

**Comment by not-night-but** [comment]
> Arrow keys still don't work for me

Someone else said that they were able to fix it by selecting either vim or default mode and then restarting the app, maybe try that?
