### ISSUE TITLE
BUG: Say something here

### ISSUE THREAD

**Issue by Sangoku** [beekeeper-studio/beekeeper-studio#1638]
**Describe the bug**
Arrow keys are again broken. This time diferent error message: 

**To Reproduce**
 Tried this fix: https://github.com/beekeeper-studio/beekeeper-studio/issues/1618 but does not work i get a diferent error message.

**Expected behavior**
To move the cursor with arrow keys. 

**Screenshots / Gifs**  
![Screenshot 2023-07-14 at 07 40 51](https://github.com/beekeeper-studio/beekeeper-studio/assets/64758/cc278efe-7550-4fa3-aa5a-b7707324a652)

**Version Information (please complete the following information):**
 - OS: Mack Apple M2 Max 13.4.1
 - App Version  3.9.17
 - Database type and version,  internal or any other

**Additional context** 
Nothing helps.. every keypress just makes the last error again.

**Comment by not-night-but** [comment]
@Sangoku Hey! I'm actually in the middle of pushing out a release, which should hopefully fix this issue for good. So sorry for the inconvenience and frustration I'm sure this caused.

**Comment by not-night-but** [comment]
@Sangoku The release is out. Please let me know if you still have issues after updating
