### ISSUE TITLE
BUG: Query tabs text turned invisible.

### ISSUE THREAD

**Issue by virtuallyunknown** [beekeeper-studio/beekeeper-studio#1640]
**Describe the bug**

**To Reproduce**
1. Go to a new query tab (or any open query tab for any connection)
2. The part where you write your query (not the results section) is blank (invisible).

You can actually write text and run the query, but you can't see what you're writing.

**Screenshots / Gifs**
If applicable, add screenshots or GIFS to help explain your problem.

https://github.com/beekeeper-studio/beekeeper-studio/assets/24871108/dc915d28-ac7f-4b72-afde-00ab4b350d9b

**Version Information (please complete the following information):**
 - OS: Linux Mint 21.1 Cinnamon 5.6.8
 - App Version 3.9.18
 - Database type and version: Postgresql 15.3

**Additional context**
Pretty sure I update Beekeeper studio earlier today and this is when the problem started occurring. Although I am not sure if I have restarted the application since updating.

As I was recording the video to attach to this issue, I restarted the application several times and now it appears the problem has gone away, nevertheless it's probably something worth looking into. I have no idea what I've done to fix it.

**Comment by not-night-but** [comment]
I suspect this is an issue with the query editor fix. There's a migration that should have run while updating the application that changed the type of the keymap user setting, but it may have still been in memory as the wrong type, so restarting the app reloaded it and now you're good. At least I hope that's the case lol. If you see this issue again after it's fixed itself, please ping me.

**Comment by virtuallyunknown** [comment]
> I suspect this is an issue with the query editor fix. There's a migration that should have run while updating the application that changed the type of the keymap user setting, but it may have still been in memory as the wrong type, so restarting the app reloaded it and now you're good. At least I hope that's the case lol. If you see this issue again after it's fixed itself, please ping me.

I wouldn't be making an issue about it if it was fixable with just a simple app restart. When I updated the app and it got stuck in this state, I tried restarting it several times, then somewhere in between this process `/opt/Beekeeper Studio/beekeeper-studio-bin` got in some unkillable (zombie) state so I couldn't even `sudo kill` it. Then I rebooted my entire system just to make sure, but that was to no avail either, just then I decided to open an issue (on github).



But yep, no worries if it happens again I will make sure to ping you. Thanks.

**Comment by not-night-but** [comment]
Oh sorry I totally misunderstood what you meant. I'll download the last update and see if I can reproduce this

**Comment by AndyBarker-egs** [comment]
I'm had the same problem.  I just upgraded from the previous version due to the editor cursor issue and now I can't view, edit, or create any queries.
"Viewing data" for a table works, but creating new tabs, etc or looking at previous tabs there was no ability to type anything. The mouse cursor was the normal arrow suggesting that it doesn't have a text box underneath it.

I found a solution though:

I found that selecting the Editor type by clicking the Cog and selecting Default then restarting the app made it work.  When I first selected the Cog, neither option was selected.  I am guessing that the editor failed as it didn't know which editor to use!

![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/73164417/4062e3d6-1b9d-4fa2-b10c-19d2ed874a79)

**Comment by bzenker-amplify** [comment]
Yea, this happened to me when I was previously trying to edit the Beekeeper settings to fix the cursor issue from one of the previous versions. Everything went invisible so I panicked and reset the value to "5" (re-removing cursor movement). Thank you for the workaround AndyBarker
