### ISSUE TITLE
Android app

### ISSUE THREAD

**Issue by mcanepa** [beekeeper-studio/beekeeper-studio#1643]
Can this excellent tool be ported to android?

**Comment by mcanepa** [comment]
Sometimes I'm on the road with nothing but a tablet. I don't see any decent app for database management and I would love to use this tool

**Comment by JarKanni** [comment]
I'd love to see an Android app, too!  There are plenty of times I'm away from the computer and want to check a query quick, yet haven't found any DBM apps worthwhile.

**Comment by rathboma** [comment]
Hi all!

I'd love to do that eventually :-). Right now we're pretty rightly bound to electron and the desktop app ecosystem.

I'm going to close this issue, not because I don't care, but because I can't really do it, lol.

**Comment by JarKanni** [comment]
Makes sense, thanks for the reply. Will keep enjoying it on desktop!

**Comment by mcanepa** [comment]
@rathboma Thanks for your answer! But do you think it can be done? Does the code allow it? May be someone could do it in the future...
