### ISSUE TITLE
BUG: Can't see comment column when modifying a table

### ISSUE THREAD

**Issue by zhaolingzhi** [beekeeper-studio/beekeeper-studio#1644]
**Details:**
How to show comment colume

if i dont use auto_increment, here will show comment colume.
but if i use it, the comment colume will disappear

**Version Information [might be relevant to your issue]**
ver 3.9.17

**Screenshot / GIF [if appropriate]**:
![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/26158797/0e34f62d-5339-4a18-be06-0aa328d2dc22)

**Comment by rathboma** [comment]
Let me take a look, probably I need to add some scrolling to the table

**Comment by xuanyanwow** [comment]
Hi,Is there any new progress?

**Comment by azmy60** [comment]
Hi @xuanyanwow :) , I have some works to be done today so I'm planning to take a look at this probably tomorrow.
