### ISSUE TITLE
FEAT: export and import connections

### ISSUE THREAD

**Issue by mcanepa** [beekeeper-studio/beekeeper-studio#1645]
When I open beekeeper, where the connections are listed, I would expect a button to export all saved connections to a file (preferably a in json format) So I can have a backup if I format my PC o want to port them to another machine.

I would also expect an import button that reads that file and rebuilds the connections.

Somehow beekeeper stores this data, so I believe it would be just a matter to make it available for user export.

**Comment by davidkaufman** [comment]
Hi @mcanepa 

While Beekeeper Studio does not have a JSON export feature for saved connections, all of the application's state, including saved connection information, is stored in the `app.db` file which is a standard SQLite database, which you can copy, backup and use to import all of your saved settings to a new Beekeeper Studio installation.

See the [Data Storage Location](https://docs.beekeeperstudio.io/docs/deep-dive-overview#database-location) page in the Advanced section of the docs to find the location of this file, depending on your OS

- ADVANCED / Data Storage Location
  <https://docs.beekeeperstudio.io/docs/deep-dive-overview#database-location>

**Comment by austinwilcox** [comment]
@mcanepa the app.db might be a good file to toss into a private repo and then symlink it into your .config/beekeeper-studio folder? That is if you are on Linux or Mac.

**Comment by mcanepa** [comment]
Didn't know about that file...that's good to know! thanks

1) How are password stored?

2) Even though such file exists. I still believe in the export/import ux (with passwords in plain text)

**Comment by rathboma** [comment]
Hey! There's a keyfile and an app.db, back both up and you're golden.

You can also export to CSV. Click `help -> add beekeeper's database`, then you can query the beekeeper database, and export the results to CSV whenever you like.

So you can backup Beekeeper....using Beekeeper

Hope that helps :-).

Going to close this as more of a question. You can also use the commercial version which has cloud storage for connections.

**Comment by alan345** [comment]
FYI, there is a typo in the documentation for MacOS: https://docs.beekeeperstudio.io/support/data-location/
The directory is 
`~/Library/Application Support/beekeeper-studio`
not
`~/Library/Application Support/Beekeeper Studio`

**Comment by alan345** [comment]
The feature `help -> add beekeeper's database` is not working (`Version 5.1.5`)

![Image](https://github.com/user-attachments/assets/e4317fe2-381f-486a-844c-a5d0518c54d0)
