### ISSUE TITLE
BUG: Format Query

### ISSUE THREAD

**Issue by jtnguyen2020** [beekeeper-studio/beekeeper-studio#1646]
Format query is no longer working for version 3.9.18

**Comment by rathboma** [comment]
What database type are you using?

**Comment by jtnguyen2020** [comment]
It was redshift but the latest update resolved the issue.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by wmontgomery** [comment]
Going to close this as it sounds like the new update fixed the problem. If the issue pops up again, please reopen.
