### ISSUE TITLE
QUESTION: Can I connect beekeper studio to my planet scale? How do I do it?

### ISSUE THREAD

**Issue by crision-olt** [beekeeper-studio/beekeeper-studio#1652]
I tried to connect to the tool to my planetscale database. As I know that is postgresql I thought i can connect.

In the configuration i dont know what port to use but itried with 3306 and gives me ECONNRESET

![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/96696392/523f5aa6-1205-4ade-a444-cb6f746b2376)

**Comment by arryhere** [comment]
Shouldn't the connection type be MySQL ?

**Comment by davidkaufman** [comment]
Yeah, I'm not familiar with Planet Scale, but if it's postgresql as @crision-olt mentioned, then the port should be 5432 not 3306 (which is the port for MySQL).  If it's MySQL, then the "Connection Type" dropdown should be changed to MySQL or MariaDB (either should work the same).

`ECONNRESET` means the server disconnected you, which it would do if you tried to talk to a mysql db using the postgresql driver...
