### ISSUE TITLE
BUG: System theme won't sync when app is running.

### ISSUE THREAD

**Issue by Ashvith10** [beekeeper-studio/beekeeper-studio#1656]
**Describe the bug**
Theme won't toggle to light and dark mode in real time. Switch takes place after restarting the app.

**To Reproduce**
1. Launch Beekeeper Studio
2. Toggle system theme
3. Theme won't switch

**Expected behavior**
System theme should update in real time, not when app is open on next instance.

**Screenshots / Gifs**
![Screencast from 2023-08-02 17-35-56.webm](https://github.com/beekeeper-studio/beekeeper-studio/assets/113123021/0f1149ee-8e3b-448c-b9c0-53af712e0228)

**Version Information (please complete the following information):**
 - OS: NixOS Stoat 23.05
 - App Version: 3.6.2
 - Database type and version: -

**Additional context**
Using GNOME Shell's system theme toggle isn't working on Beekeeper Studio. Not sure if this behavior exists in other Linux desktop manager.

Interestingly, the **About** section toggles with the system theme:
![Screencast from 2023-08-02 17-44-49.webm](https://github.com/beekeeper-studio/beekeeper-studio/assets/113123021/f922976e-02f0-4399-a494-418df5c0941c)

**Comment by rathboma** [comment]
Oh yeah. Changing between system and client requires a restart. Isn’t there a notification saying that?

**Comment by Ashvith10** [comment]
@rathboma there isn't any notification. But I was wondering - since this uses something that is Electron (or similar), wouldn't it be easy to do what VSCode does when system themes are changed?
