### ISSUE TITLE
BUG: Wrong table name on "Copy Row (Insert)"

### ISSUE THREAD

**Issue by lucafornerone** [beekeeper-studio/beekeeper-studio#1658]
The copied text on "Copy Row (Insert)" after a query result is wrong. Insted of the table name the script begin with `insert into mytable`.

1. Write a select query without join
2. Right click on a row
3. Select "Copy Row (Insert)"
4. Paste the result

**Expected behavior**
The script begin with `insert into <query-table-name>` instead of `insert into mytable`

**Version Information:**
 - OS: Windows 10
 - App Version: 3.9.18
 - Database type and version: mySQL 5.7.18

**Comment by rathboma** [comment]
Yuck, thanks

**Comment by azmy60** [comment]
@rathboma I think this is a perfect use case for your [proposed](https://github.com/coresql/sql-query-identifier/pull/69) PR in sql-query-identifier. And `mytable` is a hardcode so it happens in all database types, not only mysql.
