### ISSUE TITLE
BUG: No autocomplete for field now?

### ISSUE THREAD

**Issue by andreas-ajaib** [beekeeper-studio/beekeeper-studio#1659]
**Describe the bug**

After new update, I am unable autocomplete field name.

**To Reproduce**

**Expected behavior**

**Screenshots / Gifs**
If applicable, add screenshots or GIFS to help explain your problem.

**Version Information (please complete the following information):**
 - OS: [e.g. Windows/Mac/Ubuntu]
 - App Version [e.g. help -> About Beekeeper Studio]
 - Database type and version [eg Posgresql 9.3]

**Additional context**
Anything else you think might be helpful

**Comment by EliezerMafra** [comment]
Same problem in here

**Comment by azmy60** [comment]
Could you provide more details? I'm using mysql and postgres with this syntax. It triggers the autocomplete for columns as soon as I type `.`.

![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/38707148/5c7211b3-eba9-45bf-ba01-c52d5170864a)

**Comment by EliezerMafra** [comment]
My problem is with the names of the tables.
When I typed just the beginning of the table name and pressed `Ctrl`+`Space` it would give me the possible names or just complete it if it was only one

**Comment by mojtabakaviani** [comment]
PostgreSQL columns autocomplete and intellisense just work with table alias.

**Comment by azmy60** [comment]
So I just found a small change of behavior when using the autocomplete.

![in newer version, the table uses quotes](https://github.com/beekeeper-studio/beekeeper-studio/assets/38707148/e3c38417-6c36-43dd-8b33-72b09bff783f)

![in older version, the table does not use quotes](https://github.com/beekeeper-studio/beekeeper-studio/assets/38707148/5f16e483-72da-4250-b06f-8c0db3cf0e6b)

If you look closely in the newer version, the table that uses uppercased letters, `TestTable`, is provided by the autocompletion with quotes, which makes the typing slower, but still can autocomplete the columns.

Quotes are only needed when there are special characters like `!@#$%^*()` and quotes itself.

I'll make a patch for this, though it's probably not exactly the issue that you might experience. It would be great if you can attach a video / gif as it makes the debugging process much easier. Thanks!

**Comment by azmy60** [comment]
@andreas-ajaib @EliezerMafra @mojtabakaviani Would you be able to give me some SQL to create the table/schema so I can demo it? What database type do you use (mysql/postgres)?

**Comment by rathboma** [comment]
Yeah I see the same thing. It’s after adding support for schema autocomplete.

**Comment by EmanNo1** [comment]
I have a similar issue. All the tables are now quoted in the pull down/suggestion. I am not able to filter the list unless I type a " in the SQL.

Version 3.9.20 on Ubuntu via Snap
MS SQL database

![Selection_005](https://github.com/beekeeper-studio/beekeeper-studio/assets/2874846/aa4bf478-f441-4753-80b4-09e00159cba0)
