### ISSUE TITLE
FEAT: unsigned column

### ISSUE THREAD

**Issue by mcanepa** [beekeeper-studio/beekeeper-studio#1660]
While creating/altering a table, I need to specify if the data will be signed or unsigned. I should be able to set that property visually.

![Captura de pantalla de 2023-08-08 14-49-47](https://github.com/beekeeper-studio/beekeeper-studio/assets/25961439/64dc086f-000f-43fe-96fc-6dcc22b0d7a8)

**Comment by rathboma** [comment]
Agreed.
