### ISSUE TITLE
FEAT:  Add support for simple .vimrc file

### ISSUE THREAD

**Issue by austinwilcox** [beekeeper-studio/beekeeper-studio#1663]
This is a feature that would be nice to have for vim users of Beekeeper Studio. 

The idea would be that the user can place a .vimrc in the default config path, we could name it something like .beekeeper.vimrc, similar to the [obsidian plugin for vimrc support](https://github.com/esm7/obsidian-vimrc-support). In an initial version we can support imap, nmap, and vmap rebindings. 

For example, I use a couple helix keybindings in my vim config, I map gl to $ and gh to ^. These command will take you to start of the line, and the end of the line. Currently you can do that in the editor each time you load it up by entering cmd mode and typing: nmap gl $, and nmap gh ^. 

I have a simple parser already written in typescript that could grab the mappings out of a vimrc, and I have the code to set those bindings in CodeMirror. If this sounds like a good enough idea I can create the PR and get the process started for adding this into the editor.

edit: Grammatical error

**Comment by not-night-but** [comment]
@austinwilcox I think this is a great idea! I personally use helix so this would be a great interim solution for me until I can get the time to create a helix mapping for codemirror. But beyond that I think it'd be a great QoL feature!

**Comment by austinwilcox** [comment]
@not-night-but If you're using helix, I wonder if with this PR I add the unbind option as well to parse from the config file, that way you could get even closer to helix bindings. Thoughts? I can try and get an initial PR up here in the next week or so. I have most of the code already written in a separate node project, I just need to move it into the codebase and test a couple of things.

**Comment by not-night-but** [comment]
@austinwilcox I mean if it's easy to implement I say go wild! Get an initial PR up and then we can discuss more of the nitty gritty. Thanks so much!

**Comment by austinwilcox** [comment]
@not-night-but [PR 1670](https://github.com/beekeeper-studio/beekeeper-studio/pull/1670) has the start of my code for this. There are a couple of things still needed in the code, main one being reading in the vimrc and passing it down with the ipcrenderer. I have not gotten to setting the unbind keybindings yet in there, but I figure that's something that can be discussed in the actual PR.
