### ISSUE TITLE
BUG: Connection error "no pg_hba.conf entry for..."

### ISSUE THREAD

**Issue by lqmanh** [beekeeper-studio/beekeeper-studio#1680]
**Describe the bug**
I have a PostgreSQL instance deployed on Amazon RDS. When I try to connect to it, this error message is popped up:

```
no pg_hba.conf entry for host "10.0.10.**", user "pick**", database "ingest**", no encryption
```

I'm not sure if it's because of the server, as I can still connect to it via command-line with `psql`, or some other apps like DBeaver and pgAdmin 4.

**Expected behavior**
The app should connect to the DB server normally.

**Version Information (please complete the following information):**
 - OS: MacOS 13.5.1
 - App Version: 3.9.20
 - Database type and version: PosgreSQL 15

**Comment by dapmel** [comment]
Try enabling the SSL connection if you haven't already.

https://github.com/beekeeper-studio/beekeeper-studio/issues/1451

**Comment by lqmanh** [comment]
It works, thanks
