### ISSUE TITLE
BUG: "View record in [table]" buttons are unresponsive

### ISSUE THREAD

**Issue by jeremynevans** [beekeeper-studio/beekeeper-studio#1682]
**Describe the bug**
Whenever I click on "View record in [table]" buttons inside a cell that's linked to a foreign table, nothing happens.

**To Reproduce**
1. Go to a table with a column linked to a foreign table.
2. Click on "View record in [table]"
3. See that nothing happens

**Expected behavior**
I expect to be shown the corresponding record in the other table.

**Screenshots / Gifs**
![2023-08-26 15 20 46](https://github.com/beekeeper-studio/beekeeper-studio/assets/10399785/15ec92fb-2764-41bf-a843-745d47e8b796)

**Version Information (please complete the following information):**
 - OS: Mac
 - App Version 3.9.20
 - Database type and version: Postgres: 15.1.0.112 (Supabase)

**Comment by rathboma** [comment]
Oh, that's not good. We'll look into it.

**Comment by azmy60** [comment]
Hi @jeremynevans ! Would you mind to share a little sample for the tables? any errors in the devtools? (You can open the devtools by clicking `Help > Show Developer Tools > Console`)

**Comment by jeremynevans** [comment]
Yep same error for me!
<img width="560" alt="image" src="https://github.com/beekeeper-studio/beekeeper-studio/assets/10399785/67ad4357-4441-4c64-b04b-68e61557c9ab">

**Comment by rathboma** [comment]
Fix coming this week!

**Comment by azmy60** [comment]
Oh I just realized this is an issue with the ultimate build. @rathboma Was it fixed by your recent [commit](https://github.com/beekeeper-studio/beekeeper-studio/commit/105413a968a7607b364d1bcbaa6b4b39e638b6f8)?

**Comment by rathboma** [comment]
Yep, fixed it :-)
