### ISSUE TITLE
FEAT: When in Vim Mode, :w should save the file

### ISSUE THREAD

**Issue by austinwilcox** [beekeeper-studio/beekeeper-studio#1685]
To save a file in vim, while in normal mode you would type :w to write the file. I want to set this up so that we can save files with :w, currently code mirror does nothing with this command, but I know that you can tap into this and have an actual action tied to the command. Even if worst case scenario I think I could bind this to hit ctrl+s to save the file.

**Comment by not-night-but** [comment]
Good idea!!! I know you can listen for when a vim command is executed and then check the keys that were pressed, so I think this should be pretty easy to implement!

**Comment by austinwilcox** [comment]
That's what I was thinking. Expect a PR to come up here in the next couple of weeks to implement this.

**Comment by not-night-but** [comment]
Thinking about this a bit more, we could also add support for `:q` and `:q!` for closing tabs?

**Comment by austinwilcox** [comment]
Hmm I like that idea! I'll add that in with the PR.

**Comment by austinwilcox** [comment]
@mohamedelhefni @not-night-but this is complete and has been merged into master correct? If so I can close out this issue.
