### ISSUE TITLE
FEAT: Rich-editing of large data in a modal

### ISSUE THREAD

**Issue by rathboma** [beekeeper-studio/beekeeper-studio#1698]
Problem:
It is common for a database table to contain fields of large values, for example the content of a blog post, a large json document, xml document, html page, css rules, etc, etc.

Editing these in Beekeeper Studio is terrible, because we only support in-line editing.

Solution:
We need a way to 'pop out' the editor for complex data in some way.
We've previously discussed a right-side sidebar, but this could also be a modal, or maybe even something like the gmail bottom-right pop up email composer window. We'd need to experiment with what feels natural.

Solutions we've spitballed in the past:
We've discussed having a right-side sidebar that displays the entire highlighted record for editing. This could be nice for other use cases, but doesn't intrinsically solve this use case, which is editing a single large value, in fact it could have many of the same problems.

Implementation notes:
- Beekeeper should try to auto-detect the type of content being edited, maybe using https://github.com/microsoft/vscode-languagedetection

**Comment by not-night-but** [comment]
I think the Gmail composer is a good solution for this (we all know I despise modals for anything beyond a confirmation of action). In this case I think the modal could be frustrating, particularly if you're using other data in the app to edit the field. 

Another thing to consider with that is whether it's a popout that's local to the tab and will only show when that tab is active, or if it's global (and then can be minimised/expanded like how Gmail handles it)

**Comment by rathboma** [comment]
Yeah I'm not sure honestly. I'll have to play with the different options.

**Comment by RonnieSan** [comment]
PGAdmin does something similar. I would suggest something not unlike the [primevue overlay panel](https://primevue.org/overlaypanel/) which is basically an attached modal so it has a clear association with the exact field you are editing.

**Comment by rathboma** [comment]
Something like that could work, but might still not be big enough.

What about a right sidebar?

This won't be in 4.0, but want to include it for 4.1

**Comment by rathboma** [comment]
Maybe an overlay with an expand button that makes it a large modal? Still not sure. Probably need to try a few

**Comment by RonnieSan** [comment]
> Maybe an overlay with an expand button that makes it a large modal? Still not sure. Probably need to try a few

Yeah, I think some kind of expand button would work great for larger objects. I think my main ask for this would be a keyboard shortcut for submitting whatever data is changed in the field (something like ctrl+enter). It's really time-consuming when you have to click a button if you have to update multiple fields.

**Comment by rathboma** [comment]
Ok, I think for v1 of this:

When editing a cell that is long (the formatter has needed to truncate it), include a 'edit in modal' button in the editor.

When you click this button it opens a large modal with auto-detected syntax highlighting.

Formats to autodetect:
- JSON - from json/jsonb columns and from TEXT columns that are obviously JSON
- ARRAY - just treat them as JSON arrays
- TEXT - everything else ends up as text
- Include a dropdown for selecting syntax (in case we get it wrong)
- This should use codemirror
- It should include find/replace functionality, and VIM mode (synced with the query editor's VIM mode selection)

For all json/array detected data - show it as nicely formatted, include a checkbox for 'save compacted', which removes all the formatting.

When clicking 'done' on the modal, the data is written to the UI as a staged change ready for 'apply'

**Comment by rathboma** [comment]
The first version of this is DONE and will be in the next release
