### ISSUE TITLE
Postgress SSL connection

### ISSUE THREAD

**Issue by PaulusTM** [beekeeper-studio/beekeeper-studio#17]
To use Azure Postgres service we need to option to enable TLS in the connection.
In the connection string this is set by `Ssl Mode=Require;`

Am I missing a setting somewhere or is this not possible yet?

**Comment by rathboma** [comment]
Hey!

I have this built into the app but is not tested yet. I'll bump it up on my priority list.

**Comment by PaulusTM** [comment]
Hi @rathboma!

Is there any branch or build I can have a look at and help with testing?

**Comment by rathboma** [comment]
What platform are you running on? (mac windows linux)?

**Comment by PaulusTM** [comment]
Mac is my main, but I'm able to test any platform.

**Comment by rathboma** [comment]
I've created an AppImage linux image build with the fix, can you check to see if it works?

https://github.com/beekeeper-studio/beekeeper-studio/releases/download/v1.1.1/Beekeeper.Studio-ssl-test.AppImage

**Comment by PaulusTM** [comment]
Tested with Ubuntu 18.04 TLS and works like a charm.
<img width="796" alt="Screenshot 2020-04-23 at 11 03 54" src="https://user-images.githubusercontent.com/85584/80080671-3cacee00-8552-11ea-89fa-40f3e9816e3e.png">

**Comment by rathboma** [comment]
Hooray! Thanks for helping! I'll create a bump release today
