### ISSUE TITLE
BUG: Closing all tabs does not give warning of unsaved changes 

### ISSUE THREAD

**Issue by azmy60** [beekeeper-studio/beekeeper-studio#1700]
**To Reproduce**
1. Make some changes in many tabs (writing queries, creating a table, etc.)
2. Right click the tab and `Close All`/`Close Other`/`Close Tabs to The Right`

**Expected behavior**
It should give a warning like when closing a single tab.

**Additional context**
It should be able to handle unsaved changes in multiple tabs too.

**Comment by not-night-but** [comment]
@azmy60 good catch! I'm assuming this behaviour also happens with Close Others and whatever other variations we have?

**Comment by azmy60** [comment]
@not-night-but yeah, including close tabs to the right.
