### ISSUE TITLE
BUG: Foreign key links don't work

### ISSUE THREAD

**Issue by PHLAK** [beekeeper-studio/beekeeper-studio#1710]
**Describe the bug**

When clicking a foreign key link nothing happens.

**To Reproduce**

1. Have foreign key relation on a column to another table
2. Add a row with the foreign key defined
3. Click the foreign key link
4. Nothing happens

**Expected behavior**

I'm brought to the record for the foreign key in the related table.

**Screenshots / Gifs**

![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/53531/2a129774-51a6-4ecb-94b4-7db865c832e6)

**Version Information (please complete the following information):**

 - OS: Arch Linux
 - App Version: 3.9.20
 - Database type and version: MySQL 8.0

**Additional context**

Looks like this happened before (#1220) but was resolved.

**Comment by rathboma** [comment]
Hey! This is resolved in Master, and new release coming out in the next day or two. Sorry about the problems!

**Comment by PHLAK** [comment]
Thanks @rathboma!
