### ISSUE TITLE
BUG: [Critical] v4.0.2 compound foreign keys issue

### ISSUE THREAD

**Issue by intaniger** [beekeeper-studio/beekeeper-studio#1714]
**Describe the bug**
This bug has only occurred in Beekeeper v4.0+, both the open-source and ultimate versions, while trying to browse a table that is hosted by PostgreSQL 15.4 with the following command:

`docker run --rm -p 5432:5432 cloudiana/pg-tpcc:1.0.0`

When trying to open table `customer1`, the table view tab displays nothing, but the PostgreSQL log displays the following error

```
2023-09-29 08:05:14.710 UTC [107] ERROR:  more than one row returned by a subquery used as an expression
2023-09-29 08:05:14.710 UTC [107] STATEMENT:  
	SELECT
	   kcu.constraint_schema AS from_schema,
	   kcu.table_name AS from_table,
	   kcu.column_name AS from_column,
	   rc.unique_constraint_schema AS to_schema,
	   tc.constraint_name,
	   rc.update_rule,
	   rc.delete_rule,
	   (SELECT kcu2.table_name
	    FROM information_schema.key_column_usage AS kcu2
	    WHERE kcu2.constraint_name = rc.unique_constraint_name) AS to_table,
	   (SELECT kcu2.column_name
	    FROM information_schema.key_column_usage AS kcu2
	    WHERE kcu2.constraint_name = rc.unique_constraint_name) AS to_column
	FROM
	   information_schema.key_column_usage AS kcu
	JOIN
	   information_schema.table_constraints AS tc
	ON
	   tc.constraint_name = kcu.constraint_name
	JOIN
	   information_schema.referential_constraints AS rc
	ON
	   rc.constraint_name = kcu.constraint_name
	WHERE
	   tc.constraint_type = 'FOREIGN KEY' AND
	   kcu.table_schema NOT LIKE 'pg_%' AND
	   kcu.table_schema = $2 AND
	   kcu.table_name = $1;
```

This bug also happened when try to browse a table structure

**To Reproduce - Table data not shown**
1. Spin up PostgreSQL database with `docker run --rm -p 5432:5432 cloudiana/pg-tpcc:1.0.0`
2. Connect to the database using URI string `postgres:postgres-tpcc@localhost:5432/postgres`, no worries, just benchmark data there, nothing sensitive 😃  .
3. Click `customer1` tab to browse data in the table
4. Nothing is displayed, but you can see an error message on docker logs side

**To Reproduce - Table data not shown**
_After spinning up the database in the same fashion as above ☝🏽_ 
1. Right-click on `customer1` tab > View Structure
2. Error happened: `more than one row returned by a subquery used as an expression`

**Expected behavior**
It should display correctly, the same way to v3.9.20

**Screenshots / Gifs**
<img width="1312" alt="image" src="https://github.com/beekeeper-studio/beekeeper-studio/assets/37364131/45acf47f-f619-41bb-84e2-f8d42f4f5f01">
<img width="1312" alt="image" src="https://github.com/beekeeper-studio/beekeeper-studio/assets/37364131/d6d206d7-0654-4019-a876-bad06beca3af">

**Version Information (please complete the following information):**
 - OS: macOS Sonoma 14.0
 - App Version: 4.0.2
 - Database type and version: PostgreSQL:15.4

**Additional context**
I think this happened as v4.0+ will query the database in a different way than v3.9.20 
Users who have installed v4.0+ without prior `.dmg` of version 3.9.20, especially those who are using the ultimate version , will suffer from this bug, seeing no workaround.

**Comment by iifawzi** [comment]
The issue is happening because the customer has a compound foreign key referencing the district table 
``` SQL
fkey_customer_1_1 FOREIGN KEY (c_w_id,c_d_id) REFERENCES public.district1(d_w_id,d_id);
```

I'd love to work on fixing this, and at the same time, I will refactor it so we treat compound keys correctly, as follows: 

1- in the table structure, it should be shown in a single row - it will fix this issue too - instead of duplicating each key twice as in old versions. 
2- The referenced table is to be filtered by the compound values while navigating to it from the referencing table ( customer to district ).

I will address these and create a PR, in a couple hours. 

let me know if I'm missing something, or if it should be handled in a different way.

**Comment by intaniger** [comment]
@iifawzi  Thanks a lot! My use case was to view all indexes in this table, but I also later found that it displayed duplicate reference keys in v3.9.20, despite having all the same foreign keys. So I'm completely in agreement with you on both points.  

Hope and wish the best to a better version of Beekeeper!
