### ISSUE TITLE
BUG: Table Rows not showing after 4.0

### ISSUE THREAD

**Issue by desenvolvimento02jocc** [beekeeper-studio/beekeeper-studio#1719]
**Describe the bug**
After updating to 4.0, selected table doesn't show any data.

**To Reproduce**
Opening a table in postgres after updating to 4.0

**Expected behavior**
...To show my table rows

**Screenshots / Gifs**
![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/87676055/88749698-2ed6-46d1-b379-edcd401aa526) 
![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/87676055/8e089f2a-f478-4310-ab1f-caefed4a7955)

**Version Information (please complete the following information):**
 - OS: WIN 10
 - App Version 4.0 Community
 - Database type and version Postgresql

**Additional context**
Extremely weird issue, never had it.

**Comment by rathboma** [comment]
Hey @desenvolvimento02jocc quick question -- does this table have a composite primary key?

If so - we've already fixed this and will be pushing a patch release soon
If not - could you open the developer console and see if there are any errors?

**Comment by desenvolvimento02jocc** [comment]
It doesn't has a composite primary key.
This is the error that shows when I open the table.
![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/87676055/71eea6c7-1a46-46b0-bd45-eff34c8a03ba)

The structure tab works fine, and it looks like this:
![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/87676055/c34b7e9e-079f-49f2-8501-1d60360d750d)

**Comment by rathboma** [comment]
Huh, looks like two of your columns don't have types? Is that a bug?

**Comment by rathboma** [comment]
If you can provide me with some SQL code to replicate that table structure (with the missing types). I can identify the root issue and get the whole thing fixed.

**Comment by desenvolvimento02jocc** [comment]
> I've found that `toLowerCase` and fixed it, but looking at your table structure:
> 
> Two of your columns don't have types. Is that real, or is that another Beekeeper Studio bug?

They do have a type, it was defined using Sequelize, the two types are supposed to be a FLOAT.
```js
      totalAmount: {
        type: Sequelize.FLOAT,
        allowNull: false,
      },
      discount: {
        type: Sequelize.FLOAT,
        allowNull: false,
      },
```
Extremely simple migration.

**Comment by desenvolvimento02jocc** [comment]
The entire migration:
```js
"use strict";

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.createTable("ordersRequest", {
      id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
        type: Sequelize.INTEGER,
      },
      companyId: {
        type: Sequelize.INTEGER,
        allowNull: false,
        references: {
          model: "companies",
          key: "id",
        },
        onDelete: "CASCADE",
      },
      clientId: {
        type: Sequelize.INTEGER,
        allowNull: true,
        references: {
          model: "clients",
          key: "id",
        },
        onDelete: "CASCADE",
      },
      statusId: {
        type: Sequelize.INTEGER,
        allowNull: true,
        references: {
          model: "orderRequestTags",
          key: "id",
        },
        onDelete: "CASCADE",
      },
      totalAmount: {
        type: Sequelize.FLOAT,
        allowNull: false,
      },
      discount: {
        type: Sequelize.FLOAT,
        allowNull: false,
      },
      vendorId: {
        type: Sequelize.INTEGER,
        allowNull: true,
        references: {
          model: "companyVendors",
          key: "id",
        },
      },
      paymentMethod: {
        type: Sequelize.STRING,
        allowNull: true,
      },
      withdrawalDate: {
        allowNull: true,
        type: Sequelize.DATE,
      },
      createdAt: {
        allowNull: false,
        type: Sequelize.DATE,
      },
      updatedAt: {
        allowNull: false,
        type: Sequelize.DATE,
      },
    });
  },

  down: (queryInterface) => {
    return queryInterface.dropTable("ordersRequest");
  },
};
```

**Comment by vkSegfault** [comment]
Indeed there is something fishy going on with FLOAT type.

I made 2 separte attempts to create table containing one row of floats: one with Sping Data and another with Rust's Diesel. They seem to be working fine but in Beekeeper it's not showing type at all:
```java
// Spring Data
@Getter
@ToString
@Entity
@Table( name = "infra" )
@Document( indexName = "infra")
public class Infra {

    @Id
    private String name;
    private float infra_modifier;
    private int price;
}
``` 
```sql
-- SQL for Diesel
create table
  "public"."infra" (
    "name" VARCHAR(255) not null,
    "infra_modifier" FLOAT null,
    "price" INT null,
    constraint "infra_pkey" primary key ("name")
  )
```
How it looks like ine Beekeeper:
![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/45318345/2a0a0ca6-dcca-4a32-b6fd-9369899a7026)
![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/45318345/4f4afd66-1c03-4449-910c-aec4636239ca)

and to compare with some other SQL editor (here DBeaver) - floats are displayed correctly:
![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/45318345/b70ef224-8bfc-4602-a1ee-d38e384ac318)

**Comment by s-bose** [comment]
Can confirm, facing the same issue from ^v4.
