### ISSUE TITLE
Error displaying icon

### ISSUE THREAD

**Issue by JyCAydon** [beekeeper-studio/beekeeper-studio#172]
![image](https://user-images.githubusercontent.com/41415004/83372886-40594d80-a3f9-11ea-986b-811f8e0cbe72.png)

Almost all icons can't be displayed.
os: Ubuntu 18.04.3 mini installation

**Comment by rathboma** [comment]
Can you run like this:

DEBUG=beekeeper* beekeeper-studio

And see what errors are in the terminal or the js console?

**Comment by JyCAydon** [comment]
![image](https://user-images.githubusercontent.com/41415004/83603984-ef3b8c00-a5a7-11ea-97ed-f6bfb826510a.png)

**Comment by rathboma** [comment]
@JyCAydon what installer version is this? Is this the tarball?

**Comment by JyCAydon** [comment]
I use apt to install. And where can i find version?

**Comment by rathboma** [comment]
If you used apt install then it's the latest version... Can you test the AppImage version and see if it has the same issue? link - https://www.beekeeperstudio.io/download/?platform=appimage

**Comment by JyCAydon** [comment]
![image](https://user-images.githubusercontent.com/41415004/84037213-d7fa0580-a9d0-11ea-8bf6-07018a9f1ded.png)
sorry, I forget to test the AppImage. The AppImage version has the same issue too.

**Comment by rathboma** [comment]
@JyCAydon did you manage to run with the debug flag to see if there were any errors? Check both terminal output and the developer console in the app

**Comment by JyCAydon** [comment]
It works now.
