### ISSUE TITLE
BUG: Autocomplete wiping whole line

### ISSUE THREAD

**Issue by mattnSwimd** [beekeeper-studio/beekeeper-studio#1720]
**Describe the bug**
When using the autocomplete for table columns on a left join, it wipes the line for the left join

**To Reproduce**
1. Start Typing out a left join
2. give table an alias
3. when typing the on clause, use the alias to autocomplete the column
4. select the autocompleted selection

**Expected behavior**
It should finish typing the selected column name

**Screenshots / Gifs**
I am attaching a video of it happening

**Version Information (please complete the following information):**
 - OS: [e.g. Windows/Mac/Ubuntu]
        Windows
 - App Version [e.g. help -> About Beekeeper Studio]
        4.0.0
 - Database type and version [eg Posgresql 9.3]
        Mariadb and mysql

**Additional context**
Nope

https://github.com/beekeeper-studio/beekeeper-studio/assets/121575096/a5fb6714-edd6-4855-a7f9-f8194959d302

**Comment by rathboma** [comment]
Hey @mattnSwimd That is very strange. I haven't seen this at all, but I'm going to try and replicate it. Thank you SO MUCH for reporting it.

Can you past a SQL query I can use to replicate this behavior?

**Comment by rathboma** [comment]
Based on where the dropdown appears for the autocomplete in your video it seems like the autocomplete system thinks that `LEFT JOIN officeproductprices` is the end of the table name.

**Comment by mattnSwimd** [comment]
I cannot post it publicly but a can provide it to you, also I noticed on that same query the Undo and Redo are totally messed up too.

**Comment by rathboma** [comment]
Ok that's great. Thanks.

If you can find a way to reproduce the problem with a query you can share that would be SUPER helpful.

Some other questions to help me debug:

1. What version of MariaDB or MySQL are you using?
2. If you press escape to cancel the autocomplete, then press ctrl+space again to trigger it, does it do anything?

**Comment by mattnSwimd** [comment]
My MariaDB version I am currently seeing this in is 10.5.16-MariaDB, for whatever reason I deleted the query by accident and had to retype the part from the video. I restarted to application and now as I am retyping it, the autocomplete is not showing up at all.

Sorry this is getting so confusing, I have no idea what is going on with it at this point.

**Comment by rathboma** [comment]
The error trace you sent me does have a helpful error trace in it. Looks like you're running a pretty complex query and my formatter isn't able to recognize it (It thinks you have a query error).

Probably there is something in your SQL code that is confusing the Beekeeper query parsing engine, if it possible to make a generic version of this query to share it would help me identify it.  Likely it's a part of the query not shown in the video.

**Comment by mattnSwimd** [comment]
I haven't tried to downgrade as I am really enjoying this update and even with the issue, I prefer it over the prior version I had. I attached a generic version of the query. I will keep watching for more in the console, and post it here.
[crazyQuery.txt](https://github.com/beekeeper-studio/beekeeper-studio/files/12770806/crazyQuery.txt)

**Comment by mattnSwimd** [comment]
[another.txt](https://github.com/beekeeper-studio/beekeeper-studio/files/12770850/another.txt)

Here is another error I am getting.

**Comment by azmy60** [comment]
@mattnSwimd In your generic version of the query, can you pinpoint which line that causes the issue?

**Comment by mattnSwimd** [comment]
```
LEFT JOIN product_prices AS ppTwo ON ppTwo.product_id = mt.product_id
  AND  ppTwo.reason = 5
  AND NOT EXISTS (
```

It is the second condition on line 47 that caused the issue

**Comment by mattnSwimd** [comment]
It has just happened again with a totally different query

```
SELECT
  l.id,
  l.name,
  l.type,
  GROUP_CONCAT(ih.colThree)
FROM
  tableone AS l
  LEFT JOIN tabletwo AS i ON i.t_id = l.id
  LEFT JOIN tablethree AS ih ON ih.i_id = i.id
WHERE
  l.condition = 0
  AND i.id IS NOT NULL
```

In this query it happened on the group concat

```
10:23:00.049 (query-editor)        › Error: Unknown column 'locations.ishub' in 'where clause'
    at Packet.asError (C:\Users\Matt\AppData\Local\Programs\beekeeper-studio\resources\app.asar\node_modules\mysql2\lib\packets\packet.js:728:17)
    at Query.execute (C:\Users\Matt\AppData\Local\Programs\beekeeper-studio\resources\app.asar\node_modules\mysql2\lib\commands\command.js:29:26)
    at PoolConnection.handlePacket (C:\Users\Matt\AppData\Local\Programs\beekeeper-studio\resources\app.asar\node_modules\mysql2\lib\connection.js:456:32)
    at PacketParser.onPacket (C:\Users\Matt\AppData\Local\Programs\beekeeper-studio\resources\app.asar\node_modules\mysql2\lib\connection.js:85:12)
    at PacketParser.executeStart (C:\Users\Matt\AppData\Local\Programs\beekeeper-studio\resources\app.asar\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\Users\Matt\AppData\Local\Programs\beekeeper-studio\resources\app.asar\node_modules\mysql2\lib\connection.js:92:25)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
```

This is the error it recieved

**Comment by azmy60** [comment]
I've spotted something that potentially is the root cause of this issue and added the patch to this PR #1722. Would you be able to test this using the built files [attached](https://github.com/beekeeper-studio/beekeeper-studio/actions/runs/6386542622?pr=1722) of it? Just to confirm from your end.

**Comment by mattnSwimd** [comment]
If you can give me a quick crash course of what you need me to do, I've only worked with the chromium web containers and electron briefly.

**Comment by azmy60** [comment]
There is a windows executable that you can download at the bottom of the page. This is the link of for the [artifact](https://github.com/beekeeper-studio/beekeeper-studio/suites/16803347033/artifacts/959667782).

**Comment by mattnSwimd** [comment]
I just ran the second query with that artifact, and it did not mess up on the group concat. I think that change fixes it.
