### ISSUE TITLE
BUG: In SQL Server: The "View Data" and "View Structure" functions do not work with the latest update.

### ISSUE THREAD

**Issue by elmouse19** [beekeeper-studio/beekeeper-studio#1730]
**Describe the bug**
Today I updated to the latest version (4.0.3), and from there, the application has some errors. I cannot use the mentioned functions, since they open a tab but it is completely empty, or it shows an error message ("CONCAT is not a buit-in function name.").
At the moment I have not found another problem. If I do, I'll add it here.

**To Reproduce**
1. Go to 'any table'
2. Right click on 'the table'
3. Click on '"View data" or "View structure" options'
5. See error

**Expected behavior**
View the table data, or its structure.

**Screenshots / Gifs**
![image_2023-10-03_09-19-59](https://github.com/beekeeper-studio/beekeeper-studio/assets/9272135/37e020b0-e4b2-4044-b615-6087b18ed7ba)

**Version Information (please complete the following information):**
 - OS: Window 10
 - App Version 4.0.3
 - Database type and version SQL Server

**Additional context**
As soon as you connect to a database, in the development tools you can see a javascript error in the console.

**Comment by rathboma** [comment]
Hey! Thanks for the report! We'll look into it.

@elmouse19 what version of SQL Server are you using?

**Comment by not-night-but** [comment]
@elmouse19 are you still seeing this behaviour? I'm not able to reproduce it at all.

**Comment by rathboma** [comment]
Looks like we need to avoid the use of CONCAT in SQL Server to maintain compatibility with SQL Server < 2012:

```
There's also no way to make it fail in 2012+, even with compatibility level. So have your people check SELECT @@VERSION; on both servers; you'll find that where CONCAT fails it is < 11. In order to make your code compatible with earlier versions, you'll need to use the standard string concatenation operator (+)
```
