### ISSUE TITLE
BUG: Double clicking an opened tab from the left menu opens the tab again

### ISSUE THREAD

**Issue by VenatusSimpleX** [beekeeper-studio/beekeeper-studio#1732]
**Describe the bug**
It seems like the bug from https://github.com/beekeeper-studio/beekeeper-studio/issues/469 popped up again, because now when I double click a table from the sidebar, a duplicate opens up instead of switching to that tab.

**To Reproduce**
1. Double click a table
2. Wait for the table to load
3. Double click the table again

**Expected behavior**
Double clicking an already-opened table should switch the user to the tab instead of duplicating it.

**Screenshots / Gifs**

https://github.com/beekeeper-studio/beekeeper-studio/assets/31540342/18253999-4305-4eb0-b9bd-8737b0cc4345

**Version Information (please complete the following information):**
 - OS: Mac
 - App Version: 4.0.3
 - Database type and version: 11.1.2-MariaDB Homebrew

**Comment by rathboma** [comment]
So I think we need to tidy this up, but we do this so as to not blitz any filters you have.

For example, you can click a foreign key from a table view and it opens the FK record in a new tab. If it took over an active tab, you would lose your filters or sorting.

Maybe that's fine. I'm going to think about this some more and maybe experiment with one table = one tab

**Comment by VenatusSimpleX** [comment]
Thanks for the reply! I didn't know about pressing the FK that would link us to the filtered data, very nifty!

Would it makes sense to store the filter and/or sorts as like a state or a hash? So if say when you double-click a tab, it can first compare if the target link has the same hash with any opened tabs. If there's a match, it'll shift you over to that tab, if there's no match, then it'll open up a new tab for you?

**Comment by erlangparasu** [comment]
https://github.com/beekeeper-studio/beekeeper-studio/issues/1775

**Comment by azmy60** [comment]
Closing this in favor of #1834.
