### ISSUE TITLE
BUG: Wrong SQL generated when column name ends with `?`

### ISSUE THREAD

**Issue by cschmatzler** [beekeeper-studio/beekeeper-studio#1734]
**Describe the bug**
When a column name ends with a question mark, e.g. `approved?`, the SQL generated by BS gets mangled and is invalid.

**To Reproduce**
1. Create a table with a column including a question mark.
As an example, here's one of mine:
```sql
CREATE TABLE
  auth.organisation_members (
    "approved?" boolean NULL DEFAULT false,
    organisation_id character varying(255) NOT NULL,
    identity_id character varying(255) NOT NULL
  );
```
3. Open the table in Beekeeper Studio and try to edit the value of a row.
4. Try to save the row.

**Expected behavior**
The row should save without any issues.

**Actual behavior**
The saving fails, with the generated SQL being
```sql
update
  "auth"."organisation_members"
set
  "approvedfalse" = 'organisation_01hby3vz36fxyt9ds522twgmhx'
where
  "organisation_id" = 'identity_01hby3vbszfthvzdh3181z47bv'
  and "identity_id" = ?;
```

**Version Information (please complete the following information):**
 - OS: macOS 14.0
 - App Version: 4.0.2
 - Database type and version: Postgres 16.0

**Comment by rathboma** [comment]
Thanks for highlighting this!
