### ISSUE TITLE
CTRL+Right shouldn't work when editing a row.

### ISSUE THREAD

**Issue by arshx86** [beekeeper-studio/beekeeper-studio#1735]
**Describe the bug**
When editing a row value, if you use CTRL+Right to point anywhere of text you editing, it forwarding to next page. Which causes all the changes being lost if you hit Ctrl+Right.

**To Reproduce**
1. Go edit any row.
2. While editing, use `CTRL+Right`
3. All the changes you made is lost and you forwarded to next page. (That's a another bug, even that much page doesn't exists it still allows you increment the page.)

**Expected behavior**
Ctrl+R shouldn't forward to next page. While editing a row.

**Version Information (please complete the following information):**
MySQL-Windows10-Beekeeper 4.0.3

**Additional context**
Ctrl+right shouldn't go to next page while editing a column. It only should do the mission of ctrl+r. Because i lost all of the changes i made because i hit ctrl+right to point anywhere of the text.

**Comment by rathboma** [comment]
Thanks! Yeah I think ctrl+rightarrow should behave the same way as on a spreadsheet
