### ISSUE TITLE
FEAT: CTRL + P multiple select

### ISSUE THREAD

**Issue by mattnSwimd** [beekeeper-studio/beekeeper-studio#1737]
**Is your feature request related to a problem? Please describe.**
It is not at all a problem. I would like to request the ability to select multiple tables when using the CTRL + P menu to select tables.

**Describe the solution you'd like**
I do not know how complicated it would be to implement, but the right arrow key opening a table without closing the CTRL + P menu would be perfect. If you need more reference, using the CTRL + P shortcut in vscode and use the right arrow on multiple files in the list. 

**Describe alternatives you've considered**
Potentially, maybe a modifier like holding shift to once the menu is open and pressing enter on the tables you want, then upon releasing shift it would open all selected tables.

**Additional context**
This exact feature is in vscode currently for opening files and it is fantastic, If you haven't used it 10/10 I would highly recommend.

**Database type, if appropriate**
I use mariaDB and MySQL mainly, and am unsure how the other databases function in beekeeper, but I'd imagine it would apply to all of them.

**Comment by rathboma** [comment]
Huh, I had no idea you could do that in VSCode, neat! Yeah we can probably have the exact same behavior

**Comment by rathboma** [comment]
Note for implementation, pressing right arrow on an item in the list opens it in a tab in the background. Ctrl+right arrow should work the same as ctrl+enter

**Comment by mattnSwimd** [comment]
The feature is awesome, thanks!
