### ISSUE TITLE
SSH Tunnel timeout is too long, makes it look like the app has frozen

### ISSUE THREAD

**Issue by lawless-m** [beekeeper-studio/beekeeper-studio#174]
When I select SSH Tunnel it fails with the error message

"Failed to connect to 127.0.0.1:10000 in 15000ms"

I have no services running on that port

Looking online it suggests trying to reach Network Data Management Protocol (NDMP) but that's just a guess.

It works when I create the tunnel manually with ssh -L ........

so I can just use a wrapper and keep working

I'm using the Appimage version

**Comment by rathboma** [comment]
It's just using that port for the tunnel, but seems like it's failing to pass through the packets maybe.

Are you behind any type of firewall?

**Comment by rathboma** [comment]
Can you run like this:

```
DEBUG=* ./beekeeper-studio.AppImage
```

**Comment by rathboma** [comment]
Ah, great to know! Glad I didn't break SSH :-).

I'm changing the topic of the thread to match this

**Comment by lawless-m** [comment]
I must apologise. I too have got it working.

I still think the error message could do with changing as it didn't help me diagnose the problem.

I don't know if it is possible to tell whether it connected to the first hop or the target.
