### ISSUE TITLE
BUG: Cannot get SQL for a regular view on Postgres with capital letter

### ISSUE THREAD

**Issue by CooperMidnight** [beekeeper-studio/beekeeper-studio#1746]
**Describe the bug**
When the name of a view has a capital letter, the "SQL: Create" context menu item doesn't work.

**To Reproduce**
Example view definition:
```
CREATE OR REPLACE VIEW "Test" 
AS
SELECT 1 AS "DummyColumn";
```

1. Create a view whose name contains at least one capital letter
2. Refresh the database in Beekeeper
3. Right-click the view and select "SQL: Create"

**Expected behavior**
New tab opens with `CREATE` code.

**Screenshots / Gifs**
![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/121775581/1bcfd9b5-589b-4a48-ab6f-177289f06c62)

**Version Information (please complete the following information):**
 - OS: Windows 10
 - App Version 4.0.3
 - Database type and version: Postgres 16

**Additional context**
N/A

**Comment by CooperMidnight** [comment]
This seems to be a problem with postgres itself. Manually executing the query

```
SELECT PG_GET_VIEWDEF('ViewNameHere'::regclass, true);
```

yields an error:

```
relation "viewnamehere" does not exist
```

**Comment by rathboma** [comment]
That's def a bug we can work around. It hink we just need to use a different query. Thanks for the bug report!

I think You probably have to do `'"ViewNameHere"'` to have it work
