### ISSUE TITLE
BUG: Tools -> Export data button not working

### ISSUE THREAD

**Issue by rathboma** [beekeeper-studio/beekeeper-studio#1748]

**Comment by davidkaufman** [comment]
I wan't able to reproduce this bug.  The "Export Data" menut item under the Tools menu opened the "Data Export (beta)" tab and i was able to go through all three steps and export a CSV of my table.

on:

 - OS: MacOS Ventura 13.06 (I finally upgraded!)
 - App Version: Beekeeper Studio Ultimate 4.03
 - Database type and version: Sqlite 3.41.0

What happened when you tried it?

**Comment by wmontgomery** [comment]
@rathboma Also was able to run it through on Max OS14.1 in a few different DB clients. 
![titlebar](https://github.com/beekeeper-studio/beekeeper-studio/assets/314613/e9e91a64-b43c-4142-bf5d-76da0e19e367)

**Comment by rathboma** [comment]
@wmontgomery ^ here is how to replicate.
