### ISSUE TITLE
Not everyone loves dark mode

### ISSUE THREAD

**Issue by lawless-m** [beekeeper-studio/beekeeper-studio#175]
And I'm one of them. 

Any way to enable black-on-white ?

**Comment by ghstng** [comment]
There is a light theme; we just haven't created a way to switch yet (Still working on a Settings View).

**Comment by tonyrein** [comment]
Just adding my vote -- I never have understood the appeal of dark themes! Thank you for your work on this -- other than the theme it looks great, and I'm looking forward to being able to use it.
--T

**Comment by iKlsR** [comment]
Duplicate of #26

**Comment by lawless-m** [comment]
oh, sorry for the dupe, I did scan through but missed it

**Comment by lawless-m** [comment]
hey, you implemented it - thanks mate
