### ISSUE TITLE
FEAT: Beautify and Format JSON Data Enhanced Readability

### ISSUE THREAD

**Issue by khad1r** [beekeeper-studio/beekeeper-studio#1759]
**Is your feature request related to a problem? Please describe.**
Yes, it is. When working with JSON data in MySQL using Beekeeper Studio, the data is displayed as a single line in a cell. This makes it difficult to read and understand the data structure, especially when dealing with complex JSON objects.

**Describe the solution you'd like**
I would like Beekeeper Studio to have a feature that formats or beautifies the JSON data in MySQL. Instead of showing the entire JSON data as a single line in a cell, it would be great if the data could be formatted in a readable structure with proper indentation.

**Describe alternatives you've considered**
An alternative could be to provide an option to view the formatted JSON data in a separate window or panel when clicked on the cell. This would avoid cluttering the main data view but still provide easy access to a more readable format of the JSON data.

Here's VSCode Database Client Example
![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/60246846/14126a5c-98c4-4b64-8d61-0114655325d7)
![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/60246846/61664625-a15d-4222-abad-d5d43a23b111)
![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/60246846/bf5f27ea-8820-4b51-8d88-8a88d02d615d)

**Additional context**
This feature would greatly improve the readability and accessibility of JSON data in MySQL, making it easier for users to understand and work with complex data structures.

**Database type, if appropriate**
MySQL/MariaDB databases.

**Comment by Z3rio** [comment]
As much as I hate storing JSON in SQL, I do agree that this is a great idea.
I'll see if I have some free time to have a look at this.

**Comment by khad1r** [comment]
Hi Z3rio, it’s great that you’re open to this idea
Can’t wait to see how it turns out!

**Comment by Z3rio** [comment]
I've started working on this now, you guys can assign me to this issue if you wish :)
