### ISSUE TITLE
Bug: Duplicated results when joining tables and selecting columns with the same names

### ISSUE THREAD

**Issue by ptrkrlsrd** [beekeeper-studio/beekeeper-studio#176]
## Bug
When joining two tables where there are columns with the same name(e.g `artist.name` and `album.name`), only results from the last selected column are shown in the results table as shown below. In the example below I join a table called `artist` with one called `album`. Both of these have a column called `name` which causes a conflict when showing the results. 

<img width="902" alt="Skjermbilde 2020-06-01 kl  14 16 36" src="https://user-images.githubusercontent.com/6945858/83409232-51638800-a414-11ea-9a38-9cfbc2ce2098.png">

## Expected behavior
When initially performing the query above I expected the name of the albums to be shown in the left column of the results, and the name of the artist to be shown in the rightmost column. This is what `psql` would have done. A workaround is performing the same query with column aliases.

<img width="899" alt="Skjermbilde 2020-06-01 kl  14 31 37" src="https://user-images.githubusercontent.com/6945858/83409412-a6070300-a414-11ea-86f3-619740d6e463.png">

OS: macOS Catalina
Database: Postgres 10.5 (Alpine)

**Comment by rathboma** [comment]
Yes very interesting. I'll see what I can do about this.

**Comment by ptrkrlsrd** [comment]
> Yes very interesting. I'll see what I can do about this.

Lovely! I might take a look at it myself if I find some time

**Comment by cursorius-cursor** [comment]
Discoverd the same effect and tested with a sqlite3 database. In postgres the first column is doubled, in sqlite the second column with the same name is not shown.

`CREATE TABLE T1(
NUM INT PRIMARY KEY     NOT NULL,
NAME            TEXT    NOT NULL);

CREATE TABLE T2(
NUM INT PRIMARY KEY     NOT NULL,
NAME           TEXT);


INSERT INTO T1 VALUES(1,'a');
INSERT INTO T1 VALUES(2,'b');
INSERT INTO T1 VALUES(3,'c');
INSERT INTO T1 VALUES(4,'d');

INSERT INTO T2 VALUES(1,NULL);
INSERT INTO T2 VALUES(2,'xxx');
INSERT INTO T2 VALUES(3,'yyy');
INSERT INTO T2 VALUES(4,'zzz');

select t1.name, t2.name from t1,t2;`

**Comment by UtechtDustin** [comment]
We have to use the option `rowMode` for the sqlite client and `nestTables` for mysql.
For the other clients we have to check if there is a similar option.

**Comment by rathboma** [comment]
Yeah this will be DB by DB and require some fairly big API changes. Will have to wait until after this mammoth release is out :+)

**Comment by rathboma** [comment]
This is fixed for PostgreSQL, other databases require more work.

**Comment by rathboma** [comment]
MySQL2, use `rowsAsArray`: https://github.com/sidorares/node-mysql2/blob/a80d2cab92b5809e810ae8a2e0f6841c6f8e1d7e/lib/parsers/text_parser.js#L144

**Comment by rathboma** [comment]
Oh, this is fixed (in as many databases as possible)
