### ISSUE TITLE
FEAT: libsql-server / Turso support

### ISSUE THREAD

**Issue by lukeberry99** [beekeeper-studio/beekeeper-studio#1762]
**Is your feature request related to a problem? Please describe.**
I've recently swapped to Turso for new projects, and would love a native/desktop app to interact with it.

**Describe the solution you'd like**
Support for libsql/turso - I think we would _just_ need to allow a URL + token instead of just a file for the SQLite driver. 

**Database type, if appropriate**
sqlite/libsql/turso

**Comment by meitrix8208** [comment]
+1 here

**Comment by RemcoE33** [comment]
I would like this as well. As far as I know there is no SQL editor that supports Turso. I my opinion the mindset of Turso matches greatly. Would be a win win.

**Comment by knekvasil** [comment]
Any update on this?

**Comment by pedroresende** [comment]
Any news on this ?

**Comment by rathboma** [comment]
Hey all, question, seems like libsql, and turso-server are two separate things? libsql would be a different library to access local .db files, but the server would allow remote connections, is that a valid summary?

Looks like this is the client for remote conns - https://docs.turso.tech/sdk/ts/quickstart
And this is libsql for local file access? - https://github.com/tursodatabase/libsql-js

Maybe these should be two tickets?

**Comment by rathboma** [comment]
Notes on implementation:
- Testing: would need to build a docker image of libsql-server (that's the turso server). They don't provide one 🙄
- Implementation: This should be a subclass of the `sqlite` driver
- Dialect is `sqlite`
- Tests should be able to run anything that sqlite can run. It will need to make sure any tests for `sqlite` also check for turso

**Comment by rathboma** [comment]
Note: This ticket is ONLY for libsql-server / Turso support. Local libsql support should be added separately.

**Comment by sunxyw** [comment]
> Hey all, question, seems like libsql, and turso-server are two separate things? libsql would be a different library to access local .db files, but the server would allow remote connections, is that a valid summary?
> 
> Looks like this is the client for remote conns - https://docs.turso.tech/sdk/ts/quickstart
> And this is libsql for local file access? - https://github.com/tursodatabase/libsql-js
> 
> Maybe these should be two tickets?

If I understand it right. The libsql-js is a better-sqlite compatible client with remote database support, it supports both local and remote connections. Instead, the sdk is dedicated for remote libSQL connection.

So we should be able to use libsql-js for both local and remote libSQL support.
