### ISSUE TITLE
BUG: Text auto change issues.. 

### ISSUE THREAD

**Issue by mahimaholla** [beekeeper-studio/beekeeper-studio#1766]
when you write a  query and auto change the text it removes previous text also
![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/48175865/3ed4571c-abf7-45ef-a3e2-cfe0beccfa21)
here when firstname is selected previous column name disappers
![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/48175865/533e0409-87a4-49e0-9eed-c796325a3fcf)
like this

**Comment by rathboma** [comment]
@azmy60 is this fixed by your recent changes?

**Comment by azmy60** [comment]
yeah, tested with master branch. Thanks for reporting tho!
