### ISSUE TITLE
FEAT: Keybind for reopening recently closed tab

### ISSUE THREAD

**Issue by Z3rio** [beekeeper-studio/beekeeper-studio#1768]
**Is your feature request related to a problem? Please describe.**
No, this is not related to an issue, it is simply an idea/feature request

**Describe the solution you'd like**
**_Ctrl + Shift + T_** should reopen the most recently closed tab.
Just like it does in most web browsers, code editors, and such.
It has become quite a universal key bind, so why not include it here?

**Why should this be added?**
Often, we can accidentally close important tabs, especially when using Ctrl + W quickly.
And being able to quickly reopen the accidentally closed tab would be great.

**Describe alternatives you've considered**
As I am a bit new to using Beekeeper Studio, I'm unaware of other solutions.
If there are any, then please tell me.

**Database type, if appropriate**
Universal (aka not appropriate)

**Comment by Z3rio** [comment]
@rathboma Would love to get your input on this issue, as I'm thinking about starting to work on it and it would be a bit wasteful to work on it if it isn't wanted/needed.

**Comment by azmy60** [comment]
Hi @Z3rio ! I think it's reasonable to support `Ctrl+Shift+T` keybinding. Feel free to submit a PR! : )

**Comment by Z3rio** [comment]
Thank you, I'll see if I can make some time for this :)
