### ISSUE TITLE
FEAT: Please make opening tab behavior like vscode

### ISSUE THREAD

**Issue by erlangparasu** [beekeeper-studio/beekeeper-studio#1775]
**Is your feature request related to a problem? Please describe.**
currently every time clicking on table name (on sidebar) make it open new tab (on every click)

**Describe the solution you'd like**
only open 1 tab on each table

**Describe alternatives you've considered**
make opening tab behavior like vscode

**Additional context**
-

**Database type, if appropriate**
i test this on sqlite db

**Comment by Z3rio** [comment]
I think being able to open multiple tabs of the same table is intentional, although I agree that it may sometimes be a bit confusing.

**Comment by azmy60** [comment]
Closing this in favor of #1834.
