### ISSUE TITLE
make new connection configurable by URL

### ISSUE THREAD

**Issue by mariusa** [beekeeper-studio/beekeeper-studio#178]
Most database providers give only the Connection URL by default, eg
```
postgres://analyst:98kd8a9@ec2-123-73-145-214.compute-1.amazonaws.com:6212/dee932clc3mg8h
```
https://devcenter.heroku.com/articles/heroku-postgresql-credentials

Note this is one string, no need to specify the separate fields.
When creating a new connection, would you please implement support for this type of URL as an alternative to filling in all the fields?

Thanks!

**Comment by rathboma** [comment]
Yes! This always annoys me when I'm using heroku, cant believe I overlooked it.

**Comment by strotgen** [comment]
Hey, I would like to help with this if that's okay.

**Comment by rathboma** [comment]
:+1: that'd be amazing

**Comment by strotgen** [comment]
How were you thinking about doing it? 

Visually: TablePlus has an [Import from URL](https://docs.tableplus.com/gui-tools/manage-connections#importing-connection-url) button on the same screen that allows you to select the database driver. That would be one option. Or maybe adding a button to the left of _Test_ and _Connect_ buttons?

For the URI parsing, I had thought of a simple method that assigns directly to `config`.

**Comment by rathboma** [comment]
I think a import link in the top right on the connection card, even when the DB type drop-down is there would work, then that is parsed and fills in host/port/type/etc ready for the user to test/connect/etc as normal

Also, if someone pastes a valid DB url into the host field it should auto detect it and do the same

**Comment by mariusa** [comment]
Please see https://github.com/beekeeper-studio/beekeeper-studio/pull/201/commits/263b0f5070e484d7b41135d9c0dc95f5801c268f
for a bug & solution

**Comment by mariusa** [comment]
Also, please check Enable SSL too when importing (eg heroku string)

**Comment by strotgen** [comment]
Thanks for spotting that bug, I'll fix it asap.

As for the SSL option, there is already some code for doing that. It just checks for sslmode=require or sslmode=prefer in the params. I could add the other [sslmode options](https://www.cockroachlabs.com/docs/stable/connection-parameters.html#secure-connections-with-urls), if that's the problem.

If it isn't working for you, could you please provide me an example of how heroku strings are formatted.

**Comment by mariusa** [comment]
Thanks!

Heroku URL:
```
postgres://analyst:98kd8a9@ec2-123-73-145-214.compute-1.amazonaws.com:6212/dee932clc3mg8h
```

For me it didn't work without SSL, with the message
```
no pg_hba.conf entry for host ... 
```
(on Linux, Fedora)

**Comment by rathboma** [comment]
Hey folks,

I've disabled this feature currently in the 1.5.3 deploy. I have a branch to re-enable it with a few changes. Notably there are some URL parsing differences in node vs browser JS.

**Comment by mariusa** [comment]
Was this included in https://github.com/beekeeper-studio/beekeeper-studio/releases/tag/v1.6.11 ?

**Comment by rathboma** [comment]
Yes! It's back! Good point. Will close this ticket.
