### ISSUE TITLE
Enhancement:  Allow SQLite over SSH

### ISSUE THREAD

**Issue by dopeghoti** [beekeeper-studio/beekeeper-studio#179]
Allowing an SSH tunnel to "proper" SQL servers such as MySQL or Prostgres is a boon, to be sure, but it would be neat indeed to be able to use Beekeeper to also access an SQLite file stored on a remote host through a tunnel.

**Comment by rathboma** [comment]
Hey! Thanks for filing an issue. I agree this would be good.

Unfortunately this is not really possible with SSH tunnels (they require us to make a TCP connection, so we don't get a filesystem handle). We'd have to run our own node process on the remote server (like VSCode does for it's remote connections), and that's a lot of work.

Right now I recommend you use `sshfs` - https://github.com/libfuse/sshfs, mount the remote filesystem, then use Beekeeper Studio like normal.

I'm going to close the issue (no way to fix it), but please report back if that works!
