### ISSUE TITLE
BUG: SQLite generated columns not displayed

### ISSUE THREAD

**Issue by psychedelicious** [beekeeper-studio/beekeeper-studio#1804]
**Is your feature request related to a problem? Please describe.**
SQLite generated columns are not displayed in the UI. 

**Describe the solution you'd like**
- Generated columns are displayed and there is some UI indication that the column is generated.
- When using the `Structure` UI, generated columns are annotated as such

**Describe alternatives you've considered**
Using another tool or sqlite3 cli

**Additional context**
It looks like this is because `PRAGMA table_info(...);` is used. This doesn't include generated columns.

`PRAGMA table_xinfo(...);` includes generated columns.

**Database type, if appropriate**
SQLite

**Comment by azmy60** [comment]
Thanks!
