### ISSUE TITLE
BUG: COUNT() shows no return

### ISSUE THREAD

**Issue by dslotcavage** [beekeeper-studio/beekeeper-studio#1809]
**Describe the bug**
COUNT([column]) returns nothing in the return dialog box despite having non-zero return.  The same query gives the expected return in SQL Server Management Studio.

**To Reproduce**
SELECT COUNT(col1)
FROM table1
WHERE col2 = 'value'

**Expected behavior**
A single row should be returned with proper count.

**Screenshots / Gifs**
![Screenshot 2023-12-01 093559](https://github.com/beekeeper-studio/beekeeper-studio/assets/8889630/29a46981-3421-42d7-8549-f6adaa4c7459)

**Version Information (please complete the following information):**
 - OS: Windows 10
 - Version 4.0.3
 - Microsoft SQL Server 2016

**Comment by rathboma** [comment]
Well that's weird. My guess is this is a weird thing with column names. Can you try `SELECT COUNT(1) as col1`?

**Comment by dslotcavage** [comment]
Just tried; same result, unfortunately.

**Comment by rathboma** [comment]
@dslotcavage We can't replicate this. Are there any errors in the developer console (they'd be in red). Go to help -> toggle developer tools, then re-run the query.

**Comment by dslotcavage** [comment]
I was able to finally resolve this issue.  It appears to be related to unknown column names.  If I name the resulting column (as below), I then get a non-blank result!
SELECT COUNT(col1) AS testing
FROM table1
WHERE col2 = 'value'

Removing "AS testing" returns to a blank result.  Hopefully this helps someone here!

**Comment by not-night-but** [comment]
@dslotcavage oh interesting! Any chance I could get the schema of the table that's causing issues?

**Comment by dslotcavage** [comment]
I wish I could share, but, unfortunately, I can't for IP reasons :(.

**Comment by not-night-but** [comment]
@dslotcavage hey! I'm not asking for specifics of your implementation or anything. Just what is the data type of col1? Is it a key? Etc. just the minimum information for me to be able to hopefully replicate it

**Comment by dslotcavage** [comment]
This appears to happen for any of the following data types for col 1: varchar, tinyint, int, real, and datetime, and happens when the column is either a primary key or not a key at all.  Is that helpful?

**Comment by rathboma** [comment]
We've fixed this. It was an issue in the `ultimate` edition only.

**Comment by dslotcavage** [comment]
Awesome!
