### ISSUE TITLE
Feature Request: Save, Update and Delete Records

### ISSUE THREAD

**Issue by aligoren** [beekeeper-studio/beekeeper-studio#182]
Hi.

Nowadays, I'm trying to implement these features on Beekeeper's table screen. By these features, I add a new row using a <kbd>+</kbd> button. And I can remove a record using <kbd>-</kbd> button. I also use a save button, etc.

| ...| ...| ...|
|--------------|--------|-------|
| ///|///  | ///  | 
| <kbd>+ Button</kbd>          | <kbd>- Button</kbd>    | <kbd>Save Button</kbd>   | 

## Update a Record

For example, if I want to update an existing record, which column should I use as update criteria?

Let's assume we have a table like below;

| nonPrimaryID | userID | etcID | primaryKeyID |
|--------------|--------|-------|--------------|
| 12421        | 3421   | 1511  | 3            |
| 641          | 661    | 431   | 2            |

How should I update the first row's record? The primary key was placed in the last column.

Can we understand is this record a primary key?

How can we batch update? Actually, If I use the update button, I can achieve this idea using a loop.

## Insert a New Record

The second question is about to insert a new record. For example, I added a new record with the primary key field. If the primary key existed it won't be added, the SQL server will be thrown an error.

But I want to avoid run unnecessary SQL queries. If I know primary key existed in the table, I can show an alert like "This table already has a record with this primary key"

## Add a New Record by Down Arrow Key

Currently, we can add a new row using the <kbd>tab</kbd> key. I like this feature. But we can also add a new row using down arrow key on any column. Because tab expects the last column to add a new row.

Now, I can ask, how we can add a new row using down arrow and If this happens, the cursor should be focused on the new row's the same cell.

I hope these features can be added. Writing SQL queries not the hard thing. But I don't know this table library well and I think we can't have any information about primary key information.

Thanks, ^_^

**Comment by gnovaro** [comment]
I think is a related issue: Editing rows by double click #39

**Comment by aligoren** [comment]
> I think is a related issue: Editing rows by double click #39

Wow, :O there are many PRs. Thanks. I'll check it.

**Comment by AqilCont** [comment]
TBH, these are some pretty sick additions tho, would love to see these keybinds implemented.

**Comment by rathboma** [comment]
Hey! Awesome that you're thinking about this :-).

There are a few things we need to do to enable editing / deleting:
- When fetching table schemas, we should also fetch keys using `connection.getTableKeys()` - this will tell us which key is a primary key, and which is a foreign key
- If there is no indicated primary key (not sure this is even possible for most databases?), editing would be disabled.
- I think edits should be 'staged', and not actually pushed to the database until the user clicks a 'save x changes' button in the footer
- Right now the footer is controlled by tabulator. This would need to change to a bk-provided footer and the pagination buttons migrated to that footer.

In answers to your questions:
- If someone tries to insert a row with an existing PK - I think we just delegate that error handling to the database when they click save

So it's probably worth splitting up the work into different pieces all working towards supporting this:
1. Update the table-view to integrate primary / foreign key indicators
  - this would also work towards solving #118 
2. 'stage changes' API for table modifications
3. Ability to insert rows
4. Ability to delete rows
4. Ability to edit rows that contain a PK

**Comment by MasterOdin** [comment]
> If there is no indicated primary key (not sure this is even possible for most databases?)

All of the support databases of beekeeper support creating a table without a primary key. Some of them may create implicit primary keys under the hood (e.g. mysql using InnoDB), but that's completely invisible to the user.

**Comment by rathboma** [comment]
@MasterOdin I'm not sure there's a easy way to do updating if there isn't a primary key?

**Comment by MasterOdin** [comment]
An off the cuff answer would be to use the `ROW_NUMBER()` function (or something like it) which provides a sequential number per row in a view. You would then be able to use that as a test for what row to update. Not as clean as a primary key, but should be doable.

**Comment by rathboma** [comment]
Yep thought about that, but worried a little about the implications. I'm going to spy on what other db clients do and copy them :-)

**Comment by jenstornell** [comment]
I think I have the solution to this problem with tables without primary keys. I asked that question on Stackoverflow a while ago.

https://stackoverflow.com/questions/62443984/how-to-uniquely-identify-all-rows-in-a-mysql-table-without-a-primary-key

**Comment by gnovaro** [comment]
We can close this?

**Comment by UtechtDustin** [comment]
@gnovaro no. We can update records, but we cant create or delete records

**Comment by gnovaro** [comment]
You try the last version?

**Comment by UtechtDustin** [comment]
Sure, i helped to develop that.
Currently its not possible to delete/create records with the ui.

**Comment by smlarkin** [comment]
Is Create / Delete on the roadmap?

I'm using BS daily and loving it and finding that this is the only gotcha that forces me to jump from a table to a query.

**Comment by rathboma** [comment]
Yep! Delete coming in next release, create is mostly done, but needs a few tweaks

**Comment by liflovs** [comment]
Is there a ticket for bulk delete like in DBeaver?

**Comment by rathboma** [comment]
Closing this as this functionality is in Beekeeper. Bulk delete coming soon.
