### ISSUE TITLE
FEAT: View saved passwords

### ISSUE THREAD

**Issue by jdbacero** [beekeeper-studio/beekeeper-studio#1828]
**Is your feature request related to a problem? Please describe.**
I have multiple saved connections, and thought that because it is saved, I would also be able to see the passwords. It is frustrating when there are instances where I need to copy the password but I'm not able to provide them to other people, or when I need it or something else. I'm certain that this is my fault for not storing passwords in a password manager but it'd be a nice QOL if this was added.

**Describe the solution you'd like**
Like one of those typical login form in the password field where users can toggle if they want to view the password they've typed.

**Describe alternatives you've considered**
A copy button to immediately copy the password would be okay, too.

**Comment by rathboma** [comment]
Ah yeah, maybe an :eye: button to let you view the passwords would be useful. We can do that.

**Comment by rathboma** [comment]
Implementation notes:
- Add an :eye: button or `show password` checkbox that lets the user view the password.
