### ISSUE TITLE
BUG: Unable to save after setting null to a cell

### ISSUE THREAD

**Issue by hubertokf** [beekeeper-studio/beekeeper-studio#1830]
**Describe the bug**
After setting a cell to null, I'm no longer seeing the save button at the bottom right of the app.

**To Reproduce**
1. Go to any table
2. Set a cell to null

**Expected behavior**
The expected behavior is to show the save button

**Version Information (please complete the following information):**
 - OS: Linux Mint
 - App Version 4.1.0
 - Database type and version Mysql

**Comment by rathboma** [comment]
This is fixed! I think you're using the DEB version right? You actually got the pre-release 4.1 version with this bug.
