### ISSUE TITLE
BUG: When the database password contains special symbols, they are passed as is (unescaped) to mysqldump

### ISSUE THREAD

**Issue by ivanovbgr** [beekeeper-studio/beekeeper-studio#1831]
**Describe the bug**
When the database password contains special symbols, they are passed as is (unescaped) to `--password` parameter of mysqlump which leads to an error like this:

```
/bin/sh: 1: b}cyb?Av5: not found
mysqldump: [Warning] Using a password on the command line interface can be insecure.
-- Connecting to devhub2-wordpress-db-stage.cx47kcpuckwp.eu-west-1.rds.amazonaws.com...
mysqldump: Got error: 1045: Access denied for user 'admin'@'ec2-34-250-153-107.eu-west-1.compute.amazonaws.com' (using password: YES) when trying to connect
```

**To Reproduce**
1. Add connection to a mysql database having password with special (to bash) characters like `b}cyb?Av5`
2. Try to export it :)

**Expected behavior**
Successfully dump the database

**Version Information (please complete the following information):**
 - OS: Ubuntu 22.04
 - App Version: 4.0.3
 - Database type: MySQL

**Comment by rathboma** [comment]
@not-night-but  -- this should be an easy fix

**Comment by not-night-but** [comment]
@ivanovbgr  Yeah this is definitely my bad, I use fish and I guess it just doesn't care about the special characters in this instance? 

Fixing now, thanks for reporting!

**Comment by ivanovbgr** [comment]
I switched to fish with [starship](https://starship.rs/) prompt, too.
Thanks for fixing that!
