### ISSUE TITLE
FEAT: Table resizing enhancements (Tabulator Spreadsheet Mode)

### ISSUE THREAD

**Issue by rathboma** [beekeeper-studio/beekeeper-studio#1839]
Azmi is king of the spreadsheet. All hail Azmi. :crown: 

Let's take things up a knotch and double down on the sheets-style UX:

## Multi-column resizing
Selecting multiple columns and resizing one of them should resize them all to be the same width. This works for all columns if the top-left corner is selected.

[Screencast from 12-27-2023 04:19:19 PM.webm](https://github.com/beekeeper-studio/beekeeper-studio/assets/279769/17fe6b4a-9e6b-4d50-bb24-255105161391)

## Resizing like Google Sheets

1. Only allow resizing at the column headers
2. Show a visual indicator that resizing can happen
3. Don't 'live-resize' the column when dragging, show a line where the resize will go, then resize when the user releases. This will provide a MASSIVE performance improvement

[Screencast from 12-27-2023 04:21:50 PM.webm](https://github.com/beekeeper-studio/beekeeper-studio/assets/279769/53fbe3d4-a51c-4d5c-ac5a-b7a4ba5f5f19)

**Comment by azmy60** [comment]
Couldn't do it without Oli's great design on Tabulator's extensibility! :)

**Comment by azmy60** [comment]
@rathboma  Not sure if I should make a new PR, so I put the enhancements codes here #1844 alongside some fixes I mentioned last week.
