### ISSUE TITLE
FEAT: MD5 Hash Value

### ISSUE THREAD

**Issue by Olbotron** [beekeeper-studio/beekeeper-studio#1842]
**Is your feature request related to a problem? Please describe.**
I love Beekeeper Studio but as far as I'm aware there doesn't seem to be the option of MD5 hashing a password within the program, when setting up my DB with dummy data I still have to go back to PHPmyAdmin to hash passwords. I know I could do this from my server side scripting but it would be useful when setting up data to have the ability to encode passwords within Beekeeper.

**Describe the solution you'd like**
The option, possibly under the Extra column, of MD5 hashing passwords.

**Describe alternatives you've considered**
A work around is to go back to PHPMyAdmin to encode the passwords but this is not ideal.

**Additional context**
It may already be a feature, but if so I couldn't find it in the documentation online, perhaps a quick video of how to do this.

**Database type, if appropriate**
N/A

**Comment by davidkaufman** [comment]
The database can do this. For instance, on MySQL:

~~~sql
update user
set password=md5("test")
~~~

https://dev.mysql.com/doc/refman/8.0/en/encryption-functions.html#function_md5

**Comment by Olbotron** [comment]
Thanks David, I never thought of that, I always thought GUI over SQL. But thanks and I'm reaching the point where my code on the server needs to hash the passwords so thanks for this.

**Comment by rathboma** [comment]
Hey! Going to close this issue in favor of using the database functions..
