### ISSUE TITLE
Can't copy only cell contents any more

### ISSUE THREAD

**Issue by AlanHorrocks** [beekeeper-studio/beekeeper-studio#1867]
**Details:**
Since the update to v4.1 (and maybe 4.0) I can no longer right-click and copy the highlighted cell contents.  There used to be an option to copy the cell contents - now the option is to copy as json, copy as tsv, etc. but the problem is this now copies the field name as well and also add quotes or escape sequences.

My use-case is that I have a field that contains a large json document - when I copy it I now have to remove the field name and additional nesting that is present and I also have to remove backslashes that have been added to the cell content.

I'm not sure of any use-case where I would want that content nested inside an object including the field name.

Is this an intentional change?  Or will the previous behaviour be restored?  Even an additional option to copy just the field content without the extra stuff would work.

**Version Information [might be relevant to your issue]**
Operating System: Linux
App Version [help -> about]: 4.1.0
Database type and version [eg Posgresql 9.3]: MariaDB 10.6

**Comment by EmanNo1** [comment]
Same for me. When I copy a numeric cell, it is now quoted.

Linux
Snap Version 4.1.4
MS SQL Database

**Comment by rathboma** [comment]
Ah yes. Good point. We need to add a basic copy.

Does the keyboard shortcut work?

**Comment by azmy60** [comment]
I'll look into this tomorrow.
