### ISSUE TITLE
BUG: Broken UI whrn deleting a rows

### ISSUE THREAD

**Issue by EmanNo1** [beekeeper-studio/beekeeper-studio#1877]
**Describe the bug**
After clicking Apply there is this error message "Plaurlize is not defined" and the deleted row is still visiable.

If I re-run teh query, the seleted rows are no longer there. The delete action worked.

**To Reproduce**
1. Select 1 or rows by right-clicking and selecting "delete row"
2. Click "Apply"

**Expected behavior**
UI is refreshed with slected rows removed

**Screenshots / Gifs**
![Selection_024](https://github.com/beekeeper-studio/beekeeper-studio/assets/2874846/9e73f380-5017-4360-bde6-b3430351adee)

**Version Information (please complete the following information):**
 - OS: Ubuntu Mate 23:10
 - App Version: Sanp 4.1.4
 - Database: MS SQL 12

**Comment by azmy60** [comment]
I saw this in SQLite too today. It happened when inserting and deleting.
