### ISSUE TITLE
BUG: "Export data" no longer works - clicking on it does nothing

### ISSUE THREAD

**Issue by ivanovbgr** [beekeeper-studio/beekeeper-studio#1884]
After upgrading my Ubuntu OS from 22.04 to 23.10, "Export data" no longer works - clicking on it does nothing and there is the following error in the console:
```
[130578:0112/231240.398209:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
Couldn't trigger action importExportTables(), Cannot read properties of undefined (reading 'bind')
```
I do not know if it is relevant to the issue, but I also switched from bash to fish as my default shell. 

**Steps to reproduce the behaviour:**
1. Go to 'Tools -> Export data" while being connected to a database

**Expected behaviour**
I expect to see the view allowing me to select tables to be exported. Instead of that nothing happens.

**Version Information (please complete the following information):**
 - OS: Ubuntu 23.10
 - App Version: 4.0.3
 - Database type and version: MySQL 8.0.33

**Additional context**
I haven't used the functionality for a while so I am unsure if the Ubuntu upgrade or switching from bash to fish as default shell broke it.

**Comment by rathboma** [comment]
This is fixed in the latest release!
