### ISSUE TITLE
BUG: Primary keys are not editable, but the UI indicates that they are

### ISSUE THREAD

**Issue by luisotavio-dev** [beekeeper-studio/beekeeper-studio#1886]
**Is your feature request related to a problem? Please describe.**
When I access the data in a table in a simple way and right-click on a record to use the 'Edit in modal' option it works, but for the primary key it does not allow editing.

**Describe the solution you'd like**
If possible, I would like to edit. In development mode I use it to perform tests, and this option would be useful.

**Describe alternatives you've considered**
If it is not possible to enable it, I suggest hiding the pop-up menu button to prevent that nothing action from being taken when clicking on the ‘Edit in modal’ option, as it currently stands.

**Database type, if appropriate**
MariaDB

**Comment by rathboma** [comment]
Hey! Thanks for the bug report.

So just so I'm clear: The UI suggests it is editable, but it is not. Is that correct?

So we need to either:
- Make primary keys editable, OR
- Don't show edit options if they are not

**Comment by luisotavio-dev** [comment]
> Hey! Thanks for the bug report.
> 
> So just so I'm clear: The UI suggests it is editable, but it is not. Is that correct?
> 
> So we need to either:
> - Make primary keys editable, OR
> - Don't show edit options if they are not

Exactly.
