### ISSUE TITLE
Initial menu items

### ISSUE THREAD

**Issue by rathboma** [beekeeper-studio/beekeeper-studio#189]
Note: We're not doing a settings page right now, we don't have enough stuff to configure. Instead just building a legit menu.

Beekeeper Studio (mac only)
- Quit (Mac)

File:
- New Window (eventually, not yet)
- New Query (ctrl + t)
- Quit (- Mac)

Edit:
- Copy
- Paste
- Cut
- Undo
- Redo

View:
- Reset Zoom
- Zoom in
- Zoom Out
- Toggle Full creen
- Theme
  - Light
  - Dark

Connection:
- Refresh Databases
- Refresh Tables
- Disconnect

Help:
- Documentation
- Display Developer Console

**Comment by AqilCont** [comment]
From the looks of this table, it looks like you will implement a standardized menu like this(but probably better looking):
![image](https://user-images.githubusercontent.com/32044067/83932439-8d7a4e00-a770-11ea-9cdb-d0e2908f4667.png)
Will it possible to place the menu in a non-standardized place(like somewhere other than the top left)? I personally find this boring as this makes the app look more plain and takes away from the unique, futuristic aesthetic. Maybe some circular button in the bottom right with a gear icon and a more unique user interface would be better. Just wanted to get my opinion out.

**Comment by rathboma** [comment]
What platform are you on? We have some really nice designs for the Windows app. MacOS has an integrated menu bar, so that's solved, and for Linux I know better than to mess with native window decorations, so we'll be using the native menu bar.

I don't want to post screenshots to spoil it yet, but I will once we have a PR up :-)

**Comment by gnovaro** [comment]
I suggest add
Help -> About
Display current version runing and check for updates

**Comment by seisenreich** [comment]
Also Edit -> Import Database (from .sql file) and Edit->Export Database... would be fantastic as it is done in SequelPro for Mac OS.
