### ISSUE TITLE
FEAT: Just copy text without delimiters

### ISSUE THREAD

**Issue by simonwj** [beekeeper-studio/beekeeper-studio#1891]
Thanks for the great table feature in the 4.1 update.

I have been using it to copy text cell values from a set of query results to a table.  When I do so the text is always wrapped in "" or some other format.

Would it be also possible to just be able to copy the clean value without any delimiters?

I did end up selecting the text out as a table and copying it into the query window as CSV format and then cutting the text from there, but it would have been easier to just copy the text.

I am using MySQL in this case.

**Comment by rathboma** [comment]
We just implemented a default copy mode that uses Tab separators between values, but doesn't quote all the values. Is that what you're looking for?

If not -- can you give me a specific example of what you'd want it to copy in a screenshot or a code block?

**Comment by paketep** [comment]
I'll add to this and say that it should just copy the contents.

I select a cell with an integer value. Copy it. Go to an Excel to get some stats. That used to work fine. Now I get the number in quotes, and Excel complains, so I have to do every number by hand.

Copying "quoted" should be either a right click or a mode that you activate so when you are in "quoted" mode you copy with quotes. Or when selecting several cells.

But one cell? You should always copy the contents, as raw as possible. IMHO.

**Comment by tomonetml** [comment]
Copy as TSV is good it's just missing the most simple action from previous versions "Copy" cell as is.

Great project btw, always getting better and better. hats off

**Comment by recck** [comment]
https://github.com/beekeeper-studio/beekeeper-studio/pull/1888 I believe this resolves the request here, just awaiting a release.

**Comment by rathboma** [comment]
Yep, this is fixed! Patch release out soon

**Comment by paketep** [comment]
Great! Thanks!
