### ISSUE TITLE
BUG: Table with field type 'double precision' not browseable

### ISSUE THREAD

**Issue by stensrud** [beekeeper-studio/beekeeper-studio#1892]
**Describe the bug**
PostgreSQL table not browseable after upgrade to 4.1.10 (community) or 4.1.11 (Ultimate).

Developer console outputs the following error: `Cannot read properties of null (reading 'startsWith')` in `TableTable.vue?cfa8:331`

**To Reproduce**
1. Open connection to PostgreSQL database.
2. Double-click database tables in left pane
3. For tables with fields of some types, no results are showing

**Expected behavior**
A tab should open in main pane with first page of table contents.

**Version Information (please complete the following information):**
 - OS: MacOS Sonoma 14.2.1
 - App Version: Beekeeper Studio Ultimate, 4.1.11
 - PosgreSQL 14, managed by Digital Ocean

**Additional context**
It seems if table has any fields with type `double precision`, it will not be correctly handled by BeeKeeper.

<img width="572" alt="Screenshot 2024-01-15 at 13 43 11" src="https://github.com/beekeeper-studio/beekeeper-studio/assets/1352216/99e2fc15-66cb-47ae-b591-60ff97a10e1f">
<img width="591" alt="Screenshot 2024-01-15 at 14 15 01" src="https://github.com/beekeeper-studio/beekeeper-studio/assets/1352216/7aefaed1-047a-45e3-9d79-390516369cdd">
<img width="636" alt="Screenshot 2024-01-15 at 14 15 24" src="https://github.com/beekeeper-studio/beekeeper-studio/assets/1352216/a53dfb79-e86e-4129-8195-60c68c957941">

**Comment by desenvolvimento02jocc** [comment]
Same here, It's sad to say this but community edition is just unbearable since the last few updates, been more than 2 months since I opened an issue with double precision types where u couldn't identify the column type but now its even worse.
![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/87676055/864ab0db-9142-4d60-94f6-7323465268d6)
