### ISSUE TITLE
BUG: Clone row feature converts JSON content to text

### ISSUE THREAD

**Issue by simonjharris** [beekeeper-studio/beekeeper-studio#1893]
**Describe the bug**
When using the (new?) "clone row" feature, JSON content is being converted to text.

**To Reproduce**
1. Go to the table view for a table with JSON fields
2. Right click on the row number
3. Select "clone row"
4. JSON content cloned as text.

**Expected behavior**
The data to be cloned without any changes.

**Screenshots / Gifs**
<img width="509" alt="Screenshot 2024-01-15 at 14 05 21" src="https://github.com/beekeeper-studio/beekeeper-studio/assets/41231349/dc95b26b-b1ea-4f3d-947c-9aec6fd2c9aa">

**Version Information (please complete the following information):**
 - OS: Mac Sonoma
 - App Version 4.1
 - Database type and version: postgres 14.1

**Comment by rathboma** [comment]
Well that's no good, lol.
