### ISSUE TITLE
BUG: the app doesn't handle the real data type in Postgres failing to display the data 

### ISSUE THREAD

**Issue by ml** [beekeeper-studio/beekeeper-studio#1896]
**Describe the bug**
The app doesn't handle the `real` data type in Postgres. It doesn't show the type on the View Structure screen (less problematic) and it doesn't show any data on the View Data screen for tables with `real` columns. 

**To Reproduce**
1. Create a table with `real` column type.
```
CREATE TABLE real_test (
  id serial,
  something_real real
 );
 insert into real_test values (1, 0.4);
```
3. Select  View Structure for the table - the column type for `something_real` is blank
4. Select View Data for the table - no data is being displayed

**Expected behavior**
The app should display the data and the column type

**Screenshots / Gifs**
<img width="450" alt="image" src="https://github.com/beekeeper-studio/beekeeper-studio/assets/1509/3da45357-8f18-4326-b277-c8021dfc29c8">

<img width="1051" alt="image" src="https://github.com/beekeeper-studio/beekeeper-studio/assets/1509/7a80c828-8994-4c33-83be-de204c4c94cd">

<img width="577" alt="image" src="https://github.com/beekeeper-studio/beekeeper-studio/assets/1509/91e08b57-5594-466d-8d39-29f8f8927cbc">

 - OS: Mac
 - App Version 4.1.10
 - Database type and version Postgresql 16

**Additional context**
Looks like the `column.dataType` is being set to null. This is the trace from the console when I clicked View Data:

```
TableTable.vue?186f:326 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'startsWith')
    at TableTable.vue?186f:326:45
    at Array.forEach (<anonymous>)
    at a.tableColumns (TableTable.vue?186f:255:26)
    at e.get (vue.runtime.esm.js:3415:33)
    at e.evaluate (vue.runtime.esm.js:3516:27)
    at a.tableColumns (vue.runtime.esm.js:5492:25)
    at a.initialize (TableTable.vue?186f:549:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by desenvolvimento02jocc** [comment]
Maybe it's related to [this](https://github.com/beekeeper-studio/beekeeper-studio/pull/1894)?
But seems like it's not released yet.

**Comment by azmy60** [comment]
Yes, we haven't release the patch yet.

**Comment by ml** [comment]
🙌🏿
