### ISSUE TITLE
Ubuntu Repository

### ISSUE THREAD

**Issue by sajanp** [beekeeper-studio/beekeeper-studio#19]
Ubuntu 20.04 was just released, but simply adding the repository and going from there does not work as there is no release info for the 20.04 code name `bionic`.

A further look at the repository shows that it might only work for Ubuntu 19.04, Disco Dingo.

In which case the official documentation has you copy the following, and that won't work.

```echo "deb https://dl.bintray.com/beekeeper-studio/releases bionic main" | sudo tee /etc/apt/sources.list.d/beekeeper-studio.list```

I understand a Snap exists.

**Comment by rathboma** [comment]
Hey @sajanp. the `bionic` line in the documentation does work fine on 20.04. In fact it works on all versions 18.04 and onwards.

I'm not a DEB expert, but the only thing `bionic` does in the sources file is to tell apt what path to look in when scanning the bintray repo. I could have called it `stable`, but wanted to communicate that it was compatible with 18.04+.


For example, Spotify just used the 'stable' namespace, so their source looks like this:
```
deb http://repository.spotify.com stable non-free
```

**Comment by sajanp** [comment]
Certainly not a .deb export either, but here is what I'm getting and I think I can work out why through your spotify example.  On a clean install of 20.04, following the instructions in documentation entirely, here's what an apt update yields.
`E: The repository 'https://dl.bintray.com/beekeeper-studio/releases bionic Release' does not have a Release file.`

If you browse to `https://dl.bintray.com/beekeeper-studio/releases/` in the browser, you see the dists folder.  Inside, only `disco` appears.  Inside there we have the release file.  In order for this to work for other codenames, they need to be added as a directory along with their own release file.

In spotify's case, if you browse to `https://repository-origin.spotify.com/dists/`, you'll see they have the two folders with release files, `stable` and `testing`, which is what they put in the deb listing for apt on the machine.

For Beekeepr, in my local `/etc/apt/sources.list.d/beekeeper-studio.list` file, if I replace the `bionic` with the `disco` that actually exists on the server, everything works.

**Comment by sajanp** [comment]
@rathboma - so in summary, I would either create a folder/release file for all of the codenames supported instead of just `disco` on the server.

Or, if the package works across different ubuntu releases like spotify, update the `disco` folder to say something like `stable` and update the documentation.

**Comment by rathboma** [comment]
Oh, you're totally right, I used the wrong name, doh

**Comment by rathboma** [comment]
I'll update the docs, yes jut changing 'bionic' to 'disco' in the apt package list should work

**Comment by sajanp** [comment]
Yep, I just confirmed.  It does work, updating the doc to say bionic is an option.  However, some people like me will question that...
- Does it mean it's only for Bionix?
- Is it going to have dependacies from older libraries?

When you have time later, just saying 'stable' is probably best.  At least until you need to build separate packages for different versions.

In any case, thank you!

**Comment by rathboma** [comment]
Thanks so much for catching that mistake! You rule.

Yes in future I'll change it to stable or something similar.
