### ISSUE TITLE
Simple sort no longer available. Must use context menu or column header ellipses.

### ISSUE THREAD

**Issue by Mrjwm** [beekeeper-studio/beekeeper-studio#1900]
**Describe the bug**
Before updating to 4.1.10, clicking a column header toggle between ascending/descending sort

**To Reproduce**
1. Open a Table
2. Click a column header. Nothing happens. Clicking a column header no longer toggles between ascending sort or descending sort. You have to right click the column header then select a sort order, which is much less convenient than the original feature.

**Expected behavior**
Clicking the header toggles between ascending sort or descending sort without having to open a context menu or click the vertical ellipses in the header. 

**Version Information:**
- MacOS Ventura 13.5.2
- BeeKeeper Studio 4.1.10
- Postgres 14.2

**Comment by rathboma** [comment]
Hey! We did this to allow whole-column activities like copying and pasting. I understand this is slower. 

What about if we bound ctrl+click to do this, or something like that?
