### ISSUE TITLE
BUG: Sorting Data Load Error:  Unknown column '--row-header' in 'order clause'

### ISSUE THREAD

**Issue by tomonetml** [beekeeper-studio/beekeeper-studio#1905]
**Describe the bug**
trying to sort from outside a column raise an error

**To Reproduce**
1. Go to origin of results data table
2. Right Click on it
4. Click on Sort

**Screenshots / Gifs**
![beekeper1](https://github.com/beekeeper-studio/beekeeper-studio/assets/34745293/53600682-2f23-4afe-b29a-673e1ab4a4b0)
![beekeper2](https://github.com/beekeeper-studio/beekeeper-studio/assets/34745293/41546009-0fba-4013-b6e5-4336c6764daa)

**Version Information (please complete the following information):**
 - OS: Windows
 - App Version 4.1.13

**Comment by azmy60** [comment]
Nice catch! Thanks for reporting this!
