### ISSUE TITLE
how to use the flatpak version of the app under wayland

### ISSUE THREAD

**Issue by Haidara-Ismandar** [beekeeper-studio/beekeeper-studio#1906]
I installed the app from flathub and tried to run it under wayland using the method described on the website https://docs.beekeeperstudio.io/installation/linux/#wayland-support-including-fractional-scaling
 and gave it access to .config folder but this didn't work

**Comment by rathboma** [comment]
Hey! I don't support the flatpak version, so I'm not sure I'm afraid.
