### ISSUE TITLE
BUG: Download query results in Excel and CSV adds a Column upfront

### ISSUE THREAD

**Issue by tomonetml** [beekeeper-studio/beekeeper-studio#1918]
**Describe the bug**
When using the download button from a query result the eported files for xlsx and csv both have a first empty column

**Version Information (please complete the following information):**
 - OS: Windows
 - App Version 4.1.13
 - Database type and version Mariadb

**Additional context**
Will put additional infos or attachments in case the'll be needed

**Comment by azmy60** [comment]
Note: This is a bug from tabulator that's fixed in the recent version (5.6). But before we can upgrade, there are some bugs and spreadsheet regressions that need to be addressed from there as well. PRs to address them are currently up.
