### ISSUE TITLE
VIM: :q quits file even though there are unsaved changes

### ISSUE THREAD

**Issue by austinwilcox** [beekeeper-studio/beekeeper-studio#1927]
When you run :q in command mode, it will quit the current file regardless of whether or not you have saved the changes. This should not be the intended behavior. I would expect the dialogue to show up just as it does when you click the x to prompt you so save changes to the file.

I have a PR nearly ready for this, just finishing out some testing on my local machine.

![Peek 2024-01-30 09-45](https://github.com/beekeeper-studio/beekeeper-studio/assets/43357911/3c6cd432-49e5-4480-bc87-3008bbe37d49)

**Comment by not-night-but** [comment]
Good catch. Can't believe we missed that. Do we have :q! In there as well?

**Comment by austinwilcox** [comment]
Not yet, that one is a little bit trickier with codemirror. I will get the :q PR up and then spend some time investigating the :q! to force quit a file.

**Comment by austinwilcox** [comment]
I switched node version managers to volta, and it's messed up yarn on my machine, so it's taking me a minute to get that all fixed up. The code is ready for PR but I want to test and make sure it works as expected first.

**Comment by austinwilcox** [comment]
@not-night-but [here](https://github.com/beekeeper-studio/beekeeper-studio/pull/1934) is the PR for this fix. Thanks for the patience on this, took me a lot longer to get my yarn working correctly.

**Comment by not-night-but** [comment]
Sweet, I'll take a look!
