### ISSUE TITLE
BUG: Bit field = "false" okay for in-line edit but not for cloned row

### ISSUE THREAD

**Issue by EmanNo1** [beekeeper-studio/beekeeper-studio#1945]
**Describe the bug**
When I edit an individual cell that is a bit type, I can type true or false and apply the change. When I clone a row, I need to change the bit fields from true and false to 1 and 0 respectively before I can save.

**To Reproduce**
1. Select "Clone Row" on a table with one or more bit fields
2. Click Apply
3. Error Message "Invalid column name: false"

**Expected behavior**
Save the new record/row

**Screenshots / Gifs**
![Selection_036](https://github.com/beekeeper-studio/beekeeper-studio/assets/2874846/a6540b9a-1ca1-4aad-9258-adad657633fb)

**Version Information (please complete the following information):**
 - OS: Ubuntu 23.10
 - App Version SNAP 4.1.13 Beta
 - Database type and version MS SQL 12

**Additional context**
This has been an issue for many versions

**Comment by rathboma** [comment]
Hey! That's definitely a bug. Thanks for bringing it up.
