### ISSUE TITLE
BUG: SQLite3 result columns overwrite previous columns with the same name

### ISSUE THREAD

**Issue by bbkane** [beekeeper-studio/beekeeper-studio#1976]
**Describe the bug**

When SELECTing columns that end up with the same name, the result table overwrites the first column.

**To Reproduce**

1. Open a SQLite3 database to the query screen
2. Run any command that results in a table with duplicate column names - smallest example is probably `SELECT 1 as id, 2 as id;`
3. Check the results window to show that only one column with that name appears

**Expected behavior**

I expect to see both columns end up in the result window.

**Screenshots / Gifs**
If applicable, add screenshots or GIFS to help explain your problem.

### Screenshot of overwritten column in SQLite

![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/6081085/404ef3c3-5662-42fc-ae41-d133e3759583)

### This does not occur in the SQLite3 shell

```
$ sqlite3
-- Loading resources from /Users/bbkane/.sqliterc
SQLite version 3.45.1 2024-01-30 16:01:20
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> SELECT 1 as id, 2 as id;
┌────┬────┐
│ id │ id │
├────┼────┤
│ 1  │ 2  │
└────┴────┘
```

**Version Information (please complete the following information):**
 - OS: macOS
 - App Version: 4.1.13
 - Database type and version: SQlite 3.45.1 (from the sqlite shell)

**Additional context**
Anything else you think might be helpful

This does not occur for a Beekeeper MySQL connection, so I have a hunch its the SQLite3 library at fault

![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/6081085/32c02105-5a48-45b6-ae46-f6cde0ac4ec6)

**Comment by azmy60** [comment]
Nice catch! Thanks for reporting this!

**Comment by bbkane** [comment]
Thank you!!!
