### ISSUE TITLE
BUG: column name drop down do not show while writing query in sql

### ISSUE THREAD

**Issue by mahimaholla** [beekeeper-studio/beekeeper-studio#1985]
While writing the select query in sql server the column dropdown do not show column names when a letter is typed.

![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/48175865/6b2f5328-fd02-4ae4-90e6-bcdc2477c830)
it shows before typing a letter but when a letter is typed then 
![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/48175865/f1d9f6f0-7064-46ba-aa1d-2a8115ecb9be)

 - OS: [ Windows]
 - App Version 4.1.13 (the same bug existed in previous versions as well)
 - Microsoft SQL Server 2016 (RTM-GDR) (KB4019088) - 13.0.1742.0 (X64) 
	Jul  5 2017 23:41:17 
	Copyright (c) Microsoft Corporation
	Web Edition (64-bit) on Windows Server 2016 Datacenter 6.3 <X64> (Build 14393: ) (Hypervisor)

**Comment by azmy60** [comment]
That's really bad. Thanks for submitting this!
