### ISSUE TITLE
BUG: Query magic screws up alignment between headers and data column

### ISSUE THREAD

**Issue by came** [beekeeper-studio/beekeeper-studio#1986]
When you create magic queries, the column headers and the data columns are screwed up. I guess this is because of the open window icon (see screenshot) that increases the data column size. When you have multiple columns this is quite annoying as you don't know what data is what column.

**Expected behavior**
Header and data column should stay in order

**Screenshots / Gifs**
![vpclb_supabase_-_Beekeeper_Studio](https://github.com/beekeeper-studio/beekeeper-studio/assets/149962/51e5d93a-5bc0-4946-8db0-728ee28b62cc)

![vpclb_supabase_-_Beekeeper_Studio](https://github.com/beekeeper-studio/beekeeper-studio/assets/149962/d2c3f7f9-07f1-4da3-92a3-cb33fa1d958c)

**Version Information (please complete the following information):**
 - OS: Mac
 - App Version screw up
 - Database type and version Posgresql

**Comment by rathboma** [comment]
Thanks for the feedback! Will get this fixed
