### ISSUE TITLE
Backslash as escape character throws off SQL syntax highlighting

### ISSUE THREAD

**Issue by JamesDBartlett** [beekeeper-studio/beekeeper-studio#199]
It appears that backslash is treated as an escape character for the purposes of the SQL syntax highlighter, so it treats all code following a backslash encased in single-quotes ('\\') as one long string.

![image](https://user-images.githubusercontent.com/37491308/84545110-3fab9b80-acc4-11ea-8d44-d93db301b42a.png)

Notepad++ has an option in its language settings called "Treat backslash as escape character for SQL" which, when disabled, resolves this issue. Perhaps a similar solution could be implemented here?

**Comment by rathboma** [comment]
Oh yeah that's a PITA. We're using the stock CodeMirror syntax highlighting libraries. I'll see if there's a way to fix it.
