### ISSUE TITLE
BUG: CMD + SPACE autocomplete not working

### ISSUE THREAD

**Issue by RobinVW** [beekeeper-studio/beekeeper-studio#2006]
**Describe the bug**
The autocomplete is not working properly when I'm writing a query.

I only get a suggestion after a 'FROM' statement but after 'SELECT' and 'WHERE' statements I don't get auto complete options and CMD + SPACE is not working to trigger it.

**To Reproduce**
1. Open a query tab
2. type a select statement and use cmd + space to trigger the auto complete options

**Expected behavior**
see the possible auto complete options after a statement when possible
for example: 'select * from users where ' 
when I type this I want to see all the possible column names after the 'where' clause

**Version Information (please complete the following information):**
 - OS: Mac Sonoma 14.3.1
 - App Version: Beekeeper Studio version 4.1.13 (community edition)
 - Database type and version: MySQL 5.7

**Comment by rathboma** [comment]
Hey! The shortcut should be ctrl+space, as `cmd+space` pulls up the MacOS spotlight app
