### ISSUE TITLE
Add topic 'mariadb' to GitHub repository

### ISSUE THREAD

**Issue by ottok** [beekeeper-studio/beekeeper-studio#2028]
Hi! Beekeeper docs state clearly that is supports MariaDB. Could you please also add the topic 'mariadb' in the project, so people looking for MariaDB tools on GitHub are more likely to find it?

![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/668724/bd6380f3-c00d-47e0-8ff4-2d5ce8c7011f)

The [popularity of MySQL is slowly declining](https://salsa.debian.org/mariadb-team/mariadb-server/-/wikis/Home#popularity) so it would be good for Dolt to ensure MariaDB users can easily find it.

**Comment by rathboma** [comment]
done!
