### ISSUE TITLE
Cannot copy text/highlight text in Beekeeper latest update

### ISSUE THREAD

**Issue by tonywei92** [beekeeper-studio/beekeeper-studio#203]
Cannot copy any Text (CTRL+C). I'm using Linux PopOS.
Why the text-highlighting disabled?

**Comment by rathboma** [comment]
Hmm, it shouldn't be. I'll investigate.

**Comment by rathboma** [comment]
Which version are you using? Deb/Snap/AppImage?

**Comment by tonywei92** [comment]
Hi, it is deb one

**Comment by p0n1** [comment]
Same here on macOS 10.15.4. I switched back to version 1.4.0.

**Comment by tonywei92** [comment]
@p0n1 I ended up using both BeeKeeper and DBeaver at the same time, DBeaver for the copy operation.

**Comment by rathboma** [comment]
@tonywei92 @p0n1 do you mean copying text from the SQL editor, or from the table view?

**Comment by rathboma** [comment]
@ghstng I think the 'no select' change you made also made it impossible to select text in result tables and copy it

**Comment by rathboma** [comment]
build coming out later today

**Comment by tonywei92** [comment]
@rathboma hi thanks for the update, tried it, now I can highlight text and copy, but still cannot copy table name on the sidebar, any idea?

**Comment by rathboma** [comment]
Can I ask the use case of copying the table name?  I want to support it, but maybe there's something else I can do to support your use case better
