### ISSUE TITLE
BUG: Params popup not showing for params inside of a CTE

### ISSUE THREAD

**Issue by koddr** [beekeeper-studio/beekeeper-studio#2031]
**Describe the bug**

The pop-up window with the input of parameters in the SQL query is not shown after click `Run` button.

**To Reproduce**
1. Go to query tab
2. Add SQL with CTE section
3. Run query

**Expected behavior**

I would like the pop-up window with the input of parameters to work throughout the SQL query, and not just in the general section.

**Screenshots / Gifs**

<img width="1257" alt="Снимок экрана 2024-03-20 в 13 48 27" src="https://github.com/beekeeper-studio/beekeeper-studio/assets/11155743/887d1a1e-87bb-41d9-a6dc-f9c0991ccc3a">

**Version Information (please complete the following information):**
 - OS: [e.g. Windows/Mac/Ubuntu] `22.6.0 Darwin Kernel Version 22.6.0: Tue Nov  7 21:42:27 PST 2023; root:xnu-8796.141.3.702.9~2/RELEASE_ARM64_T8103 arm64`
 - App Version [e.g. help -> About Beekeeper Studio] `v4.1.13`
 - Database type and version [eg Posgresql 9.3] `PostgreSQL 16.2 (via Docker)`

**Additional context**
N/A

**Comment by rathboma** [comment]
Very interesting! Yes I don't know if we've tested Params with CTEs.

**Comment by rathboma** [comment]
Implementation notes:
- Make sure we add a unit test that replicates this problem (be sure the test fails) before fixing it.
- Probably needs fixing on sql-query-identifier
