### ISSUE TITLE
clash between parameter feature and type casting in Redshift

### ISSUE THREAD

**Issue by louisguitton** [beekeeper-studio/beekeeper-studio#204]
Hi, I wanted to give beekeeper studio a try. So I installed it on my Mac, and connected to a Redshift Data Warehouse.
I ran the following query:

```sql
select 
	lifetime_session_count / days_since_birth :: float as avg_daily_sessions,
from dim_users
where id='1235';
```

and when I try to tun it, I get the following pop-up:
![image](https://user-images.githubusercontent.com/7823843/84877511-e60eec80-b088-11ea-8a96-c59cd171928d.png)

I couldn't find any more info in the docs ore on the landing page about the parameter feature of beekeeper, so I'm unable to dig deeper. But I'm assuming there is a clash between that feature and type casting.

**Comment by GammaGames** [comment]
You can get it to work by entering `:float` in the input box, but the  ignore `::`, maybe an issue with the regex on [this line](https://github.com/hillmanov/beekeeper-studio/blob/b65514ffbcdd2c50c6b0d712edde92c8108d2079/src/lib/db/sql_tools.js#L30)

**Comment by rathboma** [comment]
Thanks! @GammaGames you're right. I'm going to incorporate that change. @louisguitton so sorry you hit this issue. Point release coming out presently

**Comment by rathboma** [comment]
build coming out later today
