### ISSUE TITLE
BUG: Import saved queries tweaks (non urgent)

### ISSUE THREAD

**Issue by rathboma** [beekeeper-studio/beekeeper-studio#2042]
1. Add a `File -> Import .sql files` top level menu item
  - This should open a modal that says "This will make a **copy** of your .sql files and add them to your Beekeeper Studio saved queries. Any changes to the original .sql files will not be reflected in Beekeeper Studio", and has a `select files` box.
  - We want to make it clear that Beekeeper Studio is not going to track the .sql files when they are changed.
  - This needs to work in the client-side menu, and the electron-side menu

2. Fix the star icon in the dropdown menu for `import from workspace`
3. When clicking 'import .sql files' in the import dropdown, it should show the same modal as above.
![Screenshot from 2024-03-24 14-11-20](https://github.com/beekeeper-studio/beekeeper-studio/assets/279769/c58cc81e-d4cd-4bfc-a562-c3da1293337f)

**Comment by rathboma** [comment]
Also... is the font different in the import menu dropdown? It looks different somehow

**Comment by azmy60** [comment]
@rathboma no, the `letter-spacing` made it look weird.
