### ISSUE TITLE
BUG: Filters are ignored causing ALL rows to be deleted

### ISSUE THREAD

**Issue by alvesvin** [beekeeper-studio/beekeeper-studio#2049]
**Describe the bug**
When trying to delete one filtered row, all table rows are deleted!

**To Reproduce**
1. Go to any table
2. Filter by two columns using AND filter (perhaps in a way that filters only one row)
3. Click the row, press delete on keyboard and hit apply button at the bottom
4. Remove filters and see that all rows were deleted

**Expected behavior**
I was expecting only the selected row to be deleted not the entire table.

**Screenshots / Gifs**

https://github.com/beekeeper-studio/beekeeper-studio/assets/55713933/9a597260-896c-49f2-8446-47ddb7bf01aa

**Version Information (please complete the following information):**
 - OS: Debian 12
 - App Version 4.1.13
 - Database type and version PostgreSQL 14 (or latest)

**Comment by azmy60** [comment]
Hi @alvesvin ! We'll get this fixed ASAP. Sorry for the trouble.
