### ISSUE TITLE
BUG: On any tab with a tabulator table, switching to another tab, then switching back will reset column widths

### ISSUE THREAD

**Issue by rathboma** [beekeeper-studio/beekeeper-studio#2056]
**Describe the bug**
Switching away from a tab that contains a tabulator table will reset the column widths, although thankfully it will not reset the scroll position.

Notes for implementation: try to abstract this such that we don't need to copy/paste the code between tables.
- If this can be implemented on the Tabulator side, that'd be ideal

[Screencast from 03-27-2024 09:00:05 PM.webm](https://github.com/beekeeper-studio/beekeeper-studio/assets/279769/d4aaf5c9-ce16-4fb6-a0e0-2164d54effa4)

**Comment by Zac-Zajdel** [comment]
@rathboma I thought this was just default functionality and is what made me switch back to DBeaver from Beekeeper.

Super excited to see this resolved 🥇

**Comment by rathboma** [comment]
Please report weird quirks whenever you see them! Likelihood is that we just broke something by mistake :-)
