### ISSUE TITLE
BUG: Check Oracle Auto-complete works properly

### ISSUE THREAD

**Issue by rathboma** [beekeeper-studio/beekeeper-studio#2069]
From Slack:
```
I'm trying out Beekeepr Ultimate, because I want a client that can access both Oracle and Sql Server.  I'm having trouble getting autocomplete to work reliably in Oracle.  It seems like beekeeper will only complete table and column names if I use a certain case, but Oracle identifiers are case insensitive.  Additionally, I can't get it to complete anything unless I explicitly specify the schema. Is this intended behavior or is there a setting I can adjust?
```
Make sure
- [ ] Autocomplete works without the schema
- [ ] Any table case works `TAB` and `tab` should both autocomplete `table`
- [ ] Same with column case

Please add a unit test!

**Comment by azmy60** [comment]
I can't replicate this. It's possible that the autocomplete was working but it took longer to fetch the columns. Quoting the follow-up message:

```
I might have just been impatient - tried with lowercase, got nothing immediately because they hadn't loaded yet, then by the time I tried again with uppercase the results were back?
```

We have tests for the autocomplete but we're missing the uppercase cases. So I'll add that.

**Comment by azmy60** [comment]
@rathboma Might be worth to add loading indicator when fetching columns? Probably at the status bar.

**Comment by rathboma** [comment]
Sure, if you can do it in a way that looks good. Ideally it would open the autocomplete box with a loading indicator, but that might be hard.

**Comment by azmy60** [comment]
closing in favor of #2105
