### ISSUE TITLE
BUG: Can not see content of saved queries

### ISSUE THREAD

**Issue by suuuunto** [beekeeper-studio/beekeeper-studio#2070]
**Describe the bug**
If I click on a saved query it does open in a new tab but does not show any content. If I mouse over a saved query I still see its content.

**Expected behavior**
Query is displayed

**Screenshots / Gifs**
![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/6173396/59c9793a-e6b2-4fe4-972d-87c17c7bb9a9)

**Version Information (please complete the following information):**
 - OS:**Ubuntu**
 - App Version **4.2.0**
 - Database type **MYSQL**

**Additional context**
-

**Comment by rathboma** [comment]
Hey! Did you install from the DEB? If so, please use 4.1.3 for now

**Comment by suuuunto** [comment]
Hi rathboma, 

Thanks for the advise, I got an update today to v4.2.5 and its working now. 

Thanks to who fixed it :)
