### ISSUE TITLE
BUG: Cannot install from homebrew

### ISSUE THREAD

**Issue by bkane-msft** [beekeeper-studio/beekeeper-studio#2071]
**Describe the bug**

I cannot install Beekeeper Studio from Homebrew, due to a non-existing download link. I've opened an issue there ( https://github.com/Homebrew/homebrew-cask/issues/170472 ) too.

**To Reproduce**

```bash
$ brew install beekeeper-studio --force
==> Downloading https://formulae.brew.sh/api/formula.jws.json
################################################################################################################################## 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
################################################################################################################################## 100.0%
==> Downloading https://github.com/beekeeper-studio/beekeeper-studio/releases/download/v4.2.5/Beekeeper-Studio-4.2.5-arm64.dmg
curl: (22) The requested URL returned error: 404

Error: Download failed on Cask 'beekeeper-studio' with message: Download failed: https://github.com/beekeeper-studio/beekeeper-studio/releases/download/v4.2.5/Beekeeper-Studio-4.2.5-arm64.dmg
```

**Expected behavior**

Beekeeper Studio installs

**Screenshots / Gifs**

N/A

**Version Information (please complete the following information):**
 - OS: Mac
 - App Version : N/A
 - Database type and version: N/A

**Additional context**

See linked issue?  Or release a Beekeepr 4.2.5? I'm also curious what your tagging strategy is. These tags don't line up to the releases.
![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/92759008/7943362c-8e2f-4fe4-bc50-307cb68fd9cd)

**Comment by chenrui333** [comment]
I can see the 4.2.5 tag

<img width="435" alt="image" src="https://github.com/beekeeper-studio/beekeeper-studio/assets/1580956/29f87735-75c0-4b9e-b071-c05b383da4ec">

**Comment by not-night-but** [comment]
@chenrui333 Hey! In regards to the 4.2.5 release, we moved it back to pre-release as there was a connection pooling bug that was wreaking havoc. We'll re-release once that's all figured out.

In terms of not installing from homebrew, we don't manage that, but from the issue that tagged this, it seems that it's pointing at the release that doesn't exist anymore. Can you specify a version to use with brew?

**Comment by rathboma** [comment]
This is fixed! (I didn't fix it, they fixed it)
