### ISSUE TITLE
BUG: When opening a tabletable the Tabulator table is not selected by default

### ISSUE THREAD

**Issue by rathboma** [beekeeper-studio/beekeeper-studio#2077]
In PSQL DEV:
1. Double click `film` in the left sidebar
2. The `film` data view opens
3. Press up and down arrow keys

Expected: the selected range will move up and down based on arrow presses
Actual: The left sidebar table list moves up and down

Funnily enough: It should auto-focus, because that's built into tabulator's Range select mode. Maybe that feature itself is a bit broken?

**Comment by azmy60** [comment]
Yes, it's broken in tabulator.
