### ISSUE TITLE
Auto completion when using backticks around tables names

### ISSUE THREAD

**Issue by lode** [beekeeper-studio/beekeeper-studio#208]
I would love the auto completion of column names also when adding backticks around the table name. Maybe it is not always needed but it is something I've got accustomed to. E.g. typing

```
SELECT * FROM `users` WHERE `users`.`
```

would then auto complete the columns.

**Comment by rathboma** [comment]
I believe this works in PSQL with double quotes right now, but we need a more comprehensive solution for sure. Definitely related to your other ticket #209, a more intelligent SQLHint library is required here.

**Comment by lode** [comment]
Thanks for the heads up. And too bad, I'll try to change my habit :)
