### ISSUE TITLE
BUG: JSON Column wrong in copied markdown

### ISSUE THREAD

**Issue by wmontgomery** [beekeeper-studio/beekeeper-studio#2083]
**Describe the bug**
When attempting to copy a result set to Markdown, a column that is a JSON datatype appears as [object Object]

**To Reproduce**
1. Show the results of a table with a JSON column
2. copy to clipboard as markdown
3. See error

**Expected behavior**
JSON columns should show as a JSON string as opposed to [object Object]...

**Screenshots / Gifs**
![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/314613/e898fcec-14c8-4856-b156-14b80c5f2229)
![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/314613/fb2024db-a193-49f1-84c1-b00ff9313f12)

**Version Information (please complete the following information):**
 - OS: [e.g. Windows/Mac/Ubuntu]
 - App Version [e.g. help -> About Beekeeper Studio]
 - Database type and version [eg Posgresql 9.3]

**Additional context**
Anything else you think might be helpful

**Comment by TimBailey-driva** [comment]
Ubuntu 22.04.4 LTS
Beekeeper Ultimate 4.1.13
MySql 8.0.35
