### ISSUE TITLE
BUG: No Entities Found in Default Database on first load

### ISSUE THREAD

**Issue by origamifreak2** [beekeeper-studio/beekeeper-studio#2084]
**Describe the bug**
When opening a connection, beekeeper studio shows no entities in the default database

**To Reproduce**
1. Open Beekeeper Studio
2. Open a database connection with a default database
3. Message on sidebar will say "There are no entities in the ... database"

**Expected behavior**
Database Entities should load

**Screenshots / Gifs**

https://github.com/beekeeper-studio/beekeeper-studio/assets/2578041/93a39a4c-3719-4653-903b-1e7360b6a7fb

**Version Information (please complete the following information):**
 - OS: Mac OS Monterey 12.6.3 (21G419) 
 - App Version: 4.2.8
 - DB: MariaDB 10.5.23

**Additional context**
My guess is this is related to the bug fix in the newest release

**Comment by not-night-but** [comment]
Hey! Good catch, definitely a bug introduced yesterday. I've fixed it now, so it should be in the next release
