### ISSUE TITLE
Auto completion of columns without table prefix

### ISSUE THREAD

**Issue by lode** [beekeeper-studio/beekeeper-studio#209]
I would love if column auto completion would also work when not prefixing with the table name. This saves some typing when doing single table queries. Also, not having this makes me feel I have to tell the software how to be smart :) E.g. when typing `SELECT * FROM users WHERE ` it would auto complete column names from `users`.

I understand this might be tricky, especially when using joins. I don't know if it helps from a UX pov, but I would be fine if it auto completes columns from multiple tables in such case.

**Comment by rathboma** [comment]
💯  I agree with this. Currently I'm using the off-the-shelf SQLHint component of CodeMirror, which isn't super duper smart about this stuff. And it certainly gets more tricky as you have more and more tables in a join.

The real solution is for us to build a full-blown SQL parser library to turn the (partial) query into a structured object. Short-term we could probably build a regex to extract used table names, then use the columns from those tables to provide sql-hint at various places.
