### ISSUE TITLE
BUG: Filter bar disappears when opening a table that is already open with an active filter

### ISSUE THREAD

**Issue by rathboma** [beekeeper-studio/beekeeper-studio#2098]
How to reproduce:

1. Open `film`, filter for a specific ID
2. Switch to another tab
3. Double click `film` in the sidebar
4. Film re-opens but the filter bar is missing

What should it do?
Switch to the tab, but don't clear the filter.

![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/279769/4492af1b-5148-46fb-98f0-396bf393ae3f)

**Comment by azmy60** [comment]
closing in favor of #2125
