### ISSUE TITLE
BUG: Beekeeper doesn't properly show prefix indexes for TEXT / BLOB

### ISSUE THREAD

**Issue by mkellyxp** [beekeeper-studio/beekeeper-studio#2120]
**Is your feature request related to a problem? Please describe.**
On some tables, I have the need to put an index on a TEXT field.  But MySQL can't (for good reason) index the whole TEXT field.  So it wants me to add a prefix index.  Like so:

```
ALTER TABLE example ADD INDEX text_index (text_field(10));
```

Currently, there is no way to specify the (10) part when adding an index in beekeeper.  And even when I do manually add the index, the (10) doesn't display when showing my indexes.

![Screenshot from 2024-04-12 09-40-39](https://github.com/beekeeper-studio/beekeeper-studio/assets/6528226/a8670720-14cb-4fbb-9b4c-25da09c253e0)

**Describe the solution you'd like**
It would be amazing if you could do the following.

1.  When adding an index to a TEXT or BLOB field, prompt the user to provide a prefix value
2.  When viewing your indexes, display the prefix

**Describe alternatives you've considered**
I can still manually add the prefix, so it does work.  But there is still no way to view that index in beekeeper

**Additional context**
![Screenshot from 2024-04-12 09-40-47](https://github.com/beekeeper-studio/beekeeper-studio/assets/6528226/eedd8b13-cd0e-4bfc-a796-d9d7a476ca3e)

**Database type, if appropriate**
I'm not sure if this is only MySQL or not, but this is what i'm using.

**Comment by rathboma** [comment]
Thanks! This is a good heads up. I consider this a 'bug'. I'll get it on the schedule
