### ISSUE TITLE
BUG: Unexpected token g in JSON at position 0

### ISSUE THREAD

**Issue by jancoow** [beekeeper-studio/beekeeper-studio#2130]
**Describe the bug**
When editing or adding a row in a table, sometimes this error shows up. When copying the output to SQL and execute it there it works fine. 

**To Reproduce**
1. Open a table and view the data
2. Editing a column
3. Apply chanes

**Screenshots / Gifs**

![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/9000749/095a4cbe-c2e8-4ab1-a35d-655f03eb36e8)

**Version Information (please complete the following information):**
 - OS:  Arch Linux
 - App Version 4.2.9
 - Database type and version PostgreSQL 12.16

**Comment by rathboma** [comment]
Thanks! We'll take a look. Can you provide some SQL to replicate a table + data that causes this?

**Comment by jancoow** [comment]
This is the SQL when tapping "copy to sql" in the right bottom corner:

```
update
  "public"."accountorganizationbinding"
set
  "role" = 'admin'
where
  "accountid" = '378'
  and "organizationid" = '5';
```
The table is as followed:

```
CREATE TABLE
  public.accountorganizationbinding (
    accountid bigint NOT NULL,
    organizationid bigint NOT NULL,
    role _accountrole NULL
  );
  
  ALTER TABLE
  public.accountorganizationbinding
ADD
  CONSTRAINT accountorganizationbinding_pk PRIMARY KEY (accountid)
```

where _accountrole is an enum
