### ISSUE TITLE
Check connection name on save

### ISSUE THREAD

**Issue by rafaeldev** [beekeeper-studio/beekeeper-studio#215]
![image](https://user-images.githubusercontent.com/4596160/85411124-552f8980-b53e-11ea-8dfe-8562441d57a1.png)

When I click on "Save" without fill "connction name" the message "Connection information saved" appears but does not reflect on my saved connections left tab.

I think which that behaviour is show alert from any validation from form fields.

**Comment by rathboma** [comment]
Yes this is a bug, good call. Should be easy to fix.

**Comment by rafaeldev** [comment]
Great!
And, about this same action, after a create the connection (and its appears on side bar) the form still binding new connection.
Make sense clear all fields after save?
