### ISSUE TITLE
Table and schema names do not autocomplete properly

### ISSUE THREAD

**Issue by rathboma** [beekeeper-studio/beekeeper-studio#216]
Currently the editor auto completes column names, but does not auto complete schmas or tables in certain circumstances.

- Schemas should auto-complete along with table names after typing `from`, `join`, etc.
- Tables should auto-complete after typing `schema.`, same as columns auto-complete after typing `table.`

**Comment by infraweavers** [comment]
Just to chime in on this; it's pretty critical for PostgreSQL uses. PG databases tend to use schemas a lot compared to MySQL/SQLServer etc so it basically makes the autocompletion useless as it stands for most databases.
