### ISSUE TITLE
FEAT: Better upsell box when on the connection interface

### ISSUE THREAD

**Issue by rathboma** [beekeeper-studio/beekeeper-studio#2167]
When selecting a connection that is only in the commercial edition, we have a pathetic attempt to upsell the user.

Make a nice new upsell box that has similar vibes to our upgrade modal.

TODO:
- [x] Design by @haleytrieu99 
- [x] Design approval by @rathboma 
- [ ] Implementation by @azmy60 

Haley if you wanna post mockups and figma links in here, once approved it can be implemented!

**Comment by haleytrieu99** [comment]
![upsellbox](https://github.com/beekeeper-studio/beekeeper-studio/assets/149030318/b61f0d5a-bb40-445d-b7c0-4fa3197b0e80)

[Figma file](https://www.figma.com/file/ozxewm8i0jcxl1M6DYtAjJ/Beekeeper-Studio?type=design&node-id=4-8&mode=design&t=5LHph35MZyfvwIwg-0)

**Comment by azmy60** [comment]
I know that this issue focuses on the upsell box. But the connection type looks much better that I can imagine the rest of the connection interface would improve a lot. :D

**Comment by rathboma** [comment]
Looks good! Yeah we can update the connection type styles if you like.
