### ISSUE TITLE
BUG: Can't select column type after updating to v4.3.0 on mac arm64

### ISSUE THREAD

**Issue by samnimoh** [beekeeper-studio/beekeeper-studio#2169]
There is an issue with trying to select a column type when creating a table or editing the structure of a table. The field is inactive

1. open a table to edit the structure 
2. attempt to add a column 
3. Attempt to choose a type for the column

**Expected behavior**
I expected an active field which would allow me to select a field type by either manually typing it in or typing and selecting the type

 - OS: Mac arm64
 - App Version: 4.3.0
 - Database type and version: Postgresql 14

**Comment by azmy60** [comment]
Thank you for bringing this up! We're working on it.

**Comment by patrickchoi** [comment]
Have this problem too. Had to revert to MySQLWorkbench. Not happy.
