### ISSUE TITLE
BUG: Adding an enum to a table disables editing

### ISSUE THREAD

**Issue by rathboma** [beekeeper-studio/beekeeper-studio#2180]
Video: https://www.loom.com/share/458422e9c98a4340915a0a2620cd0c26?sid=5be77852-400c-4457-b882-e9fd24a26f62

This is either:
1. Changing the id column when it shouldn't be
2. Confusing something with the table table

**Comment by azmy60** [comment]
@rathboma Can I get the query to recreate the table? Also, it seems like there's no primary key in the table to begin with.

![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/38707148/d845b913-7dde-455a-a85e-18f4adb259be)

**Comment by azmy60** [comment]
Oh I can replicate this. I used the table builder and it's strange that the id isn't detected as a primary key somehow.
