### ISSUE TITLE
BUG: Several more issues with focus (largely thanks to Tabulator / Codemirror)

### ISSUE THREAD

**Issue by rathboma** [beekeeper-studio/beekeeper-studio#2187]
Goal: Users should be able to navigate around the whole app with the keyboard, even if they can't do 'everything', they shouldn't have to click to perform primary actions.

##  If I click CMD-W to close a tab, I get the following prompt, and there's no way to tab through the options in the modal, nor does Enter work. This is because focus stays in the editor in the background.
![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/279769/7eabfdcb-905e-4c7e-a334-6f0c8cc8f0fb)
FIX: 
It should have one of the options selected by default. Probably 'cancel', it should let you tab between them. This used to be the case, this is a regression.

## 2. When you switch to a tab opened via "View Data" with the keyboard, focus goes elsewhere (even though the first cell looks selected!), so you can't use the keyboard to navigate the rows.

![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/279769/53da9403-c98a-4698-bba8-d84081321509)
- This is another weird tabulator focus bug

## 3. I can't figure out a way to switch which pane is selected using keyboard shortcuts.
![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/279769/f5646df2-2b9d-47cb-999f-0d1aa81ed509)
- This should be ctrl+tab maybe?

**Comment by azmy60** [comment]
I've been wanting to call this out because I use keyboard almost every time. This will be so satisfying! 🙌
