### ISSUE TITLE
BUG: Import should stream data rather than reading the whole file into memory

### ISSUE THREAD

**Issue by rathboma** [beekeeper-studio/beekeeper-studio#2189]
Large files break the import process for two reasons:
1. The app runs out of memory
2. We send 'too large' query text to the database driver, which causes an error

What we should do is:
1. start a transactions
2. Read the file record by record
3. batch into ~x inserts / updates at once
4. send those to the db in batches
5. Close the file and transaction

**Comment by wmontgomery** [comment]
This is added with the v5 beta release
