### ISSUE TITLE
Queries using regexp character classes prompt for parameter values

### ISSUE THREAD

**Issue by jsenich** [beekeeper-studio/beekeeper-studio#219]
When executing a MySQL query with a regular expression character class, the character class is being picked up as a parameter and a prompt to provide parameter values is displayed.

```
SELECT 'a' REGEXP '^[[:alpha:]]';
```

![Screen Shot 2020-06-26 at 8 22 30 AM](https://user-images.githubusercontent.com/1821282/85856565-3c191980-b786-11ea-8b62-5fd3f45332ff.png)

**Comment by GammaGames** [comment]
Oh boy this regex is getting complicated, I bet it can be simplified: `(?:[^a-zA-Z0-9_:]|^)(?::|\$)(\w+|\$\d+)(?:[^:]*?$)`

[regex101](https://regex101.com/r/lAMQlh/2)

**Comment by rathboma** [comment]
Yes that's a problem.

If you have time, do you mind adding the test case to `sql_tools_spec.js`? Even if you can't fix it.

**Comment by GammaGames** [comment]
I'll make a pr after work
