### ISSUE TITLE
BUG: When closing empty query tab its asking to save/close

### ISSUE THREAD

**Issue by mahimaholla** [beekeeper-studio/beekeeper-studio#2194]
when i try to close empty query tab its asking to save or close.
I was a good feature before where we can close empty queires directly.
![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/48175865/0c1c09e8-0cde-4990-8d33-a7451b516398)
![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/48175865/97abe2db-d568-4f90-bc39-95e2894831ce)

**Comment by rathboma** [comment]
Oh yeah, that's silly. Thanks for finding.

**Comment by wmontgomery** [comment]
This looks like it's been fixed in Main.
![2194-1](https://github.com/user-attachments/assets/7abf571d-4a0a-4b2c-9f65-1e41fd5c511a)
