### ISSUE TITLE
usability: can't tell which connection I'm in

### ISSUE THREAD

**Issue by mariusa** [beekeeper-studio/beekeeper-studio#221]
After connecting with a saved db connection, there's no visual way to tell which connection I'm in (eg a few hours later)

![Screenshot from 2020-06-29 09-28-19](https://user-images.githubusercontent.com/1283842/85980430-0d4fad00-b9eb-11ea-8948-a6a0632a6e55.png)

Would you please consider making the "Connection" string be the saved connection name & color instead?

**Comment by rathboma** [comment]
Yep 100%. We have a change in a PR that moves some of this stuff to a status bar at the bottom -- complete with connection colors. :-)
