### ISSUE TITLE
BUG: this.identifyCommands is not a function

### ISSUE THREAD

**Issue by yngfoxx** [beekeeper-studio/beekeeper-studio#2222]
**Describe the bug**
Tried using the Cassandra support to work with ScyllaDB, I am able to view keyspaces and tables but unable to execute any CQL command

**To Reproduce**
1. Create a ScyllaDB container using docker for testing purpose
2. Connect Beekeeper Studio Ultimate to the ScyllaDB container using the cassandra option
3. Run any CQL command
4. The error will be shown saying: "There was a problem: this.identifyCommands is not a function"

**Expected behavior**
I expect it to execute the CQL command and display the output

**Screenshots / Gifs**
![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/47150226/fab9e3a0-92f7-4130-baf1-907fd1bcf861)

**Version Information (please complete the following information):**
 - OS: Windows 11
 - App Version: Beekeeper Studio 4.3.4 Beekeeper Studio Team
 - Database type and version: (Cassandra) ScyllaDB 5.4 (scylladb/scylla:latest) 

**Additional context**
ScyllaDB is the main reason for my paid membership

**Comment by albertojnk** [comment]
I've just downloaded Beekeeper Studio Team v4.3.4 and got the same error from a simple select

OS: macOS Monterey 12.7.5
Database is also Cassandra (no Scylla)
