### ISSUE TITLE
FEAT: using keyboard for closing the query tab

### ISSUE THREAD

**Issue by mahimaholla** [beekeeper-studio/beekeeper-studio#2229]
![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/48175865/b3783e89-7059-4cce-ae16-8c59738965bf)
 
 here when we click tab and enter it should close it..  Now we have to manually do it with mouse. make it accessible using keyboard alone as well.. even some shortcut to close the tab.

**Comment by azmy60** [comment]
Hey! Thanks for the report. Yes, normally we should be able to use keyboard to navigate. This was fixed by this PR https://github.com/beekeeper-studio/beekeeper-studio/pull/2215
