### ISSUE TITLE
BUG: The application works in Read-Only mode in the Community Edition

### ISSUE THREAD

**Issue by koheiyamayama** [beekeeper-studio/beekeeper-studio#2234]
**Describe the bug**
I use community edtion. So I think I dont use Read-Only mode.
And I cant switch modes between Read-Only and normal mode.

**To Reproduce**
1. When I try to insert data, it results in an error

**Expected behavior**
I cant use Read-Only model on Community Edition.

**Screenshots / Gifs**
If applicable, add screenshots or GIFS to help explain your problem.

**Version Information (please complete the following information):**
 - OS: macOS Monterey
 - App Version 4.3.4
 - Database type and version PostgreSQL 16.3 and CockroachDB 24.1.0

**Additional context**
Anything else you think might be helpful

**Comment by not-night-but** [comment]
Hey! Thanks for your report.

I'm honestly not sure how your connection got into this state, as there is no read-only mode control in community... As a temporary fix for you, you should be able to go into the app db (In the window menu -> Help -> Add Beekeeper's Database. And then connect to Beekeeper's Database), and check the value of the readOnlyMode column in saved_connection and used_connection. If any are true, flip those. That should at least get you out of readOnlyMode

**Comment by koheiyamayama** [comment]
@not-night-but 

Thanks for your reply.

I understand how to change modes. I don't know why this mode changes, but I can solve my troubles.

Thanks for your advice.

**Comment by not-night-but** [comment]
@koheiyamayama I'm glad you could flip that back at least!! I'm gonna add a safeguard to make sure it just can't be activated in community because I'm sure that's annoying
