### ISSUE TITLE
BUG: Beekeeper Studio won't start.

### ISSUE THREAD

**Issue by telemix** [beekeeper-studio/beekeeper-studio#2239]
**Describe the bug**
When I run Beekeeper studio (4.3.4 AppImage) I get this on the CLI :

[10626:0607/124702.463975:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_beekeeSmFvja/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)

**To Reproduce**
I'm on a fresh install of Ubuntu 24.04

**Expected behavior**
That it will run.

**Screenshots / Gifs**

**Version Information (please complete the following information):**

OS:		Ubuntu 24.04 LTS noble
OS INSTALLED:	Wed Jun 5 22:01:36 2024
KERNEL:		6.8.0-35-generic
BIOS VERSION:	1.07.01
EC VERSION:	7.1
---------------------------------
PROCESSOR:	11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
CPU CORES:	4
GPU:		TigerLake-LP GT2 [Iris Xe Graphics] [8086:9A49] 
TU117M [GeForce GTX 1650 Mobile / Max-Q] [10DE:1F99] 
SSD Model:	
SSD TYPE:	SSD (non-NVMe)
SSD SIZE:	0GB
RAM:		62GB 2667 MT/s  DDR4 

I can start it successfully if I append --no-sandbox.

**Comment by rathboma** [comment]
Hey! Looks like you ran it as root using `sudo`? Either that or possibly ran another Electron app using sudo at some point?

**Comment by rathboma** [comment]
Oh, it's asking for chrome-sandbox to be owned by root. That's weird, I've never seen that before.

Looks like Obsidian users have experienced the same issue:
https://forum.obsidian.md/t/appimage-chrome-sandbox-issue/19014/5

What perms does your `/tmp` folder have?

Seems like setting `kernel.unprivileged_userns_clone` to `1` will fix it, but isn't the best idea.

Let me investigate.

**Comment by EmanNo1** [comment]
Not sure if this is related. I just upgraded my Ubuntu from 23.10 to 24.04 and Beekeeper will no longer start. I tried reinstalling the .deb and the appImage and get the same error in the kern.log

audit: type=1400 audit(1717781385.669:379): apparmor="AUDIT" operation="userns_create" class="namespace" info="Userns create - transitioning profile" profile="unconfined" pid=20075 comm="beekeeper-studi" requested="userns_create" target="unprivileged_userns"

audit: type=1400 audit(1717781385.671:380): apparmor="DENIED" operation="capable" class="cap" profile="unprivileged_userns" pid=20092 comm="beekeeper-studi" capability=21  capname="sys_admin"

traps: beekeeper-studi[20075] trap int3 ip:572d51c11eeb sp:7ffd309a4250 error:0 in beekeeper-studio-bin[572d4eba9000+6aef000]

A quick search found this about Ubuntu 23.10+
https://ubuntu.com/blog/ubuntu-23-10-restricted-unprivileged-user-namespaces

**Comment by EmanNo1** [comment]
I was able to get the .deb version to launch by setting the userns_clone to 0. Not sure what the system security impact is, but I can get work done. Hopefully there will be a new kernel to fix this soon.

`sudo sysctl kernel.unprivileged_userns_clone=0`

**Comment by rathboma** [comment]
Hi Erik, you can turn that back on and add the command line arg `--no-sandbox`, that should work also

**Comment by rathboma** [comment]
@EmanNo1 Can you cat this file for me:

```
cat /proc/sys/kernel/unprivileged_userns_clone
```
Maybe that file moved?

**Comment by EmanNo1** [comment]
cat /proc/sys/kernel/unprivileged_userns_clone returns 0

**Comment by EmanNo1** [comment]
The --no-sandbox option also works with kernel.unprivileged_userns_clone set to 1

**Comment by rathboma** [comment]
I know what it is.
I think for Ubuntu 24.04+ that setting doesn't exist, becuase it uses app armor instead. So my default execution needs to be changed.

**Comment by telemix** [comment]
Hi - thanks for looking at this. I saw it's marked as fixed, but I just re-downloaded the AppImage and the problem seems to still bee there (ie I need to use --no-sandbox). I'm downloading the trial version, not the community version.

**Comment by rathboma** [comment]
Hey! It's not released yet, but putting out a new release early this week
