### ISSUE TITLE
BUG: Studio not opening after install

### ISSUE THREAD

**Issue by Pola5h** [beekeeper-studio/beekeeper-studio#2245]
Installed [beekeeper-studio_4.3.4_amd64.deb](https://github.com/beekeeper-studio/beekeeper-studio/releases/download/v4.3.4/beekeeper-studio_4.3.4_amd64.deb) on my **OS: Ubuntu 24.04 LTS x86_64b with x11**.

"After installing, I tried to open the studio, but it wouldn't open. I also restarted the machine, but that didn't fix the issue.

To reproduce the error:

1. Install [beekeeper-studio_4.3.4_amd64.deb](https://github.com/beekeeper-studio/beekeeper-studio/releases/download/v4.3.4/beekeeper-studio_4.3.4_amd64.deb) on OS: Ubuntu 24.04 LTS x86_64.
2. Click on the studio icon."

**Comment by psilva-sv** [comment]
What did you do to solve it?

**Comment by Pola5h** [comment]
> What did you do to solve it?

installed new release.
