### ISSUE TITLE
BUG: Application does not open - @libsql/darwin-x64 not found

### ISSUE THREAD

**Issue by wladimirgrf** [beekeeper-studio/beekeeper-studio#2254]
After the last update to the version: __4.4.0__

![Screenshot 2024-06-13 at 13 35 12](https://github.com/beekeeper-studio/beekeeper-studio/assets/20077278/e7b65ffe-f50d-4580-a5b3-9f9b6c68c9b1)

The application no longer opens. It keeps looping on the boot screen.

![Screenshot 2024-06-13 at 13 33 23](https://github.com/beekeeper-studio/beekeeper-studio/assets/20077278/39427cd0-a4eb-4d64-9b72-0d6ef494f6ff)

__OS__
macOS Sonoma (14.5) 

I tried downloading the dmg again and installing it, but no luck, the issue persists.

**Comment by rathboma** [comment]
Hmm, that's not good. Let me take a look to see if I can replicate

**Comment by rathboma** [comment]
@wladimirgrf if you click help -> show developer tools, are there any errors? (red)

**Comment by wladimirgrf** [comment]
> @wladimirgrf if you click help -> show developer tools, are there any errors? (red)

Only this one:
![Screenshot 2024-06-13 at 13 52 58](https://github.com/beekeeper-studio/beekeeper-studio/assets/20077278/fd144c2c-25c9-4911-923b-5f223f196f37)

**Comment by rathboma** [comment]
That's definitely the cause of it. I'm not sure why it's doing that. Let me try and figure it out

**Comment by yxxcrtd** [comment]
How to fix it ?

**Comment by yxxcrtd** [comment]
Hurry

**Comment by hamisharmati** [comment]
Can you make the previous version available again? I was trying to activate the license on it and got a 404 error.

The client told me there was an update, so I updated and now have this issue..

**Comment by HiromuTsuchiya** [comment]
I have upgraded to 4.4.1 and am experiencing the same problem.

**Comment by Atom54** [comment]
Same issue here. Completely stuck. No way to download an earlier version ?

**Comment by rathboma** [comment]
@Atom54 This is fixed! Download the latest release
