### ISSUE TITLE
Upgrade to 4.4.0 then does not open !

### ISSUE THREAD

**Issue by yxxcrtd** [beekeeper-studio/beekeeper-studio#2256]
Upgrade to 4.4.0 then does not open ! 
help me!

**Comment by cristobalgvera** [comment]
Relates to #2254

**Comment by azmy60** [comment]
Hey @yxxcrtd ! Are you running beekeeper on MacOS? Any errors in the console (Click help -> show developer tools)? If you're on  MacOS, it could be related to #2254 and we're trying solve this right now.

**Comment by yxxcrtd** [comment]
@azmy60 I am running it on MacOS Monterey 12.7.5 , but how to solve it in #2254

**Comment by rathboma** [comment]
@yxxcrtd Download 4.6 and this is fixed!
