### ISSUE TITLE
BUG: Program freezes when importing large SQL files

### ISSUE THREAD

**Issue by negativems** [beekeeper-studio/beekeeper-studio#2259]
**Describe the bug**
When I want to import an SQL file that has +20K lines of inserts it makes the program stucks for ~30 seconds.

The reason of this is because the import button instead of executing the file it opens it on the editor, making it hangs for a lot of time until all the lines cached on memory.

**Possibles solutions:**
- An option to execute directly the sql file instead of open it on the editor.
- Only render X lines of the imported file until you scroll to the bottom.
- Show "Show more" button like VSCode does to resolve the same problem:
![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/20746840/b262feaa-5895-44fc-b312-164bfb64398d)

**To Reproduce**
Import a .sql file that has a lot of lines.

**Version Information:**
Tried on MacOS

**Additional context**
Other programs like SequelAce stuck but for ~2 seconds and it does not open it on the editor.

**Comment by not-night-but** [comment]
@wmontgomery does your new import stuff address this?

**Comment by wmontgomery** [comment]
Yes it does

**Comment by rathboma** [comment]
working on it!

**Comment by negativems** [comment]
> working on it!

Great!
