### ISSUE TITLE
BUG: Press kit color swatches inverted

### ISSUE THREAD

**Issue by uncenter** [beekeeper-studio/beekeeper-studio#2268]
**Describe the bug**

The color swatches on https://www.beekeeperstudio.io/press/  are inverted.

![CleanShot 2024-06-19 at 15 15 38@2x](https://github.com/beekeeper-studio/beekeeper-studio/assets/47499684/53ca7b4e-2f1a-44df-af59-bd2561f45406)

The color `#4ad0ff` is listed on the swatch with the yellow background while the color `#fad83B` is listed on the swatch with the blue background.

**To Reproduce**

N/A

**Expected behavior**

The hex code `#fad83B` should be listed on the yellow swatch and `#4ad0ff` on the blue swatch.

**Screenshots / Gifs**

See above.

**Version Information (please complete the following information):**
N/A

**Additional context**
Anything else you think might be helpful

**Comment by uncenter** [comment]
Also on a related matter its really hard to tell if you have selected the hex code for the blue swatch - since the `::selection` highlight color is also that exact shade of blue. Would be nice to maybe invert the selection color to yellow like this:
![CleanShot 2024-06-20 at 13 26 33@2x](https://github.com/beekeeper-studio/beekeeper-studio/assets/47499684/e4056693-b4b4-47ca-b5e6-11dba775f6cd)

**Comment by rathboma** [comment]
Doh. Fixed the color, and fixed the highlight too :-)

**Comment by uncenter** [comment]
Awesome! I'm not seeing the highlighted inverted on the blue swatch though... if I double click on the hex code I still can't tell if I have it selected.
