### ISSUE TITLE
BUG: Zero in editor interpreted as null

### ISSUE THREAD

**Issue by saviusz** [beekeeper-studio/beekeeper-studio#2279]
**Describe the bug**

`songId` and `artistId` cannot be null, but can be 0, as they are integers.
![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/42438445/4a36a6cb-5cee-4fc7-aa01-25f9ae24f737)

Beekeeper omits zeros while translating this changes to, resulting in violating `NOT NULL` constraint:
```sql
insert into
  "public"."artistOnSong" ("artistId", "role")
values
  (1, 'author');

insert into
  "public"."artistOnSong" ("role", "songId")
values
  ('author', 1);

insert into
  "public"."artistOnSong" ("artistId", "role", "songId")
values
  (2, 'performer', 1);

insert into
  "public"."artistOnSong" ("artistId", "role", "songId")
values
  (1, 'author', 1);

insert into
  "public"."artistOnSong" ("artistId", "role", "songId")
values
  (2, 'author', 2);
```

I believe, zeros shouldn't be treated as null, as they are values (databases treat them as such)

**To Reproduce**
1. Make changes to table (e.g. add rows), using zero as a value
2. Copy to sql (or try to apply on NOT NULL constrained table)

**Expected behavior**
Beekeeper should not treat zeros as nulls, as DBs treat them as value

**Version Information (please complete the following information):**
 - OS: Windows 10
 - App Version: 4.6.0
 - Database type and version: Postgres 16.3

**Comment by rathboma** [comment]
Hmm, this is definitely a regression, and a bug. Thanks for finding!

@azmy60 can you fix this one too? Once done we can do a release.

**Comment by rathboma** [comment]
This is fixed!
