### ISSUE TITLE
FEAT: UI improvements for Azure SSO authentication workflow

### ISSUE THREAD

**Issue by rathboma** [beekeeper-studio/beekeeper-studio#2287]
When connecting with SSO the following thing happens:
1. Click connect
2. Beekeeper opens a browser tab for the user to complete SSO
3. During this time, beekeeper polls for 2 minutes waiting for the SSO via the webapp, but doesn't display anything in the app to indicate this.
4. After 2 minutes is up, it shows an error.
5. Once authenticated for a connection, we have credentials, so clicking 'connect' will auto-connect you with that token

Problems:
1. There's no way to know that Beekeeper Studio is waiting for the web SSO session to complete
2. There's no way to clear a saved authentication token / change who you are signed in as (like what if you signed in as the wrong user?)
3. There's no way to cancel the polling and connect to a different database

UI items TODO
1. When you click connect, Beekeeper Studio should open a modal that shows a spinner and says something like 'Waiting for authentication...' It should Poll for AS LONG AS THE MODAL IS OPEN. There should be a **cancel** button that stops polling. This prevents folks from connecting to another database at the same time.
2. When someone has authorized themselves for a specific database, we should show that in the AzureSSO connection area, and allow them to 'sign out' and clear the token cache. We don't know the email, but you can say something like `Authenticated on <date> [sign out]`

Ping me and I can share some user credentials.

**Comment by not-night-but** [comment]
Some notes from me:
- You can get the username/name from the account info on the token response in `accessToken()` in `azure.ts` (eg. `tokenResponse.account.username`). So if you wanted to store that on the tokenCache/connection you could do so there.
- There is already a cancel function built into the authentication service, so you can just remove the timeout check in `checkStatus()` in `azure.ts`
