### ISSUE TITLE
BUG: [libSQL] queries on Turso DB return "e.reduce is not a function"

### ISSUE THREAD

**Issue by louis77** [beekeeper-studio/beekeeper-studio#2296]
When I'm connected to a database on Turso via libSQL and emit any SELECT query, I get the following error:
`e.reduce is not a function`.

1. Connect to a database via libSQL on Turso
2. Submit a query, i.e. `SELECT CURRENT_TIMESTAMP` or `SELECT * FROM [table] LIMIT 1`

**Screenshots / Gifs**
![Bildschirmfoto 2024-07-01 um 21 36 34](https://github.com/beekeeper-studio/beekeeper-studio/assets/1240462/3261870b-e6b0-4ba1-bace-74fdc28a5367)

However, working in the table view directly works.

**Version Information (please complete the following information):**
 - OS: macOS
 - App Version: 4.6.4
 - Database type and version: Turso

**Comment by azmy60** [comment]
Thank you for reporting this!

**Comment by mwiles** [comment]
Just to add this also impacts the Linux client as well.

**Comment by azmy60** [comment]
Resolved by #2337

**Comment by fightbulc** [comment]
@azmy60 should this be available as release? on linux I am still running in that issue. Running version 4.6.4

**Comment by azmy60** [comment]
It'll be in the next release for sure! We'll keep you updated.
