### ISSUE TITLE
Add Maria DB as a connection option

### ISSUE THREAD

**Issue by happinesskirin** [beekeeper-studio/beekeeper-studio#23]
Is it also available in MariaDB?

**Comment by rathboma** [comment]
Hey! I've not tested it, but the MySQL connector should work just fine with MariaDB.

I'll keep this issue around so we can add a mariaDB entry to the drop down

**Comment by rathboma** [comment]
Task: Map MariaDB to the MySQL connector, or optionally use node-mariadb

**Comment by gnovaro** [comment]
I use in ubuntu with "mysql" option and works well.

**Comment by rathboma** [comment]
I'm adding an explicit setting as part of #33

**Comment by gnovaro** [comment]
This problem is already solved.
