### ISSUE TITLE
Package available for Flatpak or .RPM

### ISSUE THREAD

**Issue by fcchn4** [beekeeper-studio/beekeeper-studio#230]
Goodnight
I am currently a beekeeper-studio user, it is an excellent administration tool for databases.
I am a user of the Fedora Operating System where I use .RPM packages and I also use Flatpak where beekeeper-studio is not available in either option.
The project will have a plan to package the beekeeper-studio at .RPM or for Flatpak where it will facilitate the use of beekeeper users.

Regards.
P.S. Sorry my bad english.

**Comment by rathboma** [comment]
👋 Your English is great!

We have an outstanding PR for an RPM package, so hopefully that will be coming soon. There's no off-the-shelf `flatpak`  builder for electron-builder, so that seems less likely in the short-term.

See: #218

**Comment by williamjmorenor** [comment]
There is a update in how build electron app in a flatpak.

https://docs.flatpak.org/en/latest/electron.html

**Comment by rajatpundir** [comment]
Is there any update on this?

**Comment by rathboma** [comment]
I'm going to close this. I'm staying with AppImage as the default format for now as it's the easiest to maintain and update.
