### ISSUE TITLE
export/import settings in YAML or JSON

### ISSUE THREAD

**Issue by oDevArc** [beekeeper-studio/beekeeper-studio#231]
It could be very cool to export/import settings in YAML or JSON for keeping all connections parameters (except passwords) 

maybe there is already a file keeping these informations in /home/$USER/snap/beekeeper-studio/current/.config/beekeeper-studio ?

thank you

**Comment by rathboma** [comment]
Hey!

So there's an `app.db` file and a `.key` file in that directory -- this stores all of your app configuration. So you can back this up / ship it around if you need to. You need both of them.

We'll be adding some formal support for this type of thing in the future, so stay tuned!

I'll close the issue for now. :-)

**Comment by jonathborg** [comment]
Actually, how can I do it?
Copying the ```app.db``` and ```.key``` files seems not working anymore.

**Comment by rathboma** [comment]
Hey! Those two files should work. Can I ask if you're moving across machines, or between versions?

eg: If you are moving to/from the `snapcraft` version, the directories are different.

**Comment by oom-** [comment]
Is there anyway to do an "export" / "import" from the UI ?  (Is it planned to be implemented ?)

**Comment by jonathborg** [comment]
Hey @rathboma, sorry for the long delay. I'm moving to another machine.
