### ISSUE TITLE
BUG: SSH external agent not working properly under Flatpak

### ISSUE THREAD

**Issue by LanVukusic** [beekeeper-studio/beekeeper-studio#2326]
**Describe the bug**
When downloading the studio from Flatpak, ssh external agent does not work, due to misconfigured Flatpak config.

**To Reproduce**
1. Download from Flatpak
2. Add a database with require SSH tunel
3. Select SSH Authentication > `SSH Agent`

**Expected behavior**
Connection should be established

**Screenshots / Gifs**

![image](https://github.com/user-attachments/assets/de209171-2852-44e1-bc95-4025d88cd356)

**Version Information:**
 - OS: Fedora workstation  40
 - App Version 4.6.2

**Comment by LanVukusic** [comment]
To fix it, enable the `socket=ssh-auth` under **Socket > Secure Shell Agent** with a tool like **Flatseal**.  
![image](https://github.com/user-attachments/assets/d172b687-f947-4125-a910-c4af5ce35353)  

This will repair the SSH functionality

**Comment by azmy60** [comment]
@rathboma is this something we can fix from the app or explain the solution in the docs?

**Comment by alexojegu** [comment]
This PR should fix it: https://github.com/flathub/io.beekeeperstudio.Studio/pull/37

**Comment by rathboma** [comment]
Awesome, thanks so much!
