### ISSUE TITLE
Scrollbar is hard to see in dark theme

### ISSUE THREAD

**Issue by mariusa** [beekeeper-studio/beekeeper-studio#233]
![Screenshot from 2020-07-06 18-28-23](https://user-images.githubusercontent.com/1283842/86610882-98660f80-bfb6-11ea-9cf8-9ff158975e0e.png)

Would you please consider making the scrollbars easier to see in dark theme?
eg 
* the background of entire area where one can move the scroller could be light gray instead of black
* the scroller could be closer to white instead of current dark grey

Thanks!

**Comment by rathboma** [comment]
@ghstng wanna weigh in here?

**Comment by ghstng** [comment]
Great suggestion; however, I like it how it is. If more people share this frustration, will consider changing.
