### ISSUE TITLE
BUG: Connection with firebird

### ISSUE THREAD

**Issue by Ddiidev** [beekeeper-studio/beekeeper-studio#2341]
**Describe the bug**
I can't connect to the Firebird 5 database (that's what I'm using, I don't know if it works with 2.5, but it doesn't seem to be a version problem)

**To Reproduce**
1. Go to 'new connection'
2. Select 'Firebird'
3. Host 'localhost'
4. Port '3050' (default)
5. User 'SYSDBA'
6. Pass 'masterkey'
7. Dafault Database 'Path from database'
8. Click on 'Test' or 'Connect'

**Expected behavior**
That at least made the connection.

**Screenshots / Gifs**
How it was installed.
![image](https://github.com/user-attachments/assets/a217d1de-734d-4fa4-af8b-142ba1dcf432)

Result when trying to connect:
![image (1)](https://github.com/user-attachments/assets/103420bf-2271-4c48-99ed-69556cdb4315)

**Version Information (please complete the following information):**
 - OS: Windows
 - App Version: 4.6.4
 - Database version: Firebird 5.0.0.1306

**Additional context**
I am able to connect to the bank through any other IDE.

**Comment by azmy60** [comment]
Hey, thanks for reporting this! We haven't seen this issue as we tested this with firebird v4. We'll take a look at v5 now.

**Comment by azmy60** [comment]
How did you install Beekeeper Studio?

**Comment by Ddiidev** [comment]
I don't remember exactly how I installed Beekeeper, but I had the free version. Then I bought Ultimate, and received a link to download the Ultimate version.
I installed it over the version I already had installed, and then I tested it and this is what happened.

**Comment by azmy60** [comment]
Could you try using `0.0.0.0` instead of `localhost`? Or maybe `127.0.0.1`?

**Comment by azmy60** [comment]
I couldn't replicate this. Do you have any extra config you've added to `firebird.conf` (for me, firebird.conf is at `C:\Program Files\Firebird\Firebird_5_0\firebird.conf`). This seems like either the firebird server is not running or maybe it's running on a different port or something like that. Could you check the following?
- Open `services.msc`, see if the Firebird is running.
![image](https://github.com/user-attachments/assets/0e8a9798-918f-4b18-a59e-0c7e6b5f5190)
- Make sure you're connecting to the same port by looking at `RemoteServicePort` in `firebird.conf`.

**Comment by azmy60** [comment]
Also is there any errors from console?

`Help` > `Show developer tools`

**Comment by Ddiidev** [comment]
![image](https://github.com/user-attachments/assets/4c35ce39-59dd-46aa-8fd5-89e75b27eb46)

```
ConnectionInterface.vue?7ce3:98 error watch null firebird
ConnectionInterface.vue?7ce3:98 error watch Error: Incompatible wire encryption levels requested on client and server
    at wo (index.js:1360:21)
    at index.js:3138:21
    at k (index.js:3198:29)
    at Mo (index.js:3481:29)
    at Do (index.js:3203:24)
    at Socket.<anonymous> (index.js:3115:13)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23) firebird
13:45:48.295 (ConnectionInterface)         › Error: Incompatible wire encryption levels requested on client and server
    at wo (index.js:1360:21)
    at index.js:3138:21
    at k (index.js:3198:29)
    at Mo (index.js:3481:29)
    at Do (index.js:3203:24)
    at Socket.<anonymous> (index.js:3115:13)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
setTimeout (async)
d @ console.js:93
t @ console.js:46
o @ log.js:44
i @ log.js:27
n @ log.js:21
submit @ ConnectionInterface.vue?7ce3:210
processTicksAndRejections @ node:internal/process/task_queues:96
await in processTicksAndRejections (async)
click @ ConnectionInterface.vue:1
Br @ vue.runtime.esm.js:2987
r @ vue.runtime.esm.js:1785
o._wrapper @ vue.runtime.esm.js:7428

```




> Could you try using `0.0.0.0` instead of `localhost`? Or maybe `127.0.0.1`?
I tested it, the same problem occurs.

![image](https://github.com/user-attachments/assets/a004abfa-a687-4649-a94c-7679660dfc23)
![image](https://github.com/user-attachments/assets/b1f3bec9-2dea-43d2-bc51-4e38af88d38f)



> I couldn't replicate this. I wonder if you've added some extra config to `firebird.conf` or something similar?
> 
> ECONNREFUSED sounds like the firebird server is not running or maybe it's running on a different port. Could you also check the following?
> 
> * Open `services.msc`, see if the Firebird is running.
>   ![image](https://private-user-images.githubusercontent.com/38707148/355298745-0e8a9798-918f-4b18-a59e-0c7e6b5f5190.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NjMwMjYsIm5iZiI6MTcyMjk2MjcyNiwicGF0aCI6Ii8zODcwNzE0OC8zNTUyOTg3NDUtMGU4YTk3OTgtOTE4Zi00YjE4LWE1OWUtMGM3ZTZiNWY1MTkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDE2NDUyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExMGFiZmRkOTg2ZjU2OWU5ZmExYTZlZjliNzZmMmI4ZDY4N2I3MzkwOGUxMDUzMjlhOTRiNGI0MWY5MTI5NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GZ9s95bzk6MZsiUllkRmkTrSG3i5gS8r3nQ-muTPp90)
> * Make sure you're connecting to the same port by looking at `RemoteServicePort` in `firebird.conf`.
> * Maybe try a different port by changing the `RemoteServicePort` and then restart the firebird service

Both services are running.
![image](https://github.com/user-attachments/assets/9fe65ebf-58b9-4c04-85ca-8c1fa5a8fa14)

It's on the default port, I didn't modify it.
![image](https://github.com/user-attachments/assets/e1038bf6-5692-45cf-b4dd-b2d503de724a)

I'm able to connect with datagrip (ibexpert and dbever too):
![image](https://github.com/user-attachments/assets/42ce1ad1-e8c1-4310-908f-bf869a5fae19)

**Comment by azmy60** [comment]
Ah, okay. That seems to be a problem with the new [wire protocol](https://github.com/hgourvest/node-firebird?tab=readme-ov-file#firebird-30-support) as we don't support it yet. In order to connect from beekeeper, you need to add the following to your `firebird.conf`:

```conf
WireCrypt = Enabled # or disabled
AuthServer = Srp256, Legacy_Auth
AuthClient = Srp256, Srp, Win_Sspi, Legacy_Auth #Windows clients
```

So sorry you're dealing with this. It should've been in the docs so I'll be working on that.

**Comment by Ddiidev** [comment]
Funcionou, muito obrigado!!
