### ISSUE TITLE
BUG: 'TRUNCATE' will not shown as Keyword

### ISSUE THREAD

**Issue by CodebyCR** [beekeeper-studio/beekeeper-studio#2346]
**Describe the bug**
If you write a sql query which used the truncate keyword, the word 'TRUNCATE' will not highlighted as keyword.

**To Reproduce**
1. Connect to a database of your choice (I test it with Postgres, sql server & sqlite but I think it is a general problem)
2. Start a sql prompt
3. Write a basic truncate statement
4. See that the word 'TRUNCATE' will not highlighted, but the word 'Table' will so.

**Expected behavior**
I expected that the 'TRUNCATE' keyword will be highlighted as keyword. (case insensitive)
I can understand that this isn't a real priority bug, but englisch is not my mother tongue so I think each time I got a typo if the word don't highlighted.

**Screenshots / Gifs**
<img width="1478" alt="image" src="https://github.com/user-attachments/assets/2355fcab-f077-461c-ad6c-e11b789a5a37">

**Version Information (please complete the following information):**
 - OS: Windows 10, Windows 11, Mac OS 14.6
 - App Version 4.6.4 Ultimate
 - Database type and version [postgres, sqlserver, sqlite]

**Additional context**
- I test on different devices.

**Comment by azmy60** [comment]
Hey @CodebyCR , thanks for submitting this! We have planned on improving our text editor including better keyword autocompletion and syntax highlighting on different types of databases. I'm closing this since we have an issue related to this :)

Please see #1508
