### ISSUE TITLE
QUESTION: slower loading screen?

### ISSUE THREAD

**Issue by mcanepa** [beekeeper-studio/beekeeper-studio#2349]
**Details:**
I've noticed a few weeks ago that the app is not as fast as it used to be when it starts. It takes up to 15 seconds to show me the saved connections (meanwhile I see the animated database icon).

I'm the only one experience this delay? 

**Version Information [might be relevant to your issue]**
Operating System: Debian 12
App Version [help -> about]: 4.6.2
Database type and version [eg Posgresql 9.3]: MariaDB 10.11.6

**Comment by azmy60** [comment]
I actually just got this too using the installer version in windows, after I convinced my friend to use Beekeeper lol. I'll see if I can get some helpful info on this.

**Comment by azmy60** [comment]
In my case, it was when we installed the app (v4.6.2) for the first time. When we opened the app, there was no loading screen, it was just a blank white window sitting for about > 1 minute until the main screen UI, not the loading screen, showed up.

Unfortunately, I couldn't replicate it. It happened just one time and after that it looked normal.

**Comment by rathboma** [comment]
My guess -- this is when running migrations

**Comment by rathboma** [comment]
I need more information to consider a fix for this -- someone please figure out how to replicate!

@mcanepa if you can make a screen recording of this happening (and recording the logs from the terminal) that would be very helpful.

**Comment by mcanepa** [comment]
This is now fixed in v5.0.8. It's increible fast now. Faster than before!!
