### ISSUE TITLE
BUG: Filter bar is missing when open a table

### ISSUE THREAD

**Issue by Mangor1no** [beekeeper-studio/beekeeper-studio#2350]
**To Reproduce**
1. Open Beekeeper Studio
2. Connect to a database 
3. Select and open a table

**Expected behavior**
Filter bar should be displayed

**Version Information (please complete the following information):**
 - OS: MacOS Ventura
 - App Version: 4.6.2
 - Database type and version: Postgresql

**Comment by not-night-but** [comment]
Hey! Sorry you're having issues!

Are you able to open the developer console? (Help -> Show Developer Tools) Are there any errors in the console when you open the data view?

**Comment by rathboma** [comment]
This is in 'minimal mode'. Go to view -> disable minimal mode. I'm just going to remove this entirely.
