### ISSUE TITLE
BUG: Unable to find/replace in editor after running query

### ISSUE THREAD

**Issue by MiConnell** [beekeeper-studio/beekeeper-studio#2358]
**Describe the bug**
Editor Find and Replace boxes cannot be toggled after query has run

**To Reproduce**
1. write a query i.e. `select 1`
2. hit cmd/ctrl+f for find and cmd/ctrl+r for replace
3. find and replace text as needed
4. execute query
5. focus on editor and hit cmd/ctrl+f for find and cmd/ctrl+r for replace - the search box does not appear

**Expected behavior**
the find/replace dialog should appear every time editor focus is toggled

**Screenshots / Gifs**
![Screen Recording 2024-08-13 at 5 04 29 PM](https://github.com/user-attachments/assets/aa6bd9df-1d3d-43a5-aa8b-8c739cf2f939)

**Version Information (please complete the following information):**
 - OS: MacOS 14.5, apple silicon
 - App Version: 4.6.4
 - Database: Redshift 1.0.71629

**Comment by rathboma** [comment]
OMG you're right. I think the shortcuts are being captured by the result table.

**Comment by sakiterais** [comment]
This is still happening to me.
Is it really resolved?

OS: windows 10 pro
App version: 4.6.8
Database: Mysql
