### ISSUE TITLE
FEAT: Forward and Back shortcuts for switching between recently visited tabs

### ISSUE THREAD

**Issue by rathboma** [beekeeper-studio/beekeeper-studio#2366]
Much like a browser, being able to go forward and backwards would be really useful, particularly when clicking a foreign key.

For example:

1. Pretend you have 20 tabs open
1. Open table 'users' in `tab 3`
2. Click the 'company_id', which opens a tab containing the 'companies' table with the single record shown as the last tab, `tab 21`
3. How to easily navigate back to `tab 3`?

Using the `<back' shortcut (alt+left, or mouse button), we could instead go from tab 21 to tab 3, then using `forward>` (alt+right, mouse button) go from tab 3 back to tab 21.

**Comment by nk9** [comment]
Yes, a shortcut to switch tabs is super important. On Mac, this should be <kbd>Cmd</kbd>-<kbd>Shift</kbd>-<kbd>[</kbd> and <kbd>Cmd</kbd>-<kbd>Shift</kbd>-<kbd>]</kbd>, which is the standard shortcut in browsers, Finder, etc.

This is, of course, very different from Cmd-P (#1968), but they are not mutually exclusive.

**Comment by nk9** [comment]
Not sure I agree with overloading Back/Forward in this way. I can't think of a tabbed interface behaves like this, I think it would be surprising. Do people really need to have 20 SQL tabs open on a given database? 🤔

**Comment by rathboma** [comment]
Ooh, I like this.

**Comment by rathboma** [comment]
Hmm, this doesn't work if the table is already open though. I think ctrl+P should have the last tab seen as the first selected in the list

**Comment by rathboma** [comment]
Closing this in favor of #2379
