### ISSUE TITLE
BUG: Editor focus is lost after app switch

### ISSUE THREAD

**Issue by nk9** [beekeeper-studio/beekeeper-studio#2369]
**Describe the bug**
When focus is in the Query editor and you switch away from the app and then return, the editor has lost focus. So you can't, for example, run the query again.

**To Reproduce**
1. Open a database
2. Create a query (e.g. "SELECT * FROM my_table;")
3. Execute the query (e.g. <kbd>Cmd</kbd>-<kbd>Shift</kbd>-<kbd>Return</kbd>)
4. Switch away from the app (<kbd>Cmd</kbd>-Cmd)
5. Return to the app and try to run the query again with Cmd-Shift-Return.

**Expected behavior**
The app should remember its focused element. But it does not, so the query is not executed again. You have to click in the query view again.

**Screenshots / Gifs**

https://github.com/user-attachments/assets/34681568-bffb-4b4b-8305-087766dad1eb

**Version Information (please complete the following information):**
 - OS: macOS Sonoma 14.5
 - App Version: 4.6.4
 - Database type and version: SQLite3 3.43.2

**Comment by rathboma** [comment]
Thanks for the bug report!
