### ISSUE TITLE
Installation per apt

### ISSUE THREAD

**Issue by seisenreich** [beekeeper-studio/beekeeper-studio#238]
Hello everyone,

I didn't find a contact mail address or form at the homepage, so I open the installation issue here.
Please tell me if this is the wrong place for this kind of problem and if so please also tell me what is the right place.

When I try to install the app per apt - as described here on the official website installation guide [https://docs.beekeeperstudio.io/installation/#apt-deb](url)  - on an ubuntu 18.04 based distro, I get an error.
I copy-pasted all lines described in the installation docs. Everything gave me positive response output.

Can you help me get it to work? I'm not a fan of installing snaps, or AppImages when I have the option using my package manager, or a dedicated *deb file.
Thank's in advance for taking your time reading this.

This is the output of all steps:
```
➜ wget --quiet -O - https://bintray.com/user/downloadSubjectPublicKey\?username\=bintray | sudo apt-key add -
OK
➜ echo "deb https://dl.bintray.com/beekeeper-studio/releases disco main" | sudo tee /etc/apt/sources.list.d/beekeeper-studio.list
deb https://dl.bintray.com/beekeeper-studio/releases disco main
➜ sudo apt update
[...]
➜ sudo apt install beekeeper-studio
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  beekeeper-studio
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 62.6 MB of archives.
After this operation, 255 MB of additional disk space will be used.
Err:1 https://dl.bintray.com/beekeeper-studio/releases disco/main amd64 beekeeper-studio amd64 1.5.3
  403  Forbidden [IP: 13.227.220.86 443]
E: Failed to fetch https://d29vzk4ow07wi7.cloudfront.net/1e969a0cfd12a79be182c931f79fda39a32d5de583625d0d87c065c8fa9abb82?response-content-disposition=attachment;filename="beekeeper-studio_1.5.3_amd64.deb"&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvMWU5NjlhMGNmZDEyYTc5YmUxODJjOTMxZjc5ZmRhMzlhMzJkNWRlNTgzNjI1ZDBkODdjMDY1YzhmYTlhYmI4Mj9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMmJlZWtlZXBlci1zdHVkaW9fMS41LjNfYW1kNjQuZGViJTIyIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNTk0MjMzMzY4fSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjAuMC4wLjAvMCJ9fX1dfQ__&Signature=kneIo8AlQS4x1uIt2UNVbnlny2nEDFS6migPCjPcHeZUAzhklznrf1RfvQ9e-nYY76joDOVJZk1dYINX8431T9KBJaBdoMRgxlM8b3xAfIy241ZbwsfCTO0tILYWBXDm4XU-0tNYUCRlc2ad7b6Md6fSvcxZnmxMaePkCHBo~XPYYT0hy5cPNk54S6ERu99x7fsszfnMoTo0nLasYHgp52lymp-vdMPF2oNOJRvWcgcKru2qlrzrbvN3iIQRSiAxyYpWHsxWxwLxtvFKaYuZ0d6QJlWY3FNVGUER-E0TSei0JCh0afbzmMPxmlvH4kVE5L8sAB58InPHtWU9XCMuAQ__&Key-Pair-Id=APKAIFKFWOMXM2UMTSFA  403  Forbidden [IP: 13.227.220.86 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

```

Kind Regards,
Steven

**Comment by rathboma** [comment]
Hey Steven,

Hmm, I'm not sure why you're having this issue.

This may have been a short-term issue with Bintray (our deb host). Can you try running `sudo apt install beekeeper-studio` again?

If that doesn't work, some questions:

1. Are you behind a corporate firewall?
2. Can you `ping d29vzk4ow07wi7.cloudfront.net`?

**Comment by seisenreich** [comment]
Hi Matthew,

well, that was a quick response. Thank you.

My computer is not behind a corporate firewall.
Ping works flawlessly - < 30 ms timing + no data loss - , but `sudo apt install beekeeper-studio` will run into the same 403 error when trying to fetch the *deb file from cloudfront.
Strange. I temporarily disabled my Routers and computers firewalls, too. No effect.

What I can do is installing the app from the *.deb file uploaded here on git in the releases page. 
When I do that and then run `sudo apt install beekeeper-studio` or `sudo apt update && sudo apt upgrade beekeeper-studio` apt recognizes it and tells me it already has installed the newest version and nothing has to be done.

So my computer seems to dislike something about the download. Have I missed something in the installation guide? Do I have to change some query values in the given urls instead of copy pasting them or something?

**Comment by rathboma** [comment]
Looks like you have some escape characters in the gpg import statement? Maybe that's it.

So the DEB download will add the repo itself, so we can test doing it that way:

I'd try:
1. Remove the apt repo for beekeeper: `rm /etc/apt/sources.list.d/beekeeper-studio.list`
2. Reinstall the `deb` file -- it will add the repo & key itself
3. remove it `sudo apt remove beekeeper-studio`
4. install again (see if it works): `sudo apt update && sudo apt install beekeeper-studio`

**Comment by seisenreich** [comment]
After executing these 4 steps I still get a 403 error when trying to install the app per apt install.
Do I have to find remove the pgp key entry manually, too if it has been saved wrong in the first place due to possibly harmful url escaping?

It's getting late (already after 0am in my time zone) and I have to work tomorrow morning, so I will continue investigating this problem tomorrow after getting some sleep.
Also thank you for your quick support and effort you already put into my issue. I appreciate that.

Here is what I checked right away after executing the above steps:

I examined what exactly my terminal does when pasting the wget command from the installation guide after you said it could be an escaping problem.

When I copy the line `wget --quiet -O - https://bintray.com/user/downloadSubjectPublicKey?username=bintray | sudo apt-key add -` from the installation instructions into my terminal it automatically escapes the `?` and `=` chars with backslashes like that: 
```
➜ wget --quiet -O - https://bintray.com/user/downloadSubjectPublicKey\?username\=bintray | sudo apt-key add -
OK
```
It says "OK" as response, though.

When I remove the escaping backslashes it responds with
```
➜ wget --quiet -O - https://bintray.com/user/downloadSubjectPublicKey?username=bintray | sudo apt-key add -
zsh: no matches found: https://bintray.com/user/downloadSubjectPublicKey?username=bintray
gpg: no valid OpenPGP data found.
```

While wrapping it in double quotes will result in another "OK" Response:
```
➜ wget --quiet -O - "https://bintray.com/user/downloadSubjectPublicKey?username=bintray" | sudo apt-key add -
OK
```

But none of these will fix the 403 while trying to download the *.deb file.
Maybe I simply didn't test it every time correctly due to beeing sleepy. I will double check this in a few hours.

**Comment by rathboma** [comment]
When you get online tomorrow, can you verify that wget is installed and try the gpg command in bash instead?

**Comment by seisenreich** [comment]
Sure.
wget is installed:
```
➜ wget --version
GNU Wget 1.19.4 built on linux-gnu.
[...] All the other more detailed stuff about my wget installation listed in the output
```

wget is absolutely available through my zsh installation.
For testing purposes I also tried to add the gpg key by curl:
```
sudo curl https://bintray.com/user/downloadSubjectPublicKey\?username=\bintray | sudo apt-key add -
```
Results also in "OK". Both 
`wget --quiet -O - https://bintray.com/user/downloadSubjectPublicKey\?username\=bintray` and `sudo curl https://bintray.com/user/downloadSubjectPublicKey\?username=\bintray` return a valid GPG public key:
```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1

mQINBFTi8JIBEACcN1ucQ1uCOZ1owTELQV/6i4q7NbYdJ5wf7yPYfEugSo3yfbo3
Pw/XEvlnpDZmT155sGNOkteZtZMdcm5XhFbdtquLlrkjAcUGatq5rAt3eLAlvU7u
CBCDJg3ZaqpZti5ti2TfiaXHeawTpxaTb3V5tT4NYhY0aJqe0MGoVl2yZyoKMWsL
8XcUiJkUYnpu98BvnzO9ORSnKWHk60YxzZuHh5buMNiV4aI331ogiTxqISzTwEdQ
ygtlp4IeqE6w4x4RUOqQg/mu0xhqnP375KksPtKALLEr9vgqsJXfWVa5UmNl+rZP
gMiNEt+Abwewa6IQGgSU8GuxMp3qHxZtJQRNwIPx/yb7FngtWrUKIoQXs9xJwdJB
z4vhfFVeQlyPkEycQNcRfHVzK62oF8L5Jj/D8BIGAD+dj3x10Cy+qVK6BTY/F1zv
5iL12LjSlz8DtmTbqjit0WGoULjXFZALAU36q6FmE/nMcFuLaTUIinGV4fMvLgf9
Zn44juAhZMweOt63Pn4n/K0W+uOdrLSmGxJDhoxztabUdIpIMsw44wZ8gnSmPAef
IDTCjJO2x9s2YuaZbgstpJldooxGJ+FTe52QXFphti+tkiGOg6Tpj8Xq3+ZEM3L9
Js38SSdys0XBCHYiCv3/4Fk4jspTsCFrDzJ9HqNjsiktxPm9szmUZ72RjwARAQAB
tChCaW50cmF5IChieSBKRnJvZykgPGJpbnRyYXlAYmludHJheS5jb20+iQI4BBMB
AgAiBQJU4vCSAhsDBgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRA3nOGS1AGr
YTe6D/9lwml8fFJxfF2dI8GNPMmRAwnewu85JSWE/Yc3adlWL+NqXhUotDbSgUXl
RmC22fxBFaWipiCMjDm5R+dthOFmaBnnIdWmTvrTyupJlsYHCj1FN/5izgYpband
qFYbpdX34fOiH+kFVKOQI5WlMGvgYRTusk5pfORK87/e9zXFFuuc4OmgKgW0JX3c
faFp8HnJFVl6j7us384U/m06BBUbJb/az7IZNZXu0FPfL9jUIcWbGRWjmIdySE9b
yMOB95QPNlTrnGcjVuWa1gTN5uEbMRa5sVq6SAxmph5eGspJrJ05Bjwk5rS3LkLE
1tv31Bpeb+2jIoIXUJj8ESS/6bLK6/d7TbjMrdcRvSIZggf1u0JnjnsT6eYmfY1m
iVhKy4FFTyofDOlyt1k7lEYH+iJ4Z5ij/b6wpoUViKv+zqDRrSSbwun111f8rH7W
WldC3rEsH5R8J+jm54P5pwC/LnBg53GvofpntARLNUPvcFVp7Hjue3kbTVx51pxx
BBf593UnAXs+pZMyhl/synSngjpebufQHPeX1jJyGdXkDnavEp8M7yqf61zj8+sj
dFPP4Sdf3sv35zJmals9L33Bjsmhvs5LtNFDJQDea/NVGcgfMHzwrMJ9GcfVPkLk
31c0+OaK11hkDZFZYrBWU6FWsj8lICJPHlmFsU/zirfkvFYJ3rkCDQRU4vCSARAA
qvnUkerHq1Fq3ptYrYsNDLJSLbBch7jldPivGVDi0YHv2qwUnxo5O2GTxcyDFW8V
6Oy2InIhwsnWfSux3agqsoAuJNiFfvOS5dO2X62jx2tr34F7IbtN/lWXDHKeicbP
lD5VR1e0hNkd6NsPiryqsyy0S2+mgURKCQrCOtB01sj47B4h62iflxTZdC09trSD
yRYzk3lSlP/DjAbNzuapd84HTBtwxRgEtgC4gm9cIfmICfXPEwOOEediadM9V1GF
71dvfBcxw+p+3o8In9jDVJCxe6BX0pJ0C5AMNVrqpMGJ90GKHH6fGlubt9d/b1lk
eVdsi1nhiNfv7KUyaj/HlwZxfoz1rooPxpBxq1gp/jE+17/E09sEeK3YXrZGD5zz
V9K2vo1EWW4nurTvwuTlk2I7q00swQ4j8TS3McVDY6zjMyG3Cy4UkUNA0xS4gueg
/uVLzyFGPxol+Tu8eIhdZMEj3KF89cPsc8wsHxWYPaBOb6BwMm6xpExQiG+TqPli
lgwmOeiu8hyyFE+FJohdi4ms+4HrE3OchUhSYT9FqZFV+hcQ7qAq8kMdC9/Kg/uH
OOOTe2lH1ZqmzgQaeDkaSf8NLPEW/eOskPE01AdOqLaL8iM9YmbLo9MlPZM2WKL6
2aSiS3gxGNk4cXVPzt2ZAKMBHk41visnXU0/a1LoIAMAEQEAAYkCHwQYAQIACQUC
VOLwkgIbDAAKCRA3nOGS1AGrYcySEACZIe/xvLjEPhiVtUqcACPyXL4U7uA+V5Ob
ZVRmKKlkuoq3AQGQs/LAyCSYIGRw13hAn1X6tnireTv+vEoMDaX0sB1qUw49WOuB
8h71NaF/UYaPehjRWyNNq5Ul+icNwc8I8tgfkUUFCm/a5nJh8pZWfo+404ujEJzI
I2Qk6SoZqhbq2xrTgCrrKHxG5Gp+a35Y2v+TC8OkAN3Gu9LBg39t058xArBikk8I
jneCbIpDV5Fv5O9J1GuFEHFH2NIolaGppEOswd0ALs3zOmQ8KOZxLa4Gnn59gkQ6
/8Db1zXTW1QUQWiylvFte0q+fcSwhKEgJKyyN0ptk4Y27rclZxLMvPAjW19bqnVR
tigjWHJlxmBzX2bodLWbx1eRiS5QIeOk32CZlQN7EE0lniKLVNHReCrBmiBVRH9k
sKFbFafs2sI97FP2QySQuugcM30qDutA2Coo58SoAYAYM+0JlKSwwFRH0mGDPCiw
xSzOu4BNlIoxQh3EzrsmiyiB4hWPn9qzX5VM2IXvtL1Wzv8rUtpANkso9MPjsMAf
1Y/KBBaUm0QehoMwCWF/1KwsF9ENu6xon4l+GfkPhuCsEHEdqWIVGXrDLSshMGZ7
HdyAtUHPXXFV0FCT3KqV4UiJrjAzv7jqfSSUsXT8Qf4H+hC8lTfSBbFNfxP14T+E
JESa2SNRfw==
=EI0Z
-----END PGP PUBLIC KEY BLOCK-----% 
```

**Comment by seisenreich** [comment]
This seems to be the gpg key entry added to my apt-key chain:
```
pub   rsa4096 2015-02-17 [SC]
      8756 C4F7 65C9 AC3C B6B8  5D62 379C E192 D401 AB61
uid           [ unknown] Bintray (by JFrog) <bintray@bintray.com>
sub   rsa4096 2015-02-17 [E]
```

**Comment by seisenreich** [comment]
Nevermind. I had the same problem today trying to install balena etcher - with the same installation method: Add repo, add gpg key, install -> 403.
So it's obviously not problem beekeeper studio in particular!

**Comment by rathboma** [comment]
Going to close this as it seems unrelated to us, but @seisenreich please let us know if you find out what was going wrong!
