### ISSUE TITLE
BUG: Beekeeper 4.6.2 on macOS Mojave (10.14.5) never gets past the "Loading" screen

### ISSUE THREAD

**Issue by chrisriley** [beekeeper-studio/beekeeper-studio#2388]
**Describe the bug**
When attempting to launch Beekeeper Studio on macOS Mojave the initial "Loading" screen comes up and that is all that happens. 

**To Reproduce**
1. Double click on Beekeeper Studio
2. Witness the blank "Loading" screen

**Expected behavior**
The application loads and can be used.

**Screenshots / Gifs**
When double clicked:
<img width="1312" alt="Screen Shot 2024-08-29 at 11 23 14 AM" src="https://github.com/user-attachments/assets/fffe4d8d-1a92-4800-ab4d-e3d9ebc6e023">

When launched from the command line:
<img width="799" alt="Screen Shot 2024-08-29 at 11 23 28 AM" src="https://github.com/user-attachments/assets/4364ca0d-122a-4ad6-9d3b-2cae6360cee5">

**Version Information (please complete the following information):**
 - OS: macOS Mojave (10.14.5)
 - App Version: 4.6.2
 - Database type and version: N/A

**Comment by chrisriley** [comment]
I went back and checked older versions and 4.3.4 is the last version that will load on macOS Mojave

**Comment by rathboma** [comment]
Hey,

Thanks for reporting, but unfortunately I am unable to support Mac OS releases that are no longer supported by Apple. All the build tools I use are based on much newer MacOS versions that no longer provide compatibility.
