### ISSUE TITLE
QUESTION: Can you add x86_64 suffix to Linux AppImage file name?

### ISSUE THREAD

**Issue by leodip** [beekeeper-studio/beekeeper-studio#2393]
I'm using an app image launcher in Linux.

The app image launcher supports automatic updates from a GitHub 'releases' URL.

My CPU architecture is x86_64. 

The download link is:

`https://github.com/beekeeper-studio/ultimate-releases/releases/download/v4.6.4/Beekeeper-Studio-Ultimate-4.6.4.AppImage`

If I use that as a basis for the update URL, I have:

`https://github.com/beekeeper-studio/ultimate-releases/releases/download/v*/Beekeeper-Studio-Ultimate-*.AppImage`

The problem is... with that update URL, it downloads the **arm** version 😕

Can you add the x86_64 suffix to the x86_64 Linux App Image, in the same way as you do with arm?

![Screenshot_20240831_083529-1](https://github.com/user-attachments/assets/c1c02026-e88b-406f-af78-d9399ec20b2c)

**Comment by rathboma** [comment]
Hey! Beekeeper Studio comes with its own update checker, so I can't change the file names for the exact same reason (lol).

The built-in checker works great with app-image, you'll get an in-app notification when an update is available

**Comment by leodip** [comment]
@rathboma   Have you tested the update checker in Fedora with appimage? When I click to check updates, nothing happens. That's why I was trying to setup this auto update via Gear Lever.
I'm using Fedora 40 with KDE and a wayland session.
