### ISSUE TITLE
Why is sqlexpress not supported

### ISSUE THREAD

**Issue by apchenjun** [beekeeper-studio/beekeeper-studio#2395]
sql express connection error
<img width="425" alt="image" src="https://github.com/user-attachments/assets/2c762d35-0a82-464e-b7c3-3b715b83ce91">

**Comment by rathboma** [comment]
Hey! SQL Express is not supported by the Javascript Sql Server drivers from microsoft. Sorry about that, nothing I can do to work around it. :-/
