### ISSUE TITLE
FEAT: Docker Implementation 

### ISSUE THREAD

**Issue by ondrovic** [beekeeper-studio/beekeeper-studio#2396]
**Is your feature request related to a problem? Please describe.**
Would be nice to be able to use it as a docker container or in a docker compose stack, instead of having to download and run it locally

**Describe the solution you'd like**
Ability to spin up a docker instance of beekeeper-studio

**Describe alternatives you've considered**
Download and install it like intended

**Additional context**
N/A

**Database type, if appropriate**
N/A

**Comment by rathboma** [comment]
Hey! We don't have plans for a web-based version atm, so going to close this issue. Def an interesting idea though :-)

**Comment by rktyt** [comment]
For reference:
I have provided an example of using it as a container at https://github.com/beekeeper-studio/beekeeper-studio/issues/360#issuecomment-2995072006.
