### ISSUE TITLE
Support for ssh-agent with SSH tunneling

### ISSUE THREAD

**Issue by kozliatko** [beekeeper-studio/beekeeper-studio#24]
Is possible to use ssh-agent?
I have all my keys added to my ssh-agent and would be more comfortable if I can use this way.
Store key passwords somewhere in config files is not a best practise.

**Comment by rathboma** [comment]
It's a good question. I'm not sure the libraries I'm using support it. I'll check

**Comment by hlidotbe** [comment]
Hi, same issue here, my SSH keys are in a yubikey and so I can't even choose a file as it's exposed through the agent.

**Comment by rathboma** [comment]
@hlidotbe what platform are you on?

**Comment by hlidotbe** [comment]
Sorry, Linux (ubuntu). There are other issues I'll try to report ASAP.
-- 
Hugues Lismonde

**Comment by rathboma** [comment]
Ok, I guess you're using the version from the ubuntu store?
Matthew Rathbone
==
matthew.rathbone@gmail.com

**Comment by hlidotbe** [comment]
No I use the appimage from GitHub's releases

**Comment by rathboma** [comment]
Can you test https://github.com/beekeeper-studio/beekeeper-studio/actions/runs/106308642 (when the build is done?)

It should be able to use your SSH agent.

**Comment by hlidotbe** [comment]
Just tried and I get an error when trying to connect. I've checked and the SSH_AUTH_SOCK env is correctly set and the agent is running

**Comment by rathboma** [comment]
Ok let me try a couple of things and I'll get back to you on this ticket

**Comment by rathboma** [comment]
Ok, I've verified the SSH Agent pass-through is working on this build - https://github.com/beekeeper-studio/beekeeper-studio/actions/runs/109728576 (unless you are using Snap).

If you want to try one more time, I'm confident it should work

**Comment by rathboma** [comment]
Fixed in 1.4
