### ISSUE TITLE
Funky alignment with long column types

### ISSUE THREAD

**Issue by rathboma** [beekeeper-studio/beekeeper-studio#240]
When the column type, or column name, is long, the badge behaves in weird ways.

![image](https://user-images.githubusercontent.com/279769/86977094-7cdb4000-c141-11ea-8bdb-441d562e2bbd.png)

**Comment by rathboma** [comment]
@ghstng this done right?

**Comment by UtechtDustin** [comment]
![Bildschirmfoto von 2020-08-07 09-16-34](https://user-images.githubusercontent.com/13292481/89619711-b614e600-d88e-11ea-8bfa-9ca1430ad850.png)
![Bildschirmfoto von 2020-08-07 09-16-29](https://user-images.githubusercontent.com/13292481/89619712-b6ad7c80-d88e-11ea-8e4e-681f9bc1ef10.png)

@rathboma Yes it is.
