### ISSUE TITLE
Time Execution

### ISSUE THREAD

**Issue by alejnadro485** [beekeeper-studio/beekeeper-studio#242]
Hi, I'm use Beekeeper Studio in my work and study, and it has really helped me.

It happened that I needed to optimize some queries and views, and I needed to know how long the execution of some routines (and other things) lasted to know if those changes were the solution, so I ask you if you would include information about the sentence execution time

In any case already many thanks

**Comment by rathboma** [comment]
This is in master now! Will be in a release this week :muscle:
