### ISSUE TITLE
on db error, display error detail too

### ISSUE THREAD

**Issue by mariusa** [beekeeper-studio/beekeeper-studio#243]
Example with postgres command line:
`
ALTER TABLE persons ADD CONSTRAINT persons_key UNIQUE (company_id, first_name, last_name);
`
gives
```
ERROR:  could not create unique index "persons_key"
DETAIL:  Key (company_id, first_name, last_name)=(19, 'John', 'Doe') is duplicated.
```

beekeeper only shows
`
ERROR:  could not create unique index "persons_key"
`

Please show the detail too.

**Comment by rathboma** [comment]
Ah, I thought I was providing all the error. I'll take a look.

**Comment by mariusa** [comment]
Another example, it has HINT too:
```
ERROR:  cannot drop column age of table persons because other objects depend on it
DETAIL:  view persons_v depends on column age of table persons
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
```

**Comment by rattrayalex** [comment]
It would also be awesome if the line number was included, eg:

```
ERROR:  relation "public.film" does not exist
LINE 31: from "public"."film" as __film
              ^
```

**Comment by CP920** [comment]
Hi, is there any news about this problem? I have the same one (under PostgreSQL) and it can be really disabling to solve the problem. Without it Beekeeper would be perfect for my use.

**Comment by olymk2** [comment]
just hit this exact issue with a unique constraint with out it displaying the detail makes it quite hard to fix the issue

**Comment by rathboma** [comment]
Hey folks! A fix for this is coming in the next version! for postgresql at least. It include error line highlighting
