### ISSUE TITLE
Connection Error Between Beekeeper Studio and MySQL workbench 8.0

### ISSUE THREAD

**Issue by abhdhar-1618** [beekeeper-studio/beekeeper-studio#2446]
**Description**: I am experiencing a connection issue when trying to connect to MySQL using Beekeeper Studio. The specific error message I am encountering is:

`Access denied for user 'testuser'@'localhost' (using password: YES)`

**Environment**:

- **Beekeeper Studio Version**: 4.6.2
- **MySQL Version**: 8.0
- **Operating System**: Windows 11

**Steps to Reproduce**:

1. Install MySQL 8.0 and ensure the service is running.
2. Create a new user in MySQL with the following commands: 
    
    `CREATE USER 'testuser'@'localhost' IDENTIFIED BY 'password'; GRANT ALL PRIVILEGES ON *.* TO 'testuser'@'localhost' WITH GRANT OPTION; FLUSH PRIVILEGES;`
    
3. Open Beekeeper Studio.
4. Attempt to connect to MySQL using the credentials:
    - **Username**: testuser
    - **Password**: password
    - **Host**: localhost
    - **Port**: 3306

**Expected Behavior**: I expect to connect successfully to the MySQL database with the new user credentials.

**Actual Behavior**: I receive the following error message:

sql

`Access denied for user 'testuser'@'localhost' (using password: YES)`

**Troubleshooting Steps Taken**:

- Verified credentials are correct and correspond to the user created in MySQL.
- Checked MySQL user permissions, and confirmed that `testuser` has all privileges on all databases.
- Tested the connection using MySQL Workbench 8.0, which connects successfully using the same credentials.
- Checked MySQL server logs for any additional error messages related to the connection attempt.
- Confirmed that MySQL server is running and accessible.
- Tried using `127.0.0.1` instead of `localhost` in Beekeeper Studio but received the same error.
- Ensured that firewall settings allow connections on port 3306.
- Reinstalled Beekeeper Studio to rule out any application issues.

**Additional Information**:

- I am able to connect to the MySQL server using MySQL Workbench without issues, indicating that the server is functioning correctly.
- I have verified that MySQL configuration files (my.cnf/my.ini) do not have restrictions that could prevent user access.

**Request**: I would appreciate any guidance on resolving this issue, as it seems specific to the Beekeeper Studio connection process. If you need further information or logs, please let me know.

Thank you for your assistance!

![image](https://github.com/user-attachments/assets/48eb79df-b5aa-4aa7-9760-92fa0e62cb3b)

**Comment by not-night-but** [comment]
Hey! I was able to replicate this issue with beekeeper when using your script. I was also able to fix it by executing this:

```sql
DROP USER 'testuser'@'localhost';
FLUSH PRIVILEGES;
CREATE USER 'testuser'@'%' IDENTIFIED BY 'password'; 
GRANT ALL PRIVILEGES ON *.* TO 'testuser'@'%' WITH GRANT OPTION; 
FLUSH PRIVILEGES;
```

I assume the issue is that, at least when I tried to connect with your original user, the IP address I was accessing from was not considered 'localhost', and thus was denied because you only allowed localhost. This may be something to do with how the library we use to connect handles connecting, not totally sure yet, but that could at least solve your issue I hope.

**Comment by rathboma** [comment]
@abhdhar-1618 My guess is that this is a mix up between IPv6 and IPv4. Can you send a screenshot of your connection screen in Beekeeper Studio?

By default Beekeeper uses ipv4 right now, but will soon default to ipv6, so that might be the difference.

**Comment by rathboma** [comment]
Try using ipv6 version of localhost: `::1`

**Comment by abhdhar-1618** [comment]
> Hey! I was able to replicate this issue with beekeeper when using your script. I was also able to fix it by executing this:
> 
> ```sql
> DROP USER 'testuser'@'localhost';
> FLUSH PRIVILEGES;
> CREATE USER 'testuser'@'%' IDENTIFIED BY 'password'; 
> GRANT ALL PRIVILEGES ON *.* TO 'testuser'@'%' WITH GRANT OPTION; 
> FLUSH PRIVILEGES;
> ```
> 
> I assume the issue is that, at least when I tried to connect with your original user, the IP address I was accessing from was not considered 'localhost', and thus was denied because you only allowed localhost. This may be something to do with how the library we use to connect handles connecting, not totally sure yet, but that could at least solve your issue I hope.

The problem seems to have resolved for now by executing the above steps and an eventual reinstallation of Beekeeper studio. However, I an still getting the Access denied error when I am trying to check for the password acceptance test in cmd prompt. Strangely enough, both Mysql workbench and Beekeper is working just fine as if nothing has happened. 😂 Thanks a lot for your help..!

**Comment by abhdhar-1618** [comment]
The issue is resolved for now. Thanks a lot for your help and suggestions @not-night-but @rathboma !
