### ISSUE TITLE
Display table contents when clicking on a table in the sidebar

### ISSUE THREAD

**Issue by iKlsR** [beekeeper-studio/beekeeper-studio#25]
Left clicking on a table in the list should at minimum do a `select *` and preview the results.

**Comment by iKlsR** [comment]
I know it's coming and the project is still in it's early stages but have been wanting to do something similar for a while now (was going to use Qt) so stumbling on this is great and I'd love to help out if we can create some milestones, planned features etc.

**Comment by rathboma** [comment]
Working on it!
