### ISSUE TITLE
Postgres: error listing tables

### ISSUE THREAD

**Issue by louis77** [beekeeper-studio/beekeeper-studio#251]
When I connect to a standard Postgresql 12 database, connection is successful but I don't see the list of tables or anything. I can execute queries though.
In the JavaScript console I see the following error message:
"error: column a.relname does not exist"

![Screenshot from 2020-07-21 21-54-34](https://user-images.githubusercontent.com/1240462/88100575-00168000-cb9d-11ea-881b-81634dcb8ac4.png)

I run Beekeeper Studio v 1.6.4 via snap on Ubuntu 20.04.

**Comment by rathboma** [comment]
I've got a fix coming up for this today!

**Comment by rathboma** [comment]
Fixed in 1.6.9

**Comment by louis77** [comment]
Thank you so much @rathboma , that was super fast and I can confirm it works now!
