### ISSUE TITLE
My data no longer appears in 1.6.9 - Ubuntu 20.04

### ISSUE THREAD

**Issue by martindufresne** [beekeeper-studio/beekeeper-studio#253]
Hello, this morning I downloaded the latest version of the application (1.6.9), but since then, when I connect, my data no longer appears to me. However, version 1.5.3 worked really well. I am on Ubuntu 20.04 and downloaded the appimage. But I also tested with the snap and the DEB and each package has the same result. Here is a screenshot.

![Screenshot from 2020-07-22 08-48-32](https://user-images.githubusercontent.com/2438127/88178733-d7bc6f00-cbf8-11ea-908b-1a861138c9dc.png)

**Comment by louis77** [comment]
Which database engine do you try to connect to?

**Comment by martindufresne** [comment]
I am trying to connect to MySQL databases.

**Comment by louis77** [comment]
Do you have SSL enabled?

**Comment by martindufresne** [comment]
No, it is not activated. And if I reinstall version 1.5.3, everything comes back. So I tell myself that there is something in the latest version that is causing the bug. Could there be a conflict with configuration files since I tested the Snap and DEB version as well?

**Comment by rathboma** [comment]
Hmm, that's concerning. I'll take a look today for you

**Comment by martindufresne** [comment]
thank you so much!

**Comment by rathboma** [comment]
@martindufresne few questions to help me debug:
- What version of MYSQL?
- Can you give me the table schema (columns and types)? Even just the types is helpful

**Comment by martindufresne** [comment]
I am on MySQL 8.0.20. I have attached a screenshot of my table.I have indeed errors in the console. I attach a screenshot. Which is weird, I don't have this problem in version 5.3.
![Screenshot from 2020-07-22 14-20-32](https://user-images.githubusercontent.com/2438127/88213405-b8d4d180-cc26-11ea-9c65-7fc0693cd2b9.png)
![Screenshot from 2020-07-22 14-22-45](https://user-images.githubusercontent.com/2438127/88213529-dbff8100-cc26-11ea-97dc-5f17ff4ad3e0.png)

**Comment by rathboma** [comment]
Ok, one more thing -- can you right click the console click save-as, save the .log file and share it here?

**Comment by martindufresne** [comment]
Of course! It's sent! thanks again

**Comment by rathboma** [comment]
Thanks! Hmm, unfortunately that doesn't show too much. I think one of the tables in the database has a schema that is breaking Beekeeper Studio somehow. I don't think its the orders table, but some other table.

Are you using any mysql plugins at all?

If you can, keep the console open, then click the 'refresh' button next to `tables and views' and see if it gives you any different looking errors, then send me that console output. If that doesn't show me the issue I'll have to manually try and figure it out

**Comment by martindufresne** [comment]
I am not using a MySQL plugin. And if I keep the console open and refresh, I don't have any new errors. I'm sorry for the trouble. But I greatly appreciate your efforts :)

**Comment by MasterOdin** [comment]
It may be worth testing the build from #255 to see if it resolves your issues: https://github.com/beekeeper-studio/beekeeper-studio/actions/runs/178869355

**Comment by martindufresne** [comment]
It works! Yeah! You're on fire ... Nice work and really, a big, big thank you for your help.
