### ISSUE TITLE
UNSUPPORTED_PROTOCOL when using SSL and TLSv1 or TLSv1.1

### ISSUE THREAD

**Issue by louis77** [beekeeper-studio/beekeeper-studio#254]
I'm trying to connect to a MySQL with SSL turned on. Other clients connect successfully using these parameters:
`?useSSL=true&verifyServerCertificate=false`.

Beekeper however shows the following error message:
![Screenshot from 2020-07-22 14-54-53](https://user-images.githubusercontent.com/1240462/88178879-57633180-cc2b-11ea-9141-20772d0aea67.png)

OpenSSL is installed (version 1.1.1f-1ubuntu2). MySQL version is 5.7.25.
Beekeper Studio v 1.6.9 (via snap) on Ubuntu 20.04

Is there anything missing on the system?

**Comment by rathboma** [comment]
Hey @louis77,

I'll take a look for you today.

**Comment by rathboma** [comment]
@louis77 couple of questions to help me debug:

1. Can you try the AppImage version and see if that behaves the same?
2. Can you open the development console (help -> show development tools) and see if there are error details in there? If so right click -> save as and send them to me?
3. Can you confirm whether your MySQL server is using TLS < 1.2? It might be using TLS v 1?

**Comment by rathboma** [comment]
I think this is because Node by default uses TLS v1.2 minimum - hence my questions

**Comment by rathboma** [comment]
@louis77 do me a favor and check this:

Open the console (help -> show development tools -> console) and run:
```
require("tls").DEFAULT_MIN_VERSION = "TLSv1"
```

Then try connecting to your mysql database again.

**Comment by louis77** [comment]
@rathboma I can confirm that with TLSv1 it works. So obviously my provider doesn't support TLS v1.2 yet.

**Comment by rathboma** [comment]
Thank you so much for testing!

I'm going to treat this as a regression as it's due to upgrading from electron 5 (node 10) to electron 8 (node 12). I'll set the minimum to v1 by default.

**Comment by VaporFan** [comment]
still got this on 5.0.9

Failed to connect to 10.2.0.1:1433 - 1236952491648:error:100000f0:SSL routines:OPENSSL_internal:UNSUPPORTED_PROTOCOL:../../third_party/boringssl/src/ssl/handshake_client.cc:714:

**Comment by gravitywave-tech** [comment]
still got this on 5.1.12. Was normally connect to mssql but failed after upgrade. My mssql instance version is  SQLServer2008R2 (very old) i think. 
Failed to connect to 127.0.0.1:1433 - 116609664:error:100000f0:SSL routines:OPENSSL_internal:UNSUPPORTED_PROTOCOL:..\..\third_party\boringssl\src\ssl\handshake_client.cc:714:

**Comment by laok00** [comment]
DataGrip can resolve this issue by specifying SQL Server driver version 8.2.2. I was wondering if Beekeeper allows this as well?
