### ISSUE TITLE
BUG: Unable to install beekeeper-studio_4.6.8_amd64.deb - Invalid cross-device link

### ISSUE THREAD

**Issue by helmist** [beekeeper-studio/beekeeper-studio#2553]
**Describe the bug**

error creating hard link './opt/Beekeeper Studio/resources/public/icons/png/32x32.png': Invalid cross-device link

**To Reproduce**
1. Follow website instructions to install the deb vebatim:
```sh
# Install our GPG key
curl -fsSL https://deb.beekeeperstudio.io/beekeeper.key | sudo gpg --dearmor --output /usr/share/keyrings/beekeeper.gpg \
  && sudo chmod go+r /usr/share/keyrings/beekeeper.gpg \
  && echo "deb [signed-by=/usr/share/keyrings/beekeeper.gpg] https://deb.beekeeperstudio.io stable main" \
  | sudo tee /etc/apt/sources.list.d/beekeeper-studio-app.list > /dev/null

# Update apt and install
sudo apt update && sudo apt install beekeeper-studio -y
```

3. Get error output:
```sh
Get:1 https://deb.beekeeperstudio.io stable/main amd64 beekeeper-studio amd64 4.6.8 [78.6 MB]
Fetched 78.6 MB in 23s (3,401 kB/s)                                                                                                  
Selecting previously unselected package beekeeper-studio.
(Reading database ... 228532 files and directories currently installed.)
Preparing to unpack .../beekeeper-studio_4.6.8_amd64.deb ...
Unpacking beekeeper-studio (4.6.8) ...
dpkg: error processing archive /var/cache/apt/archives/beekeeper-studio_4.6.8_amd64.deb (--unpack):
 error creating hard link './opt/Beekeeper Studio/resources/public/icons/png/32x32.png': Invalid cross-device link
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/beekeeper-studio_4.6.8_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Expected behavior**

A working install of beekeeper studio

**Screenshots / Gifs**
If applicable, add screenshots or GIFS to help explain your problem.

**Version Information (please complete the following information):**
 - OS: Debian
 - App Version 4.6.8
 - Database type and version Postgresql 16 & 17

**Additional context**
Anything else you think might be helpful

This is the second attempt to get this installed, while I know linux is a subset of your userbase, it would be great if there could be a working deb released, even if it was an older version?

**Comment by not-night-but** [comment]
@helmist Unfortunately it looks like this is an issue with electron-builder that seems to happen when you have `/opt`, `/var` or other system directories on a separate partition. 
See: https://github.com/beekeeper-studio/beekeeper-studio/issues/593

I'd advise trying the AppImage version instead, or try some of the other workarounds mentioned in the thread above.

**Comment by helmist** [comment]
Gotcha. I'm reading through that thread now, to see what other workarounds exist.

**Comment by rathboma** [comment]
Hey folks, yeah this is an Electron issue, not a Beekeeper issue I'm afraid. I have to close this right now as can't fix
