### ISSUE TITLE
BUG: Nothing happens when "Import .sql files" is clicked

### ISSUE THREAD

**Issue by GoodJob** [beekeeper-studio/beekeeper-studio#2556]
Going on SAVED QUERIES and clicked on:
"Import .sql files" nothing happens

MacOS 14.6.1
Beekeeper Studio 4.6.8

**Comment by rathboma** [comment]
Hey!

Thanks for the heads up, we'll make sure this is fixed for 5.0.0

**Comment by rathboma** [comment]
Let's also rename this to something like `Import .sql files into Saved Queries` to make it more explicit what it does.
