### ISSUE TITLE
FEAT: Keep focus in SQL editor after running a query

### ISSUE THREAD

**Issue by ahardin13** [beekeeper-studio/beekeeper-studio#2557]
**Is your feature request related to a problem? Please describe.**
Note: This is in 5.0.0 beta 2

After running a query, focus moves to the results. When building queries, I frequently run the query in phases as I make changes. I do not expect my focus or cursor to move after running a query.

**Describe the solution you'd like**
Keep focus in SQL editor after running a query (whether run via keyboard or the Run button).

**Describe alternatives you've considered**
I tried using the keyboard (i.e. optiono-shift-tab) to change focus back to the editor, but it does not work.

**Additional context**
n/a

**Database type, if appropriate**
n/a

**Comment by rathboma** [comment]
Ah, yeah that's a bug, thanks for pointing this out! Focus should stay in the editor unless explicitly moved to results
