### ISSUE TITLE
BUG: Url parse doesn't work

### ISSUE THREAD

**Issue by azmy60** [beekeeper-studio/beekeeper-studio#2559]
This is a regression. We used to be able to copy and paste a url into the host field, and it would parse and fill out the rest of the connection form based on the url.

For example, if I create a new connection for cockroach, and paste this to host  `postgresql://matthew:password@free.1.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full&options=--cluster%3Dbks-tester-12345`, it should parse that and fill the rest of the form with `host => free.1.cockroachlabs.cloud`, `port => 26257`, etc..  

NOTE:

The parse method is in `SavedConnection` class. But because we can't call that directly from frontend, we probably need to add a utility handler and use that instead.

**Comment by not-night-but** [comment]
@azmy60 we do send this to the utility proc, that handler might be broken
