### ISSUE TITLE
BUG: When connecting to SQL Server, double colon is recognized as two query parameter

### ISSUE THREAD

**Issue by masnmt** [beekeeper-studio/beekeeper-studio#2560]
**Describe the bug**
Starting with SQL Server 2016, "geometry" and "geography" are implemented as geospatial data types, and functions related to these types are provided in the form of geometry::STxxx and geography::STxxx.
When using these functions in Beekeeper Studio's SQL Editor, "::" is recognized as two query parameter and the query cannot be executed.

**To Reproduce**
Run below the query.
```
DECLARE @g geometry;  
DECLARE @h geometry;  
SET @g = geometry::STGeomFromText('POLYGON((0 0, 2 0, 2 2, 0 2, 0 0))', 0);  
SET @h = geometry::STGeomFromText('POLYGON((1 1, 3 1, 3 3, 1 3, 1 1))', 0);  
SELECT @g.STWithin(@h);
```

**Version Information (please complete the following information):**
 - OS: Linux
 - Version 4.6.8
 - SQL Server 2016

**Comment by rathboma** [comment]
Great find, thanks! We're on it.
