### ISSUE TITLE
BUG: Database restore doesn't seem to work in v5.0 Beta 2 (mysql / mariadb)

### ISSUE THREAD

**Issue by mkellyxp** [beekeeper-studio/beekeeper-studio#2564]
**Describe the bug**
I have a .sql file that contains a create table and insert scripts.  In previous versions of Beekeeper, I was able to open the database, then restore database, and supply this file and it would import.  But now it returns with an error saying "Unknown Database: null"

**To Reproduce**
1. Open a local database
2. Click on Tools -> restore database backup
3. Provide a .sql file that contains a create table and inserts

**Expected behavior**
It should run the SQL file against the opened database

**Screenshots / Gifs**
![Screenshot from 2024-11-07 15-45-32](https://github.com/user-attachments/assets/f7ec42b8-d449-47e3-b6ea-cb54f4c08448)
![Screenshot from 2024-11-07 15-45-48](https://github.com/user-attachments/assets/65932e88-9297-4c50-af24-ef883b1b9fdb)
![Screenshot from 2024-11-07 15-45-51](https://github.com/user-attachments/assets/9bacc2c2-b1da-46fc-a6b9-c19ff832d964)
![Screenshot from 2024-11-07 15-46-57](https://github.com/user-attachments/assets/36f3d1da-39e3-4385-92a0-dc3b38772079)

**Version Information (please complete the following information):**
 - OS: Linux (NixOS)
 - App Version 5.0.0-beta.2
 - Database type and version  mariadb from 11.0.6-MariaDB, client 15.2 for Linux (x86_64) using readline 5.1

**Additional context**
Anything else you think might be helpful

**Comment by not-night-but** [comment]
Thanks for reporting this!! I'll look into it

**Comment by mkellyxp** [comment]
> Thanks for reporting this!! I'll look into it

Thanks for the quick reply!  Let me know if you need me to test anything else.  Loving the v5 release so far!

**Comment by not-night-but** [comment]
@mkellyxp Do you happen to have Default Database set for your connection? It looks like for some reason we are pulling the database name from that, so you may be able to get around this by setting that
