### ISSUE TITLE
BUG: Connections appearing multiple times in 'recent connections'

### ISSUE THREAD

**Issue by rathboma** [beekeeper-studio/beekeeper-studio#2581]
Duplicate connections are seen in recent connections, it should only show the latest time per connection.

![image](https://github.com/user-attachments/assets/4da6380b-7803-44e1-a122-b8fc6d4333c0)

**Comment by not-night-but** [comment]
@rathboma this isn't a current bug afaik. This was caused by the used connection bug from a while back, it duplicated a bunch of used connections. It is no longer actively duplicating the connections, but those duplicates still exist
