### ISSUE TITLE
Support a Light Theme

### ISSUE THREAD

**Issue by iKlsR** [beekeeper-studio/beekeeper-studio#26]
I love a good dark theme as much as anyone unfortunately some pairings don't work for everyone. When you combine 4k, tiny white text and dark backgrounds, it's easily unusable for some people.

See this link https://jessicaotis.com/academia/never-use-white-text-on-a-black-background-astygmatism-and-conference-slides/

**Comment by rathboma** [comment]
Hey! We have a light-theme in the works. Stay tuned :-)

**Comment by Siilwyn** [comment]
Would be awesome if the theme defaults to 'automatic', in that it will follow the OS setting from [`prefers-color-scheme`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme).

**Comment by castlese** [comment]
The last time I had BeeKeeper open, it was in light mode. Now in dark. I see mention that there is no setting? Any tips for changing it?

**Comment by rathboma** [comment]
Release coming out in the next few days! Stay tuned
