### ISSUE TITLE
BUG: Say something here

### ISSUE THREAD

**Issue by mkellyxp** [beekeeper-studio/beekeeper-studio#2607]
**Describe the bug**
When attempting to restore a database backup, I'm confronted with an error message saying "ERROR 1049 (42000): Unknown database 'null'"

When looking at the command it WILL run, it shows this:

```
/run/current-system/sw/bin/mariadb --verbose --user=root --password="temppass" --protocol=TCP --host=127.0.0.1 --port= --database=null --execute="SOURCE /home/mkelly/Downloads/course_dump.sql"
```

Indicating its passing in "null" as the database, even though I have one selected.  I've also had an error message that the port was = "null" as well.  Perhaps they need fallbacks if blank?

**To Reproduce**
1. Connect to MySQL or MariaDB, and create a new database
2. Click Tools -> Restore a Database Backup
3. Select a .SQL file, and execute

**Expected behavior**
The restore should work and restore the database.  The error seems to be from not passing in the selected database and sometimes port.

**Screenshots / Gifs**
![Screenshot from 2024-11-18 15-51-27](https://github.com/user-attachments/assets/b15f06e6-0fff-4124-afdc-635b0ac9fae0)
![Screenshot from 2024-11-18 15-51-58](https://github.com/user-attachments/assets/069e1b92-842f-47b6-ad75-657dcf98fe56)
![Screenshot from 2024-11-18 15-52-28](https://github.com/user-attachments/assets/3c6f69de-00e9-4733-a8cf-8ae43c4c5d57)

**Version Information (please complete the following information):**
 - OS: Linux NixOS
 - App Version: 5.0.0-beta.2
 - Database type and version:  11.0.6-MariaDB MariaDB Server

**Comment by not-night-but** [comment]
Hey! I believe this should be fixed in beta-3, have you tried that version?

**Comment by mkellyxp** [comment]
> Hey! I believe this should be fixed in beta-3, have you tried that version?

OHhh there's a beta 3?  let me grab that and check.  Thanks!

**Comment by mkellyxp** [comment]
Yup. you are correct.. Beta 4 fixes it!  Thanks!

Auto update prob wont work for me, as I'm the weirdo running Linux, and using the App Image.  I maintain my own build file here:

https://github.com/mkellyxp/nix/blob/main/common/beekeeper.nix

**Comment by not-night-but** [comment]
@mkellyxp not a weirdo, I daily drive arch lol. Might be a nixos thing though 🤔
