### ISSUE TITLE
Enhancement: Change the color of brackets in SQL when light theme is used

### ISSUE THREAD

**Issue by sooxin** [beekeeper-studio/beekeeper-studio#261]
In the current version(1.6.10), if **light theme** is used, the color of brackets in SQL makes it a little difficult to recognize.

![image](https://user-images.githubusercontent.com/16705366/88652992-13c26900-d0fe-11ea-8d0c-593f039809ec.png)

So would it be possible to change the brackets' color OR provide a function to customizing SQL color scheme?

*What's more, Beekeeper is an excellent and beautiful DB tool, thanks for your efforts.*

**Comment by rathboma** [comment]
Doh, that's our bad. We'll fix it.

**Comment by ghstng** [comment]
fixed
