### ISSUE TITLE
BUG: There're two menu bars and two title bars after changing menu style to native

### ISSUE THREAD

**Issue by sooxin** [beekeeper-studio/beekeeper-studio#262]
![image](https://user-images.githubusercontent.com/16705366/88912821-751b4100-d292-11ea-8c39-da6ecf6231a2.png)

Beekeeper Version: 1.6.11
OS: Windows 10 1903

**Comment by rathboma** [comment]
You have to close the app totally, then reopen it.nif you just open a new window this will happen!

**Comment by rathboma** [comment]
Can you let me know if this fixes it?

**Comment by sooxin** [comment]
Hi @rathboma , 

I just clicked "Close" button, then reopened it, unfortunately, this bug happened again.

Here's what I did:
![gif](https://user-images.githubusercontent.com/16705366/89034435-85ebb580-d36b-11ea-8922-9bff7ff13a10.gif)

**Comment by rathboma** [comment]
lol, that's weird. I'll see if I can replicate.

**Comment by rathboma** [comment]
Can you open 'Beekeepers Database' and send me a screenshot of the settings table? I want to see what the menustyle setting was set to.

**Comment by rathboma** [comment]
This is fixed in Master
