### ISSUE TITLE
QUESTION: Is there any telemetry in this software?

### ISSUE THREAD

**Issue by elieobeid7** [beekeeper-studio/beekeeper-studio#2626]
First things first, I installed the software and I love what you have to offer, perfect, kudos, hats off to you.

I would like to know if there's any telemetry, because that topic isn't discussed and there's no settings button to check what's happening under the scenes.

**Comment by rathboma** [comment]
Nope, nada, nothing. Check out mission:

https://www.beekeeperstudio.io/mission/

I def will be adding error reporting in the future to help debug problems, but no telemetry.
