### ISSUE TITLE
BUG: SSL error message in postgresql localhost after 5.0.5 update

### ISSUE THREAD

**Issue by nirogu** [beekeeper-studio/beekeeper-studio#2630]
**Describe the bug**

Beekeeper was just updated to version 5.0.5 (with the debian apt package). Before that, my connection to localhost worked perfectly. But after the release, I am always getting the following error when I am trying to connect to my local postgres instance: `There was a problem. The server does not support SSL connections`. I am not using SSL or SSH (as it is a localhost connection), as seen in the screenshot below.

I am certain it is an issue in beekeeper, because I can connect to the database through other means.

**To Reproduce**

Create a connection to a local postgres database, and then try to connect.

**Expected behavior**

The connection works as expected, and does not try to use SSL unless I want to.

**Screenshot**

![beekeeper-screenshot](https://github.com/user-attachments/assets/aafc3a71-ad75-422f-8808-8bd4e40624a2)

**Version Information (please complete the following information):**

 - OS: Linux (debian-based)
 - App Version: 5.0.5
 - Database type and version: Postgresql

**Additional context**

Remote connections seem to be working fine. Localhost connection was also fine before the update.

**Comment by nirogu** [comment]
@rathboma Do I close this as solved then? Or is there anything else left to be done?

**Comment by Wawilow** [comment]
I've got the same problem in 5.0.5, solve the problem with updating to 5.0.6.

Thank you for fast fix
