### ISSUE TITLE
BUG: Saved queries gone again

### ISSUE THREAD

**Issue by andreasarf** [beekeeper-studio/beekeeper-studio#2636]
With this new update my queries gone. so sad. I have spent some money to subscribe, but still got treatment like this. it's not first though.

**Comment by rathboma** [comment]
Hey! Any errors in the terminal? Help - show developer tools.

It won't be gone gone, possible 5.0 has a bug that isn't displaying it, well figure it out!

**Comment by rathboma** [comment]
Any screenshot or any information you can give to help us replicate the issue will help a bunch.

**Comment by azmy60** [comment]
I can reliably replicate this. I'm gonna put up a PR.

**Comment by azmy60** [comment]
So yeah, as @rathboma said, we still have the queries in the database, but they're not displayed in the text editor somehow.

@andreasarf In the meantime, you still can see your saved queries by accessing Beekeeper Studio's database in your system, so please take a look at this -> https://docs.beekeeperstudio.io/support/data-location/ . The saved queries will be under the `favorite_query` table.

**Comment by JelleVanDerMeulen** [comment]
I have the same issue. After the update I opened a saved query. The content of the tab was empty. After a restart of the application al tabs were empty too. Looks like all data from the beekeeper database is not shown in a tab.

**Comment by JelleVanDerMeulen** [comment]
***@***.***
***@***.***

These are the errors in my console.

De 'favorite_queries' table contains my queries. The data is still present.




Van: Matthew Rathbone ***@***.***>
Datum: woensdag, 11 december 2024 om 16:49
Aan: beekeeper-studio/beekeeper-studio ***@***.***>
CC: Jelle van der Meulen ***@***.***>, Mention ***@***.***>
Onderwerp: Re: [beekeeper-studio/beekeeper-studio] BUG: Saved queries gone again (Issue #2636)

@JelleVanDerMeulen<https://github.com/JelleVanDerMeulen> can you do a couple of things for me:

  1.  Any errors in the dev console? Help -> show developer tools
  2.  If you query the beekeeper database, are they there? help -> add beekeeper's database, then connect and look in the 'favorite_queries' table

The more information / screenshots you can provide the quicker we can get this fixed!

**Comment by rathboma** [comment]
Hey! Can you add the images directly to GitHub? They didn't work properly when coming from email

**Comment by JelleVanDerMeulen** [comment]
[beekeeper.log](https://github.com/user-attachments/files/18099966/beekeeper.log)
Here is a complete log of the developer console. 
Steps:
- Start beekeeper
- Open connection to localhost
- Systeem opened multiple tabs and table views. 
   Current tab shows SQL statements of the closing-state of the application.
- Switch to another tab. 
   2nd tab is empty. Only the first opened tab has content. All other tabs are empty. The system asks if you want to save the content when you close an empty tab.

**Comment by JelleVanDerMeulen** [comment]
version 5.0.7 seems to work. Thnx
