### ISSUE TITLE
BUG: JSON in right sidebar content is not being updated

### ISSUE THREAD

**Issue by liborkom** [beekeeper-studio/beekeeper-studio#2639]
**Describe the bug**
I seem to be having an issue with the new right sidebar feature displaying the row data in JSON format.

Firstly, when switching focus from one row to another, most of the data seem to be updated just fine. However, when I switch focus to another row, the incremental id column does not update, as shown on the screenshots below.
<img width="636" alt="image" src="https://github.com/user-attachments/assets/48f1b348-8e53-49cc-b69a-d0604a4e83cc">
<img width="498" alt="image" src="https://github.com/user-attachments/assets/8aa4ba35-96f9-49e2-9b43-2b15fd693344">
This happens when I focus on a row, then change focus to another row. On the third click on any row, the id updates correctly to that row's id. After that, the behaviour repeats (when I click on another row, the ID again does not change).

Secondly, whenever I update some data in the row, the JSON does not update with it, and the only way to fix that seems to be to close the opened table view and reopen it.

**To Reproduce**
1. Open any table that has incremental ids (not sure if it affects anything else).
2. Click on a row with the right side bar opened.
3. Click on the row below it.
4. See that the id attribute value in the side bar does not change.

Steps for my second issue related to the applying changes after updating some data:
1. Open any table.
2. Click on a row with the side bar opened (although whether side bard is opened initially or not does not seem to have any effect).
3. Update some data in the row (or any other row, no changes seem to be applied until you close and reopen the table).
4. See that the data in the json did not change accordingly.
5. Try closing the table and opening it again. After this, the data in the JSON should reflect the real data.

**Expected behavior**
When I switch from one row to another, I expect all the data in the JSON to be updated accordingly. Also, when I apply some changes to a row, I expect the changes to take effect in the JSON as well.

**Version Information (please complete the following information):**
 - OS: macOS Sequoia
 - App Version: 5.0.6
 - Database type and version: mysql 9.0.1

**Comment by mybabysexy** [comment]
problem fixed in the newest update. However, there is a bug:
- Open a table and filter by id so there is only 1 record in the view
- Update a field and save
- JSON in the right sidebar does not update the newest value, even after several refresh

**Comment by azmy60** [comment]
@mybabysexy yeah, that's a really really good catch. Thank you for reporting that! I'm gonna make a new ticket and include that and another one I found.
