### ISSUE TITLE
BUG: upgrade to 5.0.6 lost saved state

### ISSUE THREAD

**Issue by jcbradfield** [beekeeper-studio/beekeeper-studio#2653]
**Describe the bug**
My system upgrade (Xubuntu 20.04, getting beekeeper from https://deb.beekeeperstudio.io stable main) has just upgraded beekeeper to 5.0.6. On starting up, my several saved tabs are there, but all the content is gone. (I had  several carefully crafted queries:( ) Is this expected?

**To Reproduce**
Probably reproducible by downgrading and reupgrading, but that's a lot of work.

**Expected behavior**
State preserved over upgrade.

**Version Information (please complete the following information):**
 - OS: Xubuntu 20.04
 - 5.0.6
 - Mariadb (but irrelevant, probably)

**Additional context**
Anything else you think might be helpful

**Comment by not-night-but** [comment]
@jcbradfield not to worry! Your queries are still there, this was just a bug in the query editor. The bug fix is already out, so you should just need to upgrade

**Comment by jcbradfield** [comment]
Thank you!
