### ISSUE TITLE
BUG: 5.0.8 Cannot read properties of null (reading 'byteLength')

### ISSUE THREAD

**Issue by tomonetml** [beekeeper-studio/beekeeper-studio#2655]
**Describe the bug**
View data of a specific Mariadb table raise the error in topic

**To Reproduce**
Double click on the affected table and wait for the error to show

**Screenshots / Gifs**
![immagine](https://github.com/user-attachments/assets/d8134c22-c848-4b6c-bf12-e48edb06824e)

**Version Information (please complete the following information):**
 - OS: Windows 10
 - App Version 5.0.8
 - Database type and version 10.6.19-MariaDB-deb11-log

**Additional context**
Opening this table in previuos versions < 5.0 of Beekeper Studio was fine. Still can't get why it's happening.
Some logging:
`index-BaC_5bMO.js:3235 08:50:45.949 (TabModule) › saving tab {tabType: 'table', title: 'dk_orders_shippings', tableName: 'dk_orders_shippings', schemaName: undefined, entityType: 'table', …}
index-BaC_5bMO.js:3235 08:50:45.949 (renderer/utilityconnection) › SENDING REQUEST FOR NAME, ID:  appdb/tabs/save caf4a8b1-6359-4a88-9a3b-eaf1ed1d896d
index-BaC_5bMO.js:3235 08:50:45.952 (renderer/utilityconnection) › RECEIVED MESSAGE:  reply {id: 'caf4a8b1-6359-4a88-9a3b-eaf1ed1d896d', type: 'reply', data: {…}}
index-BaC_5bMO.js:3235 08:50:45.952 (renderer/utilityconnection) › RECEIVED REPLY FOR REQUEST ID:  caf4a8b1-6359-4a88-9a3b-eaf1ed1d896d
index-BaC_5bMO.js:3235 08:50:45.975 (renderer/utilityconnection) › SENDING REQUEST FOR NAME, ID:  appdb/tabs/save d79502e7-5e39-4450-a828-8362ff3954b2
index-BaC_5bMO.js:3235 08:50:45.977 (renderer/utilityconnection) › SENDING REQUEST FOR NAME, ID:  conn/listTableColumns 71e31e74-ec89-4978-9129-36fc0569324f
index-BaC_5bMO.js:3235 08:50:45.990 (renderer/utilityconnection) › RECEIVED MESSAGE:  reply {id: 'd79502e7-5e39-4450-a828-8362ff3954b2', type: 'reply', data: Array(2)}
index-BaC_5bMO.js:3235 08:50:45.991 (renderer/utilityconnection) › RECEIVED REPLY FOR REQUEST ID:  d79502e7-5e39-4450-a828-8362ff3954b2
index-BaC_5bMO.js:3235 08:50:45.991 (renderer/utilityconnection) › RECEIVED MESSAGE:  reply {id: '71e31e74-ec89-4978-9129-36fc0569324f', type: 'reply', data: Array(42)}
index-BaC_5bMO.js:3235 08:50:45.991 (renderer/utilityconnection) › RECEIVED REPLY FOR REQUEST ID:  71e31e74-ec89-4978-9129-36fc0569324f
index-BaC_5bMO.js:3235 08:50:46.005 (renderer/utilityconnection) › SENDING REQUEST FOR NAME, ID:  conn/getTableKeys 9f9cf793-047d-4e60-80ab-be840ceffd6b
index-BaC_5bMO.js:3235 08:50:46.051 (renderer/utilityconnection) › RECEIVED MESSAGE:  reply {id: '9f9cf793-047d-4e60-80ab-be840ceffd6b', type: 'reply', data: Array(0)}
index-BaC_5bMO.js:3235 08:50:46.051 (renderer/utilityconnection) › RECEIVED REPLY FOR REQUEST ID:  9f9cf793-047d-4e60-80ab-be840ceffd6b
index-BaC_5bMO.js:3235 08:50:46.051 (renderer/utilityconnection) › SENDING REQUEST FOR NAME, ID:  conn/getPrimaryKeys fd9b55fe-c8d4-4a6e-bc4c-75c98878c968
index-BaC_5bMO.js:3235 08:50:46.058 (renderer/utilityconnection) › RECEIVED MESSAGE:  reply {id: 'fd9b55fe-c8d4-4a6e-bc4c-75c98878c968', type: 'reply', data: Array(1)}
index-BaC_5bMO.js:3235 08:50:46.059 (renderer/utilityconnection) › RECEIVED REPLY FOR REQUEST ID:  fd9b55fe-c8d4-4a6e-bc4c-75c98878c968
index-BaC_5bMO.js:3185 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'verticalFillMode')
    at RowManager.adjustTableSize (index-BaC_5bMO.js:3185:10651)
    at RowManager._wipeElements (index-BaC_5bMO.js:3185:79)
    at RowManager._setDataActual (index-BaC_5bMO.js:3182:44969)
    at index-BaC_5bMO.js:3182:44877
    at new Promise (<anonymous>)
    at RowManager.setData (index-BaC_5bMO.js:3182:44576)
    at DataLoader.load (index-BaC_5bMO.js:3185:20116)
    at TabulatorFull.setData (index-BaC_5bMO.js:3186:839)
    at m.filters (index-BaC_5bMO.js:3552:11085)
    at invokeWithErrorHandling (index-BaC_5bMO.js:5:31157)
adjustTableSize @ index-BaC_5bMO.js:3185
_wipeElements @ index-BaC_5bMO.js:3185
_setDataActual @ index-BaC_5bMO.js:3182
(anonymous) @ index-BaC_5bMO.js:3182
setData @ index-BaC_5bMO.js:3182
load @ index-BaC_5bMO.js:3185
setData @ index-BaC_5bMO.js:3186
filters @ index-BaC_5bMO.js:3552
invokeWithErrorHandling @ index-BaC_5bMO.js:5
n.run @ index-BaC_5bMO.js:5
flushSchedulerQueue @ index-BaC_5bMO.js:5
(anonymous) @ index-BaC_5bMO.js:5
flushCallbacks @ index-BaC_5bMO.js:5
Promise.then (async)
timerFunc @ index-BaC_5bMO.js:5
nextTick @ index-BaC_5bMO.js:5
queueWatcher @ index-BaC_5bMO.js:5
n.update @ index-BaC_5bMO.js:5
n.notify @ index-BaC_5bMO.js:5
set @ index-BaC_5bMO.js:5
sharedPropertyDefinition.set @ index-BaC_5bMO.js:5
initialize @ index-BaC_5bMO.js:3556
await in initialize (async)
shouldInitialize @ index-BaC_5bMO.js:3552
invokeWithErrorHandling @ index-BaC_5bMO.js:5
n.run @ index-BaC_5bMO.js:5
flushSchedulerQueue @ index-BaC_5bMO.js:5
(anonymous) @ index-BaC_5bMO.js:5
flushCallbacks @ index-BaC_5bMO.js:5
Promise.then (async)
timerFunc @ index-BaC_5bMO.js:5
nextTick @ index-BaC_5bMO.js:5
queueWatcher @ index-BaC_5bMO.js:5
n.update @ index-BaC_5bMO.js:5
n.notify @ index-BaC_5bMO.js:5
set @ index-BaC_5bMO.js:5
setActive @ index-BaC_5bMO.js:3274
(anonymous) @ index-BaC_5bMO.js:3232
(anonymous) @ index-BaC_5bMO.js:3232
(anonymous) @ index-BaC_5bMO.js:3232
Store._withCommit @ index-BaC_5bMO.js:3232
Store.commit @ index-BaC_5bMO.js:3232
Store.commit @ index-BaC_5bMO.js:3232
o.commit @ index-BaC_5bMO.js:3232
setActive @ index-BaC_5bMO.js:3274
(anonymous) @ index-BaC_5bMO.js:3232
Store.dispatch @ index-BaC_5bMO.js:3232
Store.dispatch @ index-BaC_5bMO.js:3232
setActiveTab @ index-BaC_5bMO.js:3561
addTab @ index-BaC_5bMO.js:3561
await in addTab (async)
openTable @ index-BaC_5bMO.js:3561
invokeWithErrorHandling @ index-BaC_5bMO.js:5
n.$emit @ index-BaC_5bMO.js:5
openTable @ index-BaC_5bMO.js:3444
dblclick @ index-BaC_5bMO.js:3444
invokeWithErrorHandling @ index-BaC_5bMO.js:5
r @ index-BaC_5bMO.js:5
l._wrapper @ index-BaC_5bMO.js:5
index-BaC_5bMO.js:3185 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'verticalFillMode')
    at RowManager.adjustTableSize (index-BaC_5bMO.js:3185:10651)
    at RowManager._wipeElements (index-BaC_5bMO.js:3185:79)
    at RowManager._setDataActual (index-BaC_5bMO.js:3182:44969)
    at index-BaC_5bMO.js:3182:44877
    at new Promise (<anonymous>)
    at RowManager.setData (index-BaC_5bMO.js:3182:44576)
    at DataLoader.load (index-BaC_5bMO.js:3185:20116)
    at TabulatorFull.setData (index-BaC_5bMO.js:3186:839)
    at m.filters (index-BaC_5bMO.js:3552:11085)
    at invokeWithErrorHandling (index-BaC_5bMO.js:5:31157)
adjustTableSize @ index-BaC_5bMO.js:3185
_wipeElements @ index-BaC_5bMO.js:3185
_setDataActual @ index-BaC_5bMO.js:3182
(anonymous) @ index-BaC_5bMO.js:3182
setData @ index-BaC_5bMO.js:3182
load @ index-BaC_5bMO.js:3185
setData @ index-BaC_5bMO.js:3186
filters @ index-BaC_5bMO.js:3552
invokeWithErrorHandling @ index-BaC_5bMO.js:5
n.run @ index-BaC_5bMO.js:5
flushSchedulerQueue @ index-BaC_5bMO.js:5
(anonymous) @ index-BaC_5bMO.js:5
flushCallbacks @ index-BaC_5bMO.js:5
Promise.then (async)
timerFunc @ index-BaC_5bMO.js:5
nextTick @ index-BaC_5bMO.js:5
queueWatcher @ index-BaC_5bMO.js:5
n.update @ index-BaC_5bMO.js:5
n.notify @ index-BaC_5bMO.js:5
set @ index-BaC_5bMO.js:5
sharedPropertyDefinition.set @ index-BaC_5bMO.js:5
initialize @ index-BaC_5bMO.js:3556
await in initialize (async)
shouldInitialize @ index-BaC_5bMO.js:3552
invokeWithErrorHandling @ index-BaC_5bMO.js:5
n.run @ index-BaC_5bMO.js:5
flushSchedulerQueue @ index-BaC_5bMO.js:5
(anonymous) @ index-BaC_5bMO.js:5
flushCallbacks @ index-BaC_5bMO.js:5
Promise.then (async)
timerFunc @ index-BaC_5bMO.js:5
nextTick @ index-BaC_5bMO.js:5
queueWatcher @ index-BaC_5bMO.js:5
n.update @ index-BaC_5bMO.js:5
n.notify @ index-BaC_5bMO.js:5
set @ index-BaC_5bMO.js:5
setActive @ index-BaC_5bMO.js:3274
(anonymous) @ index-BaC_5bMO.js:3232
(anonymous) @ index-BaC_5bMO.js:3232
(anonymous) @ index-BaC_5bMO.js:3232
Store._withCommit @ index-BaC_5bMO.js:3232
Store.commit @ index-BaC_5bMO.js:3232
Store.commit @ index-BaC_5bMO.js:3232
o.commit @ index-BaC_5bMO.js:3232
setActive @ index-BaC_5bMO.js:3274
(anonymous) @ index-BaC_5bMO.js:3232
Store.dispatch @ index-BaC_5bMO.js:3232
Store.dispatch @ index-BaC_5bMO.js:3232
setActiveTab @ index-BaC_5bMO.js:3561
addTab @ index-BaC_5bMO.js:3561
await in addTab (async)
openTable @ index-BaC_5bMO.js:3561
invokeWithErrorHandling @ index-BaC_5bMO.js:5
n.$emit @ index-BaC_5bMO.js:5
openTable @ index-BaC_5bMO.js:3444
dblclick @ index-BaC_5bMO.js:3444
invokeWithErrorHandling @ index-BaC_5bMO.js:5
r @ index-BaC_5bMO.js:5
l._wrapper @ index-BaC_5bMO.js:5
index-BaC_5bMO.js:3235 08:50:46.130 (TableTable) › fetch params {filter: Array(0), page: 1, size: 100, sort: Array(1)}
index-BaC_5bMO.js:3235 08:50:46.131 (TableTable) › filters [__ob__: n]
index-BaC_5bMO.js:3235 08:50:46.131 (renderer/utilityconnection) › SENDING REQUEST FOR NAME, ID:  conn/selectTop 47f0e2d8-4fea-4151-a095-23956860d2b9
index-BaC_5bMO.js:3556 data fetch error TypeError: Cannot read properties of null (reading 'byteLength')
    at Object.serialize (index.html/C:\Users\lolol\AppData\Local\Programs\beekeeper-studio\resources\app.asar\dist\utility.js:381338:43)
    at index.html/C:\Users\lolol\AppData\Local\Programs\beekeeper-studio\resources\app.asar\dist\utility.js:379868:31
    at Array.forEach (<anonymous>)
    at MariaDBClient.serializeQueryResult (index.html/C:\Users\lolol\AppData\Local\Programs\beekeeper-studio\resources\app.asar\dist\utility.js:379867:40)
    at MariaDBClient.selectTop (index.html/C:\Users\lolol\AppData\Local\Programs\beekeeper-studio\resources\app.asar\dist\utility.js:381770:29)
    at process.processTicksAndRejections (VM33 task_queues:95:5)
    at async conn/selectTop (index.html/C:\Users\lolol\AppData\Local\Programs\beekeeper-studio\resources\app.asar\dist\utility.js:395717:12)
(anonymous) @ index-BaC_5bMO.js:3556
await in (anonymous) (async)
(anonymous) @ index-BaC_5bMO.js:3556
dataFetch @ index-BaC_5bMO.js:3556
sendRequest @ index-BaC_5bMO.js:3165
requestData @ index-BaC_5bMO.js:3165
(anonymous) @ index-BaC_5bMO.js:3185
_chain @ index-BaC_5bMO.js:3185
chain @ index-BaC_5bMO.js:3165
load @ index-BaC_5bMO.js:3185
_loadInitialData @ index-BaC_5bMO.js:3185
_create @ index-BaC_5bMO.js:3185
(anonymous) @ index-BaC_5bMO.js:3185
setTimeout (async)
ll @ index-BaC_5bMO.js:3185
TabulatorFull @ index-BaC_5bMO.js:3186
tabulatorForTableData @ index-BaC_5bMO.js:3472
initialize @ index-BaC_5bMO.js:3556
await in initialize (async)
shouldInitialize @ index-BaC_5bMO.js:3552
invokeWithErrorHandling @ index-BaC_5bMO.js:5
n.run @ index-BaC_5bMO.js:5
flushSchedulerQueue @ index-BaC_5bMO.js:5
(anonymous) @ index-BaC_5bMO.js:5
flushCallbacks @ index-BaC_5bMO.js:5
Promise.then (async)
timerFunc @ index-BaC_5bMO.js:5
nextTick @ index-BaC_5bMO.js:5
queueWatcher @ index-BaC_5bMO.js:5
n.update @ index-BaC_5bMO.js:5
n.notify @ index-BaC_5bMO.js:5
set @ index-BaC_5bMO.js:5
setActive @ index-BaC_5bMO.js:3274
(anonymous) @ index-BaC_5bMO.js:3232
(anonymous) @ index-BaC_5bMO.js:3232
(anonymous) @ index-BaC_5bMO.js:3232
Store._withCommit @ index-BaC_5bMO.js:3232
Store.commit @ index-BaC_5bMO.js:3232
Store.commit @ index-BaC_5bMO.js:3232
o.commit @ index-BaC_5bMO.js:3232
setActive @ index-BaC_5bMO.js:3274
(anonymous) @ index-BaC_5bMO.js:3232
Store.dispatch @ index-BaC_5bMO.js:3232
Store.dispatch @ index-BaC_5bMO.js:3232
setActiveTab @ index-BaC_5bMO.js:3561
addTab @ index-BaC_5bMO.js:3561
await in addTab (async)
openTable @ index-BaC_5bMO.js:3561
invokeWithErrorHandling @ index-BaC_5bMO.js:5
n.$emit @ index-BaC_5bMO.js:5
openTable @ index-BaC_5bMO.js:3444
dblclick @ index-BaC_5bMO.js:3444
invokeWithErrorHandling @ index-BaC_5bMO.js:5
r @ index-BaC_5bMO.js:5
l._wrapper @ index-BaC_5bMO.js:5
index-BaC_5bMO.js:3185 Data Load Error:  Cannot read properties of null (reading 'byteLength')
(anonymous) @ index-BaC_5bMO.js:3185
Promise.catch (async)
load @ index-BaC_5bMO.js:3185
_loadInitialData @ index-BaC_5bMO.js:3185
_create @ index-BaC_5bMO.js:3185
(anonymous) @ index-BaC_5bMO.js:3185
setTimeout (async)
ll @ index-BaC_5bMO.js:3185
TabulatorFull @ index-BaC_5bMO.js:3186
tabulatorForTableData @ index-BaC_5bMO.js:3472
initialize @ index-BaC_5bMO.js:3556
await in initialize (async)
shouldInitialize @ index-BaC_5bMO.js:3552
invokeWithErrorHandling @ index-BaC_5bMO.js:5
n.run @ index-BaC_5bMO.js:5
flushSchedulerQueue @ index-BaC_5bMO.js:5
(anonymous) @ index-BaC_5bMO.js:5
flushCallbacks @ index-BaC_5bMO.js:5
Promise.then (async)
timerFunc @ index-BaC_5bMO.js:5
nextTick @ index-BaC_5bMO.js:5
queueWatcher @ index-BaC_5bMO.js:5
n.update @ index-BaC_5bMO.js:5
n.notify @ index-BaC_5bMO.js:5
set @ index-BaC_5bMO.js:5
setActive @ index-BaC_5bMO.js:3274
(anonymous) @ index-BaC_5bMO.js:3232
(anonymous) @ index-BaC_5bMO.js:3232
(anonymous) @ index-BaC_5bMO.js:3232
Store._withCommit @ index-BaC_5bMO.js:3232
Store.commit @ index-BaC_5bMO.js:3232
Store.commit @ index-BaC_5bMO.js:3232
o.commit @ index-BaC_5bMO.js:3232
setActive @ index-BaC_5bMO.js:3274
(anonymous) @ index-BaC_5bMO.js:3232
Store.dispatch @ index-BaC_5bMO.js:3232
Store.dispatch @ index-BaC_5bMO.js:3232
setActiveTab @ index-BaC_5bMO.js:3561
addTab @ index-BaC_5bMO.js:3561
await in addTab (async)
openTable @ index-BaC_5bMO.js:3561
invokeWithErrorHandling @ index-BaC_5bMO.js:5
n.$emit @ index-BaC_5bMO.js:5
openTable @ index-BaC_5bMO.js:3444
dblclick @ index-BaC_5bMO.js:3444
invokeWithErrorHandling @ index-BaC_5bMO.js:5
r @ index-BaC_5bMO.js:5
l._wrapper @ index-BaC_5bMO.js:5
index-BaC_5bMO.js:3235 08:50:46.158 (renderer/utilityconnection) › RECEIVED MESSAGE:  error {id: '47f0e2d8-4fea-4151-a095-23956860d2b9', type: 'error', stack: 'TypeError: Cannot read properties of null (reading…dio\\resources\\app.asar\\dist\\utility.js:395717:12)', error: "Cannot read properties of null (reading 'byteLength')"}
index-BaC_5bMO.js:3235 08:50:46.158 (renderer/utilityconnection) › GOT ERROR BACK FOR REQUEST ID:  47f0e2d8-4fea-4151-a095-23956860d2b9
(anonymous) @ index-BaC_5bMO.js:3235
setTimeout (async)
writeFn @ index-BaC_5bMO.js:3235
e @ index-BaC_5bMO.js:3235
processMessage @ index-BaC_5bMO.js:3235
logData @ index-BaC_5bMO.js:3235
s.<computed> @ index-BaC_5bMO.js:3235
port.onmessage @ index-BaC_5bMO.js:3437
`

**Comment by iatharva** [comment]
Getting the same error in MySQL Database as well

**Comment by wouthoekstra** [comment]
Might this be the same bug as I am encountering? https://github.com/beekeeper-studio/beekeeper-studio/issues/2640 In my case it seems to be related to the collation of the tables I am looking at.

**Comment by tomonetml** [comment]
> Might this be the same bug as I am encountering? #2640 In my case it seems to be related to the collation of the tables I am looking at.

Definetely, i checked and the table has utf8mb4_general_ci collation but it has a column that has utf8mb4_bin.

**Comment by tomonetml** [comment]
#2640 duplicate
