### ISSUE TITLE
cmd-a to select an entire value in a form field

### ISSUE THREAD

**Issue by whistlerbrk** [beekeeper-studio/beekeeper-studio#267]
I think this is an "enhancement".

In Quick Connect if you click into a field and attempt to select the entire value of the field with cmd-A (macos) it will not work, you'll have to tab out and in to get the full field selected by default.

**Comment by UtechtDustin** [comment]
Works fine on Ubuntu, looks like a os depend issue.

**Comment by rathboma** [comment]
Totally a bug! This is an MacOS specific issue because Mac disables shortcuts unless you specifically add them to the menu (which I forgot, oops).

Will fix for the next release.

👋  @whistlerbrk

**Comment by rathboma** [comment]
Should be fixed in Master now
