### ISSUE TITLE
Scalable text and or interface

### ISSUE THREAD

**Issue by iKlsR** [beekeeper-studio/beekeeper-studio#27]
Can we scale individual text or the entire UI akin to how VS Code does it? There is a lot of wasted space at 4k and the small text can be hard to discern.

**Comment by iKlsR** [comment]
This could be seen as a band-aid of sorts for #26

**Comment by rathboma** [comment]
We'll think about this, we might need to pump up the default text sizes across the board.

Do you have a screenshot of how it looks on your 4k monitor?

**Comment by iKlsR** [comment]
![](https://i.imgur.com/TvBKNxS.jpg)

it doesn't look bad but could be bigger, I've unwillingly become part of a group that has to avoid eye straining interfaces, heh. A global scale value would be nice.

**Comment by rathboma** [comment]
Oh yeah that's interesting. I'm guessing you're not using OS-level hi-dpi scaling?

**Comment by iKlsR** [comment]
@rathboma Actually yes, I'm at 150%.

**Comment by ghstng** [comment]
v1.6.10

**Comment by mitas** [comment]
You can run `beekeeper` with argument `--force-device-scale-factor=1.5 `
