### ISSUE TITLE
Context menu options on query window or query tab click

### ISSUE THREAD

**Issue by mohamed-azhar** [beekeeper-studio/beekeeper-studio#270]
- **Context menu options on right click to the query tab**
Pin one or more query windows 
Closing options like (close, close all, close all but this, close all but pinned)
Option to open file containing folder

- **Context menu options on right click to the query editor window**
Allow to format the SQL queries

**Comment by rathboma** [comment]
So queries are stored in the database (not files + folders), so that one doesn't work (we have a good reason for this which will become clear in an upcoming release), but all the others should be good.

**Comment by rathboma** [comment]
Some of these items are now merged! #285

**Comment by rathboma** [comment]
going to close this. Def more stuff we want to do, but the core is there now.
