### ISSUE TITLE
Add a button to select results

### ISSUE THREAD

**Issue by 2prog** [beekeeper-studio/beekeeper-studio#280]
<img width="167" alt="CopyAll" src="https://user-images.githubusercontent.com/69429235/89736687-78b97f80-da6b-11ea-8856-bee8fb634eb1.PNG">

So we can select all than copy to clipboard instead of exporting results as a file.

**Comment by rathboma** [comment]
Good idea! I like using this functionality too

**Comment by rathboma** [comment]
The tabulator API supports this natively, so we could add a button as a short term solution.

http://tabulator.info/docs/4.0/clipboard#:~:text=The%20copy%20selector%20is%20a,table%20to%20the%20clipboard%20(default)

Bonus points: add a way to select multiple cells or rows for copying

**Comment by rathboma** [comment]
@2prog can you test something:

1. Click a header of the table
2. Press ctrl-c
3. Does this copy the table?

**Comment by 2prog** [comment]
@rathboma Clicking on header and than ctrl-c doesn't copy. The only way to copy is to click and drag, but this copies the data into one column in Excel, so it's not really functional.

**Comment by UtechtDustin** [comment]
I could do this issue.

The question is what is the best solution to select rows, as we also need a row selection for row deletion.
it seems the `selectable` option of the tabulator is not working with the editor option, that means wo have to add a column which is only for selecting the rows or as alternative we would add a checkbox to the columns start.

What do you think ?

**Comment by rathboma** [comment]
I think we should punt on this for a little bit until after the editing branch. I don't like working on several issues in the same part of the codebase at the same time -- just asking for horrible merge conflicts :-)

**Comment by rathboma** [comment]
I added a 'copy to clipboard' export in d85e08bf19448faaeee1544d162e179d693cafab!

That solves this issue for now.

**Comment by UtechtDustin** [comment]
@rathboma Do you have to select the data first or something like that ?
The `copy to clipboard` export dont work for me.

**Comment by rathboma** [comment]
Hmm, it worked in testing. I'll see if I broke something by mistake. I'll make sure it works before release
