### ISSUE TITLE
Reuse opening tabs instead of creating new ones

### ISSUE THREAD

**Issue by lqmanh** [beekeeper-studio/beekeeper-studio#281]
When opening a table, I think it's a good idea to switch to the existing tab, instead of creating a new one.
Even better, we can handle middle clicks to open in new tabs like browsers and other apps, and/or handle right clicks to open context menu with an option to open in new tabs.

**Comment by rathboma** [comment]
I was on the fence about this when I implemented the current behavior, but there are a few reasons we're not doing this, and one big way to solve it:
1. It's nice to have two distinct views of a table (if you're looking for something)
2. We're working on foreign key go-to functionality, which requires multiple table-tabs
3. We're going to implement a global-search where you can type a table name to go to it, this will allow going to an existing tab.

I also want behavior to be consistent with the open in tab button -- I don't want to do anything 'magic' depending on context.

I'll close for now, but if more folks have this issue we can maybe add an app setting for it.
