### ISSUE TITLE
how modify table content on beekeep-studio ?

### ISSUE THREAD

**Issue by silvesterwali** [beekeeper-studio/beekeeper-studio#283]
i have install beekeeper-studio on my ubuntu desktop but i cannot modify data inside table .
![image](https://user-images.githubusercontent.com/40487188/90208137-aa8b6700-de1a-11ea-9b3c-0c6a057f9628.png)

**Comment by rathboma** [comment]
I just merged a change tonight to enable this! :muscle: See PR #276 

Release should be out soon with this feature (and others)
