### ISSUE TITLE
SSH Tunnel GUI switch in wrong state

### ISSUE THREAD

**Issue by TravellerSam** [beekeeper-studio/beekeeper-studio#290]
A saved connection with an SSH tunnel configuration shows the 'SSH Tunnel' switch state in wrong position: as switched off. 

Version used: 1.6.11 on macOS 10.15.6 and Kubuntu 20.04.1 as AppImage.

![BeeKeeper ssh tunnel switch](https://user-images.githubusercontent.com/872730/90314814-e0ae1100-df16-11ea-8d9e-aae53cdc4b1f.png)

**Comment by UtechtDustin** [comment]
How do you opened the SSH Tunnel configuration ?
The normal way is to toggle the switch (marked in your screenshot).

**Comment by TravellerSam** [comment]
When configuring the connection the switch is fine (off and on in correct states). Just when the connection is configured with a tunnel and saved the switch gets drunk. :)

**Comment by UtechtDustin** [comment]
Oh okay, can reproduce it on Ubuntu 20.04!
