### ISSUE TITLE
Request: Allow not to set a connection's default database

### ISSUE THREAD

**Issue by TravellerSam** [beekeeper-studio/beekeeper-studio#292]
When configuring a Postgresql connection and leaving out the Default Database field, the app tries connect to a database with a name of the configured username, giving a red error message:

"Database >>_User's name_<< doesn't exist"

For a PSQL connection I set the field to `postgres`, but I'm not very fond of this solution, as I don't need that database being open on connection. 

Maybe my workflow is too specific, but as I work with multiple databases and switch between them anyway, it'd be nice to connect to the server and have the left-hand pane empty, without any database loaded.

**Comment by UtechtDustin** [comment]
Im not able to reproduce that issue (Ubuntu 20.04).
I think there is also only one use for the os username.
https://github.com/beekeeper-studio/beekeeper-studio/blob/dfb301fe33e5739ec3e15771eae7d9357f6c5904/src/lib/db/clients/postgresql.js#L732-L736
If no username is set for the connection we use the os username.

I normaly dont use postgresql, is there any "test" or "open" database where you can write how we can reproduce that issue ?

**Comment by TravellerSam** [comment]
I'm talking about the default _database_ name, not of the user. It has to be filled in, otherwise the connection doesn't take place. The application assumes that the default database name equals connection's user name.

As I workaround I put the standard `postgres` database name. It just would be more flexible if it wouldn't have to be set at all.

The issue is same for me in both macOS 10.15 and Ubuntu 20.04 (AppImage) versions.

**Comment by UtechtDustin** [comment]
Oh okay i understand, i submitted a PR (#293) which automaticly use the `postgres` database instead of the username (if no default database is set).
