### ISSUE TITLE
Clicking "END" remove focus from editing field

### ISSUE THREAD

**Issue by geovannimp** [beekeeper-studio/beekeeper-studio#295]
First, I was looking for a good sql editor for a long time and today I found this amazing project. Thanks for all your great working.

As I tested de editor, I missed the feature to edit fields but right after that i found that it was already merged. So I downloaded the master branch to test and its working really well, but when I'm editing a field and click 'END' the editor remove the focus from the field instead of moving the cursor to the end of the text.
Is this behavior expected?

**Comment by rathboma** [comment]
It is not. I'm fixing a bunch of funky stuff like that before release. Thanks for bringing this one up specifically.

Looks like I'll have to either totally override keybindings for tabulator or patch it. I'll get it fixed before release though :-)
