### ISSUE TITLE
[Ubuntu] No ssl certificates fields

### ISSUE THREAD

**Issue by ejf-coders51** [beekeeper-studio/beekeeper-studio#297]
Hi,

on ubuntu snap version 1.6.10 when i press enable ssl, no field about that appear. How i can set the certificates path?
![image](https://user-images.githubusercontent.com/67055839/90624420-371d9700-e218-11ea-8118-6a73c87182bc.png)

**Comment by UtechtDustin** [comment]
Its currently not possible, see #109

**Comment by rathboma** [comment]
Sorry this isn't part of the build yet :-/.

It really just requires some solid time to sit down and test this with all the different database types.

**Comment by rathboma** [comment]
Going to close as a dupuplicate of #89
