### ISSUE TITLE
Enable Active Directory Authentication for SQL Server (and other dbs?)

### ISSUE THREAD

**Issue by lordrak007** [beekeeper-studio/beekeeper-studio#30]
Hello,
i have tried connect to sqlserver using AD login but it failed.
How to login using domain account?
Thanks

**Comment by rathboma** [comment]
Hey! Right now I don't think this is possible with Beekeeper Studio. It's on our radar though.

**Comment by rathboma** [comment]
@lordrak007 can you try version 1.4?

**Comment by lordrak007** [comment]
Hello,
thanks for AD integration. But it not working yet.
When i enter all parameters and did test its say "Connection looks good", then i have clicked save. When i tried press Test button again (or connect) i am getting theese errors:
Error establishing connection
The "config.options.database" property must be of type string.
Failed to connect to cewsql402:1433 - Cannot call write after a stream was destroyed
Thanks

**Comment by rathboma** [comment]
@lordrak007 did you specify a 'defaultDatabase'?
