### ISSUE TITLE
feature: Support database connections using a socket path rather than a host and port

### ISSUE THREAD

**Issue by ejdanderson** [beekeeper-studio/beekeeper-studio#300]
It looks like there are hints at connecting directly with a socket path https://github.com/beekeeper-studio/beekeeper-studio/blob/9ff3131030057364f31f3034677fc0f6a9bd48b5/src/lib/connection-provider.js#L23 

https://github.com/beekeeper-studio/beekeeper-studio/blob/2521b8c66721c7e634a006a992bad4e4f1f6153e/src/lib/db/server.js#L22

But there does not appear to be anything in the UI to indicate how you'd go about doing this. Nor where one might be able to create their own config file to manually define this.

**Comment by Saganic** [comment]
+1 This would be a great feature for us. We currently use the cloud_sql_proxy from Google and I imagine a lot of Google customers would love this.

**Comment by jc00ke** [comment]
Could this supported via the URL with the `host` param without all the UI, at least as a first go? `postgres:///my_database?host=/path/to/postgres/socket/dir`. Or is #312 most of the work but needs to be finished off?

**Comment by Muffinman** [comment]
Ideally you would allow remote socket connections over SSH, that's a perfectly valid method of connecting!

In fact since MariaDB 10.4 [it's now the default](https://mariadb.com/kb/en/authentication-from-mariadb-104/) to only allow root to access using socket auth. Trying to connect as root with a password will fail unless the user has specifically had it's auth plugin set to `mysql_native_password`.

It would seem quite important to support this.

**Comment by azmy60** [comment]
> @ejdanderson yes you are correct, the db libraries should support socket Path connections, but you are right that we haven't yet added that option to the UI.
> 
> Should be a simple feature to add.
> 
> Notes for future self / whoever implements this:
> 
>     * Add a migration to add socketPath to both SavedConnection and UsedConnection
> 
>     * add fields to those two models
> 
>     * integrate the socketpath in the hash, simpleconnectionstring, parse, and fullconnectionstring methods
> 
>     * review each database type in lib/db to see which supports socket connections
> 
>     * add a dropdown to change from host/port to socket path in the connection form (in postgresform, mysqlform, etc)
> 
>     * disable ssh and ssl forms if using socket path
> 
>     * update ConnectionProvider to pass through socketpath

I'm working on it. Thank you for the notes!
