### ISSUE TITLE
App icon is a bit larger - Mac OS

### ISSUE THREAD

**Issue by sensnerd** [beekeeper-studio/beekeeper-studio#302]
Hi, Thank you so much for creating this App. I just found that the app icon is a bit larger than the others, especially  
on Mac OS.  It's not an important issue, but I think its very good for app enhancement. Have a nice day!

Screenshot : 

<img width="860" alt="Screen Shot 2020-08-22 at 23 53 41" src="https://user-images.githubusercontent.com/47457477/90960714-3d409b80-e4d6-11ea-909f-31b117606cbf.png">

**Comment by ghstng** [comment]
rgr

**Comment by juliandavidmr** [comment]
This problem does not occur in macOS Big Sur.

![image](https://user-images.githubusercontent.com/4544102/111054911-69097b80-843e-11eb-9d6f-d79b6a67edee.png)
