### ISSUE TITLE
FEAT: Button to clear history of queries or saved queries  

### ISSUE THREAD

**Issue by mrr07** [beekeeper-studio/beekeeper-studio#305]
An option that allows you to delete queries you no longer need, either individually or as a group

**Comment by rathboma** [comment]
Yes, we should have this functionality.

In the meantime here is a fun workaround:

`Help -> Add Beekeeper's Database`

Then go to the connection manager and connect to `Beekeeper's Database`

Then you can query, delete, or update the history as you see fit :-)

**Comment by rathboma** [comment]
This could be broken into two different PRs:

1. Simple right-click context menu to delete a query from the history / stash

2. A more complex multi-select plus right-click to delete multiple queries
