### ISSUE TITLE
FEAT: View table Structure

### ISSUE THREAD

**Issue by ccrvlh** [beekeeper-studio/beekeeper-studio#310]
**Is your feature request related to a problem? Please describe.**
It's frustrating not have an overview of your tables: column, types, defaults, indexes, fk, collation etc.
Sequel Pro makes this beautifully for MySQL, and Postico does a great job for Postgres

**Describe the solution you'd like**
The option to have the table schema/structure.
Probably could be implemented with double click in the table (instead of the current behaviour of collapsing/expanding fields), or maybe a second small button, right next to "open in new tab".
Another option, would be to have a switch: consider you've opened the table in a new tab, you could have a switch down below: structure/content, it probably would be easier to program.
I have a (very weak) notion of VueJS, so maybe I can help somehow, will dig deeper into the documentation to see if there's anyway I could contribute.
Cheers

**Describe alternatives you've considered**
Other clients: I'll probably stick with Sequel Pro for now (even though is dying) and Postico (even though is free version is very limited)

**Additional context**
Everything looks amazing from what I've seen so far.

**Comment by rathboma** [comment]
💯 

It's on our roadmap, and one of the next features we want to add.

Literally we started this project to create a 'Cross platform and cross-database Sequel Pro', so we'll get there :-).

**Comment by lowercase00** [comment]
@rathboma awesome mate!
Really glad to hear, I've been looking for a project like this for quite a while, really glad that you guys have this vision!

If I might add some other ideas for features, two things come to mind:
1. While using "longtext" to store JSON strings in MySQL, I realised the column automatically resizes to fit the whole content in one line: I have to scroll for ages to the right, maybe have a column width limit by default would be great.
2. I also use Sequel Pro's feature to move columns around a lot, that would be nice also.
3. I really like those small buttons on the bottom left corner of Sequel pro, where you can add tables and see little resumed table information
4. Last, but not least, Sequel Pro's import/export feature is pretty awesome, it would be great to see that as well.
5. And the finish the list, something I've always wanted Sequel Pro to have, but never made it, was the ability to see and mess with ERD Diagram, that would be a total killer.

I know it's a lot of stuff, juts sharing my thoughts using it for the first time, as a heavy Sequel Pro user.
Let me know if you think any of these make sense, if it does I can open specific feature request with more detailed information.

Thanks a lot for the project, really awesome!

**Comment by UtechtDustin** [comment]
@lowercase00 Thank you for the feedback, i can agree your thoughts.
I also searched this project for ages, i also use sequel pro (on work) and currently i would love to use beekeeper on work but there are two features (Table Structur and import/export) missing which i need for my work.

So i hope a lot of ppl. will find this project and help it grow !

**Comment by rathboma** [comment]
@lowercase00 We are going to build all of those things :-).

See #313 for your first point, we can fix that presently.

It takes time to get all those things working, but we think we have a solid base to start from.

QQ - when you say 'move the columns around' you mean in the table view? You're not actually moving their ordinal position in the database I assume? [if you can attach a gif that'd be amaz].

@UtechtDustin as always thanks for the support!! We're getting there slowly but surely.

**Comment by lowercase00** [comment]
@rathboma yes, tableview, just for visualisation purposes, so no changes are saved into the database.
GIF didn't work very well, but hopefully you'll get the idea.
![SequelPro Draggable Columns gif sb-7345ef22-Dp5Ae2](https://user-images.githubusercontent.com/21188280/91758732-d773a400-eba6-11ea-9ad5-284bbceeb45d.gif)
