### ISSUE TITLE
FEAT: Provide a separate view for long, complex column data

### ISSUE THREAD

**Issue by pedroapfilho** [beekeeper-studio/beekeeper-studio#313]
**Is your feature request related to a problem? Please describe.**

With `PostgreSQL` you can have `JSON` inside a cell, and sometimes it's very large, so it's hard to see the table data, making me scroll to the right a lot, to see the other data

**Describe the solution you'd like**

It would be good to have a smaller cell at the beginning, like a max-width for the first render.

**Describe alternatives you've considered**

I tried to make the cell smaller, but it's very hard because the screen doesn't follow the mouse while moving the cell.

**Additional context**

![Screen Recording 2020-08-31 at 14 25 35](https://user-images.githubusercontent.com/13142568/91748303-295ffe00-eb96-11ea-9ad7-bf0b92cda91e.gif)

**Comment by rathboma** [comment]
Ah yes, that doesn't look very good!

Two things we're doing here:
1. Set max-width on table columns (easy, quick)
2. Adding a new 'right-side sidebar' for `inspect`ing columns and editing complex content, etc.

I'll change this one to be specifically about the max-width

**Comment by mdc-git** [comment]
![Screenshot from 2020-10-17 16-50-16](https://user-images.githubusercontent.com/65224188/96345566-d89b5a80-109a-11eb-89bc-f853dd8a6df0.png)
Inspired by tableplus. Easily done with rowSelect on Tabulator.

**Comment by nstr** [comment]
Hey, @rathboma How to change the width of a column?

**Comment by rathboma** [comment]
It's it not draggable?

**Comment by jeremyarde** [comment]
It is draggable, but in my case I had to click and drag about 10 times to get the column to a suitable width. Max width would be a great change

**Comment by mariusa** [comment]
The cell data also appears now in a popup on hover, with a scroll bar. But as soon as you move the mouse, the popup moves or disappears, so the scrollbar can't actually be used. Also, the default popup size is way too small.
