### ISSUE TITLE
BUG: query with JSON fields with some attributes=null prompts dialog to set parameter values

### ISSUE THREAD

**Issue by mariusa** [beekeeper-studio/beekeeper-studio#316]
**Describe the bug**
Running a query which use JSON fields with some attributes=null prompts dialog to set parameter values

**To Reproduce**
Run query:
```
update products set title=
'[{"lang":"en","desc":null}]'
where id='aa';
```

See dialog.

**Expected behavior**
Query should run, that's a valid JSON

**Screenshots / Gifs**
![Screenshot from 2020-09-03 10-13-23](https://user-images.githubusercontent.com/1283842/92083095-251e2580-edce-11ea-99c7-b4d9abe85199.png)

**Version Information (please complete the following information):**
 - OS: Linux
 - App Version 1.7.4

**Additional context**
postgres

**Comment by rathboma** [comment]
Ah yes, that is not expected. Good bug report, thank you!
