### ISSUE TITLE
FEAT: vim key bindings for query editing

### ISSUE THREAD

**Issue by mirosval** [beekeeper-studio/beekeeper-studio#317]
**Is your feature request related to a problem? Please describe.**
I like to do as much of my coding in vim as possible. Vim does not have a great story when it comes to SQL editing and Beekeeper Studio looks like an awesome app otherwise.

**Describe the solution you'd like**
I would love to be able to continue using vim key bindings in the Beekeeper Studio Query Editor

**Describe alternatives you've considered**
There is a way how you can replicate this app in vim, but I found it confusing, I prefer to have a native app for this task.
I'm using TablePlus now, but it does not have vim support either.

**Comment by UtechtDustin** [comment]
Should be possible as CodeMirror has vim key bindings: https://codemirror.net/demo/vim.html
But i guess this is a low priority issue, first of all beekeeper needs a configuration window.

**Comment by rathboma** [comment]
Yes, would love Vim keybindings. I'd actually like Emacs keybindings (no 🔥 war plz :-).

Yeah once we have a configuration window for settings we can definitely add this one.

**Comment by rathboma** [comment]
Use in #197

**Comment by KarnerTh** [comment]
Would love to have vim bindings in beekeeper studio :)
any updates?

**Comment by austinwilcox** [comment]
I am currently maintaining a fork of Beekeeper studio that has vim keybindings in it by default. If you guys would like to take a look at that until we get the settings with vim keybindings.
[https://github.com/austinwilcox/beekeeper-studio](https://github.com/austinwilcox/beekeeper-studio)
The only thing I haven't figured yet is the escape key doesn't work to exit insert mode, but using CTRL+[ is another way to exit insert mode, so for the time being I think that will work just fine.

**Comment by unkindypie** [comment]
Joining to the request, that's what the app really lacks

**Comment by austinwilcox** [comment]
Small update here, what are the thoughts on specifying the keybindings you would like to use in the connection editor area? I am working on getting keybindings for vim pulled into the project, and this was one of the initial ideas I had come to mind. This could be a temporary fix until we get a configuration window where we can go and toggle that setting from within there.

**Comment by austinwilcox** [comment]
@rathboma  Excellent! I will try and get this finished up here in the next week or so, and then submit the PR.

**Comment by austinwilcox** [comment]
@rathboma PR is up early, had a bit of extra time and finished it out. austinwilcox:addVimKeybindings
