### ISSUE TITLE
FEAT: Click to close other tabs

### ISSUE THREAD

**Issue by seanfcarroll** [beekeeper-studio/beekeeper-studio#318]
Really awesome product, thank you! 

**Is your feature request related to a problem? Please describe.**

I love the way it is easy to run a query against all rows of the table from the table browser, with each one landing in it's own tab. In a large database, the tabs soon accumulate.

**Describe the solution you'd like**

Right click to "close other tabs", like in Atom.

**Describe alternatives you've considered**

Manually closing tabs.

**Additional context**

Could be enhanced to "close tabs to the left" or "close to the right", but for starters "close other tabs" would be great!

<img width="779" alt="Screenshot 2020-09-03 at 16 34 23" src="https://user-images.githubusercontent.com/11340230/92129086-5c5af980-ee03-11ea-8317-ce52c6523c6c.png">
<img width="798" alt="Screenshot 2020-09-03 at 16 34 05" src="https://user-images.githubusercontent.com/11340230/92129091-5f55ea00-ee03-11ea-95f4-4e70ca20dc57.png">

**Comment by UtechtDustin** [comment]
Its already implemented, i guess you should update beekeeper :)

See #275 and #285 

![89626722-1b220900-d89a-11ea-9bb4-93b605ab8083](https://user-images.githubusercontent.com/13292481/92134909-646a6780-ee0a-11ea-9429-0d3a9a34ad0f.gif)

**Comment by seanfcarroll** [comment]
@UtechtDustin wow that was quick! ;-)

Thanks very much, I didn't realise I needed to manually update Beekeeper.

Cheers!

**Comment by UtechtDustin** [comment]
Beekeeper has a auto update, but it was broken.
Check the name of the last update (https://github.com/beekeeper-studio/beekeeper-studio/releases/tag/v1.7.5) :D

**Comment by rathboma** [comment]
Yep! What @UtechtDustin said :-)
