### ISSUE TITLE
BUG: Wrong values in SELECT with multiple unnamed columns 

### ISSUE THREAD

**Issue by igponce** [beekeeper-studio/beekeeper-studio#326]
** Description **

If you have a query with more than one unnamed colum, beekeeper studio outputs the value of the last one for all unnamed columns.

** How to reproduce **
For example, connecting to a postgres database, this query:

```
Select 1, 2, 3;
```

In psql it returns:

| col1 | col2 | col3|
|------|------|------|
| 1 |  2 | 3 |

From beekeper client 1.7:

| ?column? | ?column? | ?column? |
|------|------|------|
| 3 | 3 | 3 |

** Why ir is important **

Sometimes you just need to throw away some sql to assess stuff is working okay.

**Comment by UtechtDustin** [comment]
I guess this is a duplicate of #176.

**Comment by rathboma** [comment]
Yes -- this is a problem with the Node Postgres client and how it handles duplicate column names.

The solution is to move to the `array results` interface, then there won't be duplicates.

Thanks for reporting. This is definitely something we will fix soon!

**Comment by rathboma** [comment]
This is fixed in master for PSQL users

**Comment by rathboma** [comment]
I'm closing this, I'm tracking elsewhere
