### ISSUE TITLE
[feature request] Allow viewing text (varchar, text, longtext) in a separate view

### ISSUE THREAD

**Issue by mkoske** [beekeeper-studio/beekeeper-studio#330]
Like a double click and some kind of overlay pops up with the text from clicked cell on it. 

It's quite difficult to see e.g. if there's line breaks in the text if it's in the column view only.

Br,
Miika

**Comment by UtechtDustin** [comment]
Same thing as #313.

**Comment by mkoske** [comment]
Yes, seems similar

**Comment by rathboma** [comment]
Yep! We're planning a sidebar for this type of thing. I've re-labeled that other issue, so I'll close this one to consolidate.

**Comment by mkoske** [comment]
Thanks!
