### ISSUE TITLE
BUG: string fields vulnerable to cross site scripting (XSS)

### ISSUE THREAD

**Issue by thaffenden** [beekeeper-studio/beekeeper-studio#331]
**Describe the bug**
HTML stored in string fields is not being rendered safely, which makes them vulnerable to XSS.

**To Reproduce**
1. Set the value of a string field in a table to an HTML string that contains XSS logic. e.g.: 
`<img src=x onerror=\"alert('this should not work')\">`
1. Select the table from the tables and views list.
1. Filter the table view to just the ID of the record you created/edited.
1. XSS is executed, in this instance the alert is displayed, but if your string opens a new URL etc then that navigation will occur.

**Expected behavior**
The HTML should either be rendered safely, or displayed as just a string (without the HTML formatting actually applied).

(Obviously ideal scenario you should avoid getting to the point of saving that non escpaed XSS data anyway, but if there is an issue I'd prefer my DB client isn't susceptible to it as well).

**Version Information (please complete the following information):**
 - OS: Ubuntu
 - App Version 1.7.5

**Comment by rathboma** [comment]
Hmm, it should be rendering as a non-trusted string. Thanks for reporting I will investigate.
