### ISSUE TITLE
FEAT: Place holders in Saved Queries

### ISSUE THREAD

**Issue by fredrikw** [beekeeper-studio/beekeeper-studio#342]
I would like the possibility to add place holders to Saved Queries. I have several queries that I run regularly but I need to change things like customer ID etc. between runs. It would be great to be able to have the actual "variables" tabable. c.f. https://sequelpro.com/docs/ref/core-features/query

**Comment by fredrikw** [comment]
Sorry, Just found that parameters in queries do exist (https://docs.beekeeperstudio.io/guide/#query-parameters)

**Comment by rathboma** [comment]
:+1:
