### ISSUE TITLE
 Delete record

### ISSUE THREAD

**Issue by 11JoseMarcos11** [beekeeper-studio/beekeeper-studio#348]
Hello everyone,

How do I delete a record? I pressed the key - on the keyboard, but did not delete it. I'm using a notebook. 

Sorry for my English. 

Thank you.

**Comment by UtechtDustin** [comment]
Its currently not possible to delete a new row using the ui, we have to implement this first!

**Comment by 11JoseMarcos11** [comment]
> Its currently not possible to delete a new row using the ui, we have to implement this first!

Thank you, UtechtDustin.
