### ISSUE TITLE
FEAT: Select rows and copy as CSV or JSON (like in DataGrip)

### ISSUE THREAD

**Issue by rathboma** [beekeeper-studio/beekeeper-studio#349]
It'd be nice to select a series of rows and be able to copy them.

Have it work like in Excel -> click the row 'headers' down the left side to highlight, right click -> copy as -> [options]

Types to support (also in the table copy):

- Json
- CSV
- SQL (copies as an insert statement)
- Markdown table

**Comment by harrytran998** [comment]
. for this feature 😝 !

**Comment by trevorrjohn** [comment]
@rathboma is there a library you were thinking about using for this? I might have some time to work on this.

**Comment by rathboma** [comment]
Wow, that'd be amazing.


It works with tabulator natively, but requires a row header along the left side of the table to allow row selection, then calling the tabulator copy function.

**Comment by trevorrjohn** [comment]
Quick update: I started to take a look at this, but haven't gotten too far yet.

**Comment by jonyen** [comment]
Is it also possible to select rows and be able to delete them? That would be useful for dev purposes.

**Comment by rathboma** [comment]
Delete is coming in the next release, copy row should be easy too, I'll look into it next week!
