### ISSUE TITLE
FEAT: Tab Reordering

### ISSUE THREAD

**Issue by GeorgeWells** [beekeeper-studio/beekeeper-studio#352]
It would be nice if we could have the ability to be able to reorder the tabs by clicking and dragging.

Also, it would be awesome if the open SQL tabs were remembered per connection when closing the connection/window and restored when that connection is opened again. Maybe this is something that is regularly saved behind-the-scenes in case of a power cut or crash to minimise losing any queries that have been typed up.

**Comment by rathboma** [comment]
Yes, tab reordering should be a thing. As should saving tab contents. Lets split these into two tickets.
