### ISSUE TITLE
FEAT: Collapsable sidebar 

### ISSUE THREAD

**Issue by Chris-Filiatrault** [beekeeper-studio/beekeeper-studio#353]
It would be great if it was possible to collapse the sidebar entirely, so I can focus on the code and output. 
I'm on a 13" MacBook some of the time, and if I dual screen (common while learning SQL tutorials) then I can't see much code/output.

Thanks for all your work guys, so awesome that this is open source!

**Comment by UtechtDustin** [comment]
Makes sense i guess and it should not be that hard to implement.

**Comment by rathboma** [comment]
Yes, this makes sense. @ghstng probably one for you?

**Comment by rathboma** [comment]
Oh, this was done ages ago
