### ISSUE TITLE
FEAT: New installation repository through flathub

### ISSUE THREAD

**Issue by gnovaro** [beekeeper-studio/beekeeper-studio#354]
The idea is add to an alternative installation repository https://flathub.org/ i think is really a good project for kown new applications.

**Comment by rathboma** [comment]
Unfortunately Electron builder (https://www.electron.build/) doesn't yet have a flatpack target, so I can't easily build a flatpackage.

Going to close this issue as a dupe of #22. As a linux user it is still important to me, so don't feel like this means I don't agree with you :-)
