### ISSUE TITLE
FEAT: Ability to show/hide columns when viewing table rows

### ISSUE THREAD

**Issue by EmasXP** [beekeeper-studio/beekeeper-studio#358]
When having large tables one needs to scroll horizontally to view the columns of interest. 

Coming from DBeaver, I often pick the columns of interest when listing the data. This is very useful during investigation.

DBeaver have a button called "Customize filters" to the right on the search bar. Clicking that button brings up a new dialog listing all the available columns, with check boxes on the left side beside each column. In the bottom of the dialog there are also quick-selections like "Show None" (deselects all check boxes) and "Reset" (which selects all check boxes). There are also buttons for reordering the columns, though I see that more like a nice-to-have.

I find the solution in DBeaver to be very straight forward, though there might be an even better solution that I have not thought about.

**Comment by rathboma** [comment]
Nice. Like that.

Should be super easy too. Tabulator supports hiding columns

**Comment by fabscav** [comment]
@rathboma I'd like to contribute to this project and thought this might be a good starting point, so I tried implementing this feature. I used the popover component of the included xel toolkit, but it doesn't seem to adapt to the dark style. Am I missing something?

![columns](https://user-images.githubusercontent.com/3975210/96034342-ace16000-0e61-11eb-930a-5781ef979a89.gif)
