### ISSUE TITLE
QUESTION: Running inside a container

### ISSUE THREAD

**Issue by pcorbel** [beekeeper-studio/beekeeper-studio#360]
**Details:**
Hello community 👋, 

I would like to be able to launch this fantastic tool via a Docker Container 🐳  and expose it via a port (and not have to install the client locally) 

The final goal is to be able to pop multiple containers so my users only have to connect to beekeeper.mydomain.com 🐝  and to be able to use the tool (so they just have to have a decent web browser) 

I think it is possible by skipping the electron part of the code (and just launch the Vue one) but I didn't succedeed as of today. 🙁

Does anyone already have done something like that? 🤔

**Version Information [might be relevant to your issue]**
Operating System: Docker on Mac OS
App Version: V7.1.5

**Comment by rathboma** [comment]
Right now it unfortunately won't work because the vue code has two big limitations:

- it relies on native node modules
- it relies on electron modules

We're going to produce a build eventually for running in the browser, and a way for it to be true multi-tenant, but right now it's exclusively a desktop app I'm afraid.

Some good alternatives: metabase, redash

**Comment by rathboma** [comment]
Going to close this until we're closer to working on it

**Comment by agusmdev** [comment]
Hi! @rathboma I'm trying to do the same as @pcorbel. Is this supported now?

**Comment by rktyt** [comment]
FYI:

Here is an example of using it in a container.

Dockerfile
```dockerfile
FROM ghcr.io/linuxserver/baseimage-kasmvnc:debianbookworm

# I am using Japanese, so I am adding fonts.
ENV DOCKER_MODS=linuxserver/mods:universal-package-install
ENV INSTALL_PACKAGES=fonts-noto-cjk
ENV LC_ALL=ja_JP.UTF-8

# Install Beekeeper Studio
RUN curl -fsSL https://deb.beekeeperstudio.io/beekeeper.key | sudo gpg --dearmor --output /usr/share/keyrings/beekeeper.gpg \
  && sudo chmod go+r /usr/share/keyrings/beekeeper.gpg \
  && echo "deb [signed-by=/usr/share/keyrings/beekeeper.gpg] https://deb.beekeeperstudio.io stable main" \
  | sudo tee /etc/apt/sources.list.d/beekeeper-studio-app.list > /dev/null
RUN sudo apt update && sudo apt install beekeeper-studio -y

RUN echo "/opt/Beekeeper\\ Studio/beekeeper-studio" > /defaults/autostart
```

Build & Launch
```bash
docker build -t beekeeperstudio . 
docker run --rm -it -p 3000:3000 beekeeperstudio bash
```

----

For more information, see https://github.com/linuxserver/docker-baseimage-kasmvnc.
