### ISSUE TITLE
FEAT: Smoother scrolling / speed enhancements of result loading

### ISSUE THREAD

**Issue by kalenpw** [beekeeper-studio/beekeeper-studio#362]
**Is your feature request related to a problem? Please describe.**
When scrolling the results of a query it appears to only load what is visible at a time. Which makes sense memory wise but then when I go to scroll it takes a few seconds to load and jumps around for the next bit of results

**Describe the solution you'd like**
Ideally it would be butter smooth (as that is one of the main features). Obviously I have no idea what sort of performance concerns this would impact but maybe load 2x the results as are in the view so scrolling has a head start.

**Describe alternatives you've considered**
NA

**Additional context**
Overall I think it's a great program and am excited to start using it. I have no problem making a PR but figured it would be best to start an issue and discuss it before I try anything. 

Specs:
macOS Mojave
i7, 8gb ram

**Update**

I tried it on my personal laptop (Ubuntu 18.04, i5 8250u, 32gb ram) and it was buttery smooth.  I used a similarly sized table to test the query on and the specs on this aren't _that_ much better I'd expect such a drastic difference.

**Comment by rathboma** [comment]
The next build has a new version of tabulator, so this should be improved then! It's usually the width of the table that slows it down.

**Comment by rathboma** [comment]
Going to close this as it should be fixed by the next release
