### ISSUE TITLE
The result tab shows the name of the columns with a capital letter when it is not really like this.

### ISSUE THREAD

**Issue by gnovaro** [beekeeper-studio/beekeeper-studio#37]
The result tab shows the name of the columns with a capital letter when it is not really like this.
![Captura de pantalla de 2020-05-03 14-13-53](https://user-images.githubusercontent.com/270990/80915388-59b39f00-8d52-11ea-8142-a5e0d08e98c7.png)

**Comment by rathboma** [comment]
Yep, this is a bug, will be fixed by #33
