### ISSUE TITLE
BUG: Contents of BIT columns is not shown

### ISSUE THREAD

**Issue by akesser** [beekeeper-studio/beekeeper-studio#370]
The content of columns of type bit are not shown. Im using mriadb 10.23

**Expected behavior**
The content of the column should be shown.

**Screenshots / Gifs**
The Screenshot shows columns of type BIT and the open inspector where the html around a column with a bit value is selected
![Bild 05 10 20 um 14 58](https://user-images.githubusercontent.com/10295987/95082534-76963900-071b-11eb-85a5-955721753dc7.jpg)

**Version Information (please complete the following information):**
 - OS: Mac Os Catalina 10.15.7
 - App Version: 1.7.5.

**Comment by rathboma** [comment]
Great bug report thanks! Will prioritize this for the next milestone
