### ISSUE TITLE
Password authentication failed for Blank Username/Password for Postgres

### ISSUE THREAD

**Issue by shireenrao** [beekeeper-studio/beekeeper-studio#373]
I am on Ubuntu 20.04. I am trying to connect to a local postgres database. I can connect to it from psql and pgcli. Just running psql, I can connect to my database as me. With Beekeeper I get an error saying "password authentication failed for user "shireenrao". Here is a screenshot of the error. 

![image](https://user-images.githubusercontent.com/887754/95459783-1c2af180-0942-11eb-846d-629b9f1e2555.png)

**Version Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - App Version 1.7.4

I saw #50 with the same problem was resolved. Is this a different issue?

**Comment by shireenrao** [comment]
I am closing the issue. My local postgres settings were not setup to accept passwordless connections. I changed the settings in /etc/postgresql/12/main/pg_hba.conf to what I showed below and it is now working. Sorry about that.

```
local   all             postgres                                trust

# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     trust
# IPv4 local connections:
host    all             all             127.0.0.1/32            trust
# IPv6 local connections:
host    all             all             ::1/128                 trust

```

**Comment by rathboma** [comment]
Thanks for reporting back! Much appreciated.
