### ISSUE TITLE
QUESTION: Hows does BeekeeperStudio compares to Azure data Studio?  Or other main DB managers tools 

### ISSUE THREAD

**Issue by giordafrancis** [beekeeper-studio/beekeeper-studio#374]
Hi there, 

See below example from Mst which easily alows customers to compare one tool versus other? Could something like this be produced in your documentation page

https://docs.microsoft.com/en-us/sql/azure-data-studio/what-is?view=sql-server-ver15

**Comment by rathboma** [comment]
Hey!

Thanks for the link. Yes we're going to be putting together some comparison pages in the near future :-). We track marketing stuff separately, so going to close this issue. If you feel strongly about this info you could add it to our docs, see the docs folder in this repo.
