### ISSUE TITLE
BUG: multiline selection for comment and uncomment should keep selected text when executing the command

### ISSUE THREAD

**Issue by phillpafford** [beekeeper-studio/beekeeper-studio#377]
**Describe the bug**
When selecting multiple lines to commenting or uncommenting using the keyboard shortcut `ctrl + /` 
After executing the keyboard shortcut the lines of text there were selected are no longer selected, the cursor also moves to the next line

**To Reproduce**
1. Go to `query tab`
2. Copy and paste this to the query tab 
```
WITH get_date AS (
	SELECT CURRENT_DATE
)

SELECT *
FROM get_date 
```
3. Select all the text from the example in step 2
4. Use the keyboard shortcut `ctrl + /`

**Expected behavior**
The keyboard shortcut `ctrl + /` should be able to toggle from comment to uncomment without having to reselect the text that was previously selected, and the cursor should not move

**Screenshots / Gifs**
n/a

**Version Information (please complete the following information):**
 - OS: [macOS 10.14.6]
 - App Version [1.7.5]

**Additional context**
This also happens if you just comment and uncomment a single line

**Comment by rathboma** [comment]
This is fixed in master!
