### ISSUE TITLE
BUG: symlinks in home directory prevent Beekeeper Studio from launching (Ubuntu Snap)

### ISSUE THREAD

**Issue by janhapke** [beekeeper-studio/beekeeper-studio#380]
**Describe the bug**
I installed Beekeeper Studio from Ubuntu Software Store. After installation I clicked on "Launch" and nothing happened. I could not start it from the Console or the Ubuntu App Launcher either.

Turns out that having the Ubuntu standard home-directory entries (`~/Documents`, `~/Downloads`, `~/Music`, `~/Pictures`)  replaced by symbolic links to different locations prevents Beekeeper Studio from starting initially.

After removing all of these links, Beekeeper Studio starts.

Re-creating these links does not prevent Beekeeper Studio from starting after it has successfully started once.

After removing and re-installing Beekeeper Studio, the presence of the symlinks will again prevent it from starting.

**To Reproduce**
1. Remove Beekeeper Studio from Ubuntu Software Center (if it is installed)
2. Make sure you do not have a `Documents` directory within your home directory and do `ln -s ~/Documents /mnt/data/Documents`
3. Install Beekeeper Studio from Ubuntu Software Center
4. Start `snappy-debug`
5. Try to launch Beekeeper Studio --> nothing happens
6. Observe output of `snappy-debug` indicating that access to `/mnt/data/Documents` was blocked
5. `unlink ~/Documents`
6. Try to launch Beekeeper Studio again --> it launches

**Expected behavior**
Beekeeper Studio should not attempt to read the Documents, Downloads, Music and Pictures directories inside my home directory. Or at least it should start even if it fails to read these directories due to missing snap permissions and ask me to give it the needed permissions.

**Screenshots / Gifs**
```
$ snappy-debug
INFO: Following '/var/log/syslog'. If have dropped messages, use:
INFO: $ sudo journalctl --output=short --follow --all | sudo snappy-debug
= AppArmor =
Time: Oct 11 13:07:55
Log: apparmor="DENIED" operation="open" profile="snap.beekeeper-studio.beekeeper-studio" name="/mnt/data/Documents/" pid=84930 comm="head" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
File: /mnt/data/Documents/ (read)
Suggestions:
* adjust program to read necessary files from $SNAP, $SNAP_DATA, $SNAP_COMMON, $SNAP_USER_DATA or $SNAP_USER_COMMON
* add 'removable-media' to 'plugs'
```

**Version Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - App Version
```
snap-id:      XEOrla3TiUZiTmvCRiG2TdzQMt64NARk
channels:
  latest/stable:    1.7.4 2020-08-28 (40) 79MB -
installed:          1.7.4            (40) 79MB -
```

**Additional context**
Suggestion from AppArmor to "add 'removable-media' to 'plugs'" failed:
```
$ snap connect beekeeper-studio:removable-media
error: snap "beekeeper-studio" has no plug named "removable-media"
```

**Comment by rathboma** [comment]
Hey! Thanks for the report.

So by default Beekeeper Studio stores data in ~/.config, it doesn't read any of those directories at all on start-up, so I suspect that is something to do with the way Snap access permissions work.

With snap the app only gets access to ~/, but if you have symlinks to other places it probably confuses it.

Some other options:

1. Try installing with devmode - `sudo snap install beekeeper-studio --devmode`
2. For connecting removable media you can do it like this: `sudo snap connect beekeeper-studio:removable-media :removable-media`

**Comment by janhapke** [comment]
I uninstalled and installed it with `--devmode` - the problem does not appear and Beekeeper Studio starts just fine.

My guess would be that somewhere within the depths of node fs or Electron, a `readdir` is happening which is then blocked by AppArmor. Unfortunately I don't have the time now to set up a Development Environment for Beekeeper Studio, otherwise I would look into it more deeply.

**Comment by rathboma** [comment]
Thanks for confirming the workaround!

This is the type of issue I've come to associate with Snap -- We've had some similar issues in the past that have been worked around, but the way it sandboxes apps is not transparent.

I'm going to close this for now as we have a workaround -- thanks so much (truly) for reporting.

**Comment by janhapke** [comment]
OK, I may have been a little bit too fast with claiming the workaround works.

The workaround was:
```
$ sudo snap remove beekeeper-studio
$ sudo snap install beekeeper-studio --devmode
$ beekeeper-studio
```
Then Beekeeper Studio starts and I can use it just fine.

The problem is that after I quit Beekeeper Studio, I cannot start it again. I have to again remove and re-install it with devmode and then again I get to use it exactly once. Bookmarks or stored settings are of course lost during the `snap remove`.

**Comment by janhapke** [comment]
Also the second suggestion returns an error message:

```
$ sudo snap connect beekeeper-studio:removable-media :removable-media
error: snap "beekeeper-studio" has no plug named "removable-media"
```

**Comment by rathboma** [comment]
Yes I realized after suggesting it and pushed a change to master to enable
this in future

**Comment by hyamanieu** [comment]
I had exactly the same issue de to symlinks. Just FYI, in Ubuntu Software there is a little `Permissions` button. You need to allow permission to other media. And it will launch without problem. No need to install through other means or via CLI.
