### ISSUE TITLE
BUG: Database file 'Choose file' doesn't show any written characters

### ISSUE THREAD

**Issue by matheussilvaesousa** [beekeeper-studio/beekeeper-studio#383]
**Describe the bug**
Database file "Choose file" doesn't show any written characters
When trying to choose a database file in 'Quick Connect' the Ubuntu File Manager that opens shows the blank box instead of characters.

**To Reproduce**
1. Open Beekeeper Studio from 'Show Applications' in Ubuntu
2. Select SQLite for a Connection Type
3. Click 'Choose File'
4. File Manager that opens shows the bug

**Expected behavior**
File Manager should show letters as it does when it's opened with other app (Firefox tested).

**Screenshots / Gifs**

![Screenshot from 2020-10-13 11-05-16](https://user-images.githubusercontent.com/58100766/95872566-52eb7800-0d45-11eb-819b-9fd47f59e9fb.png)
![Screenshot from 2020-10-13 11-10-08](https://user-images.githubusercontent.com/58100766/95872593-57b02c00-0d45-11eb-8523-87fc13d3c0f2.png)

**Version Information (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - For App version see Additional context. Suggested method is affected by the bug and shows this below instead:
![Screenshot from 2020-10-13 11-18-14](https://user-images.githubusercontent.com/58100766/95873130-fc326e00-0d45-11eb-8144-1337040c3731.png)

**Additional context**
Downloaded latest stable twice on Oct 13th, 2PM GMT, once via `sudo snap install beekeeper-studio` and once via Software app on 'Show Applications'

**Comment by matheussilvaesousa** [comment]
**Update**
Installed via apt / deb as shown here [https://docs.beekeeperstudio.io/installation/#linux-installation](url) and it works properly.

**Comment by rathboma** [comment]
Yes. Please use the app image or deb version. This is a problem with snaps themselves and not something I can fix

**Comment by rathboma** [comment]
```
$ sudo rm -f /var/cache/fontconfig/*
$ rm -f ~/.cache/fontconfig
```
From: https://forum.snapcraft.io/t/snap-store-fonts-on-arch-linux-are-merely-empty-rectangles/15373/9

**Comment by josegus** [comment]
> ```
> $ sudo rm -f /var/cache/fontconfig/*
> $ rm -f ~/.cache/fontconfig
> ```
> 
> From: https://forum.snapcraft.io/t/snap-store-fonts-on-arch-linux-are-merely-empty-rectangles/15373/9

Unfortunately, this solution didn't work for me (Ubuntu 21.04) using snap version

**Comment by rathboma** [comment]
Uck, yes the snap issues are very frustrating. The best workaround right now is to use the DEB version, which works great on Ubuntu
