### ISSUE TITLE
FEAT: start results export with date for easy sorting

### ISSUE THREAD

**Issue by evs-xsarus** [beekeeper-studio/beekeeper-studio#384]
Currently, when I export query results, the filename suggested starts with some text:

query_results-2020-10-13_42240.xlsx

Better would be something like:

2020-10-13_42240_query_results.xlsx

This gives nice sorting in the file browser.

Perhaps implement the placeholder system as done in HeidiSQL:

![image](https://user-images.githubusercontent.com/44158071/95874291-06b62d00-0d71-11eb-9a36-c26f5bc74304.png)

**Comment by rathboma** [comment]
This is a good candidate for #197

**Comment by rathboma** [comment]
Added to that list, going to track there and close this issue (we'll definitely add this option though when we do the settings screen)
