### ISSUE TITLE
FEAT: Ability to create tables and create/modify columns for PostgreSQL

### ISSUE THREAD

**Issue by rogerscg** [beekeeper-studio/beekeeper-studio#386]
**Is your feature request related to a problem? Please describe.**
I find creating DB tables and modifying columns via queries tedious, so I usually use a DB client like pgAdmin 3. That means I'll usually need two clients open (Beekeeper and pgAdmin 3) while developing. I'd like to eliminate pgAdmin completely.

**Describe the solution you'd like**
A simple screen/modal for creating tables and modifying columns. Constraint support would also be a huge win.

**Comment by UtechtDustin** [comment]
ref #337

**Comment by rathboma** [comment]
I think it's definitely different from #337. I agree this needs to be a thing.

We have a plan to work on this soon. So agreed :100:
