### ISSUE TITLE
BUG (minor): Error on connection is carried across connections views

### ISSUE THREAD

**Issue by danilopolani** [beekeeper-studio/beekeeper-studio#388]
**Describe the bug**
Whenever a connection fails and an error appears below the connection box, that error is carried across ALL the connections when you click them on the sidebar (even before trying to connect to them).

**To Reproduce**
1. Create a connection (even a fake one is fine, it just needs to be on the sidebar)
2. Create another failing connection or just use the quick connect. This must fail.
3. Connect to the failing connection.
4. When the error appears below the box, navigate across other connection (e.g. the created at step 1)

**Expected behavior**
The message should disappear or, better, be linked to that connection-view only.

**Screenshots / Gifs**
https://streamable.com/hlfwsr

**Version Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - App Version: 1.7.4

**Additional context**
-

**Comment by rathboma** [comment]
Excellent UI bug report, thank you!

**Comment by rathboma** [comment]
this is in master.
