### ISSUE TITLE
Editing rows by double click

### ISSUE THREAD

**Issue by AqilCont** [beekeeper-studio/beekeeper-studio#39]
A very loved feature from our MySQL Workbench. Clicking on a row in the retrieved data from a query replaces the text present there with a text input, where you can input the new value. Would appreciate this a lot, and would make me happily switch over.

**Comment by rathboma** [comment]
:100:. We're working towards this feature step by step. Stay tuned!

First step is the #33 PR which allows viewing table data, from there I can work towards implementing the editing interface.

**Comment by UtechtDustin** [comment]
@rathboma can be closed i guess, as editing is possible with  #276.

**Comment by rathboma** [comment]
Yep, this works! Got a few small changes I need to make, but then a release will be ready
