### ISSUE TITLE
Text Misidentified as Parameter

### ISSUE THREAD

**Issue by carlson001** [beekeeper-studio/beekeeper-studio#391]
**Describe the bug**

When writing a query (in my case an insert query), and the SQL contains a colon (:) in text surrounded by single quotes, it is being misidentified as a parameter that needs a value.  This is typically done when there is a JSON column and trying to insert data. It does pick up JSON text properly, but numeric values are flagged as parameters.

**To Reproduce**
1. Open a new query tab
2. Write the following query: INSERT INTO sometable (jsonvalue) VALUES ('{"id":1,"name":"Derek"}');
2a: use a select query, does the same: SELECT '{"id":1,"name":"Derek"}'
3. Run the query
4. Get a prompt to insert the value for :1

**Expected behavior**
Items wrapped in single quotes should be ignored.

**Version Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - App Version 1.7.4

**Additional context**

Mostly a minor inconvenience, the numeric values can be entered in the parameter pop-up and it works.

**Comment by jmturner** [comment]
I've noticed a similar thing happens when a parameter contains a $1, $2, etc. For instance, I build a query to insert a bcrypt hash which begins with $2y$10 ... Beekeeper throws a syntax error when it gets to y.

I'm happy to file a separate issue on this but they seem related to me.
