### ISSUE TITLE
Only run the arm64 test suite when run from beekeeper-studio/beekeeper-studio repo?

### ISSUE THREAD

**Issue by MasterOdin** [beekeeper-studio/beekeeper-studio#394]
**Details:**

Anytime I decide to work on something for beekeeper, any push I do to my fork, I then get an email / web notification for when the build suite fails due to arm64. Additionally, because this environment always fails first, it means I can never run the workflow locally, so I cannot even validate my work locally on GH before submitting a PR.

**Potential Fix**
Separate out the arm64 build step to its own workflow. Have it run only on [workflow-dispatch](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#workflow_dispatch) action, which then kicks off the arm64 build. Can then wrap the firing of this event with an if statement to validate that it only runs on `beekeeper-studio/beekeeper-studio`.

This prevents the arm64 environment from being considered for evaluation, and getting workflows to run on forks! 😄

**Comment by MasterOdin** [comment]
For clarification on how I think this would best work would be to make the arm64 endpoint trigger itself on all pull requests in addition to workflow-dispatch actions that come on pushes in https://github.com/beekeeper-studio/beekeeper-studio/blob/master/.github/workflows/build.yml.

The biggest con for this is the replication of build.yml into arm64 specific yml, but I believe the pros outweigh the con here of making it easier for external collaborators to test their code before making a PR.

**Comment by rathboma** [comment]
Some good points.

I think this is mostly an oversight on my part -- initially I had the ARM build run all the time because I was still figuring out the ARM build myself.

Mostly the ARM64 build is only useful for packaging. The app should work just fine. I'm going to update it to only run on Master and for release packaging builds.
