### ISSUE TITLE
beekeeper-studio snap does not have permission to read ssh keys

### ISSUE THREAD

**Issue by chrisdlangton** [beekeeper-studio/beekeeper-studio#40]
Using the snap, the only version of this app shown to Ubuntu 20.04 users, makes this app borked for all purposes when not connecting to a local database.
So for any prod use, this app is completely borked

Basically snap will not allow access to filesystem, so SSH keys are inaccessible.

You could solve the issue by any;

1.Running in snap with unconfined mode (not a secure choice, but is usable at least)
2. Refactoring to inherit from the ssh-agent (may require some trickery getting the snap user access to it)
3. Text area input field to copy from host the key and paste it into Beekeeper to be saved securely (like the passwords are currently) << most ideal, only thing that may work for a confined snap anyway

**Comment by rathboma** [comment]
Well, that is annoying. Thanks for finding this bug!

I'll look into a way forward for this. Perhaps there's a permission system to approve local file access. In the meantime, there is a .deb install process, but yes it is not in the Ubuntu store.

**Comment by rathboma** [comment]
So I took a look and I have the 'best' permission set - `home` which provides access to a user's home directory, but does not allow access to hidden files.... uck.

I'll ask in the snapcraft forums

**Comment by rathboma** [comment]
I've submitted a snap store request to allow all personal files to be auto-connected
