### ISSUE TITLE
QUESTION: Beekeeper needs extra permission and that one from troubleshooting isnt working

### ISSUE THREAD

**Issue by brnborges** [beekeeper-studio/beekeeper-studio#400]
**Details:**
Hi,
I installed Linux on my machine as a second boot, I put the beekeper via snap, but I can't access the database folder using SQLITE and the warning says that permissions are missing, I have tried numerous commands including the troubleshooting provided by you and nothing changed.

I am a new linux user and thank you in advance

**Version Information [Last version downloaded from snap 18/10/2020]**
Operating System: Linux Ubuntu 20.04 LTS

**Screenshot / GIF [if appropriate]**:
A screenshot of the app if that helps

![Screenshot from 2020-10-21 03-31-17](https://user-images.githubusercontent.com/60415859/96665919-eb898580-134d-11eb-9f10-0dcb2c8a2574.png)

**Comment by rathboma** [comment]
Hey! the latest version should allow you to set the external drive permission now (1.8.2 onwards).

Alternatively install the DEB version which doesn't have any of these annoying restrictions, and works great!

**Comment by rathboma** [comment]
Please try again with the latest version and see if it works. Snap permissions are the bane of my life

**Comment by brnborges** [comment]
thanks a mil mate! all good now
