### ISSUE TITLE
BUG: beekeeperstudio.io doesn't download for mac client.

### ISSUE THREAD

**Issue by thearyanahmed** [beekeeper-studio/beekeeper-studio#401]
**Describe the bug**
The download option might not be working properly. Could not download client for mac.

**To Reproduce**
Steps to reproduce the behaviour:
Just go to https://www.beekeeperstudio.io/download/?platform=mac
**Expected behaviour**
is to start a download

**Comment by UtechtDustin** [comment]
It's working fine for me.
Maybe a browser addon will prevent the download ?

Do you get any error messages ?
Which Browser (version) do you use ?

**Comment by thearyanahmed** [comment]
using chrome Version 86.0.4240.75 (Official Build) (x86_64) on mac os 10.15.6

**Comment by jschankibi** [comment]
I was having the same problem on Chrome, I tried to use IE as well and it would not download.  I finally tried Firefox and was able to get the file to download.

**Comment by UtechtDustin** [comment]
It's working fine for me on chrome.
Do you any errors (in the console ?) ?

**Comment by jschankibi** [comment]
![image](https://user-images.githubusercontent.com/67176451/96775237-3db1c180-13b5-11eb-8270-e9a2ddced9a1.png)

This is what My console in Chrome is showing

**Comment by UtechtDustin** [comment]
@jschankibi thank you, i could figure out the issue.
As the error in the console already said, the download link is https but the redirect to github is https.
The none https link can be found in the javascript file (https://www.beekeeperstudio.io/assets/js/main-0a82cc83c798d6790438436b7e4f198605f298fb8bfe6f346762b2caf5141dda.js) which triggers the download.
(Just search for `http://download.beekeeperstudio.io/download/`).

**Comment by rathboma** [comment]
Thanks! I've fixed this in a new website release coming after the next release where I totally remove the download proxy and just redirect to github

**Comment by rathboma** [comment]
@jschankibi want to check the website now? Should be fixed.

**Comment by thearyanahmed** [comment]
Working for me.
