### ISSUE TITLE
FEAT: run multiple select queries, open tab for each result

### ISSUE THREAD

**Issue by evs-xsarus** [beekeeper-studio/beekeeper-studio#403]
When I'm running multiple select queries in a Query tab, only the results for the first query are shown, although I expected to see the results from the last query.

What I would like, is to get a subtab for the results of each SELECT query when running all queries:

![image](https://user-images.githubusercontent.com/44158071/96971842-fbec5c80-1515-11eb-8bcf-ca8a78a1e3ec.png)

The tabs should be cleared when running one or all queries again.

**Comment by rathboma** [comment]
The individual results are available in a dropdown in the footer! (Results 1, Results 2)

Admittedly this seems a little confusing, maybe relocating the dropdown to above the result set would be better.

@ghstng this isn't the first time we've seen this question. Means it's probably a real usability issue. We should think about how to solve it. Maybe even just flashing the select box or something simple?

**Comment by evs-xsarus** [comment]
Ah, really didn't see those. Perhaps you could move them to be on the same line as 'Save' and 'Run'.

**Comment by rathboma** [comment]
yeah, something for us to think about. We'll discuss

**Comment by michaelblyons** [comment]
> Means it's probably a real usability issue. We should think about how to solve it. Maybe even just flashing the select box or something simple?

I absolutely agree. I was looking for a SQL editor because Oracle won't fix [this 3-year-old regression](https://bugs.mysql.com/bug.php?id=86666) and found BK in May 2020. I ran a couple experiments in June and _almost dismissed_ BK. One of our normal queries does some temporary table set-up before it runs, and when I saw "No results found," I thought the program is broken.

Luckily I was persistent and figured out the results dropdown. (And now since August we've all switched to doing MySQL and occasionally other DBMS work with BK.)

I'd like to see two things, ideally:

- Notice the multiple results better. Either
    + Highlight the dropdown emphatically when there are multiple results, or
    + Some other UI that is noticeable to a new person. The tabs suggestion is a good example.

- Name results somehow to the part of the query they came from. This will help avoid the problem "I have 'Results 1' through 'Results 6'... which one do I pick?"
    + (Forgive poor mockup) If your results dropdown looked like this, it's at least easy to skip the `DECLARE` ones:
        * Results 1  
            <sup>``SELECT foo.EditorID, foo.Name AS `Post` `` &hellip;</sup>
        * Results 2  
            <sup>`DECLARE @Start DATETIME =` &hellip;</sup>
        * Results 3  
            <sup>``SELECT bar.SubmissionID, usr.ID AS `UserID` `` &hellip;</sup>
    + Also see #146 with a bundle of `insert into`s.

**Comment by rathboma** [comment]
I think short term we can do something simple - like flashing the dropdown. Maybe long term we split results into two things: results & logs, if a query yields no output, it doesn't get a 'results' entry. All 'rows affected' outputs can go in the log.

How does that sound?

**Comment by rathboma** [comment]
@ghstng Got any short-term fixes you can make to this?

**Comment by michaelblyons** [comment]
> I think short term we can do something simple - like flashing the dropdown. Maybe long term we split results into two things: results & logs, if a query yields no output, it doesn't get a 'results' entry. All 'rows affected' outputs can go in the log.
> 
> How does that sound?

_Almost_ all of this sounds good. The flashing is great short-term!

I only have a problem with one bit of the long-term plan:

> if a query yields no output, it doesn't get a 'results' entry.

Sometimes this is good: ``insert into `foo` values ('bar', 'baz', 14)`` doesn't need a results entry.

Sometimes, though, it's bad. If you're doing some `select` statement and you get the `where` wrong, or you get the `where` _right,_ but there are no rows to show you, I would not want that to go only into a log. I would want to know there were no results.

**Comment by rathboma** [comment]
Yes for sure. Maybe we need a mapping of query type -> "show in results", or something like that?

Like: select: yes, insert: no, create: no, default: yes
