### ISSUE TITLE
QUESTION: Why no Mac DMG for 1.8.2?

### ISSUE THREAD

**Issue by Dottenpixel** [beekeeper-studio/beekeeper-studio#407]
**Details:**
Why no Mac DMG for 1.8.2?

**Version Information [might be relevant to your issue]**
Operating System: MacOS
App Version [help -> about]:

**Screenshot / GIF [if appropriate]**:
A screenshot of the app if that helps

**Comment by rathboma** [comment]
I'm about to publish a new version. Long story short - the mac builder is buggy and sometimes 'succeeds' when it doesn't really
