### ISSUE TITLE
Cannot refresh table list on once-empty empty DB

### ISSUE THREAD

**Issue by MasterOdin** [beekeeper-studio/beekeeper-studio#408]
**Describe the bug**

When opening a fresh database, if there are no tables, the left bar just shows "There are no tables in database_name" with no icon to refresh the list. One must either change databases or reconnect for the left bar to finally show a table. There is then an icon that can be used to refresh the table list on table creation / deletion.

**To Reproduce**
1. Using docker: `docker run --rm -e MYSQL_ROOT_PASSWORD=password -e MYSQL_DATABASE=beekeeper -e MYSQL_USER=test -e MYSQL_PASSWORD=test -p 3306:3306 --name mysql mysql:8`
2. In beekeeper, connect to this DB
3. Run the query `CREATE TABLE test (`col1` varchar(255))`
4. Try and find a way to refresh table list

**Expected behavior**

That there is some way to refresh the table list without changing databases or refreshing the entire connection.

**Screenshots / Gifs**

![Untitled](https://user-images.githubusercontent.com/1845314/97057629-a9349400-1559-11eb-81f0-76268975409f.png)

**Version Information (please complete the following information):**
 - OS: [e.g. Windows/Mac/Ubuntu] Windows
 - App Version [e.g. help -> About Beekeeper Studio]: master

**Additional context**

Was using mysql as was testing something else, but probably affects the other database types just as well.

**Comment by rathboma** [comment]
Doh, thanks for the report. Will fix
