### ISSUE TITLE
BUG: Self signed certificate

### ISSUE THREAD

**Issue by LuizHAP** [beekeeper-studio/beekeeper-studio#411]
**Describe the bug**
After updating to version 1.8.5, I can no longer connect to my DB using Heroku Postgres.

**To Reproduce**
1. Get database url on Heroku
2. Import from URL
3. Click on Connect
4. Get this error

![image](https://user-images.githubusercontent.com/20971507/97094430-3d226080-162b-11eb-8a81-c7836b6e433f.png)

**Expected behavior**
Connect normally, as you connected before, even choose Enable SSL

**Screenshots / Gifs**
https://www.loom.com/share/7afaf8e89a654c3db29b80e227303b71

**Version Information (please complete the following information):**
 - OS: Windows 10
 - App Version: 1.8.5

**Comment by rathboma** [comment]
Doh, sorry about that. I'll push a fix very soon

**Comment by LuizHAP** [comment]
Jeez! I'm not the best developer in Vue, but can I try to help, or is the solution simple?

**Comment by rathboma** [comment]
Probably something simple in Postgres.js. A workaround in the meantime is to use v 1.7.5.

If you can figure it out that'd be amazing, otherwise I'll take a look tomorrow.

Again, sorry you hit this. :-/

**Comment by LuizHAP** [comment]
Oh, I think it's best to leave it to those who know what they're doing. I won't try xD

**Comment by rathboma** [comment]
1.8.7 is out!
