### ISSUE TITLE
BUG: Composite keys are only partially used to identify row for updates on table view

### ISSUE THREAD

**Issue by fabscav** [beekeeper-studio/beekeeper-studio#414]
**Describe the bug**
Composite keys are not being considered when updating a column value on the table view. Instead only the first column of the composite key is being used for the `UPDATE` query, resulting in the change intended for one row potentially being applied to multiple rows.

**Expected behavior**
Only the row of the modified column(s) should be affected by the generated queries.

**Screenshots / Gifs**
![composite_keys](https://user-images.githubusercontent.com/3975210/97120516-d333b500-1717-11eb-9c3c-16f725597911.gif)

**Version Information (please complete the following information):**
 - OS: Windows
 - App Version: 1.8.5

**Comment by rathboma** [comment]
Damn. Good find. Def add that to 1.9 milestone

**Comment by rathboma** [comment]
So I'm marking this as closed -- I disabled editing of tables with composite keys in 1.8.10. I'm going to replace this with a new issue for enabling editing for composite key tables.
