### ISSUE TITLE
FEAT: rename 7.x versions to 0.7.x

### ISSUE THREAD

**Issue by ibrahimBeladi** [beekeeper-studio/beekeeper-studio#415]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Rename 7.x versions to 0.7.x

**Describe alternatives you've considered**

**Additional context**

**Comment by rathboma** [comment]
Those old versions shouldn't be there. It's a problem from when we forked an old project. I keep trying to remove them, but we push them up all the time by mistake
