### ISSUE TITLE
BUG: Changing column width only increases label

### ISSUE THREAD

**Issue by evs-xsarus** [beekeeper-studio/beekeeper-studio#418]
See the video, if the column contents are shortened with ... , increasing the column has a weird result.

![2020-10-28_shortened-column-does-not-grow-bigger](https://user-images.githubusercontent.com/44158071/97426121-4b19ff00-1913-11eb-8dc0-70f036560448.gif)

**Comment by rathboma** [comment]
Good catch thanks!

@ghstng Can you look at this one?

**Comment by markkemper1** [comment]
Very similar issue on Mac: Version 1.8.7 (1.8.7)

![image](https://user-images.githubusercontent.com/102008/97510362-ae219980-19d8-11eb-9f37-60b845214159.png)

**Comment by ghstng** [comment]
pushed fix ed0130687fe97f4ca3f6cf7da24086886e64f3cb
