### ISSUE TITLE
Executing multiple queries show 1 row affected...

### ISSUE THREAD

**Issue by gnovaro** [beekeeper-studio/beekeeper-studio#42]
I executing multiple inserts and go well but show 1 row affected only..

![Captura de pantalla de 2020-05-05 15-16-58](https://user-images.githubusercontent.com/270990/81070525-a11d6500-8ee3-11ea-8c2c-815c33bb9e4a.png)

**Comment by rathboma** [comment]
I think it's only showing the output from the first query. You're right it should show output from all of them.

It is running all of them.
