### ISSUE TITLE
FEAT: Automatic limit for query result size

### ISSUE THREAD

**Issue by mkoske** [beekeeper-studio/beekeeper-studio#422]
**Describe the bug**

If you have large dataset (many columns and many rows) and don't remember to limit it manually, Beekeeper hangs and memory usage goes quite high.

**Expected behavior**

There should be at least configurable automatic limit, so that I don't need to manually limit. If then I want to raise or remove the limit, I could configure it.

**Version Information (please complete the following information):**

- OS: Windows 10 Pro
- App Version: 1.8.7

**Comment by rathboma** [comment]
So.

I'm not a big fan of in-line editing queries for folks, but I do have a way to do this. I plan to stream data to a file and cut off the data at 50k records.

It's on the backlog! I'd like to include in 1.9, but not sure if we'll have enough time :-). But please know we're on it!

**Comment by rathboma** [comment]
duplicate of #90

**Comment by mkoske** [comment]
Thanks!

**Comment by rathboma** [comment]
Yes! We'll make it configurable

**Comment by rathboma** [comment]
@mkoske are you on version 1.87? The 1.8 release has optimizations for wide tables and should help

**Comment by hsanjuan** [comment]
I also suffer from this but not so much for user queries but when opening the view of a table.

If I want to quickly inspect a table (usually the case when opening it), I don't need to request and see the 1M rows. Ideally it would open with a default search limit (i.e. 100) and then allow the user to decide whether to increase it.

**Comment by Arkanius** [comment]
I felt the same here. I need to export a csv file with 40M rows and I got the 50k rows limit. Any way to do this while we wait the next release? :)

**Comment by rathboma** [comment]
not easily from the app right now sorry :-(.

This is one of the next 'big' things I'll be working on.

**Comment by rathboma** [comment]
I'm replacing this issue with #471 and #472 which I think will fix all the problems we talk about in this issue!

So I'm not closing this issue because I don't care, but because I do :-)

**Comment by mkoske** [comment]
Thanks!
