### ISSUE TITLE
FEAT: Auto-remove quotes around pasted query strings

### ISSUE THREAD

**Issue by sorenlyhne** [beekeeper-studio/beekeeper-studio#423]
When I work with the debugger in VS Code I often need to test the queries that are generated by the code. Since the quires are stored in variable, I can copy the value of this variable to copy the query. However, they are stored as a string, and is thus copied with surrounding quotation marks. When pasting them into Beekeeper, I have to then remove the quotation marks, before I can run the query, which is inconvenient.

In dbeaver, which I come from, the quotation marks are automatically removed. Would be nice if Beekeeper could do the same. 

Thanks for a great project :)

**Comment by rathboma** [comment]
Nice. I like this. Lovely simple thing to help make things smoother.

Question - what if you copy a non-query string with quotation marks, what does dbeaver do then?

eg: "foo" or "Matthew"

**Comment by rathboma** [comment]
Note for future Matthew:
- When pasting into a query box, check for first/last characters containing " or ', if the contents of the string are a valid query, remove quote marks
- Add unit tests (don't forget!)

**Comment by sorenlyhne** [comment]
Hi Matthew.

Sounds good!

Non-query strings in quotation marks are not being changed.

**Comment by rathboma** [comment]
Thanks! Can you give a few query examples I can use in a unit test? 

Extra points for a big file with lots of examples :-D

**Comment by rathboma** [comment]
Note for implementation - make use of the `sql-query-identifier` library that we already use heavily.

**Comment by rathboma** [comment]
Should handle all types of quotes: ```, `'`, `"`.

**Comment by karaisnik** [comment]
It would be extremely helpful if it could also recognise and remove "+" character at the end of line. Many times you copy a query in quotes from an IDE and it looks like that:

"SELECT ..... " +
"FROM ..... " +
"WHERE ..... "
