### ISSUE TITLE
BUG: Portable Update location incorrect

### ISSUE THREAD

**Issue by Immortalin** [beekeeper-studio/beekeeper-studio#426]
**Describe the bug**
When the portable executable updates, it proceeds with default system installation.

**To Reproduce**
Run portable on 1.7.5. When update prompt shows up, click install. 
**Expected behavior**
Installs in same directory and replaces the old executable.

**Version Information (please complete the following information):**
 - OS: Windows 10, but I think the behaviour is the same on other OSes too.
 - App Version: 1.7.5

**Comment by rathboma** [comment]
Oh, that's interesting. Yeah it probably shoudn't even auto-update. We're just using the built-in auto-updater from Electron Builder. Thanks for the great bug report, we'll be sure to fix it.

**Comment by Immortalin** [comment]
I think it should update, but ask user before it does.

**Comment by rathboma** [comment]
This was fixed in 1.8.10! (It just sends you to the website to dl the new one)
