### ISSUE TITLE
BUG: `cmd+w` should close tab, not close window

### ISSUE THREAD

**Issue by iketiunn** [beekeeper-studio/beekeeper-studio#428]
**Describe the bug**
When there's one or more tabs, shortcut `cmd+w` should just close one tab, but instead window got closed.

**To Reproduce**
1. Click a table or `+` button to open a new tab
2. press `cmd+w`
3. Window closed

**Expected behavior**
Should just close one tab

**Screenshots / Gifs**

<img width="557" alt="Screen Shot 2020-11-03 at 2 30 51 PM" src="https://user-images.githubusercontent.com/10249208/97955570-71431180-1de1-11eb-8d60-10be924cd8cb.png">

**Version Information (please complete the following information):**
 - OS: Mac
 - App Version: Version 1.8.7 (1.8.7)

**Additional context**
Maybe the shortcut `cmd+w` is assign to `Close Window` causes this behavior, I did not take deep loop into it yet.

**Comment by rathboma** [comment]
It should close the tab, not the window, that could be an issue with menus.

Are you definitely on the latest version of the app?

**Comment by rathboma** [comment]
I'll take a look

**Comment by rathboma** [comment]
@iketiunn I can't replicate this. What version of MacOS are you on?

**Comment by iketiunn** [comment]
> @iketiunn I can't replicate this. What version of MacOS are you on?
> 
> ![Screen Shot 2020-11-06 at 4 07 53 PM](https://user-images.githubusercontent.com/279769/98419240-44ddfe00-204a-11eb-92e3-8f883c79197f.png)

10.15.7 (19H2)

Weird, I'll fully remove, install and try it again

<img width="834" alt="Screen Shot 2020-11-07 at 9 52 08 AM" src="https://user-images.githubusercontent.com/10249208/98428962-ea42b180-20de-11eb-9a48-b77266b91df2.png">

**Comment by iketiunn** [comment]
After clear up by `rm -rf  /Users/ike/Library/Application\ Support/beekeeper-studio` it became normal.

Maybe I had built an old version on my machine before that caused it. 😅

Thanks for having a look.

<img width="619" alt="Screen Shot 2020-11-08 at 10 29 40 AM" src="https://user-images.githubusercontent.com/10249208/98455580-94890a80-21ad-11eb-9200-4093b0d635a5.png">
