### ISSUE TITLE
BUG: Can't filter for null values in table view

### ISSUE THREAD

**Issue by mroeling** [beekeeper-studio/beekeeper-studio#429]
**Is your feature request related to a problem? Please describe.**
Can't search for NULL values when in data view

**Describe the solution you'd like**
Add WHERE <fieldName> IS NULL and WHERE <fieldName> IS NOT NULL to dropdown

**Describe alternatives you've considered**
sql is possible of course

**Additional context**
This gives an error when executing
![image](https://user-images.githubusercontent.com/2706186/97975424-6a100980-1dc9-11eb-9fd3-7e452fe695ef.png)

**Comment by rathboma** [comment]
Hah. Yes you are right.

**Comment by simonjharris** [comment]
Is this fixed? Still a problem for me

**Comment by Mrjwm** [comment]
Is it possible to add the null filter to the dropdown menu as requested in the original bug description/feature request?
