### ISSUE TITLE
FEAT: Allow search IN () and NOT IN ()

### ISSUE THREAD

**Issue by evs-xsarus** [beekeeper-studio/beekeeper-studio#430]
**Is your feature request related to a problem? Please describe.**
A lot of times, I want to search for a few records with specific values (mostly primary keys). Currently, I need to write a query or search one at the time using 'equals'.

**Describe the solution you'd like**
To be able to search on all values at once, the pulldown should allow for `IN` and `NOT IN`.

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/44158071/97988761-c5e48d80-1ddd-11eb-931a-e956351ad5a6.png)

NB This could even be expanded with JSON, REGEXP etc.

**Comment by evs-xsarus** [comment]
https://github.com/beekeeper-studio/beekeeper-studio/issues/429

**Comment by rathboma** [comment]
We're going to merge #427 soon which will allow you to specify a custom where clause and should solve this.
