### ISSUE TITLE
BUG: minimum window height is larger than screen height

### ISSUE THREAD

**Issue by mariusa** [beekeeper-studio/beekeeper-studio#432]
**Describe the bug**
on a 15" laptop, the window doesn't fully fit: bottom is cut out.
Seems like the title bar takes up extra space. Tried both native & client menu.
I also use vscode and that's similar, but works fine.

**To Reproduce**
1. install appImage
2. open beekeeper
3. right click on title bar, click maximize - doesn't do anything
4. try to resize the window manually - not possible to make it smaller than (laptop screen height + beekpeer menubar)

**Expected behavior**
have the window be maximized to height of screen

**Screenshots / Gifs**
![screen1](https://user-images.githubusercontent.com/1283842/98171471-76df4b00-1ef8-11eb-84df-7d25af543ff7.png)

**Version Information (please complete the following information):**
 - OS: fedora 33
 - App Version 1.8,7

**Additional context**
Tried snap too, same issue.

**Comment by rathboma** [comment]
Can you let me know what your monitor resolution is?

@ghstng another one for you maybe?

**Comment by mariusa** [comment]
Sure: 1366x768

**Comment by rathboma** [comment]
Hmm, looks like I have minimum dimensions set to 800x600, I've confirmed I can shrink it to that size. You don't have any sort of display scaling on by any chance do you?

![image](https://user-images.githubusercontent.com/279769/99441048-fc8dce00-28dc-11eb-8732-2d670661fdf9.png)

**Comment by mariusa** [comment]
Ah, I do have gnome fonts set to large. 
In the meantime I changed the laptop, so feel free to close if this is isn't valid. Thanks!
