### ISSUE TITLE
BUG: Editing table data on this wide table doesn't work properly

### ISSUE THREAD

**Issue by ceecko** [beekeeper-studio/beekeeper-studio#433]
**Describe the bug**
On Mac when a table has a lot of columns (in my case 30+), editing data in columns close to the end is not possible. Clicking a cell to edit data scrolls the view to the left and the selected cell does not have focus.

**To Reproduce**
1. Click on a table with 30+ columns
2. List with data is shown
3. Scroll to the right to the last column
4. Click one of the last cells in one of the rows
5. View scrolls to the left and no cell has focus
6. It's not possible to edit data in the selected cell

**Expected behavior**
It should be possible to edit data in tables with many columns.

**Version Information (please complete the following information):**
 - OS: Mac
 - App Version 1.8.7

**Comment by rathboma** [comment]
Thanks for the report!

@ghstng can you take a look at this one?

**Comment by rathboma** [comment]
@ceecko if you can record a gif / video of this happening it would be SUPER helpful.

**Comment by ceecko** [comment]
I have just replicated this issue on Windows 10 with `v1.8.7`. 
It applies to both MacOS and Windows 10. See attached video.

[Beekeeper-Studio 2020-11-08 12-19-30.zip](https://github.com/beekeeper-studio/beekeeper-studio/files/5506239/Beekeeper-Studio.2020-11-08.12-19-30.zip)

**Comment by rathboma** [comment]
I'm having trouble replicating this.

Some questions:
- Does it happen with all column types?
- Does it only happen with the columns that are empty?
- Can you confirm this table has a primary key?

Thanks,

Matthew

**Comment by ceecko** [comment]
I can replicate with the following table.

```
CREATE TABLE  `_test` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `a1` varchar(45) COLLATE utf8_unicode_ci NOT NULL,
  `a2` varchar(45) COLLATE utf8_unicode_ci NOT NULL,
  `a3` varchar(45) COLLATE utf8_unicode_ci NOT NULL,
  `a4` varchar(45) COLLATE utf8_unicode_ci NOT NULL,
  `a5` varchar(45) COLLATE utf8_unicode_ci NOT NULL,
  `a6` varchar(45) COLLATE utf8_unicode_ci NOT NULL,
  `a7` varchar(45) COLLATE utf8_unicode_ci NOT NULL,
  `a8` varchar(45) COLLATE utf8_unicode_ci NOT NULL,
  `a9` varchar(45) COLLATE utf8_unicode_ci NOT NULL,
  `b1` varchar(45) COLLATE utf8_unicode_ci NOT NULL,
  `b2` varchar(45) COLLATE utf8_unicode_ci NOT NULL,
  `b3` varchar(45) COLLATE utf8_unicode_ci NOT NULL,
  `b4` varchar(45) COLLATE utf8_unicode_ci NOT NULL,
  `b5` varchar(45) COLLATE utf8_unicode_ci NOT NULL,
  `b6` varchar(45) COLLATE utf8_unicode_ci NOT NULL,
  `b7` varchar(45) COLLATE utf8_unicode_ci NOT NULL,
  `b8` varchar(45) COLLATE utf8_unicode_ci NOT NULL,
  `b9` varchar(45) COLLATE utf8_unicode_ci NOT NULL,
  `c1` varchar(45) COLLATE utf8_unicode_ci NOT NULL,
  `c2` varchar(45) COLLATE utf8_unicode_ci NOT NULL,
  `c3` varchar(45) COLLATE utf8_unicode_ci NOT NULL,
  `c4` varchar(45) COLLATE utf8_unicode_ci NOT NULL,
  `c5` varchar(45) COLLATE utf8_unicode_ci NOT NULL,
  `c6` varchar(45) COLLATE utf8_unicode_ci NOT NULL,
  `c7` varchar(45) COLLATE utf8_unicode_ci NOT NULL,
  `c8` varchar(45) COLLATE utf8_unicode_ci NOT NULL,
  `c9` varchar(45) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
```

And with this data
```
insert into _test values
(0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1),
(0,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2);
```

I scroll to the right and try to click number `2` in column `c7`

**Comment by rafmst** [comment]
I recorded my screen to better show this https://youtu.be/6SvioDDlU7M

**Comment by rathboma** [comment]
@ghstng can you look to see if this is something we're doing or something in Tabulator? It looks to be tabulator related, but want to be sure

**Comment by rathboma** [comment]
nm, def tabulator, reproduced

**Comment by rathboma** [comment]
@ceecko I think this is fixed in the latest release? Can you check? (if so can you close the issue)

**Comment by ceecko** [comment]
I confirm this has been fixed. Thank you for the update!
