### ISSUE TITLE
FEAT: Ability to edit SQL commands like on terminal (Bash-like).

### ISSUE THREAD

**Issue by bnsv** [beekeeper-studio/beekeeper-studio#435]
Hello, first I want to thank you for this great tool. It is helpful and I really love it.

Secondly, I want to suggest a little improvement that I think will helpful for some. That is the ability to editing of keyboard input for any command while querying. I mean the ability to move like terminal/bash keys (like alt+b to move backward a word, ctrl+a to move cursor to the beginning of line, ctrl+e move to eol). I usually use [rlwrap](https://github.com/hanslub42/rlwrap) for some apps that don't have this ability. I hope Beekeper Studio will adopt this feature. Thank you.

**Comment by rathboma** [comment]
Yes, this drives me INSANE. It's codemirror. There's no good way to unbound the navigation shortcuts in codemirror (our editor plugin). Rest assured we'll do it because that's how I like to set up my Linux desktop as well.

Sorry for it being annoying.

**Comment by bnsv** [comment]
No worries, its not urgent. And again thank you for the good work.
