### ISSUE TITLE
Queries not saving?

### ISSUE THREAD

**Issue by krutoo** [beekeeper-studio/beekeeper-studio#437]
Operating System: Ubuntu
App Version: 1.8.7

I save my query and i get this notice
![image](https://user-images.githubusercontent.com/13140130/98659410-e379a000-2365-11eb-9d96-e04271fc090f.png)

but Saved Queries tab is empty 
![image](https://user-images.githubusercontent.com/13140130/98659335-d066d000-2365-11eb-8b91-83595a6f9b42.png)

Where are saved queries stored?

**Comment by rathboma** [comment]
That's where they should be...

Hmm, let me investigate.

Does the tab header change?

You can debug by going to help - add beekeepers database, then look through the saved queries table

**Comment by krutoo** [comment]
@rathboma i have same issue on mac os catalina 10.15.7

![image](https://user-images.githubusercontent.com/13140130/98703471-56523d80-239d-11eb-94a8-a270b8f54280.png)

After saving nothing has change in tab

Tab header changes to target name

**Comment by krutoo** [comment]
there is no errors in devtools 

![image](https://user-images.githubusercontent.com/13140130/98704052-01fb8d80-239e-11eb-9194-554979ea5ba2.png)

**Comment by rathboma** [comment]
Thanks both! I'll look into and fix for a point release this week

**Comment by rathboma** [comment]
@krutoo I'm having trouble replicating this error. Queries save just fine for me.

Just in case - what database are you connected to?

**Comment by rathboma** [comment]
Oh oh -- when you connected, did you leave the 'database' field blank?

**Comment by rathboma** [comment]
I think that's the issue, I've fixed this in master.

**Comment by krutoo** [comment]
> Oh oh -- when you connected, did you leave the 'database' field blank?

What is a 'database field' ?

![image](https://user-images.githubusercontent.com/13140130/99481837-cacc4400-297c-11eb-87da-f437ab53d19b.png)

How can i update beekeper? snap has no updates now

**Comment by rathboma** [comment]
I'll push an update tomorrow or Thursday!
