### ISSUE TITLE
QUESTION: Instalation on VS Code

### ISSUE THREAD

**Issue by Wultyc** [beekeeper-studio/beekeeper-studio#439]
**Details:**
I would like to konw if its possible to install Beekeeper on VS Code studio. The UI is very similar with VS code so I'm suposing the base the application is VS Code and thats why I'm hopping theres an available extencion or at least plan to do it.

***Why this is relevant for me***
VS code is the tool I mostly use during when I'm developing. When I work with DBs like MongoDB and FaunaDB I have a plugin that allows me to acess the DB inside VS Code and having to switch the application when I use other DB such as MySQL or MariaDB became anoying.

**Personal remark**
This application looks awsome. I realy like the design you created for it and I'm seriuosly thinking to adopt this tool

**Comment by rathboma** [comment]
Hey!

It is not available as a vscode plugin for now. While they look similar they are actually very different codebases with almost no shared components.

There are vs code plugins that perform a similar function if you really need to stay inside the app, but we think this functionality deserves its own space in a developers taskbar/dock :-)

**Comment by rathboma** [comment]
Going to close the issue but not because I don't care, it's just not something I can solve :-)

**Comment by Wultyc** [comment]
Well thanks for the fast reply @rathboma . I understand your point. I only want to know if that kind of feature were in the roadmap.
Anyways I gave a star on this repo and definitely I will try this app in my dev machine.

**Comment by rathboma** [comment]
Sorry not on our roadmap for the foreseeable future! How you give us a try though
