### ISSUE TITLE
Show multiple result tables if query returned multiple results

### ISSUE THREAD

**Issue by rathboma** [beekeeper-studio/beekeeper-studio#44]
currently if you execute a query with multiple select statements you only get to see the results of the first statement.

There should be some way to see the results of all the queries.

![Screen Shot 2020-05-05 at 5 51 16 PM](https://user-images.githubusercontent.com/279769/81123598-121b4780-8ef9-11ea-9708-30e74a1a9371.png)

**Comment by rathboma** [comment]
@gregorygarden The only ways I can think to do this:

1. Have tabs in the result area for each result if there are more than one
2. Have tab-like pills or a dropdown in the footer to switch the resultset being viewed

Not sure I like any of these?

**Comment by manngo** [comment]
I don’t know whether this should be added here or as a new bug report. I think it’s the same problem.

When you run something like:

```mysql
USE whateverdb;
SELECT * FROM whatevertable;
```

The result is

> Query Executed Successfully. No Results

Evidently only the first statement is executed.

**Comment by rathboma** [comment]
released in 1.4

**Comment by manngo** [comment]
For anyone watching this, there’s a new popup in the status bar which lets you choose between results sets.
