### ISSUE TITLE
QUESTION: How to proceed after saving connection for the first time?

### ISSUE THREAD

**Issue by geraldlwk** [beekeeper-studio/beekeeper-studio#446]
**Details:**
Hi, I am very new to SQL and I'm trying to follow along with a Youtube tutorial. It requires me to use PopSQL but one of the comments mentioned Beekeeper as a free substitute as opposed to 2 weeks trial with PopSQL. Apologies if I am making a terrible rookie mistake here. 

After I've filled up the fields here and clicked "save", a pop up saying "connection saved" comes up but then I can't open a new tab to input my queries. Should this page go away on its own? Is it because I've not filled up "default database"? If yes, what am I supposed to write in there? 

**Version Information [might be relevant to your issue]**
Operating System: Windows 10
App Version [help -> about]: 1.8.7

**Screenshot / GIF [if appropriate]**:
![image](https://user-images.githubusercontent.com/74562098/99293387-8ad26780-287d-11eb-9c65-7e37796a8631.png)

**Comment by saberworks** [comment]
Click the yellow "Connect" button or double-click the connection name in the menu at the left.

**Comment by geraldlwk** [comment]
> Click the yellow "Connect" button or double-click the connection name in the menu at the left.

Thank you for the response. When I do that, I get this error message. Am I doing something wrong here? 
![image](https://user-images.githubusercontent.com/74562098/99364713-484a7280-28f1-11eb-93dc-1382c5a5143d.png)

**Comment by rathboma** [comment]
Can you log in using those details from other apps?

**Comment by geraldlwk** [comment]
> Can you log in using those details from other apps?

Hey hi. I made a really silly mistake here. Basically, I didn't know the server would shut down when I shut down my PC. Once I restarted the server, everything was working fine again. Thanks for following up!

**Comment by rathboma** [comment]
No problem! Please reach out if you have any other questions, here to help (with the app or general DB questions :-)
