### ISSUE TITLE
BUG: Table is not showing if the table's name is a reserved word.

### ISSUE THREAD

**Issue by nafkhanzam** [beekeeper-studio/beekeeper-studio#447]
**Describe the bug**
Table is not showing if the table's name is a reserved word. For example my table name is `Order`

**To Reproduce**
1. Connect to database
2. Open a table named `Order`
3. The contents are not showing

**Expected behavior**
Should show the table contents

**Screenshots / Gifs**
![image](https://user-images.githubusercontent.com/48153421/99440203-cc7c1480-2948-11eb-8ab7-c3f3ded7914e.png)

**Version Information (please complete the following information):**
 - OS: Linux Mint 19
 - App Version 1.8.7

**Additional context**
-

**Comment by rathboma** [comment]
Yes. This should be fixed in the upcoming bug fix release.
