### ISSUE TITLE
BUG: Postgres "relation <schema>.<tablename> does not exist"

### ISSUE THREAD

**Issue by PaulAik** [beekeeper-studio/beekeeper-studio#452]
**Bug Description**
Table contents (data & columns) aren't displaying when I try to open the table from the tree. Results are being returned when I manually write the _select_ query, so I'm guessing something might need tweaked Beekeeper's internal query to show the results?

Specific scenario is a database created by Entity Framework (.Net Core), on Windows inside a Docker container (postgres' official image). 

**To Reproduce**
1. Connect to a Postgres database on Windows
2. Open any table
3. Note there are no columns or results
4. See error in error console (dev tools)

**Expected behavior**
Columns and results are shown for the table I opened

**Screenshots / Gifs**

When trying to open from the tree:
![image](https://user-images.githubusercontent.com/99102/99795653-07866f80-2b24-11eb-8150-d517dc2c17a8.png)

Manually entering the query (note invalid column definition warnings)
![image](https://user-images.githubusercontent.com/99102/99795625-fb9aad80-2b23-11eb-9f56-4e948f1dc5a9.png)

**Version Information (please complete the following information):**
- OS: Windows 10
- App Version: 1.8.10
- Environment: Docker, postgres image

**Additional Information**

Just a hunch, but could this be something to do with case-sensitivity? I noted the error message states the table name in all lowercase.

Works: `select * from "Organisations"`

Doesn't work: `select * from "organisations"`

**Comment by canove** [comment]
Same here! No results when clicking on table name, but works with query. 
In the bottom right corner, I get an error about "Zero or multiple primary keys found"

I've downgraded to 1.8.7 and its fine again:

![image](https://user-images.githubusercontent.com/24817866/99830461-8091c100-2b3c-11eb-8454-ac9fc43b49f7.png)

**Comment by MasterOdin** [comment]
This is probably one of my least favorite things about postgres. By default, for any reference (table, column, etc.) that is not quoted, it lowercases it before looking it up. `TABLE`, `Table`, `tAbLe`, and `table` are all treated the same and the lookup happens for `table`. The only way to reference a table that uses a mixed case is to ensure it's quoted.

**Comment by rathboma** [comment]
@MasterOdin thanks for that. I'll update my selectTop function and add a unit test for this.
