### ISSUE TITLE
Microsoft Edge - Download Blocked

### ISSUE THREAD

**Issue by darthink** [beekeeper-studio/beekeeper-studio#453]
When using Microsoft Edge (Version 87.0.664.41 (Official build) (64-bit)) to download the file from Beekeeper Studio website, it gives the following warning: 

`Beekeeper-Studio-Setup-1.8.7.exe was blocked because it could harm your device.`

![image](https://user-images.githubusercontent.com/1986347/99813972-59c09400-2b16-11eb-8c09-7f3a83813211.png)

Not necessarily an issue, but wanted to point this out.

**Comment by rathboma** [comment]
I have submitted my app to Microsoft Defender, but still this happens. I don't really know how else to resolve it. You can click the three dots then click download anyway.

I pay a company for a valid signing cert too.

**Comment by rathboma** [comment]
I'm going to close this, but will try to do more to opt out from these issues.
