### ISSUE TITLE
FEAT: Allow editing of tables with composite primary keys

### ISSUE THREAD

**Issue by rathboma** [beekeeper-studio/beekeeper-studio#455]
Currently you can only edit tables with a single PK column.

We want to edit tables with composite primary keys.

Replacing #414

**Comment by baymaxdarwin** [comment]
@rathboma any update on this?.

**Comment by rathboma** [comment]
Not currently I'm afraid. We're currently pushing towards a big feature release, so will circle back on big bugs / omissions after that.

**Comment by baguilarq** [comment]
I really  hope this feature will be up soon. As far, great job guys :)

**Comment by lnking81** [comment]
Not really usable until this implemented(

**Comment by cakoose** [comment]
@rathboma: If it's not too much trouble, can you link to the parts of the codebase that deal with this feature? That might make it easier for an outside to start working on it.

(I'd definitely take a look, though obviously I can't make any promises about whether I'll have the ability/time to actually complete the task.)

**Comment by Pckool** [comment]
Please, when is this feature being added?

**Comment by samputer** [comment]
Thanks for the great work with Beekeeper Studio, though I'd also very much like to see this. Having to alternate with other tools or write queries manually to perform simple updates on tables with composite keys.

**Comment by rathboma** [comment]
Oh, this is done.
