### ISSUE TITLE
FEAT: Allow the sidebar to collapse

### ISSUE THREAD

**Issue by kurogosane1** [beekeeper-studio/beekeeper-studio#458]
Hi I just wanted to make a recommendation and not an issue. 
If we could get the side bar to be hidden and expand if we would like it to expand. 
Thats my only request. Thanks

**Comment by rathboma** [comment]
Yes! Good idea. Certainly a ui improvement for small screens or window tiling

**Comment by cbluth** [comment]
i came here to make a similar suggestion:
i think it would be nice to allow the sidebar to squash down to as small as possible without actually collapsing and disappearing.

![image](https://user-images.githubusercontent.com/6709636/103478764-2fc2e880-4dc9-11eb-9197-8cce2233274c.png)

**Comment by rathboma** [comment]
Oh, it does collapse now if you click whichever icon is currently selected!
