### ISSUE TITLE
SSH Tunneling with postgres server does not work

### ISSUE THREAD

**Issue by AuxBot-Python** [beekeeper-studio/beekeeper-studio#460]
when I go to connect to my server using any of the options I get an error saying connection terminated due to connection timeout. I am able to ssh onto this server on three devices I have tested standard username and password authentication and key authentication and it all works so it must be beekeeper. I have been at it for 5 hours and I just cannot get it to connect.

I am using putty key authentication btw because apparently beekeeper supports it. I also tried normal authentication keys it still didn't work.

**Comment by rathboma** [comment]
Hmm, can you enable debugging and check the log file for any errors?

https://docs.beekeeperstudio.io/troubleshooting/#how-to-debug-beekeeper-studio

I'm assuming you're on windows? Are you using a hostname for the psql server that resolves after sshing?

Eg:
Ssh: psql.example.com
Host: localhost

**Comment by yogski** [comment]
I've stumbled upon similar problem. I'm not sure this is exactly what OP needs, but this is my workaround to connect.
- Start SSH tunneling to Postgresql server. 
Assuming Windows environment, one can do 
`ssh -f -N [user]@[host] -L 5433:localhost:5432`
using Git Bash / WSL. 
In Putty, basically try to create tunnel to `[host]:5432` and set port forwarding to `5433`. 
Port `5433` is chosen to avoid conflict with Postgresql in local machine.

- In Beekeeper Studio, connect to database with host `localhost` and port `5433` **without** SSH tunnel. Should be able to connect by then.

**Comment by rathboma** [comment]
@yogski so using the ssh tunnel in Beekeeper Studio isn't working for you either from Windows?

**Comment by yogski** [comment]
Hi @rathboma, so I tried again to connect via SSH tunnel with 2 available methods: user/pass and key file. 
1. User/pass method worked as expected.
2. Key file method didn't work and gave me error message 
`Error while signing data with privateKey: error:06000066:public key routines:OPENSSL_internal:DECODE_ERROR`
No additional information from logs.

I use remote database for development so I often choose latter option. Hence the workaround on my previous comment.

Additional information
- OS : Windows NT 10.0 64-bit
- Beekeeper version : 1.8
- Connection : Postgresql

**Comment by rathboma** [comment]
Does your private key have a password? If so, did you enter it?

Thanks so so so much for digging a little deeper for me.

**Comment by yogski** [comment]
Yeah, my key file has passphrase but it seems to work correctly. If I don't put it, I got 
`Cannot parse privateKey: Encrypted private openSSH key detected, but no passphrase given`
In case of wrong passphrase, I got
`Cannot parse privateKey: OpenSSH key integrity check failed -- bad passphrase?`

Glad to help. This project has been helpful for my work as well.

**Comment by AuxBot-Python** [comment]
I seemed to have fixed my problem I'm not sure how but I am now able to connect to my server through putty ssh keys. I think the initial problem was the user and password for the Postgres connection were incorrect I'm not sure.

**Comment by rathboma** [comment]
Ok so seems like everything works? Let me know if I'm misunderstanding.

If so, my takeaway is that we need to make it more clear where the errors are coming from!

I'll look to add db/ssh tags to errors and add some clarification to the missing keyfile password error.

**Comment by rathboma** [comment]
@yogski oh, I re-read, so it doesn't work even if you specify the passphrase?

**Comment by AuxBot-Python** [comment]
yes I think the best solution here is to just clarify to the user what error is occurring and where it is occurring from. Rather than them trying to spend hours troubleshooting.
