### ISSUE TITLE
FEAT: Double click to open new windows for tables

### ISSUE THREAD

**Issue by gabrielsanttana** [beekeeper-studio/beekeeper-studio#465]
### Description
It's a little weird to have a new window being opened everytime we click on a table tab on the sidebar, ending, sometimes, with multiple windows opened for the same table, what makes the interface a bit more clutter.

### Solution
I think it would cool to have to double click the tabs to actually open a new window with the table data. I've been a longe time user of DBeaver, and I'm considering switching completely to Beekeeper Studio, so having this change would be nice to keep the interface more clean and helpful for other users as well. 

### Additional context
The tables on the sidebar:

![image](https://user-images.githubusercontent.com/47339825/101292868-e5157700-37f0-11eb-8f31-c084e08d23be.png)

**Comment by rathboma** [comment]
I think this should be a user setting. I'll add it to #197 . I think this is probably a personal preference thing. I've tried both ways, and I've aligned with how text editors like VSCode work over how DBeaver and co work. What I can do is disable double open on double click.

**Comment by rathboma** [comment]
Captured this in two places now so will close this issue, but I still care about this and I won't forget it!

**Comment by gabrielsanttana** [comment]
Great. Thank you for the consideration!
