### ISSUE TITLE
BUG: Don't prompt for update if there's already a prompt for update

### ISSUE THREAD

**Issue by lachieh** [beekeeper-studio/beekeeper-studio#467]
**Describe the bug**
There is an excessive number of update notifications that occur when the application is left open.

**To Reproduce**
This is only really reproducible over time and while there is an update available. Leave the application open for a few hours and you should return to multiple update notifications.

**Expected behavior**
Only one update notification should be visible

**Screenshots / Gifs**
<img width="435" alt="Screen Shot 2020-12-08 at 9 31 50 AM" src="https://user-images.githubusercontent.com/1687902/101497272-cae6b080-3938-11eb-8f6a-eb5663c992d7.png">

**Version Information (please complete the following information):**
 - OS: MacOS
 - App Version < 1.8.11

**Comment by rathboma** [comment]
That's hilarious and terrible at the same time.

in 1.8.11 I've changed the update frequency to be daily (it was every 4 hours), but I'll have it add a check to not display a notification if one is already open.

**Comment by lachieh** [comment]
Well then apparently I had it open but had used it in about 2 days 😂 

Thanks for the great project.
