### ISSUE TITLE
FEAT: Refresh data button for tables opened in a tab

### ISSUE THREAD

**Issue by mshollyintellicon** [beekeeper-studio/beekeeper-studio#468]
**Is your feature request related to a problem? Please describe.**
I noticed that while I can refresh the "Tables and Views" sidebar, the refresh button does not update a table that is opened in a tab. For example, working on a local WordPress database - If I add a comment via an external API, the new database row does not appear unless I close and/or open the 'wp_comments' table in a new tab. I wasn't sure if this is a feature or bug report, so please adjust if I'm wrong. 

**Describe the solution you'd like**
A refresh button for a tab, maybe near the pagination area? Or on the left side of the pagination row?

**Describe alternatives you've considered**
I tried right-clicking an open tab or running an empty query at the top of an open tab. I'm assuming you probably don't want a tab to live refresh, as a database snapshot might be easier to work with. This would partially replicate a "Run Query" tab, but with the UI versus building a query. 

Thank you for your work on this! It's a huge help for my Local By Flywheel workflow.

**Comment by rathboma** [comment]
Yes! This makes total sense. Not sure where we can put the button, but maybe in the right click menu.

You can re-click the search button, but I realize that doesn't retain pagination location.

@ghstng where could we fit a button in for this?

**Comment by rathboma** [comment]
This is fixed.

**Comment by msholly** [comment]
Looks great! I like the UI choice, nice work
