### ISSUE TITLE
FEAT: Clickhouse support as database source

### ISSUE THREAD

**Issue by Slach** [beekeeper-studio/beekeeper-studio#470]
Thanks a lot for great product!
It  would be nice add http://clickhouse.yandex/docs/en/ as Database source
ClickHouse is the fastest Open source column oriented Database for BI and BigData ;)

nodejs interface is already exists 
https://clickhouse.tech/docs/en/interfaces/third-party/client-libraries/

**Comment by rathboma** [comment]
Yeah! Would love that. I'll add to accepted enhancements, but not likely to get to this for a while, but PRs welcome :-)

**Comment by rathboma** [comment]
Notes for the future:
- docker image - https://github.com/jeefy/docker-clickhouse
- Node driver (http): https://github.com/apla/node-clickhouse

**Comment by MasterOdin** [comment]
I would recommend using https://hub.docker.com/r/yandex/clickhouse-server/ for a docker image. Includes also easy way to connect with a native client (that also runs under docker) for testing queries.

**Comment by mike-seekwell** [comment]
I'd consider using https://github.com/TimonKK/clickhouse over https://github.com/apla/node-clickhouse. The first one is maintained by a clickhouse employee.


It might also be worth looking at https://github.com/CraZySacX/node-jdbc. It could knock out several connectors at once.

**Comment by alexey-milovidov** [comment]
ClickHouse has REST API, which means that you can simply use `fetch`.

**Comment by redxtech** [comment]
is there any progress on this? i would love to see clickhouse sources supported!

**Comment by adambenhassen** [comment]
We would greatly appreciate the inclusion of ClickHouse support!

**Comment by Maksim-Burtsev** [comment]
Will ClickHouse support appear in the near future?

I and a lot of people dont want to use another tool ;)

@rathboma

**Comment by NicholasKao1029** [comment]
Is there an update on this?

**Comment by numbata** [comment]
@NicholasKao1029 looks like the feature is on the way #2345

**Comment by azmy60** [comment]
Yes, we've added this for the next beekeeper update. Thanks for pointing out!

**Comment by numbata** [comment]
@azmy60 Thanks to you and everyone else involved for making such a great product!
