### ISSUE TITLE
BUG: CREATE TRIGGER returns SQLITE_ERROR: incomplete input

### ISSUE THREAD

**Issue by audiomuze** [beekeeper-studio/beekeeper-studio#476]
**Describe the bug**
Running the following query throws `SQLITE_ERROR: incomplete input`

**To Reproduce**
Run this on a table with a column named sqlmodded 
```
CREATE TRIGGER sqlmods
         AFTER UPDATE
            ON alib
      FOR EACH ROW
          WHEN old.sqlmodded IS NULL
BEGIN
    UPDATE alib
       SET sqlmodded = TRUE
     WHERE rowid = NEW.rowid;
END;

```
**Expected behavior**
It should generate a table trigger called sqlmods

**Screenshots / Gifs**
![image](https://user-images.githubusercontent.com/6852511/102018891-d2fb8180-3d78-11eb-8df6-4ca4b468b5c9.png)

**Version Information (please complete the following information):**
 - OS: Arch Linux x64
 - App Version 1.8.11

**Additional context**
Anything else you think might be helpful

**Comment by rathboma** [comment]
Very interesting. Thanks for finding this bug! I'll prioritize a fix for this.

**Comment by rathboma** [comment]
Blocked on https://github.com/sqlectron/sql-query-identifier/pull/9

**Comment by rathboma** [comment]
Fixed in master

**Comment by rathboma** [comment]
For context - the sqlite node driver requires that you pass queries to it one by one, so we have to manually split out multiple-queries when you submit them.

This means we need a sql parser. We use a package we maintain, but that didn't identify triggers. Now it does. It's a pain point of the sqlite driver, and client interface in general.
