### ISSUE TITLE
BUG: PostgreSQL Array editing does not work

### ISSUE THREAD

**Issue by dalisoft** [beekeeper-studio/beekeeper-studio#478]
**Describe the bug**

**To Reproduce**
1. Connect to any test Postgres DB (ElephantSQL in my case)
2. Load any table containing array
3. Try edit Array item

**Expected behavior**
Should edit Array item

**Screenshots / Gifs**
If applicable, add screenshots or GIFS to help explain your problem.
<img width="929" alt="image" src="https://user-images.githubusercontent.com/3511344/102098850-7916bc80-3e49-11eb-9d5d-06dded2438f0.png">

**Version Information (please complete the following information):**
 - OS: macOS Catalina 10.15.7
 - App Version: 1.8.11 (1.8.11)

**Additional context**
DevTool log

<img width="1421" alt="image" src="https://user-images.githubusercontent.com/3511344/102099170-d4e14580-3e49-11eb-846c-5a0809e66d71.png">

**Comment by rathboma** [comment]
I did test this, so it must be a regression. Good find. I'll prioritize a fix for this.

**Comment by rathboma** [comment]
Note to self:

This will require several pieces:
- tabulator will deserialize this back as a string, does that need to change?
- Should be able to copy how the data is passed from the UI and test the behavior in the integration tests
-

**Comment by dalisoft** [comment]
@rathboma Thanks, i really excited how software is good quality and well designed. Loved at first look. I happy to find bugs in future as i really want use it as daily Postgres client.
