### ISSUE TITLE
Windows integrated login for MSSQL

### ISSUE THREAD

**Issue by hjone72** [beekeeper-studio/beekeeper-studio#48]
As the title says, I'd really like for windows integrated login for MSSQL.

Thanks,

**Comment by kryptonianson** [comment]
This is a must for me as well. Thanks for considering.

**Comment by silverfrost** [comment]
Absolutely - I have databases that only use this. Also... I think it is trivial, only requiring a small change to the connection string.

**Comment by rathboma** [comment]
@silverfrost interesting. I'd thought it was really hard to do. Let me look into it

**Comment by rathboma** [comment]
Might just need to add `domain`: https://github.com/tediousjs/node-mssql#general-same-for-all-drivers

**Comment by andrewgalbraith** [comment]
Would also love to have this; tried to work around this to try and get it to work without luck.

**Comment by JamesDBartlett** [comment]
This missing feature is the only barrier keeping me from using Beekeeper Studio as my go-to app for dashing off quick, ad-hoc queries (an activity I perform several times per day on average). I have a bit of background in Node & React, so if you know there's a simple solution, but just haven't had the time to implement it, let me know, and I might take a crack at it.

**Comment by rathboma** [comment]
I'm not very experienced in using Windows integrated login for SQL Server.

How does this work in other apps? Does it just get the credentials from the OS, or do you have to enter user/domain/password in the app?

**Comment by JamesDBartlett** [comment]
I'm not very familiar with all the inner workings, but as an example, [Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio) (a variant of VS Code, designed specifically for working with MSSQL servers) connects to the target database by hostname (resolved by the domain controller, most likely) and instance name. It transparently passes the logged-in Windows domain account to the server for authentication, so the user never gets a password prompt. 

Azure Data Studio is [open-source](https://github.com/microsoft/azuredatastudio), so it might be worth digging into its guts to see how it handles this particular bit of Microsoft magic.

**Comment by rathboma** [comment]
Can you folks test #134 and see if you set `domain`, but leave the password blank it allows you to log-in to your SQL Server instance?

**Comment by rathboma** [comment]
should be able to get a windows download from - https://github.com/beekeeper-studio/beekeeper-studio/actions/runs/109655006

**Comment by JamesDBartlett** [comment]
@rathboma I get the following error message when I try to log in without a password:
> Login failed. The login is from an untrusted domain and cannot be used with Windows authentication.
However, when I enter my password, the connection is successful, so it's _almost_ working.

**Comment by rathboma** [comment]
@JamesDBartlett Ok, so it IS doing windows integrated log-in now, but it is not passing through your credentials.

I'm not sure exactly why. At least this version is usable, even if not ideal.

My gut is that there's something in the main `process.env` it needs that it doesn't have available in the renderer environment.

**Comment by andrewgalbraith** [comment]
Tested the latest build and when populating the pertinent fields; username, password and domain with SSL enabled, it tested successfully and connected without issue. It also ran a SELECT statement successfully after that, so I’ll give it some more time tomorrow when I’m back in the office. Definitely excited to try some more. Thank you!!
________________________________

**Comment by kryptonianson** [comment]
So far this looks like it did the trick for me. Thank you!

**Comment by JamesDBartlett** [comment]
@rathboma This is usable enough for now. Can we expect #134 to be merged any time soon?

**Comment by rathboma** [comment]
I'm looking to merge it this weekend (along with a large ssh fix) and have a new release out ~monday! 

Thanks all for testing the build!

**Comment by rathboma** [comment]
Merged and released in 1.4

**Comment by JamesDBartlett** [comment]
@rathboma Thanks for the update! I'm now happily using Beekeeper Studio as my go-to editor for ad-hoc queries.

**Comment by andrewmorris-me** [comment]
I'm trying to get this to work with (localdb)\mssqllocaldb. Is this compatible with SQL Server Express as well?

**Comment by rathboma** [comment]
Looks like host should be localhost and database should be mssqllocaldb?

**Comment by andrewmorris-me** [comment]
Thanks for the reply, seems I'm still running into the same issue. Here is an example of how a connection string I'm using with a .net core web app in localhost, with the [SQL Server Express LocalDB](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/sql-server-express-localdb?view=sql-server-ver15),

```
 "ConnectionStrings": {
    "DefaultConnection": "Server=(localdb)\\mssqllocaldb;Database=MyWebAppsDatabaseName;Trusted_Connection=True;MultipleActiveResultSets=true"
  }
```

The extra `\` in `(localdb)\\mssqllocaldb;Database` just acts as an escape, please ignore that. 

I think I'm just not piecing the setup correctly in your form, if other's are able to connect to MSSQL? Just wondering what it could be?

I'm enjoying Beekeeper Studio too, thanks so much all your effort with this.

**Comment by rathboma** [comment]
Ok, I looked into this a little. So LocalDB is different from a normal SQL Server instance. The computer isn't actually running a SQL Server until you connect to it with this special URL.

Seems like DBeaver can't connect to these either. I'll add a new issue to track this, thanks for bringing it to my attention!

**Comment by rathboma** [comment]
@andrewmorris-me see https://github.com/beekeeper-studio/beekeeper-studio/issues/505

Looks like the NodeJS SQL Server driver does not support LocalDB, so we're heavily blocked.
