### ISSUE TITLE
BUG: Renaming successfully  a table in a MySql DB is not updating the name in the Tables list

### ISSUE THREAD

**Issue by Cfun1** [beekeeper-studio/beekeeper-studio#483]
**Describe the bug**
After renaming a table successfully on MySql database, the name in tables and views does not change even when pressing refresh database, it does update the new name only after I select another database and come back to the initial one.

**To Reproduce**
1. Connect to a Mysql server
2. Rename an existing Table in the current DB.
3. Notice the successuful message, name did change in the db but not in the window "tables and views".
4. Select another DB, go back to the initial one, notice the new name is shown.

**Expected behavior**
new name to be shown when query runs successfully 

**Version Information (please complete the following information):**
 - OS: Windows
 - App Version  1.8.11

**Comment by Cfun1** [comment]
I was refreshing in the DB drop list instead of the refresh button that appears when we hover over "Tables & Views", Maybe it is good if kept visible all the time.

**Comment by rathboma** [comment]
Yeah, we're going to revamp that UI soon anyway, but agreed this isn't super discoverable.

@ghstng if you have thoughts.
