### ISSUE TITLE
FEAT: When click on Table, updates it window data if already opened instd of duplicate it.

### ISSUE THREAD

**Issue by Cfun1** [beekeeper-studio/beekeeper-studio#486]
When clicking on a Table in the list while it data window is already opened (Table_Name [all] ), update the content/data of that window instead of  opening a duplicate one.

**Comment by rathboma** [comment]
I don't think I agree with this one, it's useful to have the same table open twice with different sorts or filters.

I think I will make it double-click at some point though, single-click seems maybe too much.

Going to close this as honestly we're not going to change this behavior, but I do agree there are times you'd want it to do the opposite thing.
