### ISSUE TITLE
I can't connect after installation 

### ISSUE THREAD

**Issue by MERCERNYC** [beekeeper-studio/beekeeper-studio#489]
I receive an error establishing a connection after creating a table on my terminal with Postgresql. 
Also, it says the database 'name' doesn't exist. I am not sure how to fix this. I am using Mac.

**Comment by rathboma** [comment]
Looks like you're connecting to a postgresql database that is running on your local machine?

If you can provide a screenshot (With any sensitive info blacked out) I can try to help debug!

**Comment by MERCERNYC** [comment]
Hi, I uninstall and installed again and updated my code. It worked after that.
Thank you
