### ISSUE TITLE
PPK Private keys don't work for ssh tunneling

### ISSUE THREAD

**Issue by ldub** [beekeeper-studio/beekeeper-studio#49]
```
Error while signing data with privateKey: error:06000066:public key routines:OPENSSL_internal:DECODE_ERROR
```

Key was generated with the following command:
```
ssh-keygen -b 2048 -t rsa -C "me@myemail.com"
```

**Comment by ldub** [comment]
not sure why, but my key starts with:

`-----BEGIN OPENSSH PRIVATE KEY-----`

Running it through `puttygen` and then back through `ssh-keygen` made it work.

**Comment by rathboma** [comment]
Yes you're right. I'm assuming the original file was a `ppk` file?

Seems to be similar to https://github.com/liximomo/vscode-sftp/issues/594

**Comment by rathboma** [comment]
Can you test two things?
Build: https://github.com/beekeeper-studio/beekeeper-studio/actions/runs/106308642

1. Test with your PEK private key
2. Test running pageant - the ssh agent that comes with putty. It should 'just work' once you add your keys to it.

**Comment by rathboma** [comment]
fixed in 1.4

**Comment by rathboma** [comment]
@ldub do you still use Beekeeper Studio? If so, would you be able to test a new Pageant SSH Agent implementation for me?

Could you download the Windows binary from here - https://github.com/beekeeper-studio/beekeeper-studio/actions/runs/4213316185 and check SSH still works? I've re-implemented the agent system to make it more maintainable.

Thanks!

**Comment by ldub** [comment]
Sorry, I don't use it anymore. I also never used it on windows or with pageant, I think I had just tried to use puttygen on Mac as a way to try to convert different formats of keys.

**Comment by rathboma** [comment]
Thanks!

**Comment by dlong500** [comment]
Is this still supposed to be working?  I use pageant and have no problem establishing a putty connection to a server.  I also use the it in concert with SQLYog without any problems.  However, when I try to use it with Beekeeper I get this error:
`Database Connection Error: SSH Tunnel Connection Error: You must set a valid agent path to allow agent forwarding`

**Comment by dlong500** [comment]
@rathboma In looking at the source for the `ssh2` dependency of `node-ssh-forward` the above mentioned error is thrown when the `agentForward` is set but `agent` is not.  So it seems that `node-ssh-forward` is not correctly setting the agent to `pageant` on my system.  It looks like you were the one to submit a PR to `node-ssh-forward` regarding pageant support?

For what it's worth, on my system I'm also using `ssh-pageant` which links OpenSSH to pageant (for use in Git Bash/MSYS).  This configuration does set the `SSH_AUTH_SOCK` environment variable, which may possibly be interfering with your pageant detection mechanism?  It would be great if there were explicit support for pageant so the agent properly gets set in the `ssh2` dependency.

**Comment by rathboma** [comment]
@dlong500 Ok, so to be clear -- you're on Windows, and use both OPENSSH and pageant?

**Comment by dlong500** [comment]
Yes, sorry I should have been clearer that I'm on Windows.  I have scripts that need to use OpenSSH (through Git Bash).  With the `ssh-pageant` utility I can use pageant to handle key authentication for OpenSSH without needing to use a separate agent just for the Git Bash environment.

**Comment by dlong500** [comment]
@rathboma any thoughts on how this might get resolved?  I'd love to start testing out beekeeper if I can find a workable solution to my particular environment.
