### ISSUE TITLE
BUG: error when connecting on Postgres with SSL

### ISSUE THREAD

**Issue by RafaelMugnol** [beekeeper-studio/beekeeper-studio#491]
**Describe the bug**
I'm trying to connect in a Postgres db with SSL certificate.
But show an error on click in Connect or Test.
Show this error: _Hostname/IP does not match certificate's altnames: Host: localhost. is not cert's CN: ..._

**To Reproduce**
1. Set up a Postgres connection .
2. Enable SSL and set the certificates.
3. Click in Connect or Test.

**Expected behavior**
Connect successfully.

**Screenshots / Gifs**
![image](https://user-images.githubusercontent.com/8561961/103093229-76019600-45d8-11eb-9008-56c1dff15f67.png)

**Version Information**
 - OS: Windows 10
 - App Version: 1.8.11

**Additional context**
I used de same configuration in another app (DBeaver) and works ok.
I'm using Google CloudSQL Postgres to host the db, with Postgres 13.

**Comment by rathboma** [comment]
That looks like a legit certificate error?

Can you try connecting without providing the certificates? It should connect in no-check mode just fine, that might be what DBeaver does by default.

**Comment by RafaelMugnol** [comment]
Great!
I believe that this solution solves my problem.
When will the release come out with this correction?
Thanks for the attention!!
