### ISSUE TITLE
Multiple queries, but only one result is displayedBUG: Say something here

### ISSUE THREAD

**Issue by Mr1X** [beekeeper-studio/beekeeper-studio#496]
Multiple queries, but only one result is displayed

![微信截图_20201228151943](https://user-images.githubusercontent.com/34152252/103197009-314f6500-4920-11eb-92dc-2cdf6e1be2a4.png)

I want to click to switch result1 or result2

**Comment by rathboma** [comment]
So you are switching between result 1 and result 2, but the data displayed doesn't change, is that right?

**Comment by rathboma** [comment]
What database and version of Beekeeper Studio are you using?

**Comment by rathboma** [comment]
I've confirmed this is a bug. I'm pushing a fix for it today

**Comment by Mr1X** [comment]
> I've confirmed this is a bug. I'm pushing a fix for it today

Thank you very much.
