### ISSUE TITLE
BUG: missing vertical scrollbar on saved connections

### ISSUE THREAD

**Issue by EnMaster** [beekeeper-studio/beekeeper-studio#497]
**Describe the bug**
In the main page, if you save over 22 connections, the vertical scrollbar will not appear and make impossible to see the RECENT CONNECTIONS list.

**To Reproduce**
Save over 22 connections

**Screenshots / Gifs**
![immagine](https://user-images.githubusercontent.com/8545371/103232438-b9daff00-493a-11eb-8a35-4dce6d319b84.png)

**Version Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - App Version: Snap 1.8.11

**Comment by rathboma** [comment]
I think this is an overflow iss.e

@ghstng can you take a look at this?
