### ISSUE TITLE
FEAT: Postgres/Cockroach - support sslMode=require

### ISSUE THREAD

**Issue by DGollings** [beekeeper-studio/beekeeper-studio#498]
**Is your feature request related to a problem? Please describe.**
Can't connect to a database through forwarded port. 
Running a database in kubernetes and instead of exposing it to the outside world I open a (non-ssh) tunnel to it. 
Problem is that Beekeeper defaults to [sslmode verify-ca/verify-full](https://www.postgresql.org/docs/11/libpq-ssl.html)
(I think, depending on whether CA added or not) whilst I need it to use mode 'require'

**Describe the solution you'd like**
Considering I was able to 'fix' it by adding a single line to postgresql.ts, maybe just add the option as described in the TODO? :)
```
    if (!config.ssl.key && !config.ssl.ca && !config.ssl.cert) {
      // TODO: provide this as an option in settings
      // not per-connection
      // How it works:
      // if false, cert can be self-signed
      // if true, has to be from a public CA
      // Heroku certs are self-signed.
      // if you provide ca/cert/key files, it overrides this
      config.ssl.rejectUnauthorized = false
    }
    config.ssl.rejectUnauthorized = false
  }
  ```

**Comment by rathboma** [comment]
That's fair. :-D

**Comment by DGollings** [comment]
works. thanks :)

**Comment by rathboma** [comment]
Sweet! Official release coming out later today

**Comment by rathboma** [comment]
I actually don't think this is implemented right now I look again.

Looks like instead of setting that I should set `sslMode` to `require`:

https://github.com/brianc/node-postgres/blob/master/packages/pg/lib/connection-parameters.js#L21

**Comment by rathboma** [comment]
going to revert this commit and do it properly

**Comment by rathboma** [comment]
I've dug through the code. Looks like there's no real difference between `verify` and `require`, when using `node-ssl` it just seems to flip the flag I've added.

**Comment by rathboma** [comment]
Ok, here is how the various modes map to the implementation in Beekeeper:

https://github.com/brianc/node-postgres/issues/2281#issuecomment-659110339

**Comment by DGollings** [comment]
apart from weird-ish verify-ca behaviour, looks good to me. Including the node-postgres mapping
