### ISSUE TITLE
Issue connecting to Postgres with blank username/password

### ISSUE THREAD

**Issue by patrickandroid** [beekeeper-studio/beekeeper-studio#50]
Hi, 
I was just trying out Beekeeper Studio but I'm having an issue connecting to a PostgreSQL@11 database with a blank username/password.
I'm able to connect using Postico.
Screenshot: https://ibb.co/KNyYX6v
Thanks

**Comment by rathboma** [comment]
Interesting. Can you take a screenshot of the postico connection screen? Is it using a socket connection rather than a TCP connection maybe?

**Comment by chrisgaraffa** [comment]
Same with my local Postgres 10 and 11 instances, with no username.

red error text reads "no PostgreSQL user name specified in startup packet"

I'm able to connect with PSequel and of course from the command line.

**Comment by rathboma** [comment]
I think in reality it just uses your OS username. Do me a favor and just enter any old username in the username field and see if that works?

**Comment by chrisgaraffa** [comment]
Interesting! Adding random text into the username field didn't work, entering my macOS username (chris) worked. Thanks for the workaround!

**Comment by patrickandroid** [comment]
Setting my username to my macOS username worked 👍
