### ISSUE TITLE
Failed to connect without any trace in debug logs

### ISSUE THREAD

**Issue by jakoss** [beekeeper-studio/beekeeper-studio#502]
**Describe the bug**
I need to connect to old database. It's SQLServer 2005 SP4 over a VPN. I know there are some issues with certificates (some old hashing method is used on domain controller), but other db apps are working just fine.

**Expected behavior**
Successful connection or some error trace in logs. I run application from powershell like that:
```
$Env:DEBUG = "*"
& '.\Beekeeper Studio.exe'
```
But there is nothing in logs during the connection failure. Nothing on network or console tabs in developer tools either

**Screenshots / Gifs**

Similar setup on Management Studio is working without errors or warnings:
![image](https://user-images.githubusercontent.com/3933348/103568048-29b23200-4ec5-11eb-9c9e-5392792fc3df.png)

**Version Information (please complete the following information):**
 - OS: Windows 10 Pro 2004
 - App Version: 1.9.0

**Comment by rathboma** [comment]
Usually a timeout indicates some sort of host resolution issue, rather than an authentication issue.

Unfortunately I don't have a SQL Server 2005 instance to test against.

Try the IP address without the information after the `\`, so just: `111.111.111.111` not `111.111.111.111\foobar`.

**Comment by rathboma** [comment]
Also FYI - the IP is visible in the error message

**Comment by jakoss** [comment]
Ok, that was silly from me. Removing the last part worked for me, although i have "no entities in MRDB" with counter on 168. Anyway - this issue is closed, Thanks
