### ISSUE TITLE
BUG: Entities list is not loading properly

### ISSUE THREAD

**Issue by jakoss** [beekeeper-studio/beekeeper-studio#503]
**Describe the bug**
I'm connecting to a server (SQLServer 2005 SP4) and after connection i have no entities on list, with message "There are no entities in MRDB". Funny thing that counter next to ENTITIES shows 168. When i try to type in filter the counter is changing, but the entities list is still empty. I don't see any errors in logs or dev console

**Screenshots / Gifs**
![image](https://user-images.githubusercontent.com/3933348/103569951-8531ef00-4ec8-11eb-9c6b-4dde658d04bc.png)
![image](https://user-images.githubusercontent.com/3933348/103570191-e954b300-4ec8-11eb-8ebd-a1d909400c0a.png)

**Version Information (please complete the following information):**
 - OS: Windows Pro 2004
 - App Version: 1.9.0

**Comment by rathboma** [comment]
I have a test build in the works. This may be due to sql server 2005 requiring capitalization of information_schema tables.

Here's the build:
https://github.com/beekeeper-studio/beekeeper-studio/actions/runs/462166264

When the windows build is done there should be a windows installer in `artifacts`, can you try that once it's there and let me know if it works?

**Comment by jakoss** [comment]
Unfortunately, the same issue occurs

**Comment by jakoss** [comment]
Sure, we could schedule something. At what time span are you usually available?

**Comment by rathboma** [comment]
I think I just fixed this in Master if you wanna check?

**Comment by jakoss** [comment]
I can confirm that the lastest version from master works perfectly now :)

**Comment by rathboma** [comment]
Hah, one small thing at a time. If you can find me docs on how fetch works in sql server 2005 vs 2018 I can compare

**Comment by jakoss** [comment]
Official documentation for SQL Server ends on 2016, but i found this: https://stackoverflow.com/questions/14264390/sql-server-2005-equivalent-of-offset-fetch . It seems like SQL Server 2005 do not support FETCH at all.. Workaround is pretty cumbersome: https://www.sqlservercentral.com/articles/sql-server-2005-paging-%e2%80%93-the-holy-grail

**Comment by jim-starace** [comment]
I am having the same issue when connecting to MSSQL 2008 R2 version 10.50.6000.34. I am able to successfully connect to my server, and the entities counter has a value but a message appears under the counter that there are no entities in my database. No Databases, Tables, or Views appear. Same as the image in the original post.

It is my understanding that offset fetch was introduced with MSSQL 2008

Im on a Windows 10 box using BeeKeeper Studio 1.9.4

There is an error in the console:

Uncaught (in promise) RequestError: 'CONCAT' is not a recognized built-in function name.
    at R (app://./js/chunk-vendors.e69b8546.js:2376:27064)
    at W.emit (events.js:210:5)
    at a.<anonymous> (app://./js/chunk-vendors.e69b8546.js:2588:391489)
    at a.emit (events.js:210:5)
    at _.<anonymous> (app://./js/chunk-vendors.e69b8546.js:2528:73686)
    at _.emit (events.js:210:5)
    at O (app://./js/chunk-vendors.e69b8546.js:2588:531098)
    at R (app://./js/chunk-vendors.e69b8546.js:2588:530928)
    at _.A.push (app://./js/chunk-vendors.e69b8546.js:2588:531851)
    at _.u.push (app://./js/chunk-vendors.e69b8546.js:2424:3202)Uncaught (in promise) RequestError: 'CONCAT' is not a recognized built-in function name.
    at R (app://./js/chunk-vendors.e69b8546.js:2376:27064)
    at W.emit (events.js:210:5)
    at a.<anonymous> (app://./js/chunk-vendors.e69b8546.js:2588:391489)
    at a.emit (events.js:210:5)
    at _.<anonymous> (app://./js/chunk-vendors.e69b8546.js:2528:73686)
    at _.emit (events.js:210:5)
    at O (app://./js/chunk-vendors.e69b8546.js:2588:531098)
    at R (app://./js/chunk-vendors.e69b8546.js:2588:530928)
    at _.A.push (app://./js/chunk-vendors.e69b8546.js:2588:531851)
    at _.u.push (app://./js/chunk-vendors.e69b8546.js:2424:3202)

**Comment by jim-starace** [comment]
For SQL 2008 R2 the entities list is now showing using BeeKeeper 1.10.0. No longer an issue for that version of SQL.

**Comment by rathboma** [comment]
@jim-starace and @jakoss I believe I've fixed the table views in this PR - https://github.com/beekeeper-studio/beekeeper-studio/pull/604

If you could download the build assets and let me know I'd appreciate it.

This works using the link you provided - using `ROW_NUMBER() OVER`.

installer / portable will be here when the build finishes - https://github.com/beekeeper-studio/beekeeper-studio/actions/runs/669185906

**Comment by rathboma** [comment]
Can't promise SQL Server 2005 / 2008 support will continue working as we add features but I'll try my best.

If there was a docker container for 2005 I'd be able to include it in my automated suite, but alas MSFT hated linux then :-)

**Comment by jim-starace** [comment]
I can confirm table views are now working for SQL Server 2008 R2. Thank you.

**Comment by jakoss** [comment]
Works great with SQL Server 2005, awesome! :)

**Comment by rathboma** [comment]
I just included this as part of the 1.10.2 release. :-)

**Comment by rathboma** [comment]
As a note - sorting by some fields is not working, but this is due to a SQL Server limitation. You can't sort by varchar for example
