### ISSUE TITLE
BUG: SQLITE_ERROR: no such column: nt.sslRejectUnauthorized

### ISSUE THREAD

**Issue by geovannimp** [beekeeper-studio/beekeeper-studio#504]
**Describe the bug**
Crash starting application.

**To Reproduce**
1. Just start the app.

**Expected behavior**
App opens.

**Screenshots / Gifs**
```
╰─ ./Beekeeper-Studio-1.9.0_cbdfc56650e2a639fe03dda29dec7247.AppImage                                                                                                                      ─╯
17:47:54.512                  › initializing background
running migrations
17:47:54.782                  › UnhandledRejection QueryFailedError: SQLITE_ERROR: no such column: nt.sslRejectUnauthorized
    at process.r (/tmp/.mount_BeekeeN2qn8S/resources/app.asar/background.js:2:291089)
    at process.emit (events.js:210:5)
    at processPromiseRejections (internal/process/promises.js:201:33)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)

```

**Version Information (please complete the following information):**
 - OS: Ubuntu 20.10
 - App Version: 1.9.0

**Additional context**
AppImage and .deb

I had this error with my old database and deleting and creating from start.

**Comment by rathboma** [comment]
If you restart the app, does it work?

**Comment by geovannimp** [comment]
The app does not start, I have to quit with ctrl+c.

![Peek 04-01-2021 18-51](https://user-images.githubusercontent.com/4943174/103583161-05068c00-4ebe-11eb-83bb-e1510fd1eab0.gif)

**Comment by rathboma** [comment]
I'm seeing this, uck. I'll get this fixed

**Comment by rathboma** [comment]
Stupid mistake - ordering of migrations

**Comment by geovannimp** [comment]
Checked and it's working. You rock!
