### ISSUE TITLE
FEAT: Support SQL Server LOCALDB (a special on-demand sql-server express)

### ISSUE THREAD

**Issue by rathboma** [beekeeper-studio/beekeeper-studio#505]
LocalDB is a feature of SQL Server express that start an on-demand instance of SQL Server when you connect to it.

https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/sql-server-express-localdb?view=sql-server-ver15

Our current connection settings don't allow a user to connect to a localdb. There would need to be a special setting.

**Comment by rathboma** [comment]
Unfortunately we're blocked on the Tedius driver not being able to support LocalDB. It's something that's usually done by the Microsoft TDS driver, but Tedius doesn't have that code.

https://github.com/tediousjs/tedious/issues/348#issuecomment-162870839

**Comment by rathboma** [comment]
I'm unfortunately going to have to close this until perhaps this feature is added to tedius (although it probably never will be)

**Comment by andrewmorris-me** [comment]
@rathboma Thanks for looking into this.
