### ISSUE TITLE
BUG: jsonb fields not displaying correctly

### ISSUE THREAD

**Issue by thasmin** [beekeeper-studio/beekeeper-studio#506]
**Describe the bug**
PostgreSQL jsonb fields are displaying as [object Object].

**To Reproduce**
1. Create a table in PostgreSQL that has a jsonb field and insert a row.
2. Run a select on that table from Beekeeper Studio

**Expected behavior**
The JSON text should be displayed.

**Screenshots / Gifs**
If applicable, add screenshots or GIFS to help explain your problem.
![image](https://user-images.githubusercontent.com/198015/103666491-52284380-4f3a-11eb-9585-11f9f7c012ee.png)

**Version Information (please complete the following information):**
 - OS: Windows
 - App Version 1.9.1

**Additional context**
This just started happening after I updated this morning.

**Comment by rathboma** [comment]
Yes, agreed. I wonder if this is a regression. I'll investigate today

**Comment by thasmin** [comment]
I downloaded the code to try and fix this and I've been unable to reproduce this in the development environment. Then I couldn't reproduce it in the original environment either.

I'll reopen the bug if I see it again and figure out how to reproduce it.

**Comment by rathboma** [comment]
Can you contrast displaying jsonb in the table view vs the query editor results? Maybe they behave differently?

**Comment by thasmin** [comment]
I've only used the query editor. I'll keep an eye out.

**Comment by di97mni** [comment]
I got a new version installed and now I don't see the json as I could before.
Same bug as before @rathboma ?
Have you experienced the same @thasmin ?

![image](https://user-images.githubusercontent.com/311406/118795024-7574df00-b89a-11eb-81b1-9e8f322e4c07.png)

**Comment by di97mni** [comment]
Downgrade to version 1.10.2 I see the json as text again

**Comment by rathboma** [comment]
Sorry about that. Yes I had to change how formatters work. I'll put out a point release before the end of the week
