### ISSUE TITLE
QUESTION: connect to postgresql with SSL fails

### ISSUE THREAD

**Issue by jvlker** [beekeeper-studio/beekeeper-studio#510]
**Details:**
We setup a new postgresql server 10.15 which requires SSL. The certificates are self-signed and the key is in PEM format. I connected successful with our C++ lib as well as pgAdmin4. Then I setup Beekeeper following the docs to get the "require-ca" mode (which is the same we use with C++ lib). But Beekeeper only tells me "connection requires a valid client certificate". Unfortunately I don't found anything about allowed certificate-formats or other users with this problem.

**Version Information [might be relevant to your issue]**
Operating System: Ubuntu 20.04
App Version [help -> about]: 1.9.1

**Screenshot / GIF [if appropriate]**:
![beekeeper_question](https://user-images.githubusercontent.com/4425214/104126024-93658c80-535a-11eb-804f-5d1e6eb4b26d.png)

**Comment by rathboma** [comment]
Does it work if you check 'reject unauthorized'?

The more information you can give me about the configuration of your psql database the better -- I've not hit this problem and I'm unsure how to replicate.

**Comment by jvlker** [comment]
Thanks for your answer!

When I check "Reject unauthorized" I got the following error: "Host/IP does not match certificate's altnames: Host: Localhost: is not cert's CN: ...". As I understand that makes sense because its a self-signed certificate and will noch pass a verfify-full. 
The database was set up by a service provider therefor I can't give you details. I connected now 3 different db-drivers in our project and everything worked without any problem (as well as pgAdmin4).
Are there any logs where I can check the exact problems? I enabled the debug-mode but neither in the main.log nor in console output there is any information about the connection attempt.

**Comment by rathboma** [comment]
If you don't provide the certs (just enable ssl), does it work? Picking at straws I know.

Couple of options for me to debug this:
- does the service provider offer services to anyone? Can I sign up for a similar DB online somwehere? If so I can do that to test it
- If not, maybe we could do a screenshare at some point in the next couple of weeks? I can create a build of Beekeeper with some extra debug output.

Let me know!

**Comment by jvlker** [comment]
Without certificates I get the error "connection requires a valid client certificate".
Unfortunatelly this is a custom setup for our company but yes, we can meet to check the extra debug output. Thanks for this offer!

**Comment by jvlker** [comment]
I just found some logs in der developer tools (I overlooked that because lot of source-map warnings first). Second and third was without certs, 4th and 5th are the setup with certs and "Reject Unauthorized" on. The first errors also occure with certs without the option "Reject...".

```
setting background to  dark

js/chunk-vendors.e69b8546.js:2346 beekeeper:db Connection error {"length":109,"name":"error","severity":"FATAL","code":"28000","file":"auth.c","line":"377","routine":"ClientAuthentication"} +0ms

js/chunk-vendors.e69b8546.js:2346 beekeeper:db Connection error {"length":109,"name":"error","severity":"FATAL","code":"28000","file":"auth.c","line":"377","routine":"ClientAuthentication"} +9m

chunk-vendors.e69b8546.js:2346 beekeeper:db Connection error [UnexpectedJSONParseError]: Converting circular structure to JSON    --> starting at object with constructor 'Object'    --- property 'issuerCertificate' closes the circle +1m

chunk-vendors.e69b8546.js:2346 beekeeper:db Connection error [UnexpectedJSONParseError]: Converting circular structure to JSON    --> starting at object with constructor 'Object'    --- property 'issuerCertificate' closes the circle +10s
```

**Comment by ostrnad** [comment]
I have the same problem.

I configured a Postgres v13 server using SSL and client certificates. This is the entry in the pg_hba.conf:

````
hostssl all             all             all                     md5 clientcert=1
````

Note that I used md5 here, because I do not want to rely on the common name of the client certificate for user mapping.

The server certificate and the client certificate are signed by my own CA. There is a Root CA and a Intermediate CA. The certificates are signed by the intermediate CA.

When I connect to my Postgres via ``psql`` it works with the following command line:

````
psql "host=xxxxxx port=5432 user=xxxxxx sslmode=verify-full sslcert=client-cert-file.pem sslkey=client-private-key.pem sslrootcert=ca-trust-chain.cert.pem"
````

When I configure Beekeeper as follows, no connection can be established:

````
Enable SSL = yes
CA Cert = ca-trust-chain.cert.pem
Certificate = client-cert-file.pem
Key File = client-private-key.pem
Reject Unauthorized = yes
````

Trying to connect gives me ``connection requires a valid client certificate``. 

I also tried the following:
* without CA Cert and with "Reject Unauthorized = no", only with client certificate and private key --> connection requires a valid client certificate
* without CA Cert and with "Reject Unauthorized = yes" --> Beekeeper is telling me that there is a self-signed certificate in the chain (which is true and the expected outcome)

I am using Beekeeper Studio v1.9.2 on Windows 10.
Postgres server version is 13.1

Connecting with psql CLI tool gives the following info: 
````
psql (13.0 (Ubuntu 13.0-1.pgdg20.04+1), server 13.1)
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
````

**Comment by yuriizinets** [comment]
Have same problem here.
Tested postgres access with certificates in TablePlus, everything is working, but not from Beekeeper.
Situation is the same as for "jvlker", self-signed PEM certificates.
Unfortunately, I can't provide database access or any details on the server side (it's managed by another team).

App Version: 1.10.2
OS Version: MacOS Catalina 10.15.7

@rathboma I'm new to this project. Where can I find some useful logs?

**Comment by jvlker** [comment]
We had this problem on another DB-Manager too. There we see that it is possible to connect from Windows but not from Linux with the same credentials and settings. Maybe that's the case here too? As I see, all comments here are from unix-based systems...

**Comment by rathboma** [comment]
Ok, I'll look into this as a priority

**Comment by rathboma** [comment]
@yuriizinets check out https://docs.beekeeperstudio.io/troubleshooting/#how-to-debug-beekeeper-studio

**Comment by aslattery** [comment]
Also running into this on Windows, running `1.10.2` as a fresh install, under similar scenario. 

Ran with `DEBUG=*`, nothing added to logs outside of `[2021-04-28 14:38:39.432] [info]                  initializing background`.

Certificates work fine when connecting from raw clients, and other tools such as pgadmin.

**Comment by rathboma** [comment]
Closing this? Don't think this is still an issue
