### ISSUE TITLE
QUESTION: Can we apply multiple filters while browsing table ?

### ISSUE THREAD

**Issue by akash10anand** [beekeeper-studio/beekeeper-studio#512]
**Details:**
I saw a PR merged regarding the multipls filters, but in the current app, I don't find a multiple filter feature. Is is there ?

**Version Information [might be relevant to your issue]**
Operating System: Mac OS
App Version [help -> about]: 1.9.1

**Screenshot / GIF [if appropriate]**:
A screenshot of the app if that helps

**Comment by rathboma** [comment]
Yes (sort of).

Click this button:
![Screen Shot 2021-01-13 at 10 46 22 AM](https://user-images.githubusercontent.com/279769/104482736-e32b9a00-558c-11eb-8ee6-d53bdcef6d6d.png)

It switches the filter to 'raw' mode -- so you can write your own SQL filter

**Comment by rathboma** [comment]
Going to close this as it's sort of answered :-). Please reply with any questions, always happy to help

**Comment by akash10anand** [comment]
Thanks @rathboma. Can you please share a small example ? Does "and" work in Raw mode ? or how is it ? And sorry, please ignore my ignorance 😅

**Comment by rathboma** [comment]
Yes! Like anything you'd put after 'where' will work. Eg `name = 'foo' and age < 100`

**Comment by akash10anand** [comment]
Thanks again! Loving your good work.

**Comment by saendu** [comment]
is it possible that this does not work with uuids? 
e.g ``user_id != ac56abca-8347-11ec-a8a3-0242ac120002 and user_id != baa0f276-8347-11ec-a8a3-0242ac120002``

**Comment by akash10anand** [comment]
@saendu try using ' ' e.g - user_id != 'ac56abca-8347-11ec-a8a3-0242ac120002' and user_id != 'baa0f276-8347-11ec-a8a3-0242ac120002'

**Comment by saendu** [comment]
> @saendu try using ' ' e.g - user_id != 'ac56abca-8347-11ec-a8a3-0242ac120002' and user_id != 'baa0f276-8347-11ec-a8a3-0242ac120002'

great this works, thanks!

**Comment by akash10anand** [comment]
@saendu happy to help!
