### ISSUE TITLE
BUG: Cross-schema foreign keys do not work properly (can't click through)

### ISSUE THREAD

**Issue by alYahudi** [beekeeper-studio/beekeeper-studio#514]
**Describe the bug**
v. 1.9.1
Foreign Keys not showing. 
My Postgres DB's tables' foreign key constraints are not showing in BKS tables. The key icon is not present nor the teleport icon to open the foreign key table. When I right click on table name > SQL:Create Table the code does no show the "REFERENCE" for columns with foreign keys. 
OS = macOS 11.1

EXAMPLE:
DDL from POSTICO = CORRECT:
CREATE TABLE lexicon.lexical_base (
    id integer DEFAULT nextval('lexicon.lexical_base_id_seq'::regclass) PRIMARY KEY,
    base text UNIQUE,
    language integer REFERENCES grammar.language(id),
    parsing1 integer REFERENCES grammar.parsing1(id),
    parsing2 integer REFERENCES grammar.parsing2(id),
    romanized text,
    loanword boolean,
    orig_lang_spelling text,
    meaning text,
    notes text,
    bibliography text,
    related_base integer REFERENCES lexicon.lexical_base(id)
);

SAME TABLE SQL from BKS = INCORRECT:
CREATE TABLE lexicon.lexical_base (
  related_base integer NULL,
  bibliography text NULL,
  notes text NULL,
  meaning text NULL,
  orig_lang_spelling text NULL,
  loanword boolean NULL,
  romanized text NULL,
  parsing2 integer NULL,
  parsing1 integer NULL,
  language integer NULL,
  base text NULL,
  id integer NOT NULL
);
ALTER TABLE
  lexicon.lexical_base
ADD
  CONSTRAINT lexical_base_pkey PRIMARY KEY (id)

**Comment by rathboma** [comment]
Hey, do you have any UI screenshots you can share?

**Comment by alYahudi** [comment]
No problem. In the table attached you see some foreign keys are working, con_id and base_id, but others are not: parsing1, parsing2, parsing3. There may be a user error on my part, but since it's working correctly in Postico (and TablePlus), I’m not sure what it could be. My hypothesis is that beekeeper is not recognizing foreign key directed to a different schema. Those foreign keys that are working are only in my “lexicon” schema, and those that are aren’t are in the “grammar” schema. 

On a different note, I noticed that on tables and views with a lot of data (many hundreds or thousands of rows and a lot of data in each cell) the GUI craps out and goes blank when I scroll right to see the rest of the table. (Attached also).

I hope these things get resolved. I think Beekeeper Studio is the ideal teaching aid. Of the cross platform GUIs I’ve surveyed it is the one that I would like to use in my classes. If I adjust a column width, it works until I leave and return to the table.

Many thanks,
James



 
_____________________
James D. Moore, Ph.D. 
Lead Researcher
"Judeans in Elephantine and Babylonia” Project manager 
Seminar für Altes Testament (Lehrstuhl for the History of Israel and the Ancient World)
Theologische Fakultät
Humboldt-Universität zu Berlin
Unter den Linden 6
10099 Berlin
Raum: Burgstr. 26 #323
Telefon: +49 30 209-391827‬
Email: james.moore@hu-berlin.de

Academia.edu page <https://hu-berlin.academia.edu/JamesMoore>

Humboldt University Page <https://www.theologie.hu-berlin.de/de/professuren/professuren/gi/personen/wimi/moore>

European Research Council-Elephantine Project, Aramaic and Northwest Semitic Specialist (Link here <https://www.smb.museum/en/museums-institutions/aegyptisches-museum-und-papyrussammlung/collection-research/research/erc-project-elephantine-localizing-4000-years-of-cultural-history-texts-and-scripts-from-elephantine-island-in-egypt/>)

**Comment by rathboma** [comment]
Hey James,

Ah, they're cross-schema foreign keys. Yes that is why. I'll rename this ticket to track that specifically

In terms of the wide tables -- the table going blank is an issue I've seen before, I'm not sure the cause, it might be an issue with Tabulator (the tables library we use), I'll see if I can figure it out.

See #445 for the blank contents

**Comment by rathboma** [comment]
@alYahudi can you check this build - https://github.com/beekeeper-studio/beekeeper-studio/actions/runs/494117549 and let me know if that fixes the disappearing table data?

**Comment by alYahudi** [comment]
No luck; same issue.
