### ISSUE TITLE
Postgres: Display views and tables from multiple schemas

### ISSUE THREAD

**Issue by CptMonac** [beekeeper-studio/beekeeper-studio#52]
It looks like by default, the tables & views displayed are only those in the public schema

**Comment by rathboma** [comment]
Yes this is correct until I figure out a way to add the a schema dropdown to the UI.

Will work on this soon. I consider this a bug.

**Comment by dwelch2344** [comment]
We tend to work across a ton of schemas, so I'd prefer not to have to switch schemas each time I want to see something in another context. Perhaps a collapsible tree component (eventually being able to specify "all schemas" or check only those you're interested in at the connection level)?

**Comment by dwelch2344** [comment]
Took a quick stab at following the `TableListItem` pattern and wrapping it in a `SchemaContainer` type component. Right now it pulls all tables in all schemas, but being able to specify those schemas in the connection would probably be good to have with this kind of approach. 

Video linked below. Thoughts? 

https://drive.google.com/file/d/1cAYel_bj7h3LD1yw3NuhzOD3OMjenyvt/view?usp=sharing

**Comment by ifokeev** [comment]
I'm trying to connect to not default schema in my `postgres` database and see `no tables` at all.

<img width="1312" alt="Screenshot 2020-05-07 at 10 51 50" src="https://user-images.githubusercontent.com/2017148/81268556-c24f9400-9050-11ea-8b77-ccf80b4c426d.png">

**Comment by rathboma** [comment]
@dwelch2344 That actually looks pretty awesome. Want to create a PR and we can iterate on it?

**Comment by rathboma** [comment]
Another option is to previx the schema on the table name, but I think that's a little ugly, eg `public.foo`, and `contacts.bar`

**Comment by ghstng** [comment]
@rathboma @dwelch2344 I'm good with it -- PR and I can do some styling cleanup

**Comment by dwelch2344** [comment]
@rathboma ew yeah I think that'd be a huge turn off to anyone who leverages schemas for namespacing / isolation. 

IntelliJ / DataGrip have really good tooling for RDBMS, and they handle it similarly with a tree component like this – was where I got the idea ;) I don't love that they mash everything (including multiple database connections) into it, but it does work well when you have multiple data sources for dev/prod and such. Screenshot below for chewing on 

<img width="370" alt="Screen Shot 2020-05-07 at 8 27 23 AM" src="https://user-images.githubusercontent.com/160142/81306591-e43f1b80-903c-11ea-942c-beae31cd7363.png">

**Comment by dwelch2344** [comment]
Ok @ghstng opened #73 to get some feedback. Definitely needs some love / controls, but think this could be a great direction

**Comment by rathboma** [comment]
This is done! See release v1.3.0 💪

**Comment by ifokeev** [comment]
@rathboma thank you. It works
