### ISSUE TITLE
BUG: syntax error at or near ":"

### ISSUE THREAD

**Issue by guigarfr** [beekeeper-studio/beekeeper-studio#529]
**Describe the bug**
Performing a query with more than one parameter where at least two of the parameters have the same name returns a syntax error

**To Reproduce**
1. Run query with two parameters being the same. Mine was a long query with a union, but you can reproduce with simple query such as:
```
select *
from table t
where t.id = :my_id or t.id = :my_id;
```

**Expected behavior**
Return row from table t where id is the provided id or nothing if the id is not in the table.

**Screenshots / Gifs**
No need. it returns the error: syntax error at or near ":"

**Version Information (please complete the following information):**
 - OS: Mac
 - App Version 1.9.1

**Additional context**
The query works in Intellij, for example.
It looks like Beekeeper stops looking for parameter replacements once it's found the first one. If you run the query with two different names and set the same value, it works. For example:

```
select *
from table t
where t.id = :my_id_1 or t.id = :my_id_2;
```

**Comment by imTigger** [comment]
+1
Placeholder only successful replaced at first time it appear.

Example:
SELECT ':test', ':test', ':test';

Output:
'123', ':test', ':test'
