### ISSUE TITLE
Adopt a component library

### ISSUE THREAD

**Issue by dwelch2344** [beekeeper-studio/beekeeper-studio#53]
Love what I'm seeing as our team has been preparing to build something like this as FOSS for a while. Fired things up against a local postgres and ran into the single-schema issue in #52. Took a look at adding a second select box and saw your comment about getting a library. 

Probably a good call regardless, unless you're really tightly controlling scope. We have used and loved Vuetify, and I'd be happy to take a stab at both adding it to the project and solving #52 with it – if it's something you'd be interested in.

**Comment by rathboma** [comment]
I'm not so hot on component libraries, and my co-creator likes to have full control of those aspects.

If you do want to take a stab at #52 it shouldn't actually be too difficult, see `CoreSidebar.vue`, `postgresql.js`, and `store/index.js` as core integration points

**Comment by rathboma** [comment]
gonna close this ticket as we have a PR
