### ISSUE TITLE
BUG: can't connect SQL Server (improve documentation and tooltip help for Windows Authentication integration, don't ask port, don't ask user / password)

### ISSUE THREAD

**Issue by aisbergde** [beekeeper-studio/beekeeper-studio#534]
**Describe the bug**
it should be clear and documented how to connect to MS SQL Server using Windows Authentication
user and password are required, but if the are entered, they are in conflict with Windows Authentication

For a new user it is not clear what he should enter to connect with MS SQL Server using Windows Integrated Authentication
There is a very poor instruction in the tooltip after domain:

>Set 'domain' to be logged in using Windows Integrated Authentication

I tried to enter the name of my PC as domain, I also tried the string "domain" and also "'domain'", but anyway I get some error that the username property must be a string

But If I want to use Windows Integrated Authentication, then I will not enter a user or password. It should be possible to connect without a user and password required in this case.

So I entered some dummy user and password. But now I get the error that a login for an untrusted domain can't be used with Integrated authentication.

Next issue is a required port.
Normally I don't care about the port of SQL Server instances because name or name\instance is fine.
How a "normal" user should know the port if it is not the standard port?

First I need to search the internet, then I need to connect to the server using another frontend.
And then I can execute:

```sql
USE master
GO
xp_readerrorlog 0, 1, N'Server is listening on' 
GO
```

Or something else.
But it looks like the port I get this way doesn't work.

I have several instances
- localhost (standard port, should be fine)
- localhost\sql2019 (no idea about the port, the query above gives me 53152 or 50365)  
  but whatever I enter I get the error "Port for sql2019 not found in localhost"
- there are also some localDB instances, but I did not try to connect

It should be possible to connect without knowing the port but only based on name or name\instance

**To Reproduce**
see above

**Expected behavior**
- It should be possible to connect without knowing the port but only based on name or name\instance
- To use Windows Authentication there should be a checkbox, not a "domain" entry and if the option is selected, then user and password should be allowed to be empty.
- It should be possible to omit the port because server or server\instance should be enough

**Screenshots / Gifs**

**Version Information (please complete the following information):**
 - OS: Windows 10
 - App Version 1.9.1

**Additional context**
My goal to evaluate beekeeper is to see, if and how I can enter data, especially multi line data.
In SSMS or Azure Data Studio it is not possible to enter multiline data. And I am looking for an easy frontend to easy enter data. Is this possibl with beekeeper? If not, then it is not urgently for me to solve the issue. But if this is possible, I would like to evaluate the beekeeper in General after I will be able to connect to my SQL Server databases.

**Comment by rathboma** [comment]
Hey! Yeah SQL Server has a bunch of non-standard connection options that are either not supported by the Node client, or are very hard to implement. One example is the unique [SQL Server LocalDB](https://github.com/beekeeper-studio/beekeeper-studio/issues/505), which you might be using?

**Comment by aisbergde** [comment]
I only know, that it is possible to connect to mssql via node, but never tried, how.

My feedback is only from the user perspective of a user, working explicitly with mssql. I know how other clients ask me to enter information, I know there are often issues with Java and jdbc. And I was not able to connect and therefore I can't test this software.

In General I am fine with SSMS, VS and Azure Data studio. And most mssql developers I know also are fine. So it is OK for me not to use this browser. On the other hand, if nobody will report these issues they (may be) will not be fixed. This was my motivation to report the issue.

It is not logical, to force the input of not used information like user and password in the case I described.

**Comment by janproch** [comment]
I use this node client https://www.npmjs.com/package/msnodesqlv8 for connecting to SQL Server with Windows authentization. It works correctly under Windows. TediousJs doesn't support Windows auth, I think native module is neccessary for this

**Comment by MasterOdin** [comment]
Tedious can support windows auth by utilizing the msnodesqlv8 module, though one has to (I think) cast the connection args to a string: https://github.com/tediousjs/node-mssql#microsoft--contributors-node-v8-driver-for-nodejs-for-sql-server

**Comment by heychazza** [comment]
Hey, just checked out this app (and btw, it looks fantastic!) however I am struggling to connect as my current logged in user to a MSSQL database.

I find the documentation to be confusing, I also use the tedious library with msnodesqlv8 for connecting (within my node apps) to databases with winows credentials.

Could this please be added or clarified how to logon using it

**Comment by AradAral** [comment]
Hey, I sympathize with the OP here, I just installed Beekeeper and after ten minutes of playing with the interface, I still have no idea how to log-in using WAI

**Comment by rathboma** [comment]
Hey all - Apologies for the confusion

So... there are some limitations here:
- You CAN log in with your windows credentials right now, but they're not 'passed through' from the OS, you have to enter your windows user/password and your domain to have it work.
- I'm not sure if credentials can be passed through from the OS using the node client. It will require investigation. Certainly the nodejs client is written assuming it is being used on a server.
- Documentation is bad. I agree. I'll open a ticket to improve it.

**Comment by rathboma** [comment]
I'm closing this ticket and tracking these issues as individual issues now. Thanks all!

**Comment by quick007** [comment]
I'm currently trying to login- port 1434, username and password set, checked trust server certificate, and added "domain" as the domain, but I'm getting the error "Login failed. The login is from an untrusted domain and cannot be used with Integrated authentication."
