### ISSUE TITLE
BUG: `cmd+w` on mac doesn't close tab

### ISSUE THREAD

**Issue by fritzlorens** [beekeeper-studio/beekeeper-studio#537]
**Describe the bug**
If you have multiple tabs, pressing `command+w` does not close tab, instead it goes into the first tab. But if you have only 1 tab, it closes the tab

**Expected behavior**
Pressing `command+w` should always closes the currently open tab.

**Version Information (please complete the following information):**
 - OS: Mac BigSur 11.1
 - App Version: 1.9.2

**Comment by rathboma** [comment]
I'm unable to replicate this on my test mac, although I'm not on big-sur.

Can you restart the app and try again, if it keeps happening can you open the console to see if there are any errors (help -> show developer tools)?

Either way if you can include a gif / video of the issue that would be super helpful.

**Comment by UtechtDustin** [comment]
`cmd + w` works fine for me, i'm using Big Sur (11.1 20C69).

**Comment by fritzlorens** [comment]
turns out restarting the app fixes it, will close it, thanks!!
