### ISSUE TITLE
QUESTION: Will we be getting a M1 ARM64 build for MacOS?

### ISSUE THREAD

**Issue by joshuapack** [beekeeper-studio/beekeeper-studio#538]
**Details:**
Will we be getting a M1 ARM64 build for MacOS?

It runs fine under Rosetta 2, however, I am sure it would run even better under ARM64! 😄 

Also, Not related to this question. I just want to say how amazing this project is! You guys rock! 🎸 

I guess we are waiting for support from NodeJS? (https://github.com/nodejs/build/issues/2474)

**Version Information [might be relevant to your issue]**
Operating System: MacOS 11.1 (Apple Silicon M1)
App Version [help -> about]: 1.9.2

**Comment by rathboma** [comment]
Thanks!! Glad you like the project. :-)

I did the initial work yesterday move us to electron 11, which supports M1 targets, but I don't have a M1 CI box to do the build on.

Hoping AWS launches a M1 vm soon, otherwise I'm kind of stuck.

**Comment by joshuapack** [comment]
Which branch is that? and can I try from my M1 mac?

**Comment by rathboma** [comment]
Hmm, in theory master should run on m1, but I'm not sure if the rest of the build-chain I use is m1-capable yet. Early days I'm afraid.

In theory, this might work?

yarn run electron:build --mac --arch arm64

**Comment by rathboma** [comment]
To be transparent: this is totally untested by me, and might require new versions of electron-builder, vue-cli, etc etc.

**Comment by joshuapack** [comment]
I was unable to get it to work :/

unsure if due to node still running on x86_64 or what, but everything I tried, just didn't work.

**Comment by rathboma** [comment]
Yeah it'll probably be a few months until all the tooling catches up to be honest

**Comment by rathboma** [comment]
Going to close this for now. I'm subscribed to a million channels, so when I can do this, I will.

**Comment by joshuapack** [comment]
just FYI, I was able to run on Mac ARM64 using electron version 13.0.0-beta.5 fine. IDK if any bugs, but works great!
