### ISSUE TITLE
BUG: Closing Multiple Tabs

### ISSUE THREAD

**Issue by JaceBayless** [beekeeper-studio/beekeeper-studio#539]
**Describe the bug**
When trying to close multiple tabs using the "Close All" feature no tabs are closed.

**To Reproduce**
1. Open multiple tabs.
2. Right click any of the tabs along the top
3. Click "Close All"

**Expected behavior**
I believe this should be closing all the table tabs.

**Version Information (please complete the following information):**
 - OS: Windows
 - App Version: 1.9.2

**Comment by rathboma** [comment]
Yes you're right, that context menu has stopped working for some reason. Investigating.

**Comment by rathboma** [comment]
Fix coming out today
