### ISSUE TITLE
HEX id are not shown correctly

### ISSUE THREAD

**Issue by zaifastafa** [beekeeper-studio/beekeeper-studio#54]
HEX fields are not shown properly.

**Comment by rathboma** [comment]
Can you give me an example? Info I need:

1. Database type
2. What it looks like
3. What it should look like

Ideally a screenshot would be amaz

**Comment by zaifastafa** [comment]
> Can you give me an example? Info I need:
> 
> 1. Database type
> 2. What it looks like
> 3. What it should look like
> 
> Ideally a screenshot would be amaz

@rathboma Hi, 

here is the expected result for a HEX: 

![screenshot](https://user-images.githubusercontent.com/24492269/81363370-9c7fc900-90fc-11ea-8201-45e05108d49a.png)

And here is the current result: 
![screenshot_1](https://user-images.githubusercontent.com/24492269/81363540-04ceaa80-90fd-11ea-8a66-15b54f647173.png)


Reference: https://dev.mysql.com/doc/refman/5.7/en/string-functions.html#function_hex

**Comment by rathboma** [comment]
Thanks! I'll take a look

**Comment by rathboma** [comment]
@zaifastafa is this fixed in 1.4?

**Comment by zaifastafa** [comment]
Hi @rathboma I haven't checked yet, I will update here once I do. Thanks

**Comment by zaifastafa** [comment]
@rathboma Hi, thanks for waiting. I checked but unfortunately it does not show as expected. 

![image](https://user-images.githubusercontent.com/24492269/83237075-09432c00-a1ae-11ea-9ee0-c4f5842bc316.png)
