### ISSUE TITLE
BUG: SQL Tables and Types are mixed

### ISSUE THREAD

**Issue by dalisoft** [beekeeper-studio/beekeeper-studio#541]
**Describe the bug**
SQL Tables and Types are currently mixed, but should be categorized or somehow sorted

**To Reproduce**
1. Connect to Postgres SQL with Types (ElephantSQL for example, not ad)
2. See results

**Expected behavior**
Only tables should show and functions should be collapsed

**Screenshots / Gifs**
![sql-compare](https://user-images.githubusercontent.com/3511344/106910060-ad5c7a00-6722-11eb-805e-b631189d508d.jpg)

There comparing two apps between Beekeeper Studio and SQLPro Studio (yes, your app quality is same/better than SQLPro)

**Version Information (please complete the following information):**
 - OS: macOS 10.15.7
 - App Version v1.9.2

**Additional context**
I love your application, very beautiful and well made

**Comment by rathboma** [comment]
Hey! Yes we do co-mingle them now, but if you click the funnel button in the filter search box in the sidebar you can choose which types of entities to display (so you can hide functions if you like.

**Comment by rathboma** [comment]
Going to close this, as I don't think this is something we will change for now

**Comment by dalisoft** [comment]
Thanks. I’ll try.

**Comment by dalisoft** [comment]
@rathboma Seems it doesn't work or there should two more filters `Functions` and `Types`

<img width="313" alt="image" src="https://user-images.githubusercontent.com/3511344/107277219-eaec3a80-6a75-11eb-860e-20e8c87bef8f.png">
