### ISSUE TITLE
BUG: Cannot use Menus Tab

### ISSUE THREAD

**Issue by depran7** [beekeeper-studio/beekeeper-studio#543]
**Describe the bug**
when I click right on the tab and click "Close", "close others", "close all" or "duplicate" it's not working but sometimes it's work when I click few times

**To Reproduce**
1. Go to Tab
2. Click Right on Menus of Tab ("Close", "close others", "close all" or "duplicate")
3. Not working, but sometimes it's work when I click few times

**Expected behavior**
I expect it's working on one click

**Screenshots / Gifs**
![image](https://user-images.githubusercontent.com/36499755/106968783-1a502e00-677c-11eb-87b8-642b869a4cb0.png)

**Version Information:**
 - OS: Windows 10
 - App Version: 1.9.2

**Comment by rathboma** [comment]
Fix about to be released!
