### ISSUE TITLE
QUESTION: Available via Setapp

### ISSUE THREAD

**Issue by mittalyashu** [beekeeper-studio/beekeeper-studio#544]
**Details:**

Are there any plans to this app available via [Setapp](http://setapp.com/)?

**Comment by rathboma** [comment]
Hey @mittalyashu! Thanks for joining us in the community!

I thought Setapp was for paid apps? Is there a reason we'd join it?

**Comment by dalisoft** [comment]
@mittalyashu I'll recommend using Homebrew. Setapp maybe good for someone, but it's for paid and subscription-based model which can reduce users in early stages of application popularity growing.

Maybe i'm don't know something, fix me if i'm wrong. But i love this application, thank you @rathboma and @beekeeper-studio for best open-source and free SQL client app

**Comment by mittalyashu** [comment]
@rathboma

There is another app [dev utils](https://devutils.app/), you can even find the source code of app on GitHub.
Still they were able to make their app available on Setapp.

Of course, (as I understand), they do paid the vendors who submit their app on Setapp. That way, you can make some additional bucks too 😋

**Comment by rathboma** [comment]
I'm going to close this, we don't really have any intention of submitting to Setapp right now I'm afraid.
