### ISSUE TITLE
BUG: Can't set a field to `NULL` in the table editor

### ISSUE THREAD

**Issue by ReynoldsCahoon** [beekeeper-studio/beekeeper-studio#551]
**Details:**
Is there currently a way to change a value in a cell to NULL? I tried removing the data (from a datetime) and also setting the value to `NULL` and `(NULL)` and it wouldn't run the change on any of these attempts. If this isn't possible, can it be considered for a feature request?

**Version Information [might be relevant to your issue]**
Operating System: Zorin OS 15.3
App Version [help -> about]: 1.9.4

**Comment by rathboma** [comment]
Hah, actually I don't think you can right now.

Good catch

**Comment by PePoDev** [comment]
@rathboma This is still can't set `NULL`?

**Comment by wdrougas** [comment]
@rathboma How is one supposed to set a field value to `NULL` ?

**Comment by Rafarel** [comment]
@PePoDev @wdrougas You can right click the cell in the table view and here you have `Set Null` option.

**Comment by phloggu** [comment]
And when pasting several columns at once?
