### ISSUE TITLE
FEAT: Columns with limited size

### ISSUE THREAD

**Issue by geovannimp** [beekeeper-studio/beekeeper-studio#555]
**Is your feature request related to a problem? Please describe.**
I have tables that store jsonb data and as columns have no limit, is terrible to find something.

**Describe the solution you'd like**
Limit columns to specific size and add some options to edit multi-line content.

**Describe alternatives you've considered**
- For column size we could do some experiments to find the best size
- For multi-line edit I suggest open a modal with a textarea editor.

**Comment by geovannimp** [comment]
I'm open to implement the solution, but I have to know the desired solution.

**Comment by rathboma** [comment]
Yes, we'll be addressing this soon. Agreed it's silly right now

**Comment by rathboma** [comment]
This is done in Master, closing
