### ISSUE TITLE
QUESTION: Why i see white text on white background on website

### ISSUE THREAD

**Issue by apschni** [beekeeper-studio/beekeeper-studio#559]
**Details:**
When I opened the guide, I saw that the buttons in the table explorer section are displayed incorrectly: a white font on a whitebackground, impossible to see any text. Is it a site problem, or is something showing wrong on my side?

**Version Information [might be relevant to your issue]**
Operating System: Ubuntu 20.04.1, GNOME 3.36.8

**Screenshot / GIF **:

![image](https://user-images.githubusercontent.com/64983176/107818947-6a854c80-6d89-11eb-93f4-949a405295a6.png)

**Comment by rathboma** [comment]
Hah, yes we have a fix for that, just needs deploying. Sorry about that
