### ISSUE TITLE
Multiple queries in same tab

### ISSUE THREAD

**Issue by szacchino** [beekeeper-studio/beekeeper-studio#56]
In other tools I like the ability to write multiple queries in the same text area and then execute the one on which the cursor is placed. A query is delimited by an empty line. Example
```
-- first query
select c.*
from clients c

-- the space above this line separates the query 2 from the first one
-- second query
select d.*
from delivery d
```
If I place the cursor in lines 1-3 and press CTRL-Enter I execute the first query.
Similarly in lines 5-8 I execute the second one.

**Comment by rathboma** [comment]
I also like that! It's on the todo list for sure

**Comment by bijai** [comment]
Something like selecting a query (highlighting it) and doing a Ctrl+Enter to execute that selected query would be good too.

**Comment by rathboma** [comment]
solved in 1.4

**Comment by rathboma** [comment]
(not the ctrl+enter bit)

**Comment by ChillarAnand** [comment]
Any plans on add support for running queries at cursor? @rathboma
