### ISSUE TITLE
FEAT: import and/or insert data to a single table from: CSV, JSON, JSON-line, Excel [commercial version]

### ISSUE THREAD

**Issue by peace-blaster** [beekeeper-studio/beekeeper-studio#560]
**Is your feature request related to a problem? Please describe.**
This is the only major feature I still need DBeaver for.

**Describe the solution you'd like**
Just a simple ability to right click a table, and "import data", or maybe go for the gold and have button to create new table where you can import.

**Describe alternatives you've considered**
The only other way I can think to do this is to use another client, or write some stranger query that pulls the .csv from the server or something.

**Additional context**
Add any other context or screenshots about the feature request here. (we love screenshots with red circles if the request is for something visual)
This seems like the place to put it, in this menu here
![wheretoput](https://user-images.githubusercontent.com/3653135/107863820-28a9e400-6e25-11eb-902c-542af30f9708.png)

**Comment by rathboma** [comment]
Yes! We'll be including this in our 2.0 release later this year :-)

**Comment by peace-blaster** [comment]
AWESOME! You da best. I've been waiting forever for someone to make a decent SQL client, and when I read the "about" on your website I thought the exact same- everything has a billion toolbars, keyboard shortcuts are inconsistent, etc., then Sequel Pro is decent. Can't wait to switch to this forever.

**Comment by thoughtspacewebsites** [comment]
Hey, just stumbled across this and wondering if you guys are planning to implement an update feature into your import functionality as well. Right now, the only other piece of software that I can find for MySQL that does this is Sequel Pro, but it's Mac only. Essentially, when importing a CSV and mapping columns, I'd like to be able to select whether a column in the CSV should be mapped to a table column, or rather used to match an existing table value in order to update the rest of the records in that CSV row. Does this make sense? Please tell me this is planned, because it's one of my most used time saving features, and right now it's one of the few things causing me to still boot into a Mac VM!

**Comment by rubenjimenez** [comment]
Any news about this feature? I'm using the version 2.1.5 and I don't find how to import a CSV.

Thanks.

**Comment by jmschabdach** [comment]
Seconding @giancarloerra 's question of is this feature supported yet. Short of manually entering each line of my large table, it's not clear how I can add data into a table.

**Comment by codevski** [comment]
Cannot find this feature as well. This premium feature?

**Comment by fanzypantz** [comment]
There is still no way to import?

**Comment by Birivera** [comment]
Hi, any news about this?

**Comment by lsrom** [comment]
Kind of sucks that BS will let me export database as CSV but when I need to import it elsewhere, it cannot do that... Original answer said it will be version 2.0 in 2021 but it is 2022 and version 3.7.1 still doesn't seem to have this feature.

**Comment by icedcoke** [comment]
Import and export directly from the command line, not very cumbersome.

Export Command:
mysqldump -uroot -p --databases [databaseName] --tables [tableName1] [tableName2]...[tableNameN] --where='id < 3000'  > [sqlName].sql
Import Command:
mysql -uroot -p [databaseName]< [sqlName].sql

**Comment by araujovicthor** [comment]
Any news about this feature?

**Comment by YoanHlebarov** [comment]
That is the only feature that is missing for me on daily basis. Otherwise Beekeeper Studio has proven to be the best GUI tool I have tried so far.

**Comment by peace-blaster** [comment]
Awesome!! Appreciate you all and all the work you do

**Comment by rathboma** [comment]
Workflow for this feature:
1. Right click a table and click import or click [tools -> import] in the top menu
2. Select a table if none selected (modal)
3. Opens a new tab, name `Import into [table]`
4. Select a file to import
  - For CSV - allow overriding the field delimiter, row delimiter, and string quoting characters, default to `,`, `\n`, and `"`
6. BKS reads the headers / first few rows to understand the schema
7. BKS presents the user a file -> column mapping for the table, the user selects which header maps to which table column
  - For CSV/Excel - need to provide the user the ability to specify whether the file contains headers or not
  - Provide a list of values that will be interpreted as null. Default is one item - empty string `""`. 
  - Provide an option to map more values to NULL - eg "NA", "-", or "NULL", explain this is case sensitive.
8. Provide two options for making this change - `Apply`, and `Copy to SQL`

**Comment by digitalcortex** [comment]
> Workflow for this feature:
> 
> 1. Right click a table and click import or click [tools -> import] in the top menu
> 2. Select a table if none selected (modal)
> 3. Opens a new tab, name `Import into [table]`
> 4. Select a file to import
>    
>    * For CSV - allow overriding the field delimiter, row delimiter, and string quoting characters, default to `,`, `\n`, and `"`
> 5. BKS reads the headers / first few rows to understand the schema
> 6. BKS presents the user a file -> column mapping for the table, the user selects which header maps to which table column
>    
>    * For CSV/Excel - need to provide the user the ability to specify whether the file contains headers or not
>    * Provide a list of values that will be interpreted as null. Default is one item - empty string `""`.
>    * Provide an option to map more values to NULL - eg "NA", "-", or "NULL", explain this is case sensitive.
> 7. Provide two options for making this change - `Apply`, and `Copy to SQL`

I dont have import option in the context menu
<img width="391" alt="Monosnap Local - Beekeeper Studio 2023-03-03 11-28-09" src="https://user-images.githubusercontent.com/62620810/222658358-aa23ff06-c3ee-4b8e-9ed0-05b2a5748d9e.png">

**Comment by YoanHlebarov** [comment]
> 

This is an upcoming feature, not yet available. Hopefully we get it soon enough!

**Comment by rathboma** [comment]
![Image](https://github.com/beekeeper-studio/beekeeper-studio/assets/279769/5f01e716-cbf2-4227-a795-dfcc5eb86e3e)
![Image](https://github.com/beekeeper-studio/beekeeper-studio/assets/279769/843d3e90-98f6-4836-9392-771e93d93803)

**Comment by rathboma** [comment]
Some items for the alpha:

1. Dropzone for uploading a file
2. Auto-detect delimiters (column and row delimiters), have a button to override
3. Show a preview of the imported data on the source tab (first 10 rows), so folks can see if delimiters are correct
4. Use a vue component for the mapper table column cell - show column options like not null / primary key / foreign key / default
5. Remove the 'ignore' checkbox, and just make it the default value in the dropdown. Also show 'ignored' as grey / italic or something in the table column view component, similar to how `(NULL)` is displayed in the table structure table for default value
6. No modal when the import is running, use a new screen for the tab, the same way we do this for export/backup
7. Modal on success or failure.
8. If there is a failure, it should show the full error on the tab, not just in the modal
