### ISSUE TITLE
BUG: missing dependency on Debian 11 - bullseye

### ISSUE THREAD

**Issue by janusheide** [beekeeper-studio/beekeeper-studio#562]
**Describe the bug**
Missing dependency on libappindicator3-1 in Debian 11

**To Reproduce**
1. Attempt to install as per the readme on a Debian 11 machine

**Expected behavior**
It should install.

**Version Information (please complete the following information):**
 - OS: Debian 11 bullseye

**Additional context**
It appear that the package was dropped and that you are supposed to use libayatana-appindicator instead.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=895037

**Comment by rathboma** [comment]
Hmm, yes I've tested in Debian 10, but not 11. So if you install `libappindicator3-1` it works fine?

**Comment by janusheide** [comment]
The package "libappindicator3-1" has been dropped from Debian 11 and has been replaced with "libayatana-appindicator". So out of the box you cannot install beekeeper... hope that helps?

**Comment by SaltyPeppermint** [comment]
The issue seems to be line 141 in beekeeper-studio/apps/studio/vue.config.js 

You should be able to replace libappindicator3-1 with libayatana-appindicator3-1.

Im fairly certain this won't cause problems since both Debian 11 and Ubuntu 20.04 LTS (and later) package it under this name.

**Comment by janusheide** [comment]
yes,

It has been in Debian since buster, and there is a stretch backport: https://packages.debian.org/buster/libayatana-appindicator3-1.

It has been (atleast) in Ubuntu since Bionic: https://packages.ubuntu.com/bionic/libayatana-appindicator3-1.

So making this change should only impact users that are on a Debian or Ubuntu that is already beyond EOL.
