### ISSUE TITLE
BUG: Support sql server 2008

### ISSUE THREAD

**Issue by nukassel** [beekeeper-studio/beekeeper-studio#564]
**Describe the bug**
Connection to sql server 2008 database is successful. But when you try to get tables in the left pane, nothing appears, you can see that some data is being loaded (this is understandable by "ENTRIES 251"), but instead of tables, the inscription "There are no entries in XXX" appears.

**To Reproduce**
1. Create a connection to sql server 2008
2. Try to get a list of tables

**Expected behavior**
Lists of tables should appear in the left pane

**Screenshots / Gifs**
![image](https://user-images.githubusercontent.com/10960084/108057313-86c40a80-7063-11eb-9a52-617930dc4306.png)

**Version Information (please complete the following information):**
 - OS: Arch linux
 - App Version: 1.9.4 (snapd)

**Additional context**
This seems to be due to the fact that there is no CONCAT () in sql server 2008 version

**Comment by MasterOdin** [comment]
Should be able to replace these lines:

https://github.com/beekeeper-studio/beekeeper-studio/blob/0fb098a8e30b1c6ad6747eff1965fc1ab9b4d231/src/lib/db/clients/sqlserver.js#L311-L313

with something that uses the [+ string concatenation](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/string-concatenation-transact-sql?view=sql-server-ver15) like so:

```
           THEN data_type + '(' + CAST(character_maximum_length AS varchar(20)) + ')'
         WHEN datetime_precision is not null THEN 
           data_type + '(' + CAST(datetime_precision AS varchar(20)) + ')'
```

only issue is that the `varchar` length needs to be given for the cast and I am not sure what the upper bounds of what those fields might hit, though I think `character_maximum_length` maxes out maybe around 8000?

**Comment by rathboma** [comment]
oh nice. This is probably the issue for #139 too.
