### ISSUE TITLE
BUG: Sqlite in Archlinux missing encoder 

### ISSUE THREAD

**Issue by JasonVolney** [beekeeper-studio/beekeeper-studio#573]
**Describe the bug**
I want to use beekeeper-studio on Archlinux, but after installation when I choose Sqlite database connection type I was bump with this bug:

![image](https://user-images.githubusercontent.com/54520187/109006794-2c8dff80-768a-11eb-8a02-f62040f6440c.png)

**Version Information (please complete the following information):**
 - OS: Archlinux
 - App Version: latest

Thanks!

**Comment by rathboma** [comment]
Hey, did you install the snap?

If so, this is a bug with Snaps that I'm not in control of fixing, can you try the appimage?

**Comment by JasonVolney** [comment]
I understood you. Thanks for instance. Yes, I was using snap for that. @rathboma 

But where I find this package for download? By the way I'm going a head try it.

If doesn't to work I back do contact with you.

**Comment by JasonVolney** [comment]
I found. Thanks @rathboma 

https://aur.archlinux.org/beekeeper-studio-appimage.git

**Comment by rathboma** [comment]
Take a look at the releases section of the GitHub repository, there is a dot app image file Also is linked to from the website! You can CH mod a app image and just execute it like a regular binary

**Comment by JasonVolney** [comment]
@rathboma 

It's work! Thank very much.

![image](https://user-images.githubusercontent.com/54520187/109018233-b17f1600-7696-11eb-8a07-4fb99ebc1642.png)

**Comment by rathboma** [comment]
Can you try this potential workaround:
Potential workaround for the snap version:
```
$ sudo rm -f /var/cache/fontconfig/*
$ rm -f ~/.cache/fontconfig
```
From: https://forum.snapcraft.io/t/snap-store-fonts-on-arch-linux-are-merely-empty-rectangles/15373/9
