### ISSUE TITLE
BUG: whitespace characters are not displayed correctly in the query results.

### ISSUE THREAD

**Issue by BlackGlory** [beekeeper-studio/beekeeper-studio#574]
**Describe the bug**
Whitespace characters are not displayed correctly in the query results.

**To Reproduce**
```sql
SELECT '                           123';
```

**Screenshots / Gifs**
![image](https://user-images.githubusercontent.com/1365962/109027258-909cdc00-76fb-11eb-8e80-c7605dd4808a.png)

**Version Information (please complete the following information):**
 - OS: Windows 10 20H2
 - App Version 1.9.4

**Comment by rathboma** [comment]
Interesting. Can I ask if this has caused problems for you in real queries?

**Comment by BlackGlory** [comment]
@rathboma [PostgreSQL's EXPLAIN results have indentation](https://www.postgresql.org/docs/current/using-explain.html), if beekeeper cannot display whitespace characters, the results cannot be read at all.

**Comment by rathboma** [comment]
Very true. Let me look into it.
