### ISSUE TITLE
QUESTION: Feasibility of using Tauri as App builder

### ISSUE THREAD

**Issue by ng28** [beekeeper-studio/beekeeper-studio#577]
**Details:**
Happy to be part of the beekeeper studio app user!

I'd like to know the feasibility of using the [Tauri](https://tauri.studio/en/) app in place of `Electron`. It seems promising and quite reduces the build size half. You can check out the comparison [listed](https://github.com/tauri-apps/tauri#comparison-between-tauri-and-electron) here.

I'd tried on my own using Tauri but ended up having issues with electron-based build configurations and Xel imports.

Consider this as a dev-based feature if it is worth it.

Operating System: 
All Platforms

**Comment by rathboma** [comment]
I think that would be a lot of work, but possible if the 'native' aspects of the app are broken out into packages. We'll eventually do this as a way to run Beekeeper in a browser, but with our limited resources right now we're just going to continue to invest in the electron app experience.

I'm going to close this issue as I don't think it'll be something we can do for quite a while, but we'll definitely revisit it when we have more resources.

**Comment by MariusVB** [comment]
+1 for Tauri.
Tauri just released as beta and is now a pretty viable solution. It would definitely increase performance on weaker systems and decrease bundle size significantly. 
They promise around 180 MB RAM usage vs ~500MB for Electron.
