### ISSUE TITLE
BUG: UI scroll issue when a record has a very long entry

### ISSUE THREAD

**Issue by jonyen** [beekeeper-studio/beekeeper-studio#580]
**Describe the bug**
In Beekeeper Studio (1.9.4) on Mac 10.15.7 (Catalina), using a Postgres database, set up a table with a `text` column, put in the following data:
```
{
a:1,
b:2,
c:3,
d:4,
e:5,
f:6,
g:7,
h:8,
i:9,
j:10,
k:11
},
list: [
a,
b,
c,
d,
e
],
l: 12,
m:13,
n: 14,
o: 15,
p: 16,
q: 17,
r: 18,
s: 19,
t: 20,
u: 21,
v: 22,
w: 23,
x: 24,
y: 25,
z: 26,
aa: 27,
ab: 28,
ac: 29,
ad: 30,
ae: 31,
af: 32,
ag: 33,
ah: 34,
ai: 35,
aj: 36,
ak: 37,
al: 38,
am: 39,
an: 40,
ao: 41,
ap: 42,
aq: 43,
ar: 44,
as: 45,
at: 46,
au: 47,
av: 48,
aw: 49,
ax: 50,
ay: 51,
az: 52,
ba: 53,
bb: 54,
bc: 55,
bd: 56,
obj: {
ca: 79,
cb: 80,
cc: 81,
cd: 82,
ce: 83,
cf: 84,
cg: 85,
ch: 86,
ci: 87,
cj: 88,
ck: 89,
cl: 90,
cm: 91
},
be: 57,
bf: 58,
bg: 59,
bh: 60,
bi: 61,
bj: 62,
bk: 63,
bl: 64,
bm: 65,
bn: 66,
bo: 67,
bp: 68,
bq: 69,
br: 70,
bs: 71,
bt: 72,
bu: 73,
bv: 74,
bw: 75,
bx: 76,
by: 77,
bz: 78
}
```

Try to edit the data, and scroll down to the bottom. The expected behavior is that it should scroll down to the bottom, but instead it stops and goes back to the top. The same occurs when I try to use the keyboard to go down to the bottom. 

See the attached screen recording:

https://user-images.githubusercontent.com/674440/109690803-b93a3100-7b54-11eb-8a31-e90b8db2dbfb.mov

**Version Information (please complete the following information):**
OS: Mac OS 10.15.7 (Catalina)
App Version: 1.9.4

**Additional context**
If I manually input just a list of numbers from 1-96 on a neighboring column, it seems to resolve the issue as a temporary workaround. But when I remove that data, switch the tab and come back, the bug appears again.

**Comment by rathboma** [comment]
I'll be doing a release this week with a fix for this! Stay tuned.

**Comment by rathboma** [comment]
Marking as closed as it is already fixed (if not released)
