### ISSUE TITLE
BUG: Query parameter input containing $(number) being interpreted as another query parameter

### ISSUE THREAD

**Issue by jmturner** [beekeeper-studio/beekeeper-studio#581]
**Describe the bug**
Query parameter input containing $(number) interpreted as query parameter

**To Reproduce**
1. Build a query containing query parameters. I use the colon-type but it may work with $.
2. Run the query and input a value for your parameter that contains $1, $2, etc. For instance, a bcrypt hash begins with "$2y$10$..."
3. Click Run.
4. Beekeeper errors out with "syntax error at or near 'y', where y is the next character after the $(number).

**Expected behavior**
Beekeeper should pass the parameter input to the database without reinterpreting it.

**Screenshots / Gifs**
If applicable, add screenshots or GIFS to help explain your problem.

**Version Information (please complete the following information):**
 - OS: MacOS Catalina 10.15.7
 - App Version 1.9.4

**Additional context**
This is possibly related to #391.

**Comment by rathboma** [comment]
Thanks for filing.

Yes it should not pick up `$x` inside of strings.
