### ISSUE TITLE
portable version downloads setup from the website

### ISSUE THREAD

**Issue by phanirithvij** [beekeeper-studio/beekeeper-studio#583]
On Windows, the portable version downloads the setup file because both links point to the same URL `https://www.beekeeperstudio.io/download/?ext=exe&arch=`

![image](https://user-images.githubusercontent.com/29627898/110233732-10247980-7f4c-11eb-9f0c-4a0f73391afb.png)

**Comment by rathboma** [comment]
Bah! Thanks for pointing that out. Fixed.
