### ISSUE TITLE
BUG: JSON download is missing field names

### ISSUE THREAD

**Issue by huotarimikko** [beekeeper-studio/beekeeper-studio#584]
**Describe the bug**
When downloading the query results in JSON format, all field names are replaced with c0, c1, c2 etc. This happens with Postgres connections.

**To Reproduce**
1. Run a query against Postgres
2. Select "Download" -> "JSON"

**Expected behavior**

JSON file should look like following:

```
[
	{
		"id": "10105",
		"created_date": "2021-03-07 13:49:57.439+00",
		"lower_user_name": "test1"
	},
	{
		"id": "10106",
		"created_date": "2021-03-07 13:49:57.751+00",
		"lower_user_name": "test2"
	}
]
```

...instead the output file contains this:

```
[
	{
		"c0": "10105",
		"c1": "2021-03-07 13:49:57.439+00",
		"c2": "test1"
	},
	{
		"c0": "10106",
		"c1": "2021-03-07 13:49:57.751+00",
		"c2": "test2"
	}
]
```

A CSV download of the same query looks like this:

```
"id","created_date","lower_user_name"
"10105","2021-03-07 13:49:57.439+00","test1"
"10106","2021-03-07 13:49:57.751+00","test2"
```

**Version Information (please complete the following information):**
 - OS: Ubuntu 20.10
 - App Version: 1.9.4 / Snap
 - Database: Postgres 9.6.0

**Comment by rathboma** [comment]
I just filed a bug with Tabulator (and a PR).

I'll get this fixed. Thanks for the heads up!

https://github.com/olifolkerd/tabulator/issues/3235

**Comment by rathboma** [comment]
This should be fixed in the next release!
