### ISSUE TITLE
Saved Queries? Where do they go?

### ISSUE THREAD

**Issue by ac470** [beekeeper-studio/beekeeper-studio#585]
**Details:**
Where are the saved queries saved to when I hit save in beekeeper?

![Screen Shot 2021-03-07 at 4 03 10 PM](https://user-images.githubusercontent.com/80226855/110258203-9e096000-7f5e-11eb-9d7c-53f15e0a2250.png)

**Comment by rathboma** [comment]
Hey! Good question and I should probably add this to the documentation.

Beekeeper stores saved queries in it's own SQLite database. What platform are you on? I can tell you where the directory is if you're interested.

You can also connect to this database directly from Beekeeper itself! Go to `help -> Add Beekeeper Database`

Going to close this issue, but please reply if you are interested.

**Comment by nymd** [comment]
> What platform are you on? I can tell you where the directory is if you're interested.

Ubuntu 18.04 -- would be nice if I could grab them as a file for my new system without having to get the old one working again. Thanks @rathboma !

**Comment by forinda** [comment]
Just got where they are located @nymd 
![Screenshot from 2023-12-17 11-07-14](https://github.com/beekeeper-studio/beekeeper-studio/assets/55891685/480feb9e-19cf-4837-918e-ee43b2c0d8a9)
You can use `CTRL + p` to open up the search section. All queries saved will be listed there. When you start typing they'll pop up

**Comment by forinda** [comment]
> Just got where they are located @nymd ![Screenshot from 2023-12-17 11-07-14](https://private-user-images.githubusercontent.com/55891685/291043735-480feb9e-19cf-4837-918e-ee43b2c0d8a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4MDA4MjAsIm5iZiI6MTcwMjgwMDUyMCwicGF0aCI6Ii81NTg5MTY4NS8yOTEwNDM3MzUtNDgwZmViOWUtMTljZi00ODM3LTkxOGUtZWU0M2IyYzBkOGE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDA4MDg0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2MDlkOTc4ZDYzOTczODdlMDg5YjMxOWE2ZmJhMWQ3MTZhMjdkNDhmNmIyZjM0MjM5Njk0NDY3ZjRkNzk4M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A_f-p-Xfc1kFUfc9J8uvvNTxX0b34zmu8-X-mIt1790) You can use `CTRL + p` to open up the search section. All queries saved will be listed there. When you start typing they'll pop up

@ac470
