### ISSUE TITLE
FEAT: When clicking on a table in the sidebar which already exists in the tabs, open the already existing tab. 

### ISSUE THREAD

**Issue by davidbernegger** [beekeeper-studio/beekeeper-studio#586]
**Is your feature request related to a problem? Please describe.**
When clicking on a table in the sidebar which already exists in the tabs, it opens a second and third one. I always have to close multiple tabs that query the same database and it clutters the tab area. 

- funnily, this works for the saved queries already

**Describe the solution you'd like**
open / refresh / redirect to the already existing tab. In vscode for example, when clicking on an item in the sidebar which already exists, it won't open it twice / thrice but switch to the already existing tab.

**Additional context**

![image](https://user-images.githubusercontent.com/16232537/110354002-fe200500-8037-11eb-8af0-38532df3b0e9.png)

**Comment by rathboma** [comment]
So we did it this way because tables can have filters, scroll positions, etc, but we want to revisit this behavior soon.

I think we'll certainly be moving to double-click to open a table, so maybe we add a right-click => open in a new tab, or something like that.

**Comment by rathboma** [comment]
I'm going to close this as I don't think we'll be implementing this as-is, but will be re approaching this question soon
