### ISSUE TITLE
Maximum size of table to show?

### ISSUE THREAD

**Issue by SamSandq** [beekeeper-studio/beekeeper-studio#589]
I connected to a (remote) Postgres DB, and wanted to download a table. It has >1million records, some 2Gb of data. Using select * from <table> I wanted to get the listing, and press download in the bottom right corner. It took a looong time but seems to have got the whole table, but then the screen turned black and nothing happened.

I had to quit the app.

Or is there an easier way to download a csv of a table?

I'm on MacOS, Big Sur if it helps.

**Comment by rathboma** [comment]
There's a proper export function coming soon!

Also, currently the query execute -> download isn't very optimized. We'll be fixing that too (it needs to page results)

**Comment by rathboma** [comment]
I'm going to close this issue as this isn't about a specific feature or bug, but we'll be fixing this problem soon.
