### ISSUE TITLE
Can not connect to Digital Ocean: ER_NOT_SUPPORTED_AUTH_MODE

### ISSUE THREAD

**Issue by Gys** [beekeeper-studio/beekeeper-studio#59]
I am trying to connect to a mysql managed db on Digital Ocean (DO) but that fails. It is a mysql 8.x instance.

Problem 1:

Error:
ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client

DO explanation:
... error message means you are attempting to connect to MySQL using an application or a version 5.x client that does not support the caching_sha2_password.

Preblem 2:

DO also uses SSL=REQUIRED which is supported by Beekeeper. But it also has a client CA Certificate for that. Beekeeper does not support that (yet)?

**Comment by rathboma** [comment]
Thanks for the heads up. I'll investigate

**Comment by rathboma** [comment]
Not sure what platform you are on, but can you download the artifacts from:
https://github.com/beekeeper-studio/beekeeper-studio/actions/runs/98791837

When the build is done, and see if it works?

**Comment by rathboma** [comment]
(this is a fix for the AUTH_MODE, not the ssl client certificate)

**Comment by Gys** [comment]
The ER_NOT_SUPPORTED_AUTH_MODE error is gone. Now it just fails to make a connection after a few seconds. Server disconnected. I think this is indeed progress ;-)
Hope you can fix the certificate as well
