### ISSUE TITLE
Incorrect string parsing in queries

### ISSUE THREAD

**Issue by saberworks** [beekeeper-studio/beekeeper-studio#591]
In the following query, the semi-colon enclosed in quotes is detected by beekeeper studio as the end of the statement.  However, since it's in quotes, it should not be detected as such.

```
UPDATE customers
   SET detection_action_fk = 0
     , note = CONCAT(note, " (Detection action set to 0; see <ticket #>)")
 WHERE detection_action_fk = 10;
```

See attached screenshot.  In addition to the highlighting being messed up, when executed it actually only sends the first/highlighted part to the server so it generates an error.

![Screen Shot 2021-03-09 at 10 49 50 AM](https://user-images.githubusercontent.com/584773/110522560-e1caa980-80c5-11eb-8854-035961f87bc0.png)

**Comment by rathboma** [comment]
Excellent find, thank you. I'll use this as a test case on the sql-identification library.

**Comment by rathboma** [comment]
@saberworks what database are you running on?

Usually strings in sql use single quotes `'`, not double quotes, as double quotes are for identifiers, but that seems to work for you?

Does this work with single quotes?

**Comment by saberworks** [comment]
Using MySQL.  Yes it works with single quotes.

I guess I've been using them interchangeably for a decade.  Articles online indicate that either by convention or in some db rules, single quotes should be used for string literals and double quotes for aliasing columns or something.  However, the double quotes also fail in the following (silly) query:

```
 select customer_id as "customer_id;" from customers;
```

But this one works:

```
 select customer_id as 'customer_id;' from customers;
```

**Comment by MasterOdin** [comment]
With MySQL, `"` and `'` can be used interchangeable as a string identifier unless [ANSI_QUOTES](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_ansi_quotes) mode is enabled.

**Comment by rathboma** [comment]
@MasterOdin I've fixed this - https://github.com/sqlectron/sql-query-identifier/pull/31
