### ISSUE TITLE
BUG: Colors of string values in queries are illegible in Light Theme

### ISSUE THREAD

**Issue by shetlandbreeder** [beekeeper-studio/beekeeper-studio#594]
**Describe the bug**
Strings in queries (in single quotes) are yellow regardless of the theme chosen. In Light theme these elements are almost invisible - yellow on white is not a good choice. 
**To Reproduce**
Write a query of the form select * from foo where bar = 'something' in Light Theme

**Expected behavior**
A decent contrast between background and foreground.
**Screenshots / Gifs**
If applicable, add screenshots or GIFS to help explain your problem.

**Version Information (please complete the following information):**
 - OS: Arch Linux
 - App Version 1.9.4

**Additional context**
Anything else you think might be helpful

**Comment by rathboma** [comment]
This is just a stylesheet bug.

@ghstng can you take a look? May be I screwed something up recently

**Comment by ghstng** [comment]
rgr

**Comment by ghstng** [comment]
I believe this was already
![light-theme](https://user-images.githubusercontent.com/5122567/111698058-5f985e80-8804-11eb-8a17-0dc14966e69e.PNG)
 addressed in the upcoming release
