### ISSUE TITLE
QUESTION: How to *only* allow SSL connections that are signed by a CA?

### ISSUE THREAD

**Issue by D1plo1d** [beekeeper-studio/beekeeper-studio#595]
I'm looking to connect to my managed Postgres server over the internet. I don't know what cert is installed on the postgres host but I can expect that it will be signed by a CA that would be recognized by a browser (eg. LetsEncrypt).

However the Beekeeper wording makes it sound like the CA may potentially not get checked and any cert accepted by default(?) How would I tell Beekeeper to check for a valid CA-signed cert in the same way that for example Firefox would?

Related: https://docs.beekeeperstudio.io/guide/#ssl

**Edit:** To clarify my concern is that if the CA is not checked then I am open to man in the middling.

**Comment by rathboma** [comment]
Hey! If you have rejectUnauthorized checked it will verify the cert, this is the same as `verify-full` on the postgres command line

**Comment by D1plo1d** [comment]
Perfect, thanks!
