### ISSUE TITLE
Unable to resize/expand text fields in results

### ISSUE THREAD

**Issue by saberworks** [beekeeper-studio/beekeeper-studio#597]
**Describe the bug**
In the results, it seems that mysql "text" fields can't be expanded/resized, so it's impossible to show more or less than the width of the result column.

**To Reproduce**
Run a simple query that has a text field in the results.  Example:

`select comment_id, comment_text, comment_time from level_comments where user_id > 8200;`

MySQL table definition:
```

Field | Type | Null | Key | Default | Extra
-- | -- | -- | -- | -- | --
comment_id | int | NO | PRI | (NULL) | auto_increment
level_id | int | NO |   | 0 |  
user_id | int | NO |   | 0 |  
comment_text | text | NO |   | (NULL) |  
comment_time | int | YES |   | (NULL) |  
comment_ip | varchar(15) | NO |   |   |  
```

The "comment_text" field is unexpandable.  I can grab the vertical bar between it and the other columns but when I click and drag the cursor changes back to a finger and the column doesn't resize (either smaller or bigger).  Expanding/contracting any other field type in the results seems to work fine.

**Expected behavior**
Expect the column to resize like all the other ones.

**Version Information (please complete the following information):**
 - OS: Ubuntu 20.04, installed via deb and your repo
 - App Version 1.10.1

**Comment by rathboma** [comment]
This should be fixed in the next release!
