### ISSUE TITLE
Show the structure of a table

### ISSUE THREAD

**Issue by GuillaumeLegendre** [beekeeper-studio/beekeeper-studio#60]
Currently I can see the fields and type of a table.

But it would be great if we could see those information of the structure of the table:
• The default of a column
• The constraint of a column (primary key, foreign key, not null, uniq...)

The indexes of a table with those infos:
• name
• type (primary key index, index, uniq, constraint...)
• columns affected

**Comment by rathboma** [comment]
:100: it's on the next major feature push

**Comment by gnovaro** [comment]
I see in some gif column size in sidebar, for example: title varchar**(255)** is really useful, maybe in a minor release can include this?

**Comment by GammaGames** [comment]
Would be nice to have a pk and similar icons in column headers in the data viewer as well

**Comment by phillpafford** [comment]
Any progress on this feature? Not sure if I could also mention GRANTS and Comments as well as something I would like to see  in this view

**Comment by rathboma** [comment]
Oh, btw this is done!
