### ISSUE TITLE
sqlserver2008 windows10；tables and database is ok，but double click table failed 

### ISSUE THREAD

**Issue by AmarsDing** [beekeeper-studio/beekeeper-studio#608]
![image](https://user-images.githubusercontent.com/16753144/111984536-71e90400-8b46-11eb-9223-c0223df6f1a0.png)

**Comment by rathboma** [comment]
Can you test #604 ? I'll add to a point release today if it looks good.

**Comment by rathboma** [comment]
You should be able to dload the test exe from here:
https://github.com/beekeeper-studio/beekeeper-studio/actions/runs/669204920

**Comment by jim-starace** [comment]
Apologies, I had a busy day. Ill try and do this for you tomorrow

**Comment by rathboma** [comment]
I had other users confirm as working, it's in the new release!
