### ISSUE TITLE
Shortcut cmd + w should close a tab

### ISSUE THREAD

**Issue by GuillaumeLegendre** [beekeeper-studio/beekeeper-studio#61]
Currently, using cmd + w (on mac) close the window and the connexion to the database.

I was expecting it to close the tab I was working on.

I guess this apply also with ctrl + w on windows and linux.

**Comment by rathboma** [comment]
:100: the keybinding is there, just MacOS overrides it (grr). I can do it a different way I think

**Comment by rathboma** [comment]
@GuillaumeLegendre can you test the mac artifact attached to the PR and let me know if it fixes the issue?

Thanks!

**Comment by rathboma** [comment]
They should appear here when the build is done -https://github.com/beekeeper-studio/beekeeper-studio/actions/runs/101867521

**Comment by GuillaumeLegendre** [comment]
@rathboma Sadly it doesn't seem to work either. If you need more testing don't hesitate. Thx a lot for your work.

**Comment by rathboma** [comment]
Ok I've got another fix to try later, stand by!

**Comment by rathboma** [comment]
Ok, I actually have a fix now #110

**Comment by GuillaumeLegendre** [comment]
Yes it works 👍 🥇 Thank you
