### ISSUE TITLE
BUG: text columns open fully expanded after latest update

### ISSUE THREAD

**Issue by barthvader13** [beekeeper-studio/beekeeper-studio#610]
**Describe the bug**
After updating to the latest build, text columns widths are fully expanded while opening any table with a text column. 

I think https://github.com/beekeeper-studio/beekeeper-studio/issues/597 is related. It seems like you're overriding all text column widths to the maximum you've set, without first checking if the column requires that maximum.

**To Reproduce**
1. Click on a table that has a column type of `text`.
2. Notice the column's size is fully expanded.

**Expected behavior**
I expect the column width/size to match the size of the largest value up to a certain maximum width.

**Screenshots / Gifs**
How it looks now:
![image](https://user-images.githubusercontent.com/5341581/112406542-5ca8dc80-8ce2-11eb-9da9-b8723a700110.png)

How it looked before:
![image](https://user-images.githubusercontent.com/5341581/112406604-7ba76e80-8ce2-11eb-9043-a0dafdc8838c.png)

I have to scroll a ways now :smile: 

**Version Information:**
 - OS: Ubuntu
 - App Version 1.10.2

**Additional context**
I've been meaning to add a feature request, but it would be amazing to have an option for beekeeper studio to remember your column width preference on each table. Also maybe I'm missing something but my pins are cleared everytime I close the app. Is this intended behavior? If you could add a preference for users to check to save pins and column width sizes that would be yuuuge!

---
I also just wanted to say thank you for all the work you've put into maintaining and building this app. I used to have a mac but switched to linux recently. On macos I used Postico as my main postgres client and Beekeeper Studio is the only app available for Linux that comes close to the modern design and feel of Postico. So thanks again for this :partying_face:

**Comment by rathboma** [comment]
I have a fix coming next week :-). I've patched the table library

**Comment by barthvader13** [comment]
> I have a fix coming next week :-). I've patched the table library

@rathboma I just downloaded the most recent update (v 1.11.3) and unfortunately the text column length issue remains - all text columns are opened to a default max length as seen in the screenshots from my original post. Only reason I'm posting again is because you mentioned you had a fix and I think there's a misunderstanding/miscommunication on the issue.

**Comment by rathboma** [comment]
Grumble. Yes I think this should have been fixed, but maybe that was in another branch. Let me see.

**Comment by rathboma** [comment]
Can you download this build (once it's finished) - https://github.com/beekeeper-studio/beekeeper-studio/actions/runs/854557689

I think I've resolved column width behavior for everyone - max initial width, can be enlarged, if 30+ columns resorts to fixed initial widths for speed.

**Comment by rathboma** [comment]
@barthvader13 if that build looks good, I'll release it

**Comment by barthvader13** [comment]
@rathboma its fixed!!!
