### ISSUE TITLE
BUG: Values get replaced for (NULL) after multiple queries are executed.

### ISSUE THREAD

**Issue by CamPen21** [beekeeper-studio/beekeeper-studio#619]
**Describe the bug**
When multiple SQL statements in the same query script result data cells get replaced with (NULL).

**To Reproduce**
1. Go to saved connections.
2. Click on saved connection.
3. New query tab.
4. Write multiple statements on the same editor.
5. Click on run.
6. See the error

**Expected behavior**
Expected multiple tabs on the dropdown list with data populated.

**Screenshots / Gifs**
![image](https://user-images.githubusercontent.com/67205201/113923490-35f0a880-97ae-11eb-82de-260c3336bcc3.png)
![Capture](https://user-images.githubusercontent.com/67205201/113923170-d5fa0200-97ad-11eb-8087-9169fdcc2936.PNG)

**Version Information (please complete the following information):**
 - OS: Windows
 - App Version 1.10.2

**Additional context**
Connection to an Aurora/MySQL database.
Resulting number of rows for every statement are good, it's only the field data the one with the issue.

**Comment by rathboma** [comment]
OMG you're right. This seems to only happen for MySQL. Super duper good find. Thanks so much!
