### ISSUE TITLE
EADDRINUSE when connecting to vagrant

### ISSUE THREAD

**Issue by gempir** [beekeeper-studio/beekeeper-studio#62]
`connect EADDRINUSE 192.168.24.24:22 - Local (0.0.0.0:8001)`

I'm trying to connect to the mysql DB hosted in my local vagrant machine. 
But I'm getting an `EADDRINUSE`, I do have other ssh connections to the vagrant machine open at the same time.

Also it would have been nice if beekeeper would use the default ssh settings and key file instead of me manually providing the key file and not being able to specify my custom host from my ssh settings

**Comment by rathboma** [comment]
Oh, yeah totally. I think it just right now chooses that port by default. Definitely the ssh config should be more configurable.

As a workaround you can create a manual ssh tunnel and connect to that from beekeeper.

**Comment by rathboma** [comment]
Going to close this. I think it's resolved.

**Comment by gempir** [comment]
Jup works now in 1.5.3 thanks!
