### ISSUE TITLE
QUESTION: SSH Tunneling

### ISSUE THREAD

**Issue by mtwinux** [beekeeper-studio/beekeeper-studio#623]
**Details:**
Hi. I'm very happy about Beekeeper Studio and today i tried to use the ssh tunneling with Bastion Host and got stuck...

My case is this one : 
3 machines, let's call them

- M1 : My local OS running an Ubuntu 18.04 on virtual box. That's where is Beekeeper Studio
- M2 : Company server with **ssh port 2221** <- the jump server
- M3 : Production server holding a postgresql database listening on **port 5432**

M1 can access M2 via ssh
M2 can access M3 (on port 5432 and do ssh if needed...)

Let's say i got M1 on my ssh config set... If i run a tunnel like this : 
ssh -f **M2** -L 5430:**\<M3 ip\>**:5432 -N
then i can connect with Beekeeper Studio using localhost and port 5430. 

But if i want to use your ssh tunneling i can't make it work. I know i saw that i can't use ssh config so i wrote my M2 address.
I used debug and seems that you can't handle this custom port on the Bastion cause you are using the end port. I tried to put the port like this : **xx.xx.xx.xx:2221** but throw an error cause it's not expected obviously.

I admit it's not very clear for me how you use those connexion fields in this tunneling case. I tried to read your doc but found nothing on this and google it but was a dead end...

Thanks for your help.

**Version Information [might be relevant to your issue]**
Operating System:  Ubuntu 18.04
App Version [help -> about]: 1.10.2

**Screenshot / GIF [if appropriate]**:
A screenshot of the app if that helps

**Comment by rathboma** [comment]
I think the way this should work:

dbHost: M3
dbPort: M3Port
sshHost: M2

Then that should work?

**Comment by mtwinux** [comment]
Hi rahtboma. it worked ! Thanks a lot.
So i didn't have to use the Bastion.

Made a picture for who's interested.

![ssh_tunnel_beekeeper](https://user-images.githubusercontent.com/24273047/114730299-0824da00-9d41-11eb-915a-2d02bc06fb71.png)
