### ISSUE TITLE
QUESTION: Where are queries saved?

### ISSUE THREAD

**Issue by jmsigner** [beekeeper-studio/beekeeper-studio#626]
I am getting started with beekeeper and was wondering if saved queries are saved locally? If so, where are they saved so I can back them up?

**Comment by dagmar-urbancova** [comment]
I believe in it's own internal database
https://github.com/beekeeper-studio/beekeeper-studio/issues/585

**Comment by rathboma** [comment]
Yep! We have a big version 2 in the works, after that we'll be taking a hard look at this to maybe make it easier.
