### ISSUE TITLE
BUG: Timeout waiting for handshake

### ISSUE THREAD

**Issue by lil5** [beekeeper-studio/beekeeper-studio#627]
**Describe the bug**
Test and Connect fails to work and gives a confusing message.

After __Click 'Test' or 'Connect'__ nothing happens for around 3 seconds and then 2 errors pop up `Error establishing a connection` & `Timed out while waiting for handshake`.

**To Reproduce**
1. Go to 'Quick Connect'
2. Under 'Connection Type' click on 'MySQL' or 'MariaDB'
3. Enter the database credentials
4. Add an SSH Tunnel
5. Fill in 'SSH Hostname', 'SSH Username'
6. Select under 'SSH Authentication': 'SSH Agent' (the connection relies on a ssh key in .ssh)
5. Use a non-default port for ssh
6. Click 'save'
7. Click 'Test' or 'Connect'

**Expected behavior**
It works

**Version Information (please complete the following information):**
 - OS: Linux mint 
 - App Version: 1.10.2 (AppImage x86_64 same on DEB)

**Additional context**
I would be nice to know if the issue happened during the ssh connection or MariaDB connection. 

I've tried using ssh and mysql in the terminal and that connects fine.

**Comment by rathboma** [comment]
Thanks for the bug report. Is there anything in the log file - https://docs.beekeeperstudio.io/troubleshooting/#how-to-debug-beekeeper-studio ?

Did you enable SSL for the db connection?

**Comment by lil5** [comment]
The only file under `~/.config/beekeeper-studio/logs/` is `main.log` with the following contents:

```log
[<timestamp>] [info]                  initializing background
```

**Comment by lil5** [comment]
When I open the **developer tools** under **help** nothing happens in `network` or `console`. In the console the only logs I do get are missing SourceMaps, nothing extraordinary.

```log
DevTools failed to load SourceMap: Could not load content for
```

**Comment by lil5** [comment]
> Did you enable SSL for the db connection?

No

**Comment by lil5** [comment]
With the latest release it works in the following condition:
- the key file is manually selected
- SSH Authenticaton is set to **Key File**

**SSH Agent** option still does not work for me.
I will close this issue for now, if there is more interest, reopening is always possible.

Thanks for the support @rathboma
