### ISSUE TITLE
FEAT: Allow double-click on a .db or .sqlite file to open the file in Beekeeper Studio

### ISSUE THREAD

**Issue by rattrayalex** [beekeeper-studio/beekeeper-studio#629]
**Is your feature request related to a problem? Please describe.**
I want to be able to work with sqlite as easily as with a csv. With a csv, I double-click it, and I can see it.

**Describe the solution you'd like**
I'd like to be able to use macos's native "open with" for db files. For example:

1. Right-click on a file, press Open with..., have "Beekeeper Studio" appear as an option. When I click it, it opens and connects to the db.
2. Open the inspector for a file, select Beekeeper, and choose "Always open with"
3. In a terminal, `open -a Beekeeper\ Studio somefile.db` and have it work

**Describe alternatives you've considered**

**Additional context**
I tested with [chinook.db](https://cdn.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip). 
Changing the filename to `chinook.sqlite` did not help. 
Selecting a connection type and then selecting the file did work.

**Comment by rathboma** [comment]
Yes, 100%! Also should be able to `$ beekeeper-studio ./mydatabase.db`, or even `$ beekeeper-studio mysql://user@password:foo.com/bar`

**Comment by rattrayalex** [comment]
Ooh absolutely!! Though for CLI it sure would be nice if it was just `beekeeper` or even `bkpr`
