### ISSUE TITLE
FEAT: Reference A Saved Query Like A Database View In Another Query

### ISSUE THREAD

**Issue by yaaminu** [beekeeper-studio/beekeeper-studio#632]
**Is your feature request related to a problem? Please describe.**
Sometimes you might want to join a query to a previously saved query but there's no way to do that right now, I have to download the query as json (or manually copy them), extract the fields I need into the new query. 

**Describe the solution you'd like**
It'd be great if I could reference saved query in another query similar to how one can can query a materialized views. 

Example: 
Say I have already written query for fetching all products that have expired as `expired_products`, 
I would like to be able to do something like this:
`select count(1) from sales join expired_products ep on ep.product_id = sales.product_id where sale.sale_date >= ep.expiry_date`

**Assumptions**
Query should be on the same database server (but ideally should be possible across databases so far as they all exist on the same database server). 

Is this something that can be achieved? I would have no problem if I have to contribute to a pull request for this feature.

**Comment by rathboma** [comment]
So Beekeeper is really just a window into your database, it has no real ability to inject data into the execution flow.

This would require a much larger infrastructure, and possibly a custom execution engine, so it'd be quite significant work! Probably more than we've ever invested in Beekeeper to date :-O

That said, I think a reasonable solution would be making it easier to create views or other tables with queries.

In this example, you'd create a view named `expired_products` by clicking query -> right click -> export as new view.

I'm going to close this issue as no way we'd be able to do this :-). But def want your opinion on whether the view-creation would work for your use case?

**Comment by yaaminu** [comment]
@rathboma thanks for the detailed response. I was not aware that one could convert saved queries to views. That answers my question.

**Comment by rathboma** [comment]
No UI to do this yet, but I'll work on it soon :-)

**Comment by yaaminu** [comment]
Thanks a lot in advance. I can work on a PR myself too if that's also possible. It's  a feature I really need.
