### ISSUE TITLE
QUESTION: Row cloning functionality?

### ISSUE THREAD

**Issue by ReynoldsCahoon** [beekeeper-studio/beekeeper-studio#639]
**Details:**
I would like to clone a row, or insert a new row into a table.

It appears that the merged PR #525 should have added this functionality, but I do not see this in the app.

**Version Information [might be relevant to your issue]**
Operating System: Zorin OS 15.3
App Version [help -> about]: 1.10.2

**Screenshot / GIF [if appropriate]**:
![Screenshot from 2021-04-30 15-12-27](https://user-images.githubusercontent.com/2556251/116759183-98605180-a9c6-11eb-8415-80c4b7c9ff38.png)

**Comment by rathboma** [comment]
Coming in the next release! Hold tight :-)
