### ISSUE TITLE
[Enhancement] Double click on table to show records

### ISSUE THREAD

**Issue by danilopolani** [beekeeper-studio/beekeeper-studio#64]
Currently you have to click on a tiny icon and at a first glance it's not really friendly, maybe implementing a double click to achieve this would be better?

**Comment by rathboma** [comment]
I agree that we need to think more about accessibility of this feature.

I'm going to track this on #96 . Double click is terrible because it delays the single-click (which currently opens the column specs), but I'm not closing because I disagree with the sentiment.

**Comment by danilopolani** [comment]
Yeah probably double click is a bad idea (to realize too), maybe we could invert the current behavior? Single click = open data, icon = toggle columns? Or simply open data and toggle columns together at single click, idk

**Comment by rathboma** [comment]
Hah, yeah I'm not sure of the primary action yet either. I'll play with a few alternatives
