### ISSUE TITLE
FEAT: RPM version needed

### ISSUE THREAD

**Issue by ghost** [beekeeper-studio/beekeeper-studio#640]
This product is great but there is no rmp installation version of it.

**Comment by rathboma** [comment]
There's a PR: #218 <- but I'm struggling what to do with the postinstall script -- it currently changes a system setting and I'm not sure if it should.

@man-kobie any thoughts here?

**Comment by SaltyPeppermint** [comment]
In Fedora 34 max_user_namespaces is set to 55284 by default (I think this is due to buildah and podman depending on user namespeces) which removes the need to change system settings.

I agree that changing system settings is not desirable here but thankfully it is no longer needed.

**Comment by rathboma** [comment]
Hey all! Apologies, but I'm going to close this in favor of sticking with the AppImage as default for the foreseeable future. AppImages are so easy to build and distribute.
