### ISSUE TITLE
QUESTION: Difference between Studio & Redshift Client

### ISSUE THREAD

**Issue by jamesarosen** [beekeeper-studio/beekeeper-studio#645]
**Details:**
The [Beekeeper Studio homepage](https://www.beekeeperstudio.io/) says it works with PostgreSQL, MySQL, Redshift, and more.

The [Beekeeper Studio Redshift Client page](https://www.beekeeperstudio.io/db/redshift-client/) says it works with Redshift.

What's the difference? Is the latter just a _feature_ of the former? The website doesn't make it clear.

**Comment by vensauro** [comment]
they are the same product, but the redshift page is make for SEO, some people will search for redshift client, and not for sql client

**Comment by jamesarosen** [comment]
That makes sense. The SEO definitely worked: that's how I first found Beekeeper. I was just confused because I also wanted support for MySQL and wasn't sure whether I was going to get it from the Redshift page.

**Comment by vensauro** [comment]
Awesome, the beekeeper works for mysql too, here is some print from the connection menu:
![image](https://user-images.githubusercontent.com/41435789/117738138-b9e4e880-b1d1-11eb-8496-78389c65f51c.png)

**Comment by rathboma** [comment]
Lol, yes we should probably mention the other databases we support. Thanks for the heads up!
