### ISSUE TITLE
BUG: Table pane doesn't return all rows

### ISSUE THREAD

**Issue by fiendish** [beekeeper-studio/beekeeper-studio#651]
**Describe the bug**
Table data pane does not reflect recently inserted rows even after refreshing or quitting and relaunching or installing new version.
The correct data shows when querying in the query pane.

**Screenshots / Gifs**

<img width="490" alt="Screen Shot 2021-05-13 at 3 07 43 PM" src="https://user-images.githubusercontent.com/201996/118192617-a620c880-b403-11eb-82a9-2df3d1bc3152.png">

![Screen Shot 2021-05-13 at 3 07 33 PM](https://user-images.githubusercontent.com/201996/118192642-ae790380-b403-11eb-82f2-30e283465bca.png)

<img width="529" alt="Screen Shot 2021-05-13 at 3 51 44 PM" src="https://user-images.githubusercontent.com/201996/118192593-9dc88d80-b403-11eb-8aa6-e0470248ffee.png">

**Version Information (please complete the following information):**
 - OS: macOS Catalina 10.15.7
 - App Version 1.10.2 and also current github master

**Comment by rathboma** [comment]
Yes, this is an approximate row count. We do this for performance reasons on Postgres, see #311 for example. I'll add a ~ to the front of the value to make that clear

**Comment by rathboma** [comment]
We'll be changing how paging works in the future so it doesn't have page numbers, this will allow you to go to the actual end of the table without this issue.
