### ISSUE TITLE
Running Multiple Queries Causes all results to be null

### ISSUE THREAD

**Issue by pixeloution** [beekeeper-studio/beekeeper-studio#652]
Write two simple queries in the client, for example: 

```
SELECT project.*
FROM   project
LIMIT  5;

SELECT 	*
FROM    region;
```

Click run. The results are all null on MacOS for both result sets. Queries will run individually and return results successfully

<img width="966" alt="Screen Shot 2021-05-14 at 17 14 55" src="https://user-images.githubusercontent.com/487337/118336749-e8b3d500-b4d7-11eb-9402-9e8c63d0deb2.png">

**Comment by rathboma** [comment]
Yes, sorry about that. Release coming on Monday with a fix!
