### ISSUE TITLE
Question: Multiple Databases

### ISSUE THREAD

**Issue by keithwhyman** [beekeeper-studio/beekeeper-studio#653]
Hi, 

I have about 14 dbs on one server and can see them all in the dropdown at the top, but seem to ba having problems connecting to them.
And there  seems to be no way to have several open at once?
Or have I missed something

thanks

**Comment by rathboma** [comment]
Hmm. What database and database version are you using? What OS are you on?

Can you attach a screenshot of the connection problem?

Opening several at once - currently you can do this by having two windows open, but you are correct, not in the same window at the moment.

**Comment by keithwhyman** [comment]
Changing the dbs does now seem to work, but having multiple would still be helpful
10.4.14-MariaDB-1:10.4.14+maria~bionic on Ubuntu over ssh
Windows 10
![live-demo-de ALL](https://user-images.githubusercontent.com/6489888/119143427-df7eb700-ba47-11eb-94a7-f2bb8839488c.png)
