### ISSUE TITLE
BUG: Clicking in a blob field, marks it as a commit

### ISSUE THREAD

**Issue by evs-xsarus** [beekeeper-studio/beekeeper-studio#657]
**Describe the bug**
In a table with a blob field, clicking in and out of that field, put's a commit in the queue. This shouldn't happen

**To Reproduce**
1. Create a table with a blob field.
2. Put some records in the tables
3. Open the table and click in the blob field
4. Click outside the field

**Expected behavior**
No commits are put in the queue as nothing should be changed.

**Screenshots / Gifs**
Watch the corner at the right bottom.
![2021-05-18_commit-queued](https://user-images.githubusercontent.com/44158071/118664123-7f8ed300-b7f1-11eb-93f8-065b4b1c9972.gif)

**Version Information (please complete the following information):**
 - OS: Ubuntu Unity 20.04
 - App Version: 1.11.3
 - Database: Percona 8.0.22

**Additional context**
na

**Comment by rathboma** [comment]
@evs-xsarus thanks for the feedback! That's a great find. I'll see what's going on

**Comment by rathboma** [comment]
@evs-xsarus what database?

**Comment by evs-xsarus** [comment]
This is in Percona 8.0.22

**Comment by rathboma** [comment]
@evs-xsarus can you check if this is still a problem?

**Comment by evs-xsarus** [comment]
Is fixed :+1:
