### ISSUE TITLE
QUESTION: Run in portable mode with a switch

### ISSUE THREAD

**Issue by naderi** [beekeeper-studio/beekeeper-studio#660]
**Details:**
Is there a possibility to run the file "Beekeeper Studio.exe" in portable mode. Something like:
```
Beekeeper Studio.exe --portable
```

**Version Information**
Operating System: Windows 10
App Version: 1.11.5

**Comment by rathboma** [comment]
I have to package the portable mode differently I'm afraid -- but there is a portable version of Beekeeper Studio you can download from the website!
