### ISSUE TITLE
BUG: Unable to export table data as SQL with advanced options active

### ISSUE THREAD

**Issue by UdittLamba** [beekeeper-studio/beekeeper-studio#666]
**Describe the bug**
When exporting the table as an SQL file, if you select 'Create Table Before Inserting', the app gets stuck on exporting user notification and produces an empty .SQL file.

**To Reproduce**
Steps to reproduce the behaviour:
1. Right lick on a table and choose export.
2. Click on Format dropdown and choose SQL
3. Expand Advanced Options and Select 'Create Table Before Inserting'
4. Click Run

**Expected behavior**
Should generate a non empty .SQL file

**Screenshots / Gifs**
none

**Version Information (please complete the following information):**
 - OS: Ubuntu 21.04 x86_64
 - App Version : 1.11.6 latest/edge

**Comment by rathboma** [comment]
Hmm.

@UdittLamba What database were you testing against?

**Comment by UdittLamba** [comment]
@rathboma I was using MySQL.

**Comment by FusionPwN** [comment]
Same issue here, mine just hangs with the "Exporting table" notification on screen
