### ISSUE TITLE
BUG: Refresh button not clickable (1.11.6, Mac Os 11.3)

### ISSUE THREAD

**Issue by dafen** [beekeeper-studio/beekeeper-studio#668]
**Describe the bug**
The button in the lower left hand side corner of the table view that says when the view has been updated the last time is not clickable anymore.
When clicked, the view does not refresh anymore instead the button just gets a colored outline:
![Bildschirmfoto 2021-05-27 um 13 24 57](https://user-images.githubusercontent.com/3841117/119817998-f1040b00-beee-11eb-8f92-0227ebfa95c9.png)

**To Reproduce**
1. Connect to any database
2. select any table to see it's rows
3. (Optional) Update that table from extern
4. Try to refresh the table view to the the updates by clicking the refresh button that states the time since the last fetch

**Expected behavior**
The data view should refresh / refetch and show the current data. The time since last fetch should change to "now"

**Screenshots / Gifs**
![Bildschirmfoto 2021-05-27 um 13 24 57](https://user-images.githubusercontent.com/3841117/119817998-f1040b00-beee-11eb-8f92-0227ebfa95c9.png)

**Version Information (please complete the following information):**
 - OS: Mac OS 11.3
 - App Version 1.11.6

**Additional context**
The issue only appeared with release 1.11.6 on my machine. However downgrading to 1.11.5 did not solve the issue, so there might be another reason other than updating Beekeeper.

**Comment by rmahmood19** [comment]
Thats not the refresh button anymore. This only shows when it was refreshed.
![Screenshot 2021-06-01 at 09 41 07](https://user-images.githubusercontent.com/24376261/120285658-bff45380-c2bd-11eb-8cb2-cb6014151725.png)

Its on the other side of the menu under the setting icon. Though i think that's a strange choice.

**Comment by dafen** [comment]
@rmahmood19 Thanks you, that works. I agree this seems like a strange and unnecessary change as it just make the workflow worse and slower.
