### ISSUE TITLE
Edit table row in a custom query 

### ISSUE THREAD

**Issue by MarchTala** [beekeeper-studio/beekeeper-studio#673]
**Details:**
is there a way to edit the table row after I make a custom query. Thank you in advance.

Example: I just want to change the column monthName from January to Jan. But i

(please see image below)

**Screenshot / GIF [if appropriate]**:
![image](https://user-images.githubusercontent.com/20549168/120478330-50768500-c3df-11eb-8aff-b33e060fb013.png)

**Comment by rathboma** [comment]
Hey! Sorry this isn't really possible :-(, but you can just open that table and filter for monthName and update it there :-)

**Comment by MarchTala** [comment]
> Hey! Sorry this isn't really possible :-(, but you can just open that table and filter for monthName and update it there :-)

Okay I got it. Thanks for the response.
