### ISSUE TITLE
DriverPackageNotInstalledError: SQLite package has not been found installed. Try to install it: npm install sqlite3 --save

### ISSUE THREAD

**Issue by AmarsDing** [beekeeper-studio/beekeeper-studio#675]
description ： 
**electron-builder** docker to build linux release package。
cmd： 
1 docker pull electronuserland/builder
2 docker run --rm -ti -v E:\beekeeper-studio\:/protect -w /protect amd64/centos
3 yarn install
4 yarn run electron:build
5 copy dir  ./dist_electron/linux-unpacked  to **centos7**
6 chmod +x ./beekeeper-studio     chmod +x ./beekeeper-studio   =>  change to  su  user
7 run  beekeeper-studio --no-sandbox
error :

db-connection
22:57:10.723                     › initializing background
Parsing app args { _: [], sandbox: false }
22:57:10.904                     › UnhandledRejection DriverPackageNotInstalledError: SQLite package has not been found installed. Try to install it: npm install better-sqlite3 --save
    at process.n (/home/atc/linux-unpacked/resources/app.asar/background.js:2:303681)
    at process.emit (events.js:315:20)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)

**Comment by rathboma** [comment]
Yes, this is due to the version of glibc on that version of centos. Make sure that better-sqlite3 is version 7.1.2 or lower.

**Comment by rathboma** [comment]
see #663 . You need to build on a machine with the right version of glibc. If you build on eg, Ubuntu 20.04 it'll pack the wrong version of sqlite. That's why I build on Ubuntu 18.04.

So you're building with glibc 2.19, then running on a machine with 2.18, which won't work.
