### ISSUE TITLE
FEAT: Sqlite open table slow due to count() query.

### ISSUE THREAD

**Issue by lambdaupb** [beekeeper-studio/beekeeper-studio#677]
**Is your feature request related to a problem? Please describe.**
Opening a large table in sqlite takes a long time because beekeeper does a `count()` query.
count queries are a little slow on sqlite since the total count is not maintained separately.

**Describe the solution you'd like**
either limit the count query to some maximum time or only do it upon user request.

**Describe alternatives you've considered**
-

**Additional context**
Tried with a >10GiB sqlite with 3mio rows, count takes 10s+ on SSD.

**Comment by lambdaupb** [comment]
`COUNT` is even done on each page navigation, which makes everything super slow.
The actual page data query is fast however.

**Comment by lambdaupb** [comment]
`select count(*) from (select * from table_xyz limit 1000)`
is fast, so maybe do this instead of a total count, for pagination is should be ok.

or just don't rely on the total count for pagination.

**Comment by rathboma** [comment]
This is fixed
