### ISSUE TITLE
QUESTION: Why does clicking on a table open a new tab every time, even if it's open already?

### ISSUE THREAD

**Issue by shamimmirzai** [beekeeper-studio/beekeeper-studio#678]
Just curious why clicking on the same table name opens up a new tab every time, even if it's open already.  I find myself with dozens of tabs open in a short space of time just switching between tables a few times.
Thank you for the awesome software.

**Comment by rathboma** [comment]
Hey!
So in the next release we're making it a double click, which should help.

The reason we let you open the tab again is to deal with filters - you can have a table filter in one pane, and a full table in another.

**Comment by rathboma** [comment]
Going to close this issue. This question does keep coming up. We may change the behavior if it continues to frustrate
