### ISSUE TITLE
Typo on the footer logo on the website

### ISSUE THREAD

**Issue by Thiht** [beekeeper-studio/beekeeper-studio#68]
Hey,
On the website you have a typo on the logo in your footer. It says Beekepeer instead of Beekeeper :)

<img width="375" alt="Capture d’écran 2020-05-07 à 15 00 39" src="https://user-images.githubusercontent.com/2796344/81297469-9396e500-9073-11ea-830a-1b44211c1f9f.png">

**Comment by rathboma** [comment]
hah! Thanks. @ghstng for you!

**Comment by ghstng** [comment]
lol... oops. Tks

**Comment by ghstng** [comment]
pushed
