### ISSUE TITLE
QUESTION: How do I fix this error during 'apt update'

### ISSUE THREAD

**Issue by kingram6865** [beekeeper-studio/beekeeper-studio#686]
**Details:**
When running `apt update` I am getting this error:
`403  Forbidden [IP: 34.213.218.48 443]`

**Version Information [might be relevant to your issue]**
Operating System: Debian Buster
App Version [help -> about]: Not installing this app. Just want to find out why I'm getting this error and how to fix it.

**Screenshot / GIF [if appropriate]**:
A screenshot of the app if that helps

**Comment by rathboma** [comment]
Bintray went offline and killed our package repository. If you download the latest package from the releases page it will automatically update the repository to the right one.

**Comment by rathboma** [comment]
Or you can just delete the repository file from /etc/apt/apt.sources.d
