### ISSUE TITLE
BUG: OnClick TableViewItem when value is Null create Commit

### ISSUE THREAD

**Issue by barrrettt** [beekeeper-studio/beekeeper-studio#688]
OnClick TableViewItem when value is Null create Commit.

1. Go to Entities list
2. Double Click on table
3. On new tab, find Null value
4. Click on other Null value
5. See Commit button: pendings changes +1

Expected behavior:
Discard change, no add pending change
![image](https://user-images.githubusercontent.com/47840319/121655537-f9d40f80-ca9e-11eb-8d2d-d0f0dc477ec2.png)

**Comment by rathboma** [comment]
Bah. Yes you’re right.

**Comment by rathboma** [comment]
This is fixed in the next release!
