### ISSUE TITLE
Error in viewing the table data

### ISSUE THREAD

**Issue by MajoDurco** [beekeeper-studio/beekeeper-studio#69]
**Beekeeper: Version 1.2.0 (1.2.0)**
**Platform: macOS Catalina 10.15.2**

Hey, I freshly downloaded the beekeeper 🐝connected to local Postgres. Unfortunately got an error when I tried to show the table data. Please see the following screenshot.

<img width="600" alt="Screenshot 2020-05-07 at 15 05 46" src="https://user-images.githubusercontent.com/13154028/81298673-63504600-9075-11ea-9159-2a3e10ed4b78.png">

I can gladly send you the logs or any more info just point me where I would find it.

**Comment by rathboma** [comment]
Can you try clicking a header to sort the table? Does that make it work?

**Comment by MajoDurco** [comment]
Forgot to mention one thing the red error disappears after a while and it's replaced with a blank screen. When I try to search for something the same error appears and again it disappears after a while.

**Comment by hillmanov** [comment]
It might be related to the capital in the table name: `Accounts`. Without surrounding the tablename in quotes, postgres will just convert it to all lower case, which will obviously throw this error. This may have been fixed by this PR: https://github.com/beekeeper-studio/beekeeper-studio/pull/82

**Comment by rathboma** [comment]
This is fixed in #82 . New release coming later this week, stay tuned!
