### ISSUE TITLE
Same sql code returns less rows on Beekeeper but more rows in other sql client

### ISSUE THREAD

**Issue by DavidQuartey** [beekeeper-studio/beekeeper-studio#691]
Hi @rathboma,

Really liking the SQL Client you've created. 

However, I have an issue where my SQL code returns 50, 000 rows whiles using Beekeeper. However, I'm the same code returns 50154 rows whiles in other clients.  So it means there's a couple of missing data points. Is there a 50K row limit built into the client?

Don't know what info might be helpful. And yes, I'm using the latest update.

**Comment by rathboma** [comment]
Yes there’s a 50k cap to results. It should indicate that somewhere in the footer? I’ll double check tomorrow.

an unfortunate limit until we can move execution to a background process.

**Comment by DavidQuartey** [comment]
Thanks for confirming @rathboma. Does that then mean exporting the excess beyond the 50K limit is not possible for now? or is the limit specific to what number that can be displayed in the result tab?

**Comment by rathboma** [comment]
No. I think that's a bug you've found! I'll get it seen to

**Comment by DavidQuartey** [comment]
@rathboma, I'm not too clear which question your answer is a response to?
