### ISSUE TITLE
BUG: Empty String columns are rendering as null

### ISSUE THREAD

**Issue by the-destro** [beekeeper-studio/beekeeper-studio#698]
**Describe the bug**
Columns with a value of '' are rendered in the results as null

**To Reproduce**
Have some data with columns that have empty strings they will show as `null` while the actual null is `NULL`

**Expected behavior**
It should render as an empty cell, or some other placeholder but having it be `null` is problematic

**Screenshots / Gifs**
<img width="327" alt="Screen Shot 2021-06-17 at 4 56 26 PM" src="https://user-images.githubusercontent.com/11051278/122477194-f8b64d00-cf8c-11eb-9acd-dddcccafe47e.png">

**Version Information (please complete the following information):**
 - OS: macOS
 - App Version 1.12.0

**Comment by ariasmn** [comment]
Hi! @rathboma 

I want to start contributing to this amazing project (thank you so much for it by the way, I use it daily in my day to day job), and I thought this would be a good first issue.

What you do think is the best approach? Show an `(EMPTY)` placeholder, or just show the empty cell? Here you have two screenshots:

- EMPTY placeholder
![image](https://user-images.githubusercontent.com/33121576/125661434-3f92b92a-a230-4a9b-af81-ce1dbdbe53d7.png)

- Cell empty
![image](https://user-images.githubusercontent.com/33121576/125661476-d69f1a11-240f-4d2c-8ba3-3c5f6a4bd78c.png)

Once you tell me what's the correct thing to do, I can make a PR for this. :smile:

**Comment by rathboma** [comment]
I actually have this fixed :-))

It's being merged as part of a bigger change on Monday.

Def would love contributions though. I'll find some other good starter issue for you!

**Comment by rathboma** [comment]
I did it how you proposed actually. But I'm pairing it with a custom input editor that allows switching between blank and null

**Comment by ariasmn** [comment]
@rathboma Glad that you already sorted it out!

Also, would love if you can guide me to those good starter issues. Waiting for those! :smiley:

**Comment by rathboma** [comment]
This should be fixed in the next release!
