### ISSUE TITLE
FEAT: Bring back the quick refresh functionality

### ISSUE THREAD

**Issue by bediu** [beekeeper-studio/beekeeper-studio#700]
In older versions, you could click on the clock icon as seen in the picture below, and it would refresh the current table.
![refresh](https://user-images.githubusercontent.com/43962398/122548242-62883280-d031-11eb-8759-f2bccbc6d187.png)

Now this feature has been moved to a sub-menu and there is one extra step to refresh a table: 
![refresh-new](https://user-images.githubusercontent.com/43962398/122548341-851a4b80-d031-11eb-846d-517673dce691.png)

There is absolutely no reason why would you make such a useful feature harder to access.

**Comment by rathboma** [comment]
Removing this was not intentional. We can put it back for sure. Easy to do!
