### ISSUE TITLE
FEAT: Cloud version?

### ISSUE THREAD

**Issue by ThomasLohmann** [beekeeper-studio/beekeeper-studio#709]
Hi everyone, 

any plans to release a cloud version of Beekeeper? It would be a great thing, since a lot of infrastructures are cloud native nowadays + more and more companies are moving away from local dev setups.

Best regards,
Thomas

**Comment by moltar** [comment]
Would love to see that as well.

Use case: deploying into AWS private subnet

**Comment by rathboma** [comment]
:wave: Hello! Thanks for bringing this up!

Yes we hope to offer a cloud version in the future, but with limited resources we'll get there slowly.

I'm going to close this ticket, as there's nothing to really 'do' right now, but don't worry we definitely aren't ignoring this idea :-)
