### ISSUE TITLE
Case sensitive filtering

### ISSUE THREAD

**Issue by MajoDurco** [beekeeper-studio/beekeeper-studio#71]
**Beekeeper: Version 1.2.0 (1.2.0)**

I've noticed that the filtering of the tables is case sensitive and just would like to ask if that's intentional or it can be changed to case insensitive? Thanks 👍

**Comment by rathboma** [comment]
Oh, yes that's a bug :-)

**Comment by MajoDurco** [comment]
Thank you for a quick fix 🙂
