### ISSUE TITLE
BUG: Export Table to CSV both missing newlines and randomly adding newlines

### ISSUE THREAD

**Issue by SampsonCrowley** [beekeeper-studio/beekeeper-studio#712]
**Describe the bug**
Export to CSV (Beta)

Random rows are missing "newline" separators for the next row, and random rows have additional new lines between them
Also no information is given on what "chunk size" means in this export context

**To Reproduce**
1. Right click a table
2. Click on 'export' (beta)
3. Format "CSV"
4. See Resulting Document

**Expected behavior**
Exported CSV should be properly formatted, and all columns should be properly quoted as necessary

**Screenshots**
<img width="632" alt="Screen Shot 2021-06-30 at 6 39 49 AM" src="https://user-images.githubusercontent.com/22461638/123961870-0cd75280-d96e-11eb-88b5-1ec1c8428599.png">
<img width="940" alt="Screen Shot 2021-06-30 at 6 41 16 AM" src="https://user-images.githubusercontent.com/22461638/123962048-427c3b80-d96e-11eb-9f5e-0b2bd122c92e.png">

**Version Information (please complete the following information):**
 - OS: Mac
 - App Version: 1.12.0

**Additional context**
See Attached Exported Table
[public_app_relations_export_2021-06-30_063932.csv](https://github.com/beekeeper-studio/beekeeper-studio/files/6740916/public_app_relations_export_2021-06-30_063932.csv)

**Comment by rathboma** [comment]
That's really weird.

Could you do me a favor and download the JSON version too? That's a 'raw' export and will help me debug.

**Comment by SampsonCrowley** [comment]
@rathboma sure thing. I will see if it is still happening after recent update

**Comment by SampsonCrowley** [comment]
Sorry I didn't see notification for reply

**Comment by wouthoekstra** [comment]
I can acknowledge that this is still happening after the most recent update (1.13.2 on Linux in my case). Some observations:
* It happens both during json and csv exports
* The missing newlines seem to correspond with the 'added' newlines. I think all of the faulty entries look like this (the first object gets 2 commas, while the next one lacks one):
```
 {
    "key": "value"
  },
,
  {
    "key": "value",
  }  {
```
* json exports always starting with a comma like this (note the comma after the square bracket), and ends with a dangling comma after the list as well (note the comma before the last square bracket)
```
[
,
  {
    "foo": "bar",
    "baz": 1234
  },
{
    "foo": "bar",
    "baz": 1234
  },
]
```

**Comment by rathboma** [comment]
Uck, so sorry about this. I'll get this fixed for the next release.

**Comment by wouthoekstra** [comment]
@rathboma I wanted to provide you with a neat create table / insert data package to reproduce the problem. But I noticed that the same problem occurs with sql exports. I guess that it also uses the same raw json base and will also be fixed when you have a fix for the json/csv export?

**Comment by rathboma** [comment]
I've fixed this. Couple of missing `await` calls. Will be in the next release.
