### ISSUE TITLE
BUG: incorrect parameter detection in string

### ISSUE THREAD

**Issue by thasmin** [beekeeper-studio/beekeeper-studio#713]
**Describe the bug**
When setting a PostgreSQL JSON field, Beekeeper is asking for a parameter

**To Reproduce**
1. Run this SQL statement: UPDATE table SET json_field = '{"key":false}'
2. Get asked for a value for the parameter :false

**Expected behavior**
Since :false is inside a string, it is not a parameter.

**Version Information (please complete the following information):**
 - OS: Windows
 - App Version: 1.12

**Comment by rathboma** [comment]
Yes I'm sorry, this is definitely a problem :-(.

We'll do a bug fix release after the next one so I'll hopefully be able to address this once and for all

**Comment by rathboma** [comment]
FYI I've pushed a change to a library that we use for query identification that should allow us to fix this soon properly

**Comment by herbertpimentel** [comment]
Even when it as properly paramter bug is commented (inactive for the query context) beekeeper still asks for it.

![image](https://user-images.githubusercontent.com/1668448/128016513-21ce5b39-998f-4faa-b60e-8d82be346e91.png)


![image](https://user-images.githubusercontent.com/1668448/128016648-813bc085-31d4-4263-b20c-e33426f4216c.png)
