### ISSUE TITLE
Azure SQL Server - Tables will not load

### ISSUE THREAD

**Issue by cj-alert** [beekeeper-studio/beekeeper-studio#714]
I create a connection.
I test the connection (success).
I connect (success).
I see a list of tables, etc.
I try to open a table, and receive the error: "error loading data. see error below"
I see below: "Cannot read property '1' of null."
[1625266135980.log](https://github.com/beekeeper-studio/beekeeper-studio/files/6757338/1625266135980.log)

**Comment by rathboma** [comment]
Can you let me know exactly what type of database you started on Azure? A screenshot of the specific page and the configuration you are using would be very helpful.

**Comment by cj-alert** [comment]
Hi. It's was a s0 sql server database on azure. Standard configuration.
What would you like a screenshot of? Beekeeper or azure? Thanks so much!

**Comment by rathboma** [comment]
This is fixed for the next release!
