### ISSUE TITLE
BUG: Can't create Stored Procedures in MariaDB database

### ISSUE THREAD

**Issue by marcelsby** [beekeeper-studio/beekeeper-studio#717]
**Describe the bug**
Beekeeper returns a error when i try to create a user-defined stored procedure in MariaDB, but when i try to do this in DBeaver it goes smooth. And when i create the procedure with DBeaver i can see the stored procedure refreshing Beekeeper entities sidebar, but the exactly same query copied and pasted in Beekeeper doesn't work.

**To Reproduce**
1. Connect to a MariaDB database
2. Write a SQL query to create a stored procedure
3. Execute this query

**Expected behavior**
Returns success message and shows the stored procedure on entities sidebar.

**Screenshots / Gifs**
Result when i try to create with Beekeeper Studio:
![create_stored_procedure_mariadb](https://user-images.githubusercontent.com/57691142/124392602-0417b100-dccd-11eb-8fe2-9ece552942f4.png)

When i create with the same SQL query in DBeaver:
![created_with_dbeaver](https://user-images.githubusercontent.com/57691142/124392601-02e68400-dccd-11eb-9b49-b33383384e62.png)

**Version Information (please complete the following information):**
 - OS: Fedora 34
 - App Version: 1.12.0

**Comment by AlexanderMisel** [comment]
I think you can remove the `DELIMITER $$` to get it work. I think this delimiter syntax only applies in MySQL terminal client.

**Comment by rathboma** [comment]
Hey! Alexander is correct. This is syntax for the mysql terminal client only. Probably Beekeeper should warn you (or just work) if you add the delimiter syntax. I'll create a separate issue for that.

**Comment by marcelsby** [comment]
Thanks for the help m8's ;)
