### ISSUE TITLE
FEAT: Allow hostname localhost to remain as localhost instead of remapping to 127.0.0.1

### ISSUE THREAD

**Issue by AndrewHutcheson** [beekeeper-studio/beekeeper-studio#720]
via ssh, beekeeper studio will try to rename localhost in the main Host field to 127.0.0.1. Mysql doesn't accept this, as it seems localhost uses a unix socket while 127.0.0.1 uses tcp (at least my server does but I don't have access to change it). 

It appears to me that beekeeper has something coded in to check localhost and remap it to an ip? I need to login with localhost, but the beekeeper error message implies beekeeper itself is changing it to the ip.

**Comment by rathboma** [comment]
Hey! So all connections with Beekeeper have to be over TCP, it cannot use UNIX Sockets unfortunately.
