### ISSUE TITLE
BUG: No pg_hba.conf entry for host

### ISSUE THREAD

**Issue by tiagocasemiro** [beekeeper-studio/beekeeper-studio#725]
**No pg_hba.conf entry for host**
I create a connection, but when try connect. The beekeeper display this message.  *No pg_hba.conf entry for host*
Iam use dbeaver and this connection work normally

**To Reproduce**
Create some connection on postges

**Screenshots / Gifs**
![image](https://user-images.githubusercontent.com/6023901/125645010-c17487e6-3f66-45fc-90b2-d63181a8fba8.png)

**Version Information (please complete the following information):**
 - OS: Zorin OS 15.3 and Pop OS 18.04
 - About Beekeeper Studio 1.12.0

**Comment by rathboma** [comment]
@tiagocasemiro Thanks for filing an issue!

This looks to be an issue with the configuration of the server, not the client.

Looking into this the pg_hba.conf file is on the server, and controls user access, so it looks like there's a rule that prevents your IP from accessing that particular database.
- https://www.postgresql.org/docs/9.1/auth-pg-hba-conf.html
- Here's how to update the file if you want to allow connections from everywhere - https://dba.stackexchange.com/questions/83984/connect-to-postgresql-server-fatal-no-pg-hba-conf-entry-for-host


Alternatively - If your pg_hba.conf allows access from `localhost` you could try using the SSH tunnel to ssh to the host and then access the database using `localhost`, or another server that is approved for access
