### ISSUE TITLE
FEAT: Add SQLTools to Beekeeper Studio?

### ISSUE THREAD

**Issue by gnat** [beekeeper-studio/beekeeper-studio#728]
**Is your feature request related to a problem? Please describe.**
Would like SQLTools (https://sqltools.beekeeperstudio.io/) to be more immediately accessible.

**Describe the solution you'd like**
In the short term would be nice to just add a link to the SQLTools to the menu in the App. Keep it super simple.

Perhaps just a new menu to the important ones like:
* Tools
  * Formatter
  * Table Builder

Thanks!

**Comment by rathboma** [comment]
Hey! We're currently integrating the table builder, and you can format queries by right-clicking in the editor cell (we definitely need to make this more accessible).

Everything on that site will end up in Beekeeper Studio, and many counter examples too :-)
