### ISSUE TITLE
BUG: Tooltips reversed for "Saved Queries" and "Run History" buttons.

### ISSUE THREAD

**Issue by khorn** [beekeeper-studio/beekeeper-studio#733]
**Description**
The button with a star icon, that displays saved queries when pressed, has a tooltip reading "Run History".
The button with a clock-like icon, that displays the history of queries that have been run when pressed, has a tooltip reading "Saved Queries".

**To Reproduce**
1. Hover over either button with mouse pointer.

**Expected behavior**
The star button should have a tooltip reading "Saved Queries".
The clock button should have a tooltip reading "Run History".

**Screenshots / Gifs**
Unable to get screenshot, as using modifier keys causes tooltip to disappear.

**Version Information (please complete the following information):**
 - OS: Pop! OS, Linux (Ubuntu derived)
 - App Version: 1.12.0

**Comment by rathboma** [comment]
Khorn! Yes! You are right. We have fixed this but not yet released it :-D
