### ISSUE TITLE
BUG: Intermittently freezes on Big Sur M1 Mac

### ISSUE THREAD

**Issue by MattGson** [beekeeper-studio/beekeeper-studio#735]
**Describe the bug**

Beekeeper intermittently freezes during usage on my M1 Mac running Big Sur.
This normally happens when searching for a table. Note, the UI is still somewhat responsive (hover effects) but clicking any button does nothing. I see this a couple of times every hour and have to restart the app.

**Comment by rathboma** [comment]
Huh. This is weird.
Some questions:

1. Does it lock up all of a sudden, or slow down over time?
2. Does it exclusively happen when filtering the table list?
3. Can you record a gif / screen video of it happening?

If you need a screen capture tool look at Kap - https://github.com/wulkano/Kap

**Comment by MattGson** [comment]
1. It locks up all of a sudden. Working fine then not working. Sometimes it's the first search after opening the app. Sometimes it works 20 times before locking up.
2. This is the only place I have noticed it so far
3. 

https://user-images.githubusercontent.com/20088009/127070059-104ccaeb-f052-454f-b677-f21f77262db0.mov

**Comment by MattGson** [comment]
Also, just for reference for future issues, OSX has quicktime player with a screen-recorder built-in.

**Comment by geovannimp** [comment]
I have the same problem with search on ubuntu.

It happens only in one of my databases.

This is the error at developer tools:

```
vue.runtime.esm.js:1897 TypeError: Cannot read property 'key' of undefined
    at Di (vue.runtime.esm.js:5861)
    at T (vue.runtime.esm.js:6263)
    at R (vue.runtime.esm.js:6363)
    at T (vue.runtime.esm.js:6237)
    at R (vue.runtime.esm.js:6363)
    at T (vue.runtime.esm.js:6237)
    at R (vue.runtime.esm.js:6363)
    at a.__patch__ (vue.runtime.esm.js:6526)
    at a.e._update (vue.runtime.esm.js:3963)
    at a.r (vue.runtime.esm.js:4081)
```

**Comment by geovannimp** [comment]
The problem can be related with having tables/functions/etc. with same name in different schemas. But this is totally a guess.

**Comment by rathboma** [comment]
Interesting. Thanks for the theory, gives me something to test.

**Comment by MattGson** [comment]
> The problem can be related with having tables/functions/etc. with same name in different schemas. But this is totally a guess.

At the risk of creating a red-herring, I think you may be on to something.

-  the database I have seen this on DOES have multiple schemas with the same names for tables.
- It didn't start happening until a month or so ago which roughly coincides with this schema name duplications being added. 

I have setup a database without any name duplication so will see if it still happens at all.

**Comment by rathboma** [comment]
I have found a couple of issues. One is related to what you are saying, the other is a event listener memory leak. I'll get them both fixed for the next release. Thanks!

**Comment by rathboma** [comment]
This should be fixed in the next release. If not, please reopen the ticket.
