### ISSUE TITLE
QUESTION: Windows: custom install location

### ISSUE THREAD

**Issue by Arteneko** [beekeeper-studio/beekeeper-studio#737]
**Details:**

Usually, when we install something on Windows, we can choose where to install it and whether or not we want certain files (e.g. start menu launchers).

The current system doesn't allow for any customization, and I would guess it installs everything in the user's data folders (APPDATA).

**Comment by rathboma** [comment]
Hey! Wanted to respond to this - I do plan to make the installer more customizable, but it's not a priority for now.

I'm going to close the issue for now as I just can't imagine prioritizing this in the near future.
