### ISSUE TITLE
FEAT: Make read-only tables more obvious

### ISSUE THREAD

**Issue by rathboma** [beekeeper-studio/beekeeper-studio#745]
It's not super clear that a table is read-only.

See: https://github.com/beekeeper-studio/beekeeper-studio/issues/743

We should add another way that we indicate a table is read-only because it does not have a primary key, either as a tooltip, something in the tab header, or a more prominent warning in the statusbar.

**Comment by RocksteadyTC** [comment]
Good looking out, thanks!

**Comment by rathboma** [comment]
done in the next release.

**Comment by RocksteadyTC** [comment]
Awesome! Thanks @rathboma you guy's really make a good app.
