### ISSUE TITLE
FEAT: Find/replace in the query editor

### ISSUE THREAD

**Issue by skoshy** [beekeeper-studio/beekeeper-studio#747]
**Is your feature request related to a problem? Please describe.**
I want to be able to find/replace in the query editor

**Describe the solution you'd like**
Pressing Ctrl/Cmd+F should show a find dialog with optional replacing. Right now it makes the app fullscreen. It'd be nice if it could even support regex like VSCode.

**Comment by rathboma** [comment]
Yes, for sure.

**Comment by wmontgomery** [comment]
PR available here https://github.com/beekeeper-studio/beekeeper-studio/pull/1464
