### ISSUE TITLE
BUG: 10k tables crashes client (Redshift + SSL)

### ISSUE THREAD

**Issue by ADataGMan** [beekeeper-studio/beekeeper-studio#748]
**Describe the bug**
I installed 1.13.2 on Windows 10, connected it to my Redshift database over mandatory SSL and, and the side bar said it was loading all 10k+ tables and crashed.

**To Reproduce**
A fresh install of 1.13.2 on Windows 10 and connect to a cluster that has 10,000+ objects spread across 100+ schemas and consumes a petabyte of storage.

**Expected behavior**
The interface to not crash and become unusable just after initial connection

**Screenshots / Gifs**

**Version Information (please complete the following information):**
 - OS: Windows 10  Build 19042
 - App Version 1.13.2

**Additional context**
Fresh install and other SQL clients do not have an issue connecting. I also believe they don't index anything until you open a particular schema.

**Comment by rathboma** [comment]
Hmm, yes 10k tables will do it as we load all columns for all tables up front.

That's a good test case though, thanks for reporting, we'll definitely get that type of stuff smoothed out.

**Comment by ADataGMan** [comment]
If it provides any useful guidance, some of those Redshift tables are 1500~ columns wide and that's after we've pruned the data set that produced them. I could easily see them reaching 3000~ if not more.

**Comment by rathboma** [comment]
Yeah the scale of the tables + columns is definitely what is making it fall over. It's a current design limitation of the text editor that it needs the list of tables/columns up-front. If we change that we can make the table view smarter too.

Thank you so much for opening a ticket. I hate issues like this being out in the wild.
