### ISSUE TITLE
BUG: Alter column in the editor

### ISSUE THREAD

**Issue by gnovaro** [beekeeper-studio/beekeeper-studio#749]
**Describe the bug**
I trying to edit column size for a tinyint column, from 3 to 1

**To Reproduce**
1. Go to 'Entitites -> select a table
2. Right Click on 'View structure''

**Expected behavior**
Change the column size without errors

**Screenshots / Gifs**
![imagen](https://user-images.githubusercontent.com/270990/127655123-85f3c3bd-b805-404a-b4e0-cab624c702f4.png)

**Version Information (please complete the following information):**
 - OS:  Ubuntu
 - App Version: Latest
 - DB: MariaDB

**Additional context**
If i copy the SQL generated by Beekeper: 

```SQL
ALTER TABLE
  `website`
ALTER COLUMN
  `status` TYPE tinyint(1) unsigned;
```

phpMyAdmin generated:
```SQL
ALTER TABLE `website` CHANGE `status` `status` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1'; 
```

**Comment by rathboma** [comment]
Hey!
Yes you are right, that needs to be updated. This is using incorrect syntax.

Matthew

**Comment by rathboma** [comment]
This is fixed in the next release :-).
