### ISSUE TITLE
FEAT: Rename tabs (without save them) and quick navigation

### ISSUE THREAD

**Issue by chsjr1996** [beekeeper-studio/beekeeper-studio#753]
**Problem**
Sometimes I has a lot of tabs opened with different queries but the tab title cannot be change and I need open tab by tab to find some query.

**Solution**
Allow change tab title without save query, and if tab is from a saved query then rename title will be change saved query name.

**Additional**
Maybe add a navigation popup like VSCode (CTRL+P) to jump to the tabs using filtering by name?

**Comment by Zerotask** [comment]
You can save a query and then you can give it a name.
You find your saved queries on the left hand side, the star icon.

**Comment by chsjr1996** [comment]
@Zerotask thanks for the sugestion!

But currently I can't change tab names without save query. The main idea here is add a feature to rename tabs without save the query.

**Comment by rathboma** [comment]
Quick search is launching in the next release!

We don't have any plans to enable tab renaming outside of query saving I'm afraid. I'm hoping quick search will alleviate some of the problems (although it does require that you save your queries).

I'm going to close the issue -- I still care about the problem, but I think we can mitigate it in other ways.

Matthew
