### ISSUE TITLE
BUG: Export table as SQL does not quote values for JSON field types

### ISSUE THREAD

**Issue by dylanlt** [beekeeper-studio/beekeeper-studio#755]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

1. Have a table with a JSON column and at least one row of data 
2. Just to make these steps easier, avoid having unique constraints
2. Expand entities and right-click on the table
3. Choose 'Export'
4. In the following screen, choose 'SQL' as the format
5. Click the run button
6. Open the exported SQL and copy-paste into a query tab in Beekeeper
7. Notice that the JSON is not in quotes
8. Click the run button
9. Notice the error: **syntax error at or near "{"**

**Expected behaviour**
The data is inserted successfully and no error is shown.

**Version Information (please complete the following information):**
 - OS: Mac Big Sur 11.5.1
 - App Version 1.13.2

**Comment by rathboma** [comment]
Thanks for the bug. I'll get on this fix.

**Comment by rathboma** [comment]
fixed in the next release.
