### ISSUE TITLE
BUG: Text fiels are rendered as `html`

### ISSUE THREAD

**Issue by isgj** [beekeeper-studio/beekeeper-studio#758]
**Describe the bug**

When I query the DB the text columns that have `html` on them are rendered messing the UI and making it hard to see the raw data.

**To Reproduce**

1. Save `<em>as</em><srcipt>alert(1)</script>` to a text field on your DB
2. Query for this row

**Expected behavior**

The text field should show `<em>as</em><srcipt>alert(1)</script>`

**Screenshots / Gifs**

I![image](https://user-images.githubusercontent.com/20517048/128715296-02e7c800-c1b2-4fee-92d5-036f23a2c05b.png)

**Version Information (please complete the following information):**
 - OS: `Ubuntu`
 - App Version `1.13.2`

**Additional context**
XSS from DB :man_shrugging: :smile:

**Comment by rathboma** [comment]
Hey! Bad html is sanitized, but you are correct it should be displaying as plain text. I will fix this!

**Comment by rathboma** [comment]
fixed in next release.
