### ISSUE TITLE
FEAT: Better support for CockroachCloud clusters

### ISSUE THREAD

**Issue by ianjevans** [beekeeper-studio/beekeeper-studio#760]
**Is your feature request related to a problem? Please describe.**
A couple rough-edges in Beekeeper Studio have come up when trying to use it with CockroachCloud free-tier, which is a multi-tenant serverless cluster that requires you to set your cluster-name when connecting either through an `options` parameter in the connection URL or alternately specifying the tenant cluster name in the database name using `cluster-name.database`.

1. Connection string Import from URL doesn't work with CockroachCloud free-tier. When testing the connection, you get a "codeParamsRoutingFailed: missing cluster name in connection string" error. Basically, it doesn't parse any options within the db URL. E.g. `postgresql://ian:<ENTER-PASSWORD>@free-tier.gcp-us-central1.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full&sslrootcert=$HOME/.postgresql/root.crt&options=--cluster%3Dunique-insect-1893`
2. Importing CockroachDB URLs for either local or CockroachCloud clusters sets the Connection Type to Postgres.
3. Manually entering the connection parameters does work for CockroachCloud, but you need to use the alternate `cluster-name.database` pattern for the database name. But unfortunately, this causes weirdness in the Sidebar Entities. You can see the other database names in the drop down, but if you switch to a different database the Entities are not refreshed. E.g. if you create a new `test` database with a statement and refresh the connection, you see `test` in the drop down, but selecting it doesn't refresh the Entities within that database, and there's no way to see the schemas & tables in test in the Sidebar.

**Describe the solution you'd like**
Ideally, there'd be an option in the Connection dialog for CockroachDB to specify that this is a CockroachCloud connection and set the cluster-name. The issue with multi-tenant database clusters is that the hostname is shared across tenants. So e.g. the host name of `free-tier.gcp-use-central1.cockroachlabs.cloud` isn't sufficient to specify the actual cluster. You need add an `options=--cluster={cluster-name}` URL parameter (best) or you set the database name to `cluster-name.database`.

If you use the database name `cluster-name.database`, the Sidebar needs to be able to prefix the cluster name to the database when retrieving the database entities when switching databases so it retrieves the database entities for that database.

**Describe alternatives you've considered**
A workaround is to create different connections for each database in a multi-tenant cluster, setting the database name to `cluster-name.database`. But that takes away the ability to work across databases within a single connection, and still leads to the incorrect Sidebar entities behavior if you try to switch databases during a session.

**Additional context**
Create a free serverless cluster here: https://cockroachlabs.cloud/ to test this.

Cockroach Labs will be offering paid multi-tenant serverless CockroachDB clusters on CockroachCloud soon, and it's likely other databases will be moving to multi-tenant databases and encounter some of the same issues.

**Comment by rathboma** [comment]
Hmm, yes that is a problem. We definitely want to fix this. Thanks for bringing it up!

**Comment by sadeqush** [comment]
Any solutions to this?

**Comment by vickywane** [comment]
This is also an issue when trying to connect to a free cluster from pgAdmin 4. 😔

**Comment by AditechGH** [comment]
Any solutions to this?

**Comment by MattGoodwin0** [comment]
Estimated timescales on this?

**Comment by namgk** [comment]
any work around?

**Comment by DalenW** [comment]
Bumping this, would like to see this added

**Comment by rmcfadzean** [comment]
Work-around for CockroachLab Cloud cluster:

Set the database name to `your-cluster-id.databasename`. Eg: If your cluster is `large-mouse-1234` and your DB name is `defaultdb` it would be `large-mouse-1234.defaultdb`.

It probably works for others too but I haven't tested.

**Comment by rathboma** [comment]
Thanks for that! I'll add that to the docs

**Comment by ianjevans** [comment]
It's only a partial workaround. Changing databases doesn't work, as the prefix is only done for initial routing. E.g. in the database drop-down, you will see the other databases, but if you try to connect to a different database it will error out, as the new database doesn't have the routing ID prefix.

**Comment by RobbieLD** [comment]
I've tried the `cluster_name.database_name` property and I can't even start the server. It fails with the following stack strace. 

TypeError: Cannot read properties of null (reading '1')
    at Client_PG._parseVersion (C:\Code\robdavis.dev\cms.robdavis.dev\node_modules\knex\lib\dialects\postgres\index.js:135:56)
    at Query.<anonymous> (C:\Code\robdavis.dev\cms.robdavis.dev\node_modules\knex\lib\dialects\postgres\index.js:129:22)
    at Query.handleReadyForQuery (C:\Code\robdavis.dev\cms.robdavis.dev\node_modules\pg\lib\query.js:138:12)
    at Client._handleReadyForQuery (C:\Code\robdavis.dev\cms.robdavis.dev\node_modules\pg\lib\client.js:290:19)
    at Connection.emit (node:events:527:28)
    at Connection.emit (node:domain:475:12)
    at C:\Code\robdavis.dev\cms.robdavis.dev\node_modules\pg\lib\connection.js:114:12
    at Parser.parse (C:\Code\robdavis.dev\cms.robdavis.dev\node_modules\pg-protocol\dist\parser.js:40:17)
    at TLSSocket.<anonymous> (C:\Code\robdavis.dev\cms.robdavis.dev\node_modules\pg-protocol\dist\index.js:11:42)
    at TLSSocket.emit (node:events:527:28)
    at TLSSocket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)

**Comment by rathboma** [comment]
I'm fixing it properly on Monday :-)

**Comment by arturs706** [comment]
Any solution ?

**Comment by rathboma** [comment]
This is live!
