### ISSUE TITLE
FEAT: Hideable columns

### ISSUE THREAD

**Issue by grawtar** [beekeeper-studio/beekeeper-studio#764]
Currently when viewing a large table I manually resize each column to minimum in order to see relevant information.
While this is doable with SQL statements (SELECT ...) that disables editing values directly from the table view.

Being able to hide irrelevant columns would be really useful when manually editing some data in a table.

**Comment by rathboma** [comment]
Yes! We definitely want to do this.

Would like both:
- hide a column
- reorder columns

This should be persisted across sessions.

This certainly isn't a priority item for us right now, but if someone could hook up the Tabulator callbacks (http://tabulator.info), I could add the persistence layer pretty easily.

**Comment by EmasXP** [comment]
This is a related issue: https://github.com/beekeeper-studio/beekeeper-studio/issues/358

**Comment by azmy60** [comment]
Closing in favor of #358
