### ISSUE TITLE
BUG: Interface shows index columns reversed (PostgreSQL)

### ISSUE THREAD

**Issue by crbelaus** [beekeeper-studio/beekeeper-studio#767]
**Describe the bug**
When viewing an index covering multiple columns, the interface shows the columns in the reverse order:

**To Reproduce**
Inspect a table having an index that covers multiple columns using `psql` directly:

```
\d time_attendance_one_time_schedules_projects
                                   Table "public.time_attendance_one_time_schedules_projects"
        Column        |  Type  | Collation | Nullable |                                 Default
----------------------+--------+-----------+----------+-------------------------------------------------------------------------
 id                   | bigint |           | not null | nextval('time_attendance_one_time_schedules_projects_id_seq'::regclass)
 project_id           | bigint |           | not null |
 one_time_schedule_id | bigint |           | not null |
 company_id           | bigint |           | not null |
Indexes:
    "time_attendance_one_time_schedules_projects_pkey" PRIMARY KEY, btree (id)
    "time_attendance_one_time_schedules_projects_one_time_schedule_i" UNIQUE, btree (one_time_schedule_id, project_id)
Foreign-key constraints:
    "time_attendance_one_time_schedules_projects_company_id_fkey" FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE
    "time_attendance_one_time_schedules_projects_one_time_schedule_i" FOREIGN KEY (one_time_schedule_id) REFERENCES time_attendance_one_time_schedules(id) ON DELETE CASCADE
    "time_attendance_one_time_schedules_projects_project_id_fkey" FOREIGN KEY (project_id) REFERENCES projects(id)

hcmex_dev=#
```

As you can see, the index has the columns: **one_time_schedule_id** and **project_id**.

If we inspect the same table using the Beekeper interface we got the columns backwards: **project_id** and then **one_time_schedule_id**.

![image](https://user-images.githubusercontent.com/2965623/129871347-40ad6f1c-28b4-4cf8-a17b-c40b31114eed.png)

For an extra reference, DBeaver also shows the columns in the proper order:

![image](https://user-images.githubusercontent.com/2965623/129872328-5e295c02-75c8-4f78-b33d-fa4ca09f4196.png)

**Expected behavior**
I expect that Beekeper shows the index columns in the proper order since it is important to know when the database will use that index.

**Version Information (please complete the following information):**
 - OS: Mac OS 11.5.2
 - App Version: 1.13.2

**Comment by rathboma** [comment]
Good find, thanks! Let me make sure this is fixed before the next release.

**Comment by crbelaus** [comment]
Thanks @rathboma! 🙇
