### ISSUE TITLE
Portable version ?

### ISSUE THREAD

**Issue by jimmy123j** [beekeeper-studio/beekeeper-studio#77]
Can support the portable version ? Thanks !!

**Comment by rathboma** [comment]
Not sure how possible this is with Electron, but I'll look into it. Are you on Windows?

**Comment by rathboma** [comment]
@jimmy123j can you download this build - https://github.com/beekeeper-studio/beekeeper-studio/suites/663475268/artifacts/5872764

and see if the *-portable.exe works?

**Comment by jimmy123j** [comment]
@rathboma thanks for ur help sir, portable.exe can be ran on win 10
but the server at my company, so i'll try it on monday and feedback to u
if'u have time, might u can release the new ver. including portable ver.
cause many company has PIP rule, we can't install App at company
Thanks again, sir !!

**Comment by rathboma** [comment]
Yay! I'll be doing a new release next week with a bunch of bug fixes, so I'll roll the portable release into that.
This was a surprisingly easy ticket.

**Comment by rathboma** [comment]
@jimmy123j let me know on monday if everything is working on windows server and if so, I'll mark as complete and merge the change.

**Comment by mbinette** [comment]
The link you provided worked for me as far as not needing to be installed. But a "portable" app, I believe, also should not be saving data to the user's home directory. On Windows this is Users\<username>\AppData\Roaming\beekeeper-studio. I think it should be storing all that data in a folder within the same directory as the portable exe. That allows it to be copied to a flashdrive for instance and taken with you, including connection information and saved queries.

**Comment by jimmy123j** [comment]
It's work at my company server, Thanks sir !!

**Comment by mbinette** [comment]
It's closed but not really a portable app at this point. Please see me previous comment about the location of the files.

**Comment by rathboma** [comment]
@mbinette sorry I didn't see your comment. Lets open a new ticket for that, it's definitely a good point, but requires a bit more work than this one line fix to implement
