### ISSUE TITLE
BUG: HTML in fields is rendered

### ISSUE THREAD

**Issue by evs-xsarus** [beekeeper-studio/beekeeper-studio#770]
**Describe the bug**
HTML contents in field are rendered instead of shown raw.

**To Reproduce**
1. Create a table with a text field
2. Put valid HTML in it.
3. Load the table in Beekeeper
4. See rendered HTML

**Expected behavior**
The raw HMTL must be shown

**Screenshots / Gifs**
![image](https://user-images.githubusercontent.com/44158071/129903907-750d3e5e-7f44-4a70-b1dd-ef3e335c74c2.png)

**Version Information (please complete the following information):**
 - OS: Ubuntu
 - App Version: 1.13.2
 - 
**Additional context**
n/a

**Comment by rathboma** [comment]
Yes! This is fixed in the next release, coming early next week
