### ISSUE TITLE
BUG: Inconsistent empty query parameter value

### ISSUE THREAD

**Issue by anicolas-richard** [beekeeper-studio/beekeeper-studio#771]
**Describe the bug**
Query Parameters values can be empty in the popup.
When run, the query, Beekeeper Studio will act in two different ways when rewriting the query with user set parameters.
This can lead to false returned sets.

**To Reproduce**
1. Create a new query
2. Copy this query : " SELECT ':param_value' FROM DUAL "
3. Click Run Button
4. Leave empty input box for :param_value and click 'Run' button of the popup
5. Returnset value is undefined.

6. Click again Run Button
7. This time, start typing something in the input box, then delete its content and click 'Run' button of the popup
8. This time, Returnset value is (EMPTY).

**Expected behavior**
Ideally, returning in both cases null (EMPTY) would be great and consistent.

**Version Information (please complete the following information):**
 - OS: Windows
 - App Version : 1.13.2

**Comment by rathboma** [comment]
Yes, there are some quirks with params right now. We'll be tidying them up in a future release!
