### ISSUE TITLE
FEAT: Backup a whole database for Postgres to start

### ISSUE THREAD

**Issue by Zerotask** [beekeeper-studio/beekeeper-studio#778]
**Is your feature request related to a problem? Please describe.**
During development it can be useful to save a complete database before executing tasks.

**Describe the solution you'd like**
A simple option to export / dump the whole database. Currently there is just an option to export a single table inside a database.

**Comment by rathboma** [comment]
Yes! I agree 100%.

We'll get there. It is on our minds, as is `import` for a whole database.

**Comment by sanjay1688** [comment]
Looking for it we are able to export or import the whole database.

Also if possible have some multiple options - 
- import/export with multiple formats raw(SQL), Tar
- import/export only data / schema / all

Thanks!

@rathboma @Zerotask

**Comment by bennettblack** [comment]
This feature would be super handy! I do this pretty frequently with Table Plus - and it's really the only reason I use Table Plus anymore. Everything else I do with Beekeeper.

**Comment by joeke** [comment]
+1 for this!

**Comment by AdsonCicilioti** [comment]
+1

**Comment by mfakhrys** [comment]
Hello, Is there any update on this?

**Comment by ToshY** [comment]
@Zerotask Could you give a status update or some information on when this feature could possibly be implemented?

**Comment by hotrungnhan** [comment]
+1 up.

**Comment by davedgd** [comment]
From a teaching perspective, this is one piece of functionality that would be really desirable (the other being .sql exports of query files). Relying on alternatives like `mysqldump` (for MySQL/mariadb) via the shell is a reasonable workaround, but it would be great to have support for full exports via the GUI.

+1

**Comment by crucifyer** [comment]
![image](https://user-images.githubusercontent.com/1300668/196914247-4cf7733e-6e41-4882-8805-fafee2c96d5f.png)
Like the db tool in jetbrains ide, it would be good if copy paste, export, and import were done in the table view.
It is very convenient to copy and paste only the desired parts from different dbs with the select statement.

**Comment by marco7249** [comment]
it's really helpful if Beekeeper can  export / dump the whole database !
 Is there any update on this ?

**Comment by haveamission** [comment]
Also would love if there was a way to export/dump a database. I want to make a backup before making some changes to a local database, and instead I have to go to CLI SQL to do it rather than just from the UI, which is more time consuming

**Comment by squpshift** [comment]
Really surprised this hasn't been added. Could this please be prioritised ahead of any more magic features no one asked for.

**Comment by rathboma** [comment]
FYI - working on this soon.

@squpshift we have limited resources, and I work on this project for free, so sometimes we have to prioritize working on stuff that is enjoyable so we don't burn out.

**Comment by squpshift** [comment]
@rathboma awesome, thanks for the update. Totally respect that you're keeping it enjoyable for yourself!

**Comment by rathboma** [comment]
Notes for implementing this:

- research how other tools do it, and copy them.

**Comment by ToshY** [comment]
@not-night-but Why has this ticket been closed? I cannot seem to find a PR that implements this change, making me believe it hasn't been implemented yet. Please state a reason or mention the corresponding PR.

@rathboma  Why has the title been changed to just "Postgres"? Does this mean that other database types like MySQL/MariaDB will not be included in this feature?

**Comment by not-night-but** [comment]
@ToshY hi! This issue was closed automatically when the PR was merged in our private ultimate repository, it just hasn't been included in a release yet.

In terms of the title change, it was changed to "Postgres to start" as that is what a good portion of the community uses and we wanted to lessen the scope so we could get everything working properly before adding more databases, but more databases are in the works.

**Comment by not-night-but** [comment]
Soon™
