### ISSUE TITLE
FEAT: Ability to add relationships like foreign keys and ability to delete a table

### ISSUE THREAD

**Issue by azamsharp** [beekeeper-studio/beekeeper-studio#779]
Please add 

Ability to add relationships like foreign keys and ability to delete a table

**Comment by rathboma** [comment]
Foreign keys coming in the next release! Yes no delete table yet, but that's a pretty easy one in SQL

**Comment by rathboma** [comment]
FK adding is live. No table deletion, for now I think it's ok for that to be a manual action in the query window.
