### ISSUE TITLE
FEAT: show number of affected rows after UPDATE / DELETE (maybe INSERT too?)

### ISSUE THREAD

**Issue by mariusa** [beekeeper-studio/beekeeper-studio#783]
**Is your feature request related to a problem? Please describe.**
When deleting rows from `psql` shell, it shows number of deleted rows, eg
`DELETE 70219`

Beekeeper shows `Success. No results`

**Describe the solution you'd like**
show number of affected rows after UPDATE / DELETE (maybe INSERT too?)

**Comment by rathboma** [comment]
I believe it should show affected rows on the footer?

**Comment by Zerotask** [comment]
> I believe it should show affected rows on the footer?

Yep.
I just tried it with a SELECT statement. The middle one is affected rows.

![image](https://user-images.githubusercontent.com/20150243/131364313-db678199-5b18-494d-8bef-95c47cafc799.png)

**Comment by mariusa** [comment]
You're right, I see that now, after 18 months of working with Beekeeper :)

Could that be put also in the main message? Instead of "No results", say "X affected rows".
