### ISSUE TITLE
BUG: Structure footer scrolls, but should stay at bottom of the screen

### ISSUE THREAD

**Issue by Zerotask** [beekeeper-studio/beekeeper-studio#787]
**Is your feature request related to a problem? Please describe.**
If you opened the structure view (context menu -> View Structure), there is no text link or button to show the data for this table.
You have to right click / double click on the table in the `Entities` section.

**Describe the solution you'd like**
A simple button or text link `View Data` at the top

**Additional context**
![image](https://user-images.githubusercontent.com/20150243/131368625-3f323888-4e80-4a79-a753-212eea6eebec.png)

**Comment by rathboma** [comment]
Bah! This is a bug! There's a button in the footer which is not supposed to scroll :facepalm:

**Comment by rathboma** [comment]
this is fixed
