### ISSUE TITLE
FEAT: move table partitions to the "structure" view, under a sub-tab "partitions"

### ISSUE THREAD

**Issue by flexdeviser** [beekeeper-studio/beekeeper-studio#788]
I got a lot of partition tables, I really do not want to see them in the tree view.

Can you guys hide them under the origin table and would be better to create a folder "partitions"

<img width="332" alt="Screen Shot 2021-09-03 at 2 59 45 pm" src="https://user-images.githubusercontent.com/3424332/131953293-43ab7b20-390f-41aa-9b4f-7f5916d6ae10.png">

**Comment by rathboma** [comment]
Yep, agreed. We want to add a 'partitions' section to the table structure view. I'll rename this ticket to match
