### ISSUE TITLE
BUG: Color highlight sql query dark mode

### ISSUE THREAD

**Issue by venantiusgalih** [beekeeper-studio/beekeeper-studio#790]
**Describe the bug**
Love your new update on 2.0.0 version. I would like to ask, maybe you can add some tweak in the dark theme, so we can see clearly the highlighted syntax that we select. Because currently, as you can see in the attachment image, I can't see it clearly the highlighted syntax (SELECT * FROM commodity) and can't differentiate that it is highlighted or not.

![image](https://user-images.githubusercontent.com/20768516/132081943-b11fb164-b885-4f0a-a10c-35cac5868420.png)

**To Reproduce**
1. Connect to any databases
2. Write the query
3. Select few word/phrase

**Expected behavior**
A clear color for highlighted syntax in dark theme. Such as blue or white with transparency.

**Version Information (please complete the following information):**
 - OS: Windows 10
 - App Version: 2.0.0

Thank you

**Comment by rathboma** [comment]
ok, yeah probably need a tweak.

**Comment by jhult** [comment]
Definitely needs tweaking.

Using 2.1.4 on macOS
