### ISSUE TITLE
BUG: Not able to view table structure

### ISSUE THREAD

**Issue by hareendranmg** [beekeeper-studio/beekeeper-studio#793]
**Describe the bug**
Not able to view table structure on Postgres databases

**To Reproduce**
1. Right-click any table
2. Click on view structure
3. Showing an error **'column i.indnkeyatts does not exist'**

**Screenshots / Gifs**
![image](https://user-images.githubusercontent.com/19310197/132623312-b88c0177-55a5-4e48-8e89-021443a87208.png)

**Version Information**
 - OS: Ubuntu 20.04
 - App Version: 2.0.0 (Installed via snap)

**Additional context**
It was working on the previous version

**Comment by rathboma** [comment]
Interesting. What version of Postgres are you running? I think this is missing in versions < 11?

**Comment by GammaGames** [comment]
Same issue! I found it in the db running 9.5

**Comment by hareendranmg** [comment]
> Interesting. What version of Postgres are you running? I think this is missing in versions < 11?

PostgreSQL 9.5.24 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609, 64-bit
