### ISSUE TITLE
BUG: Tabs are no closed with Control + W shortcut

### ISSUE THREAD

**Issue by txigreman** [beekeeper-studio/beekeeper-studio#794]
**Describe the bug**
Tabs are no closed with control + w shortcut in windows portable versión

**To Reproduce**
1. Open new tab
2. Press Control + W

**Expected behavior**
The current tab is closed

**Version Information (please complete the following information):**
 - OS: Windows 10
 - App Version: 2.0 portable

**Comment by rathboma** [comment]
Yes! I've fixed this in my upcoming pr. Sorry for this. #789
