### ISSUE TITLE
BUG: Say something here

### ISSUE THREAD

**Issue by OnionChild** [beekeeper-studio/beekeeper-studio#796]
**Describe the bug**
Queries with CTEs (aka `with` clause) do not return any results.  This occurs for any table or database I try.

**To Reproduce**
For example, suppose we connect to Beekeeper's Database

Running this query returns results, as expected
```
select * 
from used_connection
```

Running this query returns no result.  The bottom pane of the screen is empty, showing recommended hotkeys.  The bottom right corner still says says "No Data"
```
with x as (
    select * 
	from used_connection
)
select * 
from x
```

**Expected behavior**
The two queries should return the same results.

**Screenshots / Gifs**

This is what it looks like on my screen.  Both images show the results after the query is run ("Run" is clicked, or Ctrl+Enter)

Here is the basic successful query
![Screen Shot 2021-09-14 at 3 12 00 PM](https://user-images.githubusercontent.com/7296860/133340796-49c4da51-98f5-4fcd-b08c-52df52178f32.png)

Here is the no-result CTE query
![Screen Shot 2021-09-14 at 3 12 16 PM](https://user-images.githubusercontent.com/7296860/133340823-444e5a13-e44b-40b9-87db-196617055810.png)

**Version Information (please complete the following information):**
 - OS: macOS Big Sur v11.6
 - App Version 2.1.1

**Comment by rathboma** [comment]
Good find!
Try with an uppercase `WITH` as a workaround.

This is a bug in our sql query identifier. I'm fixing that here - https://github.com/sqlectron/sql-query-identifier/pull/42

temporarily upper casing that word will fix it. Sorry about that.

**Comment by OnionChild** [comment]
That worked!  Thanks.

```
WITH x AS (
    select * 
	from used_connection
)
select * 
from x
```
