### ISSUE TITLE
FEAT: Order saved connections

### ISSUE THREAD

**Issue by rhuangabrielsantos** [beekeeper-studio/beekeeper-studio#798]
Today it is not possible to sort the saved connections, and as you add more connections it starts to become a mess.

**Comment by Zerotask** [comment]
I created a similar feature request with #799 which will also improve the organization of saved connections.

**Comment by rhuangabrielsantos** [comment]
nice!

**Comment by rathboma** [comment]
Yes, sorting is implemented! Soon we'll have folders too :-)
