### ISSUE TITLE
BUG: Query parameter placeholders only got replaced once

### ISSUE THREAD

**Issue by imTigger** [beekeeper-studio/beekeeper-studio#800]
**Describe the bug**
Query Parameters, same placeholder only got replaced once.
Therefore `SELECT id FROM orders WHERE a = :test OR b = :test` fails with syntax error.

**To Reproduce**
1. Create an MySQL connection or similar
2. Run query: `SELECT ':test', ':test', ':test';`
3. Enter 123 as `test` parameter
4. Output: `'123', ':test', ':test'`

**Expected behavior**

Expected output: `'123', '123', '123'`

**Version Information (please complete the following information):**
 - OS: Ubuntu 21.04
 - App Version: 2.1.1 (AppImage x64)

**Additional context**
Placeholder `$1` and `:test` have the same issue.

Maybe a duplicate of #529 but more specific to the problem.

**Comment by rathboma** [comment]
This will be fixed in an upcoming release as our query parser now supports params. Coming soon :tm:
