### ISSUE TITLE
FEAT: Keyboard shortcut to moderate table

### ISSUE THREAD

**Issue by TheMarkWill** [beekeeper-studio/beekeeper-studio#803]
**Is your feature request related to a problem? Please describe.**
To make the tool use faster, sometimes we could have some shortcuts active without having to resort to the mouse, such as applying changes, adding a new row, reloading selected table data.

**Describe the solution you'd like**
Create shortcuts to at least the following features.

- Apply Table Changes - `Ctrt+s`
- Reload table -  `F5` or  `Ctrt+r`
- Focus filter imput to data of table- `Ctrl+f`
- Add new blank row in table  - `Ctrt+Alt+n` or another, this one I had doubts
- Browse table pagination -  `Ctrt+Alt+RightArrow` and  `Ctrt+Alt+LeftArrow` 

**Additional context**
I'm not very familiar with the project, but I can study anything and implement these editions.

**Comment by rathboma** [comment]
Yes! We'll be reworking keyboard shortcuts in Q1.

#197 << this is me tagging this issue for when we build setting screens.
