### ISSUE TITLE
QUESTION: How do I increase the amount of memory beekeeper uses (cache_size in sqlite)

### ISSUE THREAD

**Issue by OnionChild** [beekeeper-studio/beekeeper-studio#806]
**Details:**
I'm using a large SQLite DB and I want to improve read speed by increasing the amount fo memory beekeeper uses.  Normally I would do something like `PRAGMA cache_size=64000`.  When I try to set cache_size in beekeeper, it seems to automatically reset to `cache_size=16000`

```
PRAGMA cache_size; --returns 16000
PRAGMA cache_size=64000;
PRAGMA cache_size; --still returns 16000
```

**Version Information [might be relevant to your issue]**
Operating System: MacOS 11.6
App Version [help -> about]: 2.1

**Comment by OnionChild** [comment]
Based on this issue, it seems like the answer is "Not possible yet"

https://github.com/beekeeper-studio/beekeeper-studio/issues/603

**Comment by rathboma** [comment]
Yes unfortunately you are correct. We definitely want to support this use case though.
