### ISSUE TITLE
QUESTION: Building fails because FPM cannot be downloaded

### ISSUE THREAD

**Issue by EbonJaeger** [beekeeper-studio/beekeeper-studio#807]
**Details:**
Is FPM required to build beekeeper-studio, and is there a way to build without it? I don't need a .deb, snap or AppImage to be built. If it's possible to not do those steps, it could also significantly speed up my building process.

FPM can't be downloaded because from wherever the build tool is trying to get it from returns 403 forbidden:

```
⨯ cannot resolve https://github.com/electron-userland/electron-builder-binaries/releases/download/fpm-1.9.3-2.3.1-linux-x86_64/fpm-1.9.3-2.3.1-linux-x86_64.7z: status code 403
```

Hopefully this will go away on its own, but until then....

Thanks!

**Version Information [might be relevant to your issue]**
Operating System: Linux (Solus 4.3 Fortitude)
App Version [help -> about]: 2.1.3

**Comment by EbonJaeger** [comment]
The FPM issue seems to be resolved, but it would still be nice to know if beekeeper-studio can be built without doing the deb, snap and appimage steps. :)

**Comment by rathboma** [comment]
Hey! What command are you using to build? If you don't build a deb, you don't need FPM. For example:

`yarn electron:build --linux AppImage` will only build an app image, not a DEB.

You can also tell it to use a 'local' FPM, by setting this environment variable: `USE_SYSTEM_FPM=true`. It won't download FPM then, but look for it on the system path.

If you only need to run in development `yarn electron:serve` does not need it either.

Hope that helps!

Closing this issue, as there's nothing to really fix.

**Comment by EbonJaeger** [comment]
Hello! I am currently using `yarn bks:build` to build it. Trying `yarn electron:build --linux` still builds all three, so I'm guessing it needs at least *a* target.

My usecase here is packaging beekeeper-studio for Solus, which uses Eopkg. To do that, all the Electron dist stuff is put into the appropriate directory after the build step, and all is fine. I was just hoping to be able to avoid building artifacts that we don't need to build.

Thanks!

**Comment by rathboma** [comment]
Yes you have to specify `--linux AppImage` to just build the app image or `--linux snap` to only build the snap

**Comment by EbonJaeger** [comment]
Gotcha. Thank you very much!

**Comment by EbonJaeger** [comment]
As a note to anyone else who might find this, bulding with `yarn electron:build --linux dir` works to avoid building any of the three other targets, should you for some reason need that. :)

**Comment by rathboma** [comment]
Great! Glad that worked.

Can I ask what the use case is for a custom version? Am I missing some sort of package that would be useful?

**Comment by EbonJaeger** [comment]
It's just nice to have in the repo for people who for some reason don't like using Snaps or AppImages I suppose. Given that the eopkg tooling is pretty specific to Solus, I don't think I would say to bother worrying about providing it as a package format. As long as it's buildable and redistributable, that's all that really matters.
