### ISSUE TITLE
BUG: Dropping index on a table not adding table name to the query

### ISSUE THREAD

**Issue by FusionPwN** [beekeeper-studio/beekeeper-studio#811]
**Describe the bug**
I'm using MariaDB.
Dropping index on a table is not adding table name to the query, when trying to apply the change it returns a query error on the UI, after this happened I stopped being able to edit the queries after using the "Copy to SQL" option in "Apply", butI was not able to replicate this behaviour.

**To Reproduce**
1. Add a new index to a table
2. Commit the change
3. Remove the index

**Screenshots / Gifs**
![Beekeeper_Studio_9SE8IVxfd3](https://user-images.githubusercontent.com/16710456/134164946-091b2013-c448-4035-b936-237835861cc1.png)

![Beekeeper_Studio_8KG2cLlOWG](https://user-images.githubusercontent.com/16710456/134164983-c2e09e87-39a5-43c4-98a0-4c6f3baa92f9.png)

**Version Information:**
 - Windows 10
 - App Version 2.1.3

P.S.
I'm very excited to see this project move forward been waiting for so long for a Sequel PRO style DBMS for Windows and this looks very promising, keep up the great work guys

**Comment by rathboma** [comment]
Thank you for the bug report! This is tremendously helpful. We'll get this fixed!

Yes, :heart: Sequel Pro. I wanted the same thing but for Linux + Postgres, that's why I'm here!
