### ISSUE TITLE
BUG: MySQL: Unique indexes not properly identified. Also Export column names are incorrect

### ISSUE THREAD

**Issue by FusionPwN** [beekeeper-studio/beekeeper-studio#812]
**Describe the bug**
Hey again, there is still a visual bug on the mysql/mariadb index UI, although it seems to be just visual. Also the query export and query formatting adds whitespaces between the "`" this triggers errors as the table or field names are searched including the whitespaces.

**Expected behavior**
Should see the tick on the UNIQUE KEY

**Screenshots / Gifs**
While adding:
![Beekeeper_Studio_ijeyqQbPnf](https://user-images.githubusercontent.com/16710456/134242386-9c38e96a-87f6-4696-9a14-2e26823f6baa.png)

After Commit:
![Beekeeper_Studio_9XcjSKPorZ](https://user-images.githubusercontent.com/16710456/134242434-635fd37a-0728-418b-9bb3-2114c0aa3030.png)

Table create export:
![Beekeeper_Studio_Pp3dcDX7jU](https://user-images.githubusercontent.com/16710456/134242474-21d491f0-afb6-4f4d-9331-c31fc42cba07.png)

**Version Information (please complete the following information):**
 - Windows 10
 - 2.1.4

**Comment by rathboma** [comment]
interesting, yes both of these are bugs.

Looks like you're using MySQL? Can I ask which version?

**Comment by FusionPwN** [comment]
> interesting, yes both of these are bugs.
> 
> Looks like you're using MySQL? Can I ask which version?

I'm using MariaDB 10.4.13 at the moment
