### ISSUE TITLE
FEAT: Link to documentation from HELP menu

### ISSUE THREAD

**Issue by igponce** [beekeeper-studio/beekeeper-studio#813]
**Is your feature request related to a problem? Please describe.**

I cannot open the documentation for Beekeeper studio from the help menu.
I have to google for the documentation instead.

Currently the help menu has these items:
- About Beekeeper Studio
- Add Beekeeper's database
- Show developer tools

**Describe the solution you'd like**

- Include a new item `Beekeper Studio Documentation` that opens https://docs.beekeeperstudio.io/guide/

**Describe alternatives you've considered**

- Other options: add a link to the homepage in the "about" section (not worth it).
- Opening https://docs.beekeeperstudio.io is not the best option: You need one more click to get to actual documentation.

**Comment by igponce** [comment]
this should be an easy fix - trying it to do it myself ;-)

**Comment by rathboma** [comment]
@igponce Thanks so much! Sorry our app menu code is such a mess right now.
