### ISSUE TITLE
FEAT: Dropping a Table from the sidebar context menu

### ISSUE THREAD

**Issue by UdittLamba** [beekeeper-studio/beekeeper-studio#826]
**Details:**
I may be missing something here but I was looking for a way to right-click on a table and delete it from the database. Like datagrip but either it does not exist or I am unable to find it.

**Version Information [might be relevant to your issue]**
Operating System: Manjaro Linux 
App Version [help -> about]: 2.1.1

**Screenshot / GIF [if appropriate]**:
none

**Comment by mcanepa** [comment]
I need this option too!
