### ISSUE TITLE
FEAT: Clear Text Authentication for MySQL

### ISSUE THREAD

**Issue by BrysonRafael** [beekeeper-studio/beekeeper-studio#832]
**Is your feature request related to a problem? Please describe.**
The database I am trying to connect to requires MySQL's [clear text pluggable authentication](https://dev.mysql.com/doc/refman/8.0/en/cleartext-pluggable-authentication.html) and I cannot connect to it using Beekeeper Studio.

**Describe the solution you'd like**
Beekeeper Studio allows me to authenticate with a MySQL database that requires clear text authentication. I believe I would need to install the clear text plugin somehow in Beekeeper. Perhaps an extension option that is similar to VSCode's that allows me to easily install plugins?
![image](https://user-images.githubusercontent.com/19216177/136063325-2a3e243a-bc68-4ba3-aba0-26e2254c991c.png)

**Describe alternatives you've considered**
I'm currently using DBeaver to connect to the database that I need to, but I don't like the interface and it feels too heavy for what I use it for.

**Additional context**
Here is an example of the SSL config that I have in DBeaver for my issue:
![image](https://user-images.githubusercontent.com/19216177/136063026-2a685b20-be62-4f4c-89a0-b82bc6f08538.png)
I'm not doing anything fancy in the connection config except for using SSL.

Thanks for building this project and keeping it open source! I'm loving the look and feel of it, I just wish I could use it for all of my database connections 🥲

**Comment by ethan-dowler** [comment]
@rathboma Well, I guess I got a bit mixed up. I did mean Postgres, but I guess the cleartext plugin is not what fixed my issue haha. @BrysonRafael will be back in the office tomorrow. He can follow up on this.

**Comment by rathboma** [comment]
Ok, I clearly need more testing of the auth plugin. I'll try my best to fix this on Monday.

Do you know the SQL I need to set up a user to require this auth plugin?

**Comment by BrysonRafael** [comment]
@MasterOdin that's exactly how I'm trying to connect. Sorry @rathboma, I probably should have mentioned this to begin with 🤦🏻‍♂️
