### ISSUE TITLE
BUG: can't delete row with `binary` IDs in MySQL

### ISSUE THREAD

**Issue by Zerotask** [beekeeper-studio/beekeeper-studio#839]
**Describe the bug**
I tried deleting a row of a table. I right-clicked it, clicked on delete row and then on the apply button. Nothing happend

**To Reproduce**
1. install [Shopware](https://www.shopware.com/) locally
1. Open a random table
2. Try to delete a row

**Expected behavior**
I expect that the row is deleted after clicking on apply.

**Screenshots / Gifs**

**Version Information (please complete the following information):**
 - OS: Windows 10
 - App Version: 2.1.4

**Additional context**
Shopware is using `binary` for their IDs and I assume that this is the problem.
I tried it with a similar software, which showed the SQL statement it will run and there I saw something like  `... WHERE id = NULL;`.
Therefore the binary is probably the problem.

Adminer and MySQL Workbench are able to delete rows with binary IDs.

**Comment by Zerotask** [comment]
Yes, it's MySQL, but I assume the bug exists in MariaDB too. Those two DBs are supported by the mentioned Shopware.

**Comment by azmy60** [comment]
Hey @rathboma, I'm reviewing this issue. Hope I can fix it by the end of the week.
