### ISSUE TITLE
FEAT: Be able to create databases

### ISSUE THREAD

**Issue by MordechaiHadad** [beekeeper-studio/beekeeper-studio#840]
**Is your feature request related to a problem? Please describe.**
It can be sometimes annoying to go into command line to create new database

**Describe the solution you'd like**
Be able not to just connect to database but also create it.

**Describe alternatives you've considered**
Well using the command line lol

**Comment by rathboma** [comment]
Yes! We definitely need this, just haven't gotten around to it yet :-).

Once we've finished our next big feature push we'll work on issues like this.

**Comment by MordechaiHadad** [comment]
> 
> 
> Yes! We definitely need this, just haven't gotten around to it yet :-).
> 
> Once we've finished our next big feature push we'll work on issues like this.

Awesome! thank you :)

**Comment by rathboma** [comment]
Initial pr that never merged #265

**Comment by wmontgomery** [comment]
PR Submitted: https://github.com/beekeeper-studio/beekeeper-studio/pull/1365

**Comment by wmontgomery** [comment]
Mysql with charsets and collations 
![mysql](https://user-images.githubusercontent.com/314613/189465514-ebb9bcc1-a174-4c92-b1fc-a3283ef0e11a.gif)

Postgres with just the charset (no collations)
![postgres](https://user-images.githubusercontent.com/314613/189465594-3e6d148a-888f-40e1-bc2a-89d3e9650fb7.gif)

**Comment by MordechaiHadad** [comment]
LET'S GO BABY
