### ISSUE TITLE
BUG: Please respect sslmode=require when importing Postgres from URI

### ISSUE THREAD

**Issue by danielbprice** [beekeeper-studio/beekeeper-studio#849]
**Describe the bug**

When you attempt to import a postgres connection from a URI, Beekeeper doesn't respect the sslmode parameter.
Here is an example URI:

postgres://example@example.com/postgres?sslmode=require

**To Reproduce**
1. Import from URI: postgres://example@example.com/postgres?sslmode=require
2. Observe that imported connection does not enable SSL.

**Expected behavior**
Configure/Connect with SSL enabled.

**Version Information (please complete the following information):**
 - OS: MacOS
 - App Version: 2.1.4

**Comment by rathboma** [comment]
Yes, very good point. Agreed this is a bug.

**Comment by rathboma** [comment]
fixed in master
