### ISSUE TITLE
dropdown in the menu bar show blank text and if selected, the apps freeze

### ISSUE THREAD

**Issue by ezmemoar** [beekeeper-studio/beekeeper-studio#859]
**Describe the bug**
When i click one of the menu in the menu bar, or tried to select the connection type, the dropdown shows a list of blank text menu. If one of then is clicked, the app got freeze. Anything I miss when installing the app? or is it a bug?

**Screenshots / Gifs**
No Screenshot provided because I can't capture the dropdown menu

**Version Information (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS
 - App Version 2.1.4

**Comment by rathboma** [comment]
Are you using the Snap version on an AMD GPU? This is a bug with snaps unfortunately.

I'd recommend using the DEB or AppImage version as a workaround.
