### ISSUE TITLE
FEAT: Add an option to select system default theme

### ISSUE THREAD

**Issue by ShivamJoker** [beekeeper-studio/beekeeper-studio#860]
**Is your feature request related to a problem? Please describe.**
If someone is using dynamic theme with their OS (eg MacOS) the theme stays light in day and turns dark in night the app should have the option to sync with the system theme.

**Describe the solution you'd like**
We can have a 3rd option (use system colors) in menu where it says to pick light and dark and it would take the default system color scheme.

Here is the API - https://github.com/electron/electron/blob/main/docs/api/system-preferences.md
I can try creating a PR if someone can guide me a bit on where we are setting the color schemes.

**Comment by rathboma** [comment]
I agree! We simply haven't done this yet due to time constraints.

To get this to work:

1. Listen for the callback / on startup - update the user setting for theme. We have a `UserSetting` model, there's one entry in the database for theme

**Comment by ShivamJoker** [comment]
@rathboma you'll have to guide me more I am not able to understand where should I put the event listener

**Comment by rathboma** [comment]
This is also ready in the next release!
