### ISSUE TITLE
BUG: Can't create rows in a table that has a bit(1) column

### ISSUE THREAD

**Issue by Davidson-Mike** [beekeeper-studio/beekeeper-studio#861]
**Describe the bug**
If your table has a bit(1) column then Beekeeper Studio will fail to create a new row in the list when you press the "+" button. This is due to an error.

**To Reproduce**
1. Create a table with a bit(1) column
2. Try to press the "+" to add a new row
3. Notice that it does nothing

**Expected behavior**
Create a new row to be filled in

**Screenshots / Gifs**
Here's your error.
![image](https://user-images.githubusercontent.com/66186881/140180480-6af452b8-1b36-41c5-aeef-766767aedcad.png)

**Version Information (please complete the following information):**
 - OS: Windows
 - App Version 2.1.5

**Additional context**
Cloning an existing row is a good workaround. From taking a very brief look at your sourcecode the issue appears to be when rendering the bit(1) cell
![image](https://user-images.githubusercontent.com/66186881/140180898-da53be74-26ac-4dc9-b964-b430d3592f69.png)

**Comment by rathboma** [comment]
Very interesting.

What database type (and version) are you using?

**Comment by Davidson-Mike** [comment]
> Very interesting.
> 
> What database type (and version) are you using?

Thank you for your response.

It is a MySQL Community v8.0.17 database. Not that it should matter, but for the sake of completion, it is deployed via AWS RDS.
