### ISSUE TITLE
Is there a way to copy connections to new PC? 

### ISSUE THREAD

**Issue by hunter-jeremy** [beekeeper-studio/beekeeper-studio#863]
**Details:**
I've copied my portable version of beekeeper to my new PC but my connections aren't there. Is there a way to copy over the connections I set up on my old PC? 

**Version Information [might be relevant to your issue]**
Operating System: Windows 10 -> 11
App Version [help -> about]: N/A

**Comment by rathboma** [comment]
Hey! Right now the best way to do it is to to copy the app config directory to your new machine. The only items you need are `app.db`, and the `secret.key` files.

Files should be here: `%USERPROFILE%\AppData\Roaming\beekeeper-studio`
