### ISSUE TITLE
BUG: Format Query button is not working in new update. 

### ISSUE THREAD

**Issue by Christopher-Law** [beekeeper-studio/beekeeper-studio#865]
The "Format Query" button is no longer working with the latest update.  

1. Enter a valid query in the editor.
2. Right Click in the editor
3. Click "Format Query"

**Expected behavior**
The Query should be formatted. 

**Version Information (please complete the following information):**
 - M1 Macbook Pro
 
<img width="508" alt="Screen Shot 2021-11-04 at 6 05 49 PM" src="https://user-images.githubusercontent.com/25482861/140426908-ecc6c79e-4d01-4daa-9f01-891f7814c6b8.png">

**Comment by lhleonardo** [comment]
Complementing the report presented by @Christopher-Law.

I opened the devtools console and got the following error:

![image](https://user-images.githubusercontent.com/11544276/140556367-f12ca407-1641-48d0-8484-d28589464c20.png)

In this case I'm using the app to access a SQLServer database.

**Comment by rathboma** [comment]
Aha! That's a problem in our dialect mapping. Thank you for finding it. Should be an easy fix.

**Comment by natemwilson** [comment]
I'm seeing the same issue. Can't format a query. Connected to a PostgreSQL db.
<img width="555" alt="Screen Shot 2021-12-27 at 11 09 47 AM" src="https://user-images.githubusercontent.com/10066574/147493019-21343195-6605-4db4-a6fe-3756b51e690b.png">
