### ISSUE TITLE
BUG: Format Query not working

### ISSUE THREAD

**Issue by bonniecaruso** [beekeeper-studio/beekeeper-studio#867]
**Describe the bug**
Selecting Format Query does not modify the query.  

**To Reproduce**
1. Write quick query
2. Highlight query
3. Right-click and select Format Query

**Expected behavior**
Query should format but nothing happens and the button is still visible

**Screenshots / Gifs**

**Version Information (please complete the following information):**
 - OS: Mac
 - App Version 2.1.5 (2.1.5)

**Additional context**

**Comment by UtechtDustin** [comment]
I guess this is a duplicate of #865

**Comment by bonniecaruso** [comment]
Yes it is, thank you.  Wasn't sure how to look for existing issues.
