### ISSUE TITLE
CockroachDB support

### ISSUE THREAD

**Issue by jordanlewis** [beekeeper-studio/beekeeper-studio#87]
Hi,

Thanks for the great tool! I think it would be very easy to add CockroachDB support to Beekeeper Studio: we'd just need a copy of the PostgreSQL driver that has a different default port (26257). Cheers and thanks again!

**Comment by rathboma** [comment]
Thanks!

For anyone interested in a contribution, I think this is fairly straightforward and would require slight changes in:
clients/index.js (key name to driver)
config.js (default port)
ConnectionInterface.vue - adding to the UI

That might be it? You could draft of the `mariadb` implementation (it's the same, but with the mysql driver)

**Comment by colesam** [comment]
I'd like to try and take care of this issue this weekend unless someone wants to take care of it sooner.

**Comment by jordanlewis** [comment]
Looks like this got closed by #111. Thanks @rathboma and @rafiss!
