### ISSUE TITLE
SQL Queries fail when run against localstack RDS instance in Docker container

### ISSUE THREAD

**Issue by holyoaks** [beekeeper-studio/beekeeper-studio#870]
**Describe the bug**
Query always returns `Query Executed Successfully. No Results. 0 rows affected`.

**To Reproduce**
1. Create a localstack RDS database in a Docker container
2. Create multiple schema inside that RDS instance
3. Create any table (my example has one column)
4. Insert a row into the table
5. Query the table by:

```
set search_path to <schema>;
select * from <table_name>;
```

**Expected behavior**
The query should return the row, _especially_ as if you right-click on the table and select `View Data`, the data is actually returned.

**Screenshots / Gifs**

![Screen Shot 2021-11-08 at 11 59 07 AM](https://user-images.githubusercontent.com/5797525/140794063-e649c724-b196-4b68-984e-50683da91dcb.png)

![Screen Shot 2021-11-08 at 12 00 02 PM](https://user-images.githubusercontent.com/5797525/140794033-a48e7af8-9359-4146-be18-54ff486adc91.png)

![Screen Shot 2021-11-08 at 11 59 40 AM](https://user-images.githubusercontent.com/5797525/140794054-a537a097-3770-47aa-b13c-db68e10f1c43.png)

**Version Information (please complete the following information):**
 - OS: Mac 12.0.1
 - App Version 2.1.5

**Comment by holyoaks** [comment]
Actually, this may simply be lack of clarity on how the queries are run. I chose `Run Current` and the query actually ran. But having to set the `search_path`, run it, then `Run Current` to get the query to run is confusing and not obvious. Thanks, regardless. I'm really liking Beekeeper.

**Comment by rathboma** [comment]
Ah yes! It runs all of them by default -- see a dropdown appears in the footer if you ran more than one query to allow you to select the right resultset.

Agreed it's a little unclear. Hopefully this helps others find this dropdown in future too.

I think probably we should only show 'results' for queries that return a result.
