### ISSUE TITLE
FEAT: Will  you please make the line numbers more readable?

### ISSUE THREAD

**Issue by HarrisonHemstreet** [beekeeper-studio/beekeeper-studio#872]
The line numbers are way too dark. Will you please increase their visibility? Super difficult to read.

**Comment by rathboma** [comment]
You on the dark theme? Yes we'll be tidying that stuff up as we go. I'm going to close this issue, because style issues are tracked elsewhere, but I definitely hear you and we'll be adding better contrast soon!
