### ISSUE TITLE
BUG: Sometime cannot type anywhere and must reopen app

### ISSUE THREAD

**Issue by mojtabakaviani** [beekeeper-studio/beekeeper-studio#875]
Sometime cannot type in query tab, table data and structure and must reopen app to solve problem.

**Comment by rathboma** [comment]
Very interesting.

Can you give me more information about your environment?

Some questions off the top of my head: 
Has the app been open for a while? What platform are you on? Do you have a lot of tabs open? Do you have a lot of tables?

Any sort of gif or video would be very helpful.

You're the first person to report this, so hoping it's some unique set of circumstances, but that also means it's really hard for me to replicate it without a big brain dump of information from you. :-)

**Comment by sensnerd** [comment]
Hi @rathboma, I'm also having this issues. Here are some details that may be help

How to reproduces: 
- Open multiple new tab or table (try to open 10 tab)
- write query on the new tab
- Close all tab
- open a new tab

Environtments:
- Windows 10 pro v1909 8GB RAM
- Beekeeper-studio 2.1.5
- More than 10 table

This issues is gone after I switch to other apps and switch back to Beekeeper or just close and reopen Beekeper.

![Screenshot (317)_LI](https://user-images.githubusercontent.com/47457477/142797503-a2a5e882-e892-41ea-bcd3-e0220080c71a.jpg)

**Comment by rathboma** [comment]
Wonderful directions thanks! I will try to replicate this week

**Comment by mefjak** [comment]
I have a simmilar issue - but it only takes one tab and modal window :)

You cant see it but when new tab is opened I can't type - there is no cursor.

OS: Windows 10
Ver: BS 3.0,1
![bs](https://user-images.githubusercontent.com/22888465/149753129-38a14781-5e6c-4fa9-b039-4e54efc18bae.gif)
1

**Comment by rathboma** [comment]
Are there any errors in the dev console? [help -> show developer console]

Are you using the portable or installer version?

I guess I have to fire up Windows to test this, seems like a platform specific bug.

**Comment by mefjak** [comment]
only this
![image](https://user-images.githubusercontent.com/22888465/149885406-dd80a0c8-bee2-400a-8f76-b3938df18c52.png)

**Comment by luizfelipevbll** [comment]
I have a very similar problem on the latest Beekeeper version in MacOS M1 Ventura 13.4

**Comment by rathboma** [comment]
I don't think this is still an issue, at least I can't replicate it. Please let me know if I'm incorrect.

**Comment by ailac22** [comment]
Yes, it's still happnening: Open a postgresql connection -> disconnect -> Try to fill form to open a new connection -> cannot write.
