### ISSUE TITLE
Use single quote in query tab

### ISSUE THREAD

**Issue by Marco-prog** [beekeeper-studio/beekeeper-studio#877]
**Details:**

I have the following DataTable:

|Name|Surname| 
|---|---|
|Frank|Ali'| 
|John| Man'o| 
|July|Guerrera| 

I need to write a query to retrieve all records whose surname contains a single quote character ' :
|Name|Surname| 
|---|---|
|Frank|Ali'| 
|John| Man'o| 

I tried these queries, but most of them fail to correctly interpret my requirements:

select * from table where table.surname like "%'%"  --> seems unable to correctly process double quoted strings
Query's outcome: no such column called %'%

select * from table  where table.surname like '%\'%'
Query's outcome: unrecognised token '''''

<img width="210" alt="image" src="https://user-images.githubusercontent.com/59891747/141692668-e2172767-0ff1-4a5f-b9f8-121d3d8160d5.png">

**Version Information [might be relevant to your issue]**
Operating System: macOS Monterey 12.0.1
App Version [help -> about]: 2.1.5

**Beekeeper Studio**
**2.1.5**

**Screenshot / GIF [if appropriate]**:
A screenshot of the app if that helps
<img width="1206" alt="Screenshot 2021-11-14 at 10 04 03" src="https://user-images.githubusercontent.com/59891747/141674627-b58acea2-c68f-4b02-8504-e5eae9466dc1.png">

**Comment by Marco-prog** [comment]
I was able to correctly retrieve required data by concatenating two single quotes:

select * from table  where table.surname like '%'''

I don't know if that's the intended behaviour or a bug, in the former case feel free to mark the issue as closed

**Comment by rathboma** [comment]
Hey! Yes this is a 'feature' of SQL.

Two ways to do it is to double up the single quotes (like you figured out, although this is NOT intuitive, so good job), or to backslash escape the single quote: `'\''`
