### ISSUE TITLE
QUESTION: Is Native M1 Supported in the new Release/Upcoming releases?

### ISSUE THREAD

**Issue by notshriram** [beekeeper-studio/beekeeper-studio#878]
**Details:**
Since Beekeeper is now running on electron 12.1.0, does it support M1 natively? if not, is it planned for a future release?

**Version Information [might be relevant to your issue]**
Operating System: macOS 12.0.1 Monterey

**Comment by rathboma** [comment]
It does not yet. I'm right now limited by build hardware. We run on Github actions, so I don't yet have a way to build for M1 macs.

Once that's released (maybe it is already?), we should be good to go.

**Comment by rathboma** [comment]
Yeah, not supported yet - https://github.com/actions/virtual-environments/issues/2187

The only other way would be for someone to buy us an M1 Mac Mini to use as a build server, I don't really have much of a budget yet for equipment, so can't give you an ETA, but hopefully some point in Q1 2022.

**Comment by rathboma** [comment]
Going to close this question, but it's still in my mind and I'd like to deal with it somehow.

**Comment by sholladay** [comment]
Hi, @rathboma. I'd like to donate an M1 Mac Mini to the project. You can contact me via https://seth-holladay.com/contact and we can set it up.
