### ISSUE TITLE
FEAT: Can you please add a One-time sponsorship tier?

### ISSUE THREAD

**Issue by notshriram** [beekeeper-studio/beekeeper-studio#880]
**Is your feature request related to a problem? Please describe.**
I really like the project and want to donate to it. However, I find recurring payments at a fixed amount a bit frustrating [...]

**Describe the solution you'd like**
I would suggest a one-time sponsorship tier with a custom amount option.

**Describe alternatives you've considered**
Sponsoring monthly and then cancelling the sponsorship after a one time payment but it is only possible to donate $5 or $10 like that at a time.

**Comment by rathboma** [comment]
Hey! Thanks so much for wanting to be a sponsor.

I don't think GitHub really allows us to do this, but I'll look into it. Thanks for the suggestion!

I'm going to close the ticket as it's not really an issue with the app, but I'll not forget it.
