### ISSUE TITLE
QUESTION: Is there a way to build it for Web?

### ISSUE THREAD

**Issue by chl3188** [beekeeper-studio/beekeeper-studio#881]
**Details:**
Hello
I want to build a beekeeper-studio on web and upload it to the web server.
Is there an option for build?
If not, which part should I modify to do it?
thanks

**Comment by jenspots** [comment]
I'd also love to do that! I'm guessing if all Electron, Node, etc. code gets wrapped in [`NativeWrapper.ts`](https://github.com/beekeeper-studio/beekeeper-studio/blob/5eaab7b665162d63bdfb726cc6cc8f715ec097d8/apps/studio/src/lib/NativeWrapper.ts) it would be doable?

**Comment by rathboma** [comment]
Not yet!

The UI could be separated, but it would take time. It's really all squished in as a desktop app right now, there would be a lot to change.

If I can get to a place where I'm more than just part time on the app I will be able to work on this. First step to that is building a sustainable revenue source in a way that doesn't ruin the app.

I'm going to close this issue as it's not something I can really fix right now, but hoping in 2022 I can provide something like this :-)

**Comment by binaryfire** [comment]
I realise this is a closed issue but just wanted to add my support for this! A lot of people are using browser-based IDEs now (thanks to VSCode). It'd be awesome if we could do the same with Beekeeper.
