### ISSUE TITLE
FEAT: IN operator

### ISSUE THREAD

**Issue by gmcrocetti** [beekeeper-studio/beekeeper-studio#884]
Hi all. Congrats for the amazing software :)

### Is your feature request related to a problem? Please describe.

It would be amazing to have the `IN` operator available in this drop-down list:
![Screenshot_20211118_152729](https://user-images.githubusercontent.com/24530683/142475332-dc362d7e-9e85-431a-ae0f-060f3b632d2b.png)

---

### Describe the solution you'd like

Have the `IN` operator available as a option.

---
### Describe alternatives you've considered

Write a raw query by myself.

---

**Comment by rathboma** [comment]
Right now the best way to do this is to click the `<>` button and write a clause in SQL. I realize that's not perfect, but it is the easiest.

I think this would be a good beginner ticket for someone actually.

**Comment by udhaykumarbala** [comment]
Hey, I am interested in working on this issue. can you please help me get started on the final requirement

I think "tableview/TableTable.vue" is the file, that i have to change for this issue

**Comment by devcydo** [comment]
Hi! I saw some comments on the PR, can I help on this?

**Comment by gmcrocetti** [comment]
Recently tested and it's working. Thank you for your time ! :)
