### ISSUE TITLE
BUG: Unnecessary commas at the beginning and the end of the array in exported json

### ISSUE THREAD

**Issue by unworthyEnzyme** [beekeeper-studio/beekeeper-studio#887]
**Describe the bug**
I have a table like this:
&nbsp;&nbsp;CREATE TABLE users(
&nbsp;&nbsp;&nbsp;&nbsp;id serial PRIMARY KEY,
&nbsp;&nbsp;&nbsp;&nbsp;email VARCHAR(256) UNIQUE NOT NULL
&nbsp;&nbsp;);
When i export this as json i get this result:
[
,
&nbsp;{"id":1,"email":"helloese@email.com"},
&nbsp;{"id":2,"email":"TESTING@email.com"},
&nbsp;{"id":3,"email":"something@gmail.com"},
]
which you can see there is inappropriate commas.

**To Reproduce**
1. Go to some table's tab
2. Export Whole Table

**Version Information (please complete the following information):**
 - OS: Windows
 - App Version 2.1.5

**Comment by rathboma** [comment]
Hmm that's no good. Thank you very much for the bug report!
