### ISSUE TITLE
BUG: "yarn install" failed with node 16

### ISSUE THREAD

**Issue by lydev** [beekeeper-studio/beekeeper-studio#889]
**Describe the bug**
Running "Yarn install" failed while building node-sass module. Node version is 16.x.

**To Reproduce**
1. git clone.
2. Install node 16.x.
3. yarn install
 

**Expected behavior**
All pkg get installed w/t error.

**Screenshots / Gifs**
The error is the same as this one https://stackoverflow.com/questions/67241196/error-no-template-named-remove-cv-t-in-namespace-std-did-you-mean-remove

**Version Information (please complete the following information):**
 - OS: [Mac 11.2.3]
 - App Version [e.g. help -> About Beekeeper Studio]

**Additional context**
Downgrade Node 16 can workaround this.

**Comment by rathboma** [comment]
Right now the app is built to work with Node 14.x -- that's the version that ships with Electron 12. Definitely I'll have to fix this as the project grows :-)

Going to close for now as this will get fixed 'naturally' as I upgrade things.
