### ISSUE TITLE
SSL - allow users to provide a certificate or CA for SSL connections

### ISSUE THREAD

**Issue by rathboma** [beekeeper-studio/beekeeper-studio#89]
Ideal behavior:

Provide an automatically drop-down for common CAs:
- Amazon RDS
- Azure
- GCP
- Digital Ocean

Allow users to provide CA / Cert+key for other connections

**Comment by rathboma** [comment]
If someone wants to test https://github.com/beekeeper-studio/beekeeper-studio/pull/109 that'd be great. I don't have a db set up with a real certificate yet.

**Comment by Gys** [comment]
Sorry, did not work, I get 'Connection lost: The server closed the connection.' after about 10 seconds.

I tried this (MacOS) for https://github.com/beekeeper-studio/beekeeper-studio/pull/109/checks?check_run_id=667232724

Exactly the same settings work in TablePlus.

**Comment by rathboma** [comment]
Thanks for testing! I'll do some work on this and spin up my own digital ocean instance

**Comment by danilopolani** [comment]
DigitalOcean if I remember only needs the SSL flag to be enabled, without providing any cert file, maybe we should investigate on that direction

**Comment by mholt** [comment]
Most CockroachDB installations also recommend / require TLS certificate authentication.

Once this feature lands I will probably be able to switch to using Beekeeper, looks good!

**Comment by trevorrjohn** [comment]
This can be closed as well @rathboma
