### ISSUE TITLE
BUG: view structure does not work - get 'syntax error at or near "WITH ORDINALITY"'

### ISSUE THREAD

**Issue by sarahcpage** [beekeeper-studio/beekeeper-studio#897]
**Describe the bug**
Selecting View Structure on a table yields 'syntax error at or near "WITH ORDINALITY"'.

**To Reproduce**
Right click on a table name and select View Structure

**Expected behavior**
I expect to see the structure of the table

**Screenshots / Gifs**

**Version Information (please complete the following information):**
 - OS: macOS Monterey version 12.0.1
 - App Version: 2.1.5

**Additional context**
Postgres database

**Comment by rathboma** [comment]
Hey!

Can I ask what version of postgres you are using? I don't have this problem so hoping you can help me debug it.

**Comment by sarahcpage** [comment]
Very old. 
![image](https://user-images.githubusercontent.com/37630771/146576203-3978743d-b977-4d0c-aa4d-f80bf1bb2f38.png)

**Comment by sarahcpage** [comment]
Very cool app by the way.

**Comment by rathboma** [comment]
Oh yeah, might be the age of your install. Let me add it to the integration tests, it's only one sql statement that is broken, but once that statement can be fixed it's all good

**Comment by sarahcpage** [comment]
Thanks so much!
