### ISSUE TITLE
[Enhancement] Auto limit on query

### ISSUE THREAD

**Issue by fritzlorens** [beekeeper-studio/beekeeper-studio#90]
As the title says, having an auto limit would be a nice addition and would help a lot! :)

**Comment by rathboma** [comment]
As in when you write `select * from foo` in the query editor?

**Comment by rathboma** [comment]
I'm not sure that the app should be so opinionated as to modify a user's query before running it. I feel like that sets a bad precedent on what you can trust the tool to do.

While I understand that you might do this by accident (oops, 1mm rows incoming), I think the better solution is to truncate the output as it is streamed from the client (which I do plan to do).

Going to close this issue.

**Comment by gnovaro** [comment]
SQLyog add a LIMIT check and default for 1000 results. By default is checked. Is a good option.

**Comment by lode** [comment]
I want to second this issue. It is annoying to think about this to prevent the app becoming unresponsive and crashing.

I think a default is fine, if it is shown somewhere in the footer status bar and overwritten when adding your own limit. The way it works in MySQL Workbench I think is just fine.

But having a stream could also work for sure. Or any other way that doesn't crash the app or the server.
