### ISSUE TITLE
FEAT: Highlight/select cells from results pane

### ISSUE THREAD

**Issue by kb-ig** [beekeeper-studio/beekeeper-studio#904]
**Is your feature request related to a problem? Please describe.**
I cant seem to find a way to copy multiple rows from a single column in the results pain. For example, if I have a SQL statement that selects column A, B and C, and I want to copy just the values from column A, rows 1-5, there doesnt seem to be any way to do this.

**Describe the solution you'd like**
I'd like to be able to select multiple rows from a single column, even when the results pane contains multiple columns. Perhaps holding a modifier key and selecting could go into "cell selection mode", where you can draw essentially draw a rectangle over the cells to be selected.

**Describe alternatives you've considered**
- Temporarily modify my SQL statement to return only one column - obviously not always feasible
- Copy multiple columns, paste into something like Excel, and select only one column - adds overhead
- Download results to file, open then in something like Excel, select the values that way - a lot of overhead. 
Copy cell values one by one

**Additional context**
Add any other context or screenshots about the feature request here. (we love screenshots with red circles if the request is for something visual)

**Comment by rathboma** [comment]
Yes I agree. It's a pain right now. This is something that needs adding to [Tabulator](http://tabulator.info).

I agree that it should work like an excel spreadsheet - select a range of cells to copy paste, or select rows by the row header to copy/paste, or select column headers to copy/paste.

I'll be working on this in the new year!

**Comment by rathboma** [comment]
Going to tackle this in a tabulator feature: https://github.com/olifolkerd/tabulator/issues/4294

Will be after the 4.0 release, but probably a big 4.x enhancement

**Comment by azmy60** [comment]
Closing this cause we've added the spreadsheet feature #1747 for the next 4.x release!
