### ISSUE TITLE
FEAT: Prompt to save changes/warn user of losing changes when closing app/disconnecting from server

### ISSUE THREAD

**Issue by kb-ig** [beekeeper-studio/beekeeper-studio#905]
**Is your feature request related to a problem? Please describe.**
When closing the app or disconnecting from a server, users are not warned about losing unsaved changes.

**Describe the solution you'd like**
Prompt to save any unsaved files/tabs when closing application or disconnecting from server. Users are prompted to save when a single tab is closed and contains unsaved changed. Ideally users should be prompted to save (or at least warned that any unsaved changes will be lost) when either closing the application (from the upper-right X, or File > Exit, or Alt + F4 etc), or when disconnecting from the server (File > Disconnect).

**Describe alternatives you've considered**
N/A

**Additional context**
Add any other context or screenshots about the feature request here. (we love screenshots with red circles if the request is for something visual)
N/A

**Comment by rathboma** [comment]
The real fix for this is to just persist the open tabs. This is coming soon!

**Comment by rathboma** [comment]
I'm going to close this in favor of persisting the open tabs (like vscode)

**Comment by kb-ig** [comment]
Good call, I agree this would be more suitable.
