### ISSUE TITLE
Can't select SSH-Key-File in hidden folder on MacOS Catalina

### ISSUE THREAD

**Issue by carstenh** [beekeeper-studio/beekeeper-studio#91]
I'm on a mac and if I want to select my SSH-Key-File which is located here `~/.ssh/id_rsa` I can't find any way to select it. The file selection window does not show hidden folders.

**Comment by rathboma** [comment]
I'm assuming you're on Linux and using the Snap?

This is a security problem with Snaps right now. I'm working on a long-term solution. Temporarily you'll have to move the private keys to a non-hidden directory inside your home directory.

**Comment by carstenh** [comment]
Hi, no I'm on a MacBook Pro with OS X Catalina 10.15.4. But the problem seems to be the same.

**Comment by rathboma** [comment]
I think since Catalina they put in more security checks, so yes likely the same. I'll investigate and look into a fix.

**Comment by danilopolani** [comment]
Maybe #92  could solve?

**Comment by carstenh** [comment]
By looking at the changes in https://github.com/beekeeper-studio/beekeeper-studio/pull/92 it looks like it solves the problem.

**Comment by carstenh** [comment]
Thx! Now I can see hidden folders
