### ISSUE TITLE
BUG: When connection is stablished with my Mysqk data base, it appears that theres`s no data inside it. I have used beekeper last week and it was working. Does anyone know how can i solve it? Thanks

### ISSUE THREAD

**Issue by GabrielBeOn** [beekeeper-studio/beekeeper-studio#911]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots / Gifs**
If applicable, add screenshots or GIFS to help explain your problem.

**Version Information (please complete the following information):**
 - OS: [e.g. Windows/Mac/Ubuntu]
 - App Version [e.g. help -> About Beekeeper Studio]

**Additional context**
Anything else you think might be helpful

**Comment by rathboma** [comment]
Hey! Can you provide screenshots at all?

Also:

- What version of mysql are you using?
- Can you confirm that you see the database data in another client? (eg the mysql command line cli)

**Comment by rathboma** [comment]
Hey! Is this still a problem? I need more info to solve this if so!

**Comment by GabrielBeOn** [comment]
Thanks! There’s no problem anymore Enviado do Email para Windows 10 De: Matthew RathboneEnviado:domingo, 16 de janeiro de 2022 23:15Para: beekeeper-studio/beekeeper-studioCc:GabrielBeOn; AuthorAssunto: Re: [beekeeper-studio/beekeeper-studio] BUG: When connection is stablished with my Mysqk data base, it appears that theres`s no data inside it. I have used beekeper last week and it was working. Does anyone know how can i solve it? Thanks (Issue #911) Hey! Is this still a problem? I need more info to solve this if so!—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>
