### ISSUE TITLE
FEAT: Save Previous Window Arrangement 

### ISSUE THREAD

**Issue by GMbrianlaw** [beekeeper-studio/beekeeper-studio#920]
**Is your feature request related to a problem? Please describe.**
Whenever I quit the app and reopen it, the window arrangement resets to the default location.

**Describe the solution you'd like**
A feature like VSCode where the previous arrangement is loaded, or you can set a default arrangement.

**Describe alternatives you've considered**
Manually moving the window every time I open the application.

**Comment by rathboma** [comment]
This is present in 3.x!
