### ISSUE TITLE
QUESTION: How to turn off spell check?

### ISSUE THREAD

**Issue by EdenHell** [beekeeper-studio/beekeeper-studio#926]
**Details:**
When I was editing in the form, a red wavy line appeared. I think this is a spell check of chrome. I did not find a switch to turn off the spell check in the program. If not, I hope to add this option.

**Version Information**
Operating System: Windows 11
App Version: 2.1.5

**Screenshot**:
![image](https://user-images.githubusercontent.com/5779655/147056040-1660bd80-979f-4f29-a9c4-be32d7577b55.png)

**Comment by rathboma** [comment]
This is done!
