### ISSUE TITLE
QUESTION: Deleting multiplew rows in a table.

### ISSUE THREAD

**Issue by UdittLamba** [beekeeper-studio/beekeeper-studio#928]
**Details:**
Is there a way to delete multiple rows from a table? I have looked around but couldn't find any.  
Thanks

**Comment by ojasaklechayt** [comment]
`Delete from <table_name> where <condition>;` 
using this we can delete multiple rows. 
Hope, it helped

**Comment by UdittLamba** [comment]
thanks a lot for replying but i was looking for a GUI option. Like in datagrip.

**Comment by rathboma** [comment]
You can right click each row you want to delete, but if you have a lot that'll take some time.

How would you want this to work? Can you give me some screenshots or a GIF of what you'd want this to look like?

**Comment by nheimann1** [comment]
@rathboma I would expect a standard multiple items selection, like there is in any other GUI.

Example 1 - Basic
- Click on row 2
- Click Shift + row 5
- Rows 2-5 will be marked as selected 
- Right click on one of the selected rows and choose action (delete/clone/etc..)

Example 2 - Advanced
- Select rows 2-5 as in example 1
- Click Ctrl + row 10
- Click Ctrl + Shift + row 12
- Rows 2-5 & 10-12  will be marked as selected
- Right click on one of the selected rows and choose the action


This is how the file explorer works on Windows, same goes with Excel, Google Sheet, and almost any other GUI I can think of.

I hope that helps. 

Screenshot of selected rows of example 2 (was taken from widnows file explorer)

![image](https://user-images.githubusercontent.com/3142081/160011829-111d06d5-515e-4a3b-b2e6-c16d103f6ce5.png)

**Comment by patrick-hurley** [comment]
+1 Just came here to request the same feature. I'd also like the same behaviour as suggested by @nheimann1 whereby you would left-click to select a row, hold shift, and then left-click on the last row you would like to 'multi-select'. Then right-clicking on any of the newly highlighted rows would allow you to perform bulk actions (such as delete), or potentially pressing 'CMD + BACKSPACE' could allow for a bulk delete.

**Comment by zaimazhar** [comment]
I am looking forward to purchase the Professional license and this feature (and table truncate too) has been the only missing piece I need for my daily work...

This might sound like feature imitation from other products, but having user to confirm their action would be more mistake proof;
- Add save confirmation button (CTRL+S or CMD+S) or...
- Add delete history as SQL statements so user can browse through their delete history to retrieve their deleted data

Of course, the latter sounds way too complicated to work on. I'd go for the first option since it is more easier to implement. 👍🏽

**Comment by haveamission** [comment]
Came here to also request this feature - I highly recommend taking a look at Sequel Ace/Sequel Pro - the UI on Sequel Ace is **amazing**.

Only issue is that it is only for MySQL.

A UI like Sequel Ace, for every major SQL type? I would 100% be willing to pay for that.

**Comment by dslotcavage** [comment]
Adding one more request for this feature!  Writing the SQL command works fine, but a GUI version would be faster much of the time.

**Comment by gabrielhaase** [comment]
+1

**Comment by l0rb** [comment]
Is this feature request being worked on? Or is there any plan to put this on the roadmap? Would love to see this.

**Comment by rathboma** [comment]
Update here: I have a WIP PR for this, but I've been waiting on some tabulator library improvements. Those are done, so hopefully this will be coming soon!
