### ISSUE TITLE
Unable to format queries for a postgres database

### ISSUE THREAD

**Issue by Apakottur** [beekeeper-studio/beekeeper-studio#939]
**Describe the bug**
I am unable to format queries for a postgres database.

**To Reproduce**
1. Connect to a postgres database
2. Create a new query and write `SELECT 1;`
3. Right click on the text and click `Format Query`

At this point nothing happens, the button isn't clicked and the query isn't formatted.

**Expected behavior**
The query is formatted, or if something in my configuration is wrong then I'd expect to see an indicative error.

**Screenshots / Gifs**
Here's the output in the developer tools, every click generate another instance of this error:
![beekeper_1](https://user-images.githubusercontent.com/54272821/147616559-78fcd24f-a8be-4783-9844-fd3d05d7130b.png)

**Version Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - App Version: 2.1.5

**Comment by rathboma** [comment]
This is fixed in 3.x
