### ISSUE TITLE
FEAT: Application should remember its size, position, and which monitor it was last displayed on.

### ISSUE THREAD

**Issue by Jieiku** [beekeeper-studio/beekeeper-studio#942]
**Describe the bug**
Beekeeper-studio Always launches at the same size and shape, and always on the same monitor.
I have tried resizing the beekeeper-studio window and putting it on the display that I want, but whenever I launch it again, its back to this same size, shape, and position.

**To Reproduce**
1. launch beekeeper-studio
2. make the window a bit smaller or bigger, and drag it to another position or monitor
3. close beekeeper-studio
4. relaunch beekeeper-studio
5. notice that it did not save your position, size, or shape

**Expected behavior**
I expect it would remember its window settings.

**Screenshots / Gifs**
it always appears this size, shape, and position:

![2021-12-28_18-07](https://user-images.githubusercontent.com/106644/147620791-e61e091f-5acf-4f8b-9ee5-b6b3d0d602c1.png)

**Version Information (please complete the following information):**
 - OS: Ubuntu 21.10 with plasma-desktop DE (kde/kubuntu)
 - Beekeeper Studio 2.1.5 (just installed via deb apt repository)

**Additional context**
Let me know if you need any more information, thank you for a great program, it has instantly become my favorite to use.

**Comment by rathboma** [comment]
Yeah, you're right. This is a pain! Will definitely fix it.

Not sure it's a bug, rather than a new feature, but I'll look into it.

**Comment by davidkaufman** [comment]
👍  I'd like to third it

**Comment by davidkaufman** [comment]
> > 👍  I'd like to third it
> 
> @rathboma assigned @davidkaufman 

See what happens when you open your mouth? 😆
