### ISSUE TITLE
BUG: Cannot save new connection

### ISSUE THREAD

**Issue by fekri1409** [beekeeper-studio/beekeeper-studio#949]
**Describe the bug**
I try to add new database connection and already fill up all required field. But cannot save the connection. It shows the following message : "Empty criteria(s) are not allowed for the update method." and "Could not save connection information".

**To Reproduce**
1. Open 'Beekeeper Studio'
2. Click on ' + New Connection '
3. Fill up the required field
4. Click on 'Save' button
5. See error "Empty criteria(s) are not allowed for the update method."

**Expected behavior**
Expect the connection is saved.
![beekeeper-studio](https://user-images.githubusercontent.com/68042444/148007133-99b63c9a-c3dd-41d4-b5d5-6107886277ce.png)

**Screenshots / Gifs**
If applicable, add screenshots or GIFS to help explain your problem.

**Version Information (please complete the following information):**
 - OS: Ubuntu
 - App Version 3.0.1

**Additional context**
Anything else you think might be helpful

**Comment by Dominiquini** [comment]
This bug happens on Windows x64 too!

App Version: 3.0.1

**Comment by zthh626** [comment]
This happens on macOS 12.0.1 as well.

App Version: 3.0.1

**Comment by rpsu** [comment]
I got this as well but filling up all fields (`Default database` up in the pic in this case) helped. My field was different, though, under SSH Tunnel.

**Comment by rathboma** [comment]
Sorry about this. Taking a look now

**Comment by zthh626** [comment]
I updated to 3.0.3 and when trying to save a new connection, it now has this error:
<img width="616" alt="Screen Shot 2022-01-04 at 10 30 09 AM" src="https://user-images.githubusercontent.com/31324580/148106700-5389d7a6-d9db-4282-a480-72177976e39b.png">

**Comment by dqdev** [comment]
Was experiencing this issue in 3.0.1. Updated to version 3.0.3, and now saving connection shows new error:

"SqliteError: NOT NULL constraint failed: saved_connection.createdAt"

**Comment by Rory-Sullivan** [comment]
I've had the same story as @dqdev above. I am trying to connect to a local MySQL database. Also I noted that after connecting to the database if I click on the connection in the bottom left corner and try to save it that way I get the same error.
