### ISSUE TITLE
BUG: SQLite error on saving new connection

### ISSUE THREAD

**Issue by zthh626** [beekeeper-studio/beekeeper-studio#952]
**Describe the bug**
When saving a new database and all required fields are filled, it shows the message : `SqliteError: NOT NULL constraint failed: saved_connection.createdAt`.

**To Reproduce**

1. Open 'Beekeeper Studio'
2. Click on ' + New Connection '
3. Fill in the required field
4. Click on the 'Save' button
5. See the error "Empty criteria(s) are not allowed for the update method."

**Expected behavior**
The connection is saved.

**Screenshots / Gifs**
<img width="616" alt="Screen Shot 2022-01-04 at 10 30 09 AM" src="https://user-images.githubusercontent.com/31324580/148107406-6e68476a-7ce9-43c3-8c36-9dc689635758.png">

**Version Information (please complete the following information):**
 - OS: macOS 12.0.1
 - App Version: Beekeeper Studio 3.0.3

**Comment by rathboma** [comment]
Hey! Thanks for reporting. I can't replicate this, so hoping you can answer a few questions to help me debug:

- Can you double check that you are on 3.0.3 and not 3.0.1?
- Is there anything in the development console (help -> show dev tools)
- Do you have any other saved connections? Do they save fine?

**Comment by zthh626** [comment]
I deleted app.db and restarted the app and it seems to have fixed it. 
Thanks for getting back so quickly :)
