### ISSUE TITLE
BUG: Cannot save new connection

### ISSUE THREAD

**Issue by EdenHell** [beekeeper-studio/beekeeper-studio#953]
**Describe the bug**
![image](https://user-images.githubusercontent.com/5779655/148147508-b6c14cdf-ffcc-43cb-a260-06c984abd96f.png)

**To Reproduce**

1. Open 'Beekeeper Studio'
2. Click on ' + New Connection '
3. Fill up the required field
4. Click on 'Save' button
5. See error "SqliteError: NOT NULL constraint failed: saved_connection.createdAt"

**Screenshots / Gifs**
![image](https://user-images.githubusercontent.com/5779655/148147508-b6c14cdf-ffcc-43cb-a260-06c984abd96f.png)

**Version Information (please complete the following information):**
 - OS: Windows 11
 - App Version 3.0.3

**Comment by rathboma** [comment]
Hey! I saw someone else with this problem earlier and I cannot replicate it.

Can I ask a few questions:

Is this a new install or an upgrade?
Can you close the app, reopen it and try again?
Do you have other connections that work fine?

**Comment by EdenHell** [comment]
@rathboma 

1. Upgrade.
2. After restarting the app, the connection can be successfully saved.
3. No other saved connections.

**Comment by rathboma** [comment]
Ok super weird.

I'll try to replicate myself with the same setup.

Thanks for checking! Hopefully this unblocks you for now?

**Comment by EdenHell** [comment]
Maybe it has something to do with the fact that I upgraded from 3.0.1 to 3.0.3. Because 3.0.1 was also unable to save connections.
I can now use it normally, you can close this issue.

**Comment by gutenye** [comment]
I had same problem, upgrade. `rm -r ~/Library/Application\ Support/beekeeper-studio` solved it.

**Comment by wouthoekstra** [comment]
I had a similar problem, but the error differed: "Empty criteria(s) are not allowed for the update method."

I was already in the progress of reporting an issue, when I found this one and updated Beekeeper from 3.0.1 to 3.0.7 (on Ubuntu 20.04). This also solved my problems with storing new connections.

**Comment by rathboma** [comment]
I'm going to close this as I haven't had new reports since publishing 3.0.8
