### ISSUE TITLE
FEAT: Disable row count when viewing structure

### ISSUE THREAD

**Issue by jancoow** [beekeeper-studio/beekeeper-studio#954]
When having large, very large, tables, the count(*) really introduce a lot of load on the database. This is very annoying because it happens automatically when clicking on "view structure". Could this be a setting which can be toggled somewhere?

**Comment by rathboma** [comment]
Hey! Can I ask what database you are using? (eg psql, mysql, mariadb)

**Comment by jancoow** [comment]
Hi. I'm using PostgreSQL database. It's a large production database, so a lot of records on some tables. I was trying to implement something like enable/disable when you click on the row count. Is that a viable solution? I was not sure how to save this metadata per table in some settings file.

**Comment by rathboma** [comment]
Hmm, it should be doing an optimization where it approximates the count. Is it a table or a view?

**Comment by jancoow** [comment]
This is a table. It's a pretty big table; with 100m rows +.  So I'm not surprises it takes some time to count it and introduce a huge load. But I rather not do it on those big tables, especially if it is not needed.

**Comment by jancoow** [comment]
While the feature is added now when viewing a structure, the same thing happens when opening a table to view the data. This will also count all rows now.  Wouldn't it be better to implement the same functionality as here:
https://github.com/beekeeper-studio/beekeeper-studio/commit/e8a42fd79e87c40e5a1f7a3052ef4ec4502fafa7
