### ISSUE TITLE
BUG: Related record button is not working

### ISSUE THREAD

**Issue by wnowicki** [beekeeper-studio/beekeeper-studio#955]
**Describe the bug**
When I'm browsing table content, the redirection button to related records in the other table is not working.

**To Reproduce**
Steps to reproduce the behaviour:
1. Browse any table that you have foreign key relations.
2. Try to access related record by clicking button (as on screenshot)
3. Nothing happens

**Expected behaviour**
I should be redirected to the filtered view of the desired table.

**Screenshots / Gifs**
![image](https://user-images.githubusercontent.com/3448809/148200106-086f58f5-f4b8-4698-8289-6dd6038d8308.png)

**Version Information (please complete the following information):**
 - OS: MacOS 12.1
 - App Version: 3.0.2

**Comment by rathboma** [comment]
Thank you for this! I've fixed in master, pushing out soon
