### ISSUE TITLE
BUG: All queries have tab title of "Query # 1"

### ISSUE THREAD

**Issue by jamerst** [beekeeper-studio/beekeeper-studio#956]
**Describe the bug**
When creating a new query, all queries are labelled "Query # 1", which is confusing. Previously the number would be incremented for each tab opened.

**To Reproduce**
1. Connect to a DB
2. Open a new query
3. Open another query
4. Both queries have the same tab title

**Expected behavior**
The number at the end of the title should be incremented, i.e. "Query # 1", "Query # 2", "Query # 3", etc.

**Screenshots / Gifs**
![image](https://user-images.githubusercontent.com/10601770/148202331-b849ceea-3924-4276-afe0-75241e41a2c1.png)

**Version Information (please complete the following information):**
 - OS: Windows
 - App Version: 3.0.3

**Additional context**
Connected to a SQL Server instance

(The actual titles don't have a space between # and the number, but if I put them together GitHub detects that as a reference to other issues/pull requests)

**Comment by rathboma** [comment]
hah! This is actually a bit funky now we persist tabs (because even blank tabs are persisted). Fixed in master
