### ISSUE TITLE
BUG: On save connection port number reset to default 

### ISSUE THREAD

**Issue by mojtabakaviani** [beekeeper-studio/beekeeper-studio#958]
With new version 3.0.3 of postgres connection if change default port if click save button rest to default port.

OS: windows 11
App Version: 3.0.3
Db: Postgresql

**Comment by rathboma** [comment]
Hey! Thanks for reporting. I can't replicate this. Can you send me some sort of recording to show me the behavior?

If on mac you an use Kap, if Linux, Peek, if Windows the Game bar or Captura.

**Comment by mojtabakaviani** [comment]
https://user-images.githubusercontent.com/1667525/148246290-a8aa23ed-c867-44bd-88b8-e39bc263e04f.mp4

**Comment by mojtabakaviani** [comment]
Not fixed in new version 3.0.5

**Comment by rathboma** [comment]
Thanks! I can replicate now, your video was SUPER helpful

**Comment by rathboma** [comment]
fixed, will release

**Comment by lacek** [comment]
Still got the same problem on 3.4.1

![capture](https://user-images.githubusercontent.com/1272100/163832866-63280b34-5e03-430e-a53a-feafc9770a90.gif)
