### ISSUE TITLE
FEAT: Firebird support

### ISSUE THREAD

**Issue by otaviotscha** [beekeeper-studio/beekeeper-studio#959]
Is it possible to add [Firebird](https://firebirdsql.org/) support?

**Comment by rathboma** [comment]
It's possible! Honestly I've never heard of firebird before.

I'll mark as accepted, but honestly it's probably not going to happen for a while unless we get a lot of upvotes.

**Comment by lucaskorz** [comment]
up

**Comment by luizSilfre** [comment]
up :)
