### ISSUE TITLE
UI Suggestion: Clicking on a table and see its content.

### ISSUE THREAD

**Issue by GeorgeNance** [beekeeper-studio/beekeeper-studio#96]
Similar to how [sequel pro](https://sequelpro.com/) shows data when you click on a table. 

<img width="1118" alt="image" src="https://user-images.githubusercontent.com/3322994/81432658-2a1ce200-9118-11ea-9776-86c2b6db40c7.png">

**Comment by rathboma** [comment]
Honestly I'm torn on what the default table-click behavior should be.

In many cases showing the schema is useful, but in other cases showing the contents is useful.

I'll play with both over the next few weeks and see where I end up :-)

**Comment by rathboma** [comment]
Similar to #64

**Comment by ellisgl** [comment]
Also related to #138

**Comment by rathboma** [comment]
Going to close this issue. This IS a feature, just we're not sure what the default should be, but once we have a settings system this can go in there.

**Comment by lqmanh** [comment]
> Honestly I'm torn on what the default table-click behavior should be.
> 
> In many cases showing the schema is useful, but in other cases showing the contents is useful.
> 
> I'll play with both over the next few weeks and see where I end up :-)

@rathboma, how about both: showing table content AND expanding schema list?

**Comment by UtechtDustin** [comment]
In my opinion the normal click should show the minmal table info (see screenshot above).
The double click should open the table content and there should be a option to toggle the view (schema of the table (coulmns etc.)).
As alternativ there should be a icon while hovering over the table names to open the schema view (similar to the existing icon for the table view)

**Comment by rathboma** [comment]
Current opinion: I think we have it the right way.

Once we have right click menus we can also provide show schema and view data options in there.

I think UI expectations are that clicking on something that expands makes it expand. Maybe were just not communicating that expectation enough.


When writing SQL it's imperative that the sidebar is useful and responsive.

**Comment by ellisgl** [comment]
Here's what I see with SQLYog for refrence:
![image](https://user-images.githubusercontent.com/94559/89826808-6ba89900-db1c-11ea-8fd2-05c560ee4140.png)
![image](https://user-images.githubusercontent.com/94559/89826943-9266cf80-db1c-11ea-829d-f7857f36a566.png)

As you can see, I can click on the table, have the rows, then just do a query and have the results in another tab. This allows me to be go back and forth quickly between what's the in the DB and my results.

**Comment by UtechtDustin** [comment]
@ellisgl 
You can open a query tab for your query (which contains your query and the result) and a tab with the table data.
So in my opinion it works quite good.
