### ISSUE TITLE
BUG: Cannot perform "Close Others" and "Close All"

### ISSUE THREAD

**Issue by gpscl** [beekeeper-studio/beekeeper-studio#960]
**Describe the bug**
After opening many tabs, then want to perform "Close Others" and "Close All" nothing happens.

**To Reproduce**
1. Try to open many tabs
2. Then click "Close Others" or "Close All"
3. Nothing happens

**Expected behavior**
Either close all tabs or leave 1 tab

**Screenshots / Gifs**
![Screen Recording 2022-01-06 at 08 57 44](https://user-images.githubusercontent.com/86280607/148316256-c65db27a-343f-4814-a354-15226c523d06.gif)

**Version Information (please complete the following information):**
 - OS: Mac (M1)
 - App Version 3.0.7

**Additional context**
Before update, it works fine

**Comment by joshuapack** [comment]
I added a merge request to fix this issue.

**Comment by rathboma** [comment]
this is fixed!
