### ISSUE TITLE
General Feedback

### ISSUE THREAD

**Issue by epiqu1n** [beekeeper-studio/beekeeper-studio#966]
No question, but I couldn't find anywhere else to leave feedback. Just wanted to say thank you all for making such a sleek, efficient, and well-built SQL client - and for free at that. There's no other free SQL client (perhaps even paid) that I've found that even comes close to the quality and clean UI of Beekeeper Studio, and that is greatly appreciated by an amateur developer.

Thank you and keep up the good work!

**Comment by rathboma** [comment]
Thank you so much for the kind words! I'm going to close this as it's not really a feature request, but I definitely enjoyed reading it, thank you!
