### ISSUE TITLE
QUESTION: Table information not displayed correctly in sidebar

### ISSUE THREAD

**Issue by DiracSpace** [beekeeper-studio/beekeeper-studio#970]
**Details:**
I'm connecting to localhost where I have multiple databases with various tables. These were created with Entity Framework Core via Visual Studio and .NET, the issue being that other table information is being displayed. For example, there is a database called `Example.db` with a table called `dbo.Example` but the app displays `spt_monitor`.

**Version Information [might be relevant to your issue]**
Operating System: Windows
App Version [help -> about]: `Beekeeper Studio 3.0.7 Beekeeper Studio Team`

**Screenshot / GIF [if appropriate]**:

`Beekeeper`

![image](https://user-images.githubusercontent.com/49464343/148784399-e0d356e0-ff44-4192-9f69-f4607f713332.png)

`Microsoft SQL Server Management Studio`

![image](https://user-images.githubusercontent.com/49464343/148784530-3da9990a-ed33-482f-ae0e-8ba436594bd9.png)

I'd like to know if there is an extra configuration step for displaying the table names correctly.

**Comment by rathboma** [comment]
Interesting. Are they not displaying at all? Even when the same database is selected in the dropdown?

**Comment by DiracSpace** [comment]
No, in the documentation I selected the proper database in my localhost instance of SQL Server but it isn't displaying the correct database table names nor information. I suppose it could be something to do with them being created with an ORM and not SQL

**Comment by rathboma** [comment]
No it shouldn't make any difference.

Can you check your ORM is not using [LocalDB](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/sql-server-express-localdb?view=sql-server-ver15), which is sort of like SQL Server, but does not expose a TCP port?

That's the only thing I can think about without being able to replicate.

Other things to check:
- Can you see if there are any errors in the dev console? [help -> show dev console]

**Comment by DiracSpace** [comment]
> Can you check your ORM is not using [LocalDB](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/sql-server-express-localdb?view=sql-server-ver15), which is sort of like SQL Server, but does not expose a TCP port?

According to the following article, [Entity Framework Core (EF) with SQL Server LocalDB
](https://codemurals.blogspot.com/2021/05/entity-framework-core-ef-with-sql.html) it could be using it. What do you suggest I do? The connection strings are correct.

> * Can you see if there are any errors in the dev console? [help -> show dev console]

![image](https://user-images.githubusercontent.com/49464343/149801792-2007156b-8e1a-407e-a950-f8c67ac9a153.png)

**Comment by rathboma** [comment]
So looks like you have sql server itself running AND you are using localdb, they're actually totally different things.

Beekeeper has no way to connect to localdb as Microsoft doesn't provide compatibility in their nodejs drivers unfortunately.

So either you have to use regular sql server for your orm, or you are unable to use beekeeper I'm afraid :-(

**Comment by rathboma** [comment]
Going to close this ticket as it's not really something I can resolve very easily

**Comment by DiracSpace** [comment]
> So either you have to use regular sql server for your orm, or you are unable to use beekeeper I'm afraid :-(

Aw, that's really sad but thank you for your time in resolving my question. 😢
