### ISSUE TITLE
FEAT: Better Error Messages

### ISSUE THREAD

**Issue by GammaGames** [beekeeper-studio/beekeeper-studio#974]
I love Beekeeper Studio, but its error reporting when a query fails isn't great. It should have the full reason _why_ the error happened.

Let's compare:

| Beekeeper                                                                                                      | DBeaver                                                                                                        |
|----------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------|
| ![image](https://user-images.githubusercontent.com/7832163/149203988-42ce4457-dcb6-44d8-ad14-af1e11ae29bd.png) | ![image](https://user-images.githubusercontent.com/7832163/149204164-a1fba195-88e7-40dc-9610-d14a31f8043f.png) |

DBeaver also moves your cursor to the location of the error, making it easy to find the problem when working with larger queries. That would be nice, but any extra information about the error is helpful compared to what we get now.

**Comment by rathboma** [comment]
Yes we need better error messages for sure. Can you help me by answering a couple of questions? That way I can see if the driver is providing more information that I can surface:

- What database is this (eg psql, mysql)
- Can you give me an example broken query I can use for testing?

**Comment by GammaGames** [comment]
I'm using postgresql, and my query was pretty large and gnarly but it was essentially:

```sql
SELECT \'test\';
```

So the syntax was broken (the query was copied from a PHP file), but the error still could have been more informative :p
