### ISSUE TITLE
BUG: Right click -> create table not working

### ISSUE THREAD

**Issue by mefjak** [beekeeper-studio/beekeeper-studio#975]
Hi,

I have to issues with creating scripts for tables for Postgresql.
1) I cant create script where tables are witch capital letters like "XX_Table" (ofcourse query is select * from "XX_Table" ;) )
2) When generating script for regular table like table_name there are no default values for columns - is that by design ?

**Comment by rathboma** [comment]
Can I ask what you mean when you say you cannot create a script? Do you mean the script does not run?

2. Generating script - do you mean generating the `create table` script from the sidebar?

**Comment by rathboma** [comment]
If you can provide screenshots of what you are clicking that doesn't work, that'd be very useful

**Comment by mefjak** [comment]
Ok so to be sure after updating today BS creating tables is working but using CREATE commnad doeas nothing

**Comment by mefjak** [comment]
So in console there is this error which suggests that SQL:Create is not case sensitive ;)
![image](https://user-images.githubusercontent.com/22888465/149900760-6e1e9fe6-20da-41df-8d2c-64de380125e1.png)
