### ISSUE TITLE
BUG: Code Completion doesn't autocomplete schemaname or schemaname.tablename

### ISSUE THREAD

**Issue by bsnyderm** [beekeeper-studio/beekeeper-studio#976]
I am connected to my database which has roughly 1200 objects and about 20 schemas.  The objects load and then are displayed on the left navigation window listing tables, functions etc.

I type out the following in the sql editor:

select * from schema.tablename;

While I am typing, my expectation is that as soon as I start typing "schema", I would be provided recommendations of schema.  It does provide recommendations for table, but I do not like setting my search_path so I like code sql with the full declaration of schema.tablename.  And after I type "schema." there are no tablename recommendations.

I like your app, but this is my main issue with postgres sql tools.  Looks good and I will continue to follow your app.

Also, when I right click on a function in the navigation window and select SQL:Create, nothing happens where I would expect it to open the DDL in a tab.

SYSTEM : Ubuntu 20.04
BEEKEEPER : 3.0.7

**Comment by mefjak** [comment]
Hi, 

I have the same problem with DDL SLQ:Create command on gui - but I only have it when tables has capital letters  - becouse as I understand psql is case-sensitive so if my table is "XXX_Something" DDL menu don't work, but if its "xxx_something" it generates code for creating table - maybe you have the same issue ?

cheers

**Comment by bsnyderm** [comment]
I just checked and the function name is all lowercase and no sql is generated.  We have all of our object lowercase.  The table shows the ddl however the function does not.

I originally did not test the tables so it looks like that works fine, just the functions.

Thanks, have a great weekend

**Comment by mefjak** [comment]
Hi, thx and hope you had great weekend too.

I've just checked as to creating simple function and it worked Ok...

Windows 10 : BS 3.0.11

**Comment by joaoprp** [comment]
@mefjak I don't think you're getting the issue here. Let's get as an example the `postgres` database. Inside it, we have two schemas: `information_schema` and `pg_catalog`.

When I start typing `in` to get auto-completion, this is what I get:

<img width="458" alt="image" src="https://user-images.githubusercontent.com/1233127/150586564-f2a135b8-6335-4fd9-8079-b7c4b9c8fb17.png">

Which isn't correct in any means. Then it goes worse. Let's say I choose to use `information_schema`, which has those tables:

<img width="268" alt="image" src="https://user-images.githubusercontent.com/1233127/150586738-3c51cb53-fde7-45e0-9b4b-e90d49228989.png">

if I try to get into `information_schema.sql_parts`, there's no autocomplete whatsoever:

<img width="384" alt="image" src="https://user-images.githubusercontent.com/1233127/150586827-9ca3d7bb-6d7e-4bec-952e-985f8c86fdf8.png">

And this is detrimental to Postgres users, as they _must_ use schema.

**Comment by rathboma** [comment]
Hey everyone. Yes you are right, it doesn't autocomplete schema name at all right not. It is terrible UX. I definitely appreciate that.

I'm currently using a very naive autocomplete system. I'd hoped to build a full language model to solve these types of issues, but I've heard this complaint enough that I'll take a look to see what I can do.

Thanks for all the community engagement on the app! I'm a one-man part-timer, so please be patient, but I'll get these issues sorted out :-)

**Comment by joaoprp** [comment]
@rathboma I forked the code this weekend and found the hint solution for that, but didn't have much time to pry out much more info yet. Question (or let me know where should I talk about it on a discord or something): when I'm under `TabQueryEditor.vue`, is there a way to know the query I'm working on? I see how to put the schema rendering inside `hintOptions()` but I think it's best to build a content-aware recommendation based on it.

If you can point me out one this, that would be great, so I can try to work on that over this weekend and see if I can get some out of it to help out the project :)

**Comment by mefjak** [comment]
@joaoprp thx for clearing that up.

Autocomplition is somewhat working :

![inteli](https://user-images.githubusercontent.com/22888465/151135037-83b9bb13-338d-4953-911b-84173a7249cc.gif)

And with schema it isn't - it sees all tables in all schemas but after writing manual schema it doesn't autocomplite as you can see - that moment where there is "select * from test." I am trying ctrl+space ;)
![inteli2](https://user-images.githubusercontent.com/22888465/151135392-ed144106-2cc1-47c6-b22d-39b6dd5f3316.gif)

Just trying to provide some use cases ;)

**Comment by mintsoft** [comment]
IIRC (it's been a while) I think I worked around this by making the postgresql autocomplete use the schema always: https://github.com/beekeeper-studio/beekeeper-studio/pull/582/files

**Comment by hovanessb** [comment]
Is there a PR for this and do you need help with this?
