### ISSUE TITLE
BUG: Can't query SQLite db using a STRICT table

### ISSUE THREAD

**Issue by bbkane** [beekeeper-studio/beekeeper-studio#991]
**Describe the bug**

Beekeeper Studio can't process tables using SQLite's new [STRICT syntax](https://www.sqlite.org/stricttables.html).

**To Reproduce**

Create a db using a strict table and demo querying it:

```bash
$ sqlite3 --version
3.37.0 2021-11-27 14:13:22 bd41822c7424d393a30e92ff6cb254d25c26769889c1499a18a0b9339f5d6c8a
```

```bash
$ echo "CREATE TABLE mytable(id INTEGER NOT NULL PRIMARY KEY, name TEXT) STRICT; INSERT INTO mytable(name) VALUES('bob')" | sqlite3 tmp.db
```

```bash
$ sqlite3 tmp.db 'SELECT * FROM mytable'
1|bob
```

Open in BeeKeeper Studio and try to query:

![image](https://user-images.githubusercontent.com/6081085/150625085-321fce2c-7570-46c6-b82e-5f42c5d4e06c.png)

**Expected behavior**

The query works and I can see the table I created in the left column.

**Screenshots / Gifs**

See above :)

**Version Information (please complete the following information):**
 - OS: macOS Monterey - Version 12.1
 - App Version: Version 3.0.11

**Additional context**
Anything else you think might be helpful

**Comment by rathboma** [comment]
Oh no! Thank you so much for the bug report. I'll definitely look into this.

**Comment by bbkane** [comment]
@rathboma , did your investigation turn up anything here?

**Comment by rathboma** [comment]
I think you are a mind-reader as I was testing the sqlite upgrade over the weekend.

![image](https://user-images.githubusercontent.com/279769/157155048-aa85787a-2992-4dab-bedb-5556e44352a7.png)

Will be in the next release

**Comment by bbkane** [comment]
Oh this is wonderful! Thank you!!

**Comment by bbkane** [comment]
I assume this fix will land in the next release - can you estimate when the next release will land or (even better) is there a public release schedule or list of issues until the next release?

**Comment by rathboma** [comment]
I'm putting the release together today!
