### ISSUE TITLE
Help Needed: Beekeeper Studio User Survey - Win $100 GC

### ISSUE THREAD

**Issue by rathboma** [beekeeper-studio/beekeeper-studio#994]
I'm trying to learn more about you and why you use (or used to use) Beekeeper Studio. I hope some of you have time to complete a quick survey, it should only take a few minutes, no personal details required.

### Why would I complete your survey?

Beekeeper Studio is run by a one-man development team (me). My time is tight. If I can understand who is using Beekeeper Studio, and why they are using it, it will really help me figure out what features are important!

...Also, two people (picked randomly from respondents) will win a $100 Amazon gift card 😁.

**Comment by mefjak** [comment]
Done. Keep up the good work :)
