### ISSUE TITLE
BUG: Program crashes when switching database in same postgres server and a table from old schema is open as a tab

### ISSUE THREAD

**Issue by Gabb1995** [beekeeper-studio/beekeeper-studio#998]
**Describe the bug**
Unresponsive program when switching schemas on same postgres server.

**To Reproduce**
1. Have a postgres server with multiple schemas
2. Open a table from schema 1
3. Open schema 2 from the dropdown
4. An error should show under the opened table tab, called this table does not exist
5. Press the button "Close Tab"
6. Error occurs in the console
7. UI becomes unresponsive completely cannot change schema, disconnect or anything

**Expected behavior**
Changing schema should work without crashing the app when a tab is open from the old schema.

**Screenshots / Gifs**
![Screenshot from 2022-01-25 13:51:16](https://user-images.githubusercontent.com/20728259/150980213-c013c540-8327-4bde-b5f5-122b9813853e.png)

![Screenshot from 2022-01-25 13:47:07](https://user-images.githubusercontent.com/20728259/150979601-29ab010b-70a5-47d9-aaa7-53e6dcadd5d4.png)
 

**Version Information (please complete the following information):**
 - OS: Ubuntu 21.10 x86_64
 - App Version: 3.0.3
 - Database type and version: Postgres 13.4

**Comment by rathboma** [comment]
Ah! Let me take a look at that. Thanks for the bug report!

**Comment by rathboma** [comment]
This is fixed!
